// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// The CLI flag manifest — a committed, generated list of every flag sluice
// accepts, and the gate that keeps it honest.
//
// It exists because the published command reference had silently fallen 85
// flags behind the binary, including flags OTHER published pages already link
// to (`--skip-foreign-keys` is referenced by the PlanetScale region-move guide
// and appears nowhere in the reference). Nobody noticed because nothing could:
// the reference is hand-written prose on a separate site, and prose cannot be
// diffed against a Go struct by hand.
//
// This file makes the flag set MACHINE-READABLE and versioned, so the drift
// becomes a file diff a human sees in review rather than a discovery years
// later. The manifest is derived from KONG ITSELF — the same model the binary
// parses, walked through kong's own grammar — never from regexes over struct
// tags, so it cannot disagree with what the binary actually accepts.
//
// Two consumers:
//
//   - This test, which fails when the manifest is stale. Adding a flag means
//     regenerating it (SLUICE_UPDATE_CLI_MANIFEST=1 go test ./cmd/sluice/),
//     which puts the new flag in a reviewable diff.
//   - sluicesync.com's build, whose own drift check reads this file and holds
//     the published command reference to it. That is the check that would have
//     caught the 85.

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/alecthomas/kong"
)

// cliFlagManifestPath is the committed manifest, relative to this package.
const cliFlagManifestPath = "../../docs/dev/cli-flags.txt"

// collectCLIFlags walks the kong model and returns every flag as
// "<command path> --<flag>", sorted. The command path is empty for a global
// flag, so a global sorts first and reads unambiguously.
//
// Walking kong's model rather than the Go source is the load-bearing choice:
// kong applies the name derivation (field name → kebab-case, overridden by a
// `name:` tag), the embedding rules, and the per-subcommand grouping. A regex
// over struct tags would have to reimplement all three and would drift from
// the parser the binary actually uses — which is the exact failure this file
// exists to prevent, one level down.
func collectCLIFlags(t *testing.T) []string {
	t.Helper()

	parser, err := kong.New(
		&CLI{},
		kong.Name("sluice"),
		kong.Description("Open-source database migration and continuous-sync tool."),
		kong.Vars{"version": "test"},
	)
	if err != nil {
		t.Fatalf("build kong model: %v", err)
	}

	seen := map[string]bool{}
	var out []string

	add := func(path string, f *kong.Flag) {
		if f == nil || f.Name == "" || f.Hidden {
			return
		}
		entry := strings.TrimSpace(path + " --" + f.Name)
		if seen[entry] {
			return
		}
		seen[entry] = true
		out = append(out, entry)
	}

	var walk func(node *kong.Node, path string)
	walk = func(node *kong.Node, path string) {
		for _, f := range node.Flags {
			add(path, f)
		}
		for _, child := range node.Children {
			if child == nil {
				continue
			}
			childPath := strings.TrimSpace(path + " " + child.Name)
			walk(child, childPath)
		}
	}
	walk(parser.Model.Node, "")

	sort.Strings(out)
	return out
}

// TestCLIFlagManifestIsCurrent is the gate.
func TestCLIFlagManifestIsCurrent(t *testing.T) {
	flags := collectCLIFlags(t)
	if len(flags) == 0 {
		t.Fatal("collected zero flags — the kong walk broke, and an empty manifest would agree with " +
			"any command reference")
	}

	want := strings.Join(flags, "\n") + "\n"
	header := "# Generated by cmd/sluice/cli_flag_manifest_test.go — do not edit by hand.\n" +
		"# Regenerate: SLUICE_UPDATE_CLI_MANIFEST=1 go test ./cmd/sluice/ -run TestCLIFlagManifest\n" +
		"#\n" +
		"# One line per flag, as \"<command path> --<flag>\"; a global flag has an empty path.\n" +
		"# sluicesync.com's build diffs its published command reference against this file.\n"
	want = header + want

	path := filepath.Clean(cliFlagManifestPath)
	if os.Getenv("SLUICE_UPDATE_CLI_MANIFEST") != "" {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatalf("mkdir: %v", err)
		}
		if err := os.WriteFile(path, []byte(want), 0o644); err != nil {
			t.Fatalf("write manifest: %v", err)
		}
		t.Logf("regenerated %s (%d flags)", path, len(flags))
		return
	}

	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v\n\nRegenerate with:\n  SLUICE_UPDATE_CLI_MANIFEST=1 go test ./cmd/sluice/ -run TestCLIFlagManifest",
			path, err)
	}

	if string(got) != want {
		t.Errorf("the CLI flag manifest is stale — the binary accepts a different flag set than %s records.\n\n"+
			"%s\n\n"+
			"Regenerate and review the diff:\n"+
			"  SLUICE_UPDATE_CLI_MANIFEST=1 go test ./cmd/sluice/ -run TestCLIFlagManifest\n\n"+
			"If the diff ADDS a flag, the published command reference at sluicesync.com/docs/commands/ "+
			"needs a row for it too — that reference had fallen 85 flags behind before this manifest "+
			"existed, and the site's own build check reads this file.",
			path, firstManifestDiff(string(got), want))
	}
}

// firstManifestDiff reports the first differing line, so a stale manifest
// names the flag rather than dumping two hundred lines at the reader.
func firstManifestDiff(got, want string) string {
	g := strings.Split(got, "\n")
	w := strings.Split(want, "\n")
	for i := 0; i < len(g) || i < len(w); i++ {
		var gl, wl string
		if i < len(g) {
			gl = g[i]
		}
		if i < len(w) {
			wl = w[i]
		}
		if gl != wl {
			return fmt.Sprintf("first difference at line %d:\n  committed: %q\n  actual:    %q", i+1, gl, wl)
		}
	}
	return "files differ only in trailing content"
}
