// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

package backup

// The corpus dump-parity allowlists (roadmap item 52 × item 51): the
// single reviewable answer to "what does sluice knowingly not carry
// when the item-51 restore-parity oracle is pointed at the item-52
// real-world corpus schemas?"
//
// These are SEPARATE from DumpParityAllowlist / DumpParityAllowlistMySQL
// (the kitchen-sink lists) on purpose. The kitchen-sink lists are keyed
// to the seed's specific object names ("CREATE TABLE public.orders",
// "CREATE SEQUENCE public.legacy_counters_id_seq"); the corpus schemas
// are real applications with arbitrary object names, so the corpus lists
// match by statement CLASS (glob over the object-identity KEY) so one
// entry holds across every corpus member. Every entry cites the
// doc/ADR/source that declares the degradation, or carries the
// DumpParityTriageCitation marker for a latent gap the oracle found that
// has NOT been triaged into a documented decision yet — same discipline
// as the kitchen-sink lists.
//
// Patterns match statement KEYS (see dumpStatementKey / the MySQL
// element keyer) under path.Match glob semantics via the shared
// MatchDumpParityAllowlist. First match wins — keep entries
// most-specific-first. Every hit is logged in the harness output so the
// active list is visible in CI logs.

// DumpParityCorpusAllowlistPG covers the generic same-engine PG → PG
// degradations sluice applies to any real schema.
var DumpParityCorpusAllowlistPG = []dumpParityAllowlistEntry{
	{
		Pattern:  "*sluice_migrate_*",
		Reason:   "sluice's own per-target migrate-state tables (resume machinery); operational metadata, not migrated schema",
		Citation: "internal/pipeline/resume.go",
	},
	// Serial → identity modernization (docs/type-mapping.md "Sequences and
	// serial columns"), surfaced by MediaWiki's ~30 classic serial columns.
	// sluice reads a source serial column and emits a PG IDENTITY column
	// instead, so pg_dump of the source restores three artefacts the
	// identity target does not carry: the backing CREATE SEQUENCE, its
	// ALTER SEQUENCE … OWNED BY binding, and the ALTER TABLE … ALTER COLUMN
	// … SET DEFAULT nextval() (sluice emits ADD GENERATED … AS IDENTITY
	// under the SAME key, so that one is a mismatch). Insert behaviour is
	// identical; the catalog text is not. This is the kitchen-sink's
	// legacy_counters trio generalized to the corpus's arbitrary names.
	{
		Pattern:  "CREATE SEQUENCE public.*_seq",
		Reason:   "oracle side only: the backing sequence pg_dump re-creates for a classic serial column that sluice modernizes to an identity column (scoped to pg_dump's `<table>_<col>_seq` serial naming so a differently-named standalone sequence still surfaces)",
		Citation: "docs/type-mapping.md \"Sequences and serial columns\"",
	},
	{
		Pattern:  "ALTER SEQUENCE public.* OWNED",
		Reason:   "oracle side only: the OWNED BY binding of a serial backing sequence; a standalone sequence is never OWNED BY a column, so this cannot mask a dropped standalone sequence",
		Citation: "docs/type-mapping.md \"Sequences and serial columns\"",
	},
	{
		Pattern:  "ALTER TABLE public.* ALTER COLUMN *",
		Reason:   "serial column default: oracle side SET DEFAULT nextval(...), sluice side ADD GENERATED BY DEFAULT AS IDENTITY — the modernization's catalog-visible face; pg_dump --schema-only emits ALTER COLUMN only for column defaults/identity, so the masked class is bounded",
		Citation: "docs/type-mapping.md \"Sequences and serial columns\"",
	},
}

// DumpParityCorpusAllowlistMySQL covers the generic same-engine
// MySQL → MySQL degradations sluice applies to any real schema.
var DumpParityCorpusAllowlistMySQL = []dumpParityAllowlistEntry{
	{
		Pattern:  "*sluice_migrate_*",
		Reason:   "sluice's own per-target migrate-state tables (resume machinery: sluice_migrate_state + sluice_migrate_table_progress); operational metadata, not migrated schema",
		Citation: "internal/engines/mysql/migration_state.go",
	},
}
