//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// Integration test for the ADR-0051 / research-finding-F5 source-
// identity pin. Boots a Postgres container, runs a real cold-start
// to capture a position whose token now carries (systemid, timeline),
// then exercises both the happy-path (resume against the same source
// passes) and the divergence path (resume with a tampered systemid /
// timeline refuses loudly with an ir.ErrPositionInvalid-wrapped
// error). A live PITR or standby promotion can't be cleanly wired up
// in testcontainers, but a tampered persisted-position token
// exercises the same divergence-detection code path: the comparison
// in checkSourceIdentity doesn't care whether the divergence came
// from a real PITR or from a doctored token — it cares that the
// persisted pin disagrees with what IDENTIFY_SYSTEM now reports.

package postgres

import (
	"context"
	"encoding/json"
	"errors"
	"strings"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/ir"
)

// TestCDCReader_SourceIdentityPin_HappyPathResume confirms that a
// position captured from a real PG container carries the (systemid,
// timeline) pin and that resuming with that exact pin succeeds —
// i.e. the pin doesn't accidentally refuse on its own database.
//
// This is the positive control for the divergence-refusal test
// below: if the pin were over-strict (rejecting matched pins), this
// test would fail.
func TestCDCReader_SourceIdentityPin_HappyPathResume(t *testing.T) {
	dsn, cleanup := startPostgresForCDC(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL
		);
		ALTER TABLE users REPLICA IDENTITY FULL;
	`
	applyPGSQL(t, dsn, seedDDL)

	eng := Engine{}

	// Stage 1: cold-start, emit an event, capture its position.
	ctx1, cancel1 := context.WithTimeout(context.Background(), 60*time.Second)
	rdr1, err := eng.OpenCDCReader(ctx1, dsn)
	if err != nil {
		cancel1()
		t.Fatalf("OpenCDCReader (stage 1): %v", err)
	}
	changes1, err := rdr1.StreamChanges(ctx1, ir.Position{})
	if err != nil {
		cancel1()
		t.Fatalf("StreamChanges (stage 1): %v", err)
	}
	time.Sleep(200 * time.Millisecond)
	applyPGSQL(t, dsn, `INSERT INTO users (email) VALUES ('alice@example.com');`)
	got := drainChanges(t, ctx1, changes1, 1, 30*time.Second)
	if len(got) != 1 {
		cancel1()
		t.Fatalf("stage 1: got %d changes; want 1", len(got))
	}
	capturedPos := got[0].Pos()
	if c, ok := rdr1.(interface{ Close() error }); ok {
		_ = c.Close()
	}
	// Cancel ctx1 + wait for the slot to go inactive before opening
	// stage 2. PG's `START_REPLICATION` refuses with SQLSTATE 55006
	// (`replication slot ... is active for PID N`) if the prior
	// session's walsender hasn't released the slot yet. Close() returns
	// before PG's backend cleanup observes the disconnect; without this
	// drain, stage 2 races against PG's housekeeping and fails
	// non-deterministically on CI.
	cancel1()
	waitForSlotInactive(t, dsn, "sluice_slot", 30*time.Second)

	// Sanity check: the captured position MUST carry the source-identity
	// pin. If this fails, positionAt isn't propagating r.systemID /
	// r.timeline onto emitted changes — the rest of the divergence-
	// refusal flow would then be a no-op (lazy-install would silently
	// engage on every resume).
	decoded, ok, err := decodePGPos(capturedPos)
	if err != nil || !ok {
		t.Fatalf("decode captured position: ok=%v err=%v", ok, err)
	}
	if decoded.SystemID == "" {
		t.Fatal("captured position has empty SystemID — pin is not being emitted")
	}
	if decoded.Timeline == 0 {
		t.Fatal("captured position has zero Timeline — pin is not being emitted")
	}

	// Stage 2: resume against the SAME container with the captured
	// position. The pin matches the source, so resume must succeed.
	ctx2, cancel2 := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel2()
	rdr2, err := eng.OpenCDCReader(ctx2, dsn)
	if err != nil {
		t.Fatalf("OpenCDCReader (stage 2): %v", err)
	}
	defer func() {
		if c, ok := rdr2.(interface{ Close() error }); ok {
			_ = c.Close()
		}
	}()
	changes2, err := rdr2.StreamChanges(ctx2, capturedPos)
	if err != nil {
		t.Fatalf("StreamChanges (stage 2, matched pin) must succeed; got %v", err)
	}
	// Generate one more event so we can confirm the stream is alive.
	time.Sleep(200 * time.Millisecond)
	applyPGSQL(t, dsn, `INSERT INTO users (email) VALUES ('bob@example.com');`)
	got2 := drainChanges(t, ctx2, changes2, 1, 30*time.Second)
	if len(got2) != 1 {
		t.Fatalf("stage 2: got %d changes; want 1 (matched-pin resume should stream normally)", len(got2))
	}
	// And confirm the new position still carries the pin.
	decoded2, ok, err := decodePGPos(got2[0].Pos())
	if err != nil || !ok {
		t.Fatalf("decode stage-2 position: ok=%v err=%v", ok, err)
	}
	if decoded2.SystemID != decoded.SystemID {
		t.Errorf("stage-2 emitted position has SystemID=%q; want %q (same source)", decoded2.SystemID, decoded.SystemID)
	}
	if decoded2.Timeline != decoded.Timeline {
		t.Errorf("stage-2 emitted position has Timeline=%d; want %d (same source)", decoded2.Timeline, decoded.Timeline)
	}
}

// TestCDCReader_SourceIdentityPin_DivergenceRefusesLoud is the
// silent-loss closure: a persisted position whose (systemid,
// timeline) disagrees with what IDENTIFY_SYSTEM now reports MUST be
// refused, and the refusal MUST wrap ir.ErrPositionInvalid so the
// pipeline streamer's ADR-0022 fall-through routes to cold-start
// rather than silently advancing the slot against the wrong
// timeline.
//
// The divergence is simulated by tampering with a real captured
// position's systemid (the SystemID field in the JSON token). This
// exercises the same code path a real source-side PITR or standby
// promotion would: checkSourceIdentity sees persisted != live and
// returns the loud error. A live PITR/promotion wired up in
// testcontainers would be heavier without exercising additional
// surface — the comparison is the load-bearing logic and we test
// the comparison directly.
func TestCDCReader_SourceIdentityPin_DivergenceRefusesLoud(t *testing.T) {
	dsn, cleanup := startPostgresForCDC(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL
		);
		ALTER TABLE users REPLICA IDENTITY FULL;
	`
	applyPGSQL(t, dsn, seedDDL)

	eng := Engine{}

	// Cold-start to obtain a real, pin-carrying position.
	ctx1, cancel1 := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel1()
	rdr1, err := eng.OpenCDCReader(ctx1, dsn)
	if err != nil {
		t.Fatalf("OpenCDCReader (cold-start): %v", err)
	}
	changes1, err := rdr1.StreamChanges(ctx1, ir.Position{})
	if err != nil {
		t.Fatalf("StreamChanges (cold-start): %v", err)
	}
	time.Sleep(200 * time.Millisecond)
	applyPGSQL(t, dsn, `INSERT INTO users (email) VALUES ('alice@example.com');`)
	got := drainChanges(t, ctx1, changes1, 1, 30*time.Second)
	if len(got) != 1 {
		t.Fatalf("cold-start: got %d changes; want 1", len(got))
	}
	captured := got[0].Pos()
	if c, ok := rdr1.(interface{ Close() error }); ok {
		_ = c.Close()
	}
	cancel1()
	waitForSlotInactive(t, dsn, "sluice_slot", 30*time.Second)

	decoded, ok, err := decodePGPos(captured)
	if err != nil || !ok {
		t.Fatalf("decode captured position: ok=%v err=%v", ok, err)
	}
	if decoded.SystemID == "" {
		t.Fatal("captured position has empty SystemID — cannot tamper a missing field")
	}

	// Tamper the SystemID — append a digit. This simulates a source
	// whose identity has changed (e.g. PITR clone with a new sysid,
	// or sluice was pointed at the wrong instance).
	tampered := decoded
	tampered.SystemID = decoded.SystemID + "0"
	tamperedToken, err := json.Marshal(tampered)
	if err != nil {
		t.Fatalf("marshal tampered token: %v", err)
	}
	tamperedPos := ir.Position{Engine: engineNamePostgres, Token: string(tamperedToken)}

	// Stage 2: resume with the tampered position. Must refuse loudly.
	ctx2, cancel2 := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel2()
	rdr2, err := eng.OpenCDCReader(ctx2, dsn)
	if err != nil {
		t.Fatalf("OpenCDCReader (tampered resume): %v", err)
	}
	defer func() {
		if c, ok := rdr2.(interface{ Close() error }); ok {
			_ = c.Close()
		}
	}()
	_, err = rdr2.StreamChanges(ctx2, tamperedPos)
	if err == nil {
		t.Fatal("StreamChanges with diverged sysid must refuse; got nil error")
	}
	if !errors.Is(err, ir.ErrPositionInvalid) {
		t.Errorf("error must wrap ir.ErrPositionInvalid so the streamer ADR-0022 fall-through engages; got: %v", err)
	}
	if !strings.Contains(err.Error(), "source identity has changed") {
		t.Errorf("error must say 'source identity has changed'; got: %v", err)
	}
	if !strings.Contains(err.Error(), tampered.SystemID) {
		t.Errorf("error must name the persisted SystemID for diagnostics; got: %v", err)
	}
	if !strings.Contains(err.Error(), decoded.SystemID) {
		t.Errorf("error must name the live SystemID for diagnostics; got: %v", err)
	}

	// Stage 3: resume with the un-tampered position. Must succeed —
	// confirms the refusal is specific to divergence, not a regression
	// where every resume now refuses.
	ctx3, cancel3 := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel3()
	rdr3, err := eng.OpenCDCReader(ctx3, dsn)
	if err != nil {
		t.Fatalf("OpenCDCReader (un-tampered resume): %v", err)
	}
	defer func() {
		if c, ok := rdr3.(interface{ Close() error }); ok {
			_ = c.Close()
		}
	}()
	if _, err := rdr3.StreamChanges(ctx3, captured); err != nil {
		t.Errorf("StreamChanges with un-tampered position must succeed; got %v", err)
	}
}

// TestCDCReader_SourceIdentityPin_LegacyPositionLazyInstalls confirms
// the additive-field promise from the operator's point of view: a
// position persisted by pre-ADR-0051 sluice (no SystemID, no
// Timeline) must NOT be refused on the first reconnect. The pin is
// installed lazily — the position is accepted, a one-time INFO log
// fires, and the next emitted position carries the live pin so
// subsequent reconnects engage divergence detection.
func TestCDCReader_SourceIdentityPin_LegacyPositionLazyInstalls(t *testing.T) {
	dsn, cleanup := startPostgresForCDC(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL
		);
		ALTER TABLE users REPLICA IDENTITY FULL;
	`
	applyPGSQL(t, dsn, seedDDL)

	eng := Engine{}

	// Cold-start to get a real position, then capture just the LSN
	// and re-serialize WITHOUT systemid/timeline — a pre-ADR-0051
	// token shape.
	ctx1, cancel1 := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel1()
	rdr1, err := eng.OpenCDCReader(ctx1, dsn)
	if err != nil {
		t.Fatalf("OpenCDCReader (cold-start): %v", err)
	}
	changes1, err := rdr1.StreamChanges(ctx1, ir.Position{})
	if err != nil {
		t.Fatalf("StreamChanges (cold-start): %v", err)
	}
	time.Sleep(200 * time.Millisecond)
	applyPGSQL(t, dsn, `INSERT INTO users (email) VALUES ('alice@example.com');`)
	got := drainChanges(t, ctx1, changes1, 1, 30*time.Second)
	if len(got) != 1 {
		t.Fatalf("cold-start: got %d changes; want 1", len(got))
	}
	captured := got[0].Pos()
	if c, ok := rdr1.(interface{ Close() error }); ok {
		_ = c.Close()
	}
	cancel1()
	waitForSlotInactive(t, dsn, "sluice_slot", 30*time.Second)
	decoded, ok, err := decodePGPos(captured)
	if err != nil || !ok {
		t.Fatalf("decode captured position: ok=%v err=%v", ok, err)
	}

	// Re-serialize WITHOUT the pin fields — mimics what pre-ADR-0051
	// sluice persisted. Hand-crafted JSON (rather than struct
	// marshalling with zero-value fields) to be explicit that the
	// keys are absent, not just zero-valued.
	legacyToken := `{"slot":"` + decoded.Slot + `","lsn":"` + decoded.LSN + `"}`
	legacyPos := ir.Position{Engine: engineNamePostgres, Token: legacyToken}

	// Resume with the legacy-shape position. Must succeed; subsequent
	// emitted changes must carry the now-installed pin.
	ctx2, cancel2 := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel2()
	rdr2, err := eng.OpenCDCReader(ctx2, dsn)
	if err != nil {
		t.Fatalf("OpenCDCReader (legacy resume): %v", err)
	}
	defer func() {
		if c, ok := rdr2.(interface{ Close() error }); ok {
			_ = c.Close()
		}
	}()
	changes2, err := rdr2.StreamChanges(ctx2, legacyPos)
	if err != nil {
		t.Fatalf("StreamChanges with legacy (pre-ADR-0051) position must succeed; got %v", err)
	}
	time.Sleep(200 * time.Millisecond)
	applyPGSQL(t, dsn, `INSERT INTO users (email) VALUES ('bob@example.com');`)
	got2 := drainChanges(t, ctx2, changes2, 1, 30*time.Second)
	if len(got2) != 1 {
		t.Fatalf("legacy resume: got %d changes; want 1", len(got2))
	}
	decoded2, ok, err := decodePGPos(got2[0].Pos())
	if err != nil || !ok {
		t.Fatalf("decode post-lazy-install position: ok=%v err=%v", ok, err)
	}
	// Subsequent positions must carry the now-installed pin so future
	// reconnects engage divergence detection rather than silently
	// installing again.
	if decoded2.SystemID == "" {
		t.Error("post-lazy-install emitted position has empty SystemID — pin was not installed")
	}
	if decoded2.Timeline == 0 {
		t.Error("post-lazy-install emitted position has zero Timeline — pin was not installed")
	}
}
