//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// Real-server half of the [CDCReader.Close] pump-join pin (the unit half
// is cdc_reader_close_join_test.go). This one closes a reader whose pump
// is genuinely live against a real walsender — the shape every caller's
// deferred teardown has, and the shape that produced the CI data race
// between Close's `r.db = nil` and the pump's ensureEnumTypeOIDs.
//
// It pins BOTH halves of that fix, and only a real pgconn can pin the
// second: that the pump actually observes its own cancellation. pgconn
// returns an already-done context dressed as a timeout, which the pump's
// keepalive branch used to swallow with `continue` — so a cancelled pump
// spun forever instead of unwinding. With that regressed, this test does
// not fail an assertion, it HANGS at Close and dies on the package
// timeout. Hence the real-server pin: a stubbed connection cannot
// reproduce pgconn's error shaping.

package postgres

import (
	"context"
	"fmt"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/ir"
)

// assertPumpAlreadyExited is the pin's assertion, and it is deliberately
// non-blocking: the pump closes the change channel as the very last
// thing it does before signalling done, so a Close that joined the pump
// has ALREADY closed this channel by the time it returns. No sleep, no
// timeout, no tolerance — a Close that returns early fails here on the
// first round instead of flaking.
func assertPumpAlreadyExited(t *testing.T, round int, changes <-chan ir.Change) {
	t.Helper()
	drained := 0
	for {
		select {
		case _, ok := <-changes:
			if !ok {
				return
			}
			drained++
		default:
			t.Fatalf("round %d: Close returned while the pump goroutine was still running (change channel neither closed nor drained after %d buffered events). Close must join the pump before tearing down the catalog pool it queries on every RelationMessage", round, drained)
		}
	}
}

func TestCDCReader_CloseJoinsLivePump(t *testing.T) {
	dsn, cleanup := startPostgresForCDC(t)
	defer cleanup()

	const rounds = 3

	// One table per round: a relation the stream has not seen yet forces
	// a fresh pgoutput RelationMessage, which is the message that sends
	// the pump into r.db (resolveColumnStableIDs → pg_attribute,
	// resolveIdentityKeyCols → pg_index under REPLICA IDENTITY FULL,
	// ensureEnumTypeOIDs → pg_type). That is the work Close used to tear
	// the pool out from under.
	for i := range rounds {
		applyPGSQL(t, dsn, fmt.Sprintf(`
			CREATE TABLE round_%d (
				id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				email VARCHAR(255) NOT NULL
			);
			ALTER TABLE round_%d REPLICA IDENTITY FULL;
		`, i, i))
	}

	eng := Engine{}

	for i := range rounds {
		ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)

		rdr, err := eng.OpenCDCReader(ctx, dsn)
		if err != nil {
			cancel()
			t.Fatalf("round %d: OpenCDCReader: %v", i, err)
		}
		changes, err := rdr.StreamChanges(ctx, ir.Position{})
		if err != nil {
			cancel()
			t.Fatalf("round %d: StreamChanges: %v", i, err)
		}

		// Hand the pump real work, then close without draining a single
		// event — exactly what `sluice sync`'s deferred stop() and
		// `backup incremental`'s deferred CloseIf(cdc) do when the run
		// returns early.
		applyPGSQL(t, dsn, fmt.Sprintf(
			`INSERT INTO round_%d (email) VALUES ('a@example.com'), ('b@example.com');`, i,
		))

		closer, ok := rdr.(interface{ Close() error })
		if !ok {
			cancel()
			t.Fatalf("round %d: CDC reader does not implement Close", i)
		}
		if err := closer.Close(); err != nil {
			cancel()
			t.Fatalf("round %d: Close: %v", i, err)
		}

		assertPumpAlreadyExited(t, i, changes)
		cancel()

		// The slot is shared across rounds; PG can hold it active a
		// moment past the walsender's disconnect, and the next round's
		// START_REPLICATION would otherwise burn the reader's 55006
		// retry budget.
		waitForSlotInactive(t, dsn, defaultSlot, 30*time.Second)
	}
}
