// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

package postgres

import "github.com/orware/sluice/internal/ir"

// NormalizeForCDCComparison strips IR Type / Column fields that PG's
// CDC reader (pgoutput's RelationMessage projection — see
// [buildRelationCacheEntry] / [projectRelation] / [oidToType]) cannot
// populate from the wire protocol. The cold-start [SchemaReader]
// reads these fields from information_schema / pg_attribute and is
// therefore "richer" than the CDC projection; without this
// normalization the live-coordination classifier
// ([pipeline.ClassifyShape]) compares pre (rich SchemaReader output)
// vs post (poor CDC output) via [reflect.DeepEqual] and surfaces a
// false `altered-col=true` on every existing column.
//
// ADR-0054 Bug 84 fix (v0.73.2). Implements
// [ir.CDCSchemaSnapshotNormalizer].
//
// Phase A captured the exact field-level asymmetry from a local PG
// repro using `widgets (id BIGINT GENERATED BY DEFAULT AS IDENTITY
// PRIMARY KEY, name VARCHAR(64) NOT NULL)`:
//
//	col=id   pre_type=ir.Integer{Width:64, AutoIncrement:true}
//	         post_type=ir.Integer{Width:64, AutoIncrement:false}
//	col=name pre_type=ir.Varchar{Length:64, Charset:"", Collation:""}
//	         post_type=ir.Varchar{Length:64, Charset:"", Collation:""}
//
// The `id` column's `Integer.AutoIncrement` was the smoking-gun field
// for the catalogued repro. The other known-asymmetric fields
// (Char/Varchar/Text Collation, Decimal.Unconstrained) are normalized
// pre-emptively because the same Bug 84 shape will fire on any column
// whose SchemaReader projection populates them — different sluice-
// testing rigs use different column types and we'd rather close the
// class than the single witnessed instance.
//
// The Charset field is left untouched because PG's SchemaReader
// deliberately leaves it empty (Postgres has no per-column charset
// concept — server_encoding is global). It will always match between
// pre and post.
//
// MySQL does NOT need this method: its TableMapEvent decoder re-reads
// information_schema on schema-change boundaries so the CDC projection
// already matches the SchemaReader's.
//
// Returns a new *ir.Table (deep enough copy that mutating the returned
// struct cannot mutate the input). Idempotent on repeated calls.
func (Engine) NormalizeForCDCComparison(t *ir.Table) *ir.Table {
	if t == nil {
		return nil
	}
	out := *t
	out.Columns = make([]*ir.Column, len(t.Columns))
	for i, col := range t.Columns {
		if col == nil {
			continue
		}
		newCol := *col
		newCol.Type = normalizeTypeForCDCComparison(col.Type)
		out.Columns[i] = &newCol
	}
	return &out
}

// normalizeTypeForCDCComparison zeroes the IR Type fields the PG CDC
// reader cannot populate from pgoutput. Returns the type unchanged when
// the type carries no known-asymmetric field. See
// [Engine.NormalizeForCDCComparison] for the per-field rationale.
func normalizeTypeForCDCComparison(t ir.Type) ir.Type {
	switch v := t.(type) {
	case ir.Integer:
		// pgoutput's RelationMessage carries only the data-type OID;
		// the IDENTITY/SERIAL bit lives in pg_attribute /
		// information_schema and cannot be inferred from the OID. Zero
		// the field on the seed so it matches the CDC projection.
		v.AutoIncrement = false
		return v
	case ir.Varchar:
		// pgoutput's RelationMessage carries no collation OID. The
		// SchemaReader reads pg_attribute.attcollation and would
		// populate Collation for any column with an explicit non-
		// default collation; the CDC side leaves it empty.
		v.Collation = ""
		return v
	case ir.Char:
		v.Collation = ""
		return v
	case ir.Text:
		v.Collation = ""
		return v
	case ir.Decimal:
		// The SchemaReader sets Unconstrained=true for bare `numeric`
		// (no precision/scale declared); the CDC OID-to-type mapper
		// emits Decimal{Precision:0, Scale:0, Unconstrained:false} for
		// typmod=-1. Collapse both to the (0,0,false) shape so the
		// comparison treats them as equivalent.
		if v.Unconstrained {
			v.Unconstrained = false
			v.Precision = 0
			v.Scale = 0
		}
		return v
	}
	return t
}
