//go:build integration

// Integration test for the Postgres CDC reader. Boots a Postgres
// container with wal_level=logical (the only non-default GUC the
// reader needs), seeds a table, opens the reader at "from now",
// performs INSERT / UPDATE / DELETE, and asserts the expected
// sequence of ir.Change events arrives.

package postgres

import (
	"context"
	"database/sql"
	"testing"
	"time"

	"github.com/orware/sluice/internal/ir"

	"github.com/testcontainers/testcontainers-go"
	pgtc "github.com/testcontainers/testcontainers-go/modules/postgres"
)

// startPostgresForCDC boots a Postgres container with logical
// replication enabled. Mirrors the pipeline package's startPostgres
// helper but adds the wal_level command-line override the CDC
// reader needs.
func startPostgresForCDC(t *testing.T) (dsn string, cleanup func()) {
	t.Helper()
	testcontainers.SkipIfProviderIsNotHealthy(t)

	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()

	container, err := pgtc.Run(ctx,
		"postgres:16",
		pgtc.WithDatabase("source_db"),
		pgtc.WithUsername("test"),
		pgtc.WithPassword("test"),
		pgtc.BasicWaitStrategies(),
		testcontainers.CustomizeRequest(testcontainers.GenericContainerRequest{
			ContainerRequest: testcontainers.ContainerRequest{
				// The image's docker-entrypoint.sh already invokes
				// `postgres "$@"`, so Cmd holds only the GUC overrides.
				Cmd: []string{
					"-c", "wal_level=logical",
					"-c", "max_wal_senders=4",
					"-c", "max_replication_slots=4",
				},
			},
		}),
	)
	if err != nil {
		t.Fatalf("start container: %v", err)
	}

	terminate := func() {
		shutdown, c := context.WithTimeout(context.Background(), 30*time.Second)
		defer c()
		_ = container.Terminate(shutdown)
	}

	srcConn, err := container.ConnectionString(ctx, "sslmode=disable")
	if err != nil {
		terminate()
		t.Fatalf("connection string: %v", err)
	}
	return srcConn, terminate
}

// applyPGSQL runs a possibly-multi-statement script against the DSN.
func applyPGSQL(t *testing.T, dsn, sqlText string) {
	t.Helper()
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer func() { _ = db.Close() }()

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	if _, err := db.ExecContext(ctx, sqlText); err != nil {
		t.Fatalf("apply sql: %v", err)
	}
}

// TestCDCReader_BasicChangeStream exercises the full pgoutput pipeline:
// INSERT / UPDATE / DELETE issued after StreamChanges starts arrive on
// the channel as ir.Insert / ir.Update / ir.Delete with decoded values
// and decodable positions.
func TestCDCReader_BasicChangeStream(t *testing.T) {
	dsn, cleanup := startPostgresForCDC(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE users (
			id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email  VARCHAR(255) NOT NULL,
			active BOOLEAN      NOT NULL DEFAULT true
		);
		ALTER TABLE users REPLICA IDENTITY FULL;
	`
	applyPGSQL(t, dsn, seedDDL)

	eng := Engine{}

	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()

	rdr, err := eng.OpenCDCReader(ctx, dsn)
	if err != nil {
		t.Fatalf("OpenCDCReader: %v", err)
	}
	defer func() {
		if c, ok := rdr.(interface{ Close() error }); ok {
			_ = c.Close()
		}
	}()

	changes, err := rdr.StreamChanges(ctx, ir.Position{})
	if err != nil {
		t.Fatalf("StreamChanges: %v", err)
	}

	// Give the replication start a moment to register before
	// generating events. Mirrors the MySQL CDC test.
	time.Sleep(200 * time.Millisecond)

	const dml = `
		INSERT INTO users (email, active) VALUES
			('alice@example.com', true),
			('bob@example.com',   false);
		UPDATE users SET active = false WHERE email = 'alice@example.com';
		DELETE FROM users WHERE email = 'bob@example.com';
	`
	applyPGSQL(t, dsn, dml)

	got := drainChanges(t, ctx, changes, 4, 30*time.Second)

	if len(got) != 4 {
		if cdcRdr, ok := rdr.(*CDCReader); ok {
			if streamErr := cdcRdr.Err(); streamErr != nil {
				t.Fatalf("got %d changes; want 4 (stream error: %v)", len(got), streamErr)
			}
		}
		t.Fatalf("got %d changes; want 4", len(got))
	}

	insAlice, ok := got[0].(ir.Insert)
	if !ok {
		t.Fatalf("change[0] = %T; want ir.Insert", got[0])
	}
	if insAlice.Schema != "public" || insAlice.Table != "users" {
		t.Errorf("change[0] = %s.%s; want public.users", insAlice.Schema, insAlice.Table)
	}
	if email, _ := insAlice.Row["email"].(string); email != "alice@example.com" {
		t.Errorf("change[0].Row[email] = %#v; want alice@example.com", insAlice.Row["email"])
	}
	if active, _ := insAlice.Row["active"].(bool); !active {
		t.Errorf("change[0].Row[active] = %#v; want true", insAlice.Row["active"])
	}

	insBob, ok := got[1].(ir.Insert)
	if !ok {
		t.Fatalf("change[1] = %T; want ir.Insert", got[1])
	}
	if active, _ := insBob.Row["active"].(bool); active {
		t.Errorf("change[1].Row[active] = %#v; want false", insBob.Row["active"])
	}

	upd, ok := got[2].(ir.Update)
	if !ok {
		t.Fatalf("change[2] = %T; want ir.Update", got[2])
	}
	// REPLICA IDENTITY FULL means the Before image is populated.
	if upd.Before == nil {
		t.Fatal("update.Before is nil despite REPLICA IDENTITY FULL")
	}
	if before, _ := upd.Before["active"].(bool); !before {
		t.Errorf("update.Before[active] = %#v; want true", upd.Before["active"])
	}
	if after, _ := upd.After["active"].(bool); after {
		t.Errorf("update.After[active] = %#v; want false", upd.After["active"])
	}

	del, ok := got[3].(ir.Delete)
	if !ok {
		t.Fatalf("change[3] = %T; want ir.Delete", got[3])
	}
	if del.Before == nil {
		t.Fatal("delete.Before is nil despite REPLICA IDENTITY FULL")
	}
	if email, _ := del.Before["email"].(string); email != "bob@example.com" {
		t.Errorf("delete.Before[email] = %#v; want bob@example.com", del.Before["email"])
	}

	// Positions: each change must encode a slot+lsn pair the engine
	// can decode, and the slot name should match the configured
	// default.
	for i, c := range got {
		pos := c.Pos()
		if pos.Engine != "postgres" {
			t.Errorf("change[%d].Pos.Engine = %q; want postgres", i, pos.Engine)
		}
		decoded, ok, err := decodePGPos(pos)
		if err != nil || !ok {
			t.Errorf("change[%d].Pos failed to decode: ok=%v err=%v", i, ok, err)
			continue
		}
		if decoded.Slot != "sluice_slot" {
			t.Errorf("change[%d].Pos.Slot = %q; want sluice_slot", i, decoded.Slot)
		}
	}
}

// TestCDCReader_UpdateUnderReplicaIdentityDefault exercises the
// fix for Bug 3: pgoutput omits OldTuple on UPDATEs that don't
// modify the identity-key columns under REPLICA IDENTITY DEFAULT
// (the server-wide default), and the reader synthesizes a
// key-only Before from the after-tuple's PK so the applier can
// build a usable WHERE clause. Without the synthesis, an apply
// downstream would emit "UPDATE t SET ... WHERE " (empty
// predicate) and Postgres rejects with "syntax error at end of
// input".
func TestCDCReader_UpdateUnderReplicaIdentityDefault(t *testing.T) {
	dsn, cleanup := startPostgresForCDC(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE users (
			id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email  VARCHAR(255) NOT NULL,
			active BOOLEAN      NOT NULL DEFAULT true
		);
		-- Intentionally no ALTER TABLE ... REPLICA IDENTITY: the
		-- server-default 'd' (DEFAULT) is the case that triggers
		-- the missing-OldTuple shape on non-PK UPDATEs.
	`
	applyPGSQL(t, dsn, seedDDL)

	eng := Engine{}

	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()

	rdr, err := eng.OpenCDCReader(ctx, dsn)
	if err != nil {
		t.Fatalf("OpenCDCReader: %v", err)
	}
	defer func() {
		if c, ok := rdr.(interface{ Close() error }); ok {
			_ = c.Close()
		}
	}()

	changes, err := rdr.StreamChanges(ctx, ir.Position{})
	if err != nil {
		t.Fatalf("StreamChanges: %v", err)
	}

	time.Sleep(200 * time.Millisecond)

	const dml = `
		INSERT INTO users (email, active) VALUES ('alice@example.com', true);
		UPDATE users SET active = false WHERE email = 'alice@example.com';
	`
	applyPGSQL(t, dsn, dml)

	got := drainChanges(t, ctx, changes, 2, 30*time.Second)
	if len(got) != 2 {
		if cdcRdr, ok := rdr.(*CDCReader); ok {
			if streamErr := cdcRdr.Err(); streamErr != nil {
				t.Fatalf("got %d changes; want 2 (stream error: %v)", len(got), streamErr)
			}
		}
		t.Fatalf("got %d changes; want 2", len(got))
	}

	upd, ok := got[1].(ir.Update)
	if !ok {
		t.Fatalf("change[1] = %T; want ir.Update", got[1])
	}
	if upd.Before == nil {
		t.Fatal("update.Before is nil; expected synthesized key-only Before from After's PK")
	}
	// The synthesized Before should contain only the PK column.
	if _, hasID := upd.Before["id"]; !hasID {
		t.Errorf("update.Before missing id (expected synthesized PK); got %#v", upd.Before)
	}
	if _, hasNonKey := upd.Before["email"]; hasNonKey {
		t.Errorf("update.Before unexpectedly contains non-key column 'email': %#v", upd.Before)
	}
	if _, hasNonKey := upd.Before["active"]; hasNonKey {
		t.Errorf("update.Before unexpectedly contains non-key column 'active': %#v", upd.Before)
	}
	// And After must reflect the new value.
	if after, _ := upd.After["active"].(bool); after {
		t.Errorf("update.After[active] = %#v; want false", upd.After["active"])
	}
}

// TestCDCReader_RejectsWrongWALLevel verifies the precondition check.
// Boots a fresh container with wal_level=replica (the default for
// stock postgres images is also replica unless we override) and
// confirms OpenCDCReader → StreamChanges fails with a clear error
// before any replication command is issued.
func TestCDCReader_RejectsWrongWALLevel(t *testing.T) {
	testcontainers.SkipIfProviderIsNotHealthy(t)

	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()

	container, err := pgtc.Run(ctx,
		"postgres:16",
		pgtc.WithDatabase("source_db"),
		pgtc.WithUsername("test"),
		pgtc.WithPassword("test"),
		pgtc.BasicWaitStrategies(),
		// No wal_level override → server defaults to "replica".
	)
	if err != nil {
		t.Fatalf("start container: %v", err)
	}
	defer func() {
		shutdown, c := context.WithTimeout(context.Background(), 30*time.Second)
		defer c()
		_ = container.Terminate(shutdown)
	}()

	dsn, err := container.ConnectionString(ctx, "sslmode=disable")
	if err != nil {
		t.Fatalf("connection string: %v", err)
	}

	eng := Engine{}
	rdr, err := eng.OpenCDCReader(ctx, dsn)
	if err != nil {
		t.Fatalf("OpenCDCReader: %v", err)
	}
	defer func() {
		if c, ok := rdr.(interface{ Close() error }); ok {
			_ = c.Close()
		}
	}()

	_, err = rdr.StreamChanges(ctx, ir.Position{})
	if err == nil {
		t.Fatal("expected wal_level precondition error; got nil")
	}
	// The error should name wal_level so a user can fix it.
	if !contains(err.Error(), "wal_level") {
		t.Errorf("error should mention wal_level; got %q", err.Error())
	}
}

func contains(haystack, needle string) bool {
	for i := 0; i+len(needle) <= len(haystack); i++ {
		if haystack[i:i+len(needle)] == needle {
			return true
		}
	}
	return false
}

// drainChanges reads up to want events from changes, with an overall
// timeout. Returns whatever it has if the timeout fires or the
// channel closes.
func drainChanges(
	t *testing.T,
	ctx context.Context,
	changes <-chan ir.Change,
	want int,
	timeout time.Duration,
) []ir.Change {
	t.Helper()
	deadline := time.NewTimer(timeout)
	defer deadline.Stop()

	got := make([]ir.Change, 0, want)
	for len(got) < want {
		select {
		case c, ok := <-changes:
			if !ok {
				return got
			}
			got = append(got, c)
		case <-deadline.C:
			t.Logf("timed out after %v with %d/%d changes", timeout, len(got), want)
			return got
		case <-ctx.Done():
			return got
		}
	}
	return got
}
