// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

package postgres

import "sluicesync.dev/sluice/internal/ir"

// NormalizeForCDCComparison strips IR Type / Column fields that PG's
// CDC reader (pgoutput's RelationMessage projection — see
// [buildRelationCacheEntry] / [projectRelation] / [oidToType]) cannot
// populate from the wire protocol. The cold-start [SchemaReader]
// reads these fields from information_schema / pg_attribute and is
// therefore "richer" than the CDC projection; without this
// normalization the live-coordination classifier
// ([pipeline.ClassifyShape]) compares pre (rich SchemaReader output)
// vs post (poor CDC output) via [reflect.DeepEqual] and surfaces a
// false `altered-col=true` on every existing column.
//
// ADR-0054 Bug 84 fix (v0.73.2). Implements
// [ir.CDCSchemaSnapshotNormalizer].
//
// Phase A captured the exact field-level asymmetry from a local PG
// repro using `widgets (id BIGINT GENERATED BY DEFAULT AS IDENTITY
// PRIMARY KEY, name VARCHAR(64) NOT NULL)`:
//
//	col=id   pre_type=ir.Integer{Width:64, AutoIncrement:true}
//	         post_type=ir.Integer{Width:64, AutoIncrement:false}
//	col=name pre_type=ir.Varchar{Length:64, Charset:"", Collation:""}
//	         post_type=ir.Varchar{Length:64, Charset:"", Collation:""}
//
// The `id` column's `Integer.AutoIncrement` was the smoking-gun field
// for the catalogued repro. The other known-asymmetric fields
// (Char/Varchar/Text Collation, Decimal.Unconstrained) are normalized
// pre-emptively because the same Bug 84 shape will fire on any column
// whose SchemaReader projection populates them — different sluice-
// testing rigs use different column types and we'd rather close the
// class than the single witnessed instance.
//
// The Charset field is left untouched because PG's SchemaReader
// deliberately leaves it empty (Postgres has no per-column charset
// concept — server_encoding is global). It will always match between
// pre and post.
//
// MySQL does NOT need this method: its TableMapEvent decoder re-reads
// information_schema on schema-change boundaries so the CDC projection
// already matches the SchemaReader's.
//
// Bug 86 extension (v0.78.1): also normalize column-level fields that
// pgoutput cannot carry over the wire. The pgoutput RelationMessage
// format only carries (name, OID, typmod, key-flag) per column — it
// does NOT carry the column's nullability, default expression, or
// comment. [projectRelation] therefore leaves these fields at their
// Go zero values on every CDC-projected snapshot, while the cold-
// start SchemaReader populates them faithfully from
// information_schema. Without normalization, the classifier's
// [diffAlteredColumn] (which inspects `Nullable` directly) fires
// `ShapeKindAlterColumnNullability` on every nullable existing column
// at the first post-DDL boundary — combining with a legitimate
// RENAME's added=1 / dropped=1 into the multi-shape combo refusal
// path. The fix zeroes `Nullable`, `Default`, and `Comment` on the
// seed so the comparison aligns with what pgoutput can actually
// carry. The cost is that the live-coordination classifier cannot
// detect genuine ALTER COLUMN NULLABILITY / DEFAULT / COMMENT shapes
// on PG via CDC — but it could not detect them anyway (the wire
// doesn't carry the signal), so this just makes the existing
// limitation explicit at the comparison surface.
//
// Bug 86 also surfaced a Type-level asymmetry on the temporal family
// (TIMESTAMP / TIMESTAMPTZ / TIME / TIMETZ): bare, (0), and (6) are one
// equivalence class on PG (the engine default is 6), yet different IR
// sources have represented that class differently over time (the
// pre-TRIAGE-#3 SchemaReader materialized bare as an explicit 6; the
// CDC OID mapper decoded typmod=-1 as 0; TRIAGE #3 gave both sides the
// PrecisionUnspecified state). [normalizeTypeForCDCComparison]
// collapses every class member to the ONE canonical bare form
// ({Precision:0, PrecisionUnspecified:true}) so any two
// representations compare equal — see the per-type cases for the
// canonical-form rationale and the accepted false-negative-within-
// the-class trade-off.
//
// The normalization is a comparison LENS: the live-coordination
// intercepts apply it to BOTH sides of every classifier comparison —
// the cold-start seed AND each CDC-projected snapshot — never only to
// the seed. Normalizing one side against a raw other side is exactly
// how the TRIAGE-#3 regression happened: the seed's collapsed form
// stopped matching the CDC projection's new PrecisionUnspecified
// representation and every bare temporal column phantom-altered at
// the first boundary.
//
// Returns a new *ir.Table (deep enough copy that mutating the returned
// struct cannot mutate the input). Idempotent on repeated calls.
func (Engine) NormalizeForCDCComparison(t *ir.Table) *ir.Table {
	if t == nil {
		return nil
	}
	out := *t
	// ADR-0091: drop STORED generated columns. pgoutput's
	// RelationMessage EXCLUDES generated columns (pre-PG18 they are not
	// published over logical replication at all), so [projectRelation]
	// never sees them and the CDC-projected IR omits them entirely. The
	// cold-start SchemaReader reads them from pg_attribute, so without
	// this filter the classifier's [diffColumns] sees the generated
	// column as present-in-pre / absent-in-post → a phantom
	// ShapeKindDropColumn. Under ADR-0058's ADD-only path that phantom
	// drop was refused loudly; under ADR-0091's default-on forwarding it
	// would forward an AlterDropColumn and SILENTLY DESTROY the
	// generated column on the target (the Generated-CDC integration
	// failure). A genuine generated-column drop cannot be detected via
	// pgoutput anyway, so excluding them from the comparison just makes
	// the wire's existing limitation explicit (same rationale as the
	// CheckConstraints / Indexes cases below). The discriminator is
	// GeneratedExpr (a non-empty expression) — IDENTITY / SERIAL columns
	// carry AutoIncrement, not GeneratedExpr, and ARE published, so they
	// are NOT filtered here.
	out.Columns = make([]*ir.Column, 0, len(t.Columns))
	for _, col := range t.Columns {
		if col == nil {
			continue
		}
		if col.GeneratedExpr != "" {
			continue
		}
		newCol := *col
		newCol.Type = normalizeTypeForCDCComparison(col.Type)
		// Bug 86 (v0.78.1): zero the column-level fields pgoutput
		// cannot carry. See the docstring above for the per-field
		// rationale; the smoking-gun field for the catalogued repro
		// was Nullable (Bug 86 was triggered by a NUMERIC(10,2) /
		// TEXT column with no NOT NULL — cold-start saw Nullable=true,
		// CDC projection saw Nullable=false). Default and Comment
		// are zeroed pre-emptively to close the class.
		newCol.Nullable = false
		newCol.Default = nil
		newCol.Comment = ""
		out.Columns = append(out.Columns, &newCol)
	}
	// ADR-0065 (task #22 CHECK sub-shape): pgoutput's RelationMessage
	// carries no constraint metadata, so the CDC-projected IR
	// always leaves CheckConstraints nil. The cold-start
	// SchemaReader populates it from pg_constraint. Without
	// normalization, the classifier's [pipeline.diffChecks] would
	// fire ShapeKindDropCheck on every CDC boundary for any table
	// that carries a CHECK constraint — false-positive class.
	//
	// The cost: live-coordination cannot detect CHECK constraint
	// shapes via CDC (the wire doesn't carry the signal anyway).
	// Operators issuing constraint-only DDL on the source while
	// live-coordination is engaged see the cold-start side land
	// the change at the next snapshot boundary; the CDC stream's
	// row apply path observes whatever the new CHECK admits /
	// refuses at INSERT/UPDATE time. ADR-0065 documents this
	// trade-off explicitly under "What's deferred".
	out.CheckConstraints = nil
	// ADR-0091: drop secondary indexes for the same reason as
	// CheckConstraints — pgoutput's RelationMessage carries no secondary
	// index metadata (only the replica-identity / PK key-flag, which
	// [projectRelation] surfaces as PrimaryKey), so the CDC-projected IR
	// always leaves Indexes nil. Without this, [diffIndexes] fires a
	// phantom ShapeKindDropIndex on every CDC boundary for any table
	// carrying a secondary index; under ADR-0091's default-on forwarding
	// that would forward a DropShapeIndex and drop the index on the
	// target. PrimaryKey is intentionally preserved (projectRelation
	// carries it from the key-flag). CREATE/DROP INDEX therefore cannot
	// be forwarded on PG via pgoutput — a documented limitation; MySQL's
	// information_schema re-read CDC projection carries indexes and does
	// forward them.
	out.Indexes = nil
	return &out
}

// normalizeTypeForCDCComparison zeroes the IR Type fields the PG CDC
// reader cannot populate from pgoutput. Returns the type unchanged when
// the type carries no known-asymmetric field. See
// [Engine.NormalizeForCDCComparison] for the per-field rationale.
func normalizeTypeForCDCComparison(t ir.Type) ir.Type {
	switch v := t.(type) {
	case ir.Integer:
		// pgoutput's RelationMessage carries only the data-type OID;
		// the IDENTITY/SERIAL bit lives in pg_attribute /
		// information_schema and cannot be inferred from the OID. Zero
		// the field on the seed so it matches the CDC projection.
		v.AutoIncrement = false
		return v
	case ir.Varchar:
		// pgoutput's RelationMessage carries no collation OID. The
		// SchemaReader reads pg_attribute.attcollation and would
		// populate Collation for any column with an explicit non-
		// default collation; the CDC side leaves it empty.
		v.Collation = ""
		return v
	case ir.Char:
		v.Collation = ""
		return v
	case ir.Text:
		v.Collation = ""
		return v
	case ir.Decimal:
		// The SchemaReader sets Unconstrained=true for bare `numeric`
		// (no precision/scale declared); the CDC OID-to-type mapper
		// emits Decimal{Precision:0, Scale:0, Unconstrained:false} for
		// typmod=-1. Collapse both to the (0,0,false) shape so the
		// comparison treats them as equivalent.
		if v.Unconstrained {
			v.Unconstrained = false
			v.Precision = 0
			v.Scale = 0
		}
		return v
	case ir.DateTime:
		// Bug 86 (v0.78.1) + TRIAGE #3 regression fix: the temporal
		// collapse class is bare ≡ (0) ≡ (6). PG's engine default is 6,
		// so all three forms decode the same wire values; historically
		// they also round-tripped through different representations —
		// the pre-TRIAGE-#3 SchemaReader materialized bare as
		// Precision=6 (persisted schema-history/lease rows from older
		// binaries still carry that), while the CDC OID mapper decoded
		// typmod=-1 as Precision=0. Collapse every class member to ONE
		// canonical form so any two representations of a same-class
		// column compare equal in [pipeline.ClassifyShape].
		//
		// The canonical form is the BARE one ({Precision:0,
		// PrecisionUnspecified:true}) — NOT {0,false} — for two reasons:
		// (a) it is what both the TRIAGE-#3 SchemaReader and the CDC
		// projection natively emit for the common bare column, so the
		// collapse is a no-op there; and (b) normalized types can flow
		// into shape payloads the ShapeDeltaApplier materializes on the
		// target (Shape A ADD COLUMN), where the bare form emits bare
		// DDL (6-behaving — value-safe for every class member) while an
		// explicit (0) would emit a TRUNCATING timestamp(0). The
		// pre-TRIAGE-#3 canonical was {0,false} precisely because (0)
		// then still emitted bare; TRIAGE #3 made a known 0 emit (0),
		// which is what turned the old canonical into a phantom-alter
		// regression on bare temporal columns.
		//
		// Cost (unchanged, documented since v0.78.1): a genuine ALTER
		// between two class members — e.g. timestamp(6) → timestamp(0)
		// — is a false-negative at the classifier. Precisions 1–5 stay
		// distinct and still classify.
		if v.PrecisionUnspecified || v.Precision == 0 || v.Precision == 6 {
			v.Precision = 0
			v.PrecisionUnspecified = true
		}
		return v
	case ir.Time:
		// Same temporal collapse class as ir.DateTime above; PG `TIME`
		// and `TIMETZ` default to precision 6 too.
		if v.PrecisionUnspecified || v.Precision == 0 || v.Precision == 6 {
			v.Precision = 0
			v.PrecisionUnspecified = true
		}
		return v
	case ir.Timestamp:
		// Same temporal collapse class; covers `TIMESTAMP WITH TIME
		// ZONE` (TIMESTAMPTZ).
		if v.PrecisionUnspecified || v.Precision == 0 || v.Precision == 6 {
			v.Precision = 0
			v.PrecisionUnspecified = true
		}
		return v
	case ir.Geometry:
		// Bug 147: the cold-start SchemaReader reads
		// geometry_columns/geography_columns and populates
		// ir.Geometry{Subtype, SRID, HasZ, HasM}; the pgoutput RelationMessage
		// carries only the dynamic geometry type OID, so [buildRelationCacheEntry]
		// projects a bare ir.Geometry{}. Without this, the classifier's
		// [diffAlteredColumn] reflect.DeepEqual fires a phantom
		// ShapeKindAlterColumnType on every geometry column at the first CDC
		// boundary (and, combined with a real concurrent ADD COLUMN, a loud
		// multi-shape combo refusal that wedges a legitimate change). Zero the
		// fields the wire cannot carry. IsGeography rides the OID (it IS
		// wire-recoverable), so preserve it; SRID is recovered target-side at
		// apply time (ADR-0035 / #20). Same Bug-84/86 class as the temporal
		// and decimal cases above — geometry was simply missed.
		return ir.Geometry{IsGeography: v.IsGeography}
	case ir.Enum:
		// catalog Bug 151: the cold-start SchemaReader reads pg_type +
		// pg_enum and populates ir.Enum{TypeName, Values}; the pgoutput
		// RelationMessage carries only the dynamic enum type OID, so
		// [buildRelationCacheEntry] projects a BARE ir.Enum{} (the value
		// rides the wire as its text label — type name and value list are
		// not carried). Without this, the classifier's [diffAlteredColumn]
		// reflect.DeepEqual fires a phantom ShapeKindAlterColumnType on
		// every enum column at the first CDC boundary (and, combined with a
		// real concurrent ADD COLUMN, a loud multi-shape combo refusal that
		// wedges a legitimate change). Strip both fields to the bare shape
		// the wire can carry. Same Bug-84/86/147 class as the temporal,
		// decimal, and geometry cases above. Cost: an ALTER TYPE ADD VALUE
		// can't be classifier-detected via CDC — but pgoutput doesn't carry
		// it anyway, and a new label simply applies as text on the target.
		return ir.Enum{}
	}
	return t
}
