//go:build integration

// Integration test for the Postgres snapshot+CDC handoff. Boots a
// Postgres container with wal_level=logical, seeds rows R1..R5,
// opens a snapshot stream (which atomically creates a logical
// replication slot and exports a snapshot), inserts R6 on a
// separate connection (so it commits *after* the slot's
// consistent_point LSN), and asserts:
//
//   - bulk-copy via stream.Rows yields exactly R1..R5 (no overlap),
//   - CDC via stream.Changes yields exactly the R6 insert (no gap).

package postgres

import (
	"context"
	"database/sql"
	"sort"
	"testing"
	"time"

	"github.com/orware/sluice/internal/ir"

	"github.com/testcontainers/testcontainers-go"
	pgtc "github.com/testcontainers/testcontainers-go/modules/postgres"
)

func startPostgresForSnapshotCDC(t *testing.T) (dsn string, cleanup func()) {
	t.Helper()
	testcontainers.SkipIfProviderIsNotHealthy(t)

	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()

	container, err := pgtc.Run(ctx,
		"postgres:16",
		pgtc.WithDatabase("source_db"),
		pgtc.WithUsername("test"),
		pgtc.WithPassword("test"),
		pgtc.BasicWaitStrategies(),
		testcontainers.CustomizeRequest(testcontainers.GenericContainerRequest{
			ContainerRequest: testcontainers.ContainerRequest{
				Cmd: []string{
					"-c", "wal_level=logical",
					"-c", "max_wal_senders=4",
					"-c", "max_replication_slots=4",
				},
			},
		}),
	)
	if err != nil {
		t.Fatalf("start container: %v", err)
	}

	terminate := func() {
		shutdown, c := context.WithTimeout(context.Background(), 30*time.Second)
		defer c()
		_ = container.Terminate(shutdown)
	}

	srcConn, err := container.ConnectionString(ctx, "sslmode=disable")
	if err != nil {
		terminate()
		t.Fatalf("connection string: %v", err)
	}
	return srcConn, terminate
}

func applyPGSnap(t *testing.T, dsn, sqlText string) {
	t.Helper()
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer func() { _ = db.Close() }()

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	if _, err := db.ExecContext(ctx, sqlText); err != nil {
		t.Fatalf("apply sql: %v", err)
	}
}

// TestSnapshotStream_NoGapNoOverlap is the load-bearing test for §4
// on the Postgres side. Same shape as the MySQL counterpart.
func TestSnapshotStream_NoGapNoOverlap(t *testing.T) {
	dsn, cleanup := startPostgresForSnapshotCDC(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL
		);
		ALTER TABLE users REPLICA IDENTITY FULL;

		INSERT INTO users (email) VALUES
			('r1@example.com'),
			('r2@example.com'),
			('r3@example.com'),
			('r4@example.com'),
			('r5@example.com');
	`
	applyPGSnap(t, dsn, seedDDL)

	eng := Engine{}

	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()

	stream, err := eng.OpenSnapshotStream(ctx, dsn)
	if err != nil {
		t.Fatalf("OpenSnapshotStream: %v", err)
	}
	defer func() { _ = stream.Close() }()

	// Concurrent insert on a separate connection so it commits at
	// an LSN > the slot's consistent_point.
	applyPGSnap(t, dsn, "INSERT INTO users (email) VALUES ('r6@example.com');")

	usersTable := schemaForUsers()
	bulkRows := drainAllRows(t, ctx, stream.Rows, usersTable)
	bulkEmails := emailsOf(bulkRows)
	want := []string{"r1@example.com", "r2@example.com", "r3@example.com", "r4@example.com", "r5@example.com"}
	if !equalStringSlices(bulkEmails, want) {
		t.Fatalf("bulk rows = %v; want exactly %v (overlap or missing rows)", bulkEmails, want)
	}

	changes, err := stream.Changes.StreamChanges(ctx, stream.Position)
	if err != nil {
		t.Fatalf("StreamChanges: %v", err)
	}

	got := drainSnapshotChanges(t, ctx, changes, 1, 30*time.Second)
	if len(got) != 1 {
		// Surface the streaming-side error if pump captured one.
		if cdcRdr, ok := stream.Changes.(*CDCReader); ok {
			if streamErr := cdcRdr.Err(); streamErr != nil {
				t.Fatalf("got %d changes; want 1 (R6 insert) — stream err: %v", len(got), streamErr)
			}
		}
		t.Fatalf("got %d changes; want 1 (R6 insert)", len(got))
	}
	insR6, ok := got[0].(ir.Insert)
	if !ok {
		t.Fatalf("change[0] = %T; want ir.Insert", got[0])
	}
	if email, _ := insR6.Row["email"].(string); email != "r6@example.com" {
		t.Errorf("R6 insert email = %#v; want r6@example.com", insR6.Row["email"])
	}
}

// schemaForUsers, drainAllRows, drainSnapshotChanges, emailsOf,
// equalStringSlices — same helpers as the MySQL counterpart.

func schemaForUsers() *ir.Table {
	return &ir.Table{
		Schema: "public",
		Name:   "users",
		Columns: []*ir.Column{
			{Name: "id", Type: ir.Integer{Width: 64, AutoIncrement: true}},
			{Name: "email", Type: ir.Varchar{Length: 255}},
		},
	}
}

func drainAllRows(t *testing.T, ctx context.Context, rr ir.RowReader, table *ir.Table) []ir.Row {
	t.Helper()
	ch, err := rr.ReadRows(ctx, table)
	if err != nil {
		t.Fatalf("ReadRows: %v", err)
	}
	var out []ir.Row
	for row := range ch {
		out = append(out, row)
	}
	return out
}

func drainSnapshotChanges(
	t *testing.T,
	ctx context.Context,
	changes <-chan ir.Change,
	want int,
	timeout time.Duration,
) []ir.Change {
	t.Helper()
	deadline := time.NewTimer(timeout)
	defer deadline.Stop()

	got := make([]ir.Change, 0, want)
	for len(got) < want {
		select {
		case c, ok := <-changes:
			if !ok {
				return got
			}
			got = append(got, c)
		case <-deadline.C:
			return got
		case <-ctx.Done():
			return got
		}
	}
	return got
}

func emailsOf(rows []ir.Row) []string {
	out := make([]string, 0, len(rows))
	for _, r := range rows {
		s, _ := r["email"].(string)
		out = append(out, s)
	}
	sort.Strings(out)
	return out
}

func equalStringSlices(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}
