//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// Integration test for the Postgres snapshot+CDC handoff. Boots a
// Postgres container with wal_level=logical, seeds rows R1..R5,
// opens a snapshot stream (which atomically creates a logical
// replication slot and exports a snapshot), inserts R6 on a
// separate connection (so it commits *after* the slot's
// consistent_point LSN), and asserts:
//
//   - bulk-copy via stream.Rows yields exactly R1..R5 (no overlap),
//   - CDC via stream.Changes yields exactly the R6 insert (no gap).

package postgres

import (
	"context"
	"database/sql"
	"sort"
	"testing"
	"time"

	"github.com/orware/sluice/internal/ir"

	"github.com/testcontainers/testcontainers-go"
	pgtc "github.com/testcontainers/testcontainers-go/modules/postgres"
)

func startPostgresForSnapshotCDC(t *testing.T) (dsn string, cleanup func()) {
	t.Helper()
	testcontainers.SkipIfProviderIsNotHealthy(t)

	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()

	container, err := pgtc.Run(
		ctx,
		"postgres:16",
		pgtc.WithDatabase("source_db"),
		pgtc.WithUsername("test"),
		pgtc.WithPassword("test"),
		pgtc.BasicWaitStrategies(),
		testcontainers.CustomizeRequest(testcontainers.GenericContainerRequest{
			ContainerRequest: testcontainers.ContainerRequest{
				Cmd: []string{
					"-c", "wal_level=logical",
					"-c", "max_wal_senders=4",
					"-c", "max_replication_slots=4",
				},
			},
		}),
	)
	if err != nil {
		t.Fatalf("start container: %v", err)
	}

	terminate := func() {
		shutdown, c := context.WithTimeout(context.Background(), 30*time.Second)
		defer c()
		_ = container.Terminate(shutdown)
	}

	srcConn, err := container.ConnectionString(ctx, "sslmode=disable")
	if err != nil {
		terminate()
		t.Fatalf("connection string: %v", err)
	}
	return srcConn, terminate
}

func applyPGSnap(t *testing.T, dsn, sqlText string) {
	t.Helper()
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer func() { _ = db.Close() }()

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	if _, err := db.ExecContext(ctx, sqlText); err != nil {
		t.Fatalf("apply sql: %v", err)
	}
}

// TestSnapshotStream_NoGapNoOverlap is the load-bearing test for §4
// on the Postgres side. Same shape as the MySQL counterpart.
func TestSnapshotStream_NoGapNoOverlap(t *testing.T) {
	dsn, cleanup := startPostgresForSnapshotCDC(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL
		);
		ALTER TABLE users REPLICA IDENTITY FULL;

		INSERT INTO users (email) VALUES
			('r1@example.com'),
			('r2@example.com'),
			('r3@example.com'),
			('r4@example.com'),
			('r5@example.com');
	`
	applyPGSnap(t, dsn, seedDDL)

	eng := Engine{}

	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()

	stream, err := eng.OpenSnapshotStream(ctx, dsn)
	if err != nil {
		t.Fatalf("OpenSnapshotStream: %v", err)
	}
	defer func() { _ = stream.Close() }()

	// Concurrent insert on a separate connection so it commits at
	// an LSN > the slot's consistent_point.
	applyPGSnap(t, dsn, "INSERT INTO users (email) VALUES ('r6@example.com');")

	usersTable := schemaForUsers()
	bulkRows := drainAllRows(t, ctx, stream.Rows, usersTable)
	bulkEmails := emailsOf(bulkRows)
	want := []string{"r1@example.com", "r2@example.com", "r3@example.com", "r4@example.com", "r5@example.com"}
	if !equalStringSlices(bulkEmails, want) {
		t.Fatalf("bulk rows = %v; want exactly %v (overlap or missing rows)", bulkEmails, want)
	}

	changes, err := stream.Changes.StreamChanges(ctx, stream.Position)
	if err != nil {
		t.Fatalf("StreamChanges: %v", err)
	}

	got := drainSnapshotChanges(t, ctx, changes, 1, 30*time.Second)
	if len(got) != 1 {
		// Surface the streaming-side error if pump captured one.
		if cdcRdr, ok := stream.Changes.(*CDCReader); ok {
			if streamErr := cdcRdr.Err(); streamErr != nil {
				t.Fatalf("got %d changes; want 1 (R6 insert) — stream err: %v", len(got), streamErr)
			}
		}
		t.Fatalf("got %d changes; want 1 (R6 insert)", len(got))
	}
	insR6, ok := got[0].(ir.Insert)
	if !ok {
		t.Fatalf("change[0] = %T; want ir.Insert", got[0])
	}
	if email, _ := insR6.Row["email"].(string); email != "r6@example.com" {
		t.Errorf("R6 insert email = %#v; want r6@example.com", insR6.Row["email"])
	}
}

// TestSnapshotStream_ReleaseRowsClosesSnapshotTx exercises the Bug 21
// fix: after bulk-copy completes the orchestrator should be able to
// commit the snapshot transaction and release the import-side
// connections without disturbing the CDC stream. Pre-fix, the
// snapshot tx sat as `idle in transaction` for the entire SnapshotStream
// lifetime, holding AccessShareLock on every snapshotted table and
// blocking ALTER on the source. The fix splits the cleanup into
// ReleaseRowsFn (called after bulk-copy) and CloseFn (called after
// CDC ends).
//
// Asserts:
//
//   - ReleaseRows commits the snapshot tx — pg_stat_activity shows
//     no `idle in transaction` against the source DB after release.
//   - CDC continues working after ReleaseRows — a post-release insert
//     still surfaces on the change stream.
//   - Close is idempotent with ReleaseRows; calling both is safe.
//   - An ALTER TABLE on the source after ReleaseRows succeeds without
//     blocking on the (no-longer-held) AccessShareLock.
func TestSnapshotStream_ReleaseRowsClosesSnapshotTx(t *testing.T) {
	dsn, cleanup := startPostgresForSnapshotCDC(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL
		);
		ALTER TABLE users REPLICA IDENTITY FULL;

		INSERT INTO users (email) VALUES
			('a@example.com'),
			('b@example.com');
	`
	applyPGSnap(t, dsn, seedDDL)

	eng := Engine{}

	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()

	stream, err := eng.OpenSnapshotStream(ctx, dsn)
	if err != nil {
		t.Fatalf("OpenSnapshotStream: %v", err)
	}
	defer func() { _ = stream.Close() }()

	usersTable := schemaForUsers()
	if _ = drainAllRows(t, ctx, stream.Rows, usersTable); err != nil {
		t.Fatalf("drain bulk rows: %v", err)
	}

	// Before release: the snapshot tx is alive. We don't assert the
	// pre-state strictly (whether sluice's exporter shows up depends
	// on connection-pool timing) — the load-bearing assertion is the
	// post-release state.

	if err := stream.ReleaseRows(); err != nil {
		t.Fatalf("ReleaseRows: %v", err)
	}

	// Post-release: no `idle in transaction` sessions against the
	// source DB. A connection in `idle in transaction` is the smoking
	// gun for Bug 21's symptom; this assertion would fail pre-fix
	// because CloseFn used to be the only release path.
	if n := countIdleInTxSessions(t, ctx, dsn); n != 0 {
		t.Errorf("expected 0 idle-in-transaction sessions after ReleaseRows; got %d", n)
	}

	// ALTER on the source must succeed quickly — pre-fix it would
	// block on AccessShareLock held by the snapshot tx.
	applyPGSnap(t, dsn, "ALTER TABLE users ADD COLUMN nickname VARCHAR(50)")

	// CDC still works: open StreamChanges after release, commit a row
	// post-snapshot, and watch it surface.
	changes, err := stream.Changes.StreamChanges(ctx, stream.Position)
	if err != nil {
		t.Fatalf("StreamChanges after ReleaseRows: %v", err)
	}
	applyPGSnap(t, dsn, "INSERT INTO users (email, nickname) VALUES ('c@example.com', 'cc')")
	got := drainSnapshotChanges(t, ctx, changes, 1, 30*time.Second)
	if len(got) != 1 {
		t.Fatalf("got %d post-release changes; want 1", len(got))
	}

	// Idempotency: calling ReleaseRows again is a no-op.
	if err := stream.ReleaseRows(); err != nil {
		t.Errorf("second ReleaseRows: %v; want nil", err)
	}
}

// countIdleInTxSessions returns the number of `idle in transaction`
// sessions against dsn's database. Used by the Bug 21 test to assert
// the snapshot tx has been committed.
func countIdleInTxSessions(t *testing.T, ctx context.Context, dsn string) int {
	t.Helper()
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer func() { _ = db.Close() }()

	const q = `
		SELECT COUNT(*) FROM pg_stat_activity
		WHERE datname  = current_database()
		  AND state    = 'idle in transaction'
		  AND pid     <> pg_backend_pid()`
	var n int
	if err := db.QueryRowContext(ctx, q).Scan(&n); err != nil {
		t.Fatalf("count idle-in-tx: %v", err)
	}
	return n
}

// schemaForUsers, drainAllRows, drainSnapshotChanges, emailsOf,
// equalStringSlices — same helpers as the MySQL counterpart.

func schemaForUsers() *ir.Table {
	return &ir.Table{
		Schema: "public",
		Name:   "users",
		Columns: []*ir.Column{
			{Name: "id", Type: ir.Integer{Width: 64, AutoIncrement: true}},
			{Name: "email", Type: ir.Varchar{Length: 255}},
		},
	}
}

func drainAllRows(t *testing.T, ctx context.Context, rr ir.RowReader, table *ir.Table) []ir.Row {
	t.Helper()
	ch, err := rr.ReadRows(ctx, table)
	if err != nil {
		t.Fatalf("ReadRows: %v", err)
	}
	var out []ir.Row
	for row := range ch {
		out = append(out, row)
	}
	return out
}

func drainSnapshotChanges(
	t *testing.T,
	ctx context.Context,
	changes <-chan ir.Change,
	want int,
	timeout time.Duration,
) []ir.Change {
	t.Helper()
	deadline := time.NewTimer(timeout)
	defer deadline.Stop()

	got := make([]ir.Change, 0, want)
	for len(got) < want {
		select {
		case c, ok := <-changes:
			if !ok {
				return got
			}
			// Skip orthogonal infra events — this helper captures
			// row events for shape assertions. TxBegin/TxCommit are
			// tx-boundary bookkeeping (ADR-0027); ir.SchemaSnapshot is
			// the ADR-0049 schema-history boundary event (emitted at
			// first-touch + each true DDL delta). Neither is DML.
			switch c.(type) {
			case ir.TxBegin, ir.TxCommit, ir.SchemaSnapshot:
				continue
			}
			got = append(got, c)
		case <-deadline.C:
			return got
		case <-ctx.Done():
			return got
		}
	}
	return got
}

func emailsOf(rows []ir.Row) []string {
	out := make([]string, 0, len(rows))
	for _, r := range rows {
		s, _ := r["email"].(string)
		out = append(out, s)
	}
	sort.Strings(out)
	return out
}

func equalStringSlices(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}
