//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

package postgres

import (
	"context"
	"fmt"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/ir"
)

// TestCDCReader_BlockedConsumerKeepsTheWalsenderAlive pins the keepalive a
// pump sends while it is parked on a consumer that is not reading (see
// [CDCReader.send]). Before it, the pump's only standby status came from
// the loop that feeds the change channel, so a consumer stalled past the
// server's wal_sender_timeout — a forwarded ADD COLUMN's backfill, which
// holds the consumer for a whole pass over the table — got the replication
// connection terminated.
//
// The walsender's timeout is lowered for THIS connection only (the
// `options` startup parameter reaches the walsender backend, and
// wal_sender_timeout is user-settable), so the shared container is not
// touched. The premise that it took effect is proven by the mutation run,
// not assumed: with the blocked-send keepalive removed this test fails on
// the walsender's pid changing / the reader recording an error.
//
// It grades three things, each against evidence the pump does not produce:
//
//   - no reconnect: the slot's active_pid (the walsender backend, read
//     from pg_replication_slots) is the same before and after the stall;
//   - the stream carries on: the reader records no error and a row written
//     AFTER the stall is delivered;
//   - no early ack: with an applier tracker attached that never reports an
//     applied LSN, the slot's confirmed_flush_lsn is where it was before
//     any change was written — the blocked-path status must report the
//     applier-confirmed position, never the streamed one.
func TestCDCReader_BlockedConsumerKeepsTheWalsenderAlive(t *testing.T) {
	dsn, cleanup := startPostgresForCDC(t)
	defer cleanup()

	const walSenderTimeout = 3 * time.Second
	lowTimeoutDSN := dsn + "&options=-c%20wal_sender_timeout%3D3s"

	applyPGSQL(t, dsn, `
		CREATE TABLE ka_rows (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(64) NOT NULL
		);
	`)

	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Minute)
	defer cancel()

	rdrAny, err := Engine{}.OpenCDCReader(ctx, lowTimeoutDSN)
	if err != nil {
		t.Fatalf("OpenCDCReader: %v", err)
	}
	rdr, ok := rdrAny.(*CDCReader)
	if !ok {
		t.Fatalf("OpenCDCReader returned %T, want *CDCReader", rdrAny)
	}
	defer func() { _ = rdr.Close() }()
	// A tracker that never reports: the only correct ack is the start.
	rdr.AttachLSNTracker(newLSNTracker())

	changes, err := rdr.StreamChanges(ctx, ir.Position{})
	if err != nil {
		t.Fatalf("StreamChanges: %v", err)
	}

	// Prove the stream is live before measuring anything.
	applyPGSQL(t, dsn, `INSERT INTO ka_rows (email) VALUES ('first@example.com');`)
	waitForInsert(ctx, t, changes, "first@example.com")

	pidBefore := queryPGScalar(t, dsn, fmt.Sprintf(
		`SELECT COALESCE(active_pid::text, '') FROM pg_replication_slots WHERE slot_name = '%s'`, defaultSlot,
	))
	if pidBefore == "" {
		t.Fatalf("slot %s has no active walsender after the first change arrived", defaultSlot)
	}
	flushBefore := queryPGScalar(t, dsn, fmt.Sprintf(
		`SELECT confirmed_flush_lsn::text FROM pg_replication_slots WHERE slot_name = '%s'`, defaultSlot,
	))

	// Fill the change channel well past its buffer with small committed
	// transactions, so commits are parsed (the streamed LSN advances) and
	// the pump parks on a full channel.
	for i := range 200 {
		applyPGSQL(t, dsn, fmt.Sprintf(
			`INSERT INTO ka_rows (email) VALUES ('fill-%d@example.com');`, i,
		))
	}

	// Stall the consumer for several walsender timeouts.
	time.Sleep(4 * walSenderTimeout)

	if err := rdr.Err(); err != nil {
		t.Fatalf("the reader recorded an error while its consumer was stalled for %s (wal_sender_timeout %s): %v — the pump stopped keeping the walsender alive while blocked on the change channel", 4*walSenderTimeout, walSenderTimeout, err)
	}
	pidAfter := queryPGScalar(t, dsn, fmt.Sprintf(
		`SELECT COALESCE(active_pid::text, '') FROM pg_replication_slots WHERE slot_name = '%s'`, defaultSlot,
	))
	if pidAfter != pidBefore {
		t.Fatalf("the walsender changed across a %s consumer stall (active_pid %q → %q; wal_sender_timeout %s): the replication connection was dropped because the blocked pump sent no standby status", 4*walSenderTimeout, pidBefore, pidAfter, walSenderTimeout)
	}
	flushAfter := queryPGScalar(t, dsn, fmt.Sprintf(
		`SELECT confirmed_flush_lsn::text FROM pg_replication_slots WHERE slot_name = '%s'`, defaultSlot,
	))
	if flushAfter != flushBefore {
		t.Fatalf("confirmed_flush_lsn advanced from %s to %s during the stall although the applier confirmed nothing: a status sent while blocked acked past the applier", flushBefore, flushAfter)
	}

	// The stream carries on: a row written after the stall arrives.
	applyPGSQL(t, dsn, `INSERT INTO ka_rows (email) VALUES ('after@example.com');`)
	waitForInsert(ctx, t, changes, "after@example.com")
	if err := rdr.Err(); err != nil {
		t.Fatalf("the reader recorded an error after the stall: %v", err)
	}
}

// waitForInsert drains changes until an Insert whose email column is want
// arrives.
func waitForInsert(ctx context.Context, t *testing.T, changes <-chan ir.Change, want string) {
	t.Helper()
	for {
		select {
		case c, ok := <-changes:
			if !ok {
				t.Fatalf("the change channel closed before the insert of %q arrived", want)
			}
			if ins, isIns := c.(ir.Insert); isIns && fmt.Sprint(ins.Row["email"]) == want {
				return
			}
		case <-ctx.Done():
			t.Fatalf("timed out waiting for the insert of %q", want)
		}
	}
}
