//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// Integration test for the Postgres cutover sequence primer (F10 /
// ADR-0062). Boots two Postgres containers (source + target),
// installs a schema with identity columns and disjoint sequence
// values, exercises the source-side reader, applies the priming pass
// against the target, and pins the per-table outcome (primed / noop /
// refused / skipped).
//
// The matrix exercises:
//   - The standard `id BIGINT GENERATED BY DEFAULT AS IDENTITY` shape.
//   - The legacy `id SERIAL` shape (sequence owned by column).
//   - A composite-PK table without a sequence (skipped path).
//   - Idempotent re-run (second invocation reports every primed
//     table as "noop" — the load-bearing F10 promise).
//   - Refusal class: target sequence advanced past source+margin by
//     more than the tolerance, primer returns
//     ErrCutoverSequenceTargetAhead.

package postgres

import (
	"context"
	"database/sql"
	"errors"
	"testing"
	"time"

	"github.com/orware/sluice/internal/ir"
)

// TestCutoverSequencePrimer_PG_PrimesPlusIdempotent pins the cold-path
// shape: prime once → expect "primed" actions; prime again → expect
// "noop" actions without regressing the target.
func TestCutoverSequencePrimer_PG_PrimesPlusIdempotent(t *testing.T) {
	srcDSN, srcCleanup := startPostgres(t)
	defer srcCleanup()
	tgtDSN, tgtCleanup := startPostgres(t)
	defer tgtCleanup()

	// Source: id GENERATED IDENTITY, INSERT rows so source sequence
	// last_value advances. We deliberately use disjoint values from
	// the target so the priming pass has work to do.
	applyDDL(t, srcDSN, `
		CREATE TABLE orders (
			id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name TEXT NOT NULL
		);
		INSERT INTO orders (name) VALUES ('a'), ('b'), ('c'), ('d'), ('e');
	`)
	// Target: same schema, no rows — sequence at default (last_value=1, is_called=false).
	applyDDL(t, tgtDSN, `
		CREATE TABLE orders (
			id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name TEXT NOT NULL
		);
	`)

	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()

	// Source-side state read.
	sr, err := Engine{}.OpenSchemaReader(ctx, srcDSN)
	if err != nil {
		t.Fatalf("open source reader: %v", err)
	}
	defer closeReader(t, sr)
	pgsr := sr.(*SchemaReader)
	schema, err := pgsr.ReadSchema(ctx)
	if err != nil {
		t.Fatalf("read schema: %v", err)
	}
	states, err := pgsr.ReadSequenceState(ctx, schema)
	if err != nil {
		t.Fatalf("read sequence state: %v", err)
	}
	if len(states) != 1 || states[0].Table != "orders" {
		t.Fatalf("source states = %+v; want one entry for orders", states)
	}
	if states[0].Value != 5 {
		t.Errorf("source last_value = %d; want 5 (last issued ID)", states[0].Value)
	}

	// Target-side prime.
	sw, err := Engine{}.OpenSchemaWriter(ctx, tgtDSN)
	if err != nil {
		t.Fatalf("open target writer: %v", err)
	}
	pgsw := sw.(*SchemaWriter)

	margin := int64(1000)
	report, err := pgsw.PrimeSequences(ctx, schema, states, margin)
	if err != nil {
		t.Fatalf("first prime returned err = %v", err)
	}
	if len(report.Actions) != 1 {
		t.Fatalf("first prime actions = %+v; want one", report.Actions)
	}
	a := report.Actions[0]
	if a.Outcome != "primed" {
		t.Errorf("first prime outcome = %q; want %q (action = %+v)", a.Outcome, "primed", a)
	}
	wantApply := int64(5 + margin) // 1005
	if a.TargetAfter != wantApply {
		t.Errorf("first prime TargetAfter = %d; want %d", a.TargetAfter, wantApply)
	}

	// Verify the actual target sequence — operator-facing pin.
	verifyDB, err := sql.Open("pgx", tgtDSN)
	if err != nil {
		t.Fatalf("open verify db: %v", err)
	}
	defer func() { _ = verifyDB.Close() }()

	var nextVal int64
	row := verifyDB.QueryRowContext(ctx,
		"SELECT nextval(pg_get_serial_sequence('orders', 'id'))")
	if err := row.Scan(&nextVal); err != nil {
		t.Fatalf("scan nextval: %v", err)
	}
	if nextVal != wantApply+1 {
		t.Errorf("nextval after prime = %d; want %d", nextVal, wantApply+1)
	}

	// Idempotency: re-read state (post-prime, the source is
	// unchanged; states[0].Value still 5), re-prime. Because we just
	// consumed nextval (target now at 1006), the second prime should
	// report "noop" (target already >= source+margin).
	states2, err := pgsr.ReadSequenceState(ctx, schema)
	if err != nil {
		t.Fatalf("read sequence state (2nd time): %v", err)
	}
	report2, err := pgsw.PrimeSequences(ctx, schema, states2, margin)
	if err != nil {
		t.Fatalf("second prime err = %v", err)
	}
	if len(report2.Actions) != 1 {
		t.Fatalf("second prime actions = %+v; want one", report2.Actions)
	}
	a2 := report2.Actions[0]
	if a2.Outcome != "noop" {
		t.Errorf("second prime outcome = %q; want %q (Bug 74 idempotency pin)", a2.Outcome, "noop")
	}
}

// TestCutoverSequencePrimer_PG_RefusesTargetAhead pins the loud-failure
// refusal: when the target's sequence is ahead of source+margin by
// more than the idempotency tolerance, the primer returns
// ErrCutoverSequenceTargetAhead and the action's Outcome is "refused".
func TestCutoverSequencePrimer_PG_RefusesTargetAhead(t *testing.T) {
	srcDSN, srcCleanup := startPostgres(t)
	defer srcCleanup()
	tgtDSN, tgtCleanup := startPostgres(t)
	defer tgtCleanup()

	// Source: id GENERATED IDENTITY, 5 rows.
	applyDDL(t, srcDSN, `
		CREATE TABLE orders (
			id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name TEXT NOT NULL
		);
		INSERT INTO orders (name) VALUES ('a'), ('b'), ('c'), ('d'), ('e');
	`)
	// Target: same schema, but operator INSERTed 50000 rows
	// post-cutover (simulating the "already wrote against target"
	// scenario). The target sequence is now well ahead of source.
	applyDDL(t, tgtDSN, `
		CREATE TABLE orders (
			id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name TEXT NOT NULL
		);
		SELECT setval(pg_get_serial_sequence('orders', 'id'), 50000, true);
	`)

	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()

	sr, _ := Engine{}.OpenSchemaReader(ctx, srcDSN)
	defer closeReader(t, sr)
	pgsr := sr.(*SchemaReader)
	schema, err := pgsr.ReadSchema(ctx)
	if err != nil {
		t.Fatalf("read schema: %v", err)
	}
	states, err := pgsr.ReadSequenceState(ctx, schema)
	if err != nil {
		t.Fatalf("read sequence state: %v", err)
	}

	sw, _ := Engine{}.OpenSchemaWriter(ctx, tgtDSN)
	pgsw := sw.(*SchemaWriter)

	margin := int64(1000)
	report, err := pgsw.PrimeSequences(ctx, schema, states, margin)
	if !errors.Is(err, ir.ErrCutoverSequenceTargetAhead) {
		t.Errorf("err = %v; want ErrCutoverSequenceTargetAhead", err)
	}
	if report == nil || len(report.Actions) != 1 {
		t.Fatalf("report = %+v; want one action", report)
	}
	if report.Actions[0].Outcome != "refused" {
		t.Errorf("outcome = %q; want %q", report.Actions[0].Outcome, "refused")
	}
}

// TestCutoverSequencePrimer_PG_SkipsCompositePK pins the no-sequence
// path: a table with composite PK and no identity column is omitted
// from the source-side read (no entry in states) and yields no action
// on the target.
func TestCutoverSequencePrimer_PG_SkipsCompositePK(t *testing.T) {
	srcDSN, srcCleanup := startPostgres(t)
	defer srcCleanup()
	tgtDSN, tgtCleanup := startPostgres(t)
	defer tgtCleanup()

	applyDDL(t, srcDSN, `
		CREATE TABLE memberships (
			user_id  BIGINT NOT NULL,
			group_id BIGINT NOT NULL,
			PRIMARY KEY (user_id, group_id)
		);
	`)
	applyDDL(t, tgtDSN, `
		CREATE TABLE memberships (
			user_id  BIGINT NOT NULL,
			group_id BIGINT NOT NULL,
			PRIMARY KEY (user_id, group_id)
		);
	`)

	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()

	sr, _ := Engine{}.OpenSchemaReader(ctx, srcDSN)
	defer closeReader(t, sr)
	pgsr := sr.(*SchemaReader)
	schema, err := pgsr.ReadSchema(ctx)
	if err != nil {
		t.Fatalf("read schema: %v", err)
	}
	states, err := pgsr.ReadSequenceState(ctx, schema)
	if err != nil {
		t.Fatalf("read sequence state: %v", err)
	}
	if len(states) != 0 {
		t.Errorf("states = %+v; want empty (no identity columns)", states)
	}

	sw, _ := Engine{}.OpenSchemaWriter(ctx, tgtDSN)
	pgsw := sw.(*SchemaWriter)

	report, err := pgsw.PrimeSequences(ctx, schema, states, 1000)
	if err != nil {
		t.Fatalf("PrimeSequences err = %v", err)
	}
	// The IR doesn't tag identity on the composite-PK columns, so the
	// primer's per-table walk reaches no AutoIncrement column — the
	// action list is empty.
	if len(report.Actions) != 0 {
		t.Errorf("actions = %+v; want empty (composite PK has no sequence)", report.Actions)
	}
}
