// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

package postgres

import (
	"strings"
	"testing"

	"github.com/orware/sluice/internal/ir"
)

func TestEmitColumnType(t *testing.T) {
	cases := []struct {
		name string
		in   ir.Type
		want string
	}{
		// ---- Numeric / boolean ----
		{"boolean", ir.Boolean{}, "BOOLEAN"},
		{"smallint", ir.Integer{Width: 16}, "SMALLINT"},
		{"integer", ir.Integer{Width: 32}, "INTEGER"},
		{"bigint", ir.Integer{Width: 64}, "BIGINT"},
		{"int auto", ir.Integer{Width: 32, AutoIncrement: true}, "INTEGER GENERATED BY DEFAULT AS IDENTITY"},
		{"bigint auto", ir.Integer{Width: 64, AutoIncrement: true}, "BIGINT GENERATED BY DEFAULT AS IDENTITY"},
		{"unsigned int → bigint", ir.Integer{Width: 32, Unsigned: true}, "BIGINT"},
		{"unsigned tinyint → smallint", ir.Integer{Width: 8, Unsigned: true}, "SMALLINT"},
		{"unsigned bigint → numeric(20,0)", ir.Integer{Width: 64, Unsigned: true}, "NUMERIC(20,0)"},
		{"unsigned bigint auto → bigint identity", ir.Integer{Width: 64, Unsigned: true, AutoIncrement: true}, "BIGINT GENERATED BY DEFAULT AS IDENTITY"},
		{"decimal", ir.Decimal{Precision: 10, Scale: 2}, "NUMERIC(10,2)"},
		{"real", ir.Float{Precision: ir.FloatSingle}, "REAL"},
		{"double", ir.Float{Precision: ir.FloatDouble}, "DOUBLE PRECISION"},

		// ---- Character / binary ----
		{"char", ir.Char{Length: 10}, "CHAR(10)"},
		{"varchar", ir.Varchar{Length: 255}, "VARCHAR(255)"},
		{"text any size", ir.Text{Size: ir.TextRegular}, "TEXT"},
		{"text long", ir.Text{Size: ir.TextLong}, "TEXT"},
		{"binary → bytea", ir.Binary{Length: 16}, "BYTEA"},
		{"varbinary → bytea", ir.Varbinary{Length: 64}, "BYTEA"},
		{"blob → bytea", ir.Blob{Size: ir.BlobLong}, "BYTEA"},

		// ---- Temporal ----
		{"date", ir.Date{}, "DATE"},
		{"time precision 0", ir.Time{Precision: 0}, "TIME"},
		{"time precision 6", ir.Time{Precision: 6}, "TIME(6)"},
		{"datetime precision 0", ir.DateTime{Precision: 0}, "TIMESTAMP"},
		{"datetime precision 3", ir.DateTime{Precision: 3}, "TIMESTAMP(3)"},
		{"timestamp", ir.Timestamp{Precision: 0, WithTimeZone: false}, "TIMESTAMP"},
		{"timestamptz", ir.Timestamp{Precision: 6, WithTimeZone: true}, "TIMESTAMP(6) WITH TIME ZONE"},

		// ---- Structured ----
		{"json", ir.JSON{Binary: false}, "JSON"},
		{"jsonb", ir.JSON{Binary: true}, "JSONB"},

		// ---- Identity / network ----
		{"uuid", ir.UUID{}, "UUID"},
		{"inet", ir.Inet{}, "INET"},
		{"cidr", ir.Cidr{}, "CIDR"},
		{"macaddr", ir.Macaddr{}, "MACADDR"},

		// ---- Arrays ----
		{"int array", ir.Array{Element: ir.Integer{Width: 32}}, "INTEGER[]"},
		{"text array", ir.Array{Element: ir.Text{Size: ir.TextLong}}, "TEXT[]"},
		{"uuid array", ir.Array{Element: ir.UUID{}}, "UUID[]"},

		// ---- Set → TEXT[] (membership CHECK emitted by emitTableDef) ----
		{"set", ir.Set{Values: []string{"a", "b", "c"}}, "TEXT[]"},
		{"empty set", ir.Set{Values: nil}, "TEXT[]"},
	}

	for _, c := range cases {
		c := c
		t.Run(c.name, func(t *testing.T) {
			got, err := emitColumnType(c.in, emitOpts{})
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if got != c.want {
				t.Errorf("emitColumnType(%T) = %q; want %q", c.in, got, c.want)
			}
		})
	}
}

func TestEmitColumnTypeUnsupported(t *testing.T) {
	cases := []ir.Type{
		ir.Geometry{Subtype: ir.GeometryPoint},
		ir.Enum{Values: []string{"x"}}, // requires column context
	}
	for _, c := range cases {
		c := c
		t.Run("unsupported", func(t *testing.T) {
			if _, err := emitColumnType(c, emitOpts{}); err == nil {
				t.Errorf("expected error for %T", c)
			}
		})
	}
}

// TestEmitColumnType_PgvectorEnabled emits the canonical
// `vector(384)` form when the operator opted into the pgvector
// extension via emitOpts.EnabledExtensions. This is the
// load-bearing same-engine PG → PG passthrough path (ADR-0032).
func TestEmitColumnType_PgvectorEnabled(t *testing.T) {
	got, err := emitColumnType(
		ir.ExtensionType{Extension: "vector", Name: "vector", Modifiers: []int{384}},
		emitOpts{EnabledExtensions: map[string]bool{"vector": true}},
	)
	if err != nil {
		t.Fatalf("emitColumnType: %v", err)
	}
	if got != "vector(384)" {
		t.Errorf("emitColumnType = %q; want %q", got, "vector(384)")
	}
}

// TestEmitColumnType_PgvectorDisabled refuses pgvector columns
// when the operator didn't opt in via --enable-pg-extension.
// Defends against the "ExtensionType reached the writer through a
// hand-constructed IR" path; the operator-actionable error names
// the missing flag.
func TestEmitColumnType_PgvectorDisabled(t *testing.T) {
	_, err := emitColumnType(
		ir.ExtensionType{Extension: "vector", Name: "vector", Modifiers: []int{384}},
		emitOpts{},
	)
	if err == nil {
		t.Fatal("expected error when extension is not enabled; got nil")
	}
	if !strings.Contains(err.Error(), "--enable-pg-extension") {
		t.Errorf("err = %v; want contains \"--enable-pg-extension\"", err)
	}
}

// TestResolveIndexMethod_PrefersVerbatimMethod ensures the writer
// emits the IR's verbatim Method (pgvector's ivfflat / hnsw) ahead
// of the canonical Kind dispatch — the load-bearing path for
// extension-introduced index methods round-tripping through PG → PG.
func TestResolveIndexMethod_PrefersVerbatimMethod(t *testing.T) {
	cases := []struct {
		name string
		idx  *ir.Index
		want string
	}{
		{
			"ivfflat verbatim",
			&ir.Index{Method: "ivfflat", Kind: ir.IndexKindUnspecified},
			"ivfflat",
		},
		{
			"hnsw verbatim",
			&ir.Index{Method: "hnsw", Kind: ir.IndexKindUnspecified},
			"hnsw",
		},
		{
			"falls back to Kind when Method empty",
			&ir.Index{Kind: ir.IndexKindGIN},
			"gin",
		},
		{
			"empty Kind + empty Method returns empty",
			&ir.Index{},
			"",
		},
		{
			"nil index returns empty",
			nil,
			"",
		},
	}
	for _, c := range cases {
		c := c
		t.Run(c.name, func(t *testing.T) {
			got := resolveIndexMethod(c.idx)
			if got != c.want {
				t.Errorf("resolveIndexMethod = %q; want %q", got, c.want)
			}
		})
	}
}

// TestEmitCreateIndex_PgvectorIVFFlat exercises the full CREATE
// INDEX rendering for a pgvector ivfflat index — the shape the PG →
// PG passthrough must round-trip verbatim.
func TestEmitCreateIndex_PgvectorIVFFlat(t *testing.T) {
	idx := &ir.Index{
		Name:    "idx_items_embedding_ivfflat",
		Method:  "ivfflat",
		Kind:    ir.IndexKindUnspecified,
		Columns: []ir.IndexColumn{{Column: "embedding"}},
	}
	got, err := emitCreateIndex("public", "items", idx)
	if err != nil {
		t.Fatalf("emitCreateIndex: %v", err)
	}
	if !strings.Contains(got, "USING ivfflat") {
		t.Errorf("emitCreateIndex output missing USING ivfflat: %q", got)
	}
}

// TestEmitSetCheckConstraint covers the table-level CHECK fragment
// the SET → TEXT[] policy emits. The constraint is what enforces the
// "members must be in the source's value list" guarantee on the PG
// target after the type translation.
func TestEmitSetCheckConstraint(t *testing.T) {
	cases := []struct {
		name   string
		table  string
		column string
		values []string
		want   string
	}{
		{
			"basic three-member SET",
			"events", "flags",
			[]string{"a", "b", "c"},
			`CONSTRAINT "events_flags_set" CHECK ("flags" <@ ARRAY['a','b','c']::TEXT[])`,
		},
		{
			"empty value list",
			"events", "flags",
			nil,
			`CONSTRAINT "events_flags_set" CHECK ("flags" <@ '{}'::TEXT[])`,
		},
		{
			"member containing apostrophe",
			"t", "c",
			[]string{"a'b"},
			`CONSTRAINT "t_c_set" CHECK ("c" <@ ARRAY['a''b']::TEXT[])`,
		},
	}
	for _, c := range cases {
		c := c
		t.Run(c.name, func(t *testing.T) {
			got := emitSetCheckConstraint(c.table, c.column, c.values)
			if got != c.want {
				t.Errorf("\n got:  %s\nwant:  %s", got, c.want)
			}
		})
	}
}

// TestSetDefaultToArrayLiteral covers the comma-separated → PG
// array-literal translation used when a SET column's source DEFAULT
// crosses into a TEXT[] target.
func TestSetDefaultToArrayLiteral(t *testing.T) {
	cases := []struct {
		in   string
		want string
	}{
		{"", "'{}'::TEXT[]"},
		{"a", "ARRAY['a']::TEXT[]"},
		{"a,b", "ARRAY['a','b']::TEXT[]"},
		{"a,b,c", "ARRAY['a','b','c']::TEXT[]"},
		{"a'b", "ARRAY['a''b']::TEXT[]"},
	}
	for _, c := range cases {
		c := c
		t.Run(c.in, func(t *testing.T) {
			got := setDefaultToArrayLiteral(c.in)
			if got != c.want {
				t.Errorf("\n got:  %s\nwant:  %s", got, c.want)
			}
		})
	}
}

// TestEmitTableDef_SETColumn covers the integration between
// emitColumnType (TEXT[]), the SET CHECK constraint emission, and
// the SET-default translation in emitColumnDef.
// TestEmitTableDef_GeneratedEnum_AsTextWithCheck pins Bug 25's
// fix: an enum-typed STORED generated column emits as TEXT (no
// enum type reference, since `(body)::enum_type` would trip PG's
// IMMUTABLE check) and gets a table-level CHECK enforcing the
// value-list. Mirrors the SET → TEXT[] + CHECK fallback shape.
func TestEmitTableDef_GeneratedEnum_AsTextWithCheck(t *testing.T) {
	tbl := &ir.Table{
		Name: "shipments",
		Columns: []*ir.Column{
			{Name: "id", Type: ir.Integer{Width: 64}, Nullable: false},
			{Name: "picked_at", Type: ir.Timestamp{Precision: 6}, Nullable: true},
			{
				Name:            "pickup_status",
				Type:            ir.Enum{Values: []string{"pending", "picked", "cancelled"}},
				Nullable:        true,
				GeneratedExpr:   "CASE WHEN picked_at IS NULL THEN 'pending' ELSE 'picked' END",
				GeneratedStored: true,
			},
		},
		PrimaryKey: &ir.Index{Columns: []ir.IndexColumn{{Column: "id"}}},
	}
	got, err := emitTableDef("public", tbl, emitOpts{})
	if err != nil {
		t.Fatalf("emitTableDef: %v", err)
	}
	wantContains := []string{
		// Column emits as TEXT, not as the enum type, and the body
		// is unwrapped (no ::enum_type cast).
		`"pickup_status" TEXT GENERATED ALWAYS AS (CASE WHEN picked_at IS NULL THEN 'pending' ELSE 'picked' END) STORED`,
		// Table-level CHECK enforces the value-list. Constraint name
		// uses the `_enum_chk` suffix to disambiguate from `_set` and
		// `_enum` (the type name).
		`CONSTRAINT "shipments_pickup_status_enum_chk" CHECK ("pickup_status" IN ('pending','picked','cancelled'))`,
	}
	for _, sub := range wantContains {
		if !strings.Contains(got, sub) {
			t.Errorf("CREATE TABLE missing %q\n--- got ---\n%s", sub, got)
		}
	}
	// Sanity: the column DOES NOT reference the enum type by name.
	// If a future refactor reintroduces the `::enum_type` cast or
	// the type-named column form, this catches it.
	if strings.Contains(got, `"shipments_pickup_status_enum"`) {
		t.Errorf("emitted DDL references the enum type name; should be TEXT-only for generated enums:\n%s", got)
	}
}

func TestEmitTableDef_SETColumn(t *testing.T) {
	tbl := &ir.Table{
		Name: "events",
		Columns: []*ir.Column{
			{Name: "id", Type: ir.Integer{Width: 64}, Nullable: false},
			{
				Name:     "flags",
				Type:     ir.Set{Values: []string{"a", "b", "c"}},
				Nullable: false,
				Default:  ir.DefaultLiteral{Value: "a,b"},
			},
		},
		PrimaryKey: &ir.Index{
			Columns: []ir.IndexColumn{{Column: "id"}},
		},
	}
	got, err := emitTableDef("public", tbl, emitOpts{})
	if err != nil {
		t.Fatalf("emitTableDef: %v", err)
	}
	wantContains := []string{
		`"flags" TEXT[] NOT NULL DEFAULT ARRAY['a','b']::TEXT[]`,
		`CONSTRAINT "events_flags_set" CHECK ("flags" <@ ARRAY['a','b','c']::TEXT[])`,
		`PRIMARY KEY ("id")`,
	}
	for _, sub := range wantContains {
		if !strings.Contains(got, sub) {
			t.Errorf("CREATE TABLE missing %q\n--- got ---\n%s", sub, got)
		}
	}
}

func TestEmitDefault(t *testing.T) {
	cases := []struct {
		name     string
		in       ir.DefaultValue
		want     string
		wantEmit bool
	}{
		{"none", ir.DefaultNone{}, "", false},
		{"nil", nil, "", false},
		{"literal zero", ir.DefaultLiteral{Value: "0"}, "'0'", true},
		{"literal text", ir.DefaultLiteral{Value: "hello"}, "'hello'", true},
		{"literal with quote", ir.DefaultLiteral{Value: "it's"}, "'it''s'", true},
		{"expression no dialect", ir.DefaultExpression{Expr: "now()"}, "now()", true},
		// v0.11.3 — DEFAULT-expression dialect-gated translation.
		// Bugs 28/29/30: pre-fix the DEFAULT path bypassed the
		// translator entirely. Post-fix, MySQL-tagged defaults route
		// through the same MySQL→PG rewrites as generated columns and
		// CHECK constraints. PG-tagged or untagged defaults still
		// emit verbatim.
		{
			"expression mysql dialect: UUID() translates",
			ir.DefaultExpression{Expr: "UUID()", Dialect: "mysql"},
			"gen_random_uuid()", true,
		},
		{
			"expression mysql dialect: RAND() translates",
			ir.DefaultExpression{Expr: "RAND()", Dialect: "mysql"},
			"RANDOM()", true,
		},
		{
			"expression mysql dialect: NOW() translates to keyword",
			ir.DefaultExpression{Expr: "NOW()", Dialect: "mysql"},
			"CURRENT_TIMESTAMP", true,
		},
		{
			"expression postgres dialect emits verbatim",
			ir.DefaultExpression{Expr: "now()", Dialect: "postgres"},
			"now()", true,
		},
		{
			"expression mysql dialect with unrecognised function passes through verbatim",
			ir.DefaultExpression{Expr: "WEIRD_FN()", Dialect: "mysql"},
			"WEIRD_FN()", true,
		},
	}
	for _, c := range cases {
		c := c
		t.Run(c.name, func(t *testing.T) {
			got, ok := emitDefault(c.in)
			if ok != c.wantEmit {
				t.Errorf("emit flag = %v; want %v", ok, c.wantEmit)
			}
			if got != c.want {
				t.Errorf("emitDefault = %q; want %q", got, c.want)
			}
		})
	}
}

func TestEmitColumnDef(t *testing.T) {
	usersTable := &ir.Table{Name: "users"}

	cases := []struct {
		name string
		in   *ir.Column
		want string
	}{
		{
			name: "id bigint identity not null",
			in: &ir.Column{
				Name: "id",
				Type: ir.Integer{Width: 64, AutoIncrement: true},
			},
			want: `"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL`,
		},
		{
			name: "active boolean default true",
			in: &ir.Column{
				Name:    "active",
				Type:    ir.Boolean{},
				Default: ir.DefaultLiteral{Value: "true"},
			},
			want: `"active" BOOLEAN NOT NULL DEFAULT 'true'`,
		},
		{
			name: "created_at default now()",
			in: &ir.Column{
				Name:    "created_at",
				Type:    ir.Timestamp{Precision: 6, WithTimeZone: true},
				Default: ir.DefaultExpression{Expr: "now()"},
			},
			want: `"created_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT now()`,
		},
		{
			name: "nullable text",
			in: &ir.Column{
				Name:     "notes",
				Type:     ir.Text{Size: ir.TextLong},
				Nullable: true,
			},
			want: `"notes" TEXT`,
		},
		{
			name: "enum with type-name reference",
			in: &ir.Column{
				Name: "role",
				Type: ir.Enum{Values: []string{"admin", "user"}},
			},
			want: `"role" "users_role_enum" NOT NULL`,
		},
		{
			// Cross-engine MySQL → PG with `rating ENUM(...) DEFAULT 'G'`
			// must emit the explicit type cast on the default; without
			// the cast Postgres rejects the literal as "invalid input
			// value for enum ...".
			name: "enum with default literal needs explicit type cast",
			in: &ir.Column{
				Name:    "rating",
				Type:    ir.Enum{Values: []string{"G", "PG", "PG-13", "R", "NC-17"}},
				Default: ir.DefaultLiteral{Value: "G"},
			},
			want: `"rating" "users_rating_enum" NOT NULL DEFAULT 'G'::"users_rating_enum"`,
		},
		{
			// Bug 23: MySQL's `DEFAULT ('pending')` parenthesised form
			// arrives as DefaultExpression{Expr: "'pending'"} via
			// information_schema's EXTRA=DEFAULT_GENERATED. The
			// expression body is a string literal so the cast must
			// still fire — without it PG rejects with "column X is
			// of type Y_enum but default expression is of type text".
			name: "enum with paren-literal expression default also gets cast",
			in: &ir.Column{
				Name:     "rating",
				Type:     ir.Enum{Values: []string{"G", "PG", "R"}},
				Nullable: true,
				Default:  ir.DefaultExpression{Expr: "'PG'"},
			},
			want: `"rating" "users_rating_enum" DEFAULT 'PG'::"users_rating_enum"`,
		},
		{
			// Bug 23 negative: a true expression default (not a
			// string-literal-shaped one) does NOT get the cast — the
			// cast wouldn't be safe and the resulting CREATE TABLE
			// would fail loudly on the target if the operator's
			// expression isn't enum-compatible.
			name: "enum with non-literal expression default is not cast",
			in: &ir.Column{
				Name:     "rating",
				Type:     ir.Enum{Values: []string{"G", "PG", "R"}},
				Nullable: true,
				Default:  ir.DefaultExpression{Expr: "current_setting('app.default_rating')"},
			},
			want: `"rating" "users_rating_enum" DEFAULT current_setting('app.default_rating')`,
		},
	}

	for _, c := range cases {
		c := c
		t.Run(c.name, func(t *testing.T) {
			got, err := emitColumnDef(usersTable, c.in, emitOpts{})
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if got != c.want {
				t.Errorf("\n got  %q\n want %q", got, c.want)
			}
		})
	}
}

// TestEmitColumnDef_Generated covers GENERATED ALWAYS AS (...) STORED
// emission. Postgres only supports STORED; a VIRTUAL source column is
// silently promoted with a slog warning (verified separately by the
// integration test that exercises a MySQL VIRTUAL → PG path).
func TestEmitColumnDef_Generated(t *testing.T) {
	tbl := &ir.Table{Name: "invoices"}

	cases := []struct {
		name string
		in   *ir.Column
		want string
	}{
		{
			name: "stored generated bigint",
			in: &ir.Column{
				Name:            "total",
				Type:            ir.Integer{Width: 64},
				GeneratedExpr:   "qty * price",
				GeneratedStored: true,
			},
			want: `"total" BIGINT GENERATED ALWAYS AS (qty * price) STORED NOT NULL`,
		},
		{
			name: "virtual source column promoted to stored",
			in: &ir.Column{
				Name:            "tax",
				Type:            ir.Decimal{Precision: 10, Scale: 2},
				Nullable:        true,
				GeneratedExpr:   "subtotal * 0.07",
				GeneratedStored: false,
			},
			want: `"tax" NUMERIC(10,2) GENERATED ALWAYS AS (subtotal * 0.07) STORED`,
		},
		{
			// Bug 25 (v0.10.1): enum-typed STORED generated columns
			// can't reference the enum type — `(body)::enum_type`
			// triggers PG's "generation expression is not immutable"
			// error because `enum_in()` is STABLE not IMMUTABLE.
			// Sluice sidesteps by emitting the column as TEXT (no
			// enum type, no cast); a table-level CHECK constraint
			// (added by emitTableDef) enforces the value-list. The
			// previous v0.9.2/v0.10.0 (body)::enum_type wrapper is
			// gone — see emitTableDef test for the CHECK side.
			name: "enum-typed generated column emits as TEXT (Bug 25)",
			in: &ir.Column{
				Name:            "pickup_status",
				Type:            ir.Enum{Values: []string{"pending", "picked", "cancelled"}},
				Nullable:        true,
				GeneratedExpr:   "CASE WHEN picked_at IS NULL THEN 'pending' ELSE 'picked' END",
				GeneratedStored: true,
			},
			want: `"pickup_status" TEXT GENERATED ALWAYS AS (CASE WHEN picked_at IS NULL THEN 'pending' ELSE 'picked' END) STORED`,
		},
	}
	for _, c := range cases {
		c := c
		t.Run(c.name, func(t *testing.T) {
			got, err := emitColumnDef(tbl, c.in, emitOpts{})
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if got != c.want {
				t.Errorf("\n got  %q\n want %q", got, c.want)
			}
		})
	}
}

// TestEmitCheckConstraint covers the standalone CHECK fragment used
// inline in CREATE TABLE bodies. Verbatim-passthrough policy: the
// expression text is preserved as-is.
func TestEmitCheckConstraint(t *testing.T) {
	cases := []struct {
		name string
		in   *ir.CheckConstraint
		want string
	}{
		{
			name: "named with comparison",
			in:   &ir.CheckConstraint{Name: "orders_qty_chk", Expr: "qty >= 0"},
			want: `CONSTRAINT "orders_qty_chk" CHECK (qty >= 0)`,
		},
		{
			name: "named with IN list",
			in: &ir.CheckConstraint{
				Name: "orders_status_chk",
				Expr: "status IN ('open','closed','cancelled')",
			},
			want: `CONSTRAINT "orders_status_chk" CHECK (status IN ('open','closed','cancelled'))`,
		},
		{
			name: "unnamed",
			in:   &ir.CheckConstraint{Expr: "start_date <= end_date"},
			want: `CHECK (start_date <= end_date)`,
		},
	}
	for _, c := range cases {
		c := c
		t.Run(c.name, func(t *testing.T) {
			if got := emitCheckConstraint(c.in, nil); got != c.want {
				t.Errorf("\n got  %q\n want %q", got, c.want)
			}
		})
	}
}

// TestEmitTableDef_CheckConstraints exercises the inline-emission
// path: user-declared CHECK clauses appear in the CREATE TABLE body
// alongside any synthetic SET-membership CHECKs, in source order.
func TestEmitTableDef_CheckConstraints(t *testing.T) {
	tbl := &ir.Table{
		Name: "orders",
		Columns: []*ir.Column{
			{Name: "id", Type: ir.Integer{Width: 64}},
			{Name: "qty", Type: ir.Integer{Width: 32}},
			{Name: "status", Type: ir.Varchar{Length: 20}},
		},
		PrimaryKey: &ir.Index{
			Columns: []ir.IndexColumn{{Column: "id"}},
		},
		CheckConstraints: []*ir.CheckConstraint{
			{Name: "orders_qty_chk", Expr: "qty >= 0"},
			{Name: "orders_status_chk", Expr: "status IN ('open','closed')"},
		},
	}
	got, err := emitTableDef("public", tbl, emitOpts{})
	if err != nil {
		t.Fatalf("emitTableDef: %v", err)
	}
	wants := []string{
		`CONSTRAINT "orders_qty_chk" CHECK (qty >= 0)`,
		`CONSTRAINT "orders_status_chk" CHECK (status IN ('open','closed'))`,
		`PRIMARY KEY ("id")`,
	}
	for _, w := range wants {
		if !strings.Contains(got, w) {
			t.Errorf("output missing %q; got:\n%s", w, got)
		}
	}
}

func TestEmitCreateEnumType(t *testing.T) {
	got := emitCreateEnumType("public", "users", "role", []string{"admin", "user", "guest"})
	want := `CREATE TYPE "public"."users_role_enum" AS ENUM ('admin', 'user', 'guest');`
	if got != want {
		t.Errorf("\n got  %q\n want %q", got, want)
	}
}

func TestEmitTableDef(t *testing.T) {
	table := &ir.Table{
		Name: "users",
		Columns: []*ir.Column{
			{Name: "id", Type: ir.Integer{Width: 64, AutoIncrement: true}},
			{Name: "email", Type: ir.Varchar{Length: 255}},
		},
		PrimaryKey: &ir.Index{
			Name:    "PRIMARY",
			Unique:  true,
			Columns: []ir.IndexColumn{{Column: "id"}},
		},
	}
	got, err := emitTableDef("public", table, emitOpts{})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	wants := []string{
		`CREATE TABLE IF NOT EXISTS "public"."users" (`,
		`"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,`,
		`"email" VARCHAR(255) NOT NULL,`,
		`PRIMARY KEY ("id")`,
	}
	for _, w := range wants {
		if !strings.Contains(got, w) {
			t.Errorf("output missing %q; got:\n%s", w, got)
		}
	}
}

// Bug 45 (v0.25.1): when `--target-schema=NAME` is set on a PG
// target, the column-type ident and the `::cast` suffix on enum
// DEFAULT expressions must both be schema-qualified — the bare
// ident relies on `search_path` which doesn't include per-source
// namespaces, and CREATE TABLE fails with SQLSTATE 42704 "type does
// not exist". Verifies emitColumnDef + emitTableDef produce
// `"customer_svc"."t_c_enum"` shape under non-empty TargetSchema.
func TestEmitColumnDef_TargetSchemaQualifiesEnumIdentAndCast(t *testing.T) {
	tbl := &ir.Table{Name: "orders"}
	col := &ir.Column{
		Name:    "status",
		Type:    ir.Enum{Values: []string{"pending", "paid", "shipped"}},
		Default: ir.DefaultLiteral{Value: "pending"},
	}
	got, err := emitColumnDef(tbl, col, emitOpts{TargetSchema: "customer_svc"})
	if err != nil {
		t.Fatalf("emitColumnDef: %v", err)
	}
	want := `"status" "customer_svc"."orders_status_enum" NOT NULL DEFAULT 'pending'::"customer_svc"."orders_status_enum"`
	if got != want {
		t.Errorf("\n got  %q\n want %q", got, want)
	}
}

// TestEmitColumnDef_NoTargetSchemaPreservesUnqualifiedShape pins
// the pre-Bug-45 shape: when TargetSchema is empty, enum idents and
// casts emit unqualified — the type lives in the DSN's default
// schema (typically `public`) which is in `search_path`, so the
// bare ident resolves correctly.
func TestEmitColumnDef_NoTargetSchemaPreservesUnqualifiedShape(t *testing.T) {
	tbl := &ir.Table{Name: "orders"}
	col := &ir.Column{
		Name:    "status",
		Type:    ir.Enum{Values: []string{"pending", "paid"}},
		Default: ir.DefaultLiteral{Value: "pending"},
	}
	got, err := emitColumnDef(tbl, col, emitOpts{})
	if err != nil {
		t.Fatalf("emitColumnDef: %v", err)
	}
	want := `"status" "orders_status_enum" NOT NULL DEFAULT 'pending'::"orders_status_enum"`
	if got != want {
		t.Errorf("\n got  %q\n want %q", got, want)
	}
}

// TestEmitTableDef_TargetSchemaQualifiesEnumColumnAndCast asserts
// the full CREATE TABLE statement under --target-schema carries
// schema-qualified type idents inside the column list — the
// load-bearing shape from BUG-CATALOG Bug 45's repro section.
func TestEmitTableDef_TargetSchemaQualifiesEnumColumnAndCast(t *testing.T) {
	tbl := &ir.Table{
		Name: "orders",
		Columns: []*ir.Column{
			{Name: "id", Type: ir.Integer{Width: 64, AutoIncrement: true}},
			{
				Name:    "status",
				Type:    ir.Enum{Values: []string{"pending", "paid", "shipped"}},
				Default: ir.DefaultLiteral{Value: "pending"},
			},
		},
		PrimaryKey: &ir.Index{
			Name:    "orders_pkey",
			Unique:  true,
			Columns: []ir.IndexColumn{{Column: "id"}},
		},
	}
	got, err := emitTableDef("customer_svc", tbl, emitOpts{TargetSchema: "customer_svc"})
	if err != nil {
		t.Fatalf("emitTableDef: %v", err)
	}
	wants := []string{
		`CREATE TABLE IF NOT EXISTS "customer_svc"."orders" (`,
		`"status" "customer_svc"."orders_status_enum" NOT NULL DEFAULT 'pending'::"customer_svc"."orders_status_enum"`,
	}
	for _, w := range wants {
		if !strings.Contains(got, w) {
			t.Errorf("output missing %q; got:\n%s", w, got)
		}
	}
}

// TestSchemaWriter_QualifyingSchema_TogglesOnSetSchema verifies the
// schema_writer's qualifyingSchema policy: bare ident before
// SetSchema, schema-qualified after the operator-supplied override.
func TestSchemaWriter_QualifyingSchema_TogglesOnSetSchema(t *testing.T) {
	w := &SchemaWriter{schema: "public"}
	if got := w.qualifyingSchema(); got != "" {
		t.Errorf("qualifyingSchema() before SetSchema = %q; want empty (default-public preserves bare ident)", got)
	}
	w.SetSchema("customer_svc")
	if got := w.qualifyingSchema(); got != "customer_svc" {
		t.Errorf("qualifyingSchema() after SetSchema = %q; want customer_svc", got)
	}
}

func TestEmitCreateIndex(t *testing.T) {
	cases := []struct {
		name string
		idx  *ir.Index
		want string
	}{
		{
			name: "secondary unique btree",
			idx: &ir.Index{
				Name:    "users_email_unique",
				Unique:  true,
				Kind:    ir.IndexKindBTree,
				Columns: []ir.IndexColumn{{Column: "email"}},
			},
			want: `CREATE UNIQUE INDEX "users_email_unique" ON "public"."users" USING btree ("email");`,
		},
		{
			name: "non-unique multi-column",
			idx: &ir.Index{
				Name: "users_lookup",
				Kind: ir.IndexKindBTree,
				Columns: []ir.IndexColumn{
					{Column: "tenant_id"},
					{Column: "created_at", Desc: true},
				},
			},
			want: `CREATE INDEX "users_lookup" ON "public"."users" USING btree ("tenant_id", "created_at" DESC);`,
		},
		{
			// Index name doesn't start with the table name, so the
			// PG emitter prefixes it to disambiguate against the
			// schema-scoped Postgres namespace (a sibling table
			// might use the same source-side index name).
			name: "gin index — name gets table prefix",
			idx: &ir.Index{
				Name:    "posts_search",
				Kind:    ir.IndexKindGIN,
				Columns: []ir.IndexColumn{{Column: "tsv"}},
			},
			want: `CREATE INDEX "users_posts_search" ON "public"."users" USING gin ("tsv");`,
		},
		{
			// Source-side name like MySQL's idx_fk_film_id, which
			// appears on multiple tables in real-world schemas
			// (sakila has it on inventory, film_actor, etc.). The
			// table-prefix disambiguation is what makes the
			// cross-engine migration work.
			name: "common collision-prone name gets table prefix",
			idx: &ir.Index{
				Name:    "idx_fk_film_id",
				Kind:    ir.IndexKindBTree,
				Columns: []ir.IndexColumn{{Column: "film_id"}},
			},
			want: `CREATE INDEX "users_idx_fk_film_id" ON "public"."users" USING btree ("film_id");`,
		},
		{
			// Same-dialect (PG-source) expression — passes through
			// verbatim with no translation.
			name: "same-dialect expression passes through verbatim",
			idx: &ir.Index{
				Name: "users_lower_email",
				Kind: ir.IndexKindBTree,
				Columns: []ir.IndexColumn{
					{Expression: "lower(email)", ExpressionDialect: "postgres"},
				},
			},
			want: `CREATE INDEX "users_lower_email" ON "public"."users" USING btree ((lower(email)));`,
		},
		{
			// MySQL-source expression with a JSON_UNQUOTE+JSON_EXTRACT
			// chain — the ADR-0016 translator rewrites to PG's ->>
			// idiom on emit (Bug 16 follow-up). Without this, the
			// expression would emit verbatim and PG would reject the
			// CREATE INDEX with "function json_unquote(json) does not
			// exist".
			name: "MySQL-source JSON expression rewrites to PG ->>",
			idx: &ir.Index{
				Name: "containers_pickup_status",
				Kind: ir.IndexKindBTree,
				Columns: []ir.IndexColumn{
					{Expression: "json_unquote(json_extract(meta,'$.color'))", ExpressionDialect: "mysql"},
				},
			},
			want: `CREATE INDEX "users_containers_pickup_status" ON "public"."users" USING btree (((meta->>'color')));`,
		},
		{
			// SP-GiST round-trip (Bug 50): pre-fix the enum was
			// IndexKindUnspecified for spgist and the writer dropped
			// the AM, falling back to btree. With the enum populated
			// the writer emits `USING spgist`.
			name: "spgist index",
			idx: &ir.Index{
				Name:    "geom_spgist",
				Kind:    ir.IndexKindSPGist,
				Columns: []ir.IndexColumn{{Column: "geom", OperatorClass: "spgist_geometry_ops_2d"}},
			},
			want: `CREATE INDEX "users_geom_spgist" ON "public"."users" USING spgist ("geom" spgist_geometry_ops_2d);`,
		},
		{
			// BRIN round-trip (Bug 50): same shape as SP-GiST above.
			name: "brin index",
			idx: &ir.Index{
				Name:    "geom_brin",
				Kind:    ir.IndexKindBRIN,
				Columns: []ir.IndexColumn{{Column: "geom", OperatorClass: "brin_geometry_inclusion_ops_2d"}},
			},
			want: `CREATE INDEX "users_geom_brin" ON "public"."users" USING brin ("geom" brin_geometry_inclusion_ops_2d);`,
		},
		{
			// Untagged expression (older IR / hand-built fixtures)
			// emits verbatim — same as the pre-Bug-16-follow-up
			// behaviour.
			name: "untagged expression passes through verbatim",
			idx: &ir.Index{
				Name: "users_lower_legacy",
				Kind: ir.IndexKindBTree,
				Columns: []ir.IndexColumn{
					{Expression: "lower(email)"},
				},
			},
			want: `CREATE INDEX "users_lower_legacy" ON "public"."users" USING btree ((lower(email)));`,
		},
	}
	for _, c := range cases {
		c := c
		t.Run(c.name, func(t *testing.T) {
			got, err := emitCreateIndex("public", "users", c.idx)
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if got != c.want {
				t.Errorf("\n got  %q\n want %q", got, c.want)
			}
		})
	}
}

func TestEmitAddForeignKey(t *testing.T) {
	fk := &ir.ForeignKey{
		Name:              "posts_user_id_fk",
		Columns:           []string{"user_id"},
		ReferencedTable:   "users",
		ReferencedColumns: []string{"id"},
		OnDelete:          ir.FKActionCascade,
		OnUpdate:          ir.FKActionRestrict,
	}
	got, err := emitAddForeignKey("public", "posts", fk)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	want := `ALTER TABLE "public"."posts" ADD CONSTRAINT "posts_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON DELETE CASCADE ON UPDATE RESTRICT;`
	if got != want {
		t.Errorf("\n got  %q\n want %q", got, want)
	}
}

// TestEmitAddForeignKey_SelfReferential pins the self-referential FK
// shape (employees.manager_id → employees.id). Sluice's three-phase
// apply (tables → bulk_copy → indexes → constraints) sidesteps the
// create-order problem because FKs land in phase 5 after all tables
// exist; this test pins the DDL emit so a regression couldn't drop
// the self-ref support silently. Per design-schema-completeness.md.
func TestEmitAddForeignKey_SelfReferential(t *testing.T) {
	fk := &ir.ForeignKey{
		Name:              "employees_manager_fk",
		Columns:           []string{"manager_id"},
		ReferencedTable:   "employees", // same table as the parent
		ReferencedColumns: []string{"id"},
		OnDelete:          ir.FKActionSetNull,
	}
	got, err := emitAddForeignKey("public", "employees", fk)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	want := `ALTER TABLE "public"."employees" ADD CONSTRAINT "employees_manager_fk" FOREIGN KEY ("manager_id") REFERENCES "public"."employees" ("id") ON DELETE SET NULL;`
	if got != want {
		t.Errorf("\n got  %q\n want %q", got, want)
	}
}

// TestEmitAddForeignKey_CompositePK pins the composite-PK FK shape
// (a child whose FK references a parent's two-column primary key).
// Real-world tenant-scoped data models often use (tenant_id, id)
// composite PKs; their FKs from child tables need both columns.
func TestEmitAddForeignKey_CompositePK(t *testing.T) {
	fk := &ir.ForeignKey{
		Name:              "orders_customer_fk",
		Columns:           []string{"tenant_id", "customer_id"},
		ReferencedTable:   "customers",
		ReferencedColumns: []string{"tenant_id", "id"},
		OnDelete:          ir.FKActionCascade,
		OnUpdate:          ir.FKActionCascade,
	}
	got, err := emitAddForeignKey("public", "orders", fk)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	want := `ALTER TABLE "public"."orders" ADD CONSTRAINT "orders_customer_fk" FOREIGN KEY ("tenant_id", "customer_id") REFERENCES "public"."customers" ("tenant_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;`
	if got != want {
		t.Errorf("\n got  %q\n want %q", got, want)
	}
}

// TestEmitAddForeignKey_AllOnDeleteActions pins the round-trip of
// every supported ir.FKAction value through the PG emitter. Each
// action has a different SQL keyword; a regression that swapped two
// of them would silently change cascade behavior on the target.
func TestEmitAddForeignKey_AllOnDeleteActions(t *testing.T) {
	cases := []struct {
		action ir.FKAction
		want   string
	}{
		{ir.FKActionNoAction, ""}, // omitted from output
		{ir.FKActionRestrict, "RESTRICT"},
		{ir.FKActionCascade, "CASCADE"},
		{ir.FKActionSetNull, "SET NULL"},
		{ir.FKActionSetDefault, "SET DEFAULT"},
	}
	for _, c := range cases {
		c := c
		t.Run(c.action.String(), func(t *testing.T) {
			fk := &ir.ForeignKey{
				Name:              "fk_test",
				Columns:           []string{"x"},
				ReferencedTable:   "parent",
				ReferencedColumns: []string{"id"},
				OnDelete:          c.action,
			}
			got, err := emitAddForeignKey("public", "child", fk)
			if err != nil {
				t.Fatalf("emitAddForeignKey: %v", err)
			}
			if c.want == "" {
				// NO ACTION shouldn't render an explicit clause —
				// the column-default behavior matches.
				if strings.Contains(got, "ON DELETE") {
					t.Errorf("FKActionNoAction should not render ON DELETE clause; got:\n%s", got)
				}
				return
			}
			if !strings.Contains(got, "ON DELETE "+c.want) {
				t.Errorf("expected ON DELETE %s in output; got:\n%s", c.want, got)
			}
		})
	}
}

func TestQuoteSQLString(t *testing.T) {
	cases := []struct{ in, want string }{
		{"hello", "'hello'"},
		{"it's", "'it''s'"},
		{"", "''"},
	}
	for _, c := range cases {
		if got := quoteSQLString(c.in); got != c.want {
			t.Errorf("quoteSQLString(%q) = %q; want %q", c.in, got, c.want)
		}
	}
}
