package postgres

import (
	"strings"
	"testing"

	"github.com/orware/sluice/internal/ir"
)

func TestEmitColumnType(t *testing.T) {
	cases := []struct {
		name string
		in   ir.Type
		want string
	}{
		// ---- Numeric / boolean ----
		{"boolean", ir.Boolean{}, "BOOLEAN"},
		{"smallint", ir.Integer{Width: 16}, "SMALLINT"},
		{"integer", ir.Integer{Width: 32}, "INTEGER"},
		{"bigint", ir.Integer{Width: 64}, "BIGINT"},
		{"int auto", ir.Integer{Width: 32, AutoIncrement: true}, "INTEGER GENERATED BY DEFAULT AS IDENTITY"},
		{"bigint auto", ir.Integer{Width: 64, AutoIncrement: true}, "BIGINT GENERATED BY DEFAULT AS IDENTITY"},
		{"unsigned int → bigint", ir.Integer{Width: 32, Unsigned: true}, "BIGINT"},
		{"unsigned tinyint → smallint", ir.Integer{Width: 8, Unsigned: true}, "SMALLINT"},
		{"unsigned bigint → numeric(20,0)", ir.Integer{Width: 64, Unsigned: true}, "NUMERIC(20,0)"},
		{"unsigned bigint auto → bigint identity", ir.Integer{Width: 64, Unsigned: true, AutoIncrement: true}, "BIGINT GENERATED BY DEFAULT AS IDENTITY"},
		{"decimal", ir.Decimal{Precision: 10, Scale: 2}, "NUMERIC(10,2)"},
		{"real", ir.Float{Precision: ir.FloatSingle}, "REAL"},
		{"double", ir.Float{Precision: ir.FloatDouble}, "DOUBLE PRECISION"},

		// ---- Character / binary ----
		{"char", ir.Char{Length: 10}, "CHAR(10)"},
		{"varchar", ir.Varchar{Length: 255}, "VARCHAR(255)"},
		{"text any size", ir.Text{Size: ir.TextRegular}, "TEXT"},
		{"text long", ir.Text{Size: ir.TextLong}, "TEXT"},
		{"binary → bytea", ir.Binary{Length: 16}, "BYTEA"},
		{"varbinary → bytea", ir.Varbinary{Length: 64}, "BYTEA"},
		{"blob → bytea", ir.Blob{Size: ir.BlobLong}, "BYTEA"},

		// ---- Temporal ----
		{"date", ir.Date{}, "DATE"},
		{"time precision 0", ir.Time{Precision: 0}, "TIME"},
		{"time precision 6", ir.Time{Precision: 6}, "TIME(6)"},
		{"datetime precision 0", ir.DateTime{Precision: 0}, "TIMESTAMP"},
		{"datetime precision 3", ir.DateTime{Precision: 3}, "TIMESTAMP(3)"},
		{"timestamp", ir.Timestamp{Precision: 0, WithTimeZone: false}, "TIMESTAMP"},
		{"timestamptz", ir.Timestamp{Precision: 6, WithTimeZone: true}, "TIMESTAMP(6) WITH TIME ZONE"},

		// ---- Structured ----
		{"json", ir.JSON{Binary: false}, "JSON"},
		{"jsonb", ir.JSON{Binary: true}, "JSONB"},

		// ---- Identity / network ----
		{"uuid", ir.UUID{}, "UUID"},
		{"inet", ir.Inet{}, "INET"},
		{"cidr", ir.Cidr{}, "CIDR"},
		{"macaddr", ir.Macaddr{}, "MACADDR"},

		// ---- Arrays ----
		{"int array", ir.Array{Element: ir.Integer{Width: 32}}, "INTEGER[]"},
		{"text array", ir.Array{Element: ir.Text{Size: ir.TextLong}}, "TEXT[]"},
		{"uuid array", ir.Array{Element: ir.UUID{}}, "UUID[]"},

		// ---- Set → TEXT[] (membership CHECK emitted by emitTableDef) ----
		{"set", ir.Set{Values: []string{"a", "b", "c"}}, "TEXT[]"},
		{"empty set", ir.Set{Values: nil}, "TEXT[]"},
	}

	for _, c := range cases {
		c := c
		t.Run(c.name, func(t *testing.T) {
			got, err := emitColumnType(c.in, emitOpts{})
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if got != c.want {
				t.Errorf("emitColumnType(%T) = %q; want %q", c.in, got, c.want)
			}
		})
	}
}

func TestEmitColumnTypeUnsupported(t *testing.T) {
	cases := []ir.Type{
		ir.Geometry{Subtype: ir.GeometryPoint},
		ir.Enum{Values: []string{"x"}}, // requires column context
	}
	for _, c := range cases {
		c := c
		t.Run("unsupported", func(t *testing.T) {
			if _, err := emitColumnType(c, emitOpts{}); err == nil {
				t.Errorf("expected error for %T", c)
			}
		})
	}
}

// TestEmitSetCheckConstraint covers the table-level CHECK fragment
// the SET → TEXT[] policy emits. The constraint is what enforces the
// "members must be in the source's value list" guarantee on the PG
// target after the type translation.
func TestEmitSetCheckConstraint(t *testing.T) {
	cases := []struct {
		name   string
		table  string
		column string
		values []string
		want   string
	}{
		{
			"basic three-member SET",
			"events", "flags",
			[]string{"a", "b", "c"},
			`CONSTRAINT "events_flags_set" CHECK ("flags" <@ ARRAY['a','b','c']::TEXT[])`,
		},
		{
			"empty value list",
			"events", "flags",
			nil,
			`CONSTRAINT "events_flags_set" CHECK ("flags" <@ '{}'::TEXT[])`,
		},
		{
			"member containing apostrophe",
			"t", "c",
			[]string{"a'b"},
			`CONSTRAINT "t_c_set" CHECK ("c" <@ ARRAY['a''b']::TEXT[])`,
		},
	}
	for _, c := range cases {
		c := c
		t.Run(c.name, func(t *testing.T) {
			got := emitSetCheckConstraint(c.table, c.column, c.values)
			if got != c.want {
				t.Errorf("\n got:  %s\nwant:  %s", got, c.want)
			}
		})
	}
}

// TestSetDefaultToArrayLiteral covers the comma-separated → PG
// array-literal translation used when a SET column's source DEFAULT
// crosses into a TEXT[] target.
func TestSetDefaultToArrayLiteral(t *testing.T) {
	cases := []struct {
		in   string
		want string
	}{
		{"", "'{}'::TEXT[]"},
		{"a", "ARRAY['a']::TEXT[]"},
		{"a,b", "ARRAY['a','b']::TEXT[]"},
		{"a,b,c", "ARRAY['a','b','c']::TEXT[]"},
		{"a'b", "ARRAY['a''b']::TEXT[]"},
	}
	for _, c := range cases {
		c := c
		t.Run(c.in, func(t *testing.T) {
			got := setDefaultToArrayLiteral(c.in)
			if got != c.want {
				t.Errorf("\n got:  %s\nwant:  %s", got, c.want)
			}
		})
	}
}

// TestEmitTableDef_SETColumn covers the integration between
// emitColumnType (TEXT[]), the SET CHECK constraint emission, and
// the SET-default translation in emitColumnDef.
func TestEmitTableDef_SETColumn(t *testing.T) {
	tbl := &ir.Table{
		Name: "events",
		Columns: []*ir.Column{
			{Name: "id", Type: ir.Integer{Width: 64}, Nullable: false},
			{
				Name:     "flags",
				Type:     ir.Set{Values: []string{"a", "b", "c"}},
				Nullable: false,
				Default:  ir.DefaultLiteral{Value: "a,b"},
			},
		},
		PrimaryKey: &ir.Index{
			Columns: []ir.IndexColumn{{Column: "id"}},
		},
	}
	got, err := emitTableDef("public", tbl, emitOpts{})
	if err != nil {
		t.Fatalf("emitTableDef: %v", err)
	}
	wantContains := []string{
		`"flags" TEXT[] NOT NULL DEFAULT ARRAY['a','b']::TEXT[]`,
		`CONSTRAINT "events_flags_set" CHECK ("flags" <@ ARRAY['a','b','c']::TEXT[])`,
		`PRIMARY KEY ("id")`,
	}
	for _, sub := range wantContains {
		if !strings.Contains(got, sub) {
			t.Errorf("CREATE TABLE missing %q\n--- got ---\n%s", sub, got)
		}
	}
}

func TestEmitDefault(t *testing.T) {
	cases := []struct {
		name     string
		in       ir.DefaultValue
		want     string
		wantEmit bool
	}{
		{"none", ir.DefaultNone{}, "", false},
		{"nil", nil, "", false},
		{"literal zero", ir.DefaultLiteral{Value: "0"}, "'0'", true},
		{"literal text", ir.DefaultLiteral{Value: "hello"}, "'hello'", true},
		{"literal with quote", ir.DefaultLiteral{Value: "it's"}, "'it''s'", true},
		{"expression", ir.DefaultExpression{Expr: "now()"}, "now()", true},
	}
	for _, c := range cases {
		c := c
		t.Run(c.name, func(t *testing.T) {
			got, ok := emitDefault(c.in)
			if ok != c.wantEmit {
				t.Errorf("emit flag = %v; want %v", ok, c.wantEmit)
			}
			if got != c.want {
				t.Errorf("emitDefault = %q; want %q", got, c.want)
			}
		})
	}
}

func TestEmitColumnDef(t *testing.T) {
	usersTable := &ir.Table{Name: "users"}

	cases := []struct {
		name string
		in   *ir.Column
		want string
	}{
		{
			name: "id bigint identity not null",
			in: &ir.Column{
				Name: "id",
				Type: ir.Integer{Width: 64, AutoIncrement: true},
			},
			want: `"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL`,
		},
		{
			name: "active boolean default true",
			in: &ir.Column{
				Name:    "active",
				Type:    ir.Boolean{},
				Default: ir.DefaultLiteral{Value: "true"},
			},
			want: `"active" BOOLEAN NOT NULL DEFAULT 'true'`,
		},
		{
			name: "created_at default now()",
			in: &ir.Column{
				Name:    "created_at",
				Type:    ir.Timestamp{Precision: 6, WithTimeZone: true},
				Default: ir.DefaultExpression{Expr: "now()"},
			},
			want: `"created_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT now()`,
		},
		{
			name: "nullable text",
			in: &ir.Column{
				Name:     "notes",
				Type:     ir.Text{Size: ir.TextLong},
				Nullable: true,
			},
			want: `"notes" TEXT`,
		},
		{
			name: "enum with type-name reference",
			in: &ir.Column{
				Name: "role",
				Type: ir.Enum{Values: []string{"admin", "user"}},
			},
			want: `"role" "users_role_enum" NOT NULL`,
		},
		{
			// Cross-engine MySQL → PG with `rating ENUM(...) DEFAULT 'G'`
			// must emit the explicit type cast on the default; without
			// the cast Postgres rejects the literal as "invalid input
			// value for enum ...".
			name: "enum with default literal needs explicit type cast",
			in: &ir.Column{
				Name:    "rating",
				Type:    ir.Enum{Values: []string{"G", "PG", "PG-13", "R", "NC-17"}},
				Default: ir.DefaultLiteral{Value: "G"},
			},
			want: `"rating" "users_rating_enum" NOT NULL DEFAULT 'G'::"users_rating_enum"`,
		},
	}

	for _, c := range cases {
		c := c
		t.Run(c.name, func(t *testing.T) {
			got, err := emitColumnDef(usersTable, c.in, emitOpts{})
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if got != c.want {
				t.Errorf("\n got  %q\n want %q", got, c.want)
			}
		})
	}
}

func TestEmitCreateEnumType(t *testing.T) {
	got := emitCreateEnumType("public", "users", "role", []string{"admin", "user", "guest"})
	want := `CREATE TYPE "public"."users_role_enum" AS ENUM ('admin', 'user', 'guest');`
	if got != want {
		t.Errorf("\n got  %q\n want %q", got, want)
	}
}

func TestEmitTableDef(t *testing.T) {
	table := &ir.Table{
		Name: "users",
		Columns: []*ir.Column{
			{Name: "id", Type: ir.Integer{Width: 64, AutoIncrement: true}},
			{Name: "email", Type: ir.Varchar{Length: 255}},
		},
		PrimaryKey: &ir.Index{
			Name:    "PRIMARY",
			Unique:  true,
			Columns: []ir.IndexColumn{{Column: "id"}},
		},
	}
	got, err := emitTableDef("public", table, emitOpts{})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	wants := []string{
		`CREATE TABLE "public"."users" (`,
		`"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,`,
		`"email" VARCHAR(255) NOT NULL,`,
		`PRIMARY KEY ("id")`,
	}
	for _, w := range wants {
		if !strings.Contains(got, w) {
			t.Errorf("output missing %q; got:\n%s", w, got)
		}
	}
}

func TestEmitCreateIndex(t *testing.T) {
	cases := []struct {
		name string
		idx  *ir.Index
		want string
	}{
		{
			name: "secondary unique btree",
			idx: &ir.Index{
				Name:    "users_email_unique",
				Unique:  true,
				Kind:    ir.IndexKindBTree,
				Columns: []ir.IndexColumn{{Column: "email"}},
			},
			want: `CREATE UNIQUE INDEX "users_email_unique" ON "public"."users" USING btree ("email");`,
		},
		{
			name: "non-unique multi-column",
			idx: &ir.Index{
				Name: "users_lookup",
				Kind: ir.IndexKindBTree,
				Columns: []ir.IndexColumn{
					{Column: "tenant_id"},
					{Column: "created_at", Desc: true},
				},
			},
			want: `CREATE INDEX "users_lookup" ON "public"."users" USING btree ("tenant_id", "created_at" DESC);`,
		},
		{
			// Index name doesn't start with the table name, so the
			// PG emitter prefixes it to disambiguate against the
			// schema-scoped Postgres namespace (a sibling table
			// might use the same source-side index name).
			name: "gin index — name gets table prefix",
			idx: &ir.Index{
				Name:    "posts_search",
				Kind:    ir.IndexKindGIN,
				Columns: []ir.IndexColumn{{Column: "tsv"}},
			},
			want: `CREATE INDEX "users_posts_search" ON "public"."users" USING gin ("tsv");`,
		},
		{
			// Source-side name like MySQL's idx_fk_film_id, which
			// appears on multiple tables in real-world schemas
			// (sakila has it on inventory, film_actor, etc.). The
			// table-prefix disambiguation is what makes the
			// cross-engine migration work.
			name: "common collision-prone name gets table prefix",
			idx: &ir.Index{
				Name:    "idx_fk_film_id",
				Kind:    ir.IndexKindBTree,
				Columns: []ir.IndexColumn{{Column: "film_id"}},
			},
			want: `CREATE INDEX "users_idx_fk_film_id" ON "public"."users" USING btree ("film_id");`,
		},
	}
	for _, c := range cases {
		c := c
		t.Run(c.name, func(t *testing.T) {
			got, err := emitCreateIndex("public", "users", c.idx)
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if got != c.want {
				t.Errorf("\n got  %q\n want %q", got, c.want)
			}
		})
	}
}

func TestEmitAddForeignKey(t *testing.T) {
	fk := &ir.ForeignKey{
		Name:              "posts_user_id_fk",
		Columns:           []string{"user_id"},
		ReferencedTable:   "users",
		ReferencedColumns: []string{"id"},
		OnDelete:          ir.FKActionCascade,
		OnUpdate:          ir.FKActionRestrict,
	}
	got, err := emitAddForeignKey("public", "posts", fk)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	want := `ALTER TABLE "public"."posts" ADD CONSTRAINT "posts_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON DELETE CASCADE ON UPDATE RESTRICT;`
	if got != want {
		t.Errorf("\n got  %q\n want %q", got, want)
	}
}

func TestQuoteSQLString(t *testing.T) {
	cases := []struct{ in, want string }{
		{"hello", "'hello'"},
		{"it's", "'it''s'"},
		{"", "''"},
	}
	for _, c := range cases {
		if got := quoteSQLString(c.in); got != c.want {
			t.Errorf("quoteSQLString(%q) = %q; want %q", c.in, got, c.want)
		}
	}
}
