package postgres

import (
	"errors"
	"fmt"
	"strings"

	"github.com/orware/sluice/internal/ir"
)

// emitOpts carries writer-derived flags that change how a few IR
// types render — currently just whether the target database has the
// postgis extension installed. Zero value (no PostGIS) preserves
// the writer's pre-extension behaviour for all callers.
type emitOpts struct {
	HasPostGIS bool
}

// emitColumnType returns the Postgres DDL fragment for a column type
// other than [ir.Enum]. Enum types are referenced by name in the
// column definition; the schema writer creates the CREATE TYPE
// statement separately and tracks the names — see [enumTypeName] and
// [emitColumnDef].
//
// Returns an error for IR types Postgres has no native form for, or
// for unsupported edge cases (Geometry without PostGIS, etc.).
func emitColumnType(t ir.Type, opts emitOpts) (string, error) {
	switch v := t.(type) {
	// ---- Boolean / numeric ----
	case ir.Boolean:
		return "BOOLEAN", nil
	case ir.Integer:
		return emitIntegerType(v), nil
	case ir.Decimal:
		return fmt.Sprintf("NUMERIC(%d,%d)", v.Precision, v.Scale), nil
	case ir.Float:
		if v.Precision == ir.FloatSingle {
			return "REAL", nil
		}
		return "DOUBLE PRECISION", nil

	// ---- Character / binary ----
	case ir.Char:
		return fmt.Sprintf("CHAR(%d)", v.Length), nil
	case ir.Varchar:
		return fmt.Sprintf("VARCHAR(%d)", v.Length), nil
	case ir.Text:
		// Postgres TEXT is unbounded; the IR's TextSize buckets
		// don't translate. All sizes collapse to TEXT.
		return "TEXT", nil
	case ir.Binary, ir.Varbinary, ir.Blob:
		// Postgres has only one binary type, BYTEA.
		return "BYTEA", nil

	// ---- Temporal ----
	case ir.Date:
		return "DATE", nil
	case ir.Time:
		return emitWithPrecision("TIME", v.Precision), nil
	case ir.DateTime:
		return emitWithPrecision("TIMESTAMP", v.Precision), nil
	case ir.Timestamp:
		base := emitWithPrecision("TIMESTAMP", v.Precision)
		if v.WithTimeZone {
			return base + " WITH TIME ZONE", nil
		}
		return base, nil

	// ---- Structured ----
	case ir.JSON:
		if v.Binary {
			return "JSONB", nil
		}
		return "JSON", nil

	// ---- Identity / network (extension types) ----
	case ir.UUID:
		return "UUID", nil
	case ir.Inet:
		return "INET", nil
	case ir.Cidr:
		return "CIDR", nil
	case ir.Macaddr:
		return "MACADDR", nil

	// ---- Composite (extension) ----
	case ir.Array:
		elem, err := emitColumnType(v.Element, opts)
		if err != nil {
			return "", fmt.Errorf("postgres: array element: %w", err)
		}
		// Multi-dim arrays not modelled; we always emit single-dim.
		return elem + "[]", nil

	// MySQL SET has no native PG equivalent. Default policy is to
	// land it as TEXT[]; the membership constraint enforcing the
	// source's value list is emitted separately by emitTableDef as
	// a table-level CHECK so the constraint name is operator-friendly
	// (anonymous column-level CHECKs lose their identity in error
	// messages).
	case ir.Set:
		return "TEXT[]", nil

	// ---- Cases that need column context (handled by emitColumnDef) ----
	case ir.Enum:
		return "", errors.New("postgres: Enum DDL emission requires column context (table+column); use emitColumnDef")

	// PostGIS-aware GEOMETRY emission. With the extension detected
	// at writer-open time, geometry(<subtype>, <srid>) carries the
	// IR's subtype and SRID into a typed PostGIS column. Without it,
	// the column is rejected — sluice doesn't try to install
	// extensions implicitly.
	case ir.Geometry:
		if !opts.HasPostGIS {
			return "", errors.New("postgres: GEOMETRY requires PostGIS; install with `CREATE EXTENSION postgis;` before running sluice")
		}
		return fmt.Sprintf("geometry(%s, %d)", postgisSubtypeName(v.Subtype), v.SRID), nil
	}
	return "", fmt.Errorf("postgres: unknown IR type %T", t)
}

// emitIntegerType returns the Postgres integer type for an [ir.Integer],
// expanding unsigned widths to the next signed rank (Postgres has no
// unsigned integers) and using GENERATED IDENTITY for auto-increment.
//
// BIGINT UNSIGNED that isn't auto-increment widens to NUMERIC(20,0).
// For BIGINT UNSIGNED that IS auto-increment we emit BIGINT IDENTITY
// and accept the small risk that values may exceed MaxInt64 — in
// practice an extreme corner case.
func emitIntegerType(i ir.Integer) string {
	if i.Unsigned && i.Width == 64 && !i.AutoIncrement {
		return "NUMERIC(20,0)"
	}
	width := effectiveWidth(i)
	typeName := postgresIntName(width)
	if i.AutoIncrement {
		return typeName + " GENERATED BY DEFAULT AS IDENTITY"
	}
	return typeName
}

// effectiveWidth returns the width Postgres should use for an integer
// column, widening one rank for unsigned values (so the original
// numeric range still fits).
func effectiveWidth(i ir.Integer) int8 {
	if !i.Unsigned {
		return i.Width
	}
	switch i.Width {
	case 8:
		return 16
	case 16, 24:
		return 32
	case 32, 64:
		return 64
	}
	return i.Width
}

// postgresIntName maps a signed integer width to the Postgres type
// name. 8/16 → SMALLINT (Postgres has no 8-bit type), 24/32 → INTEGER,
// 64 → BIGINT.
func postgresIntName(width int8) string {
	switch width {
	case 8, 16:
		return "SMALLINT"
	case 24, 32:
		return "INTEGER"
	case 64:
		return "BIGINT"
	}
	return "BIGINT"
}

// emitWithPrecision renders TYPE(N), or TYPE when precision is zero.
func emitWithPrecision(typeName string, precision int) string {
	if precision == 0 {
		return typeName
	}
	return fmt.Sprintf("%s(%d)", typeName, precision)
}

// quoteSQLString returns s wrapped in single quotes, with interior
// single quotes escaped by doubling.
func quoteSQLString(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

// emitDefault renders a DEFAULT clause body for the given default
// value. Returns ("", false) if no DEFAULT clause should be emitted.
func emitDefault(d ir.DefaultValue) (string, bool) {
	switch v := d.(type) {
	case nil, ir.DefaultNone:
		return "", false
	case ir.DefaultLiteral:
		return quoteSQLString(v.Value), true
	case ir.DefaultExpression:
		return v.Expr, true
	}
	return "", false
}

// setDefaultToArrayLiteral converts a MySQL-style comma-separated
// SET default ("a,b" or "" for the empty default) to a Postgres
// TEXT[] array literal expression. Used by emitColumnDef when the
// column's IR type is ir.Set, so the operator's source-side
// `DEFAULT 'a,b'` doesn't get dropped on the floor when the column
// translates to TEXT[].
//
// MySQL SET members are non-empty strings; the empty-set default
// is represented by an empty source-string, which maps to PG's
// '{}'::TEXT[] empty-array literal.
func setDefaultToArrayLiteral(commaSeparated string) string {
	if commaSeparated == "" {
		return "'{}'::TEXT[]"
	}
	parts := strings.Split(commaSeparated, ",")
	quoted := make([]string, len(parts))
	for i, p := range parts {
		quoted[i] = quoteSQLString(p)
	}
	return "ARRAY[" + strings.Join(quoted, ",") + "]::TEXT[]"
}

// emitSetCheckConstraint produces a CHECK-constraint fragment that
// enforces a SET column's value list at the table level:
//
//	CONSTRAINT "<table>_<column>_set" CHECK ("<column>" <@ ARRAY[...]::TEXT[])
//
// `<@` is PG's array-containment operator: the constraint passes
// when every element of the column value is a member of the
// declared SET. That matches MySQL SET semantics — any subset of
// the declared values is valid, including the empty array.
//
// Empty-values lists produce a CHECK against an empty array, which
// is degenerate (the column can only be the empty set) but
// well-formed; the source DDL was already strange in that case.
func emitSetCheckConstraint(tableName, columnName string, values []string) string {
	literal := "'{}'::TEXT[]"
	if len(values) > 0 {
		quoted := make([]string, len(values))
		for i, v := range values {
			quoted[i] = quoteSQLString(v)
		}
		literal = "ARRAY[" + strings.Join(quoted, ",") + "]::TEXT[]"
	}
	return fmt.Sprintf(
		"CONSTRAINT %s CHECK (%s <@ %s)",
		quoteIdent(setCheckName(tableName, columnName)),
		quoteIdent(columnName),
		literal,
	)
}

// setCheckName generates the CHECK-constraint name for a SET
// column. Same shape as enumTypeName so the two policies stay
// recognisable side-by-side.
func setCheckName(tableName, columnName string) string {
	return tableName + "_" + columnName + "_set"
}

// emitColumnDef returns the full DDL fragment for a single column,
// suitable for inclusion in a CREATE TABLE column list:
//
//	"name" TYPE [NOT NULL] [DEFAULT ...]
//
// For Enum columns, table is consulted for the per-column generated
// type name. Other IR types ignore the table argument.
func emitColumnDef(table *ir.Table, c *ir.Column, opts emitOpts) (string, error) {
	if c == nil {
		return "", errors.New("postgres: emitColumnDef: column is nil")
	}

	var typeStr string
	if _, isEnum := c.Type.(ir.Enum); isEnum {
		if table == nil {
			return "", fmt.Errorf("postgres: emitColumnDef: Enum column %q requires a table context", c.Name)
		}
		typeStr = quoteIdent(enumTypeName(table.Name, c.Name))
	} else {
		var err error
		typeStr, err = emitColumnType(c.Type, opts)
		if err != nil {
			return "", fmt.Errorf("postgres: column %q: %w", c.Name, err)
		}
	}

	var sb strings.Builder
	sb.WriteString(quoteIdent(c.Name))
	sb.WriteByte(' ')
	sb.WriteString(typeStr)
	if !c.Nullable {
		sb.WriteString(" NOT NULL")
	}
	if dflt, ok := emitDefault(c.Default); ok {
		sb.WriteString(" DEFAULT ")
		// SET columns translate the comma-separated MySQL literal
		// to a TEXT[] array literal so the source DEFAULT survives
		// the type rewrite. Other default shapes (DefaultExpression,
		// DefaultNone) flow through emitDefault unchanged.
		if _, isSet := c.Type.(ir.Set); isSet {
			if lit, ok := c.Default.(ir.DefaultLiteral); ok {
				sb.WriteString(setDefaultToArrayLiteral(lit.Value))
			} else {
				sb.WriteString(dflt)
			}
		} else {
			sb.WriteString(dflt)
		}
		// Postgres enum columns need an explicit type cast on the
		// default literal — without it, CREATE TABLE rejects the
		// default with "invalid input value for enum ...". The
		// enum type name is the same one used in typeStr above.
		if _, isEnum := c.Type.(ir.Enum); isEnum {
			if _, isLiteral := c.Default.(ir.DefaultLiteral); isLiteral {
				sb.WriteString("::")
				sb.WriteString(quoteIdent(enumTypeName(table.Name, c.Name)))
			}
		}
	}
	return sb.String(), nil
}

// enumTypeName generates a deterministic Postgres enum type name for
// the given table+column pair. Two columns with the same enum values
// in different tables get separate types — slight inefficiency, but
// no risk of name collisions or unintended sharing.
func enumTypeName(tableName, columnName string) string {
	return tableName + "_" + columnName + "_enum"
}

// pgIndexName disambiguates a source-side index name against the
// schema-scoped Postgres namespace. If the source name already
// begins with the table name (the common case for sluice-emitted
// names), it's returned verbatim; otherwise it gets a `<table>_`
// prefix. The two-form rule preserves human-readable names like
// `idx_users_email` while disambiguating MySQL-style sibling index
// names like `idx_fk_film_id` (which appears on multiple tables in
// real-world schemas).
func pgIndexName(tableName, sourceName string) string {
	if sourceName == "" {
		return ""
	}
	prefix := tableName + "_"
	if strings.HasPrefix(sourceName, prefix) {
		return sourceName
	}
	return prefix + sourceName
}

// emitCreateEnumType produces a CREATE TYPE statement for a single
// enum, named by the table+column generator. Values are quoted and
// comma-separated.
func emitCreateEnumType(schema, tableName, columnName string, values []string) string {
	parts := make([]string, len(values))
	for i, v := range values {
		parts[i] = quoteSQLString(v)
	}
	return fmt.Sprintf(
		"CREATE TYPE %s.%s AS ENUM (%s);",
		quoteIdent(schema),
		quoteIdent(enumTypeName(tableName, columnName)),
		strings.Join(parts, ", "),
	)
}

// emitTableDef produces a CREATE TABLE statement with columns,
// table-level CHECK constraints (for SET columns), and the primary
// key inline. The table is schema-qualified.
//
// Body parts assembled into a single comma-separated block so the
// trailing-comma logic stays in one place — MySQL SET columns add
// CHECK lines that complicate the per-line rule.
func emitTableDef(schema string, table *ir.Table, opts emitOpts) (string, error) {
	if table == nil {
		return "", errors.New("postgres: emitTableDef: table is nil")
	}
	if len(table.Columns) == 0 {
		return "", fmt.Errorf("postgres: emitTableDef: table %q has no columns", table.Name)
	}

	parts := make([]string, 0, len(table.Columns)+2)

	for _, col := range table.Columns {
		def, err := emitColumnDef(table, col, opts)
		if err != nil {
			return "", err
		}
		parts = append(parts, def)
	}

	// SET columns get a table-level CHECK constraint enforcing the
	// declared value list. Emitted in declaration order so the DDL
	// is stable across runs.
	for _, col := range table.Columns {
		set, ok := col.Type.(ir.Set)
		if !ok {
			continue
		}
		parts = append(parts, emitSetCheckConstraint(table.Name, col.Name, set.Values))
	}

	if table.PrimaryKey != nil {
		parts = append(parts, "PRIMARY KEY "+emitIndexColumnList(table.PrimaryKey.Columns))
	}

	var sb strings.Builder
	sb.WriteString("CREATE TABLE ")
	sb.WriteString(quoteIdent(schema))
	sb.WriteByte('.')
	sb.WriteString(quoteIdent(table.Name))
	sb.WriteString(" (\n")
	for i, p := range parts {
		sb.WriteString("  ")
		sb.WriteString(p)
		if i < len(parts)-1 {
			sb.WriteByte(',')
		}
		sb.WriteByte('\n')
	}
	sb.WriteString(");")
	return sb.String(), nil
}

// emitIndexColumnList renders a parenthesised, comma-separated list
// of index columns. Postgres doesn't support prefix-length on indexes
// the way MySQL does, so c.Length is ignored (lossy if the source
// used it; documented).
func emitIndexColumnList(cols []ir.IndexColumn) string {
	parts := make([]string, len(cols))
	for i, c := range cols {
		entry := quoteIdent(c.Column)
		if c.Desc {
			entry += " DESC"
		}
		parts[i] = entry
	}
	return "(" + strings.Join(parts, ", ") + ")"
}

// emitCreateIndex produces a CREATE INDEX statement (UNIQUE if
// applicable). Postgres uses CREATE INDEX rather than ALTER TABLE
// ADD INDEX (which doesn't exist here).
func emitCreateIndex(schema, tableName string, idx *ir.Index) (string, error) {
	if idx == nil {
		return "", errors.New("postgres: emitCreateIndex: index is nil")
	}
	if strings.EqualFold(idx.Name, "PRIMARY") {
		return "", errors.New("postgres: emitCreateIndex: PRIMARY index is inline in CREATE TABLE")
	}
	if len(idx.Columns) == 0 {
		return "", fmt.Errorf("postgres: emitCreateIndex: index %q has no columns", idx.Name)
	}

	var sb strings.Builder
	sb.WriteString("CREATE ")
	if idx.Unique {
		sb.WriteString("UNIQUE ")
	}
	sb.WriteString("INDEX ")
	if idx.Name != "" {
		// Postgres index names are schema-scoped (a single namespace
		// per schema). MySQL index names are table-scoped (the same
		// name on two tables is fine). Cross-engine, that means a
		// MySQL source with `idx_fk_film_id` on both `inventory` and
		// `film_actor` would collide on the PG target. Prefixing
		// with the table name disambiguates without losing the
		// human-readable original.
		sb.WriteString(quoteIdent(pgIndexName(tableName, idx.Name)))
		sb.WriteByte(' ')
	}
	sb.WriteString("ON ")
	sb.WriteString(quoteIdent(schema))
	sb.WriteByte('.')
	sb.WriteString(quoteIdent(tableName))
	sb.WriteByte(' ')
	if method := postgresIndexMethod(idx.Kind); method != "" {
		sb.WriteString("USING ")
		sb.WriteString(method)
		sb.WriteByte(' ')
	}
	sb.WriteString(emitIndexColumnList(idx.Columns))
	sb.WriteByte(';')
	return sb.String(), nil
}

// postgresIndexMethod maps an [ir.IndexKind] to a Postgres access
// method name. Returns "" when the IR's IndexKind has no clean
// Postgres equivalent — Postgres defaults to btree, which is what we
// want for IndexKindUnspecified.
func postgresIndexMethod(k ir.IndexKind) string {
	switch k {
	case ir.IndexKindBTree:
		return "btree"
	case ir.IndexKindHash:
		return "hash"
	case ir.IndexKindGIN:
		return "gin"
	case ir.IndexKindGIST:
		return "gist"
	}
	// FullText/Spatial don't have direct Postgres builtin equivalents
	// (FTS uses tsvector + GIN; Spatial needs PostGIS). Fall through
	// to default (btree).
	return ""
}

// emitAddForeignKey produces an ALTER TABLE ... ADD CONSTRAINT
// statement for a foreign key on the given child table.
func emitAddForeignKey(schema, childTable string, fk *ir.ForeignKey) (string, error) {
	if fk == nil {
		return "", errors.New("postgres: emitAddForeignKey: fk is nil")
	}
	if len(fk.Columns) == 0 || len(fk.ReferencedColumns) == 0 {
		return "", fmt.Errorf("postgres: emitAddForeignKey: fk %q has no columns", fk.Name)
	}
	if len(fk.Columns) != len(fk.ReferencedColumns) {
		return "", fmt.Errorf("postgres: emitAddForeignKey: fk %q column count mismatch (%d vs %d)",
			fk.Name, len(fk.Columns), len(fk.ReferencedColumns))
	}

	refSchema := fk.ReferencedSchema
	if refSchema == "" {
		refSchema = schema
	}

	var sb strings.Builder
	sb.WriteString("ALTER TABLE ")
	sb.WriteString(quoteIdent(schema))
	sb.WriteByte('.')
	sb.WriteString(quoteIdent(childTable))
	sb.WriteString(" ADD")
	if fk.Name != "" {
		sb.WriteString(" CONSTRAINT ")
		sb.WriteString(quoteIdent(fk.Name))
	}
	sb.WriteString(" FOREIGN KEY ")
	sb.WriteString(emitColumnList(fk.Columns))
	sb.WriteString(" REFERENCES ")
	sb.WriteString(quoteIdent(refSchema))
	sb.WriteByte('.')
	sb.WriteString(quoteIdent(fk.ReferencedTable))
	sb.WriteByte(' ')
	sb.WriteString(emitColumnList(fk.ReferencedColumns))

	if fk.OnDelete != ir.FKActionNoAction {
		sb.WriteString(" ON DELETE ")
		sb.WriteString(fk.OnDelete.String())
	}
	if fk.OnUpdate != ir.FKActionNoAction {
		sb.WriteString(" ON UPDATE ")
		sb.WriteString(fk.OnUpdate.String())
	}
	sb.WriteByte(';')
	return sb.String(), nil
}

// emitColumnList renders a parenthesised, comma-separated list of
// quoted column names.
func emitColumnList(cols []string) string {
	parts := make([]string, len(cols))
	for i, c := range cols {
		parts[i] = quoteIdent(c)
	}
	return "(" + strings.Join(parts, ", ") + ")"
}
