//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// Direction-aware identity priming on a real server (value-fidelity
// review BLOCKING 1 on GC-3): SyncIdentitySequences primes a descending
// identity from MIN, and the `cutover` primer (ADR-0062) advances a
// descending identity DOWNWARD with the margin, clamps into the
// sequence's bounds, and is idempotent — the same shape its standalone-
// sequence sibling has had since item 51.
//
// Independent expected values: the target's own INSERT … DEFAULT result,
// and the target's pg_sequences.last_value read with plain SQL.

package postgres

import (
	"context"
	"database/sql"
	"errors"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/ir"
)

func pgInsertDefaultID(t *testing.T, dsn, table string) (int64, error) {
	t.Helper()
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer func() { _ = db.Close() }()
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	var id int64
	err = db.QueryRowContext(ctx, `INSERT INTO `+table+` (note) VALUES ('x') RETURNING id`).Scan(&id)
	return id, err
}

// TestSyncIdentitySequences_DescendingPrimesFromMin: source tables with a
// negative-range and a positive-range descending identity plus an
// ascending control, re-created on the target through the real writer,
// rows copied with their source ids (BY DEFAULT accepts them), then
// SyncIdentitySequences. The next generated id must be beyond MIN in
// the sequence's direction, never a copied id.
func TestSyncIdentitySequences_DescendingPrimesFromMin(t *testing.T) {
	srcDSN, srcCleanup := newSharedPGDB(t, "sluice_iddir_src")
	defer srcCleanup()
	tgtDSN, tgtCleanup := newSharedPGDB(t, "sluice_iddir_tgt")
	defer tgtCleanup()

	applyDDL(t, srcDSN, `
		CREATE TABLE desc_neg (id BIGINT GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY -1) PRIMARY KEY, note TEXT NOT NULL);
		CREATE TABLE desc_pos (id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY -1 MINVALUE 1 MAXVALUE 100) PRIMARY KEY, note TEXT NOT NULL);
		CREATE TABLE asc_ctl  (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, note TEXT NOT NULL);
		INSERT INTO desc_neg (note) VALUES ('a'), ('b'), ('c');
		INSERT INTO desc_pos (note) VALUES ('a'), ('b'), ('c');
		INSERT INTO asc_ctl  (note) VALUES ('a'), ('b'), ('c');
	`)
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()
	schema := readSchemaFrom(ctx, t, srcDSN)
	sw := writeSchemaTo(ctx, t, tgtDSN, schema)
	// The copy, in miniature: the source's ids land explicitly.
	applyDDL(t, tgtDSN, `
		INSERT INTO desc_neg (id, note) VALUES (-1,'a'), (-2,'b'), (-3,'c');
		INSERT INTO desc_pos (id, note) VALUES (100,'a'), (99,'b'), (98,'c');
		INSERT INTO asc_ctl  (id, note) VALUES (1,'a'), (2,'b'), (3,'c');
	`)
	if err := sw.SyncIdentitySequences(ctx, schema); err != nil {
		t.Fatalf("SyncIdentitySequences: %v", err)
	}
	for table, want := range map[string]int64{"desc_neg": -4, "desc_pos": 97, "asc_ctl": 4} {
		got, err := pgInsertDefaultID(t, tgtDSN, table)
		if err != nil {
			t.Errorf("%s: INSERT … DEFAULT after the sync failed: %v (sequence parked on a copied id)", table, err)
			continue
		}
		if got != want {
			t.Errorf("%s: first generated id = %d; want %d", table, got, want)
		}
	}
}

// TestCutoverSequencePrimer_PG_DescendingIdentity: the ADR-0062 primer on
// a descending identity — primed to source+margin DOWNWARD, the next
// nextval one step below that, a re-run is a noop, and a target that
// moved past the tolerance in the descending direction is refused.
func TestCutoverSequencePrimer_PG_DescendingIdentity(t *testing.T) {
	srcDSN, srcCleanup := newSharedPGDB(t, "sluice_cutdesc_src")
	defer srcCleanup()
	tgtDSN, tgtCleanup := newSharedPGDB(t, "sluice_cutdesc_tgt")
	defer tgtCleanup()

	const ddl = `CREATE TABLE orders (id BIGINT GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY -1) PRIMARY KEY, note TEXT NOT NULL);`
	applyDDL(t, srcDSN, ddl+` INSERT INTO orders (note) VALUES ('a'), ('b'), ('c');`)
	applyDDL(t, tgtDSN, ddl)

	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()
	sr, err := Engine{}.OpenSchemaReader(ctx, srcDSN)
	if err != nil {
		t.Fatalf("open source reader: %v", err)
	}
	defer closeReader(t, sr)
	pgsr := sr.(*SchemaReader)
	schema, err := pgsr.ReadSchema(ctx)
	if err != nil {
		t.Fatalf("read schema: %v", err)
	}
	states, err := pgsr.ReadSequenceState(ctx, schema)
	if err != nil {
		t.Fatalf("read sequence state: %v", err)
	}
	if len(states) != 1 || states[0].Value != -3 {
		t.Fatalf("source states = %+v; want one entry at -3 (last issued)", states)
	}
	sw, err := Engine{}.OpenSchemaWriter(ctx, tgtDSN)
	if err != nil {
		t.Fatalf("open target writer: %v", err)
	}
	pgsw := sw.(*SchemaWriter)

	const margin = int64(10)
	report, err := pgsw.PrimeSequences(ctx, schema, states, margin)
	if err != nil {
		t.Fatalf("first prime: %v (report %+v)", err, report)
	}
	if len(report.Actions) != 1 || report.Actions[0].Outcome != "primed" || report.Actions[0].TargetAfter != -13 {
		t.Fatalf("first prime actions = %+v; want one 'primed' at -13 (source -3 + margin 10 downward)", report.Actions)
	}
	// The target's own next value is one step below the primed position.
	got, err := pgInsertDefaultID(t, tgtDSN, "orders")
	if err != nil {
		t.Fatalf("INSERT … DEFAULT after prime: %v", err)
	}
	if got != -14 {
		t.Errorf("first generated id after prime = %d; want -14", got)
	}
	// Idempotent re-run: the target (-14) is beyond the apply point
	// (-13) but within the tolerance → noop, no regression upward.
	report, err = pgsw.PrimeSequences(ctx, schema, states, margin)
	if err != nil {
		t.Fatalf("second prime: %v (report %+v)", err, report)
	}
	if report.Actions[0].Outcome != "noop" {
		t.Errorf("second prime outcome = %q; want noop (action %+v)", report.Actions[0].Outcome, report.Actions[0])
	}
	// Refusal: post-cutover writes moved the target far past
	// source+margin in the descending direction.
	applyDDL(t, tgtDSN, `SELECT setval(pg_get_serial_sequence('orders','id'), -100, true)`)
	report, err = pgsw.PrimeSequences(ctx, schema, states, margin)
	if !errors.Is(err, ir.ErrCutoverSequenceTargetAhead) || report.Actions[0].Outcome != "refused" {
		t.Errorf("third prime: err=%v outcome=%q; want ErrCutoverSequenceTargetAhead / refused", err, report.Actions[0].Outcome)
	}
}
