//go:build nekiverify

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

package postgres

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/ir"
)

// # Bisecting NK306: is it sluice's column list, or the batch lane?
//
// The CDC arm fails with:
//
//	insert into public.cdc_content: error preprocessing batch (prepare):
//	ERROR: shard-key column "tenant_id" of primary index 0 ("xxhash_tenant_id")
//	is required but missing from INSERT (SQLSTATE NK306)
//
// The change events demonstrably carry `tenant_id`, so one of two things is
// true, and they have DIFFERENT fixes:
//
//	(a) sluice drops the column while building the statement. That is a
//	    sluice defect, and it would be a silent-ish one — the applier would
//	    be emitting an INSERT that names fewer columns than the row has.
//
//	(b) the column IS named and the PIPELINED BATCH lane presents it in a
//	    form the router cannot route on. Then the fix is about which lane
//	    sluice uses against a sharded Neki target, and nothing about column
//	    lists would change.
//
// Neither is safe to assume, and the difference is not visible from the
// failure message — which is exactly why the CDC arm's finding was filed
// rather than fixed. These two arms decide it, and they decide it every week
// rather than once.
//
// Between them the answer is mechanical:
//
//	generated-flag arm FAILS          -> (a). sluice's bug, in NonGeneratedRowKeys.
//	serial PASSES, batch FAILS        -> (b). The pipelined lane is the differentiator.
//	both apply paths FAIL             -> neither; the problem is upstream of both
//	                                     and the CDC arm's framing needs revisiting.

// nekiShardKeyIsNotReportedGenerated tests candidate (a) at its mechanism.
//
// `buildInsertSQL` takes its column list from
// [appliershared.NonGeneratedRowKeys], which drops a column when the target's
// own metadata says it is GENERATED. That is correct behaviour — a generated
// column cannot be written — and it is a correct behaviour that would produce
// exactly this failure if the platform reported the shard key that way.
//
// It is not far-fetched. Neki's own refusal names `primary index 0
// ("xxhash_tenant_id")`, so the routing column is backed by a hash index the
// platform maintains. A catalog that surfaced that as a generated attribute
// would make sluice silently omit the one column the INSERT must carry, and
// every symptom above would follow without sluice containing a single wrong
// line of routing logic.
//
// One catalog read settles it.
func nekiShardKeyIsNotReportedGenerated(ctx context.Context, t *testing.T, db *sql.DB, table, shardKey string) {
	t.Helper()

	t.Run("PREMISE: the shard key is not reported GENERATED by the target catalog", func(t *testing.T) {
		// attgenerated is '' for an ordinary column and 's' for a STORED
		// generated one. Read the raw attribute rather than any sluice
		// helper: the point is what the PLATFORM says, and routing the
		// question through sluice's own reader would let a bug in that reader
		// hide the answer it is being asked for.
		var attgenerated string
		err := db.QueryRowContext(ctx, `
			SELECT a.attgenerated
			  FROM pg_catalog.pg_attribute a
			  JOIN pg_catalog.pg_class     c ON c.oid = a.attrelid
			  JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
			 WHERE n.nspname = 'public' AND c.relname = $1
			   AND a.attname = $2 AND a.attnum > 0 AND NOT a.attisdropped`,
			table, shardKey).Scan(&attgenerated)
		if errors.Is(err, sql.ErrNoRows) {
			t.Fatalf("the catalog has no column %q on public.%s at all — this arm cannot answer its "+
				"question, and the CDC failure it is bisecting is about that very column", shardKey, table)
		}
		if err != nil {
			t.Fatalf("read attgenerated for public.%s.%s: %v", table, shardKey, err)
		}

		if attgenerated != "" {
			t.Fatalf("THE SHARD KEY IS REPORTED GENERATED (attgenerated=%q), AND THAT IS THE NK306 BUG.\n\n"+
				"buildInsertSQL takes its columns from appliershared.NonGeneratedRowKeys, which drops "+
				"any column the target's metadata marks generated — correct in general, and here it "+
				"means sluice omits the one column a sharded INSERT must carry. The applier is at "+
				"fault, not the batch lane.\n\n"+
				"Fix in NonGeneratedRowKeys' callers: a column that is part of the routing key must be "+
				"written even when the catalog calls it generated.", attgenerated)
		}
		t.Logf("premise holds: public.%s.%s is an ordinary column (attgenerated=''), so sluice's "+
			"column list is not dropping it", table, shardKey)
	})
}

// nekiCDCSerialVsBatchedIntoSharded tests candidate (b) by DIFFERENCE.
//
// It applies the same three-change stream twice into two identical tables on
// the same cluster, in the same run, differing only in which applier interface
// carries it: the SERIAL [ir.ChangeApplier.Apply] and the pipelined
// [ir.BatchedChangeApplier.ApplyBatch].
//
// The comparison is the whole point. A batch failure alone says "NK306
// happened"; a batch failure NEXT TO a serial success on the same cluster,
// same table shape, same rows, same connection settings says the LANE is the
// variable — which is a different bug report and a different fix.
//
// Deliberately NOT asserted here: that either lane succeeds. Both outcomes are
// informative and the arm reports what it saw rather than insisting on one.
// It fails only when the pair is UNINFORMATIVE — both lanes agreeing, which
// would mean the lane is not the variable and the CDC arm's framing needs
// revisiting.
func nekiCDCSerialVsBatchedIntoSharded(ctx context.Context, t *testing.T, db *sql.DB, fx *nekiFixture, tenantA, tenantB int) {
	t.Helper()

	t.Run("BISECT: the same changes through the SERIAL and the BATCHED applier", func(t *testing.T) {
		const (
			serialTable = "nk306_serial"
			batchTable  = "nk306_batch"
		)

		for _, tbl := range []string{serialTable, batchTable} {
			if _, err := db.ExecContext(ctx, `DROP TABLE IF EXISTS `+tbl); err != nil {
				t.Fatalf("drop %s: %v", tbl, err)
			}
			if _, err := db.ExecContext(ctx, fmt.Sprintf(`
				CREATE TABLE %s (
					tenant_id BIGINT NOT NULL,
					id        BIGINT NOT NULL,
					payload   TEXT   NOT NULL,
					PRIMARY KEY (tenant_id, id)
				)`, tbl)); err != nil {
				t.Fatalf("create %s: %v", tbl, err)
			}
		}
		t.Cleanup(func() {
			cctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
			defer cancel()
			for _, tbl := range []string{serialTable, batchTable} {
				_, _ = db.ExecContext(cctx, `DROP TABLE IF EXISTS `+tbl)
			}
		})

		// The same three inserts for both lanes, spanning both shards so the
		// routing machinery is genuinely engaged rather than incidentally
		// satisfied by everything landing in one place.
		changesFor := func(tbl string) []ir.Change {
			return []ir.Change{
				ir.Insert{Schema: "public", Table: tbl, Row: ir.Row{"tenant_id": int64(tenantA), "id": int64(1), "payload": "a"}},
				ir.Insert{Schema: "public", Table: tbl, Row: ir.Row{"tenant_id": int64(tenantB), "id": int64(2), "payload": "b"}},
				ir.Insert{Schema: "public", Table: tbl, Row: ir.Row{"tenant_id": int64(tenantA), "id": int64(3), "payload": "c"}},
			}
		}

		opened, err := Engine{}.OpenChangeApplier(ctx, fx.dsn)
		if err != nil {
			t.Fatalf("open applier: %v", err)
		}
		defer func() {
			if c, ok := opened.(interface{ Close() error }); ok {
				_ = c.Close()
			}
		}()
		if err := opened.EnsureControlTable(ctx); err != nil {
			t.Fatalf("ensure control table: %v", err)
		}

		feed := func(chs []ir.Change) <-chan ir.Change {
			ch := make(chan ir.Change, len(chs))
			for _, c := range chs {
				ch <- c
			}
			close(ch)
			return ch
		}

		// LANE 1 — serial.
		serialErr := opened.Apply(ctx, "nk306-bisect-serial", feed(changesFor(serialTable)))

		// LANE 2 — pipelined batch, the lane the CDC arm fails on.
		batched, ok := opened.(ir.BatchedChangeApplier)
		if !ok {
			t.Fatal("the postgres applier no longer implements ir.BatchedChangeApplier, so there is no " +
				"second lane to compare against and this arm cannot bisect anything")
		}
		batchErr := batched.ApplyBatch(ctx, "nk306-bisect-batch", feed(changesFor(batchTable)), 10)

		serialRows := countRowsIn(ctx, t, db, serialTable)
		batchRows := countRowsIn(ctx, t, db, batchTable)

		t.Logf("SERIAL  : err=%v rows=%d", serialErr, serialRows)
		t.Logf("BATCHED : err=%v rows=%d", batchErr, batchRows)

		serialNK306 := isPGCode(serialErr, "NK306")
		batchNK306 := isPGCode(batchErr, "NK306")

		switch {
		case serialErr == nil && batchNK306:
			// THE ANSWER, if this is what comes back.
			t.Fatalf("BISECTED: the SERIAL lane applied all %d rows and the BATCHED lane was refused "+
				"with NK306.\n\nbatch error: %v\n\n"+
				"The lane is the variable — same cluster, same table shape, same rows, same run. So "+
				"sluice's column list is not the problem and the pipelined path is: it presents the "+
				"shard key in a form the router cannot route on at prepare time. The fix belongs in "+
				"lane selection for a sharded Neki target, NOT in buildInsertSQL.", serialRows, batchErr)

		case serialNK306 && batchNK306:
			t.Fatalf("BOTH lanes were refused with NK306, so the lane is NOT the variable.\n\n"+
				"serial: %v\nbatch:  %v\n\n"+
				"That rules out the pipelined-path hypothesis and points back at what both lanes share "+
				"— the statement builder or the column list. Check the generated-flag arm's verdict "+
				"alongside this one.", serialErr, batchErr)

		case serialErr == nil && batchErr == nil:
			// Both lanes work. Informative and worth saying loudly: it means
			// the CDC arm's failure is about something its own fixture does
			// that this one does not (ON CONFLICT, an UPDATE, a DELETE), not
			// about plain inserts on a sharded table at all.
			t.Fatalf("BOTH lanes applied cleanly (serial %d rows, batch %d rows), so neither the lane "+
				"nor the column list explains the CDC arm's NK306.\n\n"+
				"This arm sends plain INSERTs; the CDC arm sends INSERT + UPDATE + DELETE and its "+
				"inserts go through ON CONFLICT. The variable is therefore something in THAT shape — "+
				"most likely the ON CONFLICT DO UPDATE form, which is the one statement whose shard-key "+
				"handling sluice deliberately special-cases. Narrow the CDC arm before filing further.",
				serialRows, batchRows)

		default:
			t.Fatalf("the two lanes disagreed in a way this arm does not have a reading for.\n\n"+
				"serial: err=%v rows=%d\nbatch:  err=%v rows=%d\n\n"+
				"Record both before drawing a conclusion — an unexplained pair is the finding, not a "+
				"detail to note and move past.", serialErr, serialRows, batchErr, batchRows)
		}
	})
}

// countRowsIn is a plain COUNT(*), reported rather than asserted — the bisect
// arm's conclusions turn on which lane ERRORED, and the counts are corroborating
// detail that makes a surprising pair legible.
func countRowsIn(ctx context.Context, t *testing.T, db *sql.DB, table string) int {
	t.Helper()
	var n int
	if err := db.QueryRowContext(ctx, `SELECT count(*) FROM `+table).Scan(&n); err != nil {
		t.Logf("count %s: %v", table, err)
		return -1
	}
	return n
}
