//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

package postgres

import (
	"context"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/ir"
	"sluicesync.dev/sluice/internal/sluicecode"
)

// replayOutcome is what re-applying one INSERT through the real applier
// does to a table: the ground truth the probe's verdict is graded against.
type replayOutcome string

const (
	replayConverges  replayOutcome = "converges"  // still one row: the upsert collided
	replayDuplicates replayOutcome = "duplicates" // two rows, at no error: the F-E1 silent class
	replayLoud       replayOutcome = "loud"       // the second apply errors
)

// TestRowWriter_ProbeReplayKey_ShapeMatrix pins the Postgres half of the
// F-E1 target judgment against a real server, over every key shape the
// applier's arbiter selection distinguishes — not one representative.
//
// The independent expected value per shape is the APPLIER'S OWN behaviour,
// measured: one INSERT is applied twice through the real change applier and
// the outcome recorded. keyed=true must coincide with "converges"; every
// silent "duplicates" shape must be keyed=false. A keyed=false shape whose
// re-apply is merely LOUD (a non-arbiter unique index that still collides)
// is refused by the door too, which is the conservative direction: the
// applier would have failed on it anyway. Rows are chosen to reach the
// silent outcome wherever one exists (a NULL in a nullable key part, a value
// outside a partial index's predicate).
//
// The probe is handed the RECORDED table — the row's own columns plus "v" —
// because whether a key is SUPPLIED by the replayed rows is half of the
// judgment (audit F-E1 review, HIGH 1): a target re-keyed on a surrogate the
// rows never carry has a key and an ON CONFLICT clause, and still
// duplicates. The surrogate rows and the two-keys rows below are that class.
func TestRowWriter_ProbeReplayKey_ShapeMatrix(t *testing.T) {
	dsn, cleanup := startPostgresForApplier(t)
	defer cleanup()
	ctx, cancel := context.WithTimeout(context.Background(), 120*time.Second)
	defer cancel()

	cases := []struct {
		table, ddl   string
		row          ir.Row
		wantExists   bool
		wantKeyed    bool
		wantRefusal  bool // the applier's own deferrable-key refusal
		outcome      replayOutcome
		conservative bool // keyed=false although the re-apply converges
	}{
		{table: "absent", row: ir.Row{"id": int64(1)}},
		{"no_key", "CREATE TABLE no_key (id int NOT NULL, v text)", ir.Row{"id": int64(1)}, true, false, false, replayDuplicates, false},
		{"pk", "CREATE TABLE pk (id int PRIMARY KEY, v text)", ir.Row{"id": int64(1)}, true, true, false, replayConverges, false},
		{"nn_unique", "CREATE TABLE nn_unique (id int NOT NULL UNIQUE, v text)", ir.Row{"id": int64(1)}, true, true, false, replayConverges, false},
		{"nn_unique_composite", "CREATE TABLE nn_unique_composite (a int NOT NULL, b int NOT NULL, v text, UNIQUE (a, b))", ir.Row{"a": int64(1), "b": int64(1)}, true, true, false, replayConverges, false},
		{"nullable_unique", "CREATE TABLE nullable_unique (id int UNIQUE, v text)", ir.Row{"id": nil}, true, false, false, replayDuplicates, false},
		{"composite_one_nullable", "CREATE TABLE composite_one_nullable (a int NOT NULL, b int, v text, UNIQUE (a, b))", ir.Row{"a": int64(1), "b": nil}, true, false, false, replayDuplicates, false},
		{"partial_unique", "CREATE TABLE partial_unique (id int NOT NULL, v text); CREATE UNIQUE INDEX partial_unique_ix ON partial_unique (id) WHERE id > 0", ir.Row{"id": int64(-1)}, true, false, false, replayDuplicates, false},
		{"expression_unique", "CREATE TABLE expression_unique (id int NOT NULL, v text); CREATE UNIQUE INDEX expression_unique_ix ON expression_unique ((id * 2))", ir.Row{"id": int64(1)}, true, false, false, replayLoud, false},
		{table: "deferrable_pk_only", ddl: "CREATE TABLE deferrable_pk_only (id int PRIMARY KEY DEFERRABLE, v text)", row: ir.Row{"id": int64(1)}, wantExists: true, wantRefusal: true},
		{"deferrable_pk_plus_nn_unique", "CREATE TABLE deferrable_pk_plus_nn_unique (id int PRIMARY KEY DEFERRABLE, u int NOT NULL UNIQUE, v text)", ir.Row{"id": int64(1), "u": int64(1)}, true, true, false, replayConverges, false},
		// HIGH 1: keyed on a surrogate the replayed rows never carry. The
		// applier renders ON CONFLICT (sid); every re-applied row draws a
		// fresh sid and collides with nothing.
		{"surrogate_bigserial_pk", "CREATE TABLE surrogate_bigserial_pk (sid bigserial PRIMARY KEY, id int NOT NULL, v text)", ir.Row{"id": int64(1)}, true, false, false, replayDuplicates, false},
		{"surrogate_identity_pk", "CREATE TABLE surrogate_identity_pk (sid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id int NOT NULL, v text)", ir.Row{"id": int64(1)}, true, false, false, replayDuplicates, false},
		{"surrogate_uuid_default_pk", "CREATE TABLE surrogate_uuid_default_pk (sid uuid DEFAULT gen_random_uuid() PRIMARY KEY, id int NOT NULL, v text)", ir.Row{"id": int64(1)}, true, false, false, replayDuplicates, false},
		{"surrogate_nn_unique_only", "CREATE TABLE surrogate_nn_unique_only (sid bigserial NOT NULL UNIQUE, id int NOT NULL, v text)", ir.Row{"id": int64(1)}, true, false, false, replayDuplicates, false},
		// Two keys, one supplied. The arbiter loadConflictKey picks is the
		// one judged: the PK when there is one, and among UNIQUE indexes the
		// one with fewest columns. When it is the UNSUPPLIED one, the
		// supplied index still collides — as a 23505 the broker can never
		// get past — so the probe refuses it up front (loud either way).
		{"two_keys_pk_unsupplied", "CREATE TABLE two_keys_pk_unsupplied (sid bigserial PRIMARY KEY, id int NOT NULL UNIQUE, v text)", ir.Row{"id": int64(1)}, true, false, false, replayLoud, false},
		{"two_keys_pk_supplied", "CREATE TABLE two_keys_pk_supplied (id int PRIMARY KEY, u uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE, v text)", ir.Row{"id": int64(1)}, true, true, false, replayConverges, false},
		{"two_uniques_arbiter_unsupplied", "CREATE TABLE two_uniques_arbiter_unsupplied (s bigserial NOT NULL, a int NOT NULL, b int NOT NULL, v text, CONSTRAINT z_ab UNIQUE (a, b), CONSTRAINT a_s UNIQUE (s))", ir.Row{"a": int64(1), "b": int64(1)}, true, false, false, replayLoud, false},
		{"two_uniques_arbiter_supplied", "CREATE TABLE two_uniques_arbiter_supplied (s bigserial NOT NULL, a int NOT NULL, v text, CONSTRAINT z_s UNIQUE (s), CONSTRAINT a_a UNIQUE (a))", ir.Row{"a": int64(1)}, true, true, false, replayConverges, false},
		// A generated arbiter derived only from supplied columns converges,
		// but the probe cannot see what its expression reads: conservative.
		{"generated_pk", "CREATE TABLE generated_pk (id int NOT NULL, k int GENERATED ALWAYS AS (id * 2) STORED PRIMARY KEY, v text)", ir.Row{"id": int64(1)}, true, false, false, replayConverges, true},
	}
	for _, c := range cases {
		if c.ddl != "" {
			applyPGApplier(t, dsn, c.ddl)
		}
	}

	rw, err := (Engine{}).OpenRowWriter(ctx, dsn)
	if err != nil {
		t.Fatalf("OpenRowWriter: %v", err)
	}
	defer func() {
		if c, ok := rw.(interface{ Close() error }); ok {
			_ = c.Close()
		}
	}()
	prober, ok := rw.(ir.ReplayKeyProber)
	if !ok {
		t.Fatal("the Postgres row writer does not implement ir.ReplayKeyProber — the F-E1 target judgment is inert")
	}

	sawKeyed, sawSilent := false, false
	for _, c := range cases {
		t.Run(c.table, func(t *testing.T) {
			exists, keyed, err := prober.ProbeReplayKey(ctx, replayRecordedTable(c.table, c.row))
			if c.wantRefusal {
				if ce, ok := sluicecode.FromError(err); !ok || ce.Code != sluicecode.CodeTargetDeferrableKey {
					t.Fatalf("ProbeReplayKey = (%v, %v, %v); want the applier's %s refusal",
						exists, keyed, err, sluicecode.CodeTargetDeferrableKey)
				}
				return
			}
			if err != nil {
				t.Fatalf("ProbeReplayKey: %v", err)
			}
			if exists != c.wantExists || keyed != c.wantKeyed {
				t.Fatalf("ProbeReplayKey = (exists=%v, keyed=%v); want (%v, %v)", exists, keyed, c.wantExists, c.wantKeyed)
			}
			if !exists {
				return
			}

			row := ir.Row{"v": "x"}
			for k, v := range c.row {
				row[k] = v
			}
			ins := ir.Insert{Schema: "public", Table: c.table, Row: row}
			if err := applyDeferrableEvents(t, dsn, []ir.Change{ins}); err != nil {
				t.Fatalf("first apply: %v", err)
			}
			got := replayConverges
			if err := applyDeferrableEvents(t, dsn, []ir.Change{ins}); err != nil {
				got = replayLoud
			} else if n := pgScalarInt(t, dsn, "SELECT count(*) FROM public."+c.table); n == 2 {
				got = replayDuplicates
			}
			if got != c.outcome {
				t.Fatalf("re-applying one INSERT %s; the case declares %s — the ground truth moved", got, c.outcome)
			}
			if !c.conservative && keyed != (got == replayConverges) {
				t.Errorf("probe says keyed=%v but a re-apply %s", keyed, got)
			}
			if got == replayDuplicates && keyed {
				t.Error("a silently duplicating table was judged keyed")
			}
			sawKeyed = sawKeyed || keyed
			sawSilent = sawSilent || got == replayDuplicates
		})
	}
	if !sawKeyed || !sawSilent {
		t.Fatalf("anti-vacuity: the matrix must reach a keyed table and a silently duplicating one (keyed=%v, silent=%v)", sawKeyed, sawSilent)
	}
}

// replayRecordedTable is the recorded (backup) definition a case's replayed
// rows come from: exactly the row's columns plus "v", each nullable when the
// case's value is NULL. The probe's supplied-column set is derived from it.
func replayRecordedTable(name string, row ir.Row) *ir.Table {
	t := &ir.Table{Name: name, Columns: []*ir.Column{{Name: "v", Type: ir.Text{}, Nullable: true}}}
	for col, val := range row {
		t.Columns = append(t.Columns, &ir.Column{Name: col, Type: ir.Integer{Width: 64}, Nullable: val == nil})
	}
	return t
}

// TestRowWriter_ProbeReplayKey_InsteadOfView is audit item C's Postgres half,
// measured through the RESTORE writer (COPY), which is the path that door
// guards. A view an INSTEAD OF INSERT trigger makes writable, over a keyless
// log, accepts COPY and holds rows; the probe matched relkind r/p only, so it
// read "absent", and the restore door clears an absent table on the promise
// that it will be created from the recorded schema with its key. The
// independent expected value is the log's own row count after the same row
// is written twice.
//
// (The change applier does not reach this shape: it resolves column types
// for tables only and skips a change into anything else as an unknown table,
// recorded in its skip ledger.)
func TestRowWriter_ProbeReplayKey_InsteadOfView(t *testing.T) {
	dsn, cleanup := startPostgresForApplier(t)
	defer cleanup()
	ctx, cancel := context.WithTimeout(context.Background(), 120*time.Second)
	defer cancel()
	applyPGApplier(t, dsn, `CREATE TABLE view_log (id int NOT NULL, v text);
		CREATE VIEW view_instead_of AS SELECT id, v FROM view_log;
		CREATE FUNCTION view_instead_of_ins() RETURNS trigger LANGUAGE plpgsql AS $$
		BEGIN INSERT INTO view_log (id, v) VALUES (NEW.id, NEW.v); RETURN NEW; END $$;
		CREATE TRIGGER view_instead_of_ins INSTEAD OF INSERT ON view_instead_of
		FOR EACH ROW EXECUTE FUNCTION view_instead_of_ins();`)

	rwAny, err := (Engine{}).OpenRowWriter(ctx, dsn)
	if err != nil {
		t.Fatalf("OpenRowWriter: %v", err)
	}
	defer func() {
		if c, ok := rwAny.(interface{ Close() error }); ok {
			_ = c.Close()
		}
	}()
	recorded := replayRecordedTable("view_instead_of", ir.Row{"id": int64(1)})
	write := func() error {
		ch := make(chan ir.Row, 1)
		ch <- ir.Row{"id": int64(1), "v": "x"}
		close(ch)
		return rwAny.WriteRows(ctx, recorded, ch)
	}
	if err := write(); err != nil {
		t.Fatalf("first write through the restore writer: %v", err)
	}
	if err := write(); err != nil {
		t.Fatalf("second write: %v", err)
	}
	if n := pgScalarInt(t, dsn, "SELECT count(*) FROM view_log"); n != 2 {
		t.Fatalf("the same row written twice left %d rows in the log; the shape no longer duplicates, so this pin grades nothing", n)
	}

	empty, err := rwAny.(ir.TableEmptyChecker).IsTableEmpty(ctx, recorded)
	if err != nil || empty {
		t.Fatalf("IsTableEmpty = (%v, %v); want (false, nil) — the door reads rows under the name", empty, err)
	}
	exists, keyed, err := rwAny.(ir.ReplayKeyProber).ProbeReplayKey(ctx, recorded)
	if err != nil || !exists || keyed {
		t.Fatalf("ProbeReplayKey = (%v, %v, %v); want (true, false, nil): a relation holding rows under the name "+
			"is not absent, and a view has no key a re-written row collides on", exists, keyed, err)
	}
}
