//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// Phase A empirical verification for the slot-pause-based strict
// zero-loss live add-table mechanism (ADR-0033). The chunk's design
// hinges on a specific Postgres semantic that is NOT documented
// crisply in the official PG docs, so we measure it directly before
// committing to an implementation strategy.
//
// The question this test answers:
//
//   When the active stream's slot is held at LSN_pre (consumer paused
//   so confirmed_flush_lsn does not advance), and a new table is
//   added to the publication AFTER the slot has already streamed past
//   LSN_pre once, can a SUBSEQUENT START_REPLICATION at LSN_pre re-
//   decode the WAL between [LSN_pre, now] with the updated publication
//   scope and deliver events on the new table that occurred BEFORE the
//   publication-add LSN?
//
// If yes (H1 holds): the strict zero-loss path is implementable as
//                    "pause/stop streamer + ALTER + restart at LSN_pre".
// If no  (H1 fails): pgoutput does NOT re-decode retroactively even
//                    when the slot still has the WAL. The chunk needs
//                    a different mechanism (Strategy B dual-slot, or
//                    a more invasive pgoutput-internal hook).
//
// The test logs its findings explicitly so a CI run can be inspected
// post-facto and the ADR can quote the actual numbers. This is the
// "instrument and gather ground truth" step of the three-phase debug
// protocol applied to design verification.

package postgres

import (
	"context"
	"database/sql"
	"fmt"
	"testing"
	"time"

	"github.com/jackc/pglogrepl"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgproto3"
)

// TestSlotPause_Verify_RetainedWALReDecodesWithUpdatedPublication is
// the Phase A verification. It models the strict-zero-loss design's
// load-bearing assumption.
//
// Shape:
//  1. Boot PG with wal_level=logical.
//  2. Create publication `pub_existing` containing only `existing_tbl`.
//  3. Create logical slot `s_verify` with pgoutput.
//  4. INSERT on `existing_tbl` (decoded by the slot, used as a clean
//     anchor for confirmed_flush_lsn).
//  5. CREATE TABLE `new_tbl` (NOT in publication).
//  6. INSERT on `new_tbl` at LSN_F1 (BEFORE publication-add).
//  7. INSERT another row on `existing_tbl` at LSN_E2.
//  8. Open replication conn #1, START_REPLICATION at LSN_E1
//     (= captured before step 4's commit).
//  9. Drain a few messages — observe that we see BOTH `existing_tbl`
//     INSERTs but NOT the `new_tbl` INSERT (publication doesn't
//     include it). DO NOT send a StandbyStatusUpdate, so the slot's
//     confirmed_flush_lsn stays at LSN_E1.
//
// 10. Close replication conn #1.
// 11. ALTER PUBLICATION pub_existing ADD TABLE new_tbl.
// 12. Open replication conn #2, START_REPLICATION at LSN_E1 again.
// 13. Drain. Did `new_tbl`'s LSN_F1 INSERT appear this time?
//
// H1 holds iff step 13 yields the new_tbl INSERT. The test prints a
// verdict line so CI logs name the empirical result for the ADR.
func TestSlotPause_Verify_RetainedWALReDecodesWithUpdatedPublication(t *testing.T) {
	dsn, cleanup := startPostgresForCDC(t)
	defer cleanup()

	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Minute)
	defer cancel()

	const seedDDL = `
		CREATE TABLE existing_tbl (
			id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			label  TEXT NOT NULL
		);
		ALTER TABLE existing_tbl REPLICA IDENTITY FULL;
		CREATE PUBLICATION pub_existing FOR TABLE existing_tbl;
	`
	applyPGSQL(t, dsn, seedDDL)

	// Open a regular *sql.DB for catalog ops.
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		t.Fatalf("open db: %v", err)
	}
	defer func() { _ = db.Close() }()

	// Open a replication connection just to create the slot.
	slotConn, err := openReplicationConn(ctx, dsn)
	if err != nil {
		t.Fatalf("open slot replication conn: %v", err)
	}
	defer func() { _ = slotConn.Close(context.Background()) }()

	const slotName = "s_verify"
	if _, err := pglogrepl.CreateReplicationSlot(ctx, slotConn,
		slotName, "pgoutput",
		pglogrepl.CreateReplicationSlotOptions{Temporary: false, Mode: pglogrepl.LogicalReplication},
	); err != nil {
		t.Fatalf("CreateReplicationSlot: %v", err)
	}
	defer func() {
		// Best-effort cleanup; container teardown will handle the rest.
		_ = pglogrepl.DropReplicationSlot(context.Background(), slotConn, slotName, pglogrepl.DropReplicationSlotOptions{})
	}()

	// Capture LSN_pre BEFORE seeding the existing-table row, so the
	// slot is anchored at the very beginning of test activity. After
	// step 4's INSERT, confirmed_flush_lsn must still be LSN_pre
	// because we never send a StandbyStatusUpdate.
	lsnPre, err := currentWALLSN(ctx, db)
	if err != nil {
		t.Fatalf("read pg_current_wal_lsn pre-existing: %v", err)
	}
	t.Logf("LSN_pre (before any test inserts): %s", lsnPre)

	// Step 4: INSERT on existing_tbl (in publication) → an event the
	// slot will decode AND deliver during the first streaming pass.
	applyPGSQL(t, dsn, `INSERT INTO existing_tbl (label) VALUES ('e1');`)

	// Step 5+6: create new_tbl (NOT in publication) and INSERT on it.
	// This is the critical row — on the first streaming pass it gets
	// decoded-and-filtered by pgoutput because new_tbl isn't in the
	// publication. The question is whether a fresh START_REPLICATION
	// from LSN_pre, after publication-add, redelivers it.
	applyPGSQL(t, dsn, `
		CREATE TABLE new_tbl (
			id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			tag TEXT NOT NULL
		);
		ALTER TABLE new_tbl REPLICA IDENTITY FULL;
	`)
	applyPGSQL(t, dsn, `INSERT INTO new_tbl (tag) VALUES ('f1-pre-publication-add');`)

	// Step 7: another existing_tbl INSERT after the new_tbl INSERT,
	// so the WAL ordering is unambiguous: existing_tbl[e1] →
	// new_tbl[f1] → existing_tbl[e2] → (publication-add) →
	// existing_tbl[e3] (driven later in the test).
	applyPGSQL(t, dsn, `INSERT INTO existing_tbl (label) VALUES ('e2');`)

	// Step 8-9: First streaming pass. Drain a few messages WITHOUT
	// sending StandbyStatusUpdate. We expect to see e1, e2 from
	// existing_tbl but NOT f1 from new_tbl (filtered by publication
	// scope).
	pass1 := streamingPass(t, ctx, dsn, slotName, "pub_existing", lsnPre, 3*time.Second)
	t.Logf("pass1 (before publication-add): saw %d row events: %s", len(pass1.events), describeEvents(pass1.events))

	pass1HasF1 := containsTableEvent(pass1.events, "new_tbl")
	if pass1HasF1 {
		t.Errorf("pass1 unexpectedly observed a new_tbl event; the publication scope should exclude it: events=%s", describeEvents(pass1.events))
	}

	// Step 11: ALTER PUBLICATION ADD TABLE new_tbl. Capture LSN_pubadd
	// for diagnostic purposes.
	lsnBeforeAdd, err := currentWALLSN(ctx, db)
	if err != nil {
		t.Fatalf("read pg_current_wal_lsn before ALTER: %v", err)
	}
	applyPGSQL(t, dsn, `ALTER PUBLICATION pub_existing ADD TABLE new_tbl;`)
	lsnAfterAdd, err := currentWALLSN(ctx, db)
	if err != nil {
		t.Fatalf("read pg_current_wal_lsn after ALTER: %v", err)
	}
	t.Logf("publication-add boundary: lsn_before=%s lsn_after=%s", lsnBeforeAdd, lsnAfterAdd)

	// Insert one more row on each table after publication-add. The
	// existing_tbl[e3] is the unambiguous post-publication-add anchor;
	// new_tbl[f2] is what every pgoutput implementation will deliver
	// (post-publication-add events on a member table).
	applyPGSQL(t, dsn, `
		INSERT INTO existing_tbl (label) VALUES ('e3');
		INSERT INTO new_tbl (tag) VALUES ('f2-post-publication-add');
	`)

	// Confirm pg_replication_slots.confirmed_flush_lsn never advanced
	// past LSN_pre — we held the consumer all the way through.
	confirmed, err := readConfirmedFlushLSN(ctx, db, slotName)
	if err != nil {
		t.Fatalf("read confirmed_flush_lsn: %v", err)
	}
	t.Logf("confirmed_flush_lsn after pass1+ALTER: %s (LSN_pre=%s) — slot retention should hold WAL ≥ LSN_pre", confirmed, lsnPre)

	// Step 12-13: Second streaming pass at LSN_pre. THIS IS THE
	// LOAD-BEARING EXPERIMENT. If pgoutput re-decodes WAL [LSN_pre, now]
	// with the updated publication, we will see f1 (the
	// pre-publication-add new_tbl insert). If pgoutput's filter is
	// pinned at decode-time and that decode pass already happened
	// during pass1, we will NOT see f1 — only f2.
	pass2 := streamingPass(t, ctx, dsn, slotName, "pub_existing", lsnPre, 5*time.Second)
	t.Logf("pass2 (after publication-add, restart from LSN_pre): saw %d row events: %s", len(pass2.events), describeEvents(pass2.events))

	pass2HasF1 := containsRowWithTag(pass2.events, "new_tbl", "tag", "f1-pre-publication-add")
	pass2HasF2 := containsRowWithTag(pass2.events, "new_tbl", "tag", "f2-post-publication-add")

	switch {
	case pass2HasF1 && pass2HasF2:
		t.Logf("VERDICT_H1: HOLDS. pgoutput re-decoded WAL ≥ LSN_pre with the updated publication; both new_tbl rows (pre and post publication-add) were delivered. Strict-zero-loss via slot-pause + restart-at-LSN_pre is IMPLEMENTABLE as designed.")
	case !pass2HasF1 && pass2HasF2:
		t.Logf("VERDICT_H1: FAILS. pgoutput delivered the post-publication-add new_tbl row (f2) but NOT the pre-publication-add row (f1) on the restart-from-LSN_pre pass. Slot-pause + restart-at-LSN_pre alone cannot close the gap; pgoutput's per-LSN catalog snapshot pins publication membership at decode time and a re-decode pass at the same LSN sees the same (filtered) result.")
	case pass2HasF1 && !pass2HasF2:
		t.Errorf("VERDICT_H1: anomalous. pre-publication-add row delivered but post- not. Likely a streaming-pass timeout; rerun with longer drain.")
	default:
		t.Errorf("VERDICT_H1: anomalous. Neither new_tbl row delivered on pass2 — likely a slot-state issue; events=%s", describeEvents(pass2.events))
	}

	// Phase A complement — H2: does a temp-slot snapshot taken AFTER
	// publication-add capture rows on new_tbl committed BEFORE
	// publication-add? This is the load-bearing question for the v0.24.0
	// mechanism (publication-add → temp-slot-snapshot → bulk-copy). If
	// H2 holds, bulk-copy alone covers the pre-publication-add rows on
	// new_tbl, regardless of whether the active stream's CDC delivers
	// them. The under-load test's observed loss must originate
	// elsewhere (e.g. a window during which the snapshot is created
	// before some rows are committed but after the publication-add).
	if !verifyH2_TempSlotSnapshotCapturesPrePublicationAddRows(t, ctx, dsn, db) {
		// verifyH2 logs its own VERDICT line; do not double-log here.
		return
	}
}

// verifyH2_TempSlotSnapshotCapturesPrePublicationAddRows is the
// complement to H1. It tests the v0.24.0 baseline mechanism — does
// the temp-slot snapshot taken AFTER publication-add capture rows
// committed BEFORE publication-add on the new table?
//
// Returns true if H2 holds (snapshot captures expected rows). The
// test logs a VERDICT_H2 line either way so the ADR can quote it.
//
// Shape: this runs IN ADDITION to the H1 test on the same container,
// using a fresh "round 2" set of tables and publication so state from
// the H1 test doesn't interfere.
func verifyH2_TempSlotSnapshotCapturesPrePublicationAddRows(
	t *testing.T,
	ctx context.Context,
	dsn string,
	db *sql.DB,
) bool {
	t.Helper()

	applyPGSQL(t, dsn, `
		CREATE TABLE h2_existing (id BIGSERIAL PRIMARY KEY, label TEXT);
		ALTER TABLE h2_existing REPLICA IDENTITY FULL;
		CREATE PUBLICATION h2_pub FOR TABLE h2_existing;
		INSERT INTO h2_existing (label) VALUES ('h2-e1');
	`)

	// Create a "main slot" so WAL retention applies — the test
	// faithfully models v0.24.0's runtime where an active stream
	// already has a slot with progress.
	mainSlotConn, err := openReplicationConn(ctx, dsn)
	if err != nil {
		t.Fatalf("verifyH2: open main slot conn: %v", err)
	}
	defer func() { _ = mainSlotConn.Close(context.Background()) }()
	const mainSlot = "h2_main"
	if _, err := pglogrepl.CreateReplicationSlot(ctx, mainSlotConn,
		mainSlot, "pgoutput",
		pglogrepl.CreateReplicationSlotOptions{Mode: pglogrepl.LogicalReplication},
	); err != nil {
		t.Fatalf("verifyH2: create main slot: %v", err)
	}
	defer func() {
		_ = pglogrepl.DropReplicationSlot(context.Background(), mainSlotConn, mainSlot, pglogrepl.DropReplicationSlotOptions{})
	}()

	// Create the new table and INSERT BEFORE publication-add.
	applyPGSQL(t, dsn, `
		CREATE TABLE h2_new (id BIGSERIAL PRIMARY KEY, tag TEXT);
		ALTER TABLE h2_new REPLICA IDENTITY FULL;
		INSERT INTO h2_new (tag) VALUES ('h2-f1-pre-pub-add');
	`)

	// ALTER PUBLICATION ADD TABLE.
	applyPGSQL(t, dsn, `ALTER PUBLICATION h2_pub ADD TABLE h2_new;`)

	// Now create the temp-slot snapshot — same shape sluice's
	// AddTable.LiveMode does after the publication-add. The slot is
	// created with EXPORT_SNAPSHOT so we can read the snapshot view
	// from a regular SQL connection.
	tempSlotConn, err := openReplicationConn(ctx, dsn)
	if err != nil {
		t.Fatalf("verifyH2: open temp slot conn: %v", err)
	}
	defer func() { _ = tempSlotConn.Close(context.Background()) }()
	const tempSlot = "h2_temp"
	consistentPoint, snapshotName, err := createSlotViaPglogrepl(ctx, tempSlotConn, tempSlot, true)
	if err != nil {
		t.Fatalf("verifyH2: create temp slot: %v", err)
	}
	defer func() {
		_ = pglogrepl.DropReplicationSlot(context.Background(), tempSlotConn, tempSlot, pglogrepl.DropReplicationSlotOptions{})
	}()
	t.Logf("verifyH2: temp slot created. consistent_point=%s snapshot_name=%s", consistentPoint, snapshotName)

	// Read the snapshot via SET TRANSACTION SNAPSHOT and assert
	// h2_new contains the pre-publication-add row.
	tx, err := db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelRepeatableRead, ReadOnly: true})
	if err != nil {
		t.Fatalf("verifyH2: begin tx: %v", err)
	}
	defer func() { _ = tx.Rollback() }()
	if _, err := tx.ExecContext(ctx, fmt.Sprintf("SET TRANSACTION SNAPSHOT '%s'", snapshotName)); err != nil {
		t.Fatalf("verifyH2: SET TRANSACTION SNAPSHOT: %v", err)
	}

	rows, err := tx.QueryContext(ctx, "SELECT tag FROM h2_new ORDER BY id")
	if err != nil {
		t.Fatalf("verifyH2: SELECT FROM h2_new in snapshot: %v", err)
	}
	defer func() { _ = rows.Close() }()

	var tags []string
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			t.Fatalf("verifyH2: scan: %v", err)
		}
		tags = append(tags, tag)
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("verifyH2: rows.Err: %v", err)
	}

	t.Logf("verifyH2: temp-slot snapshot view of h2_new: %v", tags)
	containsPreAddRow := false
	for _, tag := range tags {
		if tag == "h2-f1-pre-pub-add" {
			containsPreAddRow = true
			break
		}
	}
	if containsPreAddRow {
		t.Logf("VERDICT_H2: HOLDS. The temp-slot snapshot taken after publication-add DOES capture rows committed on the new table BEFORE publication-add. v0.24.0's bulk-copy path correctly covers pre-publication-add rows; observed loss in TestAddTable_LiveMode_PG_UnderLoad must come from a different surface (timing race in snapshot creation under sustained burst, not from the publication-add boundary itself).")
		return true
	}
	t.Errorf("VERDICT_H2: FAILS. The temp-slot snapshot did NOT capture the pre-publication-add row (h2-f1-pre-pub-add); only saw %v. This contradicts standard PG MVCC snapshot semantics — the snapshot's consistent point should be ≥ publication-add LSN, and rows committed before that LSN should be visible.", tags)
	return false
}

// streamingPassResult captures what a single START_REPLICATION pass
// observed, for verdict assertions.
type streamingPassResult struct {
	events []rowEvent
}

// rowEvent is the pruned shape we care about for the verdict — table
// name + the values of one diagnostic column.
type rowEvent struct {
	table string
	row   map[string]any
}

// streamingPass opens a replication connection, runs START_REPLICATION
// at startLSN with the given publication, and drains messages until
// the deadline. Insert/Update/Delete row events on user tables are
// collected into the result; relation/begin/commit/keepalive messages
// are processed but not recorded. Crucially, this helper does NOT
// send any StandbyStatusUpdate — the slot's confirmed_flush_lsn must
// stay at startLSN so the second pass can replay from the same point.
func streamingPass(
	t *testing.T,
	ctx context.Context,
	dsn, slotName, publication string,
	startLSN pglogrepl.LSN,
	drainFor time.Duration,
) streamingPassResult {
	t.Helper()

	conn, err := openReplicationConn(ctx, dsn)
	if err != nil {
		t.Fatalf("streamingPass: open conn: %v", err)
	}
	defer func() { _ = conn.Close(context.Background()) }()

	pluginArgs := []string{
		"proto_version '2'",
		fmt.Sprintf("publication_names '%s'", publication),
	}
	if err := pglogrepl.StartReplication(ctx, conn, slotName, startLSN, pglogrepl.StartReplicationOptions{
		PluginArgs: pluginArgs,
	}); err != nil {
		t.Fatalf("streamingPass: START_REPLICATION at %s: %v", startLSN, err)
	}

	deadline := time.Now().Add(drainFor)
	relations := map[uint32]*relationCacheEntry{}
	var events []rowEvent

	for time.Now().Before(deadline) {
		recvCtx, cancel := context.WithDeadline(ctx, deadline)
		raw, err := conn.ReceiveMessage(recvCtx)
		cancel()
		if err != nil {
			if pgconn.Timeout(err) {
				break
			}
			t.Fatalf("streamingPass: ReceiveMessage: %v", err)
		}
		copyData, ok := raw.(*pgproto3.CopyData)
		if !ok {
			continue
		}
		if len(copyData.Data) == 0 {
			continue
		}
		switch copyData.Data[0] {
		case pglogrepl.PrimaryKeepaliveMessageByteID:
			// Ignore — do NOT reply. The point of this verification is
			// to NEVER send a StandbyStatusUpdate so the slot's
			// confirmed_flush_lsn never advances past startLSN.
			continue
		case pglogrepl.XLogDataByteID:
			xld, err := pglogrepl.ParseXLogData(copyData.Data[1:])
			if err != nil {
				t.Fatalf("streamingPass: ParseXLogData: %v", err)
			}
			logical, err := pglogrepl.ParseV2(xld.WALData, false)
			if err != nil {
				t.Fatalf("streamingPass: ParseV2: %v", err)
			}
			switch m := logical.(type) {
			case *pglogrepl.RelationMessageV2:
				if entry, err := buildRelationCacheEntry(m.RelationMessage); err == nil {
					relations[m.RelationID] = entry
				}
			case *pglogrepl.RelationMessage:
				if entry, err := buildRelationCacheEntry(*m); err == nil {
					relations[m.RelationID] = entry
				}
			case *pglogrepl.InsertMessageV2:
				if rel, ok := relations[m.RelationID]; ok {
					row, err := decodeTuple(m.Tuple, rel.Columns)
					if err == nil {
						events = append(events, rowEvent{table: rel.Name, row: row})
					}
				}
			case *pglogrepl.InsertMessage:
				if rel, ok := relations[m.RelationID]; ok {
					row, err := decodeTuple(m.Tuple, rel.Columns)
					if err == nil {
						events = append(events, rowEvent{table: rel.Name, row: row})
					}
				}
			}
		}
	}
	return streamingPassResult{events: events}
}

// currentWALLSN reads pg_current_wal_lsn() and returns it parsed.
func currentWALLSN(ctx context.Context, db *sql.DB) (pglogrepl.LSN, error) {
	var s string
	if err := db.QueryRowContext(ctx, "SELECT pg_current_wal_lsn()::text").Scan(&s); err != nil {
		return 0, err
	}
	return pglogrepl.ParseLSN(s)
}

// readConfirmedFlushLSN reads the slot's confirmed_flush_lsn for
// diagnostic logging in the verification.
func readConfirmedFlushLSN(ctx context.Context, db *sql.DB, slotName string) (string, error) {
	var s sql.NullString
	err := db.QueryRowContext(ctx,
		`SELECT confirmed_flush_lsn::text FROM pg_replication_slots WHERE slot_name = $1`,
		slotName,
	).Scan(&s)
	if err != nil {
		return "", err
	}
	if !s.Valid {
		return "", nil
	}
	return s.String, nil
}

// containsTableEvent reports whether any event in events targets the
// named table. Used by the verdict path to assert "new_tbl seen / not
// seen."
func containsTableEvent(events []rowEvent, table string) bool {
	for _, e := range events {
		if e.table == table {
			return true
		}
	}
	return false
}

// containsRowWithTag reports whether any event in events targets
// table and has row[col] == want. The verdict path uses this to
// distinguish the pre- vs post-publication-add rows on new_tbl.
func containsRowWithTag(events []rowEvent, table, col, want string) bool {
	for _, e := range events {
		if e.table != table {
			continue
		}
		got, ok := e.row[col].(string)
		if !ok {
			continue
		}
		if got == want {
			return true
		}
	}
	return false
}

// describeEvents renders a compact diagnostic for verdict log lines.
func describeEvents(events []rowEvent) string {
	if len(events) == 0 {
		return "[]"
	}
	out := make([]byte, 0, 64)
	out = append(out, '[')
	for i, e := range events {
		if i > 0 {
			out = append(out, ' ')
		}
		out = append(out, e.table...)
		out = append(out, '(')
		out = append(out, fmt.Sprintf("%v", e.row)...)
		out = append(out, ')')
	}
	out = append(out, ']')
	return string(out)
}
