//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// Integration test for the mid-stream live add-table flow (Phase 2,
// `--no-drain`, ADR-0030). The shape:
//
//  1. Cold-start a Streamer with a single table. Bulk-copy seeds.
//  2. Confirm CDC is healthy by inserting a row that flows through.
//  3. While the stream is still running, run AddTable with
//     LiveMode=true for a NEW source table that already has rows.
//     The new table is created on the target and bulk-copied.
//  4. INSERT a fresh row on the new table on the source. The
//     live stream's slot — whose publication scope was extended in
//     step 3 — delivers the event to the applier; the row lands on
//     the target.
//  5. Confirm the original table's CDC continued to function during
//     the add (no wedge).
//
// The PG-only refusal path is also covered: a MySQL source attempts
// the live mode and gets the clear PG-only error.

package pipeline

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	"github.com/orware/sluice/internal/engines"

	_ "github.com/orware/sluice/internal/engines/mysql"
	_ "github.com/orware/sluice/internal/engines/postgres"
)

// TestAddTable_LiveMode_PG runs the load-bearing scenario: live add
// of a new table against an actively-running stream. Verifies the
// existing table's CDC is unaffected and the new table is fully
// brought into the stream's scope (existing rows via snapshot + new
// rows via CDC).
func TestAddTable_LiveMode_PG(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresLogical(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE customers (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL
		);
		ALTER TABLE customers REPLICA IDENTITY FULL;
		INSERT INTO customers (email) VALUES ('alice@example.com');
	`
	applyDDL(t, sourceDSN, seedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	const streamID = "test-live-add"
	streamer := &Streamer{
		Source:    pgEng,
		Target:    pgEng,
		SourceDSN: sourceDSN,
		TargetDSN: targetDSN,
		StreamID:  streamID,
	}

	streamCtx, streamCancel := context.WithCancel(context.Background())
	defer streamCancel()
	runErr := make(chan error, 1)
	go func() { runErr <- streamer.Run(streamCtx) }()

	// Cold-start bulk-copy lands the seed row.
	if !waitForRowCount(t, targetDSN, "customers", 1, 30*time.Second) {
		t.Fatalf("bulk copy did not deliver customers seed row")
	}

	// Confirm CDC is healthy with a post-snapshot insert.
	applyDDL(t, sourceDSN, "INSERT INTO customers (email) VALUES ('bob@example.com');")
	if !waitForRowCount(t, targetDSN, "customers", 2, 30*time.Second) {
		t.Fatalf("CDC did not deliver post-snapshot insert on customers")
	}

	// ---- Live add-table for a NEW source table that already has rows.
	// The orders table is created on the source, populated with two
	// rows, then brought into the stream's scope via AddTable in live
	// mode. The stream keeps running throughout.
	const newTableDDL = `
		CREATE TABLE orders (
			id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			customer  BIGINT NOT NULL,
			amount    NUMERIC(10,2) NOT NULL
		);
		ALTER TABLE orders REPLICA IDENTITY FULL;
		INSERT INTO orders (customer, amount) VALUES (1, 19.99), (2, 42.00);
	`
	applyDDL(t, sourceDSN, newTableDDL)

	addCtx, addCancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer addCancel()
	add := &AddTable{
		Source:    pgEng,
		Target:    pgEng,
		SourceDSN: sourceDSN,
		TargetDSN: targetDSN,
		StreamID:  streamID,
		TableName: "orders",
		LiveMode:  true,
	}
	if err := add.Run(addCtx); err != nil {
		t.Fatalf("AddTable (live mode): %v", err)
	}

	// Snapshot rows landed on the target.
	if !waitForRowCount(t, targetDSN, "orders", 2, 30*time.Second) {
		t.Fatalf("live add did not deliver orders snapshot rows")
	}

	// Insert a fresh row on the new table; CDC should pick it up
	// (publication scope was extended at LSN P; pgoutput delivers
	// events on orders with LSN ≥ P to the slot).
	applyDDL(t, sourceDSN, "INSERT INTO orders (customer, amount) VALUES (1, 7.50);")
	if !waitForRowCount(t, targetDSN, "orders", 3, 30*time.Second) {
		t.Fatalf("CDC did not deliver post-add insert on orders — publication scope extension regressed")
	}

	// Sanity: original table's CDC continued to function during the
	// add (no wedge from publication-add-then-snapshot).
	applyDDL(t, sourceDSN, "INSERT INTO customers (email) VALUES ('carol@example.com');")
	if !waitForRowCount(t, targetDSN, "customers", 3, 30*time.Second) {
		t.Fatalf("CDC on original customers table wedged after live add")
	}

	streamCancel()
	select {
	case err := <-runErr:
		if err != nil {
			t.Errorf("Streamer.Run returned err: %v", err)
		}
	case <-time.After(20 * time.Second):
		t.Fatal("Streamer.Run did not return after ctx cancel")
	}
}

// TestAddTable_LiveMode_PG_UnderLoad runs live add while a goroutine
// drives sustained INSERTs on the new table. Pins: zero data loss
// (snapshot + CDC overlap fully covered) and no duplicates (the
// idempotent applier absorbs the [snapshot-LSN, slot-LSN] overlap on
// the new table). ADR-0030's "what could go wrong" lives or dies on
// this test.
func TestAddTable_LiveMode_PG_UnderLoad(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresLogical(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE customers (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL
		);
		ALTER TABLE customers REPLICA IDENTITY FULL;
		INSERT INTO customers (email) VALUES ('alice@example.com');
	`
	applyDDL(t, sourceDSN, seedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	const streamID = "test-live-add-load"
	streamer := &Streamer{
		Source:    pgEng,
		Target:    pgEng,
		SourceDSN: sourceDSN,
		TargetDSN: targetDSN,
		StreamID:  streamID,
	}

	streamCtx, streamCancel := context.WithCancel(context.Background())
	defer streamCancel()
	runErr := make(chan error, 1)
	go func() { runErr <- streamer.Run(streamCtx) }()

	if !waitForRowCount(t, targetDSN, "customers", 1, 30*time.Second) {
		t.Fatalf("bulk copy did not deliver customers seed row")
	}

	// Warm CDC + cdc-state row. The cdc-state row is created on the
	// applier's first per-change tx, NOT on bulk-copy completion.
	// Without this step, AddTable's preflight ListStreams query
	// returns an empty list and refuses with "no stream X on target"
	// before reaching the live-mode code path. ADR-0030's flow assumes
	// an active stream — the test must wait for that state to
	// materialize, not just for bulk-copy to land.
	applyDDL(t, sourceDSN, "INSERT INTO customers (email) VALUES ('warmup@example.com');")
	if !waitForRowCount(t, targetDSN, "customers", 2, 30*time.Second) {
		t.Fatalf("CDC did not deliver post-snapshot warmup insert; cdc-state row may not be written yet")
	}

	// Create the new table with 50 seed rows.
	const newTableDDL = `
		CREATE TABLE events (
			id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			body TEXT
		);
		ALTER TABLE events REPLICA IDENTITY FULL;
	`
	applyDDL(t, sourceDSN, newTableDDL)

	srcDB, err := sql.Open("pgx", sourceDSN)
	if err != nil {
		t.Fatalf("open source: %v", err)
	}
	defer func() { _ = srcDB.Close() }()

	const seedRowCount = 50
	seedCtx, seedCancel := context.WithTimeout(context.Background(), 30*time.Second)
	for i := 0; i < seedRowCount; i++ {
		if _, err := srcDB.ExecContext(seedCtx, `INSERT INTO events (body) VALUES ($1)`, fmt.Sprintf("seed-%d", i)); err != nil {
			seedCancel()
			t.Fatalf("seed insert %d: %v", i, err)
		}
	}
	seedCancel()

	// Driver goroutine: keep inserting fresh rows during the add.
	loadCtx, loadCancel := context.WithCancel(context.Background())
	var inserted atomic.Int64
	var loadWG sync.WaitGroup
	loadWG.Add(1)
	go func() {
		defer loadWG.Done()
		for {
			select {
			case <-loadCtx.Done():
				return
			default:
			}
			n := inserted.Add(1)
			if _, err := srcDB.ExecContext(loadCtx, `INSERT INTO events (body) VALUES ($1)`, fmt.Sprintf("load-%d", n)); err != nil {
				// Context cancellation is the expected exit path.
				if loadCtx.Err() != nil {
					return
				}
				// Surface unexpected errors via test-state side
				// channel; using t.Errorf from a goroutine is unsafe
				// per testing's contract. Decrement to keep the
				// counter aligned with successful inserts.
				inserted.Add(-1)
				return
			}
			time.Sleep(10 * time.Millisecond)
		}
	}()

	// Run live add.
	addCtx, addCancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer addCancel()
	add := &AddTable{
		Source:    pgEng,
		Target:    pgEng,
		SourceDSN: sourceDSN,
		TargetDSN: targetDSN,
		StreamID:  streamID,
		TableName: "events",
		LiveMode:  true,
	}
	if err := add.Run(addCtx); err != nil {
		loadCancel()
		loadWG.Wait()
		t.Fatalf("AddTable (live mode under load): %v", err)
	}

	// Stop the loader and wait for it to exit. Capture the final
	// inserted count.
	loadCancel()
	loadWG.Wait()
	finalInserted := inserted.Load()

	// Wait for CDC to drain so all of the load-* rows have flown
	// through. Total expected = seedRowCount + finalInserted.
	wantTotal := int(int64(seedRowCount) + finalInserted)
	if !waitForRowCount(t, targetDSN, "events", wantTotal, 60*time.Second) {
		got := pollRowCount(targetDSN, "events")
		t.Fatalf("under-load events row count = %d; want %d (zero data loss across snapshot + CDC overlap)", got, wantTotal)
	}

	// Pin: no duplicates. The PK is the GENERATED IDENTITY id; if the
	// applier double-applied any snapshot rows alongside CDC events,
	// either the COUNT(*) would exceed wantTotal (above) or the PK
	// constraint would have failed mid-stream. The applier's INSERT
	// ... ON CONFLICT DO NOTHING (ADR-0010) absorbs the overlap.
	// Cross-check via DISTINCT count.
	if got := distinctRowCount(t, targetDSN, "events", "id"); got != wantTotal {
		t.Errorf("under-load events DISTINCT id count = %d; want %d (duplicate ids implies idempotent applier regression)", got, wantTotal)
	}

	streamCancel()
	select {
	case err := <-runErr:
		if err != nil {
			t.Errorf("Streamer.Run returned err: %v", err)
		}
	case <-time.After(20 * time.Second):
		t.Fatal("Streamer.Run did not return after ctx cancel")
	}
}

// TestAddTable_LiveMode_MySQL_Refused confirms the MySQL source path
// gets a clear PG-only error rather than half-attempting the flow.
// Phase 2 is PG-only by design (ADR-0030); MySQL operators are
// pointed at the drained add-table flow.
func TestAddTable_LiveMode_MySQL_Refused(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startMySQLBinlog(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE users (
			id    BIGINT       NOT NULL AUTO_INCREMENT,
			email VARCHAR(255) NOT NULL,
			PRIMARY KEY (id)
		) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
		INSERT INTO users (email) VALUES ('alice@example.com');
	`
	applyDDLMySQL(t, sourceDSN, seedDDL)

	mysqlEng, ok := engines.Get("mysql")
	if !ok {
		t.Fatal("mysql engine not registered")
	}

	const streamID = "test-live-add-mysql"
	streamer := &Streamer{
		Source:    mysqlEng,
		Target:    mysqlEng,
		SourceDSN: sourceDSN,
		TargetDSN: targetDSN,
		StreamID:  streamID,
	}

	streamCtx, streamCancel := context.WithCancel(context.Background())
	defer streamCancel()
	runErr := make(chan error, 1)
	go func() { runErr <- streamer.Run(streamCtx) }()

	if !waitForRowCountMySQL(t, targetDSN, "users", 1, 30*time.Second) {
		t.Fatalf("bulk copy did not deliver users seed row")
	}

	// Warm CDC + cdc-state row before the refusal probe — without
	// this step the live-mode preflight refuses with "no stream X on
	// target" (the cdc-state row is written on first apply, not on
	// bulk-copy completion) and the assertion below would assert on
	// the wrong refusal message. Same shape as the PG happy-path
	// test's CDC-warmup step.
	applyDDLMySQL(t, sourceDSN, "INSERT INTO users (email) VALUES ('warmup@example.com');")
	if !waitForRowCountMySQL(t, targetDSN, "users", 2, 30*time.Second) {
		t.Fatalf("CDC did not deliver post-snapshot warmup insert; cdc-state row may not be written yet")
	}

	applyDDLMySQL(t, sourceDSN, `
		CREATE TABLE orders (
			id        BIGINT NOT NULL AUTO_INCREMENT,
			customer  BIGINT NOT NULL,
			PRIMARY KEY (id)
		) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
		INSERT INTO orders (customer) VALUES (1);
	`)

	addCtx, addCancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer addCancel()
	add := &AddTable{
		Source:    mysqlEng,
		Target:    mysqlEng,
		SourceDSN: sourceDSN,
		TargetDSN: targetDSN,
		StreamID:  streamID,
		TableName: "orders",
		LiveMode:  true,
	}
	err := add.Run(addCtx)
	if err == nil {
		t.Fatalf("AddTable (MySQL live mode): expected refusal; got nil")
	}
	if !containsAll(err.Error(), "publication-bearing", "drained add-table flow") {
		t.Errorf("MySQL refusal message missing expected hints; got: %v", err)
	}

	streamCancel()
	select {
	case <-runErr:
	case <-time.After(20 * time.Second):
		t.Fatal("Streamer.Run did not return after ctx cancel")
	}
}

// distinctRowCount returns the count of DISTINCT values in column
// for the named table. Used to detect double-applied rows (which
// would inflate COUNT(*) but leave DISTINCT id unchanged).
func distinctRowCount(t *testing.T, dsn, table, column string) int {
	t.Helper()
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer func() { _ = db.Close() }()
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	var n int
	q := fmt.Sprintf("SELECT COUNT(DISTINCT %s) FROM %s", column, table)
	if err := db.QueryRowContext(ctx, q).Scan(&n); err != nil {
		t.Fatalf("distinct-count: %v", err)
	}
	return n
}

// containsAll returns true when s contains every needle. Used in
// the refusal-message assertions to keep them readable.
func containsAll(s string, needles ...string) bool {
	for _, n := range needles {
		if !strings.Contains(s, n) {
			return false
		}
	}
	return true
}
