//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// Integration test for the mid-stream live add-table flow on PG
// (Phase 2, `--no-drain`, ADR-0030). The shape:
//
//  1. Cold-start a Streamer with a single table. Bulk-copy seeds.
//  2. Confirm CDC is healthy by inserting a row that flows through.
//  3. While the stream is still running, run AddTable with
//     LiveMode=true for a NEW source table that already has rows.
//     The new table is created on the target and bulk-copied.
//  4. INSERT a fresh row on the new table on the source. The
//     live stream's slot — whose publication scope was extended in
//     step 3 — delivers the event to the applier; the row lands on
//     the target.
//  5. Confirm the original table's CDC continued to function during
//     the add (no wedge).
//
// MySQL Phase 2 lives in add_table_live_mysql_integration_test.go
// (ADR-0034, filter-flip mechanism).

package pipeline

import (
	"context"
	"database/sql"
	"fmt"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/engines"

	_ "sluicesync.dev/sluice/internal/engines/postgres"
)

// TestStreamer_AddTable_LiveMode_PG runs the load-bearing scenario: live add
// of a new table against an actively-running stream. Verifies the
// existing table's CDC is unaffected and the new table is fully
// brought into the stream's scope (existing rows via snapshot + new
// rows via CDC).
func TestStreamer_AddTable_LiveMode_PG(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresLogical(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE customers (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL
		);
		ALTER TABLE customers REPLICA IDENTITY FULL;
		INSERT INTO customers (email) VALUES ('alice@example.com');
	`
	applyDDL(t, sourceDSN, seedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	const streamID = "test-live-add"
	streamer := &Streamer{
		Source:    pgEng,
		Target:    pgEng,
		SourceDSN: sourceDSN,
		TargetDSN: targetDSN,
		StreamID:  streamID,
	}

	streamCtx, streamCancel := context.WithCancel(context.Background())
	defer streamCancel()
	runErr := make(chan error, 1)
	go func() { runErr <- streamer.Run(streamCtx) }()

	// Cold-start bulk-copy lands the seed row.
	if !waitForRowCount(t, targetDSN, "customers", 1, 30*time.Second) {
		t.Fatalf("bulk copy did not deliver customers seed row")
	}

	// Confirm CDC is healthy with a post-snapshot insert.
	applyDDL(t, sourceDSN, "INSERT INTO customers (email) VALUES ('bob@example.com');")
	if !waitForRowCount(t, targetDSN, "customers", 2, 30*time.Second) {
		t.Fatalf("CDC did not deliver post-snapshot insert on customers")
	}

	// ---- Live add-table for a NEW source table that already has rows.
	// The orders table is created on the source, populated with two
	// rows, then brought into the stream's scope via AddTable in live
	// mode. The stream keeps running throughout.
	const newTableDDL = `
		CREATE TABLE orders (
			id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			customer  BIGINT NOT NULL,
			amount    NUMERIC(10,2) NOT NULL
		);
		ALTER TABLE orders REPLICA IDENTITY FULL;
		INSERT INTO orders (customer, amount) VALUES (1, 19.99), (2, 42.00);
	`
	applyDDL(t, sourceDSN, newTableDDL)

	addCtx, addCancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer addCancel()
	add := &AddTable{
		Source:    pgEng,
		Target:    pgEng,
		SourceDSN: sourceDSN,
		TargetDSN: targetDSN,
		StreamID:  streamID,
		TableName: "orders",
		LiveMode:  true,
	}
	if err := add.Run(addCtx); err != nil {
		t.Fatalf("AddTable (live mode): %v", err)
	}

	// Snapshot rows landed on the target.
	if !waitForRowCount(t, targetDSN, "orders", 2, 30*time.Second) {
		t.Fatalf("live add did not deliver orders snapshot rows")
	}

	// Insert a fresh row on the new table; CDC should pick it up
	// (publication scope was extended at LSN P; pgoutput delivers
	// events on orders with LSN ≥ P to the slot).
	applyDDL(t, sourceDSN, "INSERT INTO orders (customer, amount) VALUES (1, 7.50);")
	if !waitForRowCount(t, targetDSN, "orders", 3, 30*time.Second) {
		t.Fatalf("CDC did not deliver post-add insert on orders — publication scope extension regressed")
	}

	// Sanity: original table's CDC continued to function during the
	// add (no wedge from publication-add-then-snapshot).
	applyDDL(t, sourceDSN, "INSERT INTO customers (email) VALUES ('carol@example.com');")
	if !waitForRowCount(t, targetDSN, "customers", 3, 30*time.Second) {
		t.Fatalf("CDC on original customers table wedged after live add")
	}

	streamCancel()
	select {
	case err := <-runErr:
		if err != nil {
			t.Errorf("Streamer.Run returned err: %v", err)
		}
	case <-time.After(20 * time.Second):
		t.Fatal("Streamer.Run did not return after ctx cancel")
	}
}

// TestStreamer_AddTable_LiveMode_PG_UnderLoad runs live add while a goroutine
// drives sustained INSERTs on the new table. Pins: zero data loss
// (snapshot + CDC overlap fully covered) and no duplicates (the
// idempotent applier absorbs the [snapshot-LSN, slot-LSN] overlap on
// the new table). ADR-0030's "what could go wrong" lives or dies on
// this test.
func TestStreamer_AddTable_LiveMode_PG_UnderLoad(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresLogical(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE customers (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL
		);
		ALTER TABLE customers REPLICA IDENTITY FULL;
		INSERT INTO customers (email) VALUES ('alice@example.com');
	`
	applyDDL(t, sourceDSN, seedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	const streamID = "test-live-add-load"
	streamer := &Streamer{
		Source:    pgEng,
		Target:    pgEng,
		SourceDSN: sourceDSN,
		TargetDSN: targetDSN,
		StreamID:  streamID,
	}

	streamCtx, streamCancel := context.WithCancel(context.Background())
	defer streamCancel()
	runErr := make(chan error, 1)
	go func() { runErr <- streamer.Run(streamCtx) }()

	if !waitForRowCount(t, targetDSN, "customers", 1, 30*time.Second) {
		t.Fatalf("bulk copy did not deliver customers seed row")
	}

	// Warm CDC + cdc-state row. The cdc-state row is created on the
	// applier's first per-change tx, NOT on bulk-copy completion.
	// Without this step, AddTable's preflight ListStreams query
	// returns an empty list and refuses with "no stream X on target"
	// before reaching the live-mode code path. ADR-0030's flow assumes
	// an active stream — the test must wait for that state to
	// materialize, not just for bulk-copy to land.
	applyDDL(t, sourceDSN, "INSERT INTO customers (email) VALUES ('warmup@example.com');")
	if !waitForRowCount(t, targetDSN, "customers", 2, 30*time.Second) {
		t.Fatalf("CDC did not deliver post-snapshot warmup insert; cdc-state row may not be written yet")
	}

	// Create the new table with 50 seed rows.
	const newTableDDL = `
		CREATE TABLE events (
			id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			body TEXT
		);
		ALTER TABLE events REPLICA IDENTITY FULL;
	`
	applyDDL(t, sourceDSN, newTableDDL)

	srcDB, err := sql.Open("pgx", sourceDSN)
	if err != nil {
		t.Fatalf("open source: %v", err)
	}
	defer func() { _ = srcDB.Close() }()

	const seedRowCount = 50
	seedCtx, seedCancel := context.WithTimeout(context.Background(), 30*time.Second)
	for i := 0; i < seedRowCount; i++ {
		if _, err := srcDB.ExecContext(seedCtx, `INSERT INTO events (body) VALUES ($1)`, fmt.Sprintf("seed-%d", i)); err != nil {
			seedCancel()
			t.Fatalf("seed insert %d: %v", i, err)
		}
	}
	seedCancel()

	// Driver goroutine: keep inserting fresh rows during the add.
	// The counter increments AFTER successful commit so it always
	// matches actually-committed rows — the previous "increment
	// before insert + decrement on error" shape lost a row whenever
	// loadCancel fired mid-INSERT (the ctx-cancel branch returned
	// without decrementing because errors.Is(err, context.Canceled)
	// short-circuited the decrement path), producing an off-by-one
	// failure under CI's specific scheduler.
	//
	// The pause uses a select-on-loadCtx-with-time.After rather than
	// time.Sleep + ctx-aware Exec so the goroutine can't be killed
	// mid-INSERT — that's the other class of "did this commit?"
	// uncertainty (driver-side: pgx may have flushed the INSERT to
	// the wire and the server committed before the ctx-cancel
	// reached the client). With a clean pre-INSERT cancellation
	// check + ctx.Background() Exec, the counter is provably exact.
	loadCtx, loadCancel := context.WithCancel(context.Background())
	var inserted atomic.Int64
	var loadWG sync.WaitGroup
	loadWG.Add(1)
	go func() {
		defer loadWG.Done()
		var local int64
		for {
			select {
			case <-loadCtx.Done():
				inserted.Store(local)
				return
			default:
			}
			if _, err := srcDB.ExecContext(context.Background(), `INSERT INTO events (body) VALUES ($1)`, fmt.Sprintf("load-%d", local+1)); err != nil {
				inserted.Store(local)
				return
			}
			local++
			select {
			case <-loadCtx.Done():
				inserted.Store(local)
				return
			case <-time.After(10 * time.Millisecond):
			}
		}
	}()

	// Run live add.
	addCtx, addCancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer addCancel()
	add := &AddTable{
		Source:    pgEng,
		Target:    pgEng,
		SourceDSN: sourceDSN,
		TargetDSN: targetDSN,
		StreamID:  streamID,
		TableName: "events",
		LiveMode:  true,
	}
	if err := add.Run(addCtx); err != nil {
		loadCancel()
		loadWG.Wait()
		t.Fatalf("AddTable (live mode under load): %v", err)
	}

	// Stop the loader, drive a fresh post-add INSERT, then wait for
	// drain. The fresh insert pins that CDC for the new table is
	// healthy past the live-add boundary. Total expected = at least
	// seedRowCount + 1 (the post-add INSERT) — finalInserted load
	// rows are best-effort (see "what could go wrong" below).
	loadCancel()
	loadWG.Wait()
	finalInserted := inserted.Load()

	// Drive a post-add INSERT to verify CDC for the new table is
	// healthy beyond the publication-add boundary — this is the
	// load-bearing pin of the Phase 2 contract: events on the new
	// table at LSN > publication-add LSN are delivered exactly-once-
	// effectively. Use a sentinel body so the post-add row is
	// distinguishable from the load-* rows in the diagnostic below.
	if _, err := srcDB.ExecContext(context.Background(), `INSERT INTO events (body) VALUES ($1)`, "post-add-sentinel"); err != nil {
		t.Fatalf("post-add insert: %v", err)
	}

	// Wait for CDC to drain. The lower bound is seedRowCount + 1
	// (snapshot rows + post-add sentinel) — Phase 2's strict pin.
	// The upper bound is seedRowCount + finalInserted + 1 — what we'd
	// see in the perfect-zero-loss world. CI under heavy concurrent
	// load tends to land in between because of the in-flight-event
	// gap documented in ADR-0030 + below.
	minTotal := seedRowCount + 1
	maxTotal := int(int64(seedRowCount) + finalInserted + 1)
	if !waitForRowCount(t, targetDSN, "events", minTotal, 60*time.Second) {
		got := pollRowCount(targetDSN, "events")
		t.Fatalf("under-load events row count = %d; want at least %d (snapshot rows + post-add sentinel must all land)", got, minTotal)
	}

	// Pin the load-bearing post-add CDC delivery: the sentinel row
	// must be present on the target. Phase 2's contract is "events
	// at LSN > publication-add LSN are delivered" — this row is the
	// concrete instance.
	if !sentinelDelivered(t, targetDSN, "events", "post-add-sentinel") {
		t.Errorf("post-add-sentinel row NOT delivered to target — CDC delivery for new table after live add is broken (the load-bearing Phase 2 pin)")
	}

	got := pollRowCount(targetDSN, "events")

	// Strict zero-loss assertion. ADR-0036 Phase B closes the v0.24.0
	// best-effort gap: the orchestrator now creates the target table
	// BEFORE publication-add so the active stream's applier never
	// sees an `errUnknownTable` silent drop for CDC events on the
	// new table during the [publication-add, bulk-copy] window. Phase
	// A.3 confirmed 10/10 runs that the missing rows reach the applier
	// dispatch site (the M5c verdict); Phase B's fix is the targeted
	// `errUnknownTable` exposure closure. The ideal (zero-loss) count
	// is now the only acceptable shape. A regression here re-opens the
	// best-effort gap and warrants ADR-0036's diagnose protocol.
	if got != maxTotal {
		// Re-poll the source so the error message captures the actual
		// committed-vs-delivered state for triage. If the source row
		// count disagrees with finalInserted the loader race is back —
		// reach for the diagnose test to characterize.
		gotSource := pollRowCount(sourceDSN, "events")
		t.Errorf("under-load events row count = %d; want exactly %d (snapshot %d + load %d + post-add 1). Source committed = %d. ADR-0036 Phase B closes the in-flight-loss gap; a non-zero gap here is a regression — run TestStreamer_AddTable_LiveMode_PG_DiagnoseLossSurface against the same Postgres to characterize.",
			got, maxTotal, seedRowCount, finalInserted, gotSource)
	}

	// Pin: no duplicates. Whatever count actually landed, every row
	// has a distinct id. If the applier double-applied any snapshot
	// rows alongside CDC events, COUNT(*) would exceed COUNT(DISTINCT
	// id). The applier's INSERT ... ON CONFLICT DO NOTHING (ADR-0010)
	// absorbs the overlap.
	if distinct := distinctRowCount(t, targetDSN, "events", "id"); distinct != got {
		t.Errorf("under-load events DISTINCT id count = %d; total count = %d (duplicate ids implies idempotent applier regression)", distinct, got)
	}

	streamCancel()
	select {
	case err := <-runErr:
		if err != nil {
			t.Errorf("Streamer.Run returned err: %v", err)
		}
	case <-time.After(20 * time.Second):
		t.Fatal("Streamer.Run did not return after ctx cancel")
	}
}

// MySQL live-mode used to be a refusal path (PG-only at v0.24.0,
// ADR-0030). v0.27.0 lands ADR-0034: MySQL supports live add-table
// via the streamer-side filter-flip mechanism. The MySQL happy-path
// + under-load + filter-respected coverage moved to
// add_table_live_mysql_integration_test.go.

// sentinelDelivered polls the target for a row whose body column
// contains the sentinel string. Returns true once seen, polling up
// to 30 seconds. Used by the under-load test to pin Phase 2's
// load-bearing CDC contract: events on the new table at LSN >
// publication-add LSN are delivered exactly-once-effectively.
func sentinelDelivered(t *testing.T, dsn, table, sentinel string) bool {
	t.Helper()
	deadline := time.Now().Add(30 * time.Second)
	for time.Now().Before(deadline) {
		db, err := sql.Open("pgx", dsn)
		if err != nil {
			t.Fatalf("open: %v", err)
		}
		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		var present bool
		q := fmt.Sprintf("SELECT EXISTS (SELECT 1 FROM %s WHERE body = $1)", table)
		err = db.QueryRowContext(ctx, q, sentinel).Scan(&present)
		cancel()
		_ = db.Close()
		if err == nil && present {
			return true
		}
		time.Sleep(250 * time.Millisecond)
	}
	return false
}

// distinctRowCount returns the count of DISTINCT values in column
// for the named table. Used to detect double-applied rows (which
// would inflate COUNT(*) but leave DISTINCT id unchanged).
func distinctRowCount(t *testing.T, dsn, table, column string) int {
	t.Helper()
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer func() { _ = db.Close() }()
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	var n int
	q := fmt.Sprintf("SELECT COUNT(DISTINCT %s) FROM %s", column, table)
	if err := db.QueryRowContext(ctx, q).Scan(&n); err != nil {
		t.Fatalf("distinct-count: %v", err)
	}
	return n
}
