//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// v0.18.0 load-bearing integration test: the snapshot-anchored
// EndPosition closes the during-backup write-window gap that v0.17.x
// carried. The test seeds a source, takes a full backup whose row
// sweep is interleaved with concurrent writes, runs an incremental
// from the recorded EndPosition, restores the chain into a fresh
// target, and verifies every write — those committed BEFORE the
// snapshot AND those committed DURING the row sweep — lands on the
// target.
//
// Pre-fix shape (v0.17.x): writes that landed during the row sweep
// would be missing from BOTH the row chunks (no shared snapshot) AND
// the incremental's `--since=<full>.EndPosition` window (post-sweep
// EndPosition lies past those writes' LSNs). Restore would silently
// drop them.
//
// Post-fix shape (v0.18.0): the snapshot-anchored EndPosition lies
// AT snapshot start, before the during-window writes. The row sweep
// reads the source as it appeared at that anchor; the incremental's
// CDC pump from EndPosition forward picks up every write after.
// Restore lands a complete result.

package pipeline

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"sync"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/engines"
	irbackup "sluicesync.dev/sluice/internal/ir/backup"
	"sluicesync.dev/sluice/internal/pipeline/blobcodec"
	"sluicesync.dev/sluice/internal/pipeline/lineage"

	_ "sluicesync.dev/sluice/internal/engines/postgres"
)

// TestBackup_SnapshotAnchoredEndPosition_PostgresGapClosed pins the
// v0.18.0 fix end-to-end. The flow:
//
//  1. Seed source with N rows (the "pre-snapshot" set).
//  2. Run a full backup against the source. The orchestrator opens a
//     snapshot-anchored consistent view; EndPosition = snapshot LSN.
//  3. WHILE the backup's row sweep is in flight, the test fires M
//     concurrent INSERTs against the source (the "during-backup-
//     window" set). The snapshot view doesn't see them; they land
//     after the recorded EndPosition.
//  4. Backup completes. EndPosition is the snapshot's anchor LSN.
//  5. An incremental backup runs from EndPosition; CDC streams every
//     write at or after that LSN — including all M during-backup
//     writes.
//  6. Chain restore into a fresh target.
//  7. Verify the target reflects N + M rows.
//
// Pre-fix this test would catch the gap: M writes would be missing
// from the target. Post-fix the gap is closed.
func TestBackup_SnapshotAnchoredEndPosition_PostgresGapClosed(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresLogical(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL
		);
		ALTER TABLE users REPLICA IDENTITY FULL;

		INSERT INTO users (email) VALUES
			('alice@example.com'),
			('bob@example.com'),
			('carol@example.com');
	`
	applyDDL(t, sourceDSN, seedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	dir := t.TempDir()
	store, err := blobcodec.NewLocalStore(dir)
	if err != nil {
		t.Fatalf("NewLocalStore: %v", err)
	}

	// Pre-create the publication + chain-handoff slot so the
	// incremental can resume CDC. The full's snapshot uses a
	// SEPARATE temporary anchor slot internal to OpenBackupSnapshot;
	// the chain slot is what the manifest's EndPosition references.
	applyDDL(t, sourceDSN, `CREATE PUBLICATION sluice_pub FOR ALL TABLES`)
	if _, err := createPGLogicalSlotReturningLSN(t, sourceDSN, "sluice_slot"); err != nil {
		t.Fatalf("create chain slot: %v", err)
	}
	defer dropPGLogicalSlot(t, sourceDSN, "sluice_slot")

	// 1. Run the full backup in a goroutine; meanwhile fire concurrent
	//    writes after a short delay. The delay is long enough that the
	//    snapshot has been captured (so the writes go AFTER the
	//    consistent_point) but short enough that the row sweep is
	//    likely still running. Even if the row sweep finishes before
	//    our writes land, the load-bearing property holds: writes
	//    after the snapshot's anchor LSN must show up via the
	//    incremental's CDC from EndPosition forward, not via the row
	//    sweep itself.
	const duringWindowEmails = 4
	bgCtx, bgCancel := context.WithCancel(context.Background())
	defer bgCancel()
	var wg sync.WaitGroup
	wg.Add(1)
	go func() {
		defer wg.Done()
		// Small head start so the snapshot's slot creation has
		// committed before we start writing. 100ms is conservative
		// for testcontainers-on-localhost throughput.
		time.Sleep(100 * time.Millisecond)
		db, err := sql.Open("pgx", sourceDSN)
		if err != nil {
			t.Errorf("during-window writer open: %v", err)
			return
		}
		defer func() { _ = db.Close() }()
		for i := 0; i < duringWindowEmails; i++ {
			email := fmt.Sprintf("during-window-%d@example.com", i)
			if _, err := db.ExecContext(bgCtx,
				"INSERT INTO users (email) VALUES ($1)", email); err != nil {
				t.Errorf("during-window insert %d: %v", i, err)
				return
			}
			// Spread the writes a bit so at least one likely races the
			// row sweep mid-flight.
			time.Sleep(50 * time.Millisecond)
		}
	}()

	if err := (&Backup{
		Source:        pgEng,
		SourceDSN:     sourceDSN,
		Store:         store,
		SluiceVersion: "v0.18.0-test",
		SlotName:      "sluice_slot",
	}).Run(context.Background()); err != nil {
		t.Fatalf("Backup.Run: %v", err)
	}

	// Wait for the during-window writer to finish so all M writes
	// have committed before we open the incremental's CDC pump. If
	// the writer is still going when the incremental opens, we'd be
	// racing a separate concern (window-end position), and the load-
	// bearing property is "writes that happen DURING the backup are
	// captured by EndPosition's CDC stream forward."
	wg.Wait()

	full, err := lineage.ReadManifest(context.Background(), store)
	if err != nil {
		t.Fatalf("lineage.ReadManifest: %v", err)
	}
	if full.EndPosition.Token == "" {
		t.Fatal("full manifest has empty EndPosition; snapshot-anchored capture failed")
	}
	t.Logf("full manifest EndPosition = %s", full.EndPosition.Token)

	// 2. Incremental backup from the full's EndPosition. Window long
	//    enough to capture the during-window writes; MaxChanges
	//    bounded to the writes we expect plus a slack margin.
	incrCtx, incrCancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer incrCancel()
	incr := &IncrementalBackup{
		Source:        pgEng,
		SourceDSN:     sourceDSN,
		Store:         store,
		ParentRef:     full.BackupID,
		Window:        15 * time.Second,
		MaxChanges:    50,
		ChunkChanges:  20,
		SluiceVersion: "v0.18.0-test",
	}
	if err := incr.Run(incrCtx); err != nil {
		t.Fatalf("IncrementalBackup.Run: %v", err)
	}

	// 3. Verify the chain integrity (every chunk's SHA-256 still
	//    matches its recorded value).
	total, mismatches, err := VerifyBackup(context.Background(), store)
	if err != nil {
		t.Fatalf("VerifyBackup: %v", err)
	}
	if mismatches != 0 {
		t.Errorf("VerifyBackup: %d of %d chunks failed", mismatches, total)
	}

	// 4. Chain restore.
	if err := (&Restore{
		Target:    pgEng,
		TargetDSN: targetDSN,
		Store:     store,
	}).Run(context.Background()); err != nil {
		t.Fatalf("Restore.Run: %v", err)
	}

	// 5. Target must reflect every email — both pre-snapshot (alice,
	//    bob, carol) AND every during-window write. Pre-fix this is
	//    where the gap shows up: during-window writes would be
	//    missing because the row sweep didn't see them (no shared
	//    snapshot in v0.17.x) AND the incremental's `--since=<full>
	//    .EndPosition` window starts past their LSN. Post-fix
	//    EndPosition is the snapshot anchor, which is BEFORE those
	//    writes' LSNs, so the incremental's CDC stream picks them up.
	got := pgQueryEmails(t, targetDSN)
	gotMap := map[string]bool{}
	for _, e := range got {
		gotMap[e] = true
	}
	wantEmails := []string{
		"alice@example.com",
		"bob@example.com",
		"carol@example.com",
	}
	for i := 0; i < duringWindowEmails; i++ {
		wantEmails = append(wantEmails, fmt.Sprintf("during-window-%d@example.com", i))
	}
	for _, w := range wantEmails {
		if !gotMap[w] {
			t.Errorf("target missing email %q (got %d emails: %v)", w, len(got), got)
		}
	}
	if t.Failed() {
		t.Logf("v0.18.0 gap-fix regression: target was missing one or more during-backup-window writes; the snapshot-anchored EndPosition is supposed to ensure the chain's CDC catch-up captures every write after the snapshot point")
	}
}

// TestBackup_OpenBackupSnapshot_PostgresPositionShape pins the wire
// shape of the recorded position: the chain-handoff slot name (not
// the temporary anchor slot) and a non-empty LSN. Operators eyeball
// the manifest to spot misconfiguration; the test catches a future
// regression that records the wrong slot.
func TestBackup_OpenBackupSnapshot_PostgresPositionShape(t *testing.T) {
	sourceDSN, _, cleanup := startPostgresLogical(t)
	defer cleanup()

	applyDDL(t, sourceDSN, `
		CREATE TABLE users (id BIGINT PRIMARY KEY, email TEXT NOT NULL);
		INSERT INTO users (id, email) VALUES (1, 'alice@example.com');
	`)

	pgEng, _ := engines.Get("postgres")
	opener, ok := pgEng.(irbackup.SnapshotOpener)
	if !ok {
		t.Fatal("postgres engine does not implement BackupSnapshotOpener")
	}

	const chainSlot = "sluice_chain_test_slot"
	snap, err := opener.OpenBackupSnapshot(context.Background(), sourceDSN, irbackup.SnapshotOptions{SlotName: chainSlot})
	if err != nil {
		t.Fatalf("OpenBackupSnapshot: %v", err)
	}
	defer func() { _ = snap.Close() }()

	if snap.Position.Engine != "postgres" {
		t.Errorf("Position.Engine = %q; want postgres", snap.Position.Engine)
	}
	if snap.Position.Token == "" {
		t.Error("Position.Token is empty; want JSON envelope")
	}
	// Token must reference the chain-handoff slot name, not the
	// temporary anchor slot. Eyeball check via substring; the format
	// is `{"slot":"sluice_chain_test_slot","lsn":"…"}`.
	if want := `"slot":"` + chainSlot + `"`; !strings.Contains(snap.Position.Token, want) {
		t.Errorf("Position.Token = %s; want it to include %q (chain slot, not anchor slot)", snap.Position.Token, want)
	}
}
