//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// ADR-0046 §14d / ADR-0067 compact integration pin (Postgres,
// testcontainers).
//
// TestADR0067_BackupCompact_LiveRotationContiguous_Merges_PG — Drive a
// real CDC stream into a >= 3-segment rotated lineage under continuous
// write load, then compact. ADR-0067: the rotation handoff KEEPS the
// (P_N, S] overlap in each new segment's incrementals and records
// IncrementalCoverageStart = P_N, so consecutive segments are
// contiguous (prior.End == cur.IncrementalCoverageStart). Naive compact
// MERGES the chain, re-stitches the parent links across the former
// segment joins, and the merged chain restore-walks clean with a real
// position comparator. This is the Bug 95 regression pin.
//
// Pre-ADR-0067 this test asserted the OPPOSITE: live rotation produced
// strict S > P_N handoffs, the (P_N, S] window lived only in the
// dropped intermediate full, and compact refused loudly at the
// position-gap pre-flight. That genuine-gap refusal is still unit-
// covered (chain_compact_test.go's TestCompactChain_PositionGap_
// RefusesLoudly) for pre-0067 / imported / corrupted lineages.
//
// Aligned-position happy-path + rotated-overlap unit coverage lives in
// chain_compact_test.go (TestCompactChain_*Merges, ...RestoreShape...,
// TestCompactChain_RotatedOverlap_Merges) and the boundary matrix in
// chain_contiguous_rotation_test.go.

package pipeline

import (
	"context"
	"fmt"
	"strings"
	"sync"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/engines"
	"sluicesync.dev/sluice/internal/pipeline/blobcodec"
	"sluicesync.dev/sluice/internal/pipeline/lineage"

	_ "sluicesync.dev/sluice/internal/engines/postgres"
)

// TestADR0067_BackupCompact_LiveRotationContiguous_Merges_PG is the
// load-bearing Bug 95 pin: a real PG rotation chain under continuous CDC
// writes is now born-CONTIGUOUS (ADR-0067 keeps the (P_N, S] overlap in
// each new segment's incrementals and records IncrementalCoverageStart =
// P_N), so naive compact MERGES it and the merged chain restore-walks
// clean. Pre-ADR-0067 the strict S > P_N handoff forced a position-gap
// refusal (this test asserted that refusal); ADR-0067 deliberately
// replaces it with a successful, restorable merge. The position-gap
// refusal itself stays unit-covered for genuine gaps
// (TestCompactChain_PositionGap_RefusesLoudly).
func TestADR0067_BackupCompact_LiveRotationContiguous_Merges_PG(t *testing.T) {
	sourceDSN, _, cleanup := startPostgresLogical(t)
	defer cleanup()

	applyDDL(t, sourceDSN, `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL UNIQUE
		);
		ALTER TABLE users REPLICA IDENTITY FULL;
		INSERT INTO users (email) VALUES ('seed0@example.com');
	`)
	applyDDL(t, sourceDSN, `CREATE PUBLICATION sluice_pub FOR ALL TABLES`)
	slotLSN, err := createPGLogicalSlotReturningLSN(t, sourceDSN, "sluice_slot")
	if err != nil {
		t.Fatalf("create slot: %v", err)
	}
	defer dropPGLogicalSlot(t, sourceDSN, "sluice_slot")

	eng, _ := engines.Get("postgres")
	dir := t.TempDir()
	store, _ := blobcodec.NewLocalStore(dir)
	full := rotationSeedFull(t, store, eng, sourceDSN, slotLSN)

	const total = 30
	var wg sync.WaitGroup
	writeCtx, writeCancel := context.WithCancel(context.Background())
	wg.Add(1)
	go func() {
		defer wg.Done()
		for i := 0; i < total; i++ {
			select {
			case <-writeCtx.Done():
				return
			default:
			}
			applyDDL(t, sourceDSN, fmt.Sprintf(
				`INSERT INTO users (email) VALUES ('row%03d@example.com');`, i,
			))
			time.Sleep(40 * time.Millisecond)
		}
	}()

	stream := &BackupStream{
		Source:                    eng,
		SourceDSN:                 sourceDSN,
		Store:                     store,
		ParentRef:                 full.BackupID,
		RolloverWindow:            900 * time.Millisecond,
		RolloverMaxChanges:        6,
		RolloverMaxBytes:          1 << 30,
		ChunkChanges:              50,
		RetainRotateAtChainLength: 2,
		SluiceVersion:             "test",
	}
	ctx, cancel := context.WithTimeout(context.Background(), 120*time.Second)
	defer cancel()
	streamErr := make(chan error, 1)
	go func() { streamErr <- stream.Run(ctx) }()

	wg.Wait()
	writeCancel()
	time.Sleep(6 * time.Second)
	cancel()
	select {
	case err := <-streamErr:
		if err != nil {
			t.Fatalf("stream.Run = %v; want clean exit", err)
		}
	case <-time.After(20 * time.Second):
		t.Fatal("stream.Run did not exit within 20s of cancel")
	}

	lin, ok, err := lineage.LoadLineageCatalog(context.Background(), store)
	if err != nil || !ok {
		t.Fatalf("lineage.LoadLineageCatalog: ok=%v err=%v", ok, err)
	}
	preCompactSegmentCount := len(lin.Segments)
	if preCompactSegmentCount < 3 {
		t.Fatalf("pre-compact lineage segments = %d; want >= 3", preCompactSegmentCount)
	}
	t.Logf("pre-compact: %d segments", preCompactSegmentCount)

	// ADR-0067: live rotation now KEEPS the (P_N, S] overlap in each new
	// segment's incrementals (recording IncrementalCoverageStart = P_N),
	// so consecutive segments are CONTIGUOUS and naive compact MERGES
	// them — where pre-ADR-0067 the strict S > P_N handoff forced a
	// position-gap refusal. This is the Bug 95 regression pin.
	res, err := CompactChain(context.Background(), store, CompactOpts{
		MergeWindow: time.Hour, // window captures every rotation
	})
	if err != nil {
		if strings.Contains(err.Error(), "position gap") {
			t.Fatalf("ADR-0067 regression: live rotation produced a position gap that compact refused — rotated chains must be born-contiguous and compactable: %v", err)
		}
		t.Fatalf("CompactChain on live-rotation lineage: %v", err)
	}
	if res.GroupsMerged < 1 {
		t.Fatalf("GroupsMerged = %d; want >= 1 (a contiguous rotated chain must merge)", res.GroupsMerged)
	}

	// Segments were merged: the count dropped.
	postLin, _, _ := lineage.LoadLineageCatalog(context.Background(), store)
	if len(postLin.Segments) >= preCompactSegmentCount {
		t.Errorf("post-compact segments = %d; want < %d (merge reduces the segment count)",
			len(postLin.Segments), preCompactSegmentCount)
	}

	// The merged lineage must pass the full restore-walk boundary
	// validation with a REAL position comparator — proving the kept
	// (P_N, S] overlap is tolerated at the within-segment boundary AND
	// the re-stitched parent links chain cleanly across the former
	// segment joins (DR data — a merge that can't restore would be worse
	// than the old refusal).
	cmp := lineage.SameEngineComparator(context.Background(), store, eng)
	chain, err := lineage.BuildLineageChain(context.Background(), store, cmp)
	if err != nil {
		t.Fatalf("post-compact lineage.BuildLineageChain (restore-walk): %v", err)
	}
	if len(chain) < 2 {
		t.Fatalf("post-compact chain links = %d; want the merged full + its incrementals", len(chain))
	}
	t.Logf("ADR-0067 Bug-95 pin PROVEN: %d-segment live-rotation lineage merged to %d; merged chain restore-walks clean (%d links)",
		preCompactSegmentCount, len(postLin.Segments), len(chain))
}
