//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// Phase 6.1 integration tests: passphrase-mode envelope encryption.
// Covers the load-bearing acceptance criteria from
// `docs/dev/design-logical-backups-phase-6.md`:
//
//   1. Round-trip — encrypted backup + correct-passphrase restore lands
//      the original data byte-for-byte; chunk bytes on disk are NOT
//      plaintext.
//   2. Wrong-passphrase refusal — restore with the wrong key fails
//      with auth-tag-mismatch error; no partial data lands.
//   3. Missing-key refusal — encrypted chain restored without an
//      envelope refuses at chain-walk time with operator-actionable
//      error.
//   4. Per-chunk mode — each chunk's manifest entry carries its own
//      WrappedCEK (verified by inspection); restore round-trips clean.
//   5. Plaintext backward-compat — pre-Phase-6 chains restore
//      unchanged.

package pipeline

import (
	"bytes"
	"context"
	"io"
	"os"
	"path/filepath"
	"testing"

	"sluicesync.dev/sluice/internal/crypto"
	"sluicesync.dev/sluice/internal/engines"
	"sluicesync.dev/sluice/internal/ir"

	_ "sluicesync.dev/sluice/internal/engines/postgres"
)

// newTestPassphraseEnvelope returns a freshly-built passphrase
// envelope with default Argon2id params. Used by both the backup-side
// and restore-side construction in tests.
func newTestPassphraseEnvelope(t *testing.T, passphrase string) *crypto.PassphraseEnvelope {
	t.Helper()
	params, err := crypto.DefaultArgon2idParams()
	if err != nil {
		t.Fatalf("DefaultArgon2idParams: %v", err)
	}
	env, err := crypto.NewPassphraseEnvelope(passphrase, params)
	if err != nil {
		t.Fatalf("NewPassphraseEnvelope: %v", err)
	}
	return env
}

// envelopeFromManifest reads the chain root from store, extracts the
// recorded Argon2id params, and builds a restore-side
// PassphraseEnvelope using the supplied passphrase. Mirrors the CLI
// path's "read manifest, build envelope from recorded params" flow.
func envelopeFromManifest(t *testing.T, store ir.BackupStore, passphrase string) crypto.EnvelopeEncryption {
	t.Helper()
	root, err := ReadRootManifest(context.Background(), store)
	if err != nil {
		t.Fatalf("ReadRootManifest: %v", err)
	}
	if root == nil || root.ChainEncryption == nil || root.ChainEncryption.Argon2id == nil {
		t.Fatalf("manifest missing ChainEncryption.Argon2id")
	}
	p := root.ChainEncryption.Argon2id
	params := crypto.Argon2idParams{
		Salt:        p.Salt,
		Memory:      p.Memory,
		Iterations:  p.Iterations,
		Parallelism: p.Parallelism,
		KeyLen:      p.KeyLen,
	}
	env, err := crypto.NewPassphraseEnvelope(passphrase, params)
	if err != nil {
		t.Fatalf("NewPassphraseEnvelope: %v", err)
	}
	return env
}

// chunkContainsPlaintext reads a chunk file's bytes off disk and
// returns true if any of the supplied substrings appears as plaintext.
// Used by the round-trip test to confirm encryption actually happened.
func chunkContainsPlaintext(t *testing.T, store ir.BackupStore, chunkPath string, substrs ...string) bool {
	t.Helper()
	rc, err := store.Get(context.Background(), chunkPath)
	if err != nil {
		t.Fatalf("store.Get %q: %v", chunkPath, err)
	}
	defer func() { _ = rc.Close() }()
	b, err := io.ReadAll(rc)
	if err != nil {
		t.Fatalf("read chunk %q: %v", chunkPath, err)
	}
	for _, s := range substrs {
		if bytes.Contains(b, []byte(s)) {
			t.Logf("chunk %q contains plaintext substring %q (encryption broken?)", chunkPath, s)
			return true
		}
	}
	return false
}

// TestBackup_PassphraseEncryption_RoundTrip validates acceptance
// criterion 1: encrypt a PG full backup, verify chunks on disk are
// ciphertext, restore with the same passphrase, confirm data matches.
func TestBackup_PassphraseEncryption_RoundTrip(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL
		);
		INSERT INTO users (email) VALUES
			('alice@example.com'),
			('bob@example.com'),
			('carol@example.com');
	`
	applyDDL(t, sourceDSN, seedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	dir := t.TempDir()
	store, err := NewLocalStore(dir)
	if err != nil {
		t.Fatalf("NewLocalStore: %v", err)
	}

	const passphrase = "correct horse battery staple"
	envBackup := newTestPassphraseEnvelope(t, passphrase)

	if err := (&Backup{
		Source:        pgEng,
		SourceDSN:     sourceDSN,
		Store:         store,
		SluiceVersion: "v0.22.0-test",
		Encryption: &BackupEncryption{
			Envelope: envBackup,
			Mode:     crypto.EncryptModePerChain,
		},
	}).Run(context.Background()); err != nil {
		t.Fatalf("Backup.Run: %v", err)
	}

	// Manifest should carry encryption metadata.
	root, err := readManifest(context.Background(), store)
	if err != nil {
		t.Fatalf("readManifest: %v", err)
	}
	if root.ChainEncryption == nil {
		t.Fatal("ChainEncryption nil after encrypted backup")
	}
	if root.ChainEncryption.Algorithm != crypto.AlgorithmAESGCM {
		t.Errorf("Algorithm: got %q", root.ChainEncryption.Algorithm)
	}
	if root.ChainEncryption.Mode != crypto.EncryptModePerChain {
		t.Errorf("Mode: got %q", root.ChainEncryption.Mode)
	}
	if root.ChainEncryption.KEKMode != crypto.KEKModePassphrase {
		t.Errorf("KEKMode: got %q", root.ChainEncryption.KEKMode)
	}
	if len(root.ChainEncryption.WrappedCEK) == 0 {
		t.Errorf("WrappedCEK empty")
	}
	if root.ChainEncryption.Argon2id == nil {
		t.Errorf("Argon2id params missing")
	}

	// Each chunk's manifest entry should carry encryption metadata too.
	if len(root.Tables) == 0 || len(root.Tables[0].Chunks) == 0 {
		t.Fatalf("no chunks in manifest")
	}
	chunk := root.Tables[0].Chunks[0]
	if chunk.Encryption == nil {
		t.Errorf("ChunkInfo.Encryption nil")
	}
	if len(chunk.Encryption.WrappedCEK) != 0 {
		t.Errorf("per-chain mode: ChunkInfo.Encryption.WrappedCEK should be empty; got %d bytes", len(chunk.Encryption.WrappedCEK))
	}

	// On-disk chunk bytes must NOT contain any of the plaintext values.
	chunkPath := chunk.File
	if chunkContainsPlaintext(t, store, chunkPath, "alice", "bob", "carol", "@example.com") {
		t.Errorf("encrypted chunk on disk contains plaintext rows; encryption layer broken")
	}

	// Restore with the matching passphrase.
	envRestore := envelopeFromManifest(t, store, passphrase)
	if err := (&Restore{
		Target:    pgEng,
		TargetDSN: targetDSN,
		Store:     store,
		Envelope:  envRestore,
	}).Run(context.Background()); err != nil {
		t.Fatalf("Restore.Run: %v", err)
	}

	got := pgQueryEmails(t, targetDSN)
	gotMap := map[string]bool{}
	for _, e := range got {
		gotMap[e] = true
	}
	for _, want := range []string{"alice@example.com", "bob@example.com", "carol@example.com"} {
		if !gotMap[want] {
			t.Errorf("target missing email %q (got %v)", want, got)
		}
	}
}

// TestBackup_Encryption_WrongPassphrase validates acceptance
// criterion 2: restore with the wrong passphrase fails with a clear
// auth-tag-mismatch error.
func TestBackup_Encryption_WrongPassphrase(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()

	applyDDL(t, sourceDSN, `
		CREATE TABLE users (id BIGINT PRIMARY KEY, email VARCHAR(255));
		INSERT INTO users VALUES (1, 'alice@example.com');
	`)

	pgEng, _ := engines.Get("postgres")
	dir := t.TempDir()
	store, err := NewLocalStore(dir)
	if err != nil {
		t.Fatalf("NewLocalStore: %v", err)
	}

	envBackup := newTestPassphraseEnvelope(t, "right-pass")
	if err := (&Backup{
		Source:    pgEng,
		SourceDSN: sourceDSN,
		Store:     store,
		Encryption: &BackupEncryption{
			Envelope: envBackup,
			Mode:     crypto.EncryptModePerChain,
		},
	}).Run(context.Background()); err != nil {
		t.Fatalf("Backup.Run: %v", err)
	}

	// Restore with a wrong passphrase should fail before any data
	// lands on the target.
	envWrong := envelopeFromManifest(t, store, "wrong-pass")
	err = (&Restore{
		Target:    pgEng,
		TargetDSN: targetDSN,
		Store:     store,
		Envelope:  envWrong,
	}).Run(context.Background())
	if err == nil {
		t.Fatalf("expected restore to fail with wrong passphrase; got nil")
	}
}

// TestBackup_Encryption_MissingKey validates acceptance criterion 3:
// restoring an encrypted chain without an envelope refuses up-front.
func TestBackup_Encryption_MissingKey(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()

	applyDDL(t, sourceDSN, `
		CREATE TABLE users (id BIGINT PRIMARY KEY, email VARCHAR(255));
		INSERT INTO users VALUES (1, 'alice@example.com');
	`)

	pgEng, _ := engines.Get("postgres")
	dir := t.TempDir()
	store, err := NewLocalStore(dir)
	if err != nil {
		t.Fatalf("NewLocalStore: %v", err)
	}

	envBackup := newTestPassphraseEnvelope(t, "secret")
	if err := (&Backup{
		Source:    pgEng,
		SourceDSN: sourceDSN,
		Store:     store,
		Encryption: &BackupEncryption{
			Envelope: envBackup,
			Mode:     crypto.EncryptModePerChain,
		},
	}).Run(context.Background()); err != nil {
		t.Fatalf("Backup.Run: %v", err)
	}

	// No envelope → must refuse at preflight.
	err = (&Restore{
		Target:    pgEng,
		TargetDSN: targetDSN,
		Store:     store,
		// Envelope intentionally nil.
	}).Run(context.Background())
	if err == nil {
		t.Fatalf("expected restore to refuse without envelope; got nil")
	}
}

// TestBackup_Encryption_PerChunkMode validates acceptance criterion
// for per-chunk mode: every chunk carries its own WrappedCEK; restore
// round-trips clean.
func TestBackup_Encryption_PerChunkMode(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()

	applyDDL(t, sourceDSN, `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL
		);
		INSERT INTO users (email) VALUES
			('alice@example.com'),
			('bob@example.com');
	`)

	pgEng, _ := engines.Get("postgres")
	dir := t.TempDir()
	store, err := NewLocalStore(dir)
	if err != nil {
		t.Fatalf("NewLocalStore: %v", err)
	}

	envBackup := newTestPassphraseEnvelope(t, "per-chunk-pass")
	if err := (&Backup{
		Source:    pgEng,
		SourceDSN: sourceDSN,
		Store:     store,
		ChunkRows: 1, // force multiple chunks
		Encryption: &BackupEncryption{
			Envelope: envBackup,
			Mode:     crypto.EncryptModePerChunk,
		},
	}).Run(context.Background()); err != nil {
		t.Fatalf("Backup.Run: %v", err)
	}

	root, err := readManifest(context.Background(), store)
	if err != nil {
		t.Fatalf("readManifest: %v", err)
	}
	if root.ChainEncryption == nil {
		t.Fatal("ChainEncryption nil")
	}
	if root.ChainEncryption.Mode != crypto.EncryptModePerChunk {
		t.Errorf("Mode: got %q", root.ChainEncryption.Mode)
	}
	// Per-chunk mode: chain-level WrappedCEK is empty.
	if len(root.ChainEncryption.WrappedCEK) != 0 {
		t.Errorf("per-chunk mode: ChainEncryption.WrappedCEK should be empty; got %d bytes", len(root.ChainEncryption.WrappedCEK))
	}
	// Each chunk's WrappedCEK is non-empty.
	if len(root.Tables) == 0 {
		t.Fatalf("no tables in manifest")
	}
	chunks := root.Tables[0].Chunks
	if len(chunks) < 2 {
		t.Fatalf("expected multiple chunks for per-chunk-mode test; got %d", len(chunks))
	}
	for i, c := range chunks {
		if c.Encryption == nil {
			t.Errorf("chunk %d: Encryption nil", i)
			continue
		}
		if len(c.Encryption.WrappedCEK) == 0 {
			t.Errorf("chunk %d: per-chunk WrappedCEK is empty", i)
		}
	}

	// Round-trip restore.
	envRestore := envelopeFromManifest(t, store, "per-chunk-pass")
	if err := (&Restore{
		Target:    pgEng,
		TargetDSN: targetDSN,
		Store:     store,
		Envelope:  envRestore,
	}).Run(context.Background()); err != nil {
		t.Fatalf("Restore.Run: %v", err)
	}

	got := pgQueryEmails(t, targetDSN)
	if len(got) != 2 {
		t.Errorf("got %d emails want 2: %v", len(got), got)
	}
}

// TestBackup_PlaintextBackwardCompat validates acceptance criterion 6:
// pre-Phase-6 (plaintext) chains continue to restore unchanged.
func TestBackup_PlaintextBackwardCompat(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()

	applyDDL(t, sourceDSN, `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL
		);
		INSERT INTO users (email) VALUES ('alice@example.com');
	`)

	pgEng, _ := engines.Get("postgres")
	dir := t.TempDir()
	store, err := NewLocalStore(dir)
	if err != nil {
		t.Fatalf("NewLocalStore: %v", err)
	}

	// Plaintext backup (no Encryption field).
	if err := (&Backup{
		Source:    pgEng,
		SourceDSN: sourceDSN,
		Store:     store,
	}).Run(context.Background()); err != nil {
		t.Fatalf("Backup.Run: %v", err)
	}

	root, err := readManifest(context.Background(), store)
	if err != nil {
		t.Fatalf("readManifest: %v", err)
	}
	if root.ChainEncryption != nil {
		t.Errorf("plaintext backup: ChainEncryption should be nil; got %+v", root.ChainEncryption)
	}

	// Restore without envelope; must succeed.
	if err := (&Restore{
		Target:    pgEng,
		TargetDSN: targetDSN,
		Store:     store,
	}).Run(context.Background()); err != nil {
		t.Fatalf("Restore.Run: %v", err)
	}

	got := pgQueryEmails(t, targetDSN)
	if len(got) != 1 || got[0] != "alice@example.com" {
		t.Errorf("got %v want [alice@example.com]", got)
	}
}

// TestBackupVerify_EncryptedChain_NoKey validates acceptance criterion
// 8: `backup verify` runs without --encrypt + passphrase (sha256-only
// verification doesn't need decryption).
func TestBackupVerify_EncryptedChain_NoKey(t *testing.T) {
	sourceDSN, _, cleanup := startPostgres(t)
	defer cleanup()

	applyDDL(t, sourceDSN, `
		CREATE TABLE users (id BIGINT PRIMARY KEY, email VARCHAR(255));
		INSERT INTO users VALUES (1, 'alice@example.com');
	`)

	pgEng, _ := engines.Get("postgres")
	dir := t.TempDir()
	store, err := NewLocalStore(dir)
	if err != nil {
		t.Fatalf("NewLocalStore: %v", err)
	}

	env := newTestPassphraseEnvelope(t, "verify-pass")
	if err := (&Backup{
		Source:    pgEng,
		SourceDSN: sourceDSN,
		Store:     store,
		Encryption: &BackupEncryption{
			Envelope: env,
			Mode:     crypto.EncryptModePerChain,
		},
	}).Run(context.Background()); err != nil {
		t.Fatalf("Backup.Run: %v", err)
	}

	// Verify without any envelope.
	total, mismatches, err := VerifyBackup(context.Background(), store)
	if err != nil {
		t.Fatalf("VerifyBackup: %v", err)
	}
	if mismatches > 0 {
		t.Errorf("VerifyBackup: %d of %d failed", mismatches, total)
	}
	if total == 0 {
		t.Errorf("VerifyBackup: 0 chunks")
	}
}

// TestBackup_Encryption_LocalStoreDir confirms the chunk file on disk
// passes a plaintext sniff test in a freshly-located filesystem path
// (unrelated to the round-trip test, kept distinct so a future bug
// in LocalStore's path mapping doesn't escape).
func TestBackup_Encryption_LocalStoreDir(t *testing.T) {
	sourceDSN, _, cleanup := startPostgres(t)
	defer cleanup()

	applyDDL(t, sourceDSN, `
		CREATE TABLE users (id BIGINT PRIMARY KEY, email VARCHAR(255));
		INSERT INTO users VALUES (1, 'forensic-marker@example.com');
	`)

	pgEng, _ := engines.Get("postgres")
	dir := t.TempDir()
	store, err := NewLocalStore(dir)
	if err != nil {
		t.Fatalf("NewLocalStore: %v", err)
	}

	env := newTestPassphraseEnvelope(t, "forensic-pass")
	if err := (&Backup{
		Source:    pgEng,
		SourceDSN: sourceDSN,
		Store:     store,
		Encryption: &BackupEncryption{
			Envelope: env,
			Mode:     crypto.EncryptModePerChain,
		},
	}).Run(context.Background()); err != nil {
		t.Fatalf("Backup.Run: %v", err)
	}

	root, err := readManifest(context.Background(), store)
	if err != nil {
		t.Fatalf("readManifest: %v", err)
	}
	for _, table := range root.Tables {
		for _, c := range table.Chunks {
			abs := filepath.Join(dir, filepath.FromSlash(c.File))
			data, rerr := readFileForTest(abs)
			if rerr != nil {
				t.Fatalf("read chunk %q: %v", abs, rerr)
			}
			if bytes.Contains(data, []byte("forensic-marker")) {
				t.Errorf("chunk %q on disk contains plaintext marker; encryption broken", abs)
			}
			if bytes.Contains(data, []byte("@example.com")) {
				t.Errorf("chunk %q on disk contains plaintext domain", abs)
			}
		}
	}
}

// readFileForTest is a small wrapper over os.ReadFile that surfaces a
// clear error for the integration tests.
func readFileForTest(path string) ([]byte, error) {
	return os.ReadFile(path)
}
