//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// Phase 6.1 chain-extension regression tests (Bug 43, fixed in v0.22.1).
//
// The bug: the CLI's `buildBackupEncryption` minted a fresh Argon2id
// salt every call, so an `incremental --encrypt` or `stream run
// --encrypt` against an existing encrypted chain derived its KEK
// against the wrong salt and failed to unwrap the parent chain's
// WrappedCEK with `aes-gcm open: cipher: message authentication
// failed`. The read-side (`restore`) already mirrored the chain's
// recorded salt; the write-side did not.
//
// These tests pin the post-fix shape: a chain-extending writer
// supplied with a passphrase + the chain's recorded Argon2id params
// (via [BackupEncryption.RebuildForChain]) successfully extends the
// chain. Restore of the resulting chain lands every row from the
// full + every change from the incremental.
//
// Two-envelope shape: the full's envelope is built with a freshly-
// minted salt (the cold-start path). The incremental is given a
// SECOND fresh-salt envelope plus a RebuildForChain hook (mirroring
// what the CLI's `buildBackupEncryption` returns). Without the hook,
// the incremental's writer would unwrap the parent's WrappedCEK
// against the wrong salt and fail with auth-tag-mismatch — that's
// the v0.22.0 reproducer. With the hook populated, the orchestrator
// rebuilds the envelope against the chain's recorded salt before
// unwrap; restore round-trips clean.

package pipeline

import (
	"bytes"
	"context"
	"fmt"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/crypto"
	"sluicesync.dev/sluice/internal/engines"
	"sluicesync.dev/sluice/internal/ir"
	irbackup "sluicesync.dev/sluice/internal/ir/backup"

	_ "sluicesync.dev/sluice/internal/engines/postgres"
)

// passphraseRebuildHook is the test-local mirror of the CLI helper
// `passphraseRebuildForChain`: takes the operator's passphrase and
// returns a builder that derives an envelope from any supplied
// Argon2id params. Used to simulate what `buildBackupEncryption`
// produces.
func passphraseRebuildHook(passphrase string) func(*irbackup.Argon2idParams) (crypto.EnvelopeEncryption, error) {
	return func(p *irbackup.Argon2idParams) (crypto.EnvelopeEncryption, error) {
		if p == nil {
			return nil, fmt.Errorf("rebuild envelope: chain has no recorded Argon2id params")
		}
		return crypto.NewPassphraseEnvelope(passphrase, crypto.Argon2idParams{
			Salt:        p.Salt,
			Memory:      p.Memory,
			Iterations:  p.Iterations,
			Parallelism: p.Parallelism,
			KeyLen:      p.KeyLen,
		})
	}
}

// TestBackup_EncryptedChainExtension_Incremental_PG (Bug 43): full
// backup encrypted with envelope A (fresh salt); incremental started
// with envelope B (DIFFERENT fresh salt) plus RebuildForChain hook.
// The orchestrator rebinds B against the chain's recorded salt before
// unwrapping the parent CEK; the incremental commits cleanly. Chain
// restore (read-side mirrors the chain salt the same way) lands every
// row from both backups.
func TestBackup_EncryptedChainExtension_Incremental_PG(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresLogical(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL
		);
		ALTER TABLE users REPLICA IDENTITY FULL;
		INSERT INTO users (email) VALUES
			('alice@example.com'),
			('bob@example.com');
	`
	applyDDL(t, sourceDSN, seedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	dir := t.TempDir()
	store, err := NewLocalStore(dir)
	if err != nil {
		t.Fatalf("NewLocalStore: %v", err)
	}

	const passphrase = "correct horse battery staple"

	applyDDL(t, sourceDSN, `CREATE PUBLICATION sluice_pub FOR ALL TABLES`)
	slotLSN, err := createPGLogicalSlotReturningLSN(t, sourceDSN, "sluice_slot")
	if err != nil {
		t.Fatalf("create slot: %v", err)
	}
	defer dropPGLogicalSlot(t, sourceDSN, "sluice_slot")

	// 1. Encrypted full backup. Envelope A holds salt-A.
	envFull := newTestPassphraseEnvelope(t, passphrase)
	if err := (&Backup{
		Source:        pgEng,
		SourceDSN:     sourceDSN,
		Store:         store,
		SluiceVersion: "test-v0.22.1",
		Encryption: &BackupEncryption{
			Envelope: envFull,
			Mode:     crypto.EncryptModePerChain,
		},
	}).Run(context.Background()); err != nil {
		t.Fatalf("Backup.Run (full): %v", err)
	}

	full, err := readManifest(context.Background(), store)
	if err != nil {
		t.Fatalf("readManifest: %v", err)
	}
	if full.ChainEncryption == nil || full.ChainEncryption.Argon2id == nil {
		t.Fatal("full manifest missing ChainEncryption.Argon2id")
	}
	chainSalt := full.ChainEncryption.Argon2id.Salt
	if len(chainSalt) == 0 {
		t.Fatal("chain salt is empty")
	}

	// Stamp EndPosition + recompute BackupID so the incremental can
	// chain off the full (mirrors the pattern in incremental_pg
	// integration tests; v0.16.x fulls didn't record EndPosition).
	full.Kind = irbackup.BackupKindFull
	full.EndPosition = ir.Position{
		Engine: "postgres",
		Token:  fmt.Sprintf(`{"slot":"sluice_slot","lsn":%q}`, slotLSN),
	}
	full.BackupID = irbackup.ComputeBackupID(full)
	if err := writeManifestAt(context.Background(), store, ManifestFileName, full); err != nil {
		t.Fatalf("rewrite full manifest: %v", err)
	}

	// 2. Mutate source to generate CDC events.
	applyDDL(t, sourceDSN, `
		INSERT INTO users (email) VALUES ('carol@example.com');
		INSERT INTO users (email) VALUES ('dave@example.com');
	`)

	// 3. Encrypted incremental — envelope B has a DIFFERENT salt
	// from envelope A. Without RebuildForChain, the orchestrator
	// would call envB.UnwrapCEK(parent.WrappedCEK) and fail with
	// auth-tag-mismatch (this is the v0.22.0 reproducer). With
	// RebuildForChain populated, the orchestrator rebuilds the
	// envelope against the chain's recorded salt before unwrap.
	envIncrColdStart := newTestPassphraseEnvelope(t, passphrase)

	// Sanity guard: the two envelopes truly have distinct salts. If
	// DefaultArgon2idParams ever started returning a deterministic
	// salt, this test would silently lose its discriminating power.
	if bytes.Equal(envIncrColdStart.Params().Salt, chainSalt) {
		t.Fatal("test setup: cold-start incremental envelope happened to have same salt as full; cannot exercise Bug 43")
	}

	incrCtx, incrCancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer incrCancel()
	if err := (&IncrementalBackup{
		Source:        pgEng,
		SourceDSN:     sourceDSN,
		Store:         store,
		ParentRef:     full.BackupID,
		Window:        15 * time.Second,
		MaxChanges:    20,
		ChunkChanges:  10,
		SluiceVersion: "test-v0.22.1",
		Encryption: &BackupEncryption{
			Envelope:        envIncrColdStart,
			RebuildForChain: passphraseRebuildHook(passphrase),
			Mode:            crypto.EncryptModePerChain,
		},
	}).Run(incrCtx); err != nil {
		t.Fatalf("IncrementalBackup.Run: %v (Bug 43 regression)", err)
	}

	// 4. Verify chain integrity.
	total, mismatches, err := VerifyBackup(context.Background(), store)
	if err != nil {
		t.Fatalf("VerifyBackup: %v", err)
	}
	if mismatches != 0 {
		t.Errorf("VerifyBackup: %d of %d chunks failed", mismatches, total)
	}

	// 5. Chain restore. Read-side envelope is built from the chain's
	// recorded salt (envelopeFromManifest mirrors the production CLI
	// path's buildReadEnvelope shape).
	envRestore := envelopeFromManifest(t, store, passphrase)
	if err := (&Restore{
		Target:    pgEng,
		TargetDSN: targetDSN,
		Store:     store,
		Envelope:  envRestore,
	}).Run(context.Background()); err != nil {
		t.Fatalf("Restore.Run: %v", err)
	}

	// 6. Target should reflect every row from full + incremental.
	got := pgQueryEmails(t, targetDSN)
	want := map[string]bool{
		"alice@example.com": true,
		"bob@example.com":   true,
		"carol@example.com": true,
		"dave@example.com":  true,
	}
	gotMap := map[string]bool{}
	for _, e := range got {
		gotMap[e] = true
	}
	for w := range want {
		if !gotMap[w] {
			t.Errorf("target missing email %q (got: %v)", w, got)
		}
	}
}

// TestBackup_EncryptedChainExtension_NoRebuildHook_Fails is the
// "before the fix" assertion: without the RebuildForChain hook, an
// incremental given a fresh-salt envelope MUST fail to unwrap the
// chain CEK (auth-tag mismatch). Pins the failure mode that Bug 43
// produced on v0.22.0 so a future regression of the fix surfaces
// loudly here.
func TestBackup_EncryptedChainExtension_NoRebuildHook_Fails(t *testing.T) {
	sourceDSN, _, cleanup := startPostgresLogical(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL
		);
		ALTER TABLE users REPLICA IDENTITY FULL;
		INSERT INTO users (email) VALUES ('alice@example.com');
	`
	applyDDL(t, sourceDSN, seedDDL)

	pgEng, _ := engines.Get("postgres")
	dir := t.TempDir()
	store, err := NewLocalStore(dir)
	if err != nil {
		t.Fatalf("NewLocalStore: %v", err)
	}

	const passphrase = "regression-pin"

	applyDDL(t, sourceDSN, `CREATE PUBLICATION sluice_pub FOR ALL TABLES`)
	slotLSN, err := createPGLogicalSlotReturningLSN(t, sourceDSN, "sluice_slot")
	if err != nil {
		t.Fatalf("create slot: %v", err)
	}
	defer dropPGLogicalSlot(t, sourceDSN, "sluice_slot")

	envFull := newTestPassphraseEnvelope(t, passphrase)
	if err := (&Backup{
		Source:        pgEng,
		SourceDSN:     sourceDSN,
		Store:         store,
		SluiceVersion: "test-v0.22.1",
		Encryption: &BackupEncryption{
			Envelope: envFull,
			Mode:     crypto.EncryptModePerChain,
		},
	}).Run(context.Background()); err != nil {
		t.Fatalf("Backup.Run (full): %v", err)
	}
	full, err := readManifest(context.Background(), store)
	if err != nil {
		t.Fatalf("readManifest: %v", err)
	}
	full.Kind = irbackup.BackupKindFull
	full.EndPosition = ir.Position{
		Engine: "postgres",
		Token:  fmt.Sprintf(`{"slot":"sluice_slot","lsn":%q}`, slotLSN),
	}
	full.BackupID = irbackup.ComputeBackupID(full)
	if err := writeManifestAt(context.Background(), store, ManifestFileName, full); err != nil {
		t.Fatalf("rewrite full manifest: %v", err)
	}

	applyDDL(t, sourceDSN, `INSERT INTO users (email) VALUES ('bob@example.com');`)

	// Cold-start envelope (different salt) — no RebuildForChain.
	// Pre-fix v0.22.0 behaviour: this is exactly what the CLI used
	// to produce, and the orchestrator would happily call
	// envCold.UnwrapCEK(parent.WrappedCEK) → auth-tag failure.
	envCold := newTestPassphraseEnvelope(t, passphrase)

	incrCtx, incrCancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer incrCancel()
	err = (&IncrementalBackup{
		Source:        pgEng,
		SourceDSN:     sourceDSN,
		Store:         store,
		ParentRef:     full.BackupID,
		Window:        5 * time.Second,
		MaxChanges:    5,
		ChunkChanges:  5,
		SluiceVersion: "test-v0.22.1",
		Encryption: &BackupEncryption{
			Envelope: envCold,
			// RebuildForChain intentionally nil — pin the
			// pre-fix failure mode.
			Mode: crypto.EncryptModePerChain,
		},
	}).Run(incrCtx)
	if err == nil {
		t.Fatal("Bug 43 regression: incremental with a fresh-salt envelope and no RebuildForChain hook should fail to unwrap parent CEK; got nil")
	}
}
