//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// Roadmap item 100 — the refusal an ordinary retention cron actually
// hits, driven through the real prune path on a real Postgres chain.
//
// The sibling matrix file exercises this shape on a ROTATED chain, where
// it is one cell of a bigger table. This file pins the case that made
// item 100 a release blocker rather than a filed defect: a NON-rotated,
// single-segment chain, where EVERY `--keep-incrementals` prune is a
// within-segment trim, because no positive keep-count can retire a
// segment's incrementals entirely. That is the most ordinary retention
// invocation there is, and before this refusal it failed every time
// under prose ("the chain does not walk") that told the operator neither
// whether their backups were broken, nor whether sluice was, nor what to
// run instead.
//
// So the assertions here are about the REMEDY as much as the refusal:
// the message must name the shape, promise inertness, and name retention
// that works — and the test then proves both promises against the real
// chain, by restoring it row-exact after the refusal and by running the
// remedy it named.

package pipeline

import (
	"context"
	"fmt"
	"strings"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/engines"
	"sluicesync.dev/sluice/internal/ir"
	irbackup "sluicesync.dev/sluice/internal/ir/backup"
	"sluicesync.dev/sluice/internal/pipeline/backup"
	"sluicesync.dev/sluice/internal/pipeline/blobcodec"
	"sluicesync.dev/sluice/internal/pipeline/lineage"
	"sluicesync.dev/sluice/internal/sluicecode"

	_ "sluicesync.dev/sluice/internal/engines/postgres"
)

// seedSingleSegmentChainFixture is [seedRotatedChainFixture]'s deliberate
// opposite: an anchored full plus three one-shot `backup incremental`
// runs, and NO rotation — so the whole lineage is one segment.
//
// That absence is the fixture's entire point. A rotated chain has
// segment boundaries a keep-count can land on; a single-segment chain has
// none, so `--keep-incrementals` cannot express segment-granular
// retention there at all. Reusing [shapingFixture] rather than minting a
// second harness keeps the restore/verify/oracle plumbing identical to
// the matrix's, so a difference in outcome is about the CHAIN and not
// about the harness.
func seedSingleSegmentChainFixture(t *testing.T) *shapingFixture {
	t.Helper()
	sourceDSN, targetDSN, cleanup := startPostgresLogical(t)
	t.Cleanup(cleanup)

	applyDDL(t, sourceDSN, `
		CREATE TABLE ledger (
			id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			memo    VARCHAR(255) NOT NULL,
			balance BIGINT NOT NULL DEFAULT 0
		);
		ALTER TABLE ledger REPLICA IDENTITY FULL;
		INSERT INTO ledger (memo, balance) VALUES ('seed', 1);
	`)
	applyDDL(t, sourceDSN, `CREATE PUBLICATION sluice_pub FOR ALL TABLES`)
	slotLSN, err := createPGLogicalSlotReturningLSN(t, sourceDSN, "sluice_slot")
	if err != nil {
		t.Fatalf("create slot: %v", err)
	}
	t.Cleanup(func() { dropPGLogicalSlot(t, sourceDSN, "sluice_slot") })

	eng, _ := engines.Get("postgres")
	store, _ := blobcodec.NewLocalStore(t.TempDir())
	f := &shapingFixture{sourceDSN: sourceDSN, targetDSN: targetDSN, store: store}

	if err := (&backup.Backup{
		Source: eng, SourceDSN: sourceDSN, Store: store,
		SluiceVersion: "test", ChunkRows: 1,
	}).Run(context.Background()); err != nil {
		t.Fatalf("seed Backup.Run: %v", err)
	}
	full, err := lineage.ReadManifest(context.Background(), store)
	if err != nil {
		t.Fatalf("read seed full: %v", err)
	}
	full.Kind = irbackup.BackupKindFull
	full.EndPosition = ir.Position{
		Engine: "postgres",
		Token:  fmt.Sprintf(`{"slot":"sluice_slot","lsn":%q}`, slotLSN),
	}
	full.BackupID = irbackup.ComputeBackupID(full)
	if err := lineage.WriteManifestAt(context.Background(), store, lineage.ManifestFileName, full); err != nil {
		t.Fatalf("rewrite seed full: %v", err)
	}
	_ = lineage.UpdateLineageForManifestBestEffort(context.Background(), store, full, lineage.ManifestFileName, blobcodec.DefaultCodec)

	// Three incrementals, all resuming the OPEN (and only) segment.
	for i := 0; i < 3; i++ {
		f.insert(t, 2)
		f.runIncremental(t)
	}
	return f
}

// TestItem100_SingleSegmentKeepIncrementals_RefusesActionably is the pin
// the release blocker needs: the most ordinary retention invocation on
// the most ordinary chain shape must refuse with a message an operator
// can ACT on, and both of that message's promises must hold.
func TestItem100_SingleSegmentKeepIncrementals_RefusesActionably(t *testing.T) {
	ctx := context.Background()
	f := seedSingleSegmentChainFixture(t)

	// Non-vacuity 1: this really is a never-rotated chain. If rotation
	// ever crept into the fixture the test would be pinning the matrix's
	// case again, not this one.
	if segs := f.segments(t); segs != 1 {
		t.Fatalf("fixture produced %d segments; this pin is specifically about the SINGLE-segment (never-rotated) chain", segs)
	}
	pre, ok, err := lineage.LoadLineageCatalog(ctx, f.store)
	if err != nil || !ok {
		t.Fatalf("LoadLineageCatalog: ok=%v err=%v", ok, err)
	}
	if n := len(pre.Segments[0].Incrementals); n < 3 {
		t.Fatalf("segment holds %d incrementals; need >= 3 for a trim to leave survivors", n)
	}
	oracle := f.oracle(t)
	if oracle.n < 2 {
		t.Fatalf("source oracle has %d rows; the fixture produced nothing", oracle.n)
	}

	// Non-vacuity 2: --dry-run returns ahead of the readability gate by
	// design, so it enumerates what a real run would drop without
	// tripping it. A refusal over a prune that would have deleted nothing
	// proves nothing.
	plan, err := backup.PruneChain(ctx, f.store, backup.PruneOpts{KeepIncrementals: 1, DryRun: true})
	if err != nil {
		t.Fatalf("PruneChain --dry-run: %v", err)
	}
	if len(plan.Pruned) == 0 {
		t.Fatal("--keep-incrementals=1 planned nothing to drop; this pin would be vacuous")
	}

	_, err = backup.PruneChain(ctx, f.store, backup.PruneOpts{KeepIncrementals: 1})
	if err == nil {
		t.Fatal("`backup prune --keep-incrementals=1` on a single-segment chain SUCCEEDED — roadmap item 100's " +
			"within-segment trim appears fixed. Do not delete this test: re-read item 100, then promote it to a " +
			"round trip that pins the pruned chain's restorability.")
	}
	coded, codedOK := sluicecode.FromError(err)
	if !codedOK || coded.Code != sluicecode.CodeBackupChainUnreadable {
		t.Fatalf("refusal is not %s, so a retention cron cannot branch on it: %v", sluicecode.CodeBackupChainUnreadable, err)
	}
	if coded.ExitCode() != sluicecode.ExitRefusal {
		t.Errorf("ExitCode() = %d; want %d — a re-run will not help", coded.ExitCode(), sluicecode.ExitRefusal)
	}
	if coded.Hint == "" {
		t.Error("no standalone hint — the machine-readable remedy is exactly what item 100 was filed for")
	}
	// The message's three jobs, on a REAL chain: what happened, that
	// nothing was destroyed, and what to run instead.
	for _, want := range []string{
		"refusing --keep-incrementals=1",
		"within-segment incremental trim severs the chain",
		"still records parent",
		"pre-commit leg",
		"NOTHING WAS DELETED",
		"exactly as restorable as it was before this run",
		"No --keep-incrementals value lands on a segment boundary",
		"never-rotated (SINGLE-segment) chain none ever can",
		"--keep-duration",
	} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("the refusal is missing %q — it has regressed toward the unactionable generic prose:\n  %v", want, err)
		}
	}
	t.Logf("item-100 refusal:\n  %v", err)

	// PROMISE 1 — inertness, structurally and then behaviourally.
	post, ok, err := lineage.LoadLineageCatalog(ctx, f.store)
	if err != nil || !ok {
		t.Fatalf("post-refusal LoadLineageCatalog: ok=%v err=%v", ok, err)
	}
	if len(post.Segments) != len(pre.Segments) || len(post.Segments[0].Incrementals) != len(pre.Segments[0].Incrementals) {
		t.Fatalf("the pre-commit refusal rewrote the catalog: %+v; want the pre-prune shape %+v", post.Segments, pre.Segments)
	}
	if ex, _ := f.store.Exists(ctx, lineage.ManifestFileName); !ex {
		t.Error("the refusal deleted the chain-root manifest — the Bug-214/item-95 file it exists to protect")
	}
	if _, verr := f.verifyChain(t); verr != nil {
		t.Errorf("`backup verify` after the refusal: %v; the chain was supposed to be untouched", verr)
	}
	if rerr := f.restoreChain(t); rerr != nil {
		t.Fatalf("the refused chain does not restore — \"exactly as restorable as it was before this run\" is FALSE: %v", rerr)
	}
	if got := f.restored(t); got != oracle {
		t.Fatalf("restore after the refusal != source oracle: got %+v want %+v", got, oracle)
	}

	// PROMISE 2 — the remedy the message named actually works. A computed
	// remedy nobody ran is the same unactionable refusal with more words.
	res, err := backup.PruneChain(ctx, f.store, backup.PruneOpts{KeepDuration: time.Nanosecond})
	if err != nil {
		t.Fatalf("the --keep-duration remedy the refusal named still refuses: %v", err)
	}
	if len(res.Pruned) == 0 {
		t.Fatal("the named remedy pruned nothing — it is a no-op dressed as advice")
	}
	trimmed, ok, err := lineage.LoadLineageCatalog(ctx, f.store)
	if err != nil || !ok {
		t.Fatalf("post-remedy LoadLineageCatalog: ok=%v err=%v", ok, err)
	}
	if n := len(trimmed.Segments[0].Incrementals); n != 0 {
		t.Errorf("post-remedy incrementals = %d; want 0 (the segment keeps only its full)", n)
	}
	if _, err := lineage.BuildLineageChain(ctx, f.store, nil); err != nil {
		t.Errorf("the chain the named remedy produced does not walk: %v", err)
	}
	if _, verr := f.verifyChain(t); verr != nil {
		t.Errorf("`backup verify` on the chain the named remedy produced: %v", verr)
	}
}
