//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// ADR-0046 §14d compact integration pin (Task #15, Postgres,
// testcontainers).
//
// TestADR0046_BackupCompact_LiveRotationGap_RefusesLoudly_PG — Drive
// a real CDC stream into a >= 3-segment rotated lineage under
// continuous write load, then attempt compact. PG's rotation FSM
// allows S >= P_N (strict ≥); under continuous write the snapshot
// anchor S routinely lands AT a strictly later LSN than the prior
// segment's last incremental P_N (a handful of bytes of WAL between
// them — slot-flush metadata or intervening writes). Naive compact
// would have to drop the intermediate full's snapshot bytes to merge,
// but those bytes carry row-state captured ONLY in that full (writes
// that landed between P_N and S_next don't appear in any incremental).
// The compact pre-flight REFUSES LOUDLY (per ADR-0046 §14d
// position-gap loud-failure clause) — operators get a clear message
// naming the boundary segments, and the catalog stays unchanged.
// This is the load-bearing pin: the refusal saves the operator from
// a silent-loss class that the unit tests (which use
// position-aligned seed lineages) can't surface.
//
// Aligned-position happy-path coverage lives in
// chain_compact_test.go's unit pin matrix
// (TestCompactChain_TwoSegmentGroup_Merges,
// TestCompactChain_ThreeSegmentGroup_Merges,
// TestCompactChain_RestoreShape_PostCompact); those use in-memory
// stores + hand-seeded lineages so positions align exactly.

package pipeline

import (
	"context"
	"fmt"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/orware/sluice/internal/engines"

	_ "github.com/orware/sluice/internal/engines/postgres"
)

// TestADR0046_BackupCompact_LiveRotationGap_RefusesLoudly_PG is the
// load-bearing loud-failure pin: a real PG rotation chain under
// continuous CDC writes carries position handoffs S > P_N (strict
// greater), and naive compact must refuse loudly rather than silently
// drop the dropped-full's snapshot row-state.
func TestADR0046_BackupCompact_LiveRotationGap_RefusesLoudly_PG(t *testing.T) {
	sourceDSN, _, cleanup := startPostgresLogical(t)
	defer cleanup()

	applyDDL(t, sourceDSN, `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL UNIQUE
		);
		ALTER TABLE users REPLICA IDENTITY FULL;
		INSERT INTO users (email) VALUES ('seed0@example.com');
	`)
	applyDDL(t, sourceDSN, `CREATE PUBLICATION sluice_pub FOR ALL TABLES`)
	slotLSN, err := createPGLogicalSlotReturningLSN(t, sourceDSN, "sluice_slot")
	if err != nil {
		t.Fatalf("create slot: %v", err)
	}
	defer dropPGLogicalSlot(t, sourceDSN, "sluice_slot")

	eng, _ := engines.Get("postgres")
	dir := t.TempDir()
	store, _ := NewLocalStore(dir)
	full := rotationSeedFull(t, store, eng, sourceDSN, slotLSN)

	const total = 30
	var wg sync.WaitGroup
	writeCtx, writeCancel := context.WithCancel(context.Background())
	wg.Add(1)
	go func() {
		defer wg.Done()
		for i := 0; i < total; i++ {
			select {
			case <-writeCtx.Done():
				return
			default:
			}
			applyDDL(t, sourceDSN, fmt.Sprintf(
				`INSERT INTO users (email) VALUES ('row%03d@example.com');`, i,
			))
			time.Sleep(40 * time.Millisecond)
		}
	}()

	stream := &BackupStream{
		Source:                    eng,
		SourceDSN:                 sourceDSN,
		Store:                     store,
		ParentRef:                 full.BackupID,
		RolloverWindow:            900 * time.Millisecond,
		RolloverMaxChanges:        6,
		RolloverMaxBytes:          1 << 30,
		ChunkChanges:              50,
		RetainRotateAtChainLength: 2,
		SluiceVersion:             "test",
	}
	ctx, cancel := context.WithTimeout(context.Background(), 120*time.Second)
	defer cancel()
	streamErr := make(chan error, 1)
	go func() { streamErr <- stream.Run(ctx) }()

	wg.Wait()
	writeCancel()
	time.Sleep(6 * time.Second)
	cancel()
	select {
	case err := <-streamErr:
		if err != nil {
			t.Fatalf("stream.Run = %v; want clean exit", err)
		}
	case <-time.After(20 * time.Second):
		t.Fatal("stream.Run did not exit within 20s of cancel")
	}

	lin, ok, err := loadLineageCatalog(context.Background(), store)
	if err != nil || !ok {
		t.Fatalf("loadLineageCatalog: ok=%v err=%v", ok, err)
	}
	preCompactSegmentCount := len(lin.Segments)
	if preCompactSegmentCount < 3 {
		t.Fatalf("pre-compact lineage segments = %d; want >= 3", preCompactSegmentCount)
	}
	t.Logf("pre-compact: %d segments", preCompactSegmentCount)

	// Live-rotation lineages routinely carry small position gaps
	// (S > P_N). Compact MUST refuse loudly per the position-gap
	// loud-failure clause.
	_, err = CompactChain(context.Background(), store, CompactOpts{
		MergeWindow: time.Hour, // window captures every rotation
	})
	if err == nil {
		t.Fatal("CompactChain on live-rotation lineage: nil error; want loud position-gap refusal")
	}
	if !strings.Contains(err.Error(), "position gap") {
		t.Errorf("err = %q; want the documented position-gap refusal", err.Error())
	}
	if !strings.Contains(err.Error(), "split the merge window") {
		t.Errorf("err = %q; want the recovery hint", err.Error())
	}

	// Catalog stays unchanged after the refusal — no partial mutation.
	postLin, _, _ := loadLineageCatalog(context.Background(), store)
	if len(postLin.Segments) != preCompactSegmentCount {
		t.Errorf("post-refusal segments = %d; want %d (no mutation)",
			len(postLin.Segments), preCompactSegmentCount)
	}
	t.Logf("ADR-0046 §14d loud-failure pin PROVEN: %d-segment lineage with live rotation gaps refused cleanly", preCompactSegmentCount)
}
