//go:build integration && kmsverify

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// ADR-0154 Phase 3a — AWS KMS manifest SIGNING against a localstack KMS
// container (asymmetric ECDSA key). Runs under `integration && kmsverify`
// alongside the KMS-ENCRYPTION legs (backup_kms_localstack_integration_
// test.go), reusing its localstack + Postgres helpers.
//
// What's covered (live, against localstack KMS + real PG):
//
//   1. KMS-signed + KMS-encrypted full + incremental chain → chain restore
//      byte-exact, with signatures verified via the exported PUBLIC key
//      (the offline DR path: verification holds only the public key, never
//      the KMS Sign grant).
//   2. Store-tamper leg — corrupting a signed manifest after the fact makes
//      the restore REFUSE with SLUICE-E-BACKUP-SIGNATURE-INVALID (the
//      signature caught exactly the substitution it exists to catch).
//   3. Keyless verification — the restore host is given only the public key
//      (fetched once via GetPublicKey), proving KMS Sign access is not
//      needed to verify.

package pipeline

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/crypto"
	"sluicesync.dev/sluice/internal/engines"
	"sluicesync.dev/sluice/internal/ir"
	irbackup "sluicesync.dev/sluice/internal/ir/backup"
	"sluicesync.dev/sluice/internal/pipeline/backup"
	"sluicesync.dev/sluice/internal/pipeline/blobcodec"
	"sluicesync.dev/sluice/internal/pipeline/lineage"
	"sluicesync.dev/sluice/internal/sluicecode"

	_ "sluicesync.dev/sluice/internal/engines/postgres"

	"github.com/aws/aws-sdk-go-v2/service/kms"
	kmstypes "github.com/aws/aws-sdk-go-v2/service/kms/types"
)

// createLocalstackKMSSigningKey creates a fresh ASYMMETRIC ECDSA-P256
// SIGN_VERIFY key and returns its ARN. Skips the test if localstack does
// not support asymmetric KMS (honest skip, not a silent green).
func createLocalstackKMSSigningKey(t *testing.T, endpoint string) string {
	t.Helper()
	client := kms.NewFromConfig(localstackAWSConfig(endpoint))
	out, err := client.CreateKey(context.Background(), &kms.CreateKeyInput{
		KeySpec:  kmstypes.KeySpecEccNistP256,
		KeyUsage: kmstypes.KeyUsageTypeSignVerify,
	})
	if err != nil {
		t.Skipf("localstack does not support asymmetric KMS signing keys (%v); real-cloud validation is the operator-run path", err)
	}
	if out.KeyMetadata == nil || out.KeyMetadata.Arn == nil {
		t.Fatal("localstack CreateKey (asymmetric) returned no key ARN")
	}
	return *out.KeyMetadata.Arn
}

func newLocalstackKMSSigner(t *testing.T, endpoint, keyARN string) *lineage.Signer {
	t.Helper()
	adapter, err := crypto.NewAWSKMSSigner(context.Background(), keyARN,
		crypto.WithAWSKMSSignConfig(localstackAWSConfig(endpoint)))
	if err != nil {
		t.Fatalf("NewAWSKMSSigner: %v", err)
	}
	return lineage.NewKMSSigner(adapter)
}

// TestBackup_KMSSign_EncryptedChain_RoundTrip covers criteria 1-3: a
// KMS-signed + KMS-encrypted full+incremental chain, verified with the
// exported public key and restored byte-exact, plus a store-tamper refusal.
func TestBackup_KMSSign_EncryptedChain_RoundTrip(t *testing.T) {
	endpoint, lsCleanup := startLocalstackKMS(t)
	defer lsCleanup()
	sourceDSN, targetDSN, cleanup := startPostgresLogical(t)
	defer cleanup()

	applyDDL(t, sourceDSN, `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL
		);
		ALTER TABLE users REPLICA IDENTITY FULL;
		INSERT INTO users (email) VALUES ('alice@example.com'), ('bob@example.com');
	`)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}
	store, err := blobcodec.NewLocalStore(t.TempDir())
	if err != nil {
		t.Fatalf("NewLocalStore: %v", err)
	}

	encKeyARN := createLocalstackKMSKey(t, endpoint)         // symmetric CEK-wrap key
	signKeyARN := createLocalstackKMSSigningKey(t, endpoint) // asymmetric signing key
	env := newLocalstackKMSEnvelope(t, endpoint, encKeyARN)
	signer := newLocalstackKMSSigner(t, endpoint, signKeyARN)

	applyDDL(t, sourceDSN, `CREATE PUBLICATION sluice_pub FOR ALL TABLES`)
	slotLSN, err := createPGLogicalSlotReturningLSN(t, sourceDSN, "sluice_slot")
	if err != nil {
		t.Fatalf("create slot: %v", err)
	}
	defer dropPGLogicalSlot(t, sourceDSN, "sluice_slot")

	// 1. KMS-signed + KMS-encrypted full backup.
	if err := (&backup.Backup{
		Source:        pgEng,
		SourceDSN:     sourceDSN,
		Store:         store,
		SluiceVersion: "test-kmsverify-sign",
		Encryption: &lineage.BackupEncryption{
			Envelope: env,
			Mode:     crypto.EncryptModePerChain,
			KEKRef:   encKeyARN,
		},
		Ed25519Signer: signer, // any --sign-key signer (here: kms)
	}).Run(context.Background()); err != nil {
		t.Fatalf("Backup.Run (full): %v", err)
	}

	// Stamp EndPosition so the incremental can chain (as the KMS-encryption
	// chain-extension test does).
	full, err := lineage.ReadManifest(context.Background(), store)
	if err != nil {
		t.Fatalf("ReadManifest: %v", err)
	}
	if full.FormatVersion != irbackup.FormatVersionChunkTableBinding {
		t.Fatalf("signed full manifest FormatVersion = %d, want %d (SEC-F1 row-chunk table binding)", full.FormatVersion, irbackup.FormatVersionChunkTableBinding)
	}
	full.Kind = irbackup.BackupKindFull
	full.EndPosition = ir.Position{Engine: "postgres", Token: fmt.Sprintf(`{"slot":"sluice_slot","lsn":%q}`, slotLSN)}
	full.BackupID = irbackup.ComputeBackupID(full)
	if err := lineage.WriteManifestAt(context.Background(), store, lineage.ManifestFileName, full); err != nil {
		t.Fatalf("rewrite full manifest: %v", err)
	}
	// Re-sign the full at its new BackupID + refresh the lineage sig.
	if err := lineage.ResignLineage(context.Background(), store, signer); err != nil {
		t.Fatalf("ResignLineage after EndPosition stamp: %v", err)
	}

	applyDDL(t, sourceDSN, `
		INSERT INTO users (email) VALUES ('carol@example.com');
		INSERT INTO users (email) VALUES ('dave@example.com');
	`)

	incrCtx, incrCancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer incrCancel()
	if err := (&IncrementalBackup{
		Source:        pgEng,
		SourceDSN:     sourceDSN,
		Store:         store,
		ParentRef:     full.BackupID,
		Window:        15 * time.Second,
		MaxChanges:    20,
		ChunkChanges:  10,
		SluiceVersion: "test-kmsverify-sign",
		Encryption: &lineage.BackupEncryption{
			Envelope: env,
			Mode:     crypto.EncryptModePerChain,
			KEKRef:   encKeyARN,
		},
		Ed25519Signer: signer,
	}).Run(incrCtx); err != nil {
		t.Fatalf("IncrementalBackup.Run: %v", err)
	}

	// Resolve the signing key's PUBLIC half — the ONLY material the restore
	// host needs to verify (no KMS Sign grant).
	verifyPub, err := crypto.FetchAWSKMSPublicKey(context.Background(), signKeyARN,
		crypto.WithAWSKMSSignConfig(localstackAWSConfig(endpoint)))
	if err != nil {
		t.Fatalf("FetchAWSKMSPublicKey: %v", err)
	}

	// 2. Chain restore, strict signature verification via the public key.
	envRestore := newLocalstackKMSEnvelope(t, endpoint, encKeyARN)
	if err := (&backup.Restore{
		Target:           pgEng,
		TargetDSN:        targetDSN,
		Store:            store,
		Envelope:         envRestore,
		VerifyKey:        verifyPub,
		RequireSignature: true,
	}).Run(context.Background()); err != nil {
		t.Fatalf("Restore.Run (signed chain): %v", err)
	}

	got := pgQueryEmails(t, targetDSN)
	gotMap := map[string]bool{}
	for _, e := range got {
		gotMap[e] = true
	}
	for _, want := range []string{"alice@example.com", "bob@example.com", "carol@example.com", "dave@example.com"} {
		if !gotMap[want] {
			t.Errorf("target missing email %q (got %v)", want, got)
		}
	}

	// 3. Store-tamper leg — corrupt the root manifest's detached signature
	// MAC (a signature-specific tamper that the SchemaHash recompute gate
	// does not catch) and confirm a fresh restore REFUSES with
	// SIGNATURE-INVALID: the signature caught exactly the tamper it exists
	// to catch.
	corruptManifestSigMAC(t, store, lineage.ManifestSigPath(lineage.ManifestFileName))
	_, targetDSN2, cleanup2 := startPostgres(t)
	defer cleanup2()
	err = (&backup.Restore{
		Target:    pgEng,
		TargetDSN: targetDSN2,
		Store:     store,
		Envelope:  newLocalstackKMSEnvelope(t, endpoint, encKeyARN),
		VerifyKey: verifyPub,
	}).Run(context.Background())
	if err == nil {
		t.Fatal("tampered signed manifest restored without refusal")
	}
	if ce, ok := sluicecode.FromError(err); !ok || ce.Code != sluicecode.CodeBackupSignatureInvalid {
		t.Fatalf("store-tamper: got %v, want SLUICE-E-BACKUP-SIGNATURE-INVALID", err)
	}
}

// corruptManifestSigMAC flips a byte of the detached signature's MAC in
// place — a signature-specific tamper (the manifest itself is untouched, so
// the ADR-0152 SchemaHash recompute passes and the SIGNATURE gate is what
// refuses).
func corruptManifestSigMAC(t *testing.T, store irbackup.Store, sigPath string) {
	t.Helper()
	ctx := context.Background()
	rc, err := store.Get(ctx, sigPath)
	if err != nil {
		t.Fatalf("get sig %q: %v", sigPath, err)
	}
	body, err := io.ReadAll(rc)
	_ = rc.Close()
	if err != nil {
		t.Fatalf("read sig: %v", err)
	}
	sig, err := irbackup.UnmarshalManifestSignature(body)
	if err != nil {
		t.Fatalf("decode sig: %v", err)
	}
	// Flip the last hex nibble of the MAC.
	b := []byte(sig.MAC)
	if b[len(b)-1] == '0' {
		b[len(b)-1] = '1'
	} else {
		b[len(b)-1] = '0'
	}
	sig.MAC = string(b)
	nb, err := irbackup.MarshalManifestSignature(sig)
	if err != nil {
		t.Fatalf("marshal sig: %v", err)
	}
	if err := store.Put(ctx, sigPath, bytes.NewReader(nb)); err != nil {
		t.Fatalf("put sig: %v", err)
	}
}
