//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

package pipeline

import (
	"context"
	"fmt"
	"testing"
	"time"

	irbackup "sluicesync.dev/sluice/internal/ir/backup"

	"sluicesync.dev/sluice/internal/engines"
	"sluicesync.dev/sluice/internal/ir"
	"sluicesync.dev/sluice/internal/pipeline/backup"
	"sluicesync.dev/sluice/internal/pipeline/blobcodec"
	"sluicesync.dev/sluice/internal/pipeline/lineage"

	_ "sluicesync.dev/sluice/internal/engines/postgres"
)

// TestIncremental_VerbatimColumnInScope pins Bug 251 (found by the
// v0.126.0 regression cycle — the other half of the Bug 110 class): a
// verbatim-family column (here TSVECTOR) INSIDE the chain's scope. The
// full's schema read enables ADR-0047 verbatim capture for a PG source,
// so the chain's full succeeds — and then every `backup incremental`
// failed its own readSourceSchema with the PG reader's "unsupported
// data_type" refusal, because that read never enabled the passthrough.
// Bug 110's table-scoping fixed only the OUT-of-scope sibling (an
// unrelated verbatim table elsewhere in the source).
//
// The pin drives the REAL full→incremental flow: full over a
// tsvector-bearing table (the control — always worked), anchor it, one
// more committed row, then IncrementalBackup.Run, which must succeed
// and record the row. The mid-chain restore-side boundary is stated at
// the fix site: a delta-carried verbatim column is refused toward a
// non-PG target by CheckCrossEngineDeltaSupportable's VerbatimType arm.
func TestIncremental_VerbatimColumnInScope(t *testing.T) {
	sourceDSN, _, cleanup := startPostgresLogical(t)
	defer cleanup()

	applyDDL(t, sourceDSN, `
		CREATE TABLE docs (
			id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			body TEXT NOT NULL,
			tsv  TSVECTOR
		);
		ALTER TABLE docs REPLICA IDENTITY FULL;
		INSERT INTO docs (body, tsv) VALUES ('seed doc', to_tsvector('english', 'seed doc'));
	`)
	applyDDL(t, sourceDSN, `CREATE PUBLICATION sluice_pub FOR ALL TABLES`)
	slotLSN, err := createPGLogicalSlotReturningLSN(t, sourceDSN, "sluice_slot")
	if err != nil {
		t.Fatalf("create slot: %v", err)
	}
	t.Cleanup(func() { dropPGLogicalSlot(t, sourceDSN, "sluice_slot") })

	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Minute)
	defer cancel()
	eng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}
	store, err := blobcodec.NewLocalStore(t.TempDir())
	if err != nil {
		t.Fatalf("NewLocalStore: %v", err)
	}

	// Control: the FULL captures the verbatim column (always did).
	if err := (&backup.Backup{
		Source: eng, SourceDSN: sourceDSN, Store: store, SluiceVersion: "test",
	}).Run(ctx); err != nil {
		t.Fatalf("full over the tsvector-bearing table failed — the CONTROL is broken, nothing below measures Bug 251: %v", err)
	}
	full, err := lineage.ReadManifest(ctx, store)
	if err != nil {
		t.Fatalf("read full: %v", err)
	}
	full.Kind = irbackup.BackupKindFull
	full.EndPosition = ir.Position{
		Engine: "postgres",
		Token:  fmt.Sprintf(`{"slot":"sluice_slot","lsn":%q}`, slotLSN),
	}
	full.BackupID = irbackup.ComputeBackupID(full)
	if err := lineage.WriteManifestAt(ctx, store, lineage.ManifestFileName, full); err != nil {
		t.Fatalf("rewrite full: %v", err)
	}
	_ = lineage.UpdateLineageForManifestBestEffort(ctx, store, full, lineage.ManifestFileName, blobcodec.DefaultCodec)

	applyDDL(t, sourceDSN,
		`INSERT INTO docs (body, tsv) VALUES ('post-full doc', to_tsvector('english', 'post-full doc'))`)

	// The measured defect: this Run failed at "read source schema"
	// with the unsupported-data_type refusal on the tsv column.
	incr := &IncrementalBackup{
		Source:        eng,
		SourceDSN:     sourceDSN,
		Store:         store,
		Window:        12 * time.Second,
		MaxChanges:    50,
		ChunkChanges:  10,
		SluiceVersion: "test",
	}
	if err := incr.Run(ctx); err != nil {
		t.Fatalf("backup incremental on a chain whose SCOPE carries a tsvector column failed — the Bug 251 shape (the full captured it, the incremental's schema read refuses it): %v", err)
	}
}
