//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// Audit N-14 end-to-end DR pins: `backup verify --rebuild-catalog` on a
// chain whose lineage.json was LOST must record the codec the chunks
// were actually written with, so the subsequent restore succeeds.
// Pre-fix, the rebuild stamped blobcodec.DefaultCodec (zstd)
// unconditionally, and a gzip- or none-compressed chain then failed its
// restore with a bare zstd decode error whose remediation hint pointed
// back at the very rebuild tool that wrote the wrong record — a
// wrong-heal on the DR path.
//
// Family discipline (Bug 74): the sniff dispatches on the codec family,
// so the plaintext scenario runs for ALL THREE codecs (none / gzip /
// zstd — zstd included so the previously-working default keeps
// working), and the encrypted leg pins the layout-dictated posture:
// the codec sits INSIDE the encryption envelope, so a keyless rebuild
// REFUSES (never guesses) and a keyed rebuild decrypt-sniffs.

package pipeline

import (
	"context"
	"errors"
	"testing"

	"sluicesync.dev/sluice/internal/crypto"
	"sluicesync.dev/sluice/internal/engines"
	irbackup "sluicesync.dev/sluice/internal/ir/backup"
	"sluicesync.dev/sluice/internal/pipeline/backup"
	"sluicesync.dev/sluice/internal/pipeline/blobcodec"
	"sluicesync.dev/sluice/internal/pipeline/lineage"

	_ "sluicesync.dev/sluice/internal/engines/postgres"
)

// rebuildCatalogSeedDDL is the shared source fixture. Emails double as
// the restore-side row assertion (pgQueryEmails).
const rebuildCatalogSeedDDL = `
	CREATE TABLE users (
		id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		email VARCHAR(255) NOT NULL
	);
	INSERT INTO users (email) VALUES
		('alice@example.com'),
		('bob@example.com'),
		('carol@example.com');
`

// assertRebuildRestoreRows asserts the restored target holds the seeded
// rows.
func assertRebuildRestoreRows(t *testing.T, targetDSN string) {
	t.Helper()
	got := pgQueryEmails(t, targetDSN)
	gotSet := map[string]bool{}
	for _, e := range got {
		gotSet[e] = true
	}
	for _, want := range []string{"alice@example.com", "bob@example.com", "carol@example.com"} {
		if !gotSet[want] {
			t.Errorf("target missing email %q after restore (got %v)", want, got)
		}
	}
}

// assertRecordedCodec loads the rebuilt lineage.json and asserts the
// single segment records want.
func assertRecordedCodec(t *testing.T, store irbackup.Store, want blobcodec.Codec) {
	t.Helper()
	cat, ok, err := lineage.LoadLineageCatalog(context.Background(), store)
	if err != nil || !ok {
		t.Fatalf("LoadLineageCatalog after rebuild: (%v, %v)", ok, err)
	}
	if len(cat.Segments) != 1 {
		t.Fatalf("rebuilt lineage has %d segments; want 1", len(cat.Segments))
	}
	if got := cat.Segments[0].Codec; got != want {
		t.Fatalf("rebuilt segment codec = %q; want the sniffed %q (N-14)", got, want)
	}
}

// TestBackupRebuildCatalog_LostLineage_EveryCodec_RestoreSucceeds is
// the N-14 DR scenario end-to-end, per codec family: backup with
// --compression <codec> → DELETE lineage.json → --rebuild-catalog →
// RESTORE. Pre-fix, the gzip and none legs died in the restore with a
// zstd decode error (the rebuilt catalog lied); the zstd leg pins that
// the previously-working default still works.
func TestBackupRebuildCatalog_LostLineage_EveryCodec_RestoreSucceeds(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()
	applyDDL(t, sourceDSN, rebuildCatalogSeedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}
	ctx := context.Background()

	for _, codec := range []blobcodec.Codec{blobcodec.CodecNone, blobcodec.CodecGzip, blobcodec.CodecZstd} {
		t.Run(string(codec), func(t *testing.T) {
			store, err := blobcodec.NewLocalStore(t.TempDir())
			if err != nil {
				t.Fatalf("NewLocalStore: %v", err)
			}
			if err := (&backup.Backup{
				Source:        pgEng,
				SourceDSN:     sourceDSN,
				Store:         store,
				SluiceVersion: "test",
				Codec:         codec,
			}).Run(ctx); err != nil {
				t.Fatalf("Backup.Run(%s): %v", codec, err)
			}

			// The DR event: lineage.json (the codec record) is lost.
			if ok, err := store.Exists(ctx, lineage.LineageCatalogFileName); err != nil || !ok {
				t.Fatalf("lineage.json missing after backup (exists=%v err=%v)", ok, err)
			}
			if err := store.Delete(ctx, lineage.LineageCatalogFileName); err != nil {
				t.Fatalf("delete lineage.json: %v", err)
			}

			// The heal: rebuild must sniff + record the TRUE codec.
			segs, mans, err := lineage.RebuildLineageCatalogAt(ctx, store, nil)
			if err != nil {
				t.Fatalf("RebuildLineageCatalogAt: %v", err)
			}
			if segs != 1 || mans != 1 {
				t.Fatalf("rebuild = (%d segments, %d manifests); want (1, 1)", segs, mans)
			}
			assertRecordedCodec(t, store, codec)

			// The proof: restore off the rebuilt catalog succeeds
			// (pre-fix: zstd decode error on the gzip/none legs).
			applyDDL(t, targetDSN, `DROP TABLE IF EXISTS users;`)
			if err := (&backup.Restore{
				Target:    pgEng,
				TargetDSN: targetDSN,
				Store:     store,
			}).Run(ctx); err != nil {
				t.Fatalf("Restore.Run after rebuild (%s): %v", codec, err)
			}
			assertRebuildRestoreRows(t, targetDSN)
		})
	}
}

// TestBackupRebuildCatalog_LostLineage_EncryptedChain pins the
// encrypted posture the chunk layout dictates (codec INSIDE the
// encryption envelope): a keyless rebuild over an encrypted gzip chain
// REFUSES loudly — steering the operator to --encrypt — and a keyed
// rebuild decrypt-sniffs, records gzip, and the encrypted restore then
// succeeds end-to-end.
func TestBackupRebuildCatalog_LostLineage_EncryptedChain(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()
	applyDDL(t, sourceDSN, rebuildCatalogSeedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}
	ctx := context.Background()
	store, err := blobcodec.NewLocalStore(t.TempDir())
	if err != nil {
		t.Fatalf("NewLocalStore: %v", err)
	}

	const passphrase = "rebuild-catalog-dr-passphrase"
	if err := (&backup.Backup{
		Source:        pgEng,
		SourceDSN:     sourceDSN,
		Store:         store,
		SluiceVersion: "test",
		Codec:         blobcodec.CodecGzip,
		Encryption: &lineage.BackupEncryption{
			Envelope: newTestPassphraseEnvelope(t, passphrase),
			Mode:     crypto.EncryptModePerChain,
		},
	}).Run(ctx); err != nil {
		t.Fatalf("Backup.Run(encrypted gzip): %v", err)
	}
	if err := store.Delete(ctx, lineage.LineageCatalogFileName); err != nil {
		t.Fatalf("delete lineage.json: %v", err)
	}

	// Keyless rebuild: the codec is sealed inside the encryption
	// envelope — refusal, never a recorded guess.
	_, _, err = lineage.RebuildLineageCatalogAt(ctx, store, nil)
	if err == nil {
		t.Fatal("RebuildLineageCatalogAt(encrypted, nil env): nil error; want a loud refusal")
	}
	if !errors.Is(err, lineage.ErrCodecSniffEncrypted) {
		t.Fatalf("keyless-rebuild error should wrap ErrCodecSniffEncrypted; got: %v", err)
	}
	if ok, _ := store.Exists(ctx, lineage.LineageCatalogFileName); ok {
		t.Fatal("refused rebuild must not write lineage.json")
	}

	// Keyed rebuild: decrypt one chunk, sniff, record the truth.
	env := envelopeFromManifest(t, store, passphrase)
	if _, _, err := lineage.RebuildLineageCatalogAt(ctx, store, env); err != nil {
		t.Fatalf("RebuildLineageCatalogAt(encrypted, env): %v", err)
	}
	assertRecordedCodec(t, store, blobcodec.CodecGzip)

	applyDDL(t, targetDSN, `DROP TABLE IF EXISTS users;`)
	if err := (&backup.Restore{
		Target:    pgEng,
		TargetDSN: targetDSN,
		Store:     store,
		Envelope:  envelopeFromManifest(t, store, passphrase),
	}).Run(ctx); err != nil {
		t.Fatalf("Restore.Run after keyed rebuild: %v", err)
	}
	assertRebuildRestoreRows(t, targetDSN)
}
