//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// Integration pin for audit M2.5: the `sync from-backup` broker cold-start
// --reset-target-data path under a SIGNED backup chain. The unsigned reset
// e2e is TestSyncFromBackup_ColdStartWithReset; this is its signed sibling —
// the security-relevant leg the audit tracked OPEN (6 consecutive carries).
//
// BRK-2 (audit 2026-07-10) wired b.VerifyKey / b.RequireSignature into the
// cold-start ChainRestore (broker.go newColdStartChainRestore); nothing until
// now exercised that wiring end-to-end against a real Ed25519-signed chain.
// This proves it holds:
//
//   - a clean signed chain restores under --require-signature, and the broker
//     then transitions to live polling — whose verifyChainIntegrity re-verifies
//     the signed chain every tick — without refusing the valid signatures;
//   - a WRONG verify key is refused loudly (SIGNATURE-INVALID) on the reset
//     leg, with no data landing on the target;
//   - a TAMPERED tail-segment signature is refused loudly on the reset leg.
//
// The refusal cases are the whole point of the signed path: the broker
// cold-start reset must never silently restore an unverifiable chain (the
// sibling of the offline ChainRestore/Restore tamper pins).

package pipeline

import (
	"context"
	"encoding/json"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/crypto"
	"sluicesync.dev/sluice/internal/engines"
	irbackup "sluicesync.dev/sluice/internal/ir/backup"
	"sluicesync.dev/sluice/internal/pipeline/backup"
	"sluicesync.dev/sluice/internal/pipeline/blobcodec"
	"sluicesync.dev/sluice/internal/pipeline/lineage"
	"sluicesync.dev/sluice/internal/sluicecode"

	_ "sluicesync.dev/sluice/internal/engines/postgres"
)

// TestSyncFromBackup_ColdStartWithReset_SignedChain is the signed sibling of
// TestSyncFromBackup_ColdStartWithReset (Acceptance Criterion 7) and the
// security-relevant M2.5 pin.
//
// It builds a real Ed25519-signed chain (full + one incremental) via the
// --chain-slot provisioning path — so the manifests keep their as-produced,
// validly-signed content, no post-hoc EndPosition rewrite that would break the
// signatures — and drives the broker's cold-start --reset-target-data leg
// three ways. The three subtests share one signed chain and one broker target;
// the two refusal cases run FIRST (a refused cold start lands no data + writes
// no sluice_cdc_state row, so the target stays cold-start-eligible) and the
// clean restore runs LAST (it populates the target).
func TestSyncFromBackup_ColdStartWithReset_SignedChain(t *testing.T) {
	sourceDSN, brokerTargetDSN, cleanup := startPostgresLogical(t)
	defer cleanup()

	applyDDL(t, sourceDSN, `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL
		);
		ALTER TABLE users REPLICA IDENTITY FULL;
		INSERT INTO users (email) VALUES ('alice@example.com'), ('bob@example.com');
	`)

	pgEng, _ := engines.Get("postgres")
	pub, priv, err := crypto.GenerateEd25519Keypair()
	if err != nil {
		t.Fatal(err)
	}
	otherPub, _, _ := crypto.GenerateEd25519Keypair()

	// Signed full backup with --chain-slot provisioning: records a correct
	// EndPosition by construction and writes the manifest's .sig, so nothing
	// downstream has to rewrite (and thereby invalidate) the signed manifest.
	store, err := blobcodec.NewLocalStore(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	if err := (&backup.Backup{
		Source: pgEng, SourceDSN: sourceDSN, Store: store,
		SluiceVersion: "test", ChainSlot: true,
		Ed25519Signer: lineage.NewEd25519Signer(priv),
	}).Run(context.Background()); err != nil {
		t.Fatalf("signed full backup: %v", err)
	}
	defer dropPGLogicalSlot(t, sourceDSN, "sluice_slot")

	// Drive a change + take a signed incremental so the chain is full + ≥1
	// incremental — the reset leg must verify EVERY segment, not just the full.
	applyDDL(t, sourceDSN, `INSERT INTO users (email) VALUES ('carol@example.com')`)
	incrCtx, incrCancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer incrCancel()
	if err := (&IncrementalBackup{
		Source: pgEng, SourceDSN: sourceDSN, Store: store,
		Window: 10 * time.Second, MaxChanges: 5, ChunkChanges: 5,
		SluiceVersion: "test",
		Ed25519Signer: lineage.NewEd25519Signer(priv),
	}).Run(incrCtx); err != nil {
		t.Fatalf("signed incremental backup: %v", err)
	}

	// Sanity: the chain is actually detected as signed (else the refusal
	// pins below would be vacuous — a wrong key against an unsigned chain
	// refuses for a different reason).
	if signed, _ := lineage.ChainIsSigned(context.Background(), store); !signed {
		t.Fatal("test premise broken: chain is not detected as signed")
	}

	// runColdStartReset drives one broker cold-start --reset-target-data run
	// to completion (returns the terminal error, or nil on a clean restore that
	// then blocks in live polling until ctx expires — callers of the clean case
	// use the goroutine form below instead).
	runColdStartReset := func(verifyKey any, requireSig bool) error {
		broker := &SyncFromBackup{
			Target: pgEng, TargetDSN: brokerTargetDSN, Store: store,
			ChainURL: "test://m25-signed", StreamID: "m25-signed",
			PollInterval:     2 * time.Second,
			ResetTargetData:  true,
			VerifyKey:        verifyKey,
			RequireSignature: requireSig,
			SluiceVersion:    "test",
		}
		ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
		defer cancel()
		return broker.Run(ctx)
	}

	// (c) WRONG verify key → refused loudly on the reset leg, no data lands.
	t.Run("wrong verify key refused on cold-start reset", func(t *testing.T) {
		err := runColdStartReset(otherPub, true)
		assertCoded(t, err, sluicecode.CodeBackupSignatureInvalid)
		if n := pgUsersTableCount(t, brokerTargetDSN); n != 0 {
			t.Fatalf("wrong-key refusal still created/populated the target table (%d rows/tables)", n)
		}
	})

	// (c) TAMPERED tail-segment signature → refused loudly on the reset leg.
	t.Run("tampered incremental signature refused on cold-start reset", func(t *testing.T) {
		cat, _, err := lineage.LoadLineageCatalog(context.Background(), store)
		if err != nil || cat == nil || len(cat.Segments) == 0 || len(cat.Segments[0].Incrementals) == 0 {
			t.Fatalf("lineage catalog missing incremental: cat=%v err=%v", cat, err)
		}
		incrSigPath := lineage.ManifestSigPath(cat.Segments[0].Incrementals[0])
		origSig := storeBytes(t, store, incrSigPath)
		var sig irbackup.ManifestSignature
		if err := json.Unmarshal(origSig, &sig); err != nil {
			t.Fatalf("unmarshal incr sig: %v", err)
		}
		sig.MAC = flipHex(sig.MAC)
		nb, _ := json.Marshal(&sig)
		storePut(t, store, incrSigPath, nb)
		defer storePut(t, store, incrSigPath, origSig) // restore pristine for the clean subtest

		err = runColdStartReset(pub, true)
		assertCoded(t, err, sluicecode.CodeBackupSignatureInvalid)
		if n := pgUsersTableCount(t, brokerTargetDSN); n != 0 {
			t.Fatalf("tamper refusal still created/populated the target table (%d rows/tables)", n)
		}
	})

	// (a)+(b) CLEAN signed chain → restores under --require-signature, then
	// the broker transitions to live polling (whose per-tick
	// verifyChainIntegrity also re-verifies the signed chain). Runs LAST since
	// it populates the target.
	t.Run("clean signed chain restores under required verification", func(t *testing.T) {
		broker := &SyncFromBackup{
			Target: pgEng, TargetDSN: brokerTargetDSN, Store: store,
			ChainURL: "test://m25-signed", StreamID: "m25-signed",
			PollInterval:     2 * time.Second,
			ResetTargetData:  true,
			VerifyKey:        pub,
			RequireSignature: true,
			SluiceVersion:    "test",
		}
		runCtx, runCancel := context.WithCancel(context.Background())
		defer runCancel()
		errCh := make(chan error, 1)
		go func() { errCh <- broker.Run(runCtx) }()

		// Wait for all 3 rows (alice, bob, carol) to land via the inline
		// ChainRestore. pgQueryEmailsTolerant returns empty until the reset
		// path has recreated the table.
		deadline := time.Now().Add(60 * time.Second)
		for time.Now().Before(deadline) {
			if len(pgQueryEmailsTolerant(t, brokerTargetDSN)) >= 3 {
				break
			}
			select {
			case err := <-errCh:
				t.Fatalf("broker exited before restoring the signed chain: %v", err)
			default:
			}
			time.Sleep(500 * time.Millisecond)
		}
		got := pgQueryEmailsTolerant(t, brokerTargetDSN)
		if len(got) < 3 {
			t.Fatalf("after signed --reset-target-data, target emails = %v; want 3 (alice, bob, carol)", got)
		}

		// The broker is now live-polling the signed chain under
		// --require-signature; cancel and confirm a clean exit (no
		// verifyChainIntegrity refusal of the valid signatures).
		runCancel()
		select {
		case err := <-errCh:
			if err != nil && !isContextCanceled(err) {
				t.Fatalf("broker returned non-cancel error while live-polling the signed chain: %v", err)
			}
		case <-time.After(10 * time.Second):
			t.Fatal("broker did not exit within 10s of cancel")
		}
	})
}
