//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// Acceptance Criterion 9: 1 source-side stream + N brokers reading
// the same chain. The fan-out value-prop of Phase 4.5 — one source
// slot, N independent target replays. The test asserts both targets
// converge on the same data without doubling source-side slot
// pressure.

package pipeline

import (
	"context"
	"database/sql"
	"fmt"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/engines"

	_ "sluicesync.dev/sluice/internal/engines/postgres"
)

// TestSyncFromBackup_FanOut starts one stream + two brokers reading
// the same chain, drives source writes, observes both target
// databases catch up. The two brokers run in the same Go process
// using DIFFERENT BackupStore POINTERS (NewLocalStore'd separately
// against the same root) so the registry's pointer-identity keying
// gives them distinct in-process stop channels.
//
// In production, two separate processes consuming the same chain is
// the typical shape. The same-process variant here is sufficient to
// validate the chain-as-broadcast-log design — two separate brokers
// driving two separate target connections.
func TestSyncFromBackup_FanOut(t *testing.T) {
	const seedDDL = `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL
		);
		ALTER TABLE users REPLICA IDENTITY FULL;
		INSERT INTO users (email) VALUES ('alice@example.com');
	`
	sourceDSN, brokerTarget1DSN, store, fullBackupID, teardown := brokerTestStreamSetup(t, seedDDL)
	defer teardown()

	// Boot a second broker target on its own container.
	_, brokerTarget2DSN, ctn3Teardown := startPostgresLogical(t)
	defer ctn3Teardown()

	pgEng, _ := engines.Get("postgres")

	// Pre-restore the full into BOTH broker targets.
	if err := (&Restore{
		Target: pgEng, TargetDSN: brokerTarget1DSN, Store: store,
	}).Run(context.Background()); err != nil {
		t.Fatalf("seed restore (target 1): %v", err)
	}
	// Restore into target 2 via a second store pointer so the
	// pre-restore against the same root reuses the chain.
	store2, err := NewLocalStore(store.Root())
	if err != nil {
		t.Fatalf("NewLocalStore (store2): %v", err)
	}
	if err := (&Restore{
		Target: pgEng, TargetDSN: brokerTarget2DSN, Store: store2,
	}).Run(context.Background()); err != nil {
		t.Fatalf("seed restore (target 2): %v", err)
	}

	// Start the source-side stream (1 slot on source).
	streamCancel, streamDone := runStreamInGoroutine(t, sourceDSN, fullBackupID, store)
	defer streamCancel()

	// Drive 10 inserts.
	for i := 0; i < 10; i++ {
		applyDDL(t, sourceDSN, fmt.Sprintf(
			`INSERT INTO users (email) VALUES ('fanout-%d@example.com');`, i,
		))
	}
	waitForIncrementals(t, store, 1, 30*time.Second)

	// Two brokers — one per target. Use distinct streamIDs so each
	// broker's row in `sluice_cdc_state` is independent (the rows live
	// on the respective TARGET databases anyway, so even same streamID
	// would be OK; using distinct names matches the recommended
	// operator pattern).
	// Distinct broker-state paths per broker. The two brokers run in
	// the same Go process against the same chain root; without this,
	// they race on the shared `manifests/broker_state.json` write.
	// See `brokerOpts.StatePath` for the full attribution; the Phase A
	// diagnose narrowed the flake to writeBrokerState under concurrent
	// same-path Put. Production is unaffected — one broker process per
	// chain — so the fix lives in the test surface.
	broker1Cancel, broker1Done := runBrokerInGoroutine(t, brokerTarget1DSN, "fanout-1", store, brokerOpts{
		PollInterval: 2 * time.Second,
		AtChainID:    fullBackupID,
		StatePath:    "manifests/broker_state-fanout-1.json",
	})
	defer broker1Cancel()

	broker2Cancel, broker2Done := runBrokerInGoroutine(t, brokerTarget2DSN, "fanout-2", store2, brokerOpts{
		PollInterval: 2 * time.Second,
		AtChainID:    fullBackupID,
		StatePath:    "manifests/broker_state-fanout-2.json",
	})
	defer broker2Cancel()

	// Wait for both targets to converge on 11 emails (alice + 10).
	deadline := time.Now().Add(90 * time.Second)
	for time.Now().Before(deadline) {
		c1 := pgQueryEmails(t, brokerTarget1DSN)
		c2 := pgQueryEmails(t, brokerTarget2DSN)
		if len(c1) >= 11 && len(c2) >= 11 {
			break
		}
		time.Sleep(500 * time.Millisecond)
	}
	c1 := pgQueryEmails(t, brokerTarget1DSN)
	c2 := pgQueryEmails(t, brokerTarget2DSN)
	if len(c1) < 11 {
		t.Errorf("broker target 1 not caught up: emails = %d; want >= 11", len(c1))
	}
	if len(c2) < 11 {
		t.Errorf("broker target 2 not caught up: emails = %d; want >= 11", len(c2))
	}

	// Source has exactly 1 slot (the stream's). Verify via
	// pg_replication_slots — this is the load-bearing fan-out
	// invariant.
	slots := pgCountSluiceSlots(t, sourceDSN)
	if slots != 1 {
		t.Errorf("source has %d sluice slots; want 1 (the stream's)", slots)
	}

	streamCancel()
	<-streamDone
	broker1Cancel()
	<-broker1Done
	broker2Cancel()
	<-broker2Done
}

// pgCountSluiceSlots counts active sluice_-prefixed replication
// slots on the named source. The fan-out test uses this to assert
// the slot-count invariant: 1 slot regardless of broker count.
func pgCountSluiceSlots(t *testing.T, dsn string) int {
	t.Helper()
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer func() { _ = db.Close() }()
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	row := db.QueryRowContext(ctx,
		`SELECT COUNT(*) FROM pg_replication_slots WHERE slot_name LIKE 'sluice\_%' ESCAPE '\'`)
	var n int
	if err := row.Scan(&n); err != nil {
		t.Fatalf("count slots: %v", err)
	}
	return n
}
