//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// Phase 5 integration tests: cross-engine chain restore.
//
// PG-rooted chain → MySQL target and the reverse direction.
// Acceptance criteria 1-4 from design-logical-backups-phase-5.md:
//
//   1. PG-rooted chain → MySQL target restore (full + 2 incrementals).
//   2. MySQL-rooted chain → PG target restore (mix of INSERT/UPDATE/DELETE).
//   3. Cross-engine schema evolution mid-stream (broker-driven).
//   4. Loud refusal for unsupportable types (PostGIS).
//
// Each test boots the minimum container set needed and bounds itself to
// 60s. Acceptance criterion 6 (same-engine paths regression-clean) is
// covered by the existing same-engine chain-restore integration tests
// running unchanged.

package pipeline

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"testing"
	"time"

	"github.com/orware/sluice/internal/engines"
	"github.com/orware/sluice/internal/ir"

	_ "github.com/orware/sluice/internal/engines/mysql"
	_ "github.com/orware/sluice/internal/engines/postgres"
)

// TestChainRestore_PostgresToMySQL_CrossEngine drives a PG-rooted
// chain (full + 2 incrementals) into a MySQL target and asserts every
// row landed with values translated correctly. Phase 5 acceptance
// criterion 1.
func TestChainRestore_PostgresToMySQL_CrossEngine(t *testing.T) {
	pgSourceDSN, _, pgCleanup := startPostgresLogical(t)
	defer pgCleanup()

	_, mysqlTargetDSN, mysqlCleanup := startMySQL(t)
	defer mysqlCleanup()

	const seedDDL = `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL,
			active BOOLEAN NOT NULL DEFAULT true
		);
		ALTER TABLE users REPLICA IDENTITY FULL;
		INSERT INTO users (email, active) VALUES ('alice@example.com', true);
	`
	applyDDL(t, pgSourceDSN, seedDDL)

	pgEng, _ := engines.Get("postgres")
	mysqlEng, _ := engines.Get("mysql")

	dir := t.TempDir()
	store, err := NewLocalStore(dir)
	if err != nil {
		t.Fatalf("NewLocalStore: %v", err)
	}

	applyDDL(t, pgSourceDSN, `CREATE PUBLICATION sluice_pub FOR ALL TABLES`)
	slotLSN, err := createPGLogicalSlotReturningLSN(t, pgSourceDSN, "sluice_slot")
	if err != nil {
		t.Fatalf("create slot: %v", err)
	}
	defer dropPGLogicalSlot(t, pgSourceDSN, "sluice_slot")

	// 1. Full backup.
	if err := (&Backup{
		Source: pgEng, SourceDSN: pgSourceDSN, Store: store, SluiceVersion: "test",
	}).Run(context.Background()); err != nil {
		t.Fatalf("Backup.Run: %v", err)
	}
	full, err := readManifest(context.Background(), store)
	if err != nil {
		t.Fatalf("readManifest: %v", err)
	}
	full.Kind = ir.BackupKindFull
	full.EndPosition = ir.Position{
		Engine: "postgres",
		Token:  fmt.Sprintf(`{"slot":"sluice_slot","lsn":%q}`, slotLSN),
	}
	full.BackupID = ir.ComputeBackupID(full)
	if err := writeManifestAt(context.Background(), store, ManifestFileName, full); err != nil {
		t.Fatalf("rewrite full: %v", err)
	}

	// 2. Incremental #1: INSERT bob + carol.
	applyDDL(t, pgSourceDSN, `INSERT INTO users (email, active) VALUES ('bob@example.com', false), ('carol@example.com', true);`)
	ctx1, c1 := context.WithTimeout(context.Background(), 60*time.Second)
	defer c1()
	if err := (&IncrementalBackup{
		Source: pgEng, SourceDSN: pgSourceDSN, Store: store,
		ParentRef:    full.BackupID,
		Window:       10 * time.Second,
		MaxChanges:   10,
		ChunkChanges: 100,
	}).Run(ctx1); err != nil {
		t.Fatalf("incr1 Run: %v", err)
	}

	// 3. Incremental #2: UPDATE alice.active = false.
	applyDDL(t, pgSourceDSN, `UPDATE users SET active = false WHERE email = 'alice@example.com';`)
	ctx2, c2 := context.WithTimeout(context.Background(), 60*time.Second)
	defer c2()
	if err := (&IncrementalBackup{
		Source: pgEng, SourceDSN: pgSourceDSN, Store: store,
		Window:       10 * time.Second,
		MaxChanges:   10,
		ChunkChanges: 100,
	}).Run(ctx2); err != nil {
		t.Fatalf("incr2 Run: %v", err)
	}

	// 4. Cross-engine chain restore into MySQL.
	if err := (&ChainRestore{
		Target: mysqlEng, TargetDSN: mysqlTargetDSN, Store: store,
	}).Run(context.Background()); err != nil {
		t.Fatalf("ChainRestore.Run (PG → MySQL): %v", err)
	}

	// 5. Verify rows arrived. MySQL target.
	got := mysqlQueryEmailsActive(t, mysqlTargetDSN)
	wantActive := map[string]bool{
		"alice@example.com": false, // post-update
		"bob@example.com":   false,
		"carol@example.com": true,
	}
	for email, wantA := range wantActive {
		gotA, ok := got[email]
		if !ok {
			t.Errorf("target missing email %q (got: %v)", email, got)
			continue
		}
		if gotA != wantA {
			t.Errorf("target %s.active = %v; want %v", email, gotA, wantA)
		}
	}
}

// TestChainRestore_MySQLToPostgres_CrossEngine drives a MySQL-rooted
// chain (full + 2 incrementals with INSERT/UPDATE/DELETE) into a PG
// target. Phase 5 acceptance criterion 2.
func TestChainRestore_MySQLToPostgres_CrossEngine(t *testing.T) {
	mysqlSourceDSN, _, mysqlCleanup := startMySQLBinlog(t)
	defer mysqlCleanup()

	_, pgTargetDSN, pgCleanup := startPostgres(t)
	defer pgCleanup()

	const seedDDL = `
		CREATE TABLE users (
			id     BIGINT       NOT NULL AUTO_INCREMENT,
			email  VARCHAR(255) NOT NULL,
			active TINYINT(1)   NOT NULL DEFAULT 1,
			PRIMARY KEY (id)
		) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
		INSERT INTO users (email, active) VALUES ('alice@example.com', 1);
	`
	applyDDLMySQL(t, mysqlSourceDSN, seedDDL)

	mysqlEng, _ := engines.Get("mysql")
	pgEng, _ := engines.Get("postgres")

	dir := t.TempDir()
	store, _ := NewLocalStore(dir)

	// 1. Full backup.
	if err := (&Backup{
		Source: mysqlEng, SourceDSN: mysqlSourceDSN, Store: store, SluiceVersion: "test",
	}).Run(context.Background()); err != nil {
		t.Fatalf("Backup.Run: %v", err)
	}
	binlogFile, binlogPos := readMySQLBinlogPos(t, mysqlSourceDSN)
	full, _ := readManifest(context.Background(), store)
	full.Kind = ir.BackupKindFull
	full.EndPosition = ir.Position{
		Engine: "mysql",
		Token:  fmt.Sprintf(`{"mode":"file_pos","file":%q,"pos":%d}`, binlogFile, binlogPos),
	}
	full.BackupID = ir.ComputeBackupID(full)
	if err := writeManifestAt(context.Background(), store, ManifestFileName, full); err != nil {
		t.Fatalf("rewrite full: %v", err)
	}

	// 2. Incremental #1: INSERT bob + UPDATE alice.active=0.
	applyDDLMySQL(t, mysqlSourceDSN, `
		INSERT INTO users (email, active) VALUES ('bob@example.com', 1);
		UPDATE users SET active = 0 WHERE email = 'alice@example.com';
	`)
	ctx1, c1 := context.WithTimeout(context.Background(), 60*time.Second)
	defer c1()
	if err := (&IncrementalBackup{
		Source: mysqlEng, SourceDSN: mysqlSourceDSN, Store: store,
		ParentRef:    full.BackupID,
		Window:       10 * time.Second,
		MaxChanges:   10,
		ChunkChanges: 100,
	}).Run(ctx1); err != nil {
		t.Fatalf("incr1 Run: %v", err)
	}

	// 3. Incremental #2: DELETE bob + INSERT carol.
	applyDDLMySQL(t, mysqlSourceDSN, `
		DELETE FROM users WHERE email = 'bob@example.com';
		INSERT INTO users (email, active) VALUES ('carol@example.com', 1);
	`)
	ctx2, c2 := context.WithTimeout(context.Background(), 60*time.Second)
	defer c2()
	if err := (&IncrementalBackup{
		Source: mysqlEng, SourceDSN: mysqlSourceDSN, Store: store,
		Window:       10 * time.Second,
		MaxChanges:   10,
		ChunkChanges: 100,
	}).Run(ctx2); err != nil {
		t.Fatalf("incr2 Run: %v", err)
	}

	// 4. Cross-engine chain restore into PG.
	if err := (&ChainRestore{
		Target: pgEng, TargetDSN: pgTargetDSN, Store: store,
	}).Run(context.Background()); err != nil {
		t.Fatalf("ChainRestore.Run (MySQL → PG): %v", err)
	}

	// 5. Verify final state on PG target. alice should have active=false
	//    (after the UPDATE), bob should be gone (after the DELETE), and
	//    carol should be present (after the INSERT).
	got := pgQueryUsersActive(t, pgTargetDSN)
	if _, ok := got["bob@example.com"]; ok {
		t.Errorf("target still has bob@example.com (DELETE didn't propagate); got = %v", got)
	}
	if a, ok := got["alice@example.com"]; !ok {
		t.Errorf("target missing alice@example.com")
	} else if a != false {
		t.Errorf("alice.active = %v; want false (TINYINT(1)=0 → BOOLEAN false)", a)
	}
	if _, ok := got["carol@example.com"]; !ok {
		t.Errorf("target missing carol@example.com")
	}
}

// TestSyncFromBackup_CrossEngine_SchemaEvolution drives Phase 5
// acceptance criterion 3: stream-write a chain on PG, ALTER TABLE on
// PG mid-stream, broker on MySQL target applies the translated delta
// and replays the post-ALTER rows.
func TestSyncFromBackup_CrossEngine_SchemaEvolution(t *testing.T) {
	pgSourceDSN, _, pgCleanup := startPostgresLogical(t)
	defer pgCleanup()
	_, mysqlTargetDSN, mysqlCleanup := startMySQL(t)
	defer mysqlCleanup()

	const seedDDL = `
		CREATE TABLE customers (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL
		);
		ALTER TABLE customers REPLICA IDENTITY FULL;
		INSERT INTO customers (email) VALUES ('alice@example.com');
	`
	applyDDL(t, pgSourceDSN, seedDDL)

	pgEng, _ := engines.Get("postgres")
	mysqlEng, _ := engines.Get("mysql")

	dir := t.TempDir()
	store, _ := NewLocalStore(dir)

	applyDDL(t, pgSourceDSN, `CREATE PUBLICATION sluice_pub FOR ALL TABLES`)
	slotLSN, err := createPGLogicalSlotReturningLSN(t, pgSourceDSN, "sluice_slot")
	if err != nil {
		t.Fatalf("create slot: %v", err)
	}
	defer dropPGLogicalSlot(t, pgSourceDSN, "sluice_slot")

	// 1. Full backup.
	if err := (&Backup{
		Source: pgEng, SourceDSN: pgSourceDSN, Store: store, SluiceVersion: "test",
	}).Run(context.Background()); err != nil {
		t.Fatalf("Backup.Run: %v", err)
	}
	full, _ := readManifest(context.Background(), store)
	full.Kind = ir.BackupKindFull
	full.EndPosition = ir.Position{
		Engine: "postgres",
		Token:  fmt.Sprintf(`{"slot":"sluice_slot","lsn":%q}`, slotLSN),
	}
	full.BackupID = ir.ComputeBackupID(full)
	if err := writeManifestAt(context.Background(), store, ManifestFileName, full); err != nil {
		t.Fatalf("rewrite full: %v", err)
	}

	// 2. Cross-engine restore the full into MySQL so the broker has
	//    the base shape; then run the broker against the chain. This
	//    is the warm-resume sub-shape: target carries the full's data,
	//    broker picks up incrementals from there.
	if err := (&Restore{
		Target: mysqlEng, TargetDSN: mysqlTargetDSN, Store: store,
	}).Run(context.Background()); err != nil {
		t.Fatalf("seed Restore (full only): %v", err)
	}

	// 3. ALTER on source mid-stream: ADD COLUMN tag VARCHAR(64).
	applyDDL(t, pgSourceDSN, `
		ALTER TABLE customers ADD COLUMN tag VARCHAR(64);
		INSERT INTO customers (email, tag) VALUES ('bob@example.com', 'gold');
	`)

	// 4. Capture the schema-evolved incremental. The IncrementalBackup
	//    pipeline records the SchemaDelta automatically.
	ctx1, c1 := context.WithTimeout(context.Background(), 60*time.Second)
	defer c1()
	if err := (&IncrementalBackup{
		Source: pgEng, SourceDSN: pgSourceDSN, Store: store,
		ParentRef:    full.BackupID,
		Window:       10 * time.Second,
		MaxChanges:   10,
		ChunkChanges: 100,
	}).Run(ctx1); err != nil {
		t.Fatalf("incr Run: %v", err)
	}

	// 5. Run the broker against the chain. --at-chain-id pins the
	//    broker's resume floor to the full's BackupID; the unapplied
	//    incremental gets replayed.
	brokerCtx, brokerCancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer brokerCancel()
	broker := &SyncFromBackup{
		Target:        mysqlEng,
		TargetDSN:     mysqlTargetDSN,
		Store:         store,
		ChainURL:      "test://chain",
		StreamID:      "test-cross-broker",
		PollInterval:  1 * time.Second,
		AtChainID:     full.BackupID,
		SluiceVersion: "test",
	}
	brokerDone := make(chan error, 1)
	go func() { brokerDone <- broker.Run(brokerCtx) }()

	// 6. Wait for the broker to apply the incremental: the new column
	//    `tag` must appear on the MySQL target with bob's row carrying
	//    'gold'.
	deadline := time.Now().Add(30 * time.Second)
	var bobTag string
	for time.Now().Before(deadline) {
		bobTag = mysqlQueryTagByEmail(t, mysqlTargetDSN, "bob@example.com")
		if bobTag == "gold" {
			break
		}
		time.Sleep(500 * time.Millisecond)
	}
	if bobTag != "gold" {
		t.Errorf("bob.tag on MySQL = %q; want %q (cross-engine ALTER + INSERT not propagated)", bobTag, "gold")
	}

	brokerCancel()
	select {
	case <-brokerDone:
	case <-time.After(15 * time.Second):
		t.Error("broker did not exit within 15s of cancel")
	}
}

// TestChainRestore_CrossEngine_PostGISNowSupported documents that
// the Phase 5 PostGIS-refusal placeholder is closed in v0.28.0 by
// ADR-0035 — PG → MySQL geometry round-trips with SRID preserved.
// The remaining cross-engine refusal target is ir.ExtensionType
// (ADR-0032 pgvector and friends), exercised at the unit-test layer
// in TestChainRestore_CrossEngineExtensionTypeRefuses. The end-to-end
// PG → MySQL geometry happy-path lives under the `postgis` build tag
// (migrate_postgis_integration_test.go).
func TestChainRestore_CrossEngine_PostGISNowSupported(t *testing.T) {
	t.Skip("PostGIS cross-engine geometry support landed in v0.28.0 (ADR-0035); refusal exercised by TestChainRestore_CrossEngineExtensionTypeRefuses now uses ir.ExtensionType. End-to-end happy path: migrate_postgis_integration_test.go (build tag postgis).")
}

// mysqlQueryEmailsActive returns email → active for every row in the
// users table on the MySQL target. active is decoded as bool from
// TINYINT(1).
func mysqlQueryEmailsActive(t *testing.T, dsn string) map[string]bool {
	t.Helper()
	db, err := sql.Open("mysql", dsn)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer func() { _ = db.Close() }()
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	rows, err := db.QueryContext(ctx, "SELECT email, active FROM users ORDER BY id")
	if err != nil {
		t.Fatalf("query: %v", err)
	}
	defer func() { _ = rows.Close() }()
	out := map[string]bool{}
	for rows.Next() {
		var email string
		var active int64 // TINYINT(1) decodes as int64
		if err := rows.Scan(&email, &active); err != nil {
			t.Fatalf("scan: %v", err)
		}
		out[email] = active != 0
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}
	return out
}

// pgQueryUsersActive returns email → active (bool) for every row on
// the PG target.
func pgQueryUsersActive(t *testing.T, dsn string) map[string]bool {
	t.Helper()
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer func() { _ = db.Close() }()
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	rows, err := db.QueryContext(ctx, "SELECT email, active FROM users ORDER BY id")
	if err != nil {
		t.Fatalf("query: %v", err)
	}
	defer func() { _ = rows.Close() }()
	out := map[string]bool{}
	for rows.Next() {
		var email string
		var active bool
		if err := rows.Scan(&email, &active); err != nil {
			t.Fatalf("scan: %v", err)
		}
		out[email] = active
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}
	return out
}

// mysqlQueryTagByEmail reads the tag column for the row with the
// supplied email, or "" if no such row or no tag column yet (the
// schema-evolution test polls until the column appears). Tolerant of
// missing-column SQL errors so the broker's catch-up window works.
func mysqlQueryTagByEmail(t *testing.T, dsn, email string) string {
	t.Helper()
	db, err := sql.Open("mysql", dsn)
	if err != nil {
		return ""
	}
	defer func() { _ = db.Close() }()
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	var tag sql.NullString
	row := db.QueryRowContext(ctx, "SELECT tag FROM customers WHERE email = ?", email)
	if err := row.Scan(&tag); err != nil {
		// Missing column or row returns "".
		if strings.Contains(err.Error(), "Unknown column") || strings.Contains(err.Error(), "no rows") {
			return ""
		}
		return ""
	}
	if !tag.Valid {
		return ""
	}
	return tag.String
}
