//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// Cross-engine integration test for the F10 / ADR-0062 cutover
// sequence priming flow: Postgres source → MySQL target. Exercises
// the cross-engine handoff where the source's sequence state (PG
// `last_value` from pg_sequences) gets canonicalised to last-issued
// and applied as `ALTER TABLE ... AUTO_INCREMENT = N` on the target.
//
// Pin shape: source has 5 rows, target is freshly migrated with no
// rows, run cutover → expect target AUTO_INCREMENT primed to
// source+margin+1 = 1006. Re-run → expect "noop" (idempotent
// re-invocation does NOT regress AUTO_INCREMENT).

package pipeline

import (
	"context"
	"database/sql"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/engines"
	"sluicesync.dev/sluice/internal/ir"

	// Both engines must be registered for the cutover orchestrator's
	// engines.Get lookups to find them.
	_ "sluicesync.dev/sluice/internal/engines/mysql"
	_ "sluicesync.dev/sluice/internal/engines/postgres"
)

// TestCutover_PostgresToMySQL_PrimesAcrossEngines exercises the
// cross-engine F10 flow: PG source last_value → MySQL target
// AUTO_INCREMENT.
func TestCutover_PostgresToMySQL_PrimesAcrossEngines(t *testing.T) {
	pgSource, _, pgCleanup := startPostgres(t)
	defer pgCleanup()
	_, mysqlTarget, mysqlCleanup := startMySQL(t)
	defer mysqlCleanup()

	// Source: PG with IDENTITY column and 5 rows.
	applyPGDDL(t, pgSource, `
		CREATE TABLE orders (
			id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name TEXT NOT NULL
		);
		INSERT INTO orders (name) VALUES ('a'),('b'),('c'),('d'),('e');
	`)
	// Target: MySQL with AUTO_INCREMENT column and no rows.
	applyMySQLDDL(t, mysqlTarget, `
		CREATE TABLE orders (
			id   BIGINT NOT NULL AUTO_INCREMENT,
			name VARCHAR(64) NOT NULL,
			PRIMARY KEY (id)
		) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
	`)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}
	mysqlEng, ok := engines.Get("mysql")
	if !ok {
		t.Fatal("mysql engine not registered")
	}

	cut := &Cutover{
		Source:    pgEng,
		Target:    mysqlEng,
		SourceDSN: pgSource,
		TargetDSN: mysqlTarget,
		Margin:    1000,
	}

	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()

	report, err := cut.Run(ctx)
	if err != nil {
		t.Fatalf("first cutover err = %v", err)
	}
	if len(report.Actions) != 1 {
		t.Fatalf("actions = %+v; want one", report.Actions)
	}
	if report.Actions[0].Outcome != "primed" {
		t.Errorf("outcome = %q; want %q (action = %+v)",
			report.Actions[0].Outcome, "primed", report.Actions[0])
	}

	// Verify by probing the target's next-issued ID matches
	// source + margin + 1 = 1006.
	verifyDB, err := sql.Open("mysql", mysqlTarget)
	if err != nil {
		t.Fatalf("open verify db: %v", err)
	}
	defer func() { _ = verifyDB.Close() }()

	if _, err := verifyDB.ExecContext(ctx, "INSERT INTO orders (name) VALUES ('probe')"); err != nil {
		t.Fatalf("probe insert: %v", err)
	}
	var probeID int64
	if err := verifyDB.QueryRowContext(ctx, "SELECT id FROM orders WHERE name = 'probe'").Scan(&probeID); err != nil {
		t.Fatalf("scan probe id: %v", err)
	}
	const wantProbeID = int64(1006) // source(5) + margin(1000) + 1
	if probeID != wantProbeID {
		t.Errorf("probe insert id = %d; want %d", probeID, wantProbeID)
	}

	// Idempotency. Second cutover (source still at 5, target now at
	// 1007 next-to-issue because probe consumed 1006). Expect "noop"
	// — operator-facing F10 contract: re-running cutover does NOT
	// regress.
	report2, err := cut.Run(ctx)
	if err != nil {
		t.Fatalf("second cutover err = %v", err)
	}
	if len(report2.Actions) != 1 {
		t.Fatalf("second cutover actions = %+v; want one", report2.Actions)
	}
	if report2.Actions[0].Outcome != "noop" {
		t.Errorf("second cutover outcome = %q; want %q (idempotency pin)",
			report2.Actions[0].Outcome, "noop")
	}
	// Quiet a no-op import warning if no other code paths exercise
	// the ir alias.
	_ = ir.CutoverSequenceMarginDefault
}
