//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// Task #72 (postgres-trigger Phase 2) — cross-engine cutover sequence
// priming for a postgres-trigger source → MySQL target.
//
// The F10 / ADR-0062 cutover flow primes the target's AUTO_INCREMENT from
// the source's sequence state. It asserts [ir.SequenceStateReader] on the
// source SchemaReader and [ir.SequencePrimer] on the target SchemaWriter
// (cutover.go ~lines 108-134). The postgres-trigger engine DELEGATES
// OpenSchemaReader to the composed vanilla postgres engine, whose
// SchemaReader implements SequenceStateReader (cutover_sequence.go). So
// postgres-trigger → MySQL sequence priming SHOULD work via delegation with
// NO forwarding code added. This test CONFIRMS that — if the
// SequenceStateReader assertion failed for the trigger source, the cutover
// would refuse with a clear error and this test would surface it (rather
// than the harness inventing a fix).
//
// Pin shape (mirrors cutover_cross_integration_test.go): PG source has an
// IDENTITY column with 5 rows; MySQL target is migrated with no rows; run
// cutover → expect target AUTO_INCREMENT primed to source+margin+1 = 1006;
// re-run → expect "noop" (idempotent re-invocation does NOT regress).

package pipeline

import (
	"context"
	"database/sql"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/engines"
	"sluicesync.dev/sluice/internal/engines/pgtrigger"
	"sluicesync.dev/sluice/internal/ir"

	// Side-effect imports register the engines looked up by engines.Get;
	// pgtrigger self-registers through the named import above.
	_ "sluicesync.dev/sluice/internal/engines/mysql"
	_ "sluicesync.dev/sluice/internal/engines/postgres"
)

// TestCutover_PGTriggerToMySQL_PrimesAcrossEngines exercises the
// cross-engine F10 flow with a postgres-trigger source: PG IDENTITY
// last_value → MySQL AUTO_INCREMENT, via the trigger engine's delegated
// SchemaReader (which is where the SequenceStateReader surface lives).
func TestCutover_PGTriggerToMySQL_PrimesAcrossEngines(t *testing.T) {
	// startPostgresPlain boots a plain (non-logical) PG — the slot-less
	// tier the trigger engine targets. Cutover only reads the schema +
	// sequence state, so no trigger Setup / CDC is needed here.
	pgSource, _, pgCleanup := startPostgresPlain(t)
	defer pgCleanup()
	_, mysqlTarget, mysqlCleanup := startMySQL(t)
	defer mysqlCleanup()

	// Source: PG with IDENTITY column and 5 rows.
	applyPGTrigDDL(t, pgSource, `
		CREATE TABLE orders (
			id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name TEXT NOT NULL
		);
		INSERT INTO orders (name) VALUES ('a'),('b'),('c'),('d'),('e');
	`)
	// Target: MySQL with AUTO_INCREMENT column and no rows.
	applyMySQLDDL(t, mysqlTarget, `
		CREATE TABLE orders (
			id   BIGINT NOT NULL AUTO_INCREMENT,
			name VARCHAR(64) NOT NULL,
			PRIMARY KEY (id)
		) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
	`)

	trigEng, ok := engines.Get(pgtrigger.EngineName)
	if !ok {
		t.Fatal("postgres-trigger engine not registered")
	}
	mysqlEng, ok := engines.Get("mysql")
	if !ok {
		t.Fatal("mysql engine not registered")
	}

	cut := &Cutover{
		Source:    trigEng,
		Target:    mysqlEng,
		SourceDSN: pgSource,
		TargetDSN: mysqlTarget,
		Margin:    1000,
	}

	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()

	report, err := cut.Run(ctx)
	if err != nil {
		// If sequence priming refuses for the pgtrigger source (the
		// SequenceStateReader assertion failing through delegation), the
		// error surfaces HERE — fail loudly with the exact message rather
		// than masking it. The expectation is that delegation makes this
		// succeed; a refusal is a finding for the main session.
		t.Fatalf("first cutover (postgres-trigger source) err = %v "+
			"(if this is a SequenceStateReader refusal, the trigger engine's "+
			"delegated SchemaReader did not expose the surface — report, do not fix blindly)", err)
	}
	if len(report.Actions) != 1 {
		t.Fatalf("actions = %+v; want one", report.Actions)
	}
	if report.Actions[0].Outcome != "primed" {
		t.Errorf("outcome = %q; want %q (action = %+v)",
			report.Actions[0].Outcome, "primed", report.Actions[0])
	}

	// Verify by probing the target's next-issued ID matches
	// source + margin + 1 = 1006.
	verifyDB, err := sql.Open("mysql", mysqlTarget)
	if err != nil {
		t.Fatalf("open verify db: %v", err)
	}
	defer func() { _ = verifyDB.Close() }()

	if _, err := verifyDB.ExecContext(ctx, "INSERT INTO orders (name) VALUES ('probe')"); err != nil {
		t.Fatalf("probe insert: %v", err)
	}
	var probeID int64
	if err := verifyDB.QueryRowContext(ctx, "SELECT id FROM orders WHERE name = 'probe'").Scan(&probeID); err != nil {
		t.Fatalf("scan probe id: %v", err)
	}
	const wantProbeID = int64(1006) // source(5) + margin(1000) + 1
	if probeID != wantProbeID {
		t.Errorf("probe insert id = %d; want %d", probeID, wantProbeID)
	}

	// Idempotency. Second cutover (source still at 5, target now at 1007
	// next-to-issue because the probe consumed 1006). Expect "noop" — the
	// operator-facing F10 contract: re-running cutover does NOT regress.
	report2, err := cut.Run(ctx)
	if err != nil {
		t.Fatalf("second cutover err = %v", err)
	}
	if len(report2.Actions) != 1 {
		t.Fatalf("second cutover actions = %+v; want one", report2.Actions)
	}
	if report2.Actions[0].Outcome != "noop" {
		t.Errorf("second cutover outcome = %q; want %q (idempotency pin)",
			report2.Actions[0].Outcome, "noop")
	}
	// Quiet a no-op import warning if no other code paths exercise the
	// ir alias in this file.
	_ = ir.CutoverSequenceMarginDefault
}
