// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

package pipeline

// dumpParityAllowlist is the single reviewable answer to "what does
// sluice knowingly not carry on a same-engine PG → PG migration?"
// (roadmap item 51, gotcha 6). Every entry cites the doc/ADR/source
// that declares the degradation — or carries the
// dumpParityTriageCitation marker for a latent gap the oracle found
// that has NOT been triaged into a documented decision yet. TRIAGE
// entries are loudly banner-logged by the harness on every run;
// they are debt, not policy.
//
// Patterns match statement KEYS (see dumpStatementKey) under
// path.Match glob semantics. First match wins — keep entries
// most-specific-first. Every hit is logged in the test output so the
// active list is visible in CI logs.
var dumpParityAllowlist = []dumpParityAllowlistEntry{
	{
		Pattern:  "*sluice_migrate_*",
		Reason:   "sluice's own per-target migrate-state tables (resume machinery); operational metadata, not migrated schema",
		Citation: "internal/pipeline/resume.go",
	},
	{
		Pattern:  "*public.events*",
		Reason:   "PG declarative partitioning is refused loudly (Bug 100); the harness excludes the partitioned parent + children via TableFilter, so the whole partition family exists only on the oracle side",
		Citation: "internal/pipeline/partition_preflight.go (Bug 100, v0.92.0)",
	},
	// item-51 finding #1 CLOSED: the standalone order_number_seq (and
	// orders.order_number's nextval default) now round-trips at FULL
	// parity — the three TRIAGE entries that covered the collapse are
	// gone. What remains on the orders body is the typed-literal
	// default rendering, a documented cosmetic policy.
	{
		Pattern:  "CREATE TABLE public.orders",
		Reason:   "integer defaults re-emit as quoted casts (DEFAULT '0'::bigint vs source DEFAULT 0) — evaluates identically on every insert, catalog-text different; operator-approved cosmetic divergence (2026-07-03)",
		Citation: "docs/type-mapping.md \"Typed-literal default rendering\"",
	},
	// The serial → identity modernization trio (docs/type-mapping.md
	// "Sequences and serial columns"): pg_dump restores a classic
	// serial column as CREATE SEQUENCE + OWNED BY + SET DEFAULT
	// nextval(...), while sluice deliberately emits an identity
	// column. Insert behaviour is identical; the catalog text is not.
	{
		Pattern:  "CREATE SEQUENCE public.legacy_counters_id_seq",
		Reason:   "oracle side only: the backing sequence pg_dump re-creates for the classic serial column sluice modernizes to identity",
		Citation: "docs/type-mapping.md \"Sequences and serial columns\"",
	},
	{
		Pattern:  "ALTER SEQUENCE public.legacy_counters_id_seq OWNED",
		Reason:   "oracle side only: the OWNED BY binding of the serial backing sequence (counterpart of the CREATE SEQUENCE legacy_counters_id_seq entry)",
		Citation: "docs/type-mapping.md \"Sequences and serial columns\"",
	},
	{
		Pattern:  "ALTER TABLE public.legacy_counters ALTER COLUMN id",
		Reason:   "the serial column's default: oracle side SET DEFAULT nextval('legacy_counters_id_seq'), sluice side ADD GENERATED BY DEFAULT AS IDENTITY — the modernization's catalog-visible face",
		Citation: "docs/type-mapping.md \"Sequences and serial columns\"",
	},
	// TRIAGE #3 (bare-timestamptz precision materialization: the
	// customers + shipments entries) and TRIAGE #4 (UNIQUE constraints
	// demoted to unique indexes: the *_unique entry pair) are CLOSED —
	// ir temporal PrecisionUnspecified + ir.Index.ConstraintBacked
	// carry both shapes at FULL parity. Zero TRIAGE entries remain.
}
