// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

package pipeline

// dumpParityAllowlist is the single reviewable answer to "what does
// sluice knowingly not carry on a same-engine PG → PG migration?"
// (roadmap item 51, gotcha 6). Every entry cites the doc/ADR/source
// that declares the degradation — or carries the
// dumpParityTriageCitation marker for a latent gap the oracle found
// that has NOT been triaged into a documented decision yet. TRIAGE
// entries are loudly banner-logged by the harness on every run;
// they are debt, not policy.
//
// Patterns match statement KEYS (see dumpStatementKey) under
// path.Match glob semantics. First match wins — keep entries
// most-specific-first. Every hit is logged in the test output so the
// active list is visible in CI logs.
var dumpParityAllowlist = []dumpParityAllowlistEntry{
	{
		Pattern:  "*sluice_migrate_*",
		Reason:   "sluice's own per-target migrate-state tables (resume machinery); operational metadata, not migrated schema",
		Citation: "internal/pipeline/resume.go",
	},
	{
		Pattern:  "*public.events*",
		Reason:   "PG declarative partitioning is refused loudly (Bug 100); the harness excludes the partitioned parent + children via TableFilter, so the whole partition family exists only on the oracle side",
		Citation: "internal/pipeline/partition_preflight.go (Bug 100, v0.92.0)",
	},
	{
		Pattern:  "CREATE SEQUENCE public.order_number_seq",
		Reason:   "standalone (non-identity) sequences are not carried: the reader classifies any nextval() default as AutoIncrement and the PG writer re-emits it as GENERATED BY DEFAULT AS IDENTITY, so the explicit sequence object never reaches the target",
		Citation: dumpParityTriageCitation,
	},
	{
		Pattern: "CREATE TABLE public.orders",
		Reason: "two deltas in this body (allowlist granularity is the key; both logged): " +
			"(1) orders.order_number DEFAULT nextval('order_number_seq') collapses to an identity column on the sluice side (same class as the CREATE SEQUENCE entry) — custom START/INCREMENT and the shared-sequence topology are lost; " +
			"(2) integer defaults re-emit as quoted casts (DEFAULT '0'::bigint vs source DEFAULT 0) — semantically identical, catalog-text different",
		Citation: dumpParityTriageCitation,
	},
	{
		Pattern:  "ALTER TABLE public.orders ALTER COLUMN order_number",
		Reason:   "sluice side only: the identity clause pg_dump emits for the collapsed order_number column (counterpart of the CREATE TABLE public.orders mismatch)",
		Citation: dumpParityTriageCitation,
	},
	{
		Pattern: "CREATE TABLE public.customers",
		Reason: "bare timestamptz (created_at) materializes an explicit precision (timestamp(6) with time zone) — see the shipments entry for the class. " +
			"The COLLATE delta this entry used to also cover is FIXED: the PG emitter now carries per-column COLLATE (pgCollateClause), so customers.region_code keeps COLLATE \"C\" on the target",
		Citation: dumpParityTriageCitation,
	},
	{
		Pattern:  "CREATE TABLE public.shipments",
		Reason:   "bare `timestamp with time zone` (typmod -1) round-trips as `timestamp(6) with time zone`: information_schema reports datetime_precision=6 for the unspecified form and ir.Timestamp has no 'precision unspecified' state, so the default precision is materialized into the catalog (behaviorally identical in PG — 6 IS the default — but catalog-visibly different; the temporal counterpart of Bug 69's Decimal.Unconstrained)",
		Citation: dumpParityTriageCitation,
	},
	{
		Pattern:  "ALTER TABLE public.* ADD CONSTRAINT *_unique",
		Reason:   "UNIQUE constraints on tables that have a PK are recreated as plain unique INDEXES, not table constraints (only the keyless-table cold-start path promotes one inline); semantically near-equivalent but catalog-visibly different",
		Citation: dumpParityTriageCitation,
	},
	{
		// pg_dump does not schema-qualify the index name in CREATE
		// INDEX (only the ON <table> side), so the key is the bare name.
		Pattern:  "CREATE INDEX *_unique",
		Reason:   "sluice side only: the unique index that stands in for the demoted UNIQUE constraint (counterpart of the ADD CONSTRAINT *_unique entry)",
		Citation: dumpParityTriageCitation,
	},
}
