//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// End-to-end integration test for Phase 3.1 + 3.2: take a full
// backup, ALTER + INSERT on the source, take an incremental, restore
// the chain into a fresh target, and verify the data arrives.
//
// PG → PG covers:
//
//   - Acceptance criterion 1: incremental writer captures CDC events.
//   - Acceptance criterion 2: chain restore produces same data.
//   - Acceptance criterion 4: schema evolution within a chain.

package pipeline

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"testing"
	"time"

	"github.com/orware/sluice/internal/engines"
	"github.com/orware/sluice/internal/ir"

	_ "github.com/orware/sluice/internal/engines/postgres"
)

// TestIncrementalBackup_PostgresChainRestore drives the full Phase 3
// happy path on PG: full → ALTER+INSERT on source → incremental →
// restore chain → verify target reflects post-incremental state.
func TestIncrementalBackup_PostgresChainRestore(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresLogical(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL
		);
		ALTER TABLE users REPLICA IDENTITY FULL;

		INSERT INTO users (email) VALUES
			('alice@example.com'),
			('bob@example.com');
	`
	applyDDL(t, sourceDSN, seedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	dir := t.TempDir()
	store, err := NewLocalStore(dir)
	if err != nil {
		t.Fatalf("NewLocalStore: %v", err)
	}

	// 1. Create the publication + slot BEFORE the full so PG starts
	//    retaining WAL from a known LSN and the publication is in
	//    place when the incremental's CDC reader connects. In a real
	//    Phase 3.3 deployment the full backup pipeline would do this;
	//    the v0.16.x full doesn't, so we simulate it here.
	applyDDL(t, sourceDSN, `CREATE PUBLICATION sluice_pub FOR ALL TABLES`)
	slotLSN, err := createPGLogicalSlotReturningLSN(t, sourceDSN, "sluice_slot")
	if err != nil {
		t.Fatalf("create slot: %v", err)
	}
	defer dropPGLogicalSlot(t, sourceDSN, "sluice_slot")

	// 2. Full backup.
	if err := (&Backup{
		Source: pgEng, SourceDSN: sourceDSN, Store: store,
		SluiceVersion: "test",
	}).Run(context.Background()); err != nil {
		t.Fatalf("Backup.Run: %v", err)
	}
	full, err := readManifest(context.Background(), store)
	if err != nil {
		t.Fatalf("readManifest: %v", err)
	}
	full.Kind = ir.BackupKindFull
	full.EndPosition = ir.Position{
		Engine: "postgres",
		Token:  fmt.Sprintf(`{"slot":"sluice_slot","lsn":%q}`, slotLSN),
	}
	full.BackupID = ir.ComputeBackupID(full)
	if err := writeManifestAt(context.Background(), store, ManifestFileName, full); err != nil {
		t.Fatalf("rewrite full manifest: %v", err)
	}

	// 3. Inserts on source AFTER the slot was created — captured
	//    via WAL retention by the slot.
	const evolveDDL = `
		INSERT INTO users (email) VALUES ('carol@example.com');
		INSERT INTO users (email) VALUES ('dave@example.com');
	`
	applyDDL(t, sourceDSN, evolveDDL)

	// 4. Incremental backup. Window is short — we want the channel
	//    to drain quickly. The fake clock/window code path isn't used
	//    here; we let the real CDC pump run for a few seconds and
	//    then cancel via Window.
	incrCtx, incrCancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer incrCancel()

	// Ensure the parent's recorded LSN is reachable from the slot.
	// fakeCDCEngine isn't applicable here — we use the real engine.
	incr := &IncrementalBackup{
		Source:        pgEng,
		SourceDSN:     sourceDSN,
		Store:         store,
		ParentRef:     full.BackupID,
		Window:        15 * time.Second, // long enough to capture the inserts
		MaxChanges:    20,               // close after observing them
		ChunkChanges:  10,
		SluiceVersion: "test",
	}
	if err := incr.Run(incrCtx); err != nil {
		t.Fatalf("IncrementalBackup.Run: %v", err)
	}

	// 5. Verify the new manifest landed.
	records, err := listAllManifestsViaWalk(context.Background(), store)
	if err != nil {
		t.Fatalf("listAllManifestsViaWalk: %v", err)
	}
	if len(records) != 2 {
		t.Fatalf("manifests = %d; want 2 (full + incremental)", len(records))
	}
	var incrMani *ir.Manifest
	for _, r := range records {
		if r.manifest.Kind == ir.BackupKindIncremental {
			incrMani = r.manifest
		}
	}
	if incrMani == nil {
		t.Fatal("no incremental manifest found")
	}
	if incrMani.ParentBackupID != full.BackupID {
		t.Errorf("ParentBackupID = %q; want %q", incrMani.ParentBackupID, full.BackupID)
	}
	if len(incrMani.ChangeChunks) == 0 {
		t.Errorf("ChangeChunks empty; expected at least one chunk capturing carol/dave inserts")
	}

	// 6. Verify chain.
	total, mismatches, err := VerifyBackup(context.Background(), store)
	if err != nil {
		t.Fatalf("VerifyBackup: %v", err)
	}
	if mismatches != 0 {
		t.Errorf("VerifyBackup: %d of %d chunks failed", mismatches, total)
	}

	// 7. Chain restore.
	if err := (&Restore{
		Target:    pgEng,
		TargetDSN: targetDSN,
		Store:     store,
	}).Run(context.Background()); err != nil {
		t.Fatalf("Restore.Run: %v", err)
	}

	// 8. Verify target reflects every row including carol/dave.
	got := pgQueryEmails(t, targetDSN)
	wantEmails := map[string]bool{
		"alice@example.com": true,
		"bob@example.com":   true,
		"carol@example.com": true,
		"dave@example.com":  true,
	}
	gotMap := map[string]bool{}
	for _, e := range got {
		gotMap[e] = true
	}
	for w := range wantEmails {
		if !gotMap[w] {
			t.Errorf("target missing email %q (got: %v)", w, got)
		}
	}
}

// TestIncrementalBackup_PostgresChainRestore_SchemaEvolution exercises
// Phase 3.2 acceptance criterion 4: ALTER TABLE on the source between
// the full and the incremental's window end surfaces as a SchemaDelta
// entry on the manifest, and chain restore applies the post-ALTER
// shape on the target.
func TestIncrementalBackup_PostgresChainRestore_SchemaEvolution(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresLogical(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL
		);
		ALTER TABLE users REPLICA IDENTITY FULL;
		INSERT INTO users (email) VALUES ('alice@example.com');
	`
	applyDDL(t, sourceDSN, seedDDL)

	pgEng, _ := engines.Get("postgres")
	dir := t.TempDir()
	store, _ := NewLocalStore(dir)

	applyDDL(t, sourceDSN, `CREATE PUBLICATION sluice_pub FOR ALL TABLES`)
	slotLSN, err := createPGLogicalSlotReturningLSN(t, sourceDSN, "sluice_slot")
	if err != nil {
		t.Fatalf("create slot: %v", err)
	}
	defer dropPGLogicalSlot(t, sourceDSN, "sluice_slot")

	if err := (&Backup{Source: pgEng, SourceDSN: sourceDSN, Store: store, SluiceVersion: "test"}).Run(context.Background()); err != nil {
		t.Fatalf("Backup.Run: %v", err)
	}
	full, _ := readManifest(context.Background(), store)
	full.Kind = ir.BackupKindFull
	full.EndPosition = ir.Position{
		Engine: "postgres",
		Token:  fmt.Sprintf(`{"slot":"sluice_slot","lsn":%q}`, slotLSN),
	}
	full.BackupID = ir.ComputeBackupID(full)
	if err := writeManifestAt(context.Background(), store, ManifestFileName, full); err != nil {
		t.Fatalf("rewrite full: %v", err)
	}

	// ALTER on source mid-chain.
	const evolveDDL = `
		ALTER TABLE users ADD COLUMN nickname VARCHAR(50);
		INSERT INTO users (email, nickname) VALUES ('bob@example.com', 'Bobby');
	`
	applyDDL(t, sourceDSN, evolveDDL)

	incrCtx, incrCancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer incrCancel()
	if err := (&IncrementalBackup{
		Source:        pgEng,
		SourceDSN:     sourceDSN,
		Store:         store,
		ParentRef:     full.BackupID,
		Window:        15 * time.Second,
		MaxChanges:    10,
		ChunkChanges:  10,
		SluiceVersion: "test",
	}).Run(incrCtx); err != nil {
		t.Fatalf("IncrementalBackup.Run: %v", err)
	}

	// Verify the manifest captured the schema delta.
	records, _ := listAllManifestsViaWalk(context.Background(), store)
	var incr *ir.Manifest
	for _, r := range records {
		if r.manifest.Kind == ir.BackupKindIncremental {
			incr = r.manifest
		}
	}
	if incr == nil {
		t.Fatal("no incremental manifest found")
	}
	if len(incr.SchemaDelta) == 0 {
		t.Errorf("SchemaDelta empty; expected an alter_table entry for users.ADD COLUMN nickname")
	} else {
		var sawAlter bool
		for _, d := range incr.SchemaDelta {
			if d.Kind == ir.SchemaDeltaAlterTable && d.Table == "users" {
				sawAlter = true
				if d.After == nil || len(d.After.Columns) != 3 {
					t.Errorf("After.Columns count = %d; want 3 (id, email, nickname)",
						len(d.After.Columns))
				}
			}
		}
		if !sawAlter {
			t.Errorf("expected alter_table on users in SchemaDelta; got %+v", incr.SchemaDelta)
		}
	}

	// Restore — the chain restore's CreateTablesWithoutConstraints is
	// idempotent on existing tables, so a v1 same-engine ADD COLUMN
	// won't be applied via DDL. The incremental's change events also
	// carry the new column value; the applier's column-list
	// reconciliation handles the new column on insert. For target
	// table shape verification: the full's schema is what lands; the
	// post-ALTER shape needs an explicit Phase-3.2 ALTER plumbing
	// that's flagged as a future-work item in the design doc.
	//
	// What we DO verify here: the restore completes cleanly, the
	// alice/bob rows arrive, and the SchemaDelta entry records the
	// shape change for the next chain consumer to act on.
	if err := (&Restore{
		Target:    pgEng,
		TargetDSN: targetDSN,
		Store:     store,
	}).Run(context.Background()); err != nil {
		t.Fatalf("Restore.Run: %v", err)
	}
	got := pgQueryEmails(t, targetDSN)
	if len(got) != 2 {
		t.Errorf("target rows = %d (got %v); want 2 after chain restore", len(got), got)
	}
}

// TestIncrementalBackup_PostgresChainRestore_TwoIncrementals is the
// integration regression for Bug 35 from the v0.17.0 cycle. Pre-fix,
// taking two incrementals into the same store reused the same
// `chunks/_changes/changes-0.jsonl.gz` path; the second overwrote the
// first's chunk while both manifests still referenced the first's
// SHA-256, breaking chain restore + `backup verify`.
//
// This test drives the v0.17.0 repro shape end-to-end on PG: full →
// inserts → incr1 → more inserts → incr2 → verify chain → chain
// restore → confirm every row arrives on the target.
func TestIncrementalBackup_PostgresChainRestore_TwoIncrementals(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresLogical(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL
		);
		ALTER TABLE users REPLICA IDENTITY FULL;
		INSERT INTO users (email) VALUES ('alice@example.com');
	`
	applyDDL(t, sourceDSN, seedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	dir := t.TempDir()
	store, err := NewLocalStore(dir)
	if err != nil {
		t.Fatalf("NewLocalStore: %v", err)
	}

	// Slot + publication BEFORE the full so subsequent inserts are
	// retained in WAL until the incrementals consume them.
	applyDDL(t, sourceDSN, `CREATE PUBLICATION sluice_pub FOR ALL TABLES`)
	slotLSN, err := createPGLogicalSlotReturningLSN(t, sourceDSN, "sluice_slot")
	if err != nil {
		t.Fatalf("create slot: %v", err)
	}
	defer dropPGLogicalSlot(t, sourceDSN, "sluice_slot")

	// Full backup.
	if err := (&Backup{
		Source: pgEng, SourceDSN: sourceDSN, Store: store, SluiceVersion: "test",
	}).Run(context.Background()); err != nil {
		t.Fatalf("Backup.Run: %v", err)
	}
	full, err := readManifest(context.Background(), store)
	if err != nil {
		t.Fatalf("readManifest: %v", err)
	}
	full.Kind = ir.BackupKindFull
	full.EndPosition = ir.Position{
		Engine: "postgres",
		Token:  fmt.Sprintf(`{"slot":"sluice_slot","lsn":%q}`, slotLSN),
	}
	full.BackupID = ir.ComputeBackupID(full)
	if err := writeManifestAt(context.Background(), store, ManifestFileName, full); err != nil {
		t.Fatalf("rewrite full manifest: %v", err)
	}

	// First batch of inserts → incr1.
	applyDDL(t, sourceDSN, `INSERT INTO users (email) VALUES ('bob@example.com'), ('carol@example.com');`)
	ctx1, cancel1 := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel1()
	if err := (&IncrementalBackup{
		Source: pgEng, SourceDSN: sourceDSN, Store: store,
		ParentRef:    full.BackupID,
		Window:       15 * time.Second,
		MaxChanges:   20,
		ChunkChanges: 100,
	}).Run(ctx1); err != nil {
		t.Fatalf("incr1 Run: %v", err)
	}

	// Second batch of inserts → incr2 into the SAME store.
	applyDDL(t, sourceDSN, `INSERT INTO users (email) VALUES ('dave@example.com'), ('erin@example.com');`)
	ctx2, cancel2 := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel2()
	if err := (&IncrementalBackup{
		Source: pgEng, SourceDSN: sourceDSN, Store: store,
		Window:       15 * time.Second,
		MaxChanges:   20,
		ChunkChanges: 100,
	}).Run(ctx2); err != nil {
		t.Fatalf("incr2 Run: %v", err)
	}

	// Inspect manifests.
	records, err := listAllManifestsViaWalk(context.Background(), store)
	if err != nil {
		t.Fatalf("listAllManifestsViaWalk: %v", err)
	}
	var incrs []*ir.Manifest
	for _, r := range records {
		if r.manifest.Kind == ir.BackupKindIncremental {
			incrs = append(incrs, r.manifest)
		}
	}
	if len(incrs) != 2 {
		t.Fatalf("incrementals = %d; want 2", len(incrs))
	}

	// Bug-35 regression assertions: each incremental's recorded chunk
	// path is distinct AND each manifest's recorded SHA-256 matches the
	// bytes on disk (pre-fix the second incremental overwrote the
	// first's bytes, so incr1's manifest hash diverged from on-disk).
	seen := map[string]string{} // path → "incr1"/"incr2"
	for i, m := range incrs {
		label := fmt.Sprintf("incr%d", i+1)
		if len(m.ChangeChunks) == 0 {
			t.Fatalf("%s has no change chunks", label)
		}
		for _, ch := range m.ChangeChunks {
			if other, dup := seen[ch.File]; dup {
				t.Errorf("change-chunk path collision: %s and %s both reference %q (Bug 35 regression)",
					other, label, ch.File)
			}
			seen[ch.File] = label
		}
	}

	// Full chain verify — pre-fix this surfaced
	// `chunk SHA-256 mismatch` because incr1's manifest hash didn't
	// match the bytes incr2 had written to the same path.
	total, mismatches, err := VerifyBackup(context.Background(), store)
	if err != nil {
		t.Fatalf("VerifyBackup: %v", err)
	}
	if mismatches != 0 {
		t.Errorf("VerifyBackup: %d of %d chunks failed (Bug 35 regression)", mismatches, total)
	}

	// Chain restore into a fresh target.
	if err := (&Restore{
		Target:    pgEng,
		TargetDSN: targetDSN,
		Store:     store,
	}).Run(context.Background()); err != nil {
		t.Fatalf("Restore.Run: %v", err)
	}

	got := pgQueryEmails(t, targetDSN)
	wantEmails := map[string]bool{
		"alice@example.com": true,
		"bob@example.com":   true,
		"carol@example.com": true,
		"dave@example.com":  true,
		"erin@example.com":  true,
	}
	gotMap := map[string]bool{}
	for _, e := range got {
		gotMap[e] = true
	}
	for w := range wantEmails {
		if !gotMap[w] {
			t.Errorf("target missing email %q after two-incremental chain restore (got: %v)", w, got)
		}
	}
}

// createPGLogicalSlotReturningLSN creates a logical-replication slot
// with the `pgoutput` plugin and returns its consistent-point LSN.
// The slot is required for the CDC pump to resume from a recorded
// LSN; the consistent point is the LSN at which the slot started
// retaining WAL.
//
// Idempotent: an existing slot's restart_lsn is returned without
// recreating.
func createPGLogicalSlotReturningLSN(t *testing.T, dsn, name string) (string, error) {
	t.Helper()
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		return "", err
	}
	defer func() { _ = db.Close() }()
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	var existingLSN string
	err = db.QueryRowContext(ctx,
		"SELECT restart_lsn::text FROM pg_replication_slots WHERE slot_name = $1",
		name).Scan(&existingLSN)
	if err == nil {
		return existingLSN, nil
	}
	var lsn string
	row := db.QueryRowContext(ctx,
		"SELECT lsn::text FROM pg_create_logical_replication_slot($1, 'pgoutput')", name)
	if err := row.Scan(&lsn); err != nil {
		return "", err
	}
	return lsn, nil
}

// dropPGLogicalSlot removes a replication slot. Tolerant of the slot
// being absent.
func dropPGLogicalSlot(t *testing.T, dsn, name string) {
	t.Helper()
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		return
	}
	defer func() { _ = db.Close() }()
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	_, _ = db.ExecContext(ctx, "SELECT pg_drop_replication_slot($1)", name)
}

// pgQueryEmails returns every email value in the target users table.
func pgQueryEmails(t *testing.T, dsn string) []string {
	t.Helper()
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer func() { _ = db.Close() }()
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	rows, err := db.QueryContext(ctx, "SELECT email FROM users ORDER BY id")
	if err != nil {
		t.Fatalf("query: %v", err)
	}
	defer func() { _ = rows.Close() }()
	var out []string
	for rows.Next() {
		var s string
		if err := rows.Scan(&s); err != nil {
			t.Fatalf("scan: %v", err)
		}
		out = append(out, s)
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}
	return out
}

// pgQueryEmailsTolerant is the sibling of [pgQueryEmails] for poll-loop
// callers that may run before the target table exists — e.g. broker
// `--reset-target-data` tests, where the broker drops + recreates the
// schema asynchronously and the test polls catch-up. Returns an empty
// slice when the table doesn't exist yet (SQLSTATE 42P01) instead of
// fatal-failing the test; surfaces other errors as fatals.
func pgQueryEmailsTolerant(t *testing.T, dsn string) []string {
	t.Helper()
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer func() { _ = db.Close() }()
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	rows, err := db.QueryContext(ctx, "SELECT email FROM users ORDER BY id")
	if err != nil {
		// Postgres SQLSTATE 42P01 = undefined_table. The text varies
		// across drivers but reliably contains "does not exist" plus
		// "users". Match on either signal so the test tolerates the
		// pre-recreation window.
		msg := err.Error()
		if strings.Contains(msg, "42P01") || strings.Contains(msg, "does not exist") {
			return nil
		}
		t.Fatalf("query: %v", err)
	}
	defer func() { _ = rows.Close() }()
	var out []string
	for rows.Next() {
		var s string
		if err := rows.Scan(&s); err != nil {
			t.Fatalf("scan: %v", err)
		}
		out = append(out, s)
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}
	return out
}
