//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

package pipeline

import (
	"context"
	"database/sql"
	"fmt"
	"log/slog"
	"strings"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/engines"
	"sluicesync.dev/sluice/internal/ir"
	irbackup "sluicesync.dev/sluice/internal/ir/backup"
	"sluicesync.dev/sluice/internal/logcapture"
	"sluicesync.dev/sluice/internal/pipeline/backup"
	"sluicesync.dev/sluice/internal/pipeline/blobcodec"
	"sluicesync.dev/sluice/internal/pipeline/lineage"
	"sluicesync.dev/sluice/internal/pipeline/migcore"
)

// TestIncrementalBackup_ChainRestore_AddColumnDefaults is the chain-replay
// lane of the pre-existing-row DEFAULT gate (GC-36 (2); the live-forward
// lanes are TestStreamer_AddColumnForward_PreexistingRowDefaults_*).
//
// An `ALTER TABLE users ADD COLUMN c … DEFAULT d` taken on the source
// between the full and an incremental fills every row the source already
// held with d, and that fill writes no row event. On restore, the rows the
// full brought back therefore get c ONLY from the replayed ADD COLUMN's
// DEFAULT. Each cell is graded per row against the SOURCE's own value
// (read back by id), so the expected value is independent of the manifest
// the restore replays.
//
// Three capture lanes, because the delta is recorded by two orchestrators
// (IncrementalBackup.Run, BackupStream's rollover) and read from two
// source catalogs: PG `backup incremental`, PG `backup stream`, MySQL
// `backup incremental`. The replay side (migcore.ApplyAlterDelta) is shared
// by chain restore and the broker, so it is one lane on the replay axis.
//
// GROUND TRUTH that reframed GC-36 (2): the recorded delta's After shape is
// a CATALOG read at window end (ReadSchema), not the CDC projection, so a
// constant DEFAULT is carried on every lane — the stable cells are green
// with no fix. What is lost is everything the window-END catalog does not
// say about the ALTER-TIME fill; those cells are knownWrong with the
// defect named, and a cell that starts reading back the source value
// fails the test so its entry gets removed.
func TestIncrementalBackup_ChainRestore_AddColumnDefaults(t *testing.T) {
	t.Run("pg-incremental", func(t *testing.T) { runACDLane(t, acdPGLane(false)) })
	t.Run("pg-stream", func(t *testing.T) { runACDLane(t, acdPGLane(true)) })
	t.Run("mysql-incremental", func(t *testing.T) { runACDLane(t, acdMySQLLane()) })
}

// acdCell is one ADD COLUMN shape.
type acdCell struct {
	col string
	def string // the column definition after the name
	// then runs in the same window, after every ADD COLUMN.
	then string
	// post is the column's explicit value on the post-ALTER row, for a
	// column that no longer has a default to omit it against.
	post string
	// knownWrong names the defect when the restored pre-existing rows are
	// measured wrong today; empty means they must equal the source.
	knownWrong string
	// wantFillWarn: the replay must name this column under
	// migcore.AddColumnFillNotReproducibleMarker.
	wantFillWarn bool
}

// acdLane is one (source engine, capture orchestrator) combination.
type acdLane struct {
	engine string
	driver string
	start  func(t *testing.T) (src, tgt string, cleanup func())
	seed   string
	// startPos records the position the full's chain starts at (slot LSN
	// or binlog coordinate) and returns a teardown.
	startPos func(t *testing.T, src string) (ir.Position, func())
	exec     func(t *testing.T, dsn, sql string)
	// render is the per-cell grading expression (textual, both sides).
	render func(col string) string
	cells  []acdCell
	stream bool
}

// Known-wrong reasons, shared across lanes.
const (
	acdWindowEndDefault   = "the delta records the window-END DEFAULT; the source filled its rows with the ALTER-time one (no manifest field carries it)"
	acdEvaluatedAtRestore = "a non-constant DEFAULT is evaluated on the target at restore time; the source's ALTER-time values are in no link (named by ADD-COLUMN-FILL-NOT-REPRODUCIBLE)"
	acdMySQLEmitterDrop   = "GC-36 (4): the MySQL target emitter drops a TEXT/BLOB/JSON DEFAULT (with a WARN) although MySQL 8.0.13+ accepts the expression form"
)

func acdPGLane(stream bool) acdLane {
	return acdLane{
		engine: "postgres",
		driver: "pgx",
		start:  startPostgresLogical,
		seed: `
			CREATE TABLE users (
				id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				email VARCHAR(255) NOT NULL
			);
			ALTER TABLE users REPLICA IDENTITY FULL;
			INSERT INTO users (email) VALUES ('a@x'), ('b@x'), ('c@x');
			CREATE PUBLICATION sluice_pub FOR ALL TABLES;`,
		startPos: func(t *testing.T, src string) (ir.Position, func()) {
			lsn, err := createPGLogicalSlotReturningLSN(t, src, "sluice_slot")
			if err != nil {
				t.Fatalf("create slot: %v", err)
			}
			return ir.Position{Engine: "postgres", Token: fmt.Sprintf(`{"slot":"sluice_slot","lsn":%q}`, lsn)},
				func() { dropPGLogicalSlot(t, src, "sluice_slot") }
		},
		exec:   applyDDL,
		render: func(col string) string { return fmt.Sprintf(`%q::text`, col) },
		stream: stream,
		cells: []acdCell{
			{col: "c_text", def: `TEXT DEFAULT 'abc'`},
			{col: "c_varchar", def: `VARCHAR(10) DEFAULT 'vv'`},
			{col: "c_int", def: `INTEGER DEFAULT 42`},
			{col: "c_bigint", def: `BIGINT DEFAULT -9000000000`},
			{col: "c_numeric", def: `NUMERIC(10,2) DEFAULT 1.10`},
			{col: "c_float", def: `DOUBLE PRECISION DEFAULT 2.5`},
			{col: "c_bool", def: `BOOLEAN DEFAULT true`},
			{col: "c_ts", def: `TIMESTAMP DEFAULT '2020-01-02 03:04:05.123456'`},
			{col: "c_tstz", def: `TIMESTAMPTZ DEFAULT '2020-01-02 03:04:05+00'`},
			{col: "c_date", def: `DATE DEFAULT '2020-01-02'`},
			{col: "c_bytea", def: `BYTEA DEFAULT '\x00ff'::bytea`},
			{col: "c_jsonb", def: `JSONB DEFAULT '{"a": 1}'::jsonb`},
			{col: "c_uuid", def: `UUID DEFAULT 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11'`},
			{col: "c_nn_text", def: `TEXT NOT NULL DEFAULT 'nn'`},
			{col: "c_nn_int", def: `INTEGER NOT NULL DEFAULT 7`},
			// Django's AddField: the default exists only for the ALTER.
			{col: "x_django", def: `TEXT DEFAULT 'dj'`, then: `ALTER TABLE users ALTER COLUMN x_django DROP DEFAULT`, post: `'p'`, knownWrong: acdWindowEndDefault},
			{col: "x_django_nn", def: `INTEGER NOT NULL DEFAULT 5`, then: `ALTER TABLE users ALTER COLUMN x_django_nn DROP DEFAULT`, post: `9`, knownWrong: acdWindowEndDefault},
			{col: "x_reset", def: `TEXT DEFAULT 'first'`, then: `ALTER TABLE users ALTER COLUMN x_reset SET DEFAULT 'second'`, knownWrong: acdWindowEndDefault},
			// PG stores now()'s ALTER-time value as the fill (a STABLE
			// default); clock_timestamp() rewrites the table per row.
			{col: "x_now", def: `TIMESTAMPTZ DEFAULT now()`, knownWrong: acdEvaluatedAtRestore, wantFillWarn: true},
			{col: "x_clock", def: `TIMESTAMPTZ DEFAULT clock_timestamp()`, knownWrong: acdEvaluatedAtRestore, wantFillWarn: true},
		},
	}
}

func acdMySQLLane() acdLane {
	return acdLane{
		engine: "mysql",
		driver: "mysql",
		start:  startMySQLBinlog,
		seed: `
			CREATE TABLE users (
				id    BIGINT       NOT NULL AUTO_INCREMENT,
				email VARCHAR(255) NOT NULL,
				PRIMARY KEY (id)
			) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
			INSERT INTO users (email) VALUES ('a@x'), ('b@x'), ('c@x');`,
		startPos: func(t *testing.T, src string) (ir.Position, func()) {
			file, pos := readMySQLBinlogPos(t, src)
			return ir.Position{Engine: "mysql", Token: fmt.Sprintf(`{"mode":"file_pos","file":%q,"pos":%d}`, file, pos)}, func() {}
		},
		exec: applyDDLMySQL,
		render: func(col string) string {
			if strings.HasPrefix(col, "c_bin") {
				return fmt.Sprintf("HEX(`%s`)", col)
			}
			return fmt.Sprintf("CAST(`%s` AS CHAR)", col)
		},
		cells: []acdCell{
			{col: "c_varchar", def: `VARCHAR(10) DEFAULT 'vv'`},
			{col: "c_int", def: `INT DEFAULT 42`},
			{col: "c_bigint", def: `BIGINT DEFAULT -9000000000`},
			{col: "c_decimal", def: `DECIMAL(10,2) DEFAULT 1.10`},
			{col: "c_double", def: `DOUBLE DEFAULT 2.5`},
			{col: "c_bool", def: `TINYINT(1) DEFAULT 1`},
			{col: "c_datetime", def: `DATETIME(6) DEFAULT '2020-01-02 03:04:05.123456'`},
			{col: "c_date", def: `DATE DEFAULT '2020-01-02'`},
			{col: "c_enum", def: `ENUM('a','b') DEFAULT 'b'`},
			{col: "c_binary", def: `VARBINARY(4) DEFAULT 0x00FF`},
			// MySQL 8.0.13+ expression defaults on TEXT/BLOB/JSON reach the
			// chain replay and are dropped by the MySQL target emitter —
			// the GC-36 (4) defect, on this path too.
			{col: "c_text", def: `TEXT DEFAULT ('abc')`, knownWrong: acdMySQLEmitterDrop},
			{col: "c_bin_blob", def: `BLOB DEFAULT (0x00FF)`, knownWrong: acdMySQLEmitterDrop},
			{col: "c_json", def: `JSON DEFAULT ('{"a": 1}')`, knownWrong: acdMySQLEmitterDrop},
			{col: "c_nn_varchar", def: `VARCHAR(10) NOT NULL DEFAULT 'nn'`},
			{col: "c_nn_int", def: `INT NOT NULL DEFAULT 7`},
			{col: "x_django", def: `VARCHAR(10) DEFAULT 'dj'`, then: "ALTER TABLE users ALTER COLUMN x_django DROP DEFAULT", post: `'p'`, knownWrong: acdWindowEndDefault},
			{col: "x_django_nn", def: `INT NOT NULL DEFAULT 5`, then: "ALTER TABLE users ALTER COLUMN x_django_nn DROP DEFAULT", post: `9`, knownWrong: acdWindowEndDefault},
			{col: "x_reset", def: `VARCHAR(10) DEFAULT 'first'`, then: "ALTER TABLE users ALTER COLUMN x_reset SET DEFAULT 'second'", knownWrong: acdWindowEndDefault},
			{col: "x_now", def: `DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6)`, knownWrong: acdEvaluatedAtRestore, wantFillWarn: true},
		},
	}
}

// runACDLane takes a full, applies every cell's ADD COLUMN (then its
// follow-up) plus one post-ALTER write, captures one incremental with the
// lane's orchestrator, chain-restores into the fresh target and grades.
func runACDLane(t *testing.T, lane acdLane) {
	src, tgt, cleanup := lane.start(t)
	defer cleanup()
	lane.exec(t, src, lane.seed)

	eng, ok := engines.Get(lane.engine)
	if !ok {
		t.Fatalf("%s engine not registered", lane.engine)
	}
	store, err := blobcodec.NewLocalStore(t.TempDir())
	if err != nil {
		t.Fatalf("NewLocalStore: %v", err)
	}
	pos, teardown := lane.startPos(t, src)
	defer teardown()

	ctx := context.Background()
	if err := (&backup.Backup{Source: eng, SourceDSN: src, Store: store, SluiceVersion: "test"}).Run(ctx); err != nil {
		t.Fatalf("Backup.Run: %v", err)
	}
	full, err := lineage.ReadManifest(ctx, store)
	if err != nil {
		t.Fatalf("ReadManifest: %v", err)
	}
	full.Kind = irbackup.BackupKindFull
	full.EndPosition = pos
	full.BackupID = irbackup.ComputeBackupID(full)
	if err := lineage.WriteManifestAt(ctx, store, lineage.ManifestFileName, full); err != nil {
		t.Fatalf("rewrite full: %v", err)
	}

	var window []string
	for _, c := range lane.cells {
		window = append(window, fmt.Sprintf("ALTER TABLE users ADD COLUMN %s %s", c.col, c.def))
	}
	for _, c := range lane.cells {
		if c.then != "" {
			window = append(window, c.then)
		}
	}
	cols, vals := []string{"email"}, []string{"'post@x'"}
	for _, c := range lane.cells {
		if c.post != "" {
			cols, vals = append(cols, c.col), append(vals, c.post)
		}
	}
	window = append(window, fmt.Sprintf("INSERT INTO users (%s) VALUES (%s)", strings.Join(cols, ", "), strings.Join(vals, ", ")))
	lane.exec(t, src, strings.Join(window, ";\n")+";")

	if lane.stream {
		acdRunStream(t, eng, src, store, full.BackupID)
	} else {
		incrCtx, cancel := context.WithTimeout(ctx, 60*time.Second)
		defer cancel()
		if err := (&IncrementalBackup{
			Source: eng, SourceDSN: src, Store: store, ParentRef: full.BackupID,
			Window: 15 * time.Second, MaxChanges: 10, ChunkChanges: 10, SluiceVersion: "test",
		}).Run(incrCtx); err != nil {
			t.Fatalf("IncrementalBackup.Run: %v", err)
		}
	}

	logBuf := &logcapture.Buffer{}
	prev := slog.Default()
	slog.SetDefault(slog.New(slog.NewJSONHandler(logBuf, &slog.HandlerOptions{Level: slog.LevelInfo})))
	restoreErr := (&backup.Restore{Target: eng, TargetDSN: tgt, Store: store}).Run(ctx)
	slog.SetDefault(prev)
	if restoreErr != nil {
		t.Fatalf("Restore.Run: %v", restoreErr)
	}
	logs := logBuf.String()
	if !strings.Contains(logs, "applied ADD COLUMN") {
		t.Fatalf("restore applied no ADD COLUMN — the gate graded nothing it claims to (logs: %s)", logs)
	}

	for _, c := range lane.cells {
		acdGradeCell(t, lane, src, tgt, c, logs)
	}
}

// acdRunStream runs `backup stream` until at least one rollover has
// committed and the count has settled, then stops it.
func acdRunStream(t *testing.T, eng ir.Engine, src string, store irbackup.Store, parent string) {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()
	stream := &BackupStream{
		Source: eng, SourceDSN: src, Store: store, ParentRef: parent,
		RolloverWindow: 2 * time.Second, RolloverMaxChanges: 10, RolloverMaxBytes: 1 << 30,
		ChunkChanges: 100, SluiceVersion: "test",
	}
	done := make(chan error, 1)
	go func() { done <- stream.Run(ctx) }()

	var last, stable int
	for deadline := time.Now().Add(60 * time.Second); time.Now().Before(deadline); time.Sleep(500 * time.Millisecond) {
		records, _ := lineage.ListAllManifestsViaWalk(context.Background(), store)
		n, withDelta := 0, false
		for _, r := range records {
			if r.Manifest.Kind == irbackup.BackupKindIncremental {
				n++
				withDelta = withDelta || len(r.Manifest.SchemaDelta) > 0
			}
		}
		if n == last {
			stable++
		} else {
			last, stable = n, 0
		}
		if withDelta && stable >= 6 {
			break
		}
	}
	cancel()
	select {
	case err := <-done:
		if err != nil {
			t.Fatalf("stream.Run after cancel = %v; want nil", err)
		}
	case <-time.After(15 * time.Second):
		t.Fatal("stream.Run did not exit within 15s of cancel")
	}
}

// acdGradeCell grades one cell's rows and its fill WARN.
func acdGradeCell(t *testing.T, lane acdLane, src, tgt string, c acdCell, logs string) {
	t.Helper()
	want := acdColumnByID(t, lane, src, c.col)
	got := acdColumnByID(t, lane, tgt, c.col)
	if len(want) != 4 || len(got) != len(want) {
		t.Errorf("%s: row counts source=%d target=%d; want 4 each", c.col, len(want), len(got))
		return
	}
	// The post-ALTER row carries an explicit value in its row event, so
	// it must match on every cell; ids 1-3 are the pre-existing rows.
	var wrong []string
	for id := int64(1); id <= 4; id++ {
		if got[id] == want[id] {
			continue
		}
		if id == 4 {
			t.Errorf("%s (%s): the post-ALTER row id=4 reads %q, source %q — the row event's own value did not land", c.col, c.def, got[id], want[id])
			continue
		}
		wrong = append(wrong, fmt.Sprintf("id=%d source %q target %q", id, want[id], got[id]))
	}
	switch {
	case c.knownWrong == "" && len(wrong) > 0:
		t.Errorf("%s (%s): WRONG — pre-existing rows restored without the source's fill: %s", c.col, c.def, strings.Join(wrong, "; "))
	case c.knownWrong != "" && len(wrong) == 0:
		t.Errorf("%s (%s): NOW-CORRECT — known-wrong cell reads back the source value on every pre-existing row; remove its knownWrong (%s)", c.col, c.def, c.knownWrong)
	case c.knownWrong != "":
		t.Logf("%s (%s): KNOWN-WRONG (%s): %s", c.col, c.def, c.knownWrong, strings.Join(wrong, "; "))
	}

	// Per line: other WARNs (the MySQL emitter's dropped-default one) name
	// the same column.
	warned := false
	for _, line := range strings.Split(logs, "\n") {
		if strings.Contains(line, migcore.AddColumnFillNotReproducibleMarker) &&
			strings.Contains(line, fmt.Sprintf(`"column":%q`, c.col)) {
			warned = true
		}
	}
	if c.wantFillWarn && !warned {
		t.Errorf("%s (%s): restore did not name the column under %s — its pre-existing rows differ from the source silently",
			c.col, c.def, migcore.AddColumnFillNotReproducibleMarker)
	}
	if !c.wantFillWarn && warned {
		t.Errorf("%s (%s): restore named a constant DEFAULT under %s", c.col, c.def, migcore.AddColumnFillNotReproducibleMarker)
	}
}

// acdColumnByID returns the lane's textual rendering of users.<col> keyed
// by id, "<NULL>" for NULL.
func acdColumnByID(t *testing.T, lane acdLane, dsn, col string) map[int64]string {
	t.Helper()
	db, err := sql.Open(lane.driver, dsn)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer func() { _ = db.Close() }()
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	rows, err := db.QueryContext(ctx, fmt.Sprintf(`SELECT id, %s FROM users`, lane.render(col)))
	if err != nil {
		t.Fatalf("query %s: %v", col, err)
	}
	defer func() { _ = rows.Close() }()
	out := map[int64]string{}
	for rows.Next() {
		var id int64
		var v sql.NullString
		if err := rows.Scan(&id, &v); err != nil {
			t.Fatalf("scan: %v", err)
		}
		out[id] = "<NULL>"
		if v.Valid {
			out[id] = v.String
		}
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}
	return out
}
