//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// Roadmap item 92, against a real Postgres source: the real-wire half of
// the pin in incremental_maxchanges_replay_test.go.
//
// The unit pin scripts the replay; this one PROVOKES it. It chains two
// incrementals so the second resumes at a position PostgreSQL itself
// produced (a commit LSN), which is the only way to exercise the actual
// walsender behaviour behind the bug: logical decoding restarts at
// max(requested_lsn, confirmed_flush_lsn) and skips only transactions
// committing STRICTLY BEFORE that point, so the transaction the parent
// segment ends on is re-delivered in full. Nothing in sluice can be
// mocked into that; it has to come off the wire.

package pipeline

import (
	"context"
	"fmt"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/engines"
	"sluicesync.dev/sluice/internal/ir"
	irbackup "sluicesync.dev/sluice/internal/ir/backup"
	"sluicesync.dev/sluice/internal/pipeline/backup"
	"sluicesync.dev/sluice/internal/pipeline/blobcodec"
	"sluicesync.dev/sluice/internal/pipeline/lineage"

	_ "sluicesync.dev/sluice/internal/engines/postgres"
)

// TestIncrementalBackup_PostgresMaxChangesBoundedWindowOutrunsTheReplay
// is the item-92 gate. A tightly-bounded second incremental must not
// close on the boundary transaction its own resume replays: its
// EndPosition has to move past its StartPosition, and a chain restore
// has to carry the row committed after the parent — the observed cost
// was a restore cell holding 3 rows instead of 4.
func TestIncrementalBackup_PostgresMaxChangesBoundedWindowOutrunsTheReplay(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresLogical(t)
	defer cleanup()

	applyDDL(t, sourceDSN, `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL
		);
		ALTER TABLE users REPLICA IDENTITY FULL;
		INSERT INTO users (email) VALUES ('alice@example.com');
	`)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}
	store, err := blobcodec.NewLocalStore(t.TempDir())
	if err != nil {
		t.Fatalf("NewLocalStore: %v", err)
	}

	applyDDL(t, sourceDSN, `CREATE PUBLICATION sluice_pub FOR ALL TABLES`)
	slotLSN, err := createPGLogicalSlotReturningLSN(t, sourceDSN, "sluice_slot")
	if err != nil {
		t.Fatalf("create slot: %v", err)
	}
	defer dropPGLogicalSlot(t, sourceDSN, "sluice_slot")

	ctx := context.Background()
	if err := (&backup.Backup{
		Source: pgEng, SourceDSN: sourceDSN, Store: store, SluiceVersion: "test",
	}).Run(ctx); err != nil {
		t.Fatalf("Backup.Run: %v", err)
	}
	full, err := lineage.ReadManifest(ctx, store)
	if err != nil {
		t.Fatalf("ReadManifest: %v", err)
	}
	full.Kind = irbackup.BackupKindFull
	full.EndPosition = ir.Position{
		Engine: "postgres",
		Token:  fmt.Sprintf(`{"slot":"sluice_slot","lsn":%q}`, slotLSN),
	}
	full.BackupID = irbackup.ComputeBackupID(full)
	if err := lineage.WriteManifestAt(ctx, store, lineage.ManifestFileName, full); err != nil {
		t.Fatalf("rewrite full manifest: %v", err)
	}

	// Link 1: a time-bounded incremental over one committed transaction.
	// Its EndPosition is bob's commit LSN — the position link 2 resumes
	// at, and therefore the transaction PostgreSQL will replay.
	applyDDL(t, sourceDSN, `INSERT INTO users (email) VALUES ('bob@example.com');`)
	link1 := runBoundedIncremental(t, pgEng, sourceDSN, store, full.BackupID, 0)
	if len(link1.ChangeChunks) == 0 {
		t.Fatalf("link 1 captured no changes; the fixture cannot provoke a replay (end=%s)", link1.EndPosition.Token)
	}

	// Link 2 resumes at bob's commit LSN with a bound (2) that the
	// replayed bob transaction satisfies all by itself.
	applyDDL(t, sourceDSN, `INSERT INTO users (email) VALUES ('carol@example.com');`)
	link2 := runBoundedIncremental(t, pgEng, sourceDSN, store, link1.BackupID, 2)

	if link2.StartPosition != link1.EndPosition {
		t.Fatalf("link 2 StartPosition = %s; want link 1's EndPosition %s",
			link2.StartPosition.Token, link1.EndPosition.Token)
	}
	if link2.EndPosition == link2.StartPosition {
		t.Errorf("link 2 EndPosition == StartPosition (%s) — the bound closed the window on the replayed boundary transaction, so the segment carries none of the delta (roadmap item 92)",
			link2.EndPosition.Token)
	}
	after, err := pgEng.(ir.PositionMonotonicChecker).PrecedesOrEqual(link2.StartPosition, link2.EndPosition)
	if err != nil {
		t.Fatalf("PrecedesOrEqual: %v", err)
	}
	if !after {
		t.Errorf("link 2 EndPosition %s is not at-or-after its StartPosition %s",
			link2.EndPosition.Token, link2.StartPosition.Token)
	}

	// The load-bearing assertion: restore the chain and count the rows.
	if err := (&backup.Restore{Target: pgEng, TargetDSN: targetDSN, Store: store}).Run(ctx); err != nil {
		t.Fatalf("Restore.Run: %v", err)
	}
	got := map[string]bool{}
	for _, e := range pgQueryEmails(t, targetDSN) {
		got[e] = true
	}
	for _, want := range []string{"alice@example.com", "bob@example.com", "carol@example.com"} {
		if !got[want] {
			t.Errorf("restored target is missing %q (has: %v)", want, got)
		}
	}
}

// runBoundedIncremental runs one incremental against the live source and
// returns the manifest it wrote. maxChanges of 0 is the time-bounded
// shape; a non-zero value is the bounded shape under test.
func runBoundedIncremental(t *testing.T, eng ir.Engine, sourceDSN string, store irbackup.Store, parentID string, maxChanges int) *irbackup.Manifest {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 120*time.Second)
	defer cancel()

	before, err := lineage.ListAllManifestsViaWalk(ctx, store)
	if err != nil {
		t.Fatalf("list manifests (before): %v", err)
	}
	seen := map[string]bool{}
	for _, r := range before {
		seen[r.Path] = true
	}

	if err := (&IncrementalBackup{
		Source:        eng,
		SourceDSN:     sourceDSN,
		Store:         store,
		ParentRef:     parentID,
		Window:        20 * time.Second,
		MaxChanges:    maxChanges,
		ChunkChanges:  100,
		SluiceVersion: "test",
	}).Run(ctx); err != nil {
		t.Fatalf("IncrementalBackup.Run (max_changes=%d): %v", maxChanges, err)
	}

	after, err := lineage.ListAllManifestsViaWalk(ctx, store)
	if err != nil {
		t.Fatalf("list manifests (after): %v", err)
	}
	for _, r := range after {
		if !seen[r.Path] && r.Manifest.Kind == irbackup.BackupKindIncremental {
			return r.Manifest
		}
	}
	t.Fatalf("no new incremental manifest after a run with max_changes=%d", maxChanges)
	return nil
}
