// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

//go:build integration

package pipeline

import (
	"context"
	"fmt"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/engines"
	"sluicesync.dev/sluice/internal/ir"
	irbackup "sluicesync.dev/sluice/internal/ir/backup"
	"sluicesync.dev/sluice/internal/pipeline/backup"
	"sluicesync.dev/sluice/internal/pipeline/blobcodec"
	"sluicesync.dev/sluice/internal/pipeline/lineage"
)

// TestItem60_AnchorImpliesSchemaDelta_PG is the audit-2026-07-11 item-60
// GROUND TRUTH for facet (c) — the PG/MySQL SchemaHistory anchor-forge.
//
// The proposed signing-independent fix gates anchor-trust on len(SchemaDelta)>0
// (an emptied-DATA window has an empty delta; a genuine DDL-only window has a
// non-empty one). It is SAFE iff the invariant
//
//	SchemaHistoryAnchors(EndPosition) == true  =>  len(SchemaDelta) > 0
//
// holds for every legitimate incremental — otherwise it would false-positive
// refuse a legit restore (the twice-burned Bug-183/184 trap). Code-reading
// established WHY it should hold: both readers anchor a snapshot only on an
// ir.SchemaSignatureOf (column-name, ordered-type) delta (postgres
// cdc_reader.go maybeSnapshotSchema; mysql snapshotSig), which is a SUBSET of
// what DiffSchemas/columnsEqual compares (name/type/nullable/generated/default
// + PK + indexes). This test OBSERVES it against real Postgres across the DDL
// shapes that matter, and pins the invariant as an executable assertion.
//
// It logs the actual manifest shape (chunk count, SchemaDelta count, whether a
// schema anchor sits at EndPosition, EndPosition-vs-StartPosition) for each
// scenario so the ground truth is recorded, then asserts the invariant.
func TestItem60_AnchorImpliesSchemaDelta_PG(t *testing.T) {
	for _, tc := range []struct {
		name string
		// windowSQL runs on the source AFTER the full backup, before the
		// incremental window closes. It defines the window's shape.
		windowSQL string
		// wantSchemaDelta is our code-reading expectation for len(SchemaDelta)>0.
		wantSchemaDelta bool
	}{
		{
			// The canonical legit DDL-only window. A column-signature delta,
			// so the reader anchors a snapshot AND DiffSchemas records it.
			name:            "pure ADD COLUMN (no DML)",
			windowSQL:       `ALTER TABLE users ADD COLUMN nickname VARCHAR(50);`,
			wantSchemaDelta: true,
		},
		{
			// A type-PARAMETER change: signature delta (reflect.DeepEqual on
			// the IR type) AND a TypeString delta — belt-and-suspenders on the
			// one theoretical escape (a DeepEqual-distinct/TypeString-identical
			// type change).
			name:            "ALTER COLUMN TYPE param change (no DML)",
			windowSQL:       `ALTER TABLE users ALTER COLUMN email TYPE VARCHAR(512);`,
			wantSchemaDelta: true,
		},
		{
			// A CONSTRAINT-only DDL: DiffSchemas ignores CheckConstraints, so
			// SchemaDelta is empty. The reader's signature is ALSO unchanged
			// (no column delta), so it must NOT anchor a snapshot at
			// EndPosition — otherwise the invariant breaks. This is the
			// scenario that would make the gate UNSAFE if it anchored.
			name:            "ADD CHECK CONSTRAINT only (no DML)",
			windowSQL:       `ALTER TABLE users ADD CONSTRAINT email_nonempty CHECK (length(email) > 0);`,
			wantSchemaDelta: false,
		},
		{
			// A first-touch DATA window: a brand-new table's rows, no DDL on
			// the pre-existing tables. This is the FORGERY TARGET — the
			// routine first-touch snapshot the adversary re-anchors to
			// EndPosition. It must have an EMPTY SchemaDelta relative to the
			// window (the new table is an add_table delta though) — the point
			// is to observe where its anchor sits vs EndPosition.
			name:            "first-touch DATA window (INSERT, no DDL on existing)",
			windowSQL:       `INSERT INTO users (email) VALUES ('carol@example.com');`,
			wantSchemaDelta: false,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			sourceDSN, _, cleanup := startPostgresLogical(t)
			defer cleanup()

			const seedDDL = `
				CREATE TABLE users (
					id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					email VARCHAR(255) NOT NULL
				);
				ALTER TABLE users REPLICA IDENTITY FULL;
				INSERT INTO users (email) VALUES ('alice@example.com');
			`
			applyDDL(t, sourceDSN, seedDDL)

			pgEng, _ := engines.Get("postgres")
			dir := t.TempDir()
			store, _ := blobcodec.NewLocalStore(dir)

			applyDDL(t, sourceDSN, `CREATE PUBLICATION sluice_pub FOR ALL TABLES`)
			slotLSN, err := createPGLogicalSlotReturningLSN(t, sourceDSN, "sluice_slot")
			if err != nil {
				t.Fatalf("create slot: %v", err)
			}
			defer dropPGLogicalSlot(t, sourceDSN, "sluice_slot")

			if err := (&backup.Backup{Source: pgEng, SourceDSN: sourceDSN, Store: store, SluiceVersion: "test"}).Run(context.Background()); err != nil {
				t.Fatalf("Backup.Run: %v", err)
			}
			full, _ := lineage.ReadManifest(context.Background(), store)
			full.Kind = irbackup.BackupKindFull
			full.EndPosition = ir.Position{
				Engine: "postgres",
				Token:  fmt.Sprintf(`{"slot":"sluice_slot","lsn":%q}`, slotLSN),
			}
			full.BackupID = irbackup.ComputeBackupID(full)
			if err := lineage.WriteManifestAt(context.Background(), store, lineage.ManifestFileName, full); err != nil {
				t.Fatalf("rewrite full: %v", err)
			}

			applyDDL(t, sourceDSN, tc.windowSQL)

			incrCtx, incrCancel := context.WithTimeout(context.Background(), 60*time.Second)
			defer incrCancel()
			if err := (&IncrementalBackup{
				Source:        pgEng,
				SourceDSN:     sourceDSN,
				Store:         store,
				ParentRef:     full.BackupID,
				Window:        15 * time.Second,
				MaxChanges:    10,
				ChunkChanges:  10,
				SluiceVersion: "test",
			}).Run(incrCtx); err != nil {
				t.Fatalf("IncrementalBackup.Run: %v", err)
			}

			records, _ := lineage.ListAllManifestsViaWalk(context.Background(), store)
			var incr *irbackup.Manifest
			for _, r := range records {
				if r.Manifest.Kind == irbackup.BackupKindIncremental {
					incr = r.Manifest
				}
			}
			if incr == nil {
				t.Fatal("no incremental manifest found")
			}

			anchorsAtEnd := incr.SchemaHistoryAnchors(incr.EndPosition)
			posBearing := incr.EndPosition.Engine != "" || incr.EndPosition.Token != ""
			claimsAdvance := incr.EndPosition != incr.StartPosition

			// GROUND TRUTH — record the observed shape.
			t.Logf("[item60 ground truth] scenario=%q chunks=%d schemaDelta=%d "+
				"anchorsAtEnd=%v posBearing=%v claimsAdvance=%v end=%+v start=%+v history=%d",
				tc.name, len(incr.ChangeChunks), len(incr.SchemaDelta),
				anchorsAtEnd, posBearing, claimsAdvance,
				incr.EndPosition, incr.StartPosition, len(incr.SchemaHistory))

			// THE INVARIANT gate (b) relies on: an anchor at EndPosition on a
			// position-advancing window must imply a non-empty SchemaDelta.
			// If this ever fails, the SchemaDelta gate would false-refuse a
			// legit restore — do NOT ship it.
			if anchorsAtEnd && posBearing && claimsAdvance && len(incr.SchemaDelta) == 0 {
				t.Errorf("INVARIANT VIOLATED: scenario %q has a schema anchor AT EndPosition on a "+
					"position-advancing window but an EMPTY SchemaDelta — the len(SchemaDelta)>0 "+
					"gate would FALSE-REFUSE this legit window. Gate (b) is UNSAFE for this shape.",
					tc.name)
			}

			// Sanity: our per-shape SchemaDelta expectation (observability, not
			// the safety gate — a mismatch just means the shape behaved
			// differently than code-reading predicted, worth knowing).
			if got := len(incr.SchemaDelta) > 0; got != tc.wantSchemaDelta {
				t.Logf("[item60 note] scenario %q: len(SchemaDelta)>0 = %v, code-reading predicted %v "+
					"(not a failure by itself; the safety invariant above is what gates the fix)",
					tc.name, got, tc.wantSchemaDelta)
			}
		})
	}
}
