//go:build integration

// Integration test for --reset-target-data on `sluice migrate`
// (ADR-0023). The flag DELETEs the migrate-state row, DROPs every
// source-schema table on the target, and runs a fresh cold-start.
//
// Scenario: cold-start a migration once, manually tamper with the
// dest by inserting a stray row, then re-run with --reset-target-data
// against the now-populated dest. The reset wipes the dest cleanly
// and re-bulk-copies; the stray row disappears, the source row count
// matches.

package pipeline

import (
	"context"
	"database/sql"
	"testing"
	"time"

	"github.com/orware/sluice/internal/engines"

	_ "github.com/orware/sluice/internal/engines/postgres"
)

// TestMigrate_ResetTargetData_HappyPath exercises the reset path
// end-to-end. After a clean cold-start, the test "tampers" with the
// dest (a stray row + a stale migrate-state row) and re-runs migrate
// with ResetTargetData=true. Asserts the dest matches the source and
// the bookkeeping row reflects the new run, not the old one.
func TestMigrate_ResetTargetData_HappyPath(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE products (
			id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name TEXT NOT NULL
		);
		INSERT INTO products (name)
			SELECT 'product-' || g FROM generate_series(1, 50) g;
	`
	applyPGDDL(t, sourceDSN, seedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	const migrationID = "reset-happy-path"

	// ---- Phase 1: clean cold-start ----
	mig := &Migrator{
		Source: pgEng, Target: pgEng,
		SourceDSN: sourceDSN, TargetDSN: targetDSN,
		MigrationID: migrationID,
	}
	ctx1, cancel1 := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel1()
	if err := mig.Run(ctx1); err != nil {
		t.Fatalf("initial migrate: %v", err)
	}
	if got := countRows(t, targetDSN, "products"); got != 50 {
		t.Fatalf("after initial migrate: dest products = %d; want 50", got)
	}

	// ---- Phase 2: tamper with the dest. Insert a stray row that
	// would collide on PK if a normal cold-start tried to overwrite,
	// to prove the reset path actually drops + recreates. ----
	applyPGDDL(t, targetDSN, "INSERT INTO products (id, name) VALUES (9999, 'stray-row')")
	if got := countRows(t, targetDSN, "products"); got != 51 {
		t.Fatalf("after tampering: dest products = %d; want 51", got)
	}

	// ---- Phase 3: re-run with ResetTargetData. Should drop the
	// table, clear the state row, and bulk-copy fresh. ----
	resetMig := &Migrator{
		Source: pgEng, Target: pgEng,
		SourceDSN: sourceDSN, TargetDSN: targetDSN,
		MigrationID:     migrationID,
		ResetTargetData: true,
	}
	ctx2, cancel2 := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel2()
	if err := resetMig.Run(ctx2); err != nil {
		t.Fatalf("reset migrate: %v", err)
	}

	// Dest row count matches source exactly — stray row gone, all
	// 50 source rows present.
	if got := countRows(t, targetDSN, "products"); got != 50 {
		t.Errorf("after reset migrate: dest products = %d; want 50", got)
	}
	// Stray id 9999 should no longer exist.
	db, err := sql.Open("pgx", targetDSN)
	if err != nil {
		t.Fatalf("open target: %v", err)
	}
	defer func() { _ = db.Close() }()
	var n int
	if err := db.QueryRowContext(ctx2, "SELECT COUNT(*) FROM products WHERE id = 9999").Scan(&n); err != nil {
		t.Fatalf("query stray row: %v", err)
	}
	if n != 0 {
		t.Errorf("stray row id=9999 still present after reset; got %d", n)
	}

	// State row should reflect the most recent run (phase=complete).
	var phase string
	row := db.QueryRowContext(ctx2,
		"SELECT phase FROM sluice_migrate_state WHERE migration_id = $1", migrationID)
	if err := row.Scan(&phase); err != nil {
		t.Fatalf("read migrate-state: %v", err)
	}
	if phase != "complete" {
		t.Errorf("post-reset migrate-state phase = %q; want complete", phase)
	}
}
