//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// End-to-end integration test for the mappings translation pass.
// Boots a single Postgres container, seeds the source side with a
// JSON column, runs Migrator with a config.Mapping that rewrites
// that column to JSONB, then asserts the target table's column type
// actually came out as jsonb (not the source's plain json).
//
// PG → PG keeps the test focused on the orchestrator's mappings
// wiring rather than cross-engine type translation, which has its
// own coverage in migrate_cross_integration_test.go.

package pipeline

import (
	"context"
	"database/sql"
	"testing"
	"time"

	"github.com/orware/sluice/internal/config"
	"github.com/orware/sluice/internal/engines"

	_ "github.com/orware/sluice/internal/engines/postgres"
)

// TestMigrate_Mappings_PGToPG demonstrates the per-column override
// lands on the target. The seed defines a JSON column on the source;
// the mapping forces it to jsonb on the target. We verify the
// translation took effect by introspecting the target's column type
// directly via information_schema.
func TestMigrate_Mappings_PGToPG(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE events (
			id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			payload JSON NOT NULL
		);
		INSERT INTO events (payload) VALUES ('{"k":"v"}'), ('{"a":1}');
	`
	applyPGDDL(t, sourceDSN, seedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	mig := &Migrator{
		Source:    pgEng,
		Target:    pgEng,
		SourceDSN: sourceDSN,
		TargetDSN: targetDSN,
		Mappings: []config.Mapping{
			{Table: "events", Column: "payload", TargetType: "jsonb"},
		},
	}

	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		t.Fatalf("Migrator.Run: %v", err)
	}

	// Read the target column type back out via information_schema.
	// PG normalises the data_type for jsonb to "jsonb" exactly.
	got := readPGColumnType(t, ctx, targetDSN, "events", "payload")
	if got != "jsonb" {
		t.Errorf("target events.payload data_type = %q; want jsonb (mapping override)", got)
	}

	// Sanity: rows still arrived. Mappings is a schema-rewrite pass;
	// row data should land unchanged.
	if n := countRows(t, targetDSN, "events"); n != 2 {
		t.Errorf("target events row count = %d; want 2", n)
	}
}

// TestMigrate_Mappings_UnknownTable_FailsLoud verifies the strict
// validator surfaces typos rather than silently passing through.
// Operators who fat-finger a table name should see a clear error
// rather than wonder why their override didn't fire.
func TestMigrate_Mappings_UnknownTable_FailsLoud(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()

	applyPGDDL(t, sourceDSN, `
		CREATE TABLE events (id BIGINT PRIMARY KEY, payload JSON NOT NULL);
	`)

	pgEng, _ := engines.Get("postgres")

	mig := &Migrator{
		Source:    pgEng,
		Target:    pgEng,
		SourceDSN: sourceDSN,
		TargetDSN: targetDSN,
		Mappings: []config.Mapping{
			// Typo: "event" instead of "events".
			{Table: "event", Column: "payload", TargetType: "jsonb"},
		},
	}

	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()
	err := mig.Run(ctx)
	if err == nil {
		t.Fatal("expected error for mapping referencing unknown table; got nil")
	}
}

// readPGColumnType returns the information_schema data_type string
// for the named column. Used by the mappings test to assert the
// override took effect.
func readPGColumnType(t *testing.T, ctx context.Context, dsn, table, column string) string {
	t.Helper()
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer func() { _ = db.Close() }()

	queryCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()

	var dataType string
	err = db.QueryRowContext(queryCtx,
		`SELECT data_type
		 FROM information_schema.columns
		 WHERE table_name = $1 AND column_name = $2`,
		table, column,
	).Scan(&dataType)
	if err != nil {
		t.Fatalf("information_schema lookup for %s.%s: %v", table, column, err)
	}
	return dataType
}
