//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// End-to-end integration tests for the ADR-0078 PG→PG raw-copy
// passthrough fast lane (roadmap item 3b(b)). These pins are
// load-bearing in two directions:
//
//   - POSITIVE: the raw lane is actually TAKEN (asserted via the
//     rawCopyTakenObserver seam — a green zero-loss test alone can't
//     distinguish the byte-pipe from the IR fallback) AND the copy is
//     zero-loss (aggregate checksum, not just row count), for BOTH text
//     and binary formats and for the chunked path.
//   - NEGATIVE FALLBACK: with each value transform present
//     (--redact / --type-override / --expr-override / --inject-shard-column)
//     the raw lane is NOT taken AND the transform IS correctly applied on
//     the target — proving the gate prevents a silently-skipped transform
//     (a silent-loss class).

package pipeline

import (
	"context"
	"database/sql"
	"sync"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/config"
	"sluicesync.dev/sluice/internal/engines"
	"sluicesync.dev/sluice/internal/ir"
	"sluicesync.dev/sluice/internal/redact"

	_ "sluicesync.dev/sluice/internal/engines/postgres"
)

// rawCopyRecorder installs the package-level rawCopyTakenObserver seam
// and collects the table names byte-piped through the raw lane. Safe for
// the -race CI run: the observer fires from the copy goroutines.
type rawCopyRecorder struct {
	mu     sync.Mutex
	tables []string
}

func installRawCopyRecorder(t *testing.T) *rawCopyRecorder {
	t.Helper()
	rec := &rawCopyRecorder{}
	prev := rawCopyTakenObserver
	rawCopyTakenObserver = func(table string) {
		rec.mu.Lock()
		rec.tables = append(rec.tables, table)
		rec.mu.Unlock()
	}
	t.Cleanup(func() { rawCopyTakenObserver = prev })
	return rec
}

func (r *rawCopyRecorder) took(table string) bool {
	r.mu.Lock()
	defer r.mu.Unlock()
	for _, tn := range r.tables {
		if tn == table {
			return true
		}
	}
	return false
}

func (r *rawCopyRecorder) any() bool {
	r.mu.Lock()
	defer r.mu.Unlock()
	return len(r.tables) > 0
}

// pgScalar runs a single-value query and returns the int64 result.
func pgScalar(t *testing.T, dsn, query string) int64 {
	t.Helper()
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer func() { _ = db.Close() }()
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	var v sql.NullInt64
	if err := db.QueryRowContext(ctx, query).Scan(&v); err != nil {
		t.Fatalf("scalar %q: %v", query, err)
	}
	return v.Int64
}

// pgString runs a single-value text query.
func pgString(t *testing.T, dsn, query string) string {
	t.Helper()
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer func() { _ = db.Close() }()
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	var s sql.NullString
	if err := db.QueryRowContext(ctx, query).Scan(&s); err != nil {
		t.Fatalf("string %q: %v", query, err)
	}
	return s.String
}

// rawCopyChecksum is the aggregate-checksum invariant the comparison doc
// uses: count + sum(id) + sum(amount) + sum(length(text)) + true-count.
type rawCopyChecksum struct {
	count, sumID, sumAmount, sumTextLen, trueCount int64
}

func rawCopyChecksumOf(t *testing.T, dsn, table string) rawCopyChecksum {
	t.Helper()
	q := func(expr string) int64 {
		return pgScalar(t, dsn, "SELECT COALESCE("+expr+", 0) FROM "+table)
	}
	return rawCopyChecksum{
		count:      q("count(*)"),
		sumID:      q("sum(id)"),
		sumAmount:  q("sum((amount*100)::bigint)"),
		sumTextLen: q("sum(length(event_type))"),
		trueCount:  q("count(*) FILTER (WHERE flag)"),
	}
}

// rawCopySeedDDL builds a table of n rows with the mixed-type shape the
// comparison benchmark uses (bigint PK, varchar, numeric, boolean,
// timestamptz) plus a STORED generated column to pin the
// projection-exclusion invariant.
const rawCopySeedDDL = `
	CREATE TABLE events (
		id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		event_type  VARCHAR(64) NOT NULL,
		amount      NUMERIC(12,2) NOT NULL,
		flag        BOOLEAN NOT NULL,
		created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
		type_upper  TEXT GENERATED ALWAYS AS (upper(event_type)) STORED
	);
	INSERT INTO events (event_type, amount, flag)
	SELECT
		'evt_' || (g % 7),
		(g * 1.5)::numeric(12,2),
		(g % 2 = 0)
	FROM generate_series(1, 500) AS g;
`

func runRawCopyMigrate(t *testing.T, mig *Migrator) {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 120*time.Second)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		t.Fatalf("Migrator.Run: %v", err)
	}
}

func pgEngineOrSkip(t *testing.T) ir.Engine {
	t.Helper()
	eng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}
	return eng
}

// TestRawCopy_PositiveZeroLoss_TextAndBinary is the headline positive:
// the gate holds, the raw lane is TAKEN, and the copy is zero-loss
// (aggregate checksum), for BOTH text and binary formats.
func TestRawCopy_PositiveZeroLoss_TextAndBinary(t *testing.T) {
	for _, tc := range []struct {
		name   string
		format ir.RawCopyFormat
	}{
		{"text", ir.RawCopyText},
		{"binary", ir.RawCopyBinary},
	} {
		t.Run(tc.name, func(t *testing.T) {
			sourceDSN, targetDSN, cleanup := startPostgres(t)
			defer cleanup()
			applyPGDDL(t, sourceDSN, rawCopySeedDDL)

			rec := installRawCopyRecorder(t)
			pg := pgEngineOrSkip(t)
			mig := &Migrator{
				Source: pg, Target: pg,
				SourceDSN: sourceDSN, TargetDSN: targetDSN,
				RawCopyFormat: tc.format,
			}
			runRawCopyMigrate(t, mig)

			if !rec.took("events") {
				t.Fatalf("raw lane was NOT taken for events (format %s); recorded=%v", tc.name, rec.tables)
			}
			src := rawCopyChecksumOf(t, sourceDSN, "events")
			dst := rawCopyChecksumOf(t, targetDSN, "events")
			if src != dst {
				t.Fatalf("checksum mismatch (format %s):\n src=%+v\n dst=%+v", tc.name, src, dst)
			}
			if src.count != 500 {
				t.Fatalf("source count = %d; want 500", src.count)
			}
		})
	}
}

// TestRawCopy_GeneratedColumnRecomputed proves the projection-exclusion
// invariant end-to-end: the source generated column is NOT byte-copied;
// the target recomputes it from its own GENERATED clause. (If the
// exporter had used a bare `COPY tbl TO STDOUT` the generated column
// would have desynced the column list — a hard COPY error — so a clean
// run with a correct recomputed value is the proof.)
func TestRawCopy_GeneratedColumnRecomputed(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()
	applyPGDDL(t, sourceDSN, rawCopySeedDDL)

	rec := installRawCopyRecorder(t)
	pg := pgEngineOrSkip(t)
	runRawCopyMigrate(t, &Migrator{
		Source: pg, Target: pg, SourceDSN: sourceDSN, TargetDSN: targetDSN,
	})
	if !rec.took("events") {
		t.Fatalf("raw lane was NOT taken; recorded=%v", rec.tables)
	}
	// The generated column must equal upper(event_type) on every row.
	mismatches := pgScalar(t, targetDSN,
		"SELECT count(*) FROM events WHERE type_upper <> upper(event_type)")
	if mismatches != 0 {
		t.Fatalf("generated column recompute mismatch on %d rows", mismatches)
	}
	if got := pgString(t, targetDSN, "SELECT type_upper FROM events ORDER BY id LIMIT 1"); got == "" {
		t.Fatalf("generated column is empty on target; recompute did not run")
	}
}

// TestRawCopy_ChunkedZeroLoss forces the within-table parallel-chunk path
// (low --bulk-parallel-min-rows + parallelism) so the raw lane runs
// per-chunk, and asserts complete PK-range coverage + zero loss.
func TestRawCopy_ChunkedZeroLoss(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()
	applyPGDDL(t, sourceDSN, rawCopySeedDDL)

	rec := installRawCopyRecorder(t)
	pg := pgEngineOrSkip(t)
	runRawCopyMigrate(t, &Migrator{
		Source: pg, Target: pg, SourceDSN: sourceDSN, TargetDSN: targetDSN,
		BulkParallelism:     4,
		BulkParallelMinRows: 10, // force the 500-row table to split
	})
	if !rec.took("events") {
		t.Fatalf("raw lane was NOT taken on the chunked path; recorded=%v", rec.tables)
	}
	// More than one chunk byte-piped => the chunked raw path actually ran.
	rec.mu.Lock()
	chunkPipes := len(rec.tables)
	rec.mu.Unlock()
	if chunkPipes < 2 {
		t.Fatalf("expected >=2 raw chunk pipes, got %d (%v)", chunkPipes, rec.tables)
	}
	src := rawCopyChecksumOf(t, sourceDSN, "events")
	dst := rawCopyChecksumOf(t, targetDSN, "events")
	if src != dst {
		t.Fatalf("chunked checksum mismatch:\n src=%+v\n dst=%+v", src, dst)
	}
}

// TestRawCopy_ResumeFallsBack proves the raw lane is NEVER taken on a
// resume run (useFastLoader gate (1) fails → the raw lane, slotted inside
// the fast-loader branch, is unreachable on resume). A second --resume
// pass over an already-complete migration must record zero raw pipes and
// stay zero-loss (the IR resume path is idempotent).
func TestRawCopy_ResumeFallsBack(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()
	applyPGDDL(t, sourceDSN, rawCopySeedDDL)

	pg := pgEngineOrSkip(t)
	// First pass: cold-start, raw lane SHOULD run.
	rec1 := installRawCopyRecorder(t)
	runRawCopyMigrate(t, &Migrator{
		Source: pg, Target: pg, SourceDSN: sourceDSN, TargetDSN: targetDSN,
		MigrationID: "rawcopy-resume",
	})
	if !rec1.took("events") {
		t.Fatalf("first pass: raw lane was NOT taken; recorded=%v", rec1.tables)
	}

	// Second pass: --resume. Raw lane MUST NOT run.
	rec2 := installRawCopyRecorder(t)
	runRawCopyMigrate(t, &Migrator{
		Source: pg, Target: pg, SourceDSN: sourceDSN, TargetDSN: targetDSN,
		MigrationID: "rawcopy-resume",
		Resume:      true,
	})
	if rec2.any() {
		t.Fatalf("resume pass: raw lane MUST NOT run on --resume; recorded=%v", rec2.tables)
	}
	src := rawCopyChecksumOf(t, sourceDSN, "events")
	dst := rawCopyChecksumOf(t, targetDSN, "events")
	if src != dst {
		t.Fatalf("resume checksum mismatch:\n src=%+v\n dst=%+v", src, dst)
	}
}

// --- NEGATIVE FALLBACK: one per transform (the silent-loss guards) ---

// TestRawCopy_FallbackOnRedaction: with --redact, the raw lane must NOT
// be taken AND the redaction must be applied on the target.
func TestRawCopy_FallbackOnRedaction(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()
	applyPGDDL(t, sourceDSN, rawCopySeedDDL)

	rec := installRawCopyRecorder(t)
	red := redact.New()
	red.Set("public", "events", "event_type", redact.Static{Value: "REDACTED"})

	pg := pgEngineOrSkip(t)
	runRawCopyMigrate(t, &Migrator{
		Source: pg, Target: pg, SourceDSN: sourceDSN, TargetDSN: targetDSN,
		Redactor: red,
	})
	if rec.any() {
		t.Fatalf("raw lane MUST NOT run with redaction configured; recorded=%v", rec.tables)
	}
	// Every event_type must be the redacted literal on the target.
	notRedacted := pgScalar(t, targetDSN,
		"SELECT count(*) FROM events WHERE event_type <> 'REDACTED'")
	if notRedacted != 0 {
		t.Fatalf("redaction not applied on %d rows (raw lane silently skipped it?)", notRedacted)
	}
}

// TestRawCopy_FallbackOnTypeOverride: with --type-override, the raw lane
// must NOT run AND the type must be translated on the target.
func TestRawCopy_FallbackOnTypeOverride(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()
	applyPGDDL(t, sourceDSN, rawCopySeedDDL)

	rec := installRawCopyRecorder(t)
	pg := pgEngineOrSkip(t)
	runRawCopyMigrate(t, &Migrator{
		Source: pg, Target: pg, SourceDSN: sourceDSN, TargetDSN: targetDSN,
		// amount numeric(12,2) -> text on the target.
		Mappings: []config.Mapping{{Table: "events", Column: "amount", TargetType: "text"}},
	})
	if rec.any() {
		t.Fatalf("raw lane MUST NOT run with a type override; recorded=%v", rec.tables)
	}
	got := pgString(t, targetDSN,
		"SELECT data_type FROM information_schema.columns WHERE table_name='events' AND column_name='amount'")
	if got != "text" {
		t.Fatalf("type override not applied: amount data_type = %q; want text", got)
	}
}

// TestRawCopy_FallbackOnExprOverride: with --expr-override on a generated
// column, the raw lane must NOT run AND the override must take effect.
func TestRawCopy_FallbackOnExprOverride(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()
	applyPGDDL(t, sourceDSN, rawCopySeedDDL)

	rec := installRawCopyRecorder(t)
	pg := pgEngineOrSkip(t)
	runRawCopyMigrate(t, &Migrator{
		Source: pg, Target: pg, SourceDSN: sourceDSN, TargetDSN: targetDSN,
		// Override the generated column body to lower() instead of upper().
		ExpressionMappings: []config.ExpressionMapping{
			{Table: "events", Column: "type_upper", Expression: "lower(event_type)"},
		},
	})
	if rec.any() {
		t.Fatalf("raw lane MUST NOT run with an expression override; recorded=%v", rec.tables)
	}
	mismatches := pgScalar(t, targetDSN,
		"SELECT count(*) FROM events WHERE type_upper <> lower(event_type)")
	if mismatches != 0 {
		t.Fatalf("expression override not applied on %d rows", mismatches)
	}
}

// TestRawCopy_FallbackOnShardInjection: with --inject-shard-column, the
// raw lane must NOT run AND the discriminator column must be populated.
func TestRawCopy_FallbackOnShardInjection(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()
	applyPGDDL(t, sourceDSN, rawCopySeedDDL)

	rec := installRawCopyRecorder(t)
	pg := pgEngineOrSkip(t)
	runRawCopyMigrate(t, &Migrator{
		Source: pg, Target: pg, SourceDSN: sourceDSN, TargetDSN: targetDSN,
		InjectShardColumn: ShardColumnSpec{Name: "source_shard_id", Value: "shard-a"},
	})
	if rec.any() {
		t.Fatalf("raw lane MUST NOT run with shard injection; recorded=%v", rec.tables)
	}
	unstamped := pgScalar(t, targetDSN,
		"SELECT count(*) FROM events WHERE source_shard_id <> 'shard-a'")
	if unstamped != 0 {
		t.Fatalf("shard column not stamped on %d rows", unstamped)
	}
}
