//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// Integration tests for `--target-schema` (ADR-0031). Boots a single
// Postgres container and verifies:
//
//   - PG → PG migrate with --target-schema=customer_svc lands tables
//     in customer_svc and leaves public empty.
//   - sluice schema preview --target-schema renders DDL prefixed
//     with the schema name.
//   - Stream-id collision detection refuses on different fingerprint.
//
// MySQL refusal is exercised at the unit-test level (no container
// needed; the validateTargetSchema gate runs before any DB I/O).

package pipeline

import (
	"bytes"
	"context"
	"database/sql"
	"errors"
	"fmt"
	"strings"
	"testing"
	"time"

	"github.com/orware/sluice/internal/engines"
	"github.com/orware/sluice/internal/ir"

	_ "github.com/orware/sluice/internal/engines/postgres"
)

// TestMigrate_PG_TargetSchema runs a PG → PG migration with
// --target-schema=customer_svc and verifies the target tables land
// in the named schema, public stays empty, and rows are present.
func TestMigrate_PG_TargetSchema(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE customers (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL,
			plan  VARCHAR(32)  NOT NULL DEFAULT 'free'
		);
		INSERT INTO customers (email, plan) VALUES
			('alice@example.com', 'pro'),
			('bob@example.com',   'free');
	`
	applyPGDDL(t, sourceDSN, seedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	mig := &Migrator{
		Source:       pgEng,
		Target:       pgEng,
		SourceDSN:    sourceDSN,
		TargetDSN:    targetDSN,
		TargetSchema: "customer_svc",
	}
	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		t.Fatalf("Migrator.Run: %v", err)
	}

	// ---- Verify customer_svc.customers exists with the expected
	// row count, and public.customers does NOT exist.
	db, err := sql.Open("pgx", targetDSN)
	if err != nil {
		t.Fatalf("sql.Open: %v", err)
	}
	defer func() { _ = db.Close() }()

	var count int
	if err := db.QueryRowContext(ctx, `SELECT COUNT(*) FROM customer_svc.customers`).Scan(&count); err != nil {
		t.Fatalf("query customer_svc.customers: %v", err)
	}
	if count != 2 {
		t.Errorf("customer_svc.customers row count = %d; want 2", count)
	}

	// public.customers must NOT exist.
	var publicExists bool
	if err := db.QueryRowContext(ctx, `
		SELECT EXISTS (
			SELECT 1 FROM information_schema.tables
			WHERE table_schema = 'public' AND table_name = 'customers'
		)`).Scan(&publicExists); err != nil {
		t.Fatalf("query public schema: %v", err)
	}
	if publicExists {
		t.Errorf("public.customers exists; want it to not exist (target-schema spillover)")
	}

	// Schema customer_svc must exist.
	var schemaExists bool
	if err := db.QueryRowContext(ctx, `
		SELECT EXISTS (SELECT 1 FROM information_schema.schemata WHERE schema_name = 'customer_svc')
	`).Scan(&schemaExists); err != nil {
		t.Fatalf("query schemata: %v", err)
	}
	if !schemaExists {
		t.Errorf("schema customer_svc does not exist; expected auto-create")
	}

	// Verify the row data — alice's email survived the round-trip.
	var email string
	if err := db.QueryRowContext(ctx,
		`SELECT email FROM customer_svc.customers WHERE plan = 'pro'`).Scan(&email); err != nil {
		t.Fatalf("query alice: %v", err)
	}
	if email != "alice@example.com" {
		t.Errorf("alice email = %q; want alice@example.com", email)
	}
}

// TestMigrate_PG_TargetSchema_TwoSources is the load-bearing
// multi-source scenario: two source databases, each migrating into
// its own target-schema on a shared target. Verifies cross-schema
// isolation — neither source's data leaks into the other's namespace
// and both `accounts` tables coexist with their own data.
func TestMigrate_PG_TargetSchema_TwoSources(t *testing.T) {
	customerSrc, targetDSN, cleanup := startPostgres(t)
	defer cleanup()

	// Create a second source database on the same container so we
	// have two distinct sources pointing at one target.
	billingSrc := mustCreateDatabase(t, customerSrc, "billing_db")

	// Both sources have a same-named table to exercise the namespace
	// collision-prevention.
	applyPGDDL(t, customerSrc, `
		CREATE TABLE accounts (
			id     BIGINT PRIMARY KEY,
			source VARCHAR(32) NOT NULL DEFAULT 'customer'
		);
		INSERT INTO accounts (id, source) VALUES (1, 'customer'), (2, 'customer');
	`)
	applyPGDDL(t, billingSrc, `
		CREATE TABLE accounts (
			id     BIGINT PRIMARY KEY,
			source VARCHAR(32) NOT NULL DEFAULT 'billing'
		);
		INSERT INTO accounts (id, source) VALUES (101, 'billing'), (102, 'billing'), (103, 'billing');
	`)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	ctx, cancel := context.WithTimeout(context.Background(), 120*time.Second)
	defer cancel()

	for _, run := range []struct {
		schemaName string
		sourceDSN  string
	}{
		{"customer_svc", customerSrc},
		{"billing_svc", billingSrc},
	} {
		mig := &Migrator{
			Source:       pgEng,
			Target:       pgEng,
			SourceDSN:    run.sourceDSN,
			TargetDSN:    targetDSN,
			TargetSchema: run.schemaName,
		}
		if err := mig.Run(ctx); err != nil {
			t.Fatalf("Migrator.Run schema=%s: %v", run.schemaName, err)
		}
	}

	// ---- Verify both schemas have their own accounts table with
	// the expected source-tagged row counts.
	db, err := sql.Open("pgx", targetDSN)
	if err != nil {
		t.Fatalf("sql.Open: %v", err)
	}
	defer func() { _ = db.Close() }()

	var customerCount, billingCount int
	if err := db.QueryRowContext(ctx, `SELECT COUNT(*) FROM customer_svc.accounts`).Scan(&customerCount); err != nil {
		t.Fatalf("query customer_svc.accounts: %v", err)
	}
	if err := db.QueryRowContext(ctx, `SELECT COUNT(*) FROM billing_svc.accounts`).Scan(&billingCount); err != nil {
		t.Fatalf("query billing_svc.accounts: %v", err)
	}
	if customerCount != 2 {
		t.Errorf("customer_svc.accounts = %d; want 2", customerCount)
	}
	if billingCount != 3 {
		t.Errorf("billing_svc.accounts = %d; want 3", billingCount)
	}

	// Verify per-source data tagging — each schema's data should
	// reflect only its own source.
	var customerSrcTag string
	if err := db.QueryRowContext(ctx,
		`SELECT DISTINCT source FROM customer_svc.accounts`).Scan(&customerSrcTag); err != nil {
		t.Fatalf("query customer source: %v", err)
	}
	if customerSrcTag != "customer" {
		t.Errorf("customer_svc.accounts source = %q; want customer", customerSrcTag)
	}
	var billingSrcTag string
	if err := db.QueryRowContext(ctx,
		`SELECT DISTINCT source FROM billing_svc.accounts`).Scan(&billingSrcTag); err != nil {
		t.Fatalf("query billing source: %v", err)
	}
	if billingSrcTag != "billing" {
		t.Errorf("billing_svc.accounts source = %q; want billing", billingSrcTag)
	}

	// public.accounts must not exist (no spillover from either run).
	var publicExists bool
	if err := db.QueryRowContext(ctx, `
		SELECT EXISTS (
			SELECT 1 FROM information_schema.tables
			WHERE table_schema = 'public' AND table_name = 'accounts'
		)`).Scan(&publicExists); err != nil {
		t.Fatalf("query public schema: %v", err)
	}
	if publicExists {
		t.Errorf("public.accounts exists; multi-source target-schema isolation broken")
	}
}

// TestSchemaPreview_PG_TargetSchema verifies that
// `sluice schema preview --target-schema customer_svc` renders DDL
// prefixed with the schema name. The previewer doesn't write to the
// target — same DSN serves as the writer-construction handle.
func TestSchemaPreview_PG_TargetSchema(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE products (
			id   BIGINT PRIMARY KEY,
			name TEXT   NOT NULL,
			tags TEXT[] NOT NULL DEFAULT '{}'
		);
	`
	applyPGDDL(t, sourceDSN, seedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	var buf bytes.Buffer
	prev := &Previewer{
		Source:       pgEng,
		Target:       pgEng,
		SourceDSN:    sourceDSN,
		TargetDSN:    targetDSN,
		Format:       "text",
		Out:          &buf,
		TargetSchema: "customer_svc",
	}
	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()
	if err := prev.Run(ctx); err != nil {
		t.Fatalf("Previewer.Run: %v", err)
	}

	got := buf.String()
	wants := []string{
		`CREATE TABLE IF NOT EXISTS "customer_svc"."products"`,
	}
	for _, want := range wants {
		if !strings.Contains(got, want) {
			t.Errorf("preview output missing %q; got:\n%s", want, got)
		}
	}
	// Sanity: the preview must NOT default to public when target-schema
	// is set.
	if strings.Contains(got, `"public"."products"`) {
		t.Errorf("preview output references public.products; target-schema override didn't apply:\n%s", got)
	}
}

// TestStreamer_PG_StreamIDCollisionRefused exercises Phase 2 of the
// multi-source story: a `sync start` that reuses a stream-id but
// supplies a different source DSN should refuse loudly.
//
// We don't actually start a streaming run here (that requires
// wal_level=logical and slot creation, which adds container setup
// cost). Instead we exercise the same code path the streamer uses:
// EnsureControlTable + ListStreams + checkStreamIDCollision, with a
// recorded fingerprint for source A and a check against source B.
func TestStreamer_PG_StreamIDCollisionRefused(t *testing.T) {
	sourceA, targetDSN, cleanup := startPostgres(t)
	defer cleanup()
	sourceB := mustCreateDatabase(t, sourceA, "billing_db")

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()

	applier, err := pgEng.OpenChangeApplier(ctx, targetDSN)
	if err != nil {
		t.Fatalf("OpenChangeApplier: %v", err)
	}
	defer closeIf(applier)
	if err := applier.EnsureControlTable(ctx); err != nil {
		t.Fatalf("EnsureControlTable: %v", err)
	}

	// Simulate the first streamer's startup: write a position with
	// source A's fingerprint via WritePosition (which also writes the
	// fingerprint via the SourceFingerprintRecorder surface).
	fingerprintA := fingerprintSourceDSN(sourceA)
	fingerprintB := fingerprintSourceDSN(sourceB)
	if fingerprintA == "" || fingerprintB == "" {
		t.Fatalf("fingerprintSourceDSN returned empty; A=%q B=%q", fingerprintA, fingerprintB)
	}
	if fingerprintA == fingerprintB {
		t.Fatalf("fingerprints match across distinct DBs; A=%q B=%q", fingerprintA, fingerprintB)
	}

	// Use the SourceFingerprintRecorder surface to record source A.
	applySourceFingerprint(applier, fingerprintA)
	if pw, ok := applier.(interface {
		WritePosition(context.Context, string, ir.Position) error
	}); ok {
		if err := pw.WritePosition(ctx, "shared-stream", ir.Position{Engine: "postgres", Token: "tok1"}); err != nil {
			t.Fatalf("WritePosition: %v", err)
		}
	} else {
		t.Skip("applier does not implement PositionWriter; collision check requires a recorded row")
	}

	// Now: simulate the second streamer's startup with source B.
	streams, err := applier.ListStreams(ctx)
	if err != nil {
		t.Fatalf("ListStreams: %v", err)
	}
	checkErr := checkStreamIDCollision("shared-stream", fingerprintB, streams)
	if checkErr == nil {
		t.Fatal("collision check returned nil; want refusal")
	}
	if !errors.Is(checkErr, errStreamIDCollision) {
		t.Errorf("got error %v; want errStreamIDCollision", checkErr)
	}
	if !strings.Contains(checkErr.Error(), "shared-stream") {
		t.Errorf("error %q missing stream-id", checkErr.Error())
	}

	// And: same source DSN should pass the check (warm-resume case).
	if err := checkStreamIDCollision("shared-stream", fingerprintA, streams); err != nil {
		t.Errorf("warm-resume same fingerprint refused: %v", err)
	}
}

// TestMigrate_PG_TargetSchema_EnumColumn is the Bug 45 (v0.25.1)
// regression test: --target-schema against a PG source containing an
// enum-typed column with a literal DEFAULT must produce a schema-
// qualified type ident in CREATE TABLE and a schema-qualified
// `::cast` in the column DEFAULT. Pre-fix, the bare ident landed in
// CREATE TABLE and PG rejected with SQLSTATE 42704 "type does not
// exist" because the per-source namespace isn't in `search_path`.
func TestMigrate_PG_TargetSchema_EnumColumn(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()

	const seedDDL = `
		CREATE TYPE order_status AS ENUM ('pending','paid','shipped');
		CREATE TABLE orders (
			id     BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
			status order_status   NOT NULL DEFAULT 'pending',
			total  NUMERIC(10,2)  NOT NULL
		);
		INSERT INTO orders (status, total) VALUES
			('pending', 9.99),
			('paid',    19.99),
			('shipped', 29.99);
	`
	applyPGDDL(t, sourceDSN, seedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	mig := &Migrator{
		Source:       pgEng,
		Target:       pgEng,
		SourceDSN:    sourceDSN,
		TargetDSN:    targetDSN,
		TargetSchema: "customer_svc",
	}
	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		t.Fatalf("Migrator.Run with --target-schema and enum column: %v", err)
	}

	db, err := sql.Open("pgx", targetDSN)
	if err != nil {
		t.Fatalf("sql.Open: %v", err)
	}
	defer func() { _ = db.Close() }()

	// Bulk-copied rows landed.
	var count int
	if err := db.QueryRowContext(ctx, `SELECT COUNT(*) FROM customer_svc.orders`).Scan(&count); err != nil {
		t.Fatalf("count: %v", err)
	}
	if count != 3 {
		t.Errorf("customer_svc.orders count = %d; want 3", count)
	}

	// The enum type lives in the per-source namespace. Its NAME is the
	// preserved source type name `order_status` (Bug 19c, v0.69.0): a
	// same-engine PG→PG migration carries the source enum type name
	// verbatim rather than synthesizing `<table>_<col>_enum`. The
	// load-bearing assertion here is the *namespace* qualification
	// (n.nspname = 'customer_svc'); the name is `order_status` per the
	// seed `CREATE TYPE order_status`.
	var typExists bool
	if err := db.QueryRowContext(ctx, `
		SELECT EXISTS (
			SELECT 1
			FROM   pg_type t
			JOIN   pg_namespace n ON n.oid = t.typnamespace
			WHERE  n.nspname = 'customer_svc'
			  AND  t.typname = 'order_status'
		)`).Scan(&typExists); err != nil {
		t.Fatalf("query enum type: %v", err)
	}
	if !typExists {
		t.Error("customer_svc.order_status does not exist; CREATE TYPE didn't qualify to the per-source namespace")
	}

	// The column references the qualified type — INSERT against the
	// enum column with the DEFAULT must round-trip cleanly. This is
	// the load-bearing assertion: pre-fix, this INSERT crashes with
	// SQLSTATE 42704 because the column-type ident wasn't qualified
	// and the DEFAULT cast pointed at a bare type that search_path
	// can't resolve.
	if _, err := db.ExecContext(ctx,
		`INSERT INTO customer_svc.orders (total) VALUES (49.99)`,
	); err != nil {
		t.Fatalf("INSERT into customer_svc.orders (with default 'pending'::enum cast): %v", err)
	}

	// The DEFAULT fired and produced the canonical 'pending' enum
	// value via the qualified cast.
	var status string
	if err := db.QueryRowContext(ctx,
		`SELECT status::TEXT FROM customer_svc.orders WHERE total = 49.99`).Scan(&status); err != nil {
		t.Fatalf("read status: %v", err)
	}
	if status != "pending" {
		t.Errorf("status = %q; want pending (DEFAULT cast)", status)
	}
}

// mustCreateDatabase creates an additional database on the
// container's PG instance, returning a DSN pointing at it. Used by
// the multi-source tests to simulate two distinct source DBs sharing
// one PG cluster.
func mustCreateDatabase(t *testing.T, baseDSN, dbName string) string {
	t.Helper()
	db, err := sql.Open("pgx", baseDSN)
	if err != nil {
		t.Fatalf("sql.Open: %v", err)
	}
	defer func() { _ = db.Close() }()
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	if _, err := db.ExecContext(ctx, fmt.Sprintf("CREATE DATABASE %s", dbName)); err != nil {
		t.Fatalf("create database %q: %v", dbName, err)
	}
	dsn, err := buildPGDSN(baseDSN, dbName)
	if err != nil {
		t.Fatalf("build DSN for %q: %v", dbName, err)
	}
	return dsn
}
