//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// Shape A end-to-end integration test — closes the v0.72.0 gap that
// allowed Bug 80 (reader-projection regression) and Bug 81 (preflight
// no-op) to ship. The Shape A unit-tests pinned individual pieces;
// nothing exercised the full migrate path with a populated target.
// "Validate end-to-end before building more" — this test is the
// floor that should have caught both bugs pre-release.

package pipeline

import (
	"context"
	"database/sql"
	"errors"
	"strings"
	"testing"
	"time"

	"github.com/orware/sluice/internal/engines"
	"github.com/orware/sluice/internal/ir"

	_ "github.com/orware/sluice/internal/engines/mysql"
	_ "github.com/orware/sluice/internal/engines/postgres"
)

// Bug 80 pin: PG → PG Shape A bulk-copy lands non-zero rows on the
// target. Pre-v0.72.1 the SELECT projection included the
// SluiceInjected discriminator column → SQLSTATE 42703 on the source.
func TestMigrate_PG_ShapeA_Bug80_BulkCopyLandsRows(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()

	applyPGDDL(t, sourceDSN, `
		CREATE TABLE widgets (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name TEXT NOT NULL,
			price NUMERIC(10,2)
		);
		INSERT INTO widgets (name, price) VALUES
			('alpha', 1.00), ('beta', 2.50), ('gamma', 3.75);
	`)

	pgEng, _ := engines.Get("postgres")
	mig := &Migrator{
		Source:    pgEng,
		Target:    pgEng,
		SourceDSN: sourceDSN,
		TargetDSN: targetDSN,
		InjectShardColumn: ShardColumnSpec{
			Name:  "source_shard_id",
			Value: "shard_a",
		},
	}
	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		t.Fatalf("Migrator.Run: %v (Bug 80: reader builds SELECT from schema-mutated table → "+
			"SluiceInjected column queried from source, crashes with SQLSTATE 42703)", err)
	}

	tgtDB, err := sql.Open("pgx", targetDSN)
	if err != nil {
		t.Fatalf("open target: %v", err)
	}
	defer func() { _ = tgtDB.Close() }()

	var n int
	if err := tgtDB.QueryRowContext(ctx, "SELECT COUNT(*) FROM widgets").Scan(&n); err != nil {
		t.Fatalf("count widgets: %v", err)
	}
	if n != 3 {
		t.Fatalf("target rows = %d; want 3 (Bug 80 pin — bulk-copy must land rows, not crash mid-read)", n)
	}

	// All target rows must carry the stamped discriminator.
	var distinctShards int
	if err := tgtDB.QueryRowContext(ctx,
		"SELECT COUNT(DISTINCT source_shard_id) FROM widgets").Scan(&distinctShards); err != nil {
		t.Fatalf("distinct shards: %v", err)
	}
	if distinctShards != 1 {
		t.Errorf("distinct source_shard_id = %d; want 1 (all rows must carry the stamped value)", distinctShards)
	}
	var stamped string
	if err := tgtDB.QueryRowContext(ctx,
		"SELECT DISTINCT source_shard_id FROM widgets").Scan(&stamped); err != nil {
		t.Fatalf("distinct value: %v", err)
	}
	if stamped != "shard_a" {
		t.Errorf("stamped shard_id = %q; want %q", stamped, "shard_a")
	}
}

// Bug 81 pin: PG → PG Shape A populated-target preflight refuses
// loudly when the incoming shard VALUE is already present on the
// target. Pre-v0.72.1 no engine implemented shardPreflightProber so
// the preflight type-assertion fell through to a silent return-nil;
// post-fix the PG RowWriter implements it and the preflight emits the
// errShardConsolidationRefused sentinel.
func TestMigrate_PG_ShapeA_Bug81_PreflightRefusesOnShardCollision(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()

	// Source: stock table with rows.
	applyPGDDL(t, sourceDSN, `
		CREATE TABLE widgets (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name TEXT NOT NULL
		);
		INSERT INTO widgets (name) VALUES ('alpha'), ('beta');
	`)

	// Target: pre-existing Shape A table with shard_a already loaded.
	// The preflight should refuse on the value-collision check.
	applyPGDDL(t, targetDSN, `
		CREATE TABLE widgets (
			id BIGINT NOT NULL,
			name TEXT NOT NULL,
			source_shard_id VARCHAR(64) NOT NULL,
			PRIMARY KEY (source_shard_id, id)
		);
		INSERT INTO widgets (id, name, source_shard_id) VALUES
			(1, 'pre-existing-alpha', 'shard_a');
	`)

	pgEng, _ := engines.Get("postgres")
	mig := &Migrator{
		Source:    pgEng,
		Target:    pgEng,
		SourceDSN: sourceDSN,
		TargetDSN: targetDSN,
		InjectShardColumn: ShardColumnSpec{
			Name:  "source_shard_id",
			Value: "shard_a", // SAME as already-loaded → must refuse
		},
	}
	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()
	err := mig.Run(ctx)
	if err == nil {
		t.Fatal("Migrator.Run with colliding shard VALUE returned nil — Bug 81 regression " +
			"(populated-target preflight must refuse loudly; pre-v0.72.1 it was a silent no-op)")
	}
	if !errors.Is(err, errShardConsolidationRefused) {
		t.Errorf("expected errShardConsolidationRefused; got %v", err)
	}
	if !strings.Contains(err.Error(), "shard_a") {
		t.Errorf("refusal message must name the colliding VALUE; got %v", err)
	}
}

// Bug 81 pin: PG → PG Shape A populated-target with a FRESH VALUE
// (sibling-shard load) MUST succeed. Regression guard against an
// overly-broad refusal.
func TestMigrate_PG_ShapeA_Bug81_PreflightPassesOnFreshShardValue(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()

	applyPGDDL(t, sourceDSN, `
		CREATE TABLE widgets (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name TEXT NOT NULL
		);
		INSERT INTO widgets (name) VALUES ('alpha'), ('beta');
	`)

	// Target: pre-existing Shape A schema + sibling-shard rows. The
	// new shard's preflight passes (different VALUE), bulk-copy lands.
	applyPGDDL(t, targetDSN, `
		CREATE TABLE widgets (
			id BIGINT NOT NULL,
			name TEXT NOT NULL,
			source_shard_id VARCHAR(64) NOT NULL,
			PRIMARY KEY (source_shard_id, id)
		);
		INSERT INTO widgets (id, name, source_shard_id) VALUES
			(1, 'sibling-alpha', 'shard_a'),
			(2, 'sibling-beta', 'shard_a');
	`)

	pgEng, _ := engines.Get("postgres")
	mig := &Migrator{
		Source:    pgEng,
		Target:    pgEng,
		SourceDSN: sourceDSN,
		TargetDSN: targetDSN,
		InjectShardColumn: ShardColumnSpec{
			Name:  "source_shard_id",
			Value: "shard_b", // different from shard_a → must succeed
		},
	}
	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		t.Fatalf("Migrator.Run with FRESH shard VALUE returned %v; want nil "+
			"(sibling-shard load must succeed; Bug 81 prober must not over-refuse)", err)
	}

	// Verify both shards co-exist on the target.
	tgtDB, err := sql.Open("pgx", targetDSN)
	if err != nil {
		t.Fatalf("open target: %v", err)
	}
	defer func() { _ = tgtDB.Close() }()

	rows, err := tgtDB.QueryContext(ctx, `
		SELECT source_shard_id, COUNT(*)
		FROM widgets GROUP BY source_shard_id ORDER BY source_shard_id`)
	if err != nil {
		t.Fatalf("count by shard: %v", err)
	}
	defer func() { _ = rows.Close() }()

	got := map[string]int{}
	for rows.Next() {
		var shard string
		var n int
		if err := rows.Scan(&shard, &n); err != nil {
			t.Fatalf("scan: %v", err)
		}
		got[shard] = n
	}
	if got["shard_a"] != 2 {
		t.Errorf("shard_a target rows = %d; want 2 (pre-existing sibling-shard rows preserved)", got["shard_a"])
	}
	if got["shard_b"] != 2 {
		t.Errorf("shard_b target rows = %d; want 2 (new shard's rows landed)", got["shard_b"])
	}
}

// Cross-check: the Bug 80 fix must also work on MySQL. Same shape as
// the PG test above; non-zero rows on the target prove the SELECT
// projection no longer chokes on the source.
func TestMigrate_MySQL_ShapeA_Bug80_BulkCopyLandsRows(t *testing.T) {
	_ = ir.Boolean{} // import witness; avoid unused
	sourceDSN, targetDSN, cleanup := startMySQL(t)
	defer cleanup()

	// Use a non-AUTO_INCREMENT PK to avoid the separate AUTO_INCREMENT
	// demotion issue documented as a follow-up (BUG-CATALOG line 305).
	applyMySQLDDL(t, sourceDSN, `
		CREATE TABLE widgets (
			id BIGINT NOT NULL PRIMARY KEY,
			name VARCHAR(64) NOT NULL,
			price DECIMAL(10,2)
		);
		INSERT INTO widgets (id, name, price) VALUES
			(1, 'alpha', 1.00), (2, 'beta', 2.50), (3, 'gamma', 3.75);
	`)

	myEng, _ := engines.Get("mysql")
	mig := &Migrator{
		Source:    myEng,
		Target:    myEng,
		SourceDSN: sourceDSN,
		TargetDSN: targetDSN,
		InjectShardColumn: ShardColumnSpec{
			Name:  "source_shard_id",
			Value: "shard_a",
		},
	}
	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		t.Fatalf("Migrator.Run: %v (Bug 80 MySQL side — Error 1054 'Unknown column ... in field list')", err)
	}

	tgtDB, err := sql.Open("mysql", targetDSN)
	if err != nil {
		t.Fatalf("open target: %v", err)
	}
	defer func() { _ = tgtDB.Close() }()

	var n int
	if err := tgtDB.QueryRowContext(ctx, "SELECT COUNT(*) FROM widgets").Scan(&n); err != nil {
		t.Fatalf("count: %v", err)
	}
	if n != 3 {
		t.Fatalf("target rows = %d; want 3 (MySQL Bug 80 pin)", n)
	}
}
