//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// Multi-schema generated-column regression pin.
//
// This guards the class of bug fixed in planetscale/heroku-migrator#11:
// that tool detected PostgreSQL generated columns by scanning only the
// `public` schema, so a generated column in any other schema slipped
// through and broke the (Bucardo) COPY ("Generated columns cannot be
// used in COPY"). sluice's PG schema reader is parameterized by schema
// (every catalog query is `... WHERE table_schema = $1` / `n.nspname =
// $1`, where $1 is the schema actually being migrated — see
// schema_reader.go), so the generated-column flag is read in the SAME
// per-schema pass as the column itself and can never cover a different
// schema set than the copy. This test makes that property explicit on a
// NON-public source schema: the generated column must be detected,
// dropped from the bulk-copy column list (PG rejects writes to a
// generated column, SQLSTATE 428C9), recreated as GENERATED on the
// target, and recompute correctly — end to end, in a schema that is not
// `public`.

package pipeline

import (
	"context"
	"database/sql"
	"net/url"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/engines"

	_ "sluicesync.dev/sluice/internal/engines/mysql"
	_ "sluicesync.dev/sluice/internal/engines/postgres"
)

// withSchemaParam returns dsn with sluice's `schema=<name>` query
// parameter set (the param the PG engine uses to bind the schema it
// reads/writes; see postgres/connect.go parseDSN). Test DSNs from
// startPostgres are the URI form, so net/url is the robust way to add
// it without assuming the existing query shape.
func withSchemaParam(t *testing.T, dsn, schema string) string {
	t.Helper()
	u, err := url.Parse(dsn)
	if err != nil {
		t.Fatalf("parse dsn: %v", err)
	}
	q := u.Query()
	q.Set("schema", schema)
	u.RawQuery = q.Encode()
	return u.String()
}

// TestMigrate_PG_Generated_NonPublicSchema is the multi-schema
// generated-column pin (heroku-migrator #11 class). A STORED generated
// column in a non-`public` source schema must round-trip as a real
// GENERATED column on the target and recompute on update.
func TestMigrate_PG_Generated_NonPublicSchema(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()

	const schemaName = "inventory"

	// Seed the generated column in a NON-public schema. A second,
	// plain table in the same schema rides along to prove the
	// non-generated columns still copy normally beside the dropped one.
	const seedDDL = `
		CREATE TABLE invoices (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			qty   INTEGER         NOT NULL,
			price NUMERIC(10, 2)  NOT NULL,
			total NUMERIC(20, 2)  GENERATED ALWAYS AS (qty * price) STORED
		);
		INSERT INTO invoices (qty, price) VALUES
			(2, 10.00),
			(3, 5.50);
	`
	applyPGDDLInSchema(t, sourceDSN, schemaName, seedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	mig := &Migrator{
		Source:       pgEng,
		Target:       pgEng,
		SourceDSN:    withSchemaParam(t, sourceDSN, schemaName),
		TargetDSN:    targetDSN,
		TargetSchema: schemaName,
	}

	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		t.Fatalf("Migrator.Run: %v", err)
	}

	tgt, err := sql.Open("pgx", targetDSN)
	if err != nil {
		t.Fatalf("open target: %v", err)
	}
	defer func() { _ = tgt.Close() }()

	// 1. The generated column must have been DETECTED in the non-public
	//    schema and recreated as GENERATED on the target — the direct
	//    refutation of the public-only blind spot.
	var isGenerated, genExpr string
	const checkQ = `
		SELECT is_generated, COALESCE(generation_expression, '')
		FROM   information_schema.columns
		WHERE  table_schema = $1
		  AND  table_name   = 'invoices'
		  AND  column_name  = 'total'`
	if err := tgt.QueryRowContext(ctx, checkQ, schemaName).Scan(&isGenerated, &genExpr); err != nil {
		t.Fatalf("query target is_generated in schema %q: %v", schemaName, err)
	}
	if isGenerated != "ALWAYS" || genExpr == "" {
		t.Fatalf("target %s.invoices.total: is_generated=%q expr=%q; want ALWAYS + non-empty",
			schemaName, isGenerated, genExpr)
	}

	// 2. The bulk-copied rows must have recomputed via the target's
	//    GENERATED clause (qty*price), proving the column was dropped
	//    from the copy column list rather than written directly.
	assertQualifiedInvoiceTotals(t, ctx, tgt, schemaName, []float64{20.00, 16.50})

	// 3. A post-migration update to a dependent column must recompute,
	//    confirming a live GENERATED column (not a frozen copied value).
	if _, err := tgt.ExecContext(ctx,
		"UPDATE "+schemaName+".invoices SET qty = 5 WHERE id = 1"); err != nil {
		t.Fatalf("update target: %v", err)
	}
	assertQualifiedInvoiceTotals(t, ctx, tgt, schemaName, []float64{50.00, 16.50})

	// 4. public must be empty of invoices — the migration must not have
	//    leaked the non-public table into public (search-path spillover).
	var publicExists bool
	if err := tgt.QueryRowContext(ctx, `
		SELECT EXISTS (
			SELECT 1 FROM information_schema.tables
			WHERE table_schema = 'public' AND table_name = 'invoices'
		)`).Scan(&publicExists); err != nil {
		t.Fatalf("query public schema: %v", err)
	}
	if publicExists {
		t.Errorf("public.invoices exists; want the table only in %q (schema spillover)", schemaName)
	}
}

// assertQualifiedInvoiceTotals is the schema-qualified analog of
// assertInvoiceTotals — it reads `<schema>.invoices.total` explicitly
// rather than relying on the connection's search_path (sluice's
// `schema=` DSN param is stripped before the driver, so a raw sql.Open
// does not put the schema on the path).
func assertQualifiedInvoiceTotals(t *testing.T, ctx context.Context, db *sql.DB, schema string, want []float64) {
	t.Helper()
	rows, err := db.QueryContext(ctx, "SELECT total FROM "+schema+".invoices ORDER BY id")
	if err != nil {
		t.Fatalf("select totals: %v", err)
	}
	defer func() { _ = rows.Close() }()

	var got []float64
	for rows.Next() {
		var totalStr string
		if err := rows.Scan(&totalStr); err != nil {
			t.Fatalf("scan total: %v", err)
		}
		got = append(got, parseDecimal(t, totalStr))
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows iteration: %v", err)
	}
	if len(got) != len(want) {
		t.Fatalf("got %d rows; want %d (got=%v)", len(got), len(want), got)
	}
	for i := range want {
		const eps = 0.001
		if diff := got[i] - want[i]; diff < -eps || diff > eps {
			t.Errorf("row %d: total = %v; want %v", i, got[i], want[i])
		}
	}
}
