//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// PG → PG pg_trgm passthrough integration tests (ADR-0032 Tier 2 lite).
// pg_trgm is "operator-class only" — no new column types, just
// `gin_trgm_ops` / `gist_trgm_ops` operator classes on existing
// `text` / `varchar` columns. The test boots a stock postgres:16
// container (pg_trgm ships in the standard contrib bundle), runs
// CREATE EXTENSION on both source and target, exercises the migrate
// path with a `CREATE INDEX ... USING GIN (col gin_trgm_ops)` index,
// and verifies the round-trip preserves the index's operator class
// on the target.

package pipeline

import (
	"context"
	"database/sql"
	"strings"
	"testing"
	"time"

	"github.com/orware/sluice/internal/engines"
	"github.com/orware/sluice/internal/ir"

	_ "github.com/orware/sluice/internal/engines/postgres"

	"github.com/testcontainers/testcontainers-go"
	pgtc "github.com/testcontainers/testcontainers-go/modules/postgres"
)

// startPostgresWithTrgm boots a stock postgres:16 container, creates
// the source and target databases, and runs CREATE EXTENSION pg_trgm
// on both. pg_trgm ships in the standard postgres contrib bundle so
// no special image is required — the postgres:16 image CI already
// pre-pulls works as-is.
//
// enableOnTarget mirrors the pgvector helper's flag: set true for
// the happy-path round-trip, false to exercise the
// target-missing-extension preflight refusal.
func startPostgresWithTrgm(t *testing.T, enableOnTarget bool) (sourceDSN, targetDSN string, cleanup func()) {
	t.Helper()
	testcontainers.SkipIfProviderIsNotHealthy(t)

	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Minute)
	defer cancel()

	container, err := pgtc.Run(ctx,
		"postgres:16",
		pgtc.WithDatabase("source_db"),
		pgtc.WithUsername("test"),
		pgtc.WithPassword("test"),
		pgtc.BasicWaitStrategies(),
	)
	if err != nil {
		t.Fatalf("start container: %v", err)
	}

	terminate := func() {
		shutdown, c := context.WithTimeout(context.Background(), 30*time.Second)
		defer c()
		_ = container.Terminate(shutdown)
	}

	srcConn, err := container.ConnectionString(ctx, "sslmode=disable")
	if err != nil {
		terminate()
		t.Fatalf("connection string: %v", err)
	}

	db, err := sql.Open("pgx", srcConn)
	if err != nil {
		terminate()
		t.Fatalf("open: %v", err)
	}
	defer func() { _ = db.Close() }()

	if _, err := db.ExecContext(ctx, "CREATE DATABASE target_db"); err != nil {
		terminate()
		t.Fatalf("create target_db: %v", err)
	}

	tgtConn, err := buildPGDSN(srcConn, "target_db")
	if err != nil {
		terminate()
		t.Fatalf("build target DSN: %v", err)
	}

	if _, err := db.ExecContext(ctx, "CREATE EXTENSION IF NOT EXISTS pg_trgm"); err != nil {
		terminate()
		t.Fatalf("CREATE EXTENSION pg_trgm on source: %v", err)
	}

	if enableOnTarget {
		tgtDB, err := sql.Open("pgx", tgtConn)
		if err != nil {
			terminate()
			t.Fatalf("open target: %v", err)
		}
		defer func() { _ = tgtDB.Close() }()
		if _, err := tgtDB.ExecContext(ctx, "CREATE EXTENSION IF NOT EXISTS pg_trgm"); err != nil {
			terminate()
			t.Fatalf("CREATE EXTENSION pg_trgm on target: %v", err)
		}
	}

	return srcConn, tgtConn, terminate
}

// TestMigrate_PG_PgTrgm_GinIndexPassthrough exercises the load-bearing
// pg_trgm path: a `CREATE INDEX ... USING GIN (body gin_trgm_ops)`
// index round-trips through PG → PG migrate when the operator opts
// into --enable-pg-extension pg_trgm and both sides have the
// extension installed. The ground truth is a pg_index/pg_opclass
// query on the target verifying the index exists with the expected
// access method AND operator class — without the per-opclass
// passthrough this PR adds, the index would land on the target
// with the GIN AM but no opclass, and CREATE INDEX would fail at
// emit-time (gin has no default opclass for text).
func TestMigrate_PG_PgTrgm_GinIndexPassthrough(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresWithTrgm(t, true)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE documents (
			id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			body TEXT NOT NULL
		);

		INSERT INTO documents (body) VALUES
			('the quick brown fox'),
			('jumps over the lazy dog'),
			('pack my box with five dozen liquor jugs');

		CREATE INDEX documents_body_trgm
		    ON documents USING GIN (body gin_trgm_ops);
	`
	applyPGDDL(t, sourceDSN, seedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	mig := &Migrator{
		Source:              pgEng,
		Target:              pgEng,
		SourceDSN:           sourceDSN,
		TargetDSN:           targetDSN,
		EnabledPGExtensions: []string{"pg_trgm"},
	}

	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		t.Fatalf("Migrator.Run: %v", err)
	}

	tgtDB, err := sql.Open("pgx", targetDSN)
	if err != nil {
		t.Fatalf("open target: %v", err)
	}
	defer func() { _ = tgtDB.Close() }()

	// Ground truth — query pg_index + pg_opclass on the target. The
	// load-bearing assertion is `opcname = 'gin_trgm_ops'`: without
	// the per-opclass capture this PR adds, the index would either
	// fail to create (gin has no default opclass for text) or land
	// with the wrong opclass. Either way the SELECT below would
	// surface the regression cleanly.
	const idxQuery = `
		SELECT am.amname, opc.opcname
		FROM   pg_index ix
		JOIN   pg_class i  ON i.oid = ix.indexrelid
		JOIN   pg_class cl ON cl.oid = ix.indrelid
		JOIN   pg_am    am ON am.oid = i.relam
		JOIN   LATERAL unnest(ix.indclass) WITH ORDINALITY AS uc(opcoid, ord) ON TRUE
		JOIN   pg_opclass opc ON opc.oid = uc.opcoid
		WHERE  cl.relname = 'documents'
		  AND  i.relname  = 'documents_body_trgm'`
	var (
		amname  string
		opcname string
	)
	if err := tgtDB.QueryRowContext(ctx, idxQuery).Scan(&amname, &opcname); err != nil {
		t.Fatalf("index method/opclass query: %v", err)
	}
	if amname != "gin" {
		t.Errorf("target index method = %q; want gin", amname)
	}
	if opcname != "gin_trgm_ops" {
		t.Errorf("target index opclass = %q; want gin_trgm_ops", opcname)
	}

	// Row count check — bulk copy should have moved 3 rows.
	var n int
	if err := tgtDB.QueryRowContext(ctx, "SELECT COUNT(*) FROM documents").Scan(&n); err != nil {
		t.Fatalf("count: %v", err)
	}
	if n != 3 {
		t.Errorf("target documents rows = %d; want 3", n)
	}

	// Sanity check — the trigram operator should fire on the target.
	// `%` is the trigram-similarity operator; without the GIN +
	// gin_trgm_ops index it would still work as a sequential scan,
	// but the EXPLAIN below proves the index is being used.
	var planText string
	if err := tgtDB.QueryRowContext(ctx,
		"EXPLAIN (FORMAT TEXT) SELECT id FROM documents WHERE body % 'quick brown'").
		Scan(&planText); err != nil {
		// EXPLAIN may return multiple rows; falling back to a simpler
		// existence check rather than failing the test on plan-shape
		// quirks across PG versions.
		t.Logf("EXPLAIN failed (non-fatal): %v", err)
	} else {
		t.Logf("trigram-search plan: %s", planText)
	}

	// Round-trip the IR through the target reader to confirm the
	// IndexColumn.OperatorClass field surfaces from the rebuilt
	// schema. Mirrors the pgvector test's "read-back IR" assertion.
	pgRdr, err := pgEng.OpenSchemaReader(ctx, targetDSN)
	if err != nil {
		t.Fatalf("OpenSchemaReader on target: %v", err)
	}
	defer closeIf(pgRdr)
	if aware, ok := pgRdr.(ir.ExtensionAware); ok {
		if err := aware.EnableExtensions(ctx, []string{"pg_trgm"}); err != nil {
			t.Fatalf("EnableExtensions on target reader: %v", err)
		}
	}
	got, err := pgRdr.ReadSchema(ctx)
	if err != nil {
		t.Fatalf("ReadSchema on target: %v", err)
	}
	docs := findTable(got, "documents")
	if docs == nil {
		t.Fatal("target has no documents table")
	}
	var foundTrgm bool
	for _, idx := range docs.Indexes {
		for _, c := range idx.Columns {
			if c.OperatorClass == "gin_trgm_ops" {
				foundTrgm = true
				if c.Column != "body" {
					t.Errorf("trgm index column = %q; want body", c.Column)
				}
			}
		}
	}
	if !foundTrgm {
		t.Errorf("did not find gin_trgm_ops on documents indexes; got %+v", docs.Indexes)
	}
}

// TestMigrate_PG_PgTrgm_GistIndexPassthrough mirrors the GIN test for
// the GiST flavour. pg_trgm supports both AMs; the catalog declares
// both opclasses and the round-trip must preserve either.
func TestMigrate_PG_PgTrgm_GistIndexPassthrough(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresWithTrgm(t, true)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE documents (
			id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			body TEXT NOT NULL
		);

		INSERT INTO documents (body) VALUES
			('the quick brown fox'),
			('hello world');

		CREATE INDEX documents_body_trgm_gist
		    ON documents USING GIST (body gist_trgm_ops);
	`
	applyPGDDL(t, sourceDSN, seedDDL)

	pgEng, _ := engines.Get("postgres")
	mig := &Migrator{
		Source:              pgEng,
		Target:              pgEng,
		SourceDSN:           sourceDSN,
		TargetDSN:           targetDSN,
		EnabledPGExtensions: []string{"pg_trgm"},
	}

	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		t.Fatalf("Migrator.Run: %v", err)
	}

	tgtDB, err := sql.Open("pgx", targetDSN)
	if err != nil {
		t.Fatalf("open target: %v", err)
	}
	defer func() { _ = tgtDB.Close() }()

	const idxQuery = `
		SELECT am.amname, opc.opcname
		FROM   pg_index ix
		JOIN   pg_class i  ON i.oid = ix.indexrelid
		JOIN   pg_class cl ON cl.oid = ix.indrelid
		JOIN   pg_am    am ON am.oid = i.relam
		JOIN   LATERAL unnest(ix.indclass) WITH ORDINALITY AS uc(opcoid, ord) ON TRUE
		JOIN   pg_opclass opc ON opc.oid = uc.opcoid
		WHERE  cl.relname = 'documents'
		  AND  i.relname  = 'documents_body_trgm_gist'`
	var (
		amname  string
		opcname string
	)
	if err := tgtDB.QueryRowContext(ctx, idxQuery).Scan(&amname, &opcname); err != nil {
		t.Fatalf("index method/opclass query: %v", err)
	}
	if amname != "gist" {
		t.Errorf("target index method = %q; want gist", amname)
	}
	if opcname != "gist_trgm_ops" {
		t.Errorf("target index opclass = %q; want gist_trgm_ops", opcname)
	}
}

// TestMigrate_PG_PgTrgm_NotEnabled_DropsOpclass pins the loud-failure
// shape when --enable-pg-extension pg_trgm is NOT set. The schema
// reader's per-opclass gate (extensionOperatorClassEnabled) only
// fires when the operator opted into the extension; without that
// opt-in, the opclass is dropped from the IR and the writer emits
// the index without it. PG then rejects the CREATE INDEX with
// "operator class \"<x>\" does not exist for access method \"<y>\""
// — which on the index-creation phase surfaces as a Migrator.Run
// error, preserving the loud-failure tenet.
func TestMigrate_PG_PgTrgm_NotEnabled_DropsOpclass(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresWithTrgm(t, true)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE documents (
			id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			body TEXT NOT NULL
		);

		CREATE INDEX documents_body_trgm
		    ON documents USING GIN (body gin_trgm_ops);
	`
	applyPGDDL(t, sourceDSN, seedDDL)

	pgEng, _ := engines.Get("postgres")
	mig := &Migrator{
		Source:    pgEng,
		Target:    pgEng,
		SourceDSN: sourceDSN,
		TargetDSN: targetDSN,
		// Deliberately NO EnabledPGExtensions — the opt-in tenet
		// means a pg_trgm-using source without the flag must fail
		// loudly rather than silently dropping the opclass and
		// emitting a useless index.
	}

	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()
	err := mig.Run(ctx)
	if err == nil {
		t.Fatal("Migrator.Run = nil; want failure when opclass dropped from IR")
	}
	// PG's error: `data type text has no default operator class for
	// access method "gin"`. Be lenient on exact wording — assert on
	// the load-bearing fragments.
	msg := strings.ToLower(err.Error())
	if !strings.Contains(msg, "operator class") && !strings.Contains(msg, "default") {
		t.Errorf("err = %v; want mention of \"operator class\" / \"default\"", err)
	}
}

// TestMigrate_PG_PgTrgm_TargetMissing_RefusedAtPreflight pins the
// loud-failure default on a target that doesn't have pg_trgm
// installed. Mirrors the pgvector preflight refusal.
func TestMigrate_PG_PgTrgm_TargetMissing_RefusedAtPreflight(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresWithTrgm(t, false)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE documents (
			id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			body TEXT NOT NULL
		);
	`
	applyPGDDL(t, sourceDSN, seedDDL)

	pgEng, _ := engines.Get("postgres")
	mig := &Migrator{
		Source:              pgEng,
		Target:              pgEng,
		SourceDSN:           sourceDSN,
		TargetDSN:           targetDSN,
		EnabledPGExtensions: []string{"pg_trgm"},
	}

	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()
	err := mig.Run(ctx)
	if err == nil {
		t.Fatal("Migrator.Run = nil; want preflight refusal")
	}
	if !strings.Contains(err.Error(), "pg_trgm") {
		t.Errorf("err = %v; want mention of \"pg_trgm\"", err)
	}
	if !strings.Contains(err.Error(), "target") {
		t.Errorf("err = %v; want mention of \"target\"", err)
	}
}
