//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// GC-3 (gap census 2026-09-22 S4 + S5) end to end on a real Postgres
// pair: a PG → PG migrate re-creates a GENERATED ALWAYS identity as
// ALWAYS (after the copy) and a BY DEFAULT one as BY DEFAULT, and carries
// the identity sequence's options exactly.
//
// The independent expected values, named: the TARGET server's own
// SQLSTATE — 428C9 when an explicit id is inserted into the restored
// ALWAYS column, and success on the BY DEFAULT one — and the target's
// pg_sequence row for the identity's backing sequence. Neither derives
// from sluice's reader or writer.

package pipeline

import (
	"context"
	"database/sql"
	"errors"
	"log/slog"
	"strings"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/engines"
	"sluicesync.dev/sluice/internal/logcapture"

	"github.com/jackc/pgx/v5/pgconn"
)

// pgInsertSQLState runs stmt on dsn and returns the SQLSTATE it fails
// with ("" on success).
func pgInsertSQLState(t *testing.T, dsn, stmt string) string {
	t.Helper()
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer func() { _ = db.Close() }()
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	_, err = db.ExecContext(ctx, stmt)
	if err == nil {
		return ""
	}
	var pgErr *pgconn.PgError
	if !errors.As(err, &pgErr) {
		t.Fatalf("%s: non-PG error %v", stmt, err)
	}
	return pgErr.Code
}

// pgIdentitySequenceOptions reads the identity sequence's options for
// table.column straight from pg_sequence, joined through the deptype='i'
// edge — the ground truth the S5 assertion compares against.
func pgIdentitySequenceOptions(t *testing.T, dsn, table, column string) string {
	t.Helper()
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer func() { _ = db.Close() }()
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	const q = `
		SELECT s.seqstart || ',' || s.seqincrement || ',' || s.seqmin || ',' || s.seqmax || ',' || s.seqcache || ',' || s.seqcycle
		FROM   pg_depend d
		JOIN   pg_sequence  s  ON s.seqrelid = d.objid
		JOIN   pg_class     tc ON tc.oid = d.refobjid
		JOIN   pg_attribute a  ON a.attrelid = tc.oid AND a.attnum = d.refobjsubid
		WHERE  d.classid = 'pg_class'::regclass AND d.refclassid = 'pg_class'::regclass
		  AND  d.deptype = 'i' AND tc.relname = $1 AND a.attname = $2`
	var s string
	if err := db.QueryRowContext(ctx, q, table, column).Scan(&s); err != nil {
		t.Fatalf("identity sequence options for %s.%s: %v", table, column, err)
	}
	return s
}

func TestMigrate_PGIdentityAlwaysRestoredAndOptionsCarried(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()

	applyPGDDL(t, sourceDSN, `
		CREATE TABLE strict_ids (
			id   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
			note TEXT NOT NULL
		);
		CREATE TABLE loose_ids (
			id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			note TEXT NOT NULL
		);
		CREATE TABLE sharded (
			id   BIGINT GENERATED ALWAYS AS IDENTITY (INCREMENT BY 10 START WITH 3 CACHE 50 MAXVALUE 100000 CYCLE) PRIMARY KEY,
			note TEXT NOT NULL
		);
		INSERT INTO strict_ids (note) VALUES ('a'), ('b');
		INSERT INTO loose_ids (note) VALUES ('a'), ('b');
		INSERT INTO sharded (note) VALUES ('a'), ('b');
	`)
	// The source's own account of the sharded identity, before anything moves.
	wantSharded := pgIdentitySequenceOptions(t, sourceDSN, "sharded", "id")
	if wantSharded != "3,10,1,100000,50,true" {
		t.Fatalf("source sharded options = %q; the seed did not produce what this test pins", wantSharded)
	}

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	buf := &logcapture.Buffer{}
	prev := slog.Default()
	slog.SetDefault(slog.New(slog.NewJSONHandler(buf, &slog.HandlerOptions{Level: slog.LevelInfo})))
	t.Cleanup(func() { slog.SetDefault(prev) })

	mig := &Migrator{Source: pgEng, Target: pgEng, SourceDSN: sourceDSN, TargetDSN: targetDSN}
	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		t.Fatalf("Migrator.Run: %v", err)
	}
	logs := buf.String()

	// The once-per-run WARN names both ALWAYS columns and not the BY DEFAULT one.
	if n := strings.Count(logs, "IDENTITY-ALWAYS-DOWNGRADED"); n != 1 {
		t.Errorf("IDENTITY-ALWAYS-DOWNGRADED appears %d times; want exactly 1", n)
	}
	for _, want := range []string{"strict_ids.id", "sharded.id"} {
		if !strings.Contains(logs, want) {
			t.Errorf("downgrade WARN does not name %s", want)
		}
	}
	if strings.Contains(logs, "loose_ids.id") {
		t.Error("downgrade WARN names the BY DEFAULT column loose_ids.id")
	}
	if !strings.Contains(logs, "IDENTITY-ALWAYS-RESTORED") {
		t.Error("no IDENTITY-ALWAYS-RESTORED line after the copy")
	}

	// The copied rows landed with the source's ids (the reason for BY
	// DEFAULT during the copy).
	if got := pgInsertSQLState(t, targetDSN, `SELECT 1`); got != "" {
		t.Fatalf("target unreachable: %s", got)
	}

	// The independent expected value: the TARGET refuses an explicit id on
	// the restored ALWAYS columns with SQLSTATE 428C9 and accepts one on
	// the BY DEFAULT column.
	if got := pgInsertSQLState(t, targetDSN, `INSERT INTO strict_ids (id, note) VALUES (100, 'x')`); got != "428C9" {
		t.Errorf("explicit id into strict_ids: SQLSTATE %q; want 428C9 (GENERATED ALWAYS was not restored)", got)
	}
	if got := pgInsertSQLState(t, targetDSN, `INSERT INTO sharded (id, note) VALUES (100, 'x')`); got != "428C9" {
		t.Errorf("explicit id into sharded: SQLSTATE %q; want 428C9 (GENERATED ALWAYS was not restored)", got)
	}
	if got := pgInsertSQLState(t, targetDSN, `INSERT INTO loose_ids (id, note) VALUES (100, 'x')`); got != "" {
		t.Errorf("explicit id into loose_ids: SQLSTATE %q; want success (BY DEFAULT must stay BY DEFAULT)", got)
	}
	// And the generated path still works on the ALWAYS column, continuing
	// past the copied ids (SyncIdentitySequences) with the carried
	// increment.
	if got := pgInsertSQLState(t, targetDSN, `INSERT INTO sharded (note) VALUES ('y')`); got != "" {
		t.Errorf("generated id into sharded: SQLSTATE %q; want success", got)
	}

	// S5: the identity sequence options round-trip exactly, read from the
	// target's pg_sequence.
	if got := pgIdentitySequenceOptions(t, targetDSN, "sharded", "id"); got != wantSharded {
		t.Errorf("target sharded identity options = %q; want %q (START/INCREMENT/MINVALUE/MAXVALUE/CACHE/CYCLE must round-trip)", got, wantSharded)
	}
	if got, want := pgIdentitySequenceOptions(t, targetDSN, "strict_ids", "id"), pgIdentitySequenceOptions(t, sourceDSN, "strict_ids", "id"); got != want {
		t.Errorf("target strict_ids identity options = %q; want %q", got, want)
	}
}
