//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// The value-fidelity review's BLOCKING finding on GC-3: once identity
// sequence options round-trip faithfully, the post-copy identity sync
// must prime a DESCENDING identity from MIN, not MAX — otherwise the
// sequence is parked ON an existing id and the first INSERT on the target
// fails `duplicate key`, at exit 0 from the migrate (measured on PG 17/18:
// rows -1,-2,-3 → setval(-1) → `Key (id)=(-2) already exists`).
//
// Two descending shapes, because they fail differently: a negative-range
// one (INCREMENT BY -1 from the bigint default START -1) and a
// POSITIVE-range one (START 100 INCREMENT BY -1 MINVALUE 1 MAXVALUE 100),
// where MAX and MIN are both legal setval targets and only one of them
// is right.
//
// The independent expected value is the target's own INSERT … DEFAULT:
// it must succeed, and the id it assigns must be beyond MIN in the
// sequence's direction — never one of the copied ids.

package pipeline

import (
	"context"
	"database/sql"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/engines"
)

// pgInsertDefaultReturningID inserts a row through the identity and
// returns the id the TARGET assigned; fails the test on any error.
func pgInsertDefaultReturningID(t *testing.T, dsn, table string) int64 {
	t.Helper()
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer func() { _ = db.Close() }()
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	var id int64
	if err := db.QueryRowContext(ctx, `INSERT INTO `+table+` (note) VALUES ('after') RETURNING id`).Scan(&id); err != nil {
		t.Fatalf("INSERT … DEFAULT into %s after migrate: %v (the identity sequence is parked on a copied id)", table, err)
	}
	return id
}

func TestMigrate_PGIdentityDescendingPrimedFromMin(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()

	applyPGDDL(t, sourceDSN, `
		CREATE TABLE desc_neg (
			id   BIGINT GENERATED ALWAYS AS IDENTITY (INCREMENT BY -1) PRIMARY KEY,
			note TEXT NOT NULL
		);
		CREATE TABLE desc_pos (
			id   INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY -1 MINVALUE 1 MAXVALUE 100) PRIMARY KEY,
			note TEXT NOT NULL
		);
		CREATE TABLE asc_ctl (
			id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			note TEXT NOT NULL
		);
		INSERT INTO desc_neg (note) VALUES ('a'), ('b'), ('c');
		INSERT INTO desc_pos (note) VALUES ('a'), ('b'), ('c');
		INSERT INTO asc_ctl  (note) VALUES ('a'), ('b'), ('c');
	`)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}
	mig := &Migrator{Source: pgEng, Target: pgEng, SourceDSN: sourceDSN, TargetDSN: targetDSN}
	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		t.Fatalf("Migrator.Run: %v", err)
	}

	// Negative-range descending: copied -1,-2,-3 → the next id is -4.
	if got := pgInsertDefaultReturningID(t, targetDSN, "desc_neg"); got != -4 {
		t.Errorf("desc_neg: first generated id after migrate = %d; want -4 (beyond MIN -3, stepping by -1)", got)
	}
	// Positive-range descending: copied 100,99,98 → the next id is 97.
	// A MAX-based prime would park the sequence on 100 and hand out 99.
	if got := pgInsertDefaultReturningID(t, targetDSN, "desc_pos"); got != 97 {
		t.Errorf("desc_pos: first generated id after migrate = %d; want 97 (beyond MIN 98, stepping by -1)", got)
	}
	// Ascending control: copied 1,2,3 → 4, exactly as before.
	if got := pgInsertDefaultReturningID(t, targetDSN, "asc_ctl"); got != 4 {
		t.Errorf("asc_ctl: first generated id after migrate = %d; want 4", got)
	}
}
