//go:build integration

// Integration test for Bug 9: cold-start hangs when dest tables have
// pre-existing data. The pre-flight check (preflight.go) refuses
// migrations into a populated target with a clear error, replacing
// the v0.3.0 behaviour where the bulk-copy phase would hang on
// duplicate-key writer errors and a leaked snapshot transaction.
//
// We exercise the Postgres→Postgres path because it's the cheapest
// container pair to spin up; the pre-flight is engine-neutral, so
// PG→PG coverage is enough to confirm the orchestration shape.

package pipeline

import (
	"context"
	"errors"
	"strings"
	"testing"
	"time"

	"github.com/orware/sluice/internal/engines"

	// Register the postgres engine so engines.Get("postgres") works.
	_ "github.com/orware/sluice/internal/engines/postgres"
)

// TestMigrate_ColdStartRefusesPopulatedTarget reproduces Bug 9: with a
// dest table already containing rows from a previously-killed
// cold-start, restarting cold-start now refuses immediately rather
// than hanging on duplicate-key writes and leaking a snapshot tx.
func TestMigrate_ColdStartRefusesPopulatedTarget(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()

	// Source: a typical small schema with rows.
	const sourceDDL = `
		CREATE TABLE comments (
			id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			body TEXT NOT NULL
		);
		INSERT INTO comments (body)
			SELECT 'comment ' || g FROM generate_series(1, 4000) g;
	`
	applyPGDDL(t, sourceDSN, sourceDDL)

	// Target: pre-populate the comments table with some "leftover"
	// rows, simulating the killed-mid-bulk-copy state Bug 9 hits.
	const targetDDL = `
		CREATE TABLE comments (
			id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			body TEXT NOT NULL
		);
		INSERT INTO comments (body)
			SELECT 'leftover ' || g FROM generate_series(1, 501) g;
	`
	applyPGDDL(t, targetDSN, targetDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	mig := &Migrator{
		Source:    pgEng,
		Target:    pgEng,
		SourceDSN: sourceDSN,
		TargetDSN: targetDSN,
	}

	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()

	err := mig.Run(ctx)
	if err == nil {
		t.Fatal("expected pre-flight refusal; got nil error")
	}
	if !errors.Is(err, errColdStartRefused) {
		t.Errorf("expected errColdStartRefused; got %v", err)
	}
	msg := err.Error()
	if !strings.Contains(msg, "comments") {
		t.Errorf("expected populated table name in error; got %q", msg)
	}
	if !strings.Contains(msg, "--force-cold-start") {
		t.Errorf("expected --force-cold-start hint in error; got %q", msg)
	}
	if !strings.Contains(msg, "slot drop") {
		t.Errorf("expected slot drop hint in error; got %q", msg)
	}

	// The dest must still have its leftover rows — pre-flight refuses
	// before any work, so nothing is appended.
	if got := countRows(t, targetDSN, "comments"); got != 501 {
		t.Errorf("dest comments row count = %d; want 501 (pre-flight should not have written)", got)
	}
}

// TestMigrate_ColdStartForceProceeds confirms --force-cold-start
// bypasses the pre-flight. The check refuses; the override skips
// the check; the writer then hits the real PRIMARY KEY collision
// because of the leftover rows. We assert the *failure mode shifts*
// from "pre-flight refusal" to "writer error" — that's the contract
// of the override flag.
func TestMigrate_ColdStartForceProceeds(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()

	const sourceDDL = `
		CREATE TABLE items (
			id   BIGINT PRIMARY KEY,
			body TEXT NOT NULL
		);
		INSERT INTO items (id, body) VALUES (1, 'src 1'), (2, 'src 2'), (3, 'src 3');
	`
	applyPGDDL(t, sourceDSN, sourceDDL)

	// Pre-populate dest with id=1 so a real bulk-copy would collide.
	const targetDDL = `
		CREATE TABLE items (
			id   BIGINT PRIMARY KEY,
			body TEXT NOT NULL
		);
		INSERT INTO items (id, body) VALUES (1, 'leftover');
	`
	applyPGDDL(t, targetDSN, targetDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	mig := &Migrator{
		Source:         pgEng,
		Target:         pgEng,
		SourceDSN:      sourceDSN,
		TargetDSN:      targetDSN,
		ForceColdStart: true,
	}

	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()

	err := mig.Run(ctx)
	if err == nil {
		t.Fatal("expected writer-side collision when force=true; got nil")
	}
	// With --force-cold-start, we *expect* the pre-flight is skipped.
	// Therefore errColdStartRefused must NOT be in the chain.
	if errors.Is(err, errColdStartRefused) {
		t.Errorf("--force-cold-start should bypass pre-flight; got pre-flight error: %v", err)
	}
}
