//go:build integration

// Cross-engine end-to-end integration test for the simple-mode
// orchestrator: Postgres source → MySQL target. Mirrors the existing
// MySQL→Postgres test in shape so the assertion code stays close to
// identity — same conservative seed (BIGINT identity, VARCHAR(255),
// BOOLEAN, TIMESTAMP, FK with ON DELETE CASCADE), opposite direction.
//
// What this validates that the same-engine PG→PG and MySQL→PG tests
// don't:
//
//   - PG `BOOLEAN` → MySQL `TINYINT(1)` (default values included, not
//     just the type).
//   - PG `BIGINT GENERATED BY DEFAULT AS IDENTITY` → MySQL
//     `BIGINT AUTO_INCREMENT`.
//   - PG `TEXT` → MySQL `LONGTEXT` (the IR's TextLong size).
//   - PG `TIMESTAMP DEFAULT CURRENT_TIMESTAMP` → MySQL
//     `DATETIME DEFAULT CURRENT_TIMESTAMP`, including default-value
//     translation across dialects.
//   - FK `ON DELETE CASCADE` survives both readers and both writers.

package pipeline

import (
	"context"
	"testing"
	"time"

	"github.com/orware/sluice/internal/engines"
	"github.com/orware/sluice/internal/ir"

	// Both engines must be registered for engines.Get to find them.
	_ "github.com/orware/sluice/internal/engines/mysql"
	_ "github.com/orware/sluice/internal/engines/postgres"
)

// TestMigrate_PostgresToMySQL is the cross-engine validation test in
// the PG → MySQL direction.
func TestMigrate_PostgresToMySQL(t *testing.T) {
	// Reuse the same-engine helpers: each spins up a container and
	// returns a source + target DSN pair on the same instance. We
	// use the source DSN of the PG pair (the one we'll seed) and
	// the target DSN of the MySQL pair (the one we'll migrate into).
	// The unused database on each side is empty and harmless.
	pgSource, _, pgCleanup := startPostgres(t)
	defer pgCleanup()

	_, mysqlTarget, mysqlCleanup := startMySQL(t)
	defer mysqlCleanup()

	const seedDDL = `
		CREATE TABLE users (
			id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email      VARCHAR(255) NOT NULL,
			active     BOOLEAN      NOT NULL DEFAULT true,
			created_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
			metadata   JSONB        NULL,
			CONSTRAINT users_email_unique UNIQUE (email)
		);

		CREATE TABLE posts (
			id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			user_id BIGINT NOT NULL,
			body    TEXT   NOT NULL,
			CONSTRAINT posts_user_id_fk FOREIGN KEY (user_id)
				REFERENCES users (id) ON DELETE CASCADE
		);
		CREATE INDEX posts_user_id_idx ON posts (user_id);

		INSERT INTO users (email, active, metadata) VALUES
			('alice@example.com', true,  '{"k":"v"}'::jsonb),
			('bob@example.com',   false, NULL);

		INSERT INTO posts (user_id, body) VALUES
			(1, 'first post'),
			(1, 'second post'),
			(2, 'a post by bob');
	`
	applyPGDDL(t, pgSource, seedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}
	mysqlEng, ok := engines.Get("mysql")
	if !ok {
		t.Fatal("mysql engine not registered")
	}

	mig := &Migrator{
		Source:    pgEng,
		Target:    mysqlEng,
		SourceDSN: pgSource,
		TargetDSN: mysqlTarget,
	}

	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		t.Fatalf("Migrator.Run: %v", err)
	}

	// ---- Verify the MySQL target ----
	sr, err := mysqlEng.OpenSchemaReader(ctx, mysqlTarget)
	if err != nil {
		t.Fatalf("OpenSchemaReader: %v", err)
	}
	defer closeIf(sr)

	got, err := sr.ReadSchema(ctx)
	if err != nil {
		t.Fatalf("ReadSchema: %v", err)
	}
	if len(got.Tables) != 2 {
		t.Fatalf("target tables = %d; want 2 (have: %v)", len(got.Tables), targetTableNames(got))
	}

	users := findTable(got, "users")
	posts := findTable(got, "posts")
	if users == nil || posts == nil {
		t.Fatalf("missing target tables; have %v", targetTableNames(got))
	}

	// id should be a 64-bit auto-increment integer.
	idCol := findColumn(users, "id")
	if idCol == nil {
		t.Fatalf("users.id missing")
	}
	if intT, ok := idCol.Type.(ir.Integer); !ok || intT.Width != 64 || !intT.AutoIncrement {
		t.Errorf("users.id type = %#v; want ir.Integer{Width:64, AutoIncrement:true}", idCol.Type)
	}

	// active should be Boolean — the BOOLEAN → TINYINT(1) translation
	// is the load-bearing assertion in this direction.
	activeCol := findColumn(users, "active")
	if activeCol == nil {
		t.Fatalf("users.active missing")
	}
	if _, ok := activeCol.Type.(ir.Boolean); !ok {
		t.Errorf("users.active type = %#v; want ir.Boolean", activeCol.Type)
	}

	// body should map to a TEXT-family type. PG's unbounded TEXT
	// translates through ir.Text{TextLong} to MySQL's LONGTEXT.
	bodyCol := findColumn(posts, "body")
	if bodyCol == nil {
		t.Fatalf("posts.body missing")
	}
	if textT, ok := bodyCol.Type.(ir.Text); !ok || textT.Size != ir.TextLong {
		t.Errorf("posts.body type = %#v; want ir.Text{Size:TextLong}", bodyCol.Type)
	}

	// §7: PG JSONB → MySQL JSON. MySQL has only one JSON kind
	// (binary internally), so the IR shape on the MySQL side is
	// ir.JSON{Binary:true} regardless of which side originated it.
	metaCol := findColumn(users, "metadata")
	if metaCol == nil {
		t.Fatalf("users.metadata missing")
	}
	if j, ok := metaCol.Type.(ir.JSON); !ok || !j.Binary {
		t.Errorf("users.metadata type = %#v; want ir.JSON{Binary:true} (PG JSONB → MySQL JSON)", metaCol.Type)
	}

	// PK on id, unique on email.
	if users.PrimaryKey == nil || users.PrimaryKey.Columns[0].Column != "id" {
		t.Errorf("users PK = %#v; want PK on id", users.PrimaryKey)
	}
	hasEmailUnique := false
	for _, ix := range users.Indexes {
		if ix.Unique && len(ix.Columns) == 1 && ix.Columns[0].Column == "email" {
			hasEmailUnique = true
			break
		}
	}
	if !hasEmailUnique {
		t.Errorf("users indexes = %#v; want a unique index on email", users.Indexes)
	}

	// FK CASCADE preserved.
	if len(posts.ForeignKeys) != 1 {
		t.Fatalf("posts FKs = %d; want 1", len(posts.ForeignKeys))
	}
	fk := posts.ForeignKeys[0]
	if fk.ReferencedTable != "users" || fk.OnDelete != ir.FKActionCascade {
		t.Errorf("posts FK = %+v; want users on-delete cascade", fk)
	}

	// ---- Verify rows arrived intact and translated correctly ----
	rr, err := mysqlEng.OpenRowReader(ctx, mysqlTarget)
	if err != nil {
		t.Fatalf("OpenRowReader: %v", err)
	}
	defer closeIf(rr)

	usersRows := readAll(t, ctx, rr, users)
	if len(usersRows) != 2 {
		t.Errorf("target users rows = %d; want 2", len(usersRows))
	}
	if email, ok := usersRows[0]["email"].(string); !ok || email != "alice@example.com" {
		t.Errorf("users[0].email = %#v; want 'alice@example.com'", usersRows[0]["email"])
	}
	// PG's `true` must surface as MySQL `true` (TINYINT(1) decoded as bool).
	if active, ok := usersRows[0]["active"].(bool); !ok || !active {
		t.Errorf("users[0].active = %#v; want true (BOOLEAN → bool)", usersRows[0]["active"])
	}
	if active, ok := usersRows[1]["active"].(bool); !ok || active {
		t.Errorf("users[1].active = %#v; want false", usersRows[1]["active"])
	}

	postsRows := readAll(t, ctx, rr, posts)
	if len(postsRows) != 3 {
		t.Errorf("target posts rows = %d; want 3", len(postsRows))
	}
	if body, ok := postsRows[0]["body"].(string); !ok || body != "first post" {
		t.Errorf("posts[0].body = %#v; want 'first post'", postsRows[0]["body"])
	}
}
