//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// Task #42: cross-engine case-sensitivity test matrix — PG ↔ MySQL.
//
// Bulk-copy (Migrator) and CDC (Streamer) in both directions:
//   - PG → MySQL bulk + CDC
//   - MySQL → PG bulk + CDC
//
// Cross-engine is where the case-preservation invariant earns its
// keep. A source-side reader that lower-cases an identifier corrupts
// every downstream consumer regardless of target. A writer that drops
// quotes can write to a folded name on the target while the IR carries
// the correct case. The matrix exercises both source readers and both
// target writers in every cell, so any regression on either side
// surfaces immediately.
//
// Same Phase A scope discipline: quoted source DDL only.
// `lower_case_table_names=0` is forced on every MySQL container in
// this file (source AND target as needed) via
// startMySQLCaseSensitive / startMySQLBinlogCaseSensitive (defined in
// migrate_case_preservation_mysql_integration_test.go in this same
// package).

package pipeline

import (
	"context"
	"fmt"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/engines"

	_ "sluicesync.dev/sluice/internal/engines/mysql"
	_ "sluicesync.dev/sluice/internal/engines/postgres"
)

// TestMigrate_CasePreservation_PostgresToMySQL pins cross-engine case
// preservation in the PG → MySQL direction on the bulk-copy path.
func TestMigrate_CasePreservation_PostgresToMySQL(t *testing.T) {
	for _, shape := range caseShapes {
		shape := shape
		t.Run(shape.label, func(t *testing.T) {
			pgSource, _, pgCleanup := startPostgres(t)
			defer pgCleanup()

			_, mysqlTarget, mysqlCleanup := startMySQLCaseSensitive(t)
			defer mysqlCleanup()

			seedDDL := fmt.Sprintf(`
				CREATE TABLE %q (
					id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					%q VARCHAR(255) NOT NULL
				);
				INSERT INTO %q (%q) VALUES ('alice'), ('bob');
			`, shape.table, shape.column, shape.table, shape.column)
			applyPGDDL(t, pgSource, seedDDL)

			pgEng, ok := engines.Get("postgres")
			if !ok {
				t.Fatal("postgres engine not registered")
			}
			mysqlEng, ok := engines.Get("mysql")
			if !ok {
				t.Fatal("mysql engine not registered")
			}

			mig := &Migrator{
				Source:    pgEng,
				Target:    mysqlEng,
				SourceDSN: pgSource,
				TargetDSN: mysqlTarget,
			}
			ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
			defer cancel()
			if err := mig.Run(ctx); err != nil {
				t.Fatalf("Migrator.Run (PG→MySQL): %v", err)
			}

			assertMySQLTableCasePreserved(t, ctx, mysqlTarget, shape)
			assertMySQLRowsPreserved(t, ctx, mysqlTarget, shape, 2)
		})
	}
}

// TestMigrate_CasePreservation_MySQLToPostgres pins cross-engine case
// preservation in the MySQL → PG direction on the bulk-copy path.
func TestMigrate_CasePreservation_MySQLToPostgres(t *testing.T) {
	for _, shape := range caseShapes {
		shape := shape
		t.Run(shape.label, func(t *testing.T) {
			mysqlSource, _, mysqlCleanup := startMySQLCaseSensitive(t)
			defer mysqlCleanup()

			_, pgTarget, pgCleanup := startPostgres(t)
			defer pgCleanup()

			seedDDL := fmt.Sprintf(
				"CREATE TABLE `%s` ("+
					"id BIGINT NOT NULL AUTO_INCREMENT, "+
					"`%s` VARCHAR(255) NOT NULL, "+
					"PRIMARY KEY (id)"+
					") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4; "+
					"INSERT INTO `%s` (`%s`) VALUES ('alice'), ('bob');",
				shape.table, shape.column, shape.table, shape.column,
			)
			applyMySQLDDL(t, mysqlSource, seedDDL)

			mysqlEng, ok := engines.Get("mysql")
			if !ok {
				t.Fatal("mysql engine not registered")
			}
			pgEng, ok := engines.Get("postgres")
			if !ok {
				t.Fatal("postgres engine not registered")
			}

			mig := &Migrator{
				Source:    mysqlEng,
				Target:    pgEng,
				SourceDSN: mysqlSource,
				TargetDSN: pgTarget,
			}
			ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
			defer cancel()
			if err := mig.Run(ctx); err != nil {
				t.Fatalf("Migrator.Run (MySQL→PG): %v", err)
			}

			assertPGTableCasePreserved(t, ctx, pgTarget, shape)
			assertPGRowsPreserved(t, ctx, pgTarget, shape, 2)
		})
	}
}

// TestStreamer_CasePreservation_MySQLToPostgres pins cross-engine
// case preservation in the MySQL → PG direction on the CDC path.
//
// This is the heavier failure-mode cell of the matrix: a regression
// in MySQL's binlog QUERY-event parsing or PG's pgoutput change
// applier silently corrupts cross-engine CDC. The "INSERT lands on
// the target queried with the case-preserved name" assertion is the
// load-bearing proxy — if sluice lower-cased somewhere on the read
// or apply path, the apply would either fail loudly (relation does
// not exist) or silently write to a folded-name table that doesn't
// exist on the case-preserved target, leaving the polled count at 2.
func TestStreamer_CasePreservation_MySQLToPostgres(t *testing.T) {
	for _, shape := range caseShapes {
		shape := shape
		t.Run(shape.label, func(t *testing.T) {
			mysqlSource, _, mysqlCleanup := startMySQLBinlogCaseSensitive(t)
			defer mysqlCleanup()

			_, pgTarget, pgCleanup := startPostgres(t)
			defer pgCleanup()

			seedDDL := fmt.Sprintf(
				"CREATE TABLE `%s` ("+
					"id BIGINT NOT NULL AUTO_INCREMENT, "+
					"`%s` VARCHAR(255) NOT NULL, "+
					"PRIMARY KEY (id)"+
					") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4; "+
					"INSERT INTO `%s` (`%s`) VALUES ('alice');",
				shape.table, shape.column, shape.table, shape.column,
			)
			applyMySQLDDL(t, mysqlSource, seedDDL)

			mysqlEng, ok := engines.Get("mysql")
			if !ok {
				t.Fatal("mysql engine not registered")
			}
			pgEng, ok := engines.Get("postgres")
			if !ok {
				t.Fatal("postgres engine not registered")
			}

			streamer := &Streamer{
				Source:    mysqlEng,
				Target:    pgEng,
				SourceDSN: mysqlSource,
				TargetDSN: pgTarget,
				StreamID:  "test-case-pres-mysql-pg-" + shape.label,
			}
			streamCtx, streamCancel := context.WithCancel(context.Background())
			defer streamCancel()
			runErr := make(chan error, 1)
			go func() { runErr <- streamer.Run(streamCtx) }()

			if !waitForRowCountQuoted(t, pgTarget, shape.table, 1, 60*time.Second) {
				t.Fatalf("bulk copy never delivered seed row to PG target %q", shape.table)
			}

			assertPGTableCasePreserved(t, streamCtx, pgTarget, shape)

			// INSERT a second row on the source through CDC.
			applyMySQLDDL(t, mysqlSource, fmt.Sprintf(
				"INSERT INTO `%s` (`%s`) VALUES ('bob');",
				shape.table, shape.column,
			))
			if !waitForRowCountQuoted(t, pgTarget, shape.table, 2, 30*time.Second) {
				t.Fatalf("CDC never delivered post-snapshot INSERT to PG target %q", shape.table)
			}

			// Verify bob landed at the case-preserved column.
			if readOneRowByValueQuoted(t, streamCtx, pgTarget, shape.table, shape.column, "bob") == nil {
				t.Errorf("CDC row for 'bob' not found at %q.%q on PG target", shape.table, shape.column)
			}

			streamCancel()
			select {
			case <-runErr:
			case <-time.After(15 * time.Second):
				t.Fatal("Streamer.Run did not return after ctx cancel")
			}
		})
	}
}

// TestStreamer_CasePreservation_PostgresToMySQL pins cross-engine
// case preservation in the PG → MySQL direction on the CDC path.
// The mirror of TestStreamer_CasePreservation_MySQLToPostgres — same
// load-bearing claim, reverse engine pair.
func TestStreamer_CasePreservation_PostgresToMySQL(t *testing.T) {
	for _, shape := range caseShapes {
		shape := shape
		t.Run(shape.label, func(t *testing.T) {
			pgSource, _, pgCleanup := startPostgresLogical(t)
			defer pgCleanup()

			_, mysqlTarget, mysqlCleanup := startMySQLCaseSensitive(t)
			defer mysqlCleanup()

			seedDDL := fmt.Sprintf(`
				CREATE TABLE %q (
					id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					%q VARCHAR(255) NOT NULL
				);
				ALTER TABLE %q REPLICA IDENTITY FULL;
				INSERT INTO %q (%q) VALUES ('alice');
			`, shape.table, shape.column, shape.table, shape.table, shape.column)
			applyPGDDL(t, pgSource, seedDDL)

			pgEng, ok := engines.Get("postgres")
			if !ok {
				t.Fatal("postgres engine not registered")
			}
			mysqlEng, ok := engines.Get("mysql")
			if !ok {
				t.Fatal("mysql engine not registered")
			}

			streamer := &Streamer{
				Source:    pgEng,
				Target:    mysqlEng,
				SourceDSN: pgSource,
				TargetDSN: mysqlTarget,
				StreamID:  "test-case-pres-pg-mysql-" + shape.label,
			}
			streamCtx, streamCancel := context.WithCancel(context.Background())
			defer streamCancel()
			runErr := make(chan error, 1)
			go func() { runErr <- streamer.Run(streamCtx) }()

			if !waitForRowCountMySQLQuoted(t, mysqlTarget, shape.table, 1, 60*time.Second) {
				t.Fatalf("bulk copy never delivered seed row to MySQL target `%s`", shape.table)
			}

			assertMySQLTableCasePreserved(t, streamCtx, mysqlTarget, shape)

			// INSERT a second row on the source through CDC.
			applyPGDDL(t, pgSource, fmt.Sprintf(
				`INSERT INTO %q (%q) VALUES ('bob');`,
				shape.table, shape.column,
			))
			if !waitForRowCountMySQLQuoted(t, mysqlTarget, shape.table, 2, 30*time.Second) {
				t.Fatalf("CDC never delivered post-snapshot INSERT to MySQL target `%s`", shape.table)
			}

			if !mysqlRowExistsByValueQuoted(t, streamCtx, mysqlTarget, shape.table, shape.column, "bob") {
				t.Errorf("CDC row for 'bob' not found at `%s`.`%s` on MySQL target", shape.table, shape.column)
			}

			streamCancel()
			select {
			case <-runErr:
			case <-time.After(15 * time.Second):
				t.Fatal("Streamer.Run did not return after ctx cancel")
			}
		})
	}
}
