//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// Cross-engine PG → MySQL regression test for v0.32.2: a PG source
// with `jsonb NOT NULL DEFAULT '{}'::jsonb` must NOT die at CREATE
// TABLE on the MySQL target with Error 1101 ("BLOB, TEXT, GEOMETRY
// or JSON column 'col' can't have a default value"). The MySQL
// writer now drops the DEFAULT clause for JSON / TEXT / BLOB /
// GEOMETRY columns and surfaces a WARN log naming the column and
// the suppressed default. The Bulk-copy phase still moves rows.
//
// Operator workflow note (the WARN log captures this): the source
// column is NOT NULL, so without the default on the target,
// INSERTs that don't specify a value would fail. The migration
// itself is fine because the source rows already have values; only
// future inserts on the target without an explicit value are at
// risk. Operators wanting symmetric behavior drop NOT NULL on the
// source or supply the value at write time.

package pipeline

import (
	"context"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/engines"
	"sluicesync.dev/sluice/internal/ir"

	// Both engines must be registered for engines.Get to find them.
	_ "sluicesync.dev/sluice/internal/engines/mysql"
	_ "sluicesync.dev/sluice/internal/engines/postgres"
)

// TestMigrate_PostgresToMySQL_JSONBDefaultSuppressed pins the v0.32.2
// fix: a PG source with `jsonb NOT NULL DEFAULT '{}'::jsonb` migrates
// to MySQL without tripping MySQL Error 1101. The target column lands
// as `JSON NOT NULL` with no DEFAULT; the seeded rows arrive intact.
func TestMigrate_PostgresToMySQL_JSONBDefaultSuppressed(t *testing.T) {
	pgSource, _, pgCleanup := startPostgres(t)
	defer pgCleanup()

	_, mysqlTarget, mysqlCleanup := startMySQL(t)
	defer mysqlCleanup()

	// The combination that triggered the operator-visible bug:
	// jsonb + NOT NULL + DEFAULT. Adding a TEXT + DEFAULT column for
	// coverage of the second forbidden-type family (MySQL Error 1101
	// covers BLOB / TEXT / GEOMETRY / JSON; the writer's suppression
	// helper covers all four).
	const seedDDL = `
		CREATE TABLE prefs (
			id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name        VARCHAR(64)  NOT NULL,
			settings    JSONB        NOT NULL DEFAULT '{}'::jsonb,
			description TEXT         NOT NULL DEFAULT ''
		);

		INSERT INTO prefs (name, settings, description) VALUES
			('alice', '{"theme":"dark"}'::jsonb, 'admin user'),
			('bob',   '{}'::jsonb,               'regular user');
	`
	applyPGDDL(t, pgSource, seedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}
	mysqlEng, ok := engines.Get("mysql")
	if !ok {
		t.Fatal("mysql engine not registered")
	}

	mig := &Migrator{
		Source:    pgEng,
		Target:    mysqlEng,
		SourceDSN: pgSource,
		TargetDSN: mysqlTarget,
	}

	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		// The pre-fix failure mode would surface here with MySQL
		// Error 1101 inside the schema-apply phase. A successful Run
		// is the load-bearing assertion: the DEFAULT was suppressed
		// and CREATE TABLE on the target accepted the DDL.
		t.Fatalf("Migrator.Run: %v", err)
	}

	// ---- Verify the MySQL target schema shape ----
	sr, err := mysqlEng.OpenSchemaReader(ctx, mysqlTarget)
	if err != nil {
		t.Fatalf("OpenSchemaReader: %v", err)
	}
	defer closeIf(sr)

	got, err := sr.ReadSchema(ctx)
	if err != nil {
		t.Fatalf("ReadSchema: %v", err)
	}
	prefs := findTable(got, "prefs")
	if prefs == nil {
		t.Fatalf("target prefs table missing; have %v", targetTableNames(got))
	}

	settings := findColumn(prefs, "settings")
	if settings == nil {
		t.Fatalf("prefs.settings column missing")
	}
	if _, ok := settings.Type.(ir.JSON); !ok {
		t.Errorf("settings.Type = %T; want ir.JSON", settings.Type)
	}
	if settings.Nullable {
		t.Errorf("settings.Nullable = true; want NOT NULL")
	}
	if _, hasDefault := settings.Default.(ir.DefaultNone); !hasDefault {
		// MySQL reports the column with a non-None Default only when
		// a DEFAULT was actually applied at CREATE TABLE time. Post-
		// fix the writer dropped the DEFAULT, so the round-tripped
		// IR should report DefaultNone. Anything else means the fix
		// didn't engage and the test is masking a regression.
		if settings.Default != nil {
			t.Errorf("settings.Default = %#v; want ir.DefaultNone (DEFAULT should have been suppressed for JSON)", settings.Default)
		}
	}

	description := findColumn(prefs, "description")
	if description == nil {
		t.Fatalf("prefs.description column missing")
	}
	if _, ok := description.Type.(ir.Text); !ok {
		t.Errorf("description.Type = %T; want ir.Text", description.Type)
	}
	if _, hasDefault := description.Default.(ir.DefaultNone); !hasDefault {
		if description.Default != nil {
			t.Errorf("description.Default = %#v; want ir.DefaultNone (DEFAULT should have been suppressed for TEXT)", description.Default)
		}
	}

	// ---- Verify rows arrived intact ----
	rr, err := mysqlEng.OpenRowReader(ctx, mysqlTarget)
	if err != nil {
		t.Fatalf("OpenRowReader: %v", err)
	}
	defer closeIf(rr)

	rows := readAll(t, ctx, rr, prefs)
	if len(rows) != 2 {
		t.Errorf("target prefs rows = %d; want 2", len(rows))
	}
}
