//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// PG → PG pgvector passthrough integration tests (ADR-0032).
// Boots the pre-baked pgvector image (task #70 — mirror of upstream
// pgvector/pgvector:0.7.4-pg16, which ships with both PG 16 and the
// pgvector extension files installed but inactive), CREATE EXTENSION
// on both source and target, exercises the full migrate path with a
// vector column + ivfflat / hnsw indexes, and verifies the round-trip
// preserves the column type, indexes, and row data.

package pipeline

import (
	"context"
	"database/sql"
	"strings"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/engines"
	"sluicesync.dev/sluice/internal/ir"
	"sluicesync.dev/sluice/internal/pipeline/migcore"

	_ "sluicesync.dev/sluice/internal/engines/postgres"

	"github.com/testcontainers/testcontainers-go"
	pgtc "github.com/testcontainers/testcontainers-go/modules/postgres"
)

// pgVectorImage is the image tag the pgvector tests boot. Task #70
// pre-baked it to ghcr.io to eliminate docker.io as a single point of
// failure for CI pulls (3-consecutive docker.io TLS-handshake-timeouts
// on PR #72's pipeline-rest-other shard pulling the upstream tag drove
// the migration). Byte-equivalent to upstream pgvector/pgvector:
// 0.7.4-pg16 except /var/lib/postgresql/data has initdb already run +
// the `test` superuser and seed databases (source_db, warehouse,
// sluice_shared_seed) already created. The pgvector extension's
// shared libraries are present the same way they are in upstream;
// CREATE EXTENSION vector still flips the per-database bit at test
// time. See docs/dev/ci-images.md.
const pgVectorImage = "ghcr.io/sluicesync/sluice-pgvector:0.7.4-pg16-prebaked"

// startPostgresWithPGVector boots a pgvector-enabled PG container,
// creates the source and target databases, and runs CREATE
// EXTENSION vector on both. Returns the source and target DSNs
// plus a cleanup callback. Skips cleanly when no Docker provider
// is available.
func startPostgresWithPGVector(t *testing.T, enableOnTarget bool) (sourceDSN, targetDSN string, cleanup func()) {
	t.Helper()
	testcontainers.SkipIfProviderIsNotHealthy(t)

	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Minute)
	defer cancel()

	container, err := pgtc.Run(
		ctx,
		pgVectorImage,
		pgtc.WithDatabase("source_db"),
		pgtc.WithUsername("test"),
		pgtc.WithPassword("test"),
		pgtc.BasicWaitStrategies(),
		// Single-occurrence wait — required for the pre-baked image
		// (datadir already initialized, so postgres only logs "ready
		// to accept connections" once). Replaces BasicWaitStrategies'
		// 2-occurrence inner strategy. See pg_prebaked_integration_test.go.
		pgPrebakedWaitStrategy(),
	)
	if err != nil {
		t.Fatalf("start container: %v", err)
	}

	terminate := func() {
		shutdown, c := context.WithTimeout(context.Background(), 30*time.Second)
		defer c()
		_ = container.Terminate(shutdown)
	}

	srcConn, err := container.ConnectionString(ctx, "sslmode=disable")
	if err != nil {
		terminate()
		t.Fatalf("connection string: %v", err)
	}

	db, err := sql.Open("pgx", srcConn)
	if err != nil {
		terminate()
		t.Fatalf("open: %v", err)
	}
	defer func() { _ = db.Close() }()

	if _, err := db.ExecContext(ctx, "CREATE DATABASE target_db"); err != nil {
		terminate()
		t.Fatalf("create target_db: %v", err)
	}

	tgtConn, err := buildPGDSN(srcConn, "target_db")
	if err != nil {
		terminate()
		t.Fatalf("build target DSN: %v", err)
	}

	// Enable pgvector on the source.
	if _, err := db.ExecContext(ctx, "CREATE EXTENSION IF NOT EXISTS vector"); err != nil {
		terminate()
		t.Fatalf("CREATE EXTENSION vector on source: %v", err)
	}

	if enableOnTarget {
		tgtDB, err := sql.Open("pgx", tgtConn)
		if err != nil {
			terminate()
			t.Fatalf("open target: %v", err)
		}
		defer func() { _ = tgtDB.Close() }()
		if _, err := tgtDB.ExecContext(ctx, "CREATE EXTENSION IF NOT EXISTS vector"); err != nil {
			terminate()
			t.Fatalf("CREATE EXTENSION vector on target: %v", err)
		}
	}

	return srcConn, tgtConn, terminate
}

// TestMigrate_PG_Pgvector_Passthrough exercises the type-only path:
// a `vector(384)` column round-trips through PG → PG migrate when
// the operator opts into --enable-pg-extension vector and both
// sides have pgvector installed. Verifies CREATE TABLE emits the
// right type and rows survive the bulk-copy.
func TestMigrate_PG_Pgvector_Passthrough(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresWithPGVector(t, true)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE items (
			id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name        VARCHAR(64) NOT NULL,
			embedding   vector(3) NOT NULL
		);

		INSERT INTO items (name, embedding) VALUES
			('alpha', '[0.1, 0.2, 0.3]'),
			('beta',  '[0.4, 0.5, 0.6]'),
			('gamma', '[0.7, 0.8, 0.9]');
	`
	applyPGDDL(t, sourceDSN, seedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	mig := &Migrator{
		Source:              pgEng,
		Target:              pgEng,
		SourceDSN:           sourceDSN,
		TargetDSN:           targetDSN,
		EnabledPGExtensions: []string{"vector"},
	}

	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		t.Fatalf("Migrator.Run: %v", err)
	}

	// Verify the target table has the expected vector(3) column type.
	tgtDB, err := sql.Open("pgx", targetDSN)
	if err != nil {
		t.Fatalf("open target: %v", err)
	}
	defer func() { _ = tgtDB.Close() }()

	// pgvector stores the dimension verbatim in pg_attribute.atttypmod
	// (verified against pgvector/src/vector.c's `vector_typmod_in`,
	// Bug 47 root cause). A `vector(3)` column has atttypmod = 3.
	const typmodQuery = `
		SELECT atttypmod
		FROM pg_attribute
		JOIN pg_class ON pg_class.oid = pg_attribute.attrelid
		WHERE pg_class.relname = 'items'
		  AND pg_attribute.attname = 'embedding'`
	var typmod int
	if err := tgtDB.QueryRowContext(ctx, typmodQuery).Scan(&typmod); err != nil {
		t.Fatalf("typmod query: %v", err)
	}
	if typmod != 3 {
		t.Errorf("target items.embedding atttypmod = %d; want 3 (verbatim dimension, no offset)", typmod)
	}

	// Row count check — the bulk copy should have moved 3 rows.
	var n int
	if err := tgtDB.QueryRowContext(ctx, "SELECT COUNT(*) FROM items").Scan(&n); err != nil {
		t.Fatalf("count: %v", err)
	}
	if n != 3 {
		t.Errorf("target items rows = %d; want 3", n)
	}

	// One vector value content check — the alpha row should
	// retain the same components (text-form passthrough).
	var v string
	if err := tgtDB.QueryRowContext(ctx,
		"SELECT embedding::text FROM items WHERE name = 'alpha'").Scan(&v); err != nil {
		t.Fatalf("read alpha embedding: %v", err)
	}
	// pgvector text form normalises to `[0.1,0.2,0.3]` (no spaces).
	if !strings.Contains(v, "0.1") || !strings.Contains(v, "0.2") || !strings.Contains(v, "0.3") {
		t.Errorf("alpha embedding text = %q; expected to contain 0.1, 0.2, 0.3", v)
	}

	// Cross-engine refusal sanity — the IR carries ExtensionType.
	// Read the target back through sluice's reader and confirm the
	// column type is the IR variant.
	pgRdr, err := pgEng.OpenSchemaReader(ctx, targetDSN)
	if err != nil {
		t.Fatalf("OpenSchemaReader on target: %v", err)
	}
	defer migcore.CloseIf(pgRdr)
	if aware, ok := pgRdr.(ir.ExtensionAware); ok {
		if err := aware.EnableExtensions(ctx, []string{"vector"}); err != nil {
			t.Fatalf("EnableExtensions on target reader: %v", err)
		}
	}
	got, err := pgRdr.ReadSchema(ctx)
	if err != nil {
		t.Fatalf("ReadSchema on target: %v", err)
	}
	items := findTable(got, "items")
	if items == nil {
		t.Fatal("target has no items table")
	}
	var foundExt bool
	for _, col := range items.Columns {
		if col.Name == "embedding" {
			ext, ok := col.Type.(ir.ExtensionType)
			if !ok {
				t.Errorf("embedding column type = %T (%v); want ir.ExtensionType",
					col.Type, col.Type)
				continue
			}
			foundExt = true
			if ext.Extension != "vector" || ext.Name != "vector" {
				t.Errorf("embedding ExtensionType = %+v; want extension=vector name=vector", ext)
			}
			if len(ext.Modifiers) != 1 || ext.Modifiers[0] != 3 {
				t.Errorf("embedding Modifiers = %v; want [3]", ext.Modifiers)
			}
		}
	}
	if !foundExt {
		t.Error("did not find embedding column in items")
	}
}

// TestMigrate_PG_Pgvector_IVFFlatIndex exercises the Tier 2 index
// passthrough: an ivfflat index on a vector column is round-tripped
// verbatim.
func TestMigrate_PG_Pgvector_IVFFlatIndex(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresWithPGVector(t, true)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE items (
			id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			embedding vector(3) NOT NULL
		);

		INSERT INTO items (embedding) VALUES
			('[0.1, 0.2, 0.3]'),
			('[0.4, 0.5, 0.6]'),
			('[0.7, 0.8, 0.9]');

		-- ivfflat needs at least one row before CREATE INDEX
		-- can pick lists; lists=1 keeps things tiny for the test.
		CREATE INDEX items_embedding_ivfflat
		    ON items USING ivfflat (embedding vector_l2_ops)
		    WITH (lists = 1);
	`
	applyPGDDL(t, sourceDSN, seedDDL)

	pgEng, _ := engines.Get("postgres")
	mig := &Migrator{
		Source:              pgEng,
		Target:              pgEng,
		SourceDSN:           sourceDSN,
		TargetDSN:           targetDSN,
		EnabledPGExtensions: []string{"vector"},
	}

	ctx, cancel := context.WithTimeout(context.Background(), 120*time.Second)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		t.Fatalf("Migrator.Run: %v", err)
	}

	tgtDB, err := sql.Open("pgx", targetDSN)
	if err != nil {
		t.Fatalf("open target: %v", err)
	}
	defer func() { _ = tgtDB.Close() }()

	// Verify the index exists on the target with USING ivfflat.
	const idxQuery = `
		SELECT am.amname
		FROM   pg_index ix
		JOIN   pg_class i  ON i.oid = ix.indexrelid
		JOIN   pg_class cl ON cl.oid = ix.indrelid
		JOIN   pg_am    am ON am.oid = i.relam
		WHERE  cl.relname = 'items'
		  AND  i.relname  LIKE '%ivfflat%'`
	var amname string
	if err := tgtDB.QueryRowContext(ctx, idxQuery).Scan(&amname); err != nil {
		t.Fatalf("index method query: %v", err)
	}
	if amname != "ivfflat" {
		t.Errorf("target index method = %q; want ivfflat", amname)
	}
}

// TestMigrate_PG_Pgvector_HNSWIndex confirms hnsw is also recognised
// and round-tripped — the second pgvector AM the catalog declares.
func TestMigrate_PG_Pgvector_HNSWIndex(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresWithPGVector(t, true)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE items (
			id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			embedding vector(3) NOT NULL
		);
		INSERT INTO items (embedding) VALUES ('[0.1, 0.2, 0.3]');

		CREATE INDEX items_embedding_hnsw
		    ON items USING hnsw (embedding vector_cosine_ops);
	`
	applyPGDDL(t, sourceDSN, seedDDL)

	pgEng, _ := engines.Get("postgres")
	mig := &Migrator{
		Source:              pgEng,
		Target:              pgEng,
		SourceDSN:           sourceDSN,
		TargetDSN:           targetDSN,
		EnabledPGExtensions: []string{"vector"},
	}

	ctx, cancel := context.WithTimeout(context.Background(), 120*time.Second)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		t.Fatalf("Migrator.Run: %v", err)
	}

	tgtDB, err := sql.Open("pgx", targetDSN)
	if err != nil {
		t.Fatalf("open target: %v", err)
	}
	defer func() { _ = tgtDB.Close() }()

	const idxQuery = `
		SELECT am.amname
		FROM   pg_index ix
		JOIN   pg_class i  ON i.oid = ix.indexrelid
		JOIN   pg_class cl ON cl.oid = ix.indrelid
		JOIN   pg_am    am ON am.oid = i.relam
		WHERE  cl.relname = 'items'
		  AND  i.relname  LIKE '%hnsw%'`
	var amname string
	if err := tgtDB.QueryRowContext(ctx, idxQuery).Scan(&amname); err != nil {
		t.Fatalf("index method query: %v", err)
	}
	if amname != "hnsw" {
		t.Errorf("target index method = %q; want hnsw", amname)
	}
}

// TestMigrate_PG_Pgvector_TargetMissing_RefusedAtPreflight pins the
// loud-failure default on a target that doesn't have pgvector
// installed. The operator gets a clean refusal at the writer-open
// preflight rather than a mid-emit error.
func TestMigrate_PG_Pgvector_TargetMissing_RefusedAtPreflight(t *testing.T) {
	// enableOnTarget=false: source has pgvector, target doesn't.
	sourceDSN, targetDSN, cleanup := startPostgresWithPGVector(t, false)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE items (
			id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			embedding vector(3) NOT NULL
		);
	`
	applyPGDDL(t, sourceDSN, seedDDL)

	pgEng, _ := engines.Get("postgres")
	mig := &Migrator{
		Source:              pgEng,
		Target:              pgEng,
		SourceDSN:           sourceDSN,
		TargetDSN:           targetDSN,
		EnabledPGExtensions: []string{"vector"},
	}

	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()
	err := mig.Run(ctx)
	if err == nil {
		t.Fatal("Migrator.Run = nil; want preflight refusal")
	}
	if !strings.Contains(err.Error(), "vector") {
		t.Errorf("err = %v; want mention of \"vector\"", err)
	}
	if !strings.Contains(err.Error(), "target") {
		t.Errorf("err = %v; want mention of \"target\"", err)
	}
}

// TestSchemaReader_PG_VectorType_NotEnabled_FallsThroughToLoudFailure
// pins the existing behaviour when --enable-pg-extension is NOT set:
// a vector column on the source surfaces a loud refusal rather than
// being silently dropped or coerced. The point of this test is to
// guard the loud-failure tenet — the framework's "opt-in" shape
// must not weaken the unsupported-type signal for operators who
// haven't opted in.
func TestSchemaReader_PG_VectorType_NotEnabled_FallsThroughToLoudFailure(t *testing.T) {
	sourceDSN, _, cleanup := startPostgresWithPGVector(t, false)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE items (
			id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			embedding vector(3) NOT NULL
		);
	`
	applyPGDDL(t, sourceDSN, seedDDL)

	pgEng, _ := engines.Get("postgres")
	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()

	sr, err := pgEng.OpenSchemaReader(ctx, sourceDSN)
	if err != nil {
		t.Fatalf("OpenSchemaReader: %v", err)
	}
	defer migcore.CloseIf(sr)

	// Deliberately do NOT call EnableExtensions. The reader's
	// USER-DEFINED dispatch should refuse the vector column at type
	// resolution time, mirroring the pre-ADR-0032 behaviour.
	_, err = sr.ReadSchema(ctx)
	if err == nil {
		t.Fatal("ReadSchema = nil; want refusal on unrecognised user-defined type")
	}
	// The exact message is engine-internal; assert on the load-bearing
	// fragment from translateType's existing user-defined-refusal path.
	if !strings.Contains(err.Error(), "vector") &&
		!strings.Contains(err.Error(), "user-defined") &&
		!strings.Contains(err.Error(), "USER-DEFINED") {
		t.Errorf("err = %v; want mention of \"vector\" or \"user-defined\"", err)
	}
}

// TestEnableExtensions_UnknownNameRefused exercises the flag-parse-
// time refusal: an unknown extension name surfaces the recognised
// set in the error message.
func TestEnableExtensions_UnknownNameRefused(t *testing.T) {
	sourceDSN, _, cleanup := startPostgresWithPGVector(t, false)
	defer cleanup()

	pgEng, _ := engines.Get("postgres")
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	sr, err := pgEng.OpenSchemaReader(ctx, sourceDSN)
	if err != nil {
		t.Fatalf("OpenSchemaReader: %v", err)
	}
	defer migcore.CloseIf(sr)

	aware, ok := sr.(ir.ExtensionAware)
	if !ok {
		t.Fatal("PG schema reader does not implement ir.ExtensionAware")
	}
	err = aware.EnableExtensions(ctx, []string{"pgvecotr"}) // typo
	if err == nil {
		t.Fatal("err = nil; want refusal on unknown extension")
	}
	if !strings.Contains(err.Error(), "not a recognised") {
		t.Errorf("err = %v; want \"not a recognised\"", err)
	}
	if !strings.Contains(err.Error(), "vector") {
		t.Errorf("err = %v; want recognised set listed (vector)", err)
	}
}
