//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// Integration pins for the closed restore-parity TRIAGE items:
//
//   - TRIAGE #3 — temporal precision shapes: a bare `timestamptz`
//     (typmod -1) must land BARE on the target — not materialize the
//     information_schema default as `timestamp(6) with time zone` —
//     while every explicitly declared precision (including 0)
//     round-trips explicit. Ground truth is
//     pg_catalog.format_type(atttypid, atttypmod) on both sides, per
//     family × shape (the Bug 74 matrix discipline).

package pipeline

import (
	"context"
	"database/sql"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/engines"
)

// pgColumnFormatTypes reads format_type(atttypid, atttypmod) for every
// user column of public.<table> — the catalog-exact type spelling
// (`timestamp with time zone` vs `timestamp(6) with time zone`).
func pgColumnFormatTypes(t *testing.T, dsn, table string) map[string]string {
	t.Helper()
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer func() { _ = db.Close() }()

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	rows, err := db.QueryContext(ctx, `
		SELECT a.attname, pg_catalog.format_type(a.atttypid, a.atttypmod)
		FROM   pg_attribute a
		JOIN   pg_class c     ON c.oid = a.attrelid
		JOIN   pg_namespace n ON n.oid = c.relnamespace
		WHERE  n.nspname = 'public' AND c.relname = $1
		  AND  a.attnum > 0 AND NOT a.attisdropped`, table)
	if err != nil {
		t.Fatalf("format_type query: %v", err)
	}
	defer func() { _ = rows.Close() }()
	out := map[string]string{}
	for rows.Next() {
		var col, ft string
		if err := rows.Scan(&col, &ft); err != nil {
			t.Fatalf("scan: %v", err)
		}
		out[col] = ft
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}
	return out
}

// TestMigrate_PG_TemporalPrecisionShapes pins TRIAGE #3 end-to-end on
// real PG: every temporal family member × {bare, (0), mid, (6)}
// round-trips to the byte-identical catalog spelling.
func TestMigrate_PG_TemporalPrecisionShapes(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE temporal_shapes (
			id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			ts_bare   TIMESTAMPTZ,
			ts_p0     TIMESTAMPTZ(0),
			ts_p3     TIMESTAMPTZ(3),
			ts_p6     TIMESTAMPTZ(6),
			dt_bare   TIMESTAMP,
			dt_p0     TIMESTAMP(0),
			dt_p3     TIMESTAMP(3),
			dt_p6     TIMESTAMP(6),
			tm_bare   TIME,
			tm_p0     TIME(0),
			tm_p4     TIME(4),
			tm_p6     TIME(6),
			tmtz_bare TIME WITH TIME ZONE,
			tmtz_p0   TIME(0) WITH TIME ZONE,
			tmtz_p2   TIME(2) WITH TIME ZONE,
			tmtz_p6   TIME(6) WITH TIME ZONE,
			ts_arr    TIMESTAMPTZ[]
		);
		INSERT INTO temporal_shapes
			(ts_bare, ts_p0, ts_p3, ts_p6, dt_bare, dt_p0, dt_p3, dt_p6,
			 tm_bare, tm_p0, tm_p4, tm_p6, tmtz_bare, tmtz_p0, tmtz_p2, tmtz_p6, ts_arr)
		VALUES
			('2026-01-02 03:04:05.123456+00', '2026-01-02 03:04:05+00',
			 '2026-01-02 03:04:05.123+00', '2026-01-02 03:04:05.123456+00',
			 '2026-01-02 03:04:05.123456', '2026-01-02 03:04:05',
			 '2026-01-02 03:04:05.123', '2026-01-02 03:04:05.123456',
			 '03:04:05.123456', '03:04:05', '03:04:05.1234', '03:04:05.123456',
			 '03:04:05.123456+02', '03:04:05+02', '03:04:05.12+02', '03:04:05.123456+02',
			 ARRAY['2026-01-02 03:04:05.123456+00'::timestamptz]);`
	applyPGDDL(t, sourceDSN, seedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}
	mig := &Migrator{
		Source:    pgEng,
		Target:    pgEng,
		SourceDSN: sourceDSN,
		TargetDSN: targetDSN,
	}
	ctx, cancel := context.WithTimeout(context.Background(), 4*time.Minute)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		t.Fatalf("Migrator.Run: %v", err)
	}

	src := pgColumnFormatTypes(t, sourceDSN, "temporal_shapes")
	tgt := pgColumnFormatTypes(t, targetDSN, "temporal_shapes")
	for col, want := range src {
		if got := tgt[col]; got != want {
			t.Errorf("temporal_shapes.%s: target format_type = %q; want %q (source)", col, got, want)
		}
	}
	// Belt-and-braces on the headline shapes so a query regression
	// can't silently pass the loop above with empty maps.
	if src["ts_bare"] != "timestamp with time zone" {
		t.Fatalf("source ts_bare format_type = %q; harness assumption broken", src["ts_bare"])
	}
	if src["ts_p0"] != "timestamp(0) with time zone" {
		t.Fatalf("source ts_p0 format_type = %q; harness assumption broken", src["ts_p0"])
	}
}
