//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// Integration tests for the resumable simple-mode migration path.
// All tests run against Postgres on both sides because PG is the
// fastest engine pair to spin up via testcontainers; the resume
// orchestration itself is engine-neutral, so a working PG→PG resume
// confirms the pipeline-level surface. MySQL coverage can come later
// without changing the orchestration code.

package pipeline

import (
	"context"
	"database/sql"
	"errors"
	"strings"
	"testing"
	"time"

	"github.com/orware/sluice/internal/engines"
	"github.com/orware/sluice/internal/ir"

	// Register the postgres engine so engines.Get("postgres") works.
	_ "github.com/orware/sluice/internal/engines/postgres"
)

// failingRowWriterEngine wraps the real Postgres engine so a chosen
// table fails partway through bulk-copy. Used to drive the
// "failure recorded → --resume completes the rest" integration path.
//
// The wrapper delegates everything except OpenRowWriter to the real
// engine; OpenRowWriter returns a writer whose WriteRows aborts after
// `failAfterRows` rows on the named table. All other tables use the
// real writer so the resume path's "skip already-completed table"
// branch gets exercised.
type failingRowWriterEngine struct {
	ir.Engine
	failTable     string
	failAfterRows int
}

func (f *failingRowWriterEngine) OpenRowWriter(ctx context.Context, dsn string) (ir.RowWriter, error) {
	real, err := f.Engine.OpenRowWriter(ctx, dsn)
	if err != nil {
		return nil, err
	}
	return &failingRowWriter{inner: real, failTable: f.failTable, failAfterRows: f.failAfterRows}, nil
}

// OpenMigrationStateStore forwards to the wrapped engine's optional
// surface. The embedded ir.Engine interface doesn't include this
// method, so the type assertion in pipeline.openMigrationStateStore
// would otherwise miss it. Forwarding keeps resume state persisted
// during the failure-injection test.
func (f *failingRowWriterEngine) OpenMigrationStateStore(ctx context.Context, dsn string) (ir.MigrationStateStore, error) {
	opener, ok := f.Engine.(ir.MigrationStateStoreOpener)
	if !ok {
		return nil, errors.New("inner engine does not implement MigrationStateStoreOpener")
	}
	return opener.OpenMigrationStateStore(ctx, dsn)
}

// failingRowWriter aborts the WriteRows call for the named table
// after a fixed number of rows, returning a sentinel error. Other
// tables pass through unchanged.
type failingRowWriter struct {
	inner         ir.RowWriter
	failTable     string
	failAfterRows int
}

var errFailingRowWriter = errors.New("simulated mid-bulk-copy failure")

func (f *failingRowWriter) WriteRows(ctx context.Context, table *ir.Table, rows <-chan ir.Row) error {
	if table.Name != f.failTable {
		return f.inner.WriteRows(ctx, table, rows)
	}
	// Write `failAfterRows` rows then return without draining the
	// rest. The orchestrator surfaces the error and the resume path
	// then sees a partial table — what we want to test. A bounded
	// channel feeds the inner writer just the prefix; closing it
	// lets the inner writer commit before we report failure.
	bounded := make(chan ir.Row, f.failAfterRows)
	count := 0
	for row := range rows {
		if count < f.failAfterRows {
			bounded <- row
			count++
			continue
		}
		break
	}
	close(bounded)
	// Inner writer drains the buffered prefix, then sees a closed
	// channel and returns. We then report the failure regardless.
	if err := f.inner.WriteRows(ctx, table, bounded); err != nil {
		return err
	}
	return errFailingRowWriter
}

// TruncateTable on failingRowWriter passes through to the inner
// writer's TableTruncator surface (the real Postgres RowWriter
// implements it). Without this passthrough, resume's truncate path
// would refuse with "no TRUNCATE support" and the test would never
// get to the re-copy.
func (f *failingRowWriter) TruncateTable(ctx context.Context, table *ir.Table) error {
	t, ok := f.inner.(ir.TableTruncator)
	if !ok {
		return errors.New("inner writer does not implement TableTruncator")
	}
	return t.TruncateTable(ctx, table)
}

// TestMigrate_ResumeFromBulkCopyFailure: run a migration that fails
// mid-bulk-copy, then re-run with --resume and confirm every row
// landed on the target.
func TestMigrate_ResumeFromBulkCopyFailure(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()

	// Two tables; "orders" gets the failure injection.
	const seedDDL = `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL
		);
		CREATE TABLE orders (
			id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			amount BIGINT NOT NULL
		);
		INSERT INTO users (email) VALUES ('a@example.com'), ('b@example.com'), ('c@example.com');
		INSERT INTO orders (amount)
			SELECT g FROM generate_series(1, 50) g;
	`
	applyPGDDL(t, sourceDSN, seedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	// Attempt 1: orders fails after 10 rows.
	failEng := &failingRowWriterEngine{Engine: pgEng, failTable: "orders", failAfterRows: 10}

	mig := &Migrator{
		Source:      pgEng,
		Target:      failEng,
		SourceDSN:   sourceDSN,
		TargetDSN:   targetDSN,
		MigrationID: "test-resume-1",
	}
	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()
	err := mig.Run(ctx)
	if err == nil {
		t.Fatal("expected first attempt to fail; got nil")
	}
	if !strings.Contains(err.Error(), "simulated mid-bulk-copy failure") {
		t.Errorf("first-attempt err = %v; want simulated failure", err)
	}

	// State row should record the bulk_copy phase + the in-progress
	// orders table.
	state := readState(t, targetDSN, "test-resume-1")
	if state.Phase != ir.MigrationPhaseBulkCopy {
		t.Errorf("after-failure phase = %q; want bulk_copy", state.Phase)
	}

	// Attempt 2: real engine, --resume, same migration ID.
	mig2 := &Migrator{
		Source:      pgEng,
		Target:      pgEng,
		SourceDSN:   sourceDSN,
		TargetDSN:   targetDSN,
		MigrationID: "test-resume-1",
		Resume:      true,
	}
	if err := mig2.Run(ctx); err != nil {
		t.Fatalf("resume Run: %v", err)
	}

	// Confirm all rows present on target.
	if got := countRows(t, targetDSN, "users"); got != 3 {
		t.Errorf("users row count = %d; want 3", got)
	}
	if got := countRows(t, targetDSN, "orders"); got != 50 {
		t.Errorf("orders row count = %d; want 50", got)
	}

	finalState := readState(t, targetDSN, "test-resume-1")
	if finalState.Phase != ir.MigrationPhaseComplete {
		t.Errorf("final phase = %q; want complete", finalState.Phase)
	}
}

// TestMigrate_ResumeAlreadyComplete confirms a no-op resume against a
// completed migration logs the right message and exits cleanly
// without touching target state.
func TestMigrate_ResumeAlreadyComplete(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE users (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL
		);
		INSERT INTO users (email) VALUES ('alice@example.com');
	`
	applyPGDDL(t, sourceDSN, seedDDL)

	pgEng, _ := engines.Get("postgres")

	mig := &Migrator{
		Source:      pgEng,
		Target:      pgEng,
		SourceDSN:   sourceDSN,
		TargetDSN:   targetDSN,
		MigrationID: "test-resume-complete",
	}
	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		t.Fatalf("first Run: %v", err)
	}

	mig2 := &Migrator{
		Source:      pgEng,
		Target:      pgEng,
		SourceDSN:   sourceDSN,
		TargetDSN:   targetDSN,
		MigrationID: "test-resume-complete",
		Resume:      true,
	}
	if err := mig2.Run(ctx); err != nil {
		t.Fatalf("resume Run on completed migration errored: %v", err)
	}

	state := readState(t, targetDSN, "test-resume-complete")
	if state.Phase != ir.MigrationPhaseComplete {
		t.Errorf("post-resume phase = %q; want complete", state.Phase)
	}
}

// TestMigrate_NoResumeRefusesPartial: a failed migration that's
// re-run WITHOUT --resume errors out rather than silently
// overwriting.
func TestMigrate_NoResumeRefusesPartial(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE orders (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			amount BIGINT NOT NULL
		);
		INSERT INTO orders (amount)
			SELECT g FROM generate_series(1, 20) g;
	`
	applyPGDDL(t, sourceDSN, seedDDL)

	pgEng, _ := engines.Get("postgres")

	failEng := &failingRowWriterEngine{Engine: pgEng, failTable: "orders", failAfterRows: 5}
	mig := &Migrator{
		Source:      pgEng,
		Target:      failEng,
		SourceDSN:   sourceDSN,
		TargetDSN:   targetDSN,
		MigrationID: "test-resume-refuse",
	}
	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()
	if err := mig.Run(ctx); err == nil {
		t.Fatal("expected first attempt to fail")
	}

	// Re-run WITHOUT --resume — should refuse with the partial-
	// migration message.
	mig2 := &Migrator{
		Source:      pgEng,
		Target:      pgEng,
		SourceDSN:   sourceDSN,
		TargetDSN:   targetDSN,
		MigrationID: "test-resume-refuse",
		Resume:      false,
	}
	err := mig2.Run(ctx)
	if err == nil {
		t.Fatal("re-run without --resume succeeded; want refusal")
	}
	if !strings.Contains(err.Error(), "partial migration") {
		t.Errorf("err = %v; want 'partial migration' wording", err)
	}
}

// readState fetches the state row for migrationID via a direct query.
// Used by the resume integration tests to assert the persisted phase
// after a failure / success.
func readState(t *testing.T, dsn, migrationID string) ir.MigrationState {
	t.Helper()
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer func() { _ = db.Close() }()

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	const q = `SELECT phase FROM "public"."sluice_migrate_state" WHERE migration_id = $1`
	var phase string
	if err := db.QueryRowContext(ctx, q, migrationID).Scan(&phase); err != nil {
		t.Fatalf("readState: %v", err)
	}
	return ir.MigrationState{MigrationID: migrationID, Phase: ir.MigrationPhase(phase)}
}
