//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// GC-4 end to end: a SQLite source's single-column integer PRIMARY KEY lands
// on every target as an auto-assigning key EXACTLY when SQLite itself
// auto-assigns it — the rowid alias (`INTEGER PRIMARY KEY` in a rowid table)
// — and as a plain key otherwise (`BIGINT PRIMARY KEY`, which SQLite stores
// NULL into; `INTEGER PRIMARY KEY` in a `WITHOUT ROWID` table, which it
// refuses NOT NULL). Before the fix the reader marked all three as
// auto-incrementing, so Postgres got `GENERATED BY DEFAULT AS IDENTITY` and
// MySQL `AUTO_INCREMENT` for keys the source never assigned, and the SQLite
// writer spelled every integer PK as the alias.
//
// The three tables are the three measured classes of
// engines/sqlite's TestRowidAlias_ReaderAndWriterMatchTheDriver; this file
// carries them across the pipeline to each real target and reads the
// target's own catalog for the auto-assign fact.

package pipeline

import (
	"context"
	"database/sql"
	"path/filepath"
	"strings"
	"testing"

	"sluicesync.dev/sluice/internal/engines"

	_ "sluicesync.dev/sluice/internal/engines/mysql"
	_ "sluicesync.dev/sluice/internal/engines/postgres"
	_ "sluicesync.dev/sluice/internal/engines/sqlite"
)

// rowidAliasTables maps each seeded table to whether SQLite auto-assigns its
// key. The expectation is MEASURED on the source file by
// seedSQLiteRowidAliasSource (a NULL insert), not written here.
var rowidAliasTables = []string{"alias_pk", "bigint_pk", "norowid_pk"}

// seedSQLiteRowidAliasSource writes the three-table source and returns its
// path plus, per table, whether the source auto-assigned a NULL key —
// measured on a scratch copy of each table so the migrated file is untouched.
func seedSQLiteRowidAliasSource(t *testing.T) (path string, autoAssigns map[string]bool) {
	t.Helper()
	ddl := map[string]string{
		"alias_pk":   `CREATE TABLE alias_pk (id INTEGER PRIMARY KEY, v TEXT NOT NULL)`,
		"bigint_pk":  `CREATE TABLE bigint_pk (id BIGINT PRIMARY KEY, v TEXT NOT NULL)`,
		"norowid_pk": `CREATE TABLE norowid_pk (id INTEGER PRIMARY KEY, v TEXT NOT NULL) WITHOUT ROWID`,
	}
	path = filepath.Join(t.TempDir(), "rowid-alias.db")
	db, err := sql.Open("sqlite", path)
	if err != nil {
		t.Fatalf("open sqlite seed: %v", err)
	}
	defer func() { _ = db.Close() }()
	ctx := context.Background()
	autoAssigns = map[string]bool{}
	for _, name := range rowidAliasTables {
		if _, err := db.ExecContext(ctx, ddl[name]); err != nil {
			t.Fatalf("seed %s: %v", name, err)
		}
		if _, err := db.ExecContext(ctx, `INSERT INTO `+name+` (id, v) VALUES (7, 'seven')`); err != nil {
			t.Fatalf("seed row %s: %v", name, err)
		}
		// Measure on a scratch copy: same DDL, NULL key.
		scratch := filepath.Join(t.TempDir(), name+"-probe.db")
		pdb, err := sql.Open("sqlite", scratch)
		if err != nil {
			t.Fatalf("open probe: %v", err)
		}
		if _, err := pdb.ExecContext(ctx, ddl[name]); err != nil {
			t.Fatalf("probe ddl %s: %v", name, err)
		}
		autoAssigns[name] = sqliteAutoAssignsNullKey(t, pdb, name)
		_ = pdb.Close()
	}
	if !autoAssigns["alias_pk"] || autoAssigns["bigint_pk"] || autoAssigns["norowid_pk"] {
		t.Fatalf("premise: measured auto-assign = %v; the matrix expects only alias_pk to auto-assign", autoAssigns)
	}
	return path, autoAssigns
}

// sqliteAutoAssignsNullKey inserts a NULL key into table and reports whether
// SQLite assigned a value (true), or stored NULL / refused NOT NULL (false).
func sqliteAutoAssignsNullKey(t *testing.T, db *sql.DB, table string) bool {
	t.Helper()
	ctx := context.Background()
	if _, err := db.ExecContext(ctx, `INSERT INTO "`+table+`" (id, v) VALUES (NULL, 'probe')`); err != nil {
		if strings.Contains(err.Error(), "NOT NULL") {
			return false
		}
		t.Fatalf("probe insert into %s: %v", table, err)
	}
	var id sql.NullInt64
	if err := db.QueryRowContext(ctx, `SELECT id FROM "`+table+`" WHERE v = 'probe'`).Scan(&id); err != nil {
		t.Fatalf("probe read %s: %v", table, err)
	}
	return id.Valid
}

// TestMigrate_SQLiteRowidAlias_ToPostgres: pg_attribute.attidentity is 'd'
// (GENERATED BY DEFAULT) for the alias and empty for the two plain keys.
func TestMigrate_SQLiteRowidAlias_ToPostgres(t *testing.T) {
	src, autoAssigns := seedSQLiteRowidAliasSource(t)
	_, pgTarget, cleanup := startPostgres(t)
	defer cleanup()

	sqliteEng, _ := engines.Get("sqlite")
	pgEng, _ := engines.Get("postgres")
	mig := &Migrator{Source: sqliteEng, Target: pgEng, SourceDSN: src, TargetDSN: pgTarget}
	if err := mig.Run(ctx2min(t)); err != nil {
		t.Fatalf("Migrator.Run (SQLite→PG): %v", err)
	}

	db, err := sql.Open("pgx", pgTarget)
	if err != nil {
		t.Fatalf("open pg target: %v", err)
	}
	defer func() { _ = db.Close() }()
	for _, name := range rowidAliasTables {
		var identity string
		if err := db.QueryRowContext(
			ctx2min(t),
			`SELECT attidentity::text FROM pg_attribute WHERE attrelid = ('public.'||quote_ident($1))::regclass AND attname = 'id'`,
			name,
		).Scan(&identity); err != nil {
			t.Fatalf("read attidentity for %s: %v", name, err)
		}
		if got := identity != ""; got != autoAssigns[name] {
			t.Errorf("%s.id on PG: identity=%q (auto-assigns=%v); source auto-assigns=%v",
				name, identity, got, autoAssigns[name])
		}
	}
}

// TestMigrate_SQLiteRowidAlias_ToMySQL: information_schema EXTRA carries
// auto_increment for the alias only.
func TestMigrate_SQLiteRowidAlias_ToMySQL(t *testing.T) {
	src, autoAssigns := seedSQLiteRowidAliasSource(t)
	_, myTarget, cleanup := startMySQL(t)
	defer cleanup()

	sqliteEng, _ := engines.Get("sqlite")
	myEng, _ := engines.Get("mysql")
	mig := &Migrator{Source: sqliteEng, Target: myEng, SourceDSN: src, TargetDSN: myTarget}
	if err := mig.Run(ctx2min(t)); err != nil {
		t.Fatalf("Migrator.Run (SQLite→MySQL): %v", err)
	}

	db, err := sql.Open("mysql", myTarget)
	if err != nil {
		t.Fatalf("open mysql target: %v", err)
	}
	defer func() { _ = db.Close() }()
	for _, name := range rowidAliasTables {
		var extra string
		if err := db.QueryRowContext(
			ctx2min(t),
			`SELECT EXTRA FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ? AND COLUMN_NAME = 'id'`,
			name,
		).Scan(&extra); err != nil {
			t.Fatalf("read EXTRA for %s: %v", name, err)
		}
		if got := strings.Contains(strings.ToLower(extra), "auto_increment"); got != autoAssigns[name] {
			t.Errorf("%s.id on MySQL: EXTRA=%q (auto-assigns=%v); source auto-assigns=%v",
				name, extra, got, autoAssigns[name])
		}
	}
}

// TestMigrate_PostgresIntegerPK_ToSQLite_AutoAssignMatchesSource is the
// reverse cell for the SQLite WRITER: a Postgres identity key must land as
// the auto-assigning rowid alias, and a plain BIGINT PRIMARY KEY (which PG
// never auto-assigns and refuses NULL on) must land as a key SQLite refuses
// NULL on — measured on the produced file, not inferred from the DDL.
func TestMigrate_PostgresIntegerPK_ToSQLite_AutoAssignMatchesSource(t *testing.T) {
	pgSource, _, cleanup := startPostgres(t)
	defer cleanup()
	applyPGDDL(t, pgSource, `
		DROP TABLE IF EXISTS public.ident_pk, public.plain_pk;
		CREATE TABLE public.ident_pk (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, v TEXT NOT NULL);
		CREATE TABLE public.plain_pk (id BIGINT PRIMARY KEY, v TEXT NOT NULL);
		INSERT INTO public.ident_pk (id, v) VALUES (7, 'seven');
		INSERT INTO public.plain_pk (id, v) VALUES (7, 'seven');
	`)
	dst := filepath.Join(t.TempDir(), "from-pg.db")
	pgEng, _ := engines.Get("postgres")
	sqliteEng, _ := engines.Get("sqlite")
	mig := &Migrator{Source: pgEng, Target: sqliteEng, SourceDSN: pgSource, TargetDSN: dst}
	if err := mig.Run(ctx2min(t)); err != nil {
		t.Fatalf("Migrator.Run (PG→SQLite): %v", err)
	}
	db, err := sql.Open("sqlite", dst)
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = db.Close() }()
	if !sqliteAutoAssignsNullKey(t, db, "ident_pk") {
		t.Error("ident_pk.id on the SQLite target does not auto-assign; the PG identity was lost")
	}
	// plain_pk: PG refuses NULL on a PK; the target must refuse too (a NOT
	// NULL refusal), never assign a value the source would have rejected.
	if _, err := db.ExecContext(ctx2min(t), `INSERT INTO "plain_pk" (id, v) VALUES (NULL, 'probe')`); err == nil ||
		!strings.Contains(err.Error(), "NOT NULL") {
		t.Errorf("plain_pk.id on the SQLite target accepted a NULL key (err=%v); want a NOT NULL refusal like the source", err)
	}
}

// TestMigrate_SQLiteRowidAlias_ToSQLite: the SQLite writer's sibling of the
// same class — the target file auto-assigns a NULL key exactly where the
// source did, measured on both sides. No container needed.
func TestMigrate_SQLiteRowidAlias_ToSQLite(t *testing.T) {
	src, autoAssigns := seedSQLiteRowidAliasSource(t)
	dst := filepath.Join(t.TempDir(), "rowid-alias-target.db")

	sqliteEng, _ := engines.Get("sqlite")
	mig := &Migrator{Source: sqliteEng, Target: sqliteEng, SourceDSN: src, TargetDSN: dst}
	if err := mig.Run(ctx2min(t)); err != nil {
		t.Fatalf("Migrator.Run (SQLite→SQLite): %v", err)
	}

	db, err := sql.Open("sqlite", dst)
	if err != nil {
		t.Fatalf("open sqlite target: %v", err)
	}
	defer func() { _ = db.Close() }()
	for _, name := range rowidAliasTables {
		var n int
		if err := db.QueryRowContext(ctx2min(t), `SELECT COUNT(*) FROM "`+name+`"`).Scan(&n); err != nil {
			t.Fatalf("count %s: %v", name, err)
		}
		if n != 1 {
			t.Errorf("%s rows on target = %d; want 1", name, n)
		}
		if got := sqliteAutoAssignsNullKey(t, db, name); got != autoAssigns[name] {
			t.Errorf("%s.id on the SQLite target auto-assigns=%v; source auto-assigns=%v", name, got, autoAssigns[name])
		}
	}
}
