//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// Pinning integration test for the same-engine PG → PG schema-fidelity
// fixes from battle-test pass 3 (validation BUG-CATALOG #17 + #19a–d):
//
//   - #19a partial-index WHERE predicate + per-column DESC / NULLS
//   - #19b covering-index INCLUDE (non-key) columns
//   - #19c user-defined enum type name preservation
//   - #19d table & column COMMENTs
//   - #17  core type tsvector carried verbatim PG → PG
//
// Each was a silent fidelity loss (exit 0, wrong target) before the
// fix. This test ground-truths source vs target via the PG catalog
// (pg_indexes / pg_get_indexdef / pg_type / obj_description /
// format_type) so the fixes cannot silently regress.

package pipeline

import (
	"context"
	"database/sql"
	"strings"
	"testing"
	"time"

	"github.com/orware/sluice/internal/engines"

	_ "github.com/orware/sluice/internal/engines/postgres"
)

func TestMigrate_PG_SchemaFidelity_Pass3(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()

	const seedDDL = `
		CREATE TYPE post_status AS ENUM ('draft','published','archived','deleted');

		CREATE TABLE accounts (
			id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			handle TEXT NOT NULL
		);
		COMMENT ON TABLE accounts IS 'user accounts (self-ref manager FK)';
		COMMENT ON COLUMN accounts.handle IS 'public stable id';

		CREATE TABLE posts (
			id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			account_id   BIGINT NOT NULL,
			title        TEXT   NOT NULL,
			score        INT    NOT NULL DEFAULT 0,
			status       post_status NOT NULL DEFAULT 'draft',
			published_at TIMESTAMP,
			search       tsvector
		);

		-- #19a: partial index, DESC ordering.
		CREATE INDEX ix_posts_published ON posts USING btree (published_at DESC)
			WHERE (status = 'published'::post_status);

		-- #19b: covering index with INCLUDE payload columns.
		CREATE INDEX ix_posts_acct ON posts USING btree (account_id)
			INCLUDE (title, score);

		-- #19a: explicit non-default NULLS ordering.
		CREATE INDEX ix_posts_score ON posts USING btree (score ASC NULLS FIRST);

		INSERT INTO accounts (handle) VALUES ('alice'),('bob');
		INSERT INTO posts (account_id, title, status, search)
			VALUES (1,'hello','published', to_tsvector('english','hello world'));
	`
	applyPGDDL(t, sourceDSN, seedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	// #23 preview/migrate parity: `schema preview` must NOT loud-refuse
	// a type `migrate` carries verbatim. Pre-fix, preview never called
	// applyVerbatimExtensionPassthrough, so it refused the `search
	// tsvector` column while migrate (below) carried it fine — a
	// preview/migrate inconsistency. Run the previewer over the SAME
	// tsvector-bearing PG source and assert it succeeds and renders the
	// column.
	{
		var pbuf strings.Builder
		prev := &Previewer{
			Source:    pgEng,
			Target:    pgEng,
			SourceDSN: sourceDSN,
			TargetDSN: targetDSN,
			Format:    "text",
			Out:       &pbuf,
		}
		pctx, pcancel := context.WithTimeout(context.Background(), 60*time.Second)
		if err := prev.Run(pctx); err != nil {
			pcancel()
			t.Fatalf("#23: schema preview refused a tsvector-bearing PG→PG schema that migrate carries: %v", err)
		}
		pcancel()
		if !strings.Contains(pbuf.String(), "tsvector") {
			t.Errorf("#23: preview should render the tsvector column; got:\n%s", pbuf.String())
		}
	}

	mig := &Migrator{
		Source:    pgEng,
		Target:    pgEng,
		SourceDSN: sourceDSN,
		TargetDSN: targetDSN,
	}
	ctx, cancel := context.WithTimeout(context.Background(), 120*time.Second)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		t.Fatalf("Migrator.Run: %v", err)
	}

	db, err := sql.Open("pgx", targetDSN)
	if err != nil {
		t.Fatalf("open target: %v", err)
	}
	defer func() { _ = db.Close() }()

	indexDef := func(name string) string {
		var def string
		if err := db.QueryRowContext(ctx,
			`SELECT indexdef FROM pg_indexes WHERE indexname=$1`, name).Scan(&def); err != nil {
			t.Fatalf("pg_indexes %s: %v", name, err)
		}
		return def
	}

	// #19a — partial predicate + DESC must survive.
	pub := indexDef("ix_posts_published")
	if !containsAll(pub, "DESC", "WHERE", "published") {
		t.Errorf("#19a: ix_posts_published lost predicate/DESC: %q", pub)
	}

	// #19b — INCLUDE columns must stay non-key, not flattened, AND
	// keep their declared order (the reader's `ORDER BY u.ord`
	// guarantees ordinal order; pin the exact rendered clause so a
	// future query/loop change can't silently scramble or drop it).
	acct := indexDef("ix_posts_acct")
	if !strings.Contains(acct, "INCLUDE (title, score)") {
		t.Errorf("#19b: ix_posts_acct lost/reordered INCLUDE (want exact %q): %q",
			"INCLUDE (title, score)", acct)
	}
	// title/score must NOT have been promoted into the key list.
	if containsAll(acct, "(account_id, title") {
		t.Errorf("#19b: INCLUDE columns flattened into key: %q", acct)
	}

	// #19a — explicit NULLS FIRST on an ASC column preserved.
	score := indexDef("ix_posts_score")
	if !containsAll(score, "NULLS FIRST") {
		t.Errorf("#19a: ix_posts_score lost NULLS FIRST: %q", score)
	}

	// #19c — enum type name preserved verbatim (not synthesized).
	var enumName string
	if err := db.QueryRowContext(ctx,
		`SELECT t.typname FROM pg_type t WHERE t.typtype='e' AND t.typname='post_status'`,
	).Scan(&enumName); err != nil {
		t.Errorf("#19c: enum type 'post_status' not found on target (renamed?): %v", err)
	}

	// #19d — table & column comments preserved.
	var tblComment, colComment sql.NullString
	if err := db.QueryRowContext(ctx,
		`SELECT obj_description('accounts'::regclass,'pg_class')`).Scan(&tblComment); err != nil {
		t.Fatalf("obj_description: %v", err)
	}
	if tblComment.String != "user accounts (self-ref manager FK)" {
		t.Errorf("#19d: table comment = %q; want preserved", tblComment.String)
	}
	if err := db.QueryRowContext(ctx,
		`SELECT col_description('accounts'::regclass,
			(SELECT attnum FROM pg_attribute WHERE attrelid='accounts'::regclass AND attname='handle'))`,
	).Scan(&colComment); err != nil {
		t.Fatalf("col_description: %v", err)
	}
	if colComment.String != "public stable id" {
		t.Errorf("#19d: column comment = %q; want 'public stable id'", colComment.String)
	}

	// #17 — tsvector column carried verbatim (type + data).
	var tsvType string
	if err := db.QueryRowContext(ctx,
		`SELECT format_type(a.atttypid, a.atttypmod)
		   FROM pg_attribute a
		  WHERE a.attrelid='posts'::regclass AND a.attname='search'`,
	).Scan(&tsvType); err != nil {
		t.Errorf("#17: tsvector column 'search' missing on target: %v", err)
	}
	if tsvType != "tsvector" {
		t.Errorf("#17: search column type = %q; want tsvector", tsvType)
	}
	var tsvCount int
	if err := db.QueryRowContext(ctx,
		`SELECT count(*) FROM posts WHERE search IS NOT NULL`).Scan(&tsvCount); err != nil {
		t.Fatalf("tsvector data count: %v", err)
	}
	if tsvCount != 1 {
		t.Errorf("#17: tsvector data not carried; non-null rows = %d want 1", tsvCount)
	}
}

func containsAll(s string, subs ...string) bool {
	for _, sub := range subs {
		if !strings.Contains(s, sub) {
			return false
		}
	}
	return true
}
