//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// ADR-0047 verbatim (uncatalogued) PG extension passthrough
// integration tests. Exercises the passthrough tier *below* the
// ADR-0032 catalog: a column whose type is owned by an extension
// sluice does NOT catalogue (here `ltree`, in the standard postgres
// contrib bundle — the stock postgres:16 image CI pre-pulls works
// as-is, like the hstore/citext/pg_trgm suites).
//
// Coverage (mirrors the ADR §Testing matrix):
//
//   - Same-engine PG → PG migrate: the ltree type DDL round-trips
//     verbatim (no --enable-pg-extension flag — the determination is
//     implicit from same-engine identity), values round-trip via the
//     type's text I/O, and the extension-owned GiST opclass
//     (`gist_ltree_ops`) on a core-PG `gist` AM round-trips (the
//     Bug 47 verbatim-opclass path).
//   - Backup → the lineage segment records the verbatim capability
//     marker → PG restore reproduces the column + values exactly.
//   - A verbatim-marked backup restored to MySQL → LOUD refusal at
//     preflight (the load-bearing safety pin).
//   - Regression: cross-engine PG → MySQL migrate with an
//     uncatalogued type still loud-refuses (the cross-engine default
//     is NOT weakened by the same-engine verbatim tier).

package pipeline

import (
	"context"
	"database/sql"
	"strings"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/engines"
	"sluicesync.dev/sluice/internal/ir"
	"sluicesync.dev/sluice/internal/pipeline/blobcodec"
	"sluicesync.dev/sluice/internal/pipeline/lineage"
	"sluicesync.dev/sluice/internal/pipeline/migcore"

	_ "sluicesync.dev/sluice/internal/engines/mysql"
	_ "sluicesync.dev/sluice/internal/engines/postgres"
)

// seedLtreeDDL builds a table whose `path` column is the uncatalogued
// `ltree` type, plus a GiST index using the extension-owned
// `gist_ltree_ops` opclass over a core-PG `gist` access method (the
// Bug 47 verbatim-opclass shape).
const seedLtreeDDL = `
	CREATE TABLE catalog_tree (
		id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		name VARCHAR(64) NOT NULL,
		path ltree NOT NULL
	);
	CREATE INDEX catalog_tree_path_gist
		ON catalog_tree USING gist (path gist_ltree_ops);

	INSERT INTO catalog_tree (name, path) VALUES
		('root',  'Top'),
		('sci',   'Top.Science'),
		('astro', 'Top.Science.Astronomy');
`

// TestMigrate_PG_Verbatim_Ltree_Passthrough is the ADR-0047 same-engine
// happy path. NOTE: no EnabledPGExtensions — the verbatim tier is
// implicit from same-engine PG → PG identity (ADR-0047 §3).
func TestMigrate_PG_Verbatim_Ltree_Passthrough(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresWithExtension(t, "ltree", true)
	defer cleanup()
	applyPGDDL(t, sourceDSN, seedLtreeDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	mig := &Migrator{
		Source:    pgEng,
		Target:    pgEng,
		SourceDSN: sourceDSN,
		TargetDSN: targetDSN,
		// Deliberately NO EnabledPGExtensions — ADR-0047 determination
		// is implicit for same-engine PG → PG.
	}
	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		t.Fatalf("Migrator.Run: %v", err)
	}

	tgtDB, err := sql.Open("pgx", targetDSN)
	if err != nil {
		t.Fatalf("open target: %v", err)
	}
	defer func() { _ = tgtDB.Close() }()

	// Column type re-created verbatim as ltree.
	var formatType string
	if err := tgtDB.QueryRowContext(ctx, `
		SELECT pg_catalog.format_type(a.atttypid, a.atttypmod)
		FROM pg_attribute a
		JOIN pg_class c ON c.oid = a.attrelid
		WHERE c.relname = 'catalog_tree' AND a.attname = 'path'`).Scan(&formatType); err != nil {
		t.Fatalf("format_type query: %v", err)
	}
	if formatType != "ltree" {
		t.Errorf("target catalog_tree.path type = %q; want \"ltree\" (verbatim)", formatType)
	}

	// Values round-trip via text I/O.
	var n int
	if err := tgtDB.QueryRowContext(ctx, "SELECT COUNT(*) FROM catalog_tree").Scan(&n); err != nil {
		t.Fatalf("count: %v", err)
	}
	if n != 3 {
		t.Errorf("target rows = %d; want 3", n)
	}
	var astro string
	if err := tgtDB.QueryRowContext(ctx,
		"SELECT path::text FROM catalog_tree WHERE name = 'astro'").Scan(&astro); err != nil {
		t.Fatalf("read astro path: %v", err)
	}
	if astro != "Top.Science.Astronomy" {
		t.Errorf("astro path = %q; want \"Top.Science.Astronomy\"", astro)
	}

	// The GiST index over the verbatim ltree column round-tripped.
	// NOTE: gist_ltree_ops is ltree's DEFAULT gist opclass
	// (pg_opclass.opcdefault = t), so PG's pg_get_indexdef omits the
	// opclass spelling on BOTH source and target — the round-trip is
	// functionally exact even though the opclass bareword isn't echoed
	// in indexdef. Sluice still populates ir.IndexColumn.OperatorClass
	// for it (the Bug 47 invariant: extension-owned opclass → non-
	// empty), which is what makes a verbatim backup correctly refuse a
	// cross-engine restore for free. We assert the index exists, uses
	// the gist AM over `path`, and is actually usable for an ltree
	// ancestor query (the load-bearing functional property).
	var idxDef string
	if err := tgtDB.QueryRowContext(ctx, `
		SELECT indexdef FROM pg_indexes
		WHERE tablename = 'catalog_tree' AND indexname = 'catalog_tree_path_gist'`).Scan(&idxDef); err != nil {
		t.Fatalf("indexdef query: %v", err)
	}
	if !strings.Contains(idxDef, "USING gist") || !strings.Contains(idxDef, "path") {
		t.Errorf("target index def = %q; want USING gist over (path)", idxDef)
	}
	// The IR carried the extension-owned opclass (Bug 47 invariant
	// under the verbatim tier). Read it back through sluice's reader.
	{
		ir2, err := pgEng.OpenSchemaReader(ctx, targetDSN)
		if err != nil {
			t.Fatalf("OpenSchemaReader (opclass check): %v", err)
		}
		if va, ok := ir2.(ir.VerbatimExtensionAware); ok {
			va.SetVerbatimExtensionPassthrough(true)
		}
		s2, err := ir2.ReadSchema(ctx)
		migcore.CloseIf(ir2)
		if err != nil {
			t.Fatalf("ReadSchema (opclass check): %v", err)
		}
		ct := findTable(s2, "catalog_tree")
		var opclassCarried bool
		if ct != nil {
			for _, idx := range ct.Indexes {
				if idx.Name != "catalog_tree_path_gist" {
					continue
				}
				for _, c := range idx.Columns {
					if c.OperatorClass == "gist_ltree_ops" {
						opclassCarried = true
					}
				}
			}
		}
		if !opclassCarried {
			t.Error("ir.IndexColumn.OperatorClass for the verbatim ltree GiST index " +
				"was not carried as \"gist_ltree_ops\" (Bug 47 invariant under ADR-0047)")
		}
	}
	// Functional check: the GiST index supports an ltree ancestor query.
	var descendants int
	if err := tgtDB.QueryRowContext(ctx,
		"SELECT COUNT(*) FROM catalog_tree WHERE path <@ 'Top.Science'").Scan(&descendants); err != nil {
		t.Fatalf("ltree ancestor query: %v", err)
	}
	if descendants != 2 {
		t.Errorf("ltree `<@ Top.Science` matched %d rows; want 2 (sci + astro)", descendants)
	}

	// The IR carried ir.VerbatimType (not ir.ExtensionType / ir.Enum).
	rdr, err := pgEng.OpenSchemaReader(ctx, targetDSN)
	if err != nil {
		t.Fatalf("OpenSchemaReader: %v", err)
	}
	defer migcore.CloseIf(rdr)
	if va, ok := rdr.(ir.VerbatimExtensionAware); ok {
		va.SetVerbatimExtensionPassthrough(true)
	} else {
		t.Fatal("PG SchemaReader must implement ir.VerbatimExtensionAware")
	}
	got, err := rdr.ReadSchema(ctx)
	if err != nil {
		t.Fatalf("ReadSchema: %v", err)
	}
	tbl := findTable(got, "catalog_tree")
	if tbl == nil {
		t.Fatal("target missing catalog_tree")
	}
	var found bool
	for _, col := range tbl.Columns {
		if col.Name != "path" {
			continue
		}
		v, ok := col.Type.(ir.VerbatimType)
		if !ok {
			t.Fatalf("path column type = %T; want ir.VerbatimType", col.Type)
		}
		found = true
		if v.Definition != "ltree" {
			t.Errorf("VerbatimType.Definition = %q; want \"ltree\"", v.Definition)
		}
	}
	if !found {
		t.Error("path column not found in target schema")
	}
}

// TestSchemaReader_PG_Verbatim_NotEnabled_StillLoudRefuses pins
// ADR-0047 tier (c): without the same-engine guarantee (the reader's
// verbatim flag NOT set — what a cross-engine run leaves it as), an
// uncatalogued user-defined type still surfaces the loud refusal. No
// weakening.
func TestSchemaReader_PG_Verbatim_NotEnabled_StillLoudRefuses(t *testing.T) {
	sourceDSN, _, cleanup := startPostgresWithExtension(t, "ltree", false)
	defer cleanup()
	applyPGDDL(t, sourceDSN, seedLtreeDDL)

	pgEng, _ := engines.Get("postgres")
	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()

	rdr, err := pgEng.OpenSchemaReader(ctx, sourceDSN)
	if err != nil {
		t.Fatalf("OpenSchemaReader: %v", err)
	}
	defer migcore.CloseIf(rdr)
	// Deliberately DO NOT call SetVerbatimExtensionPassthrough — this
	// is the cross-engine / no-same-engine-guarantee posture.
	if _, err := rdr.ReadSchema(ctx); err == nil {
		t.Fatal("expected loud refusal for uncatalogued ltree without same-engine guarantee; got nil")
	}
}

// TestMigrate_PG_to_MySQL_Verbatim_Ltree_StillLoudRefuses is the
// regression guard: the same-engine verbatim tier must NOT leak into
// cross-engine. PG → MySQL with an uncatalogued ltree column refuses
// loudly before any data moves.
func TestMigrate_PG_to_MySQL_Verbatim_Ltree_StillLoudRefuses(t *testing.T) {
	pgSourceDSN, _, pgCleanup := startPostgresWithExtension(t, "ltree", false)
	defer pgCleanup()
	applyPGDDL(t, pgSourceDSN, seedLtreeDDL)

	_, mysqlTargetDSN, myCleanup := startMySQL(t)
	defer myCleanup()

	pgEng, _ := engines.Get("postgres")
	mysqlEng, _ := engines.Get("mysql")

	mig := &Migrator{
		Source:    pgEng,
		Target:    mysqlEng,
		SourceDSN: pgSourceDSN,
		TargetDSN: mysqlTargetDSN,
	}
	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()
	err := mig.Run(ctx)
	if err == nil {
		t.Fatal("expected loud refusal for cross-engine PG → MySQL with uncatalogued ltree; got nil")
	}
	// It refuses at schema-read (no same-engine guarantee → tier (c)
	// loud refusal) — the cross-engine default is unweakened. We only
	// assert it failed loudly before completing.
	t.Logf("cross-engine refusal (expected): %v", err)
}

// TestBackupRestore_PG_Verbatim_Ltree_MarkerAndExactRestore covers the
// backup half of the ADR §Testing matrix: backup records the
// capability marker on the lineage segment; PG restore reproduces the
// column + values exactly; restore to MySQL refuses loudly at
// preflight.
func TestBackupRestore_PG_Verbatim_Ltree_MarkerAndExactRestore(t *testing.T) {
	srcDSN, restoreDSN, cleanup := startPostgresWithExtension(t, "ltree", true)
	defer cleanup()
	applyPGDDL(t, srcDSN, seedLtreeDDL)

	pgEng, _ := engines.Get("postgres")
	mysqlEng, _ := engines.Get("mysql")

	dir := t.TempDir()
	store, err := blobcodec.NewLocalStore(dir)
	if err != nil {
		t.Fatalf("NewLocalStore: %v", err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 120*time.Second)
	defer cancel()

	// 1. Full backup (source is PG → verbatim CAPTURE enabled).
	if err := (&Backup{
		Source: pgEng, SourceDSN: srcDSN, Store: store, SluiceVersion: "test",
	}).Run(ctx); err != nil {
		t.Fatalf("Backup.Run: %v", err)
	}

	// 2. The lineage segment recorded the PG-restore-only marker.
	cat, err := lineage.ResolveLineage(ctx, store)
	if err != nil {
		t.Fatalf("lineage.ResolveLineage: %v", err)
	}
	if len(cat.Segments) != 1 {
		t.Fatalf("segments = %d; want 1", len(cat.Segments))
	}
	marker := cat.Segments[0].VerbatimExtensionColumns
	if len(marker) != 1 || !strings.Contains(marker[0], "catalog_tree.path") {
		t.Fatalf("verbatim marker = %v; want one entry containing catalog_tree.path", marker)
	}

	// 3. Restore to MySQL → LOUD refusal at preflight (the safety pin).
	_, mysqlTargetDSN, myCleanup := startMySQL(t)
	defer myCleanup()
	err = (&Restore{
		Target: mysqlEng, TargetDSN: mysqlTargetDSN, Store: store,
	}).Run(ctx)
	if err == nil {
		t.Fatal("expected LOUD refusal restoring verbatim-marked backup to MySQL; got nil")
	}
	if !strings.Contains(err.Error(), "PG-restore-only") ||
		!strings.Contains(err.Error(), "ADR-0047") {
		t.Errorf("MySQL-restore refusal = %v; want PG-restore-only / ADR-0047 wording", err)
	}

	// 4. Restore to PG → exact reproduction.
	if err := (&Restore{
		Target: pgEng, TargetDSN: restoreDSN, Store: store,
	}).Run(ctx); err != nil {
		t.Fatalf("PG Restore.Run: %v", err)
	}
	rDB, err := sql.Open("pgx", restoreDSN)
	if err != nil {
		t.Fatalf("open restore target: %v", err)
	}
	defer func() { _ = rDB.Close() }()

	var ft string
	if err := rDB.QueryRowContext(ctx, `
		SELECT pg_catalog.format_type(a.atttypid, a.atttypmod)
		FROM pg_attribute a JOIN pg_class c ON c.oid = a.attrelid
		WHERE c.relname = 'catalog_tree' AND a.attname = 'path'`).Scan(&ft); err != nil {
		t.Fatalf("restored format_type: %v", err)
	}
	if ft != "ltree" {
		t.Errorf("restored catalog_tree.path = %q; want \"ltree\"", ft)
	}
	var astro string
	if err := rDB.QueryRowContext(ctx,
		"SELECT path::text FROM catalog_tree WHERE name = 'astro'").Scan(&astro); err != nil {
		t.Fatalf("restored astro path: %v", err)
	}
	if astro != "Top.Science.Astronomy" {
		t.Errorf("restored astro path = %q; want \"Top.Science.Astronomy\"", astro)
	}
}
