//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// PG hstore + citext passthrough integration tests (ADR-0032 Tier 1).
// Both extensions ship in the standard postgres contrib bundle —
// the stock `postgres:16` image CI pre-pulls works as-is; no special
// image required (unlike pgvector). Each test exercises:
//
//   - Same-engine PG → PG: type round-trips byte-for-byte, indexes
//     and values preserved.
//   - Cross-engine PG → MySQL: type rewritten to the catalog's
//     default cross-engine translator target (hstore → JSON, citext
//     → VARCHAR _ci), values reshaped where needed.
//
// pg_hstore + citext are the v1 shortlist's Tier 1 (type-only)
// entries — simpler than pgvector / pg_trgm because they have no
// new index access methods and no operator classes (the hstore
// GIN / GiST opclasses are out-of-v1-scope per the research doc).

package pipeline

import (
	"context"
	"database/sql"
	"strings"
	"testing"
	"time"

	"github.com/orware/sluice/internal/engines"
	"github.com/orware/sluice/internal/ir"

	_ "github.com/orware/sluice/internal/engines/mysql"
	_ "github.com/orware/sluice/internal/engines/postgres"

	"github.com/testcontainers/testcontainers-go"
	pgtc "github.com/testcontainers/testcontainers-go/modules/postgres"
)

// startPostgresWithExtension boots a stock postgres:16 container,
// creates the source and target databases, and runs CREATE EXTENSION
// <name> on the source (and target when enableOnTarget is true). Used
// for the Tier 1 hstore + citext suites; both extensions ship in the
// standard contrib bundle so no special image is required.
//
// Mirrors startPostgresWithTrgm's shape, generalised on the extension
// name. The duplication kept tight rather than DRY'd because the
// pgvector helper boots a different image (pgvector/pgvector:0.7.4-pg16)
// and merging the three would obscure the per-extension provisioning.
func startPostgresWithExtension(t *testing.T, extensionName string, enableOnTarget bool) (sourceDSN, targetDSN string, cleanup func()) {
	t.Helper()
	testcontainers.SkipIfProviderIsNotHealthy(t)

	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Minute)
	defer cancel()

	container, err := pgtc.Run(ctx,
		"postgres:16",
		pgtc.WithDatabase("source_db"),
		pgtc.WithUsername("test"),
		pgtc.WithPassword("test"),
		pgtc.BasicWaitStrategies(),
	)
	if err != nil {
		t.Fatalf("start container: %v", err)
	}

	terminate := func() {
		shutdown, c := context.WithTimeout(context.Background(), 30*time.Second)
		defer c()
		_ = container.Terminate(shutdown)
	}

	srcConn, err := container.ConnectionString(ctx, "sslmode=disable")
	if err != nil {
		terminate()
		t.Fatalf("connection string: %v", err)
	}

	db, err := sql.Open("pgx", srcConn)
	if err != nil {
		terminate()
		t.Fatalf("open: %v", err)
	}
	defer func() { _ = db.Close() }()

	if _, err := db.ExecContext(ctx, "CREATE DATABASE target_db"); err != nil {
		terminate()
		t.Fatalf("create target_db: %v", err)
	}

	tgtConn, err := buildPGDSN(srcConn, "target_db")
	if err != nil {
		terminate()
		t.Fatalf("build target DSN: %v", err)
	}

	if _, err := db.ExecContext(ctx, "CREATE EXTENSION IF NOT EXISTS "+extensionName); err != nil {
		terminate()
		t.Fatalf("CREATE EXTENSION %s on source: %v", extensionName, err)
	}

	if enableOnTarget {
		tgtDB, err := sql.Open("pgx", tgtConn)
		if err != nil {
			terminate()
			t.Fatalf("open target: %v", err)
		}
		defer func() { _ = tgtDB.Close() }()
		if _, err := tgtDB.ExecContext(ctx, "CREATE EXTENSION IF NOT EXISTS "+extensionName); err != nil {
			terminate()
			t.Fatalf("CREATE EXTENSION %s on target: %v", extensionName, err)
		}
	}

	return srcConn, tgtConn, terminate
}

// TestMigrate_PG_Hstore_Passthrough exercises the same-engine PG →
// PG round-trip of an hstore column. The seed table has one column
// of type `hstore` and three rows; after migrate the target's column
// must be `hstore` (verified via pg_type lookup) and the values must
// match byte-for-byte.
//
// The COPY-binary codec landed in v0.32.1 (internal/engines/postgres/
// hstore_codec.go) — it translates the IR's text-form hstore bytes
// (`"k"=>"v"`) into hstore's pair-array wire format at encode time.
// The corresponding preflight refusal in
// `pipeline.validateEnabledPGExtensions` is gone.
func TestMigrate_PG_Hstore_Passthrough(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresWithExtension(t, "hstore", true)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE attrs (
			id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name VARCHAR(64) NOT NULL,
			tags hstore NOT NULL
		);

		INSERT INTO attrs (name, tags) VALUES
			('alpha', '"a"=>"1", "b"=>"2"'),
			('beta',  '"x"=>"hello"'),
			('gamma', '"only"=>"one"');
	`
	applyPGDDL(t, sourceDSN, seedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	mig := &Migrator{
		Source:              pgEng,
		Target:              pgEng,
		SourceDSN:           sourceDSN,
		TargetDSN:           targetDSN,
		EnabledPGExtensions: []string{"hstore"},
	}

	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		t.Fatalf("Migrator.Run: %v", err)
	}

	tgtDB, err := sql.Open("pgx", targetDSN)
	if err != nil {
		t.Fatalf("open target: %v", err)
	}
	defer func() { _ = tgtDB.Close() }()

	// Verify the target column's data type is `hstore` (not a string
	// of the same shape).
	const typeQuery = `
		SELECT format_type(atttypid, atttypmod)
		FROM   pg_attribute
		JOIN   pg_class ON pg_class.oid = pg_attribute.attrelid
		WHERE  pg_class.relname = 'attrs'
		  AND  pg_attribute.attname = 'tags'`
	var typeName string
	if err := tgtDB.QueryRowContext(ctx, typeQuery).Scan(&typeName); err != nil {
		t.Fatalf("type query: %v", err)
	}
	if typeName != "hstore" {
		t.Errorf("target attrs.tags type = %q; want %q", typeName, "hstore")
	}

	// Row count check.
	var n int
	if err := tgtDB.QueryRowContext(ctx, "SELECT COUNT(*) FROM attrs").Scan(&n); err != nil {
		t.Fatalf("count: %v", err)
	}
	if n != 3 {
		t.Errorf("target attrs rows = %d; want 3", n)
	}

	// Functional check — hstore -> operator (key lookup) should work
	// on the target. Proves it's a real hstore column, not a text
	// column that happens to contain hstore-shaped text.
	var v string
	if err := tgtDB.QueryRowContext(ctx,
		"SELECT tags -> 'a' FROM attrs WHERE name = 'alpha'").Scan(&v); err != nil {
		t.Fatalf("hstore -> lookup: %v", err)
	}
	if v != "1" {
		t.Errorf("alpha tags -> 'a' = %q; want %q", v, "1")
	}

	// Round-trip the IR through the target reader: the column type
	// should surface as ir.ExtensionType{Extension: "hstore"}.
	pgRdr, err := pgEng.OpenSchemaReader(ctx, targetDSN)
	if err != nil {
		t.Fatalf("OpenSchemaReader on target: %v", err)
	}
	defer closeIf(pgRdr)
	if aware, ok := pgRdr.(ir.ExtensionAware); ok {
		if err := aware.EnableExtensions(ctx, []string{"hstore"}); err != nil {
			t.Fatalf("EnableExtensions on target reader: %v", err)
		}
	}
	got, err := pgRdr.ReadSchema(ctx)
	if err != nil {
		t.Fatalf("ReadSchema on target: %v", err)
	}
	tbl := findTable(got, "attrs")
	if tbl == nil {
		t.Fatal("target has no attrs table")
	}
	var foundHstore bool
	for _, col := range tbl.Columns {
		if col.Name != "tags" {
			continue
		}
		ext, ok := col.Type.(ir.ExtensionType)
		if !ok {
			t.Errorf("tags column type = %T; want ir.ExtensionType", col.Type)
			continue
		}
		foundHstore = true
		if ext.Extension != "hstore" || ext.Name != "hstore" {
			t.Errorf("tags ExtensionType = %+v; want extension=hstore name=hstore", ext)
		}
	}
	if !foundHstore {
		t.Error("did not find hstore tags column in attrs")
	}
}

// TestMigrate_PG_CiText_Passthrough exercises the same-engine PG →
// PG round-trip of a citext column. The seed table has a citext
// column with three rows; after migrate the target's column must be
// `citext` and a case-insensitive lookup query must succeed.
func TestMigrate_PG_CiText_Passthrough(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresWithExtension(t, "citext", true)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email citext NOT NULL,
			CONSTRAINT users_email_unique UNIQUE (email)
		);

		INSERT INTO users (email) VALUES
			('Alice@Example.com'),
			('Bob@Example.com'),
			('Carol@example.com');
	`
	applyPGDDL(t, sourceDSN, seedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	mig := &Migrator{
		Source:              pgEng,
		Target:              pgEng,
		SourceDSN:           sourceDSN,
		TargetDSN:           targetDSN,
		EnabledPGExtensions: []string{"citext"},
	}

	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		t.Fatalf("Migrator.Run: %v", err)
	}

	tgtDB, err := sql.Open("pgx", targetDSN)
	if err != nil {
		t.Fatalf("open target: %v", err)
	}
	defer func() { _ = tgtDB.Close() }()

	// Verify the target column's data type is `citext`.
	const typeQuery = `
		SELECT format_type(atttypid, atttypmod)
		FROM   pg_attribute
		JOIN   pg_class ON pg_class.oid = pg_attribute.attrelid
		WHERE  pg_class.relname = 'users'
		  AND  pg_attribute.attname = 'email'`
	var typeName string
	if err := tgtDB.QueryRowContext(ctx, typeQuery).Scan(&typeName); err != nil {
		t.Fatalf("type query: %v", err)
	}
	if typeName != "citext" {
		t.Errorf("target users.email type = %q; want %q", typeName, "citext")
	}

	// Row count check.
	var n int
	if err := tgtDB.QueryRowContext(ctx, "SELECT COUNT(*) FROM users").Scan(&n); err != nil {
		t.Fatalf("count: %v", err)
	}
	if n != 3 {
		t.Errorf("target users rows = %d; want 3", n)
	}

	// Functional check — case-insensitive comparison should resolve
	// the row regardless of the lookup-side casing.
	var got string
	if err := tgtDB.QueryRowContext(ctx,
		"SELECT email FROM users WHERE email = 'ALICE@EXAMPLE.COM'").Scan(&got); err != nil {
		t.Fatalf("citext case-insensitive lookup: %v", err)
	}
	if !strings.EqualFold(got, "Alice@Example.com") {
		t.Errorf("citext lookup got = %q; want case-insensitive match to Alice@Example.com", got)
	}

	// Round-trip the IR.
	pgRdr, err := pgEng.OpenSchemaReader(ctx, targetDSN)
	if err != nil {
		t.Fatalf("OpenSchemaReader: %v", err)
	}
	defer closeIf(pgRdr)
	if aware, ok := pgRdr.(ir.ExtensionAware); ok {
		if err := aware.EnableExtensions(ctx, []string{"citext"}); err != nil {
			t.Fatalf("EnableExtensions on target reader: %v", err)
		}
	}
	tgtSchema, err := pgRdr.ReadSchema(ctx)
	if err != nil {
		t.Fatalf("ReadSchema: %v", err)
	}
	tbl := findTable(tgtSchema, "users")
	if tbl == nil {
		t.Fatal("target has no users table")
	}
	var foundCiText bool
	for _, col := range tbl.Columns {
		if col.Name != "email" {
			continue
		}
		ext, ok := col.Type.(ir.ExtensionType)
		if !ok {
			t.Errorf("email column type = %T; want ir.ExtensionType", col.Type)
			continue
		}
		foundCiText = true
		if ext.Extension != "citext" || ext.Name != "citext" {
			t.Errorf("email ExtensionType = %+v; want extension=citext name=citext", ext)
		}
	}
	if !foundCiText {
		t.Error("did not find citext email column in users")
	}
}

// TestMigrate_PG_Hstore_CrossEngineToMySQL exercises the cross-engine
// default translator path: a PG source with an hstore column targets
// a MySQL database, and the operator passes
// `--enable-pg-extension hstore`. The MySQL target's column should
// be JSON, and values should land as JSON objects (`"a"=>"b"` →
// `{"a":"b"}`).
func TestMigrate_PG_Hstore_CrossEngineToMySQL(t *testing.T) {
	pgSource, _, pgCleanup := startPostgresWithExtension(t, "hstore", false)
	defer pgCleanup()

	_, mysqlTarget, mysqlCleanup := startMySQL(t)
	defer mysqlCleanup()

	const seedDDL = `
		CREATE TABLE attrs (
			id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name VARCHAR(64) NOT NULL,
			tags hstore NOT NULL
		);

		INSERT INTO attrs (name, tags) VALUES
			('alpha', '"a"=>"1", "b"=>"2"'),
			('beta',  '"x"=>"hello"');
	`
	applyPGDDL(t, pgSource, seedDDL)

	pgEng, _ := engines.Get("postgres")
	mysqlEng, _ := engines.Get("mysql")
	mig := &Migrator{
		Source:              pgEng,
		Target:              mysqlEng,
		SourceDSN:           pgSource,
		TargetDSN:           mysqlTarget,
		EnabledPGExtensions: []string{"hstore"},
	}

	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		t.Fatalf("Migrator.Run: %v", err)
	}

	mysqlDB, err := sql.Open("mysql", mysqlTarget)
	if err != nil {
		t.Fatalf("open mysql target: %v", err)
	}
	defer func() { _ = mysqlDB.Close() }()

	// Verify the target column's MySQL type is JSON.
	const typeQuery = `
		SELECT column_type
		FROM   information_schema.columns
		WHERE  table_schema = DATABASE()
		  AND  table_name = 'attrs'
		  AND  column_name = 'tags'`
	var colType string
	if err := mysqlDB.QueryRowContext(ctx, typeQuery).Scan(&colType); err != nil {
		t.Fatalf("type query: %v", err)
	}
	if !strings.EqualFold(colType, "json") {
		t.Errorf("target attrs.tags column_type = %q; want \"json\"", colType)
	}

	// Row count check.
	var n int
	if err := mysqlDB.QueryRowContext(ctx, "SELECT COUNT(*) FROM attrs").Scan(&n); err != nil {
		t.Fatalf("count: %v", err)
	}
	if n != 2 {
		t.Errorf("target attrs rows = %d; want 2", n)
	}

	// Verify the JSON content is structurally a JSON object — the
	// load-bearing translation is `"a"=>"1"` → `{"a":"1"}`. MySQL's
	// JSON_TYPE returns "OBJECT" for `{...}` shapes and "STRING" for
	// raw text — confirming the value was reshaped, not blindly
	// passed through.
	var jsonType, alphaValue string
	if err := mysqlDB.QueryRowContext(ctx,
		"SELECT JSON_TYPE(tags), JSON_UNQUOTE(JSON_EXTRACT(tags, '$.a')) FROM attrs WHERE name = 'alpha'").
		Scan(&jsonType, &alphaValue); err != nil {
		t.Fatalf("JSON query: %v", err)
	}
	if jsonType != "OBJECT" {
		t.Errorf("alpha tags JSON_TYPE = %q; want OBJECT (hstore reshape failed)", jsonType)
	}
	if alphaValue != "1" {
		t.Errorf("alpha tags $.a = %q; want \"1\"", alphaValue)
	}
}

// TestMigrate_PG_CiText_CrossEngineToMySQL exercises the citext →
// MySQL VARCHAR with case-insensitive collation translator. The
// target column must declare `utf8mb4_0900_ai_ci` (or a compatible
// `_ci` collation that MySQL reports), and a case-insensitive
// equality query must resolve the row.
func TestMigrate_PG_CiText_CrossEngineToMySQL(t *testing.T) {
	pgSource, _, pgCleanup := startPostgresWithExtension(t, "citext", false)
	defer pgCleanup()

	_, mysqlTarget, mysqlCleanup := startMySQL(t)
	defer mysqlCleanup()

	const seedDDL = `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email citext NOT NULL
		);

		INSERT INTO users (email) VALUES
			('Alice@Example.com'),
			('Bob@Example.com');
	`
	applyPGDDL(t, pgSource, seedDDL)

	pgEng, _ := engines.Get("postgres")
	mysqlEng, _ := engines.Get("mysql")
	mig := &Migrator{
		Source:              pgEng,
		Target:              mysqlEng,
		SourceDSN:           pgSource,
		TargetDSN:           mysqlTarget,
		EnabledPGExtensions: []string{"citext"},
	}

	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		t.Fatalf("Migrator.Run: %v", err)
	}

	mysqlDB, err := sql.Open("mysql", mysqlTarget)
	if err != nil {
		t.Fatalf("open mysql target: %v", err)
	}
	defer func() { _ = mysqlDB.Close() }()

	// Verify the target column's data type + collation. MySQL's
	// information_schema reports collation_name for character columns;
	// the citext translator declares utf8mb4_0900_ai_ci specifically.
	const typeQuery = `
		SELECT data_type, collation_name
		FROM   information_schema.columns
		WHERE  table_schema = DATABASE()
		  AND  table_name = 'users'
		  AND  column_name = 'email'`
	var dataType string
	var collation sql.NullString
	if err := mysqlDB.QueryRowContext(ctx, typeQuery).Scan(&dataType, &collation); err != nil {
		t.Fatalf("type query: %v", err)
	}
	if !strings.EqualFold(dataType, "varchar") {
		t.Errorf("target users.email data_type = %q; want \"varchar\"", dataType)
	}
	if !collation.Valid || !strings.HasSuffix(strings.ToLower(collation.String), "_ai_ci") {
		t.Errorf("target users.email collation = %v; want a case-insensitive (_ai_ci) collation", collation)
	}

	// Functional check: MySQL with a `_ci` collation resolves
	// case-insensitive equality the same way PG citext does, so the
	// query must return the row.
	var got string
	if err := mysqlDB.QueryRowContext(ctx,
		"SELECT email FROM users WHERE email = 'ALICE@EXAMPLE.COM'").Scan(&got); err != nil {
		t.Fatalf("citext-as-VARCHAR _ci lookup on MySQL: %v", err)
	}
	if !strings.EqualFold(got, "Alice@Example.com") {
		t.Errorf("MySQL case-insensitive lookup got = %q; want case-insensitive match to Alice@Example.com", got)
	}
}
