//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// End-to-end integration test for the simple-mode orchestrator with
// the Postgres engine on both sides. Boots one Postgres container,
// creates a source and a target database, seeds the source, runs
// pipeline.Migrator, and verifies the target matches.

package pipeline

import (
	"context"
	"database/sql"
	"fmt"
	"net/url"
	"strings"
	"testing"
	"time"

	"github.com/orware/sluice/internal/engines"
	"github.com/orware/sluice/internal/ir"

	// Register the postgres engine so engines.Get("postgres") works.
	_ "github.com/orware/sluice/internal/engines/postgres"

	"github.com/testcontainers/testcontainers-go"
	pgtc "github.com/testcontainers/testcontainers-go/modules/postgres"
)

// startPostgres boots a Postgres container, then creates the two
// databases the migration test needs. Returns DSNs for source_db and
// target_db plus a cleanup callback. Skips the test cleanly when no
// Docker provider is available.
func startPostgres(t *testing.T) (sourceDSN, targetDSN string, cleanup func()) {
	t.Helper()
	testcontainers.SkipIfProviderIsNotHealthy(t)

	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()

	container, err := pgtc.Run(
		ctx,
		// Task #68: pre-baked PG image. See
		// pg_prebaked_integration_test.go for the full rationale.
		pgPrebakedImage,
		pgtc.WithDatabase("source_db"),
		pgtc.WithUsername("test"),
		pgtc.WithPassword("test"),
		pgtc.BasicWaitStrategies(),
		pgPrebakedWaitStrategy(),
	)
	if err != nil {
		t.Fatalf("start container: %v", err)
	}

	terminate := func() {
		shutdown, c := context.WithTimeout(context.Background(), 30*time.Second)
		defer c()
		_ = container.Terminate(shutdown)
	}

	srcConn, err := container.ConnectionString(ctx, "sslmode=disable")
	if err != nil {
		terminate()
		t.Fatalf("connection string: %v", err)
	}

	// Create the target database alongside the source. CREATE DATABASE
	// in Postgres has to run outside a transaction and from a different
	// database than the one being created — connecting to source_db
	// satisfies both. The role created by pgtc has CREATEDB.
	db, err := sql.Open("pgx", srcConn)
	if err != nil {
		terminate()
		t.Fatalf("open: %v", err)
	}
	defer func() { _ = db.Close() }()

	if _, err := db.ExecContext(ctx, "CREATE DATABASE target_db"); err != nil {
		terminate()
		t.Fatalf("create target_db: %v", err)
	}

	tgtConn, err := buildPGDSN(srcConn, "target_db")
	if err != nil {
		terminate()
		t.Fatalf("build target DSN: %v", err)
	}

	return srcConn, tgtConn, terminate
}

// buildPGDSN replaces the database name in a Postgres URI DSN. The
// pgtc container hands us a URI of the form
// `postgres://user:pass@host:port/dbname?params`, so net/url is the
// idiomatic way to swap the path component.
func buildPGDSN(orig, newDB string) (string, error) {
	u, err := url.Parse(orig)
	if err != nil {
		return "", fmt.Errorf("parse DSN: %w", err)
	}
	if u.Path == "" || u.Path == "/" {
		return "", fmt.Errorf("DSN has no db-name path: %q", orig)
	}
	u.Path = "/" + strings.TrimPrefix(newDB, "/")
	return u.String(), nil
}

// applyPGDDL runs a possibly-multi-statement DDL block against a
// Postgres DSN. libpq accepts multi-statement queries natively when
// sent via Exec — no special flag needed.
func applyPGDDL(t *testing.T, dsn, ddl string) {
	t.Helper()
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer func() { _ = db.Close() }()

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	if _, err := db.ExecContext(ctx, ddl); err != nil {
		t.Fatalf("apply ddl: %v", err)
	}
}

// TestMigrate_PostgresToPostgres exercises the orchestrator end-to-end
// with Postgres on both sides. Sanity check before the cross-engine
// MySQL→Postgres test does the heavier translation work.
func TestMigrate_PostgresToPostgres(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE users (
			id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email      VARCHAR(255) NOT NULL,
			active     BOOLEAN      NOT NULL DEFAULT true,
			created_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
			CONSTRAINT users_email_unique UNIQUE (email)
		);

		CREATE TABLE posts (
			id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			user_id BIGINT NOT NULL,
			body    TEXT   NOT NULL,
			CONSTRAINT posts_user_id_fk FOREIGN KEY (user_id)
				REFERENCES users (id) ON DELETE CASCADE
		);
		CREATE INDEX posts_user_id_idx ON posts (user_id);

		INSERT INTO users (email, active) VALUES
			('alice@example.com', true),
			('bob@example.com',   false);

		INSERT INTO posts (user_id, body) VALUES
			(1, 'first post'),
			(1, 'second post'),
			(2, 'a post by bob');
	`
	applyPGDDL(t, sourceDSN, seedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	mig := &Migrator{
		Source:    pgEng,
		Target:    pgEng,
		SourceDSN: sourceDSN,
		TargetDSN: targetDSN,
	}

	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		t.Fatalf("Migrator.Run: %v", err)
	}

	// ---- Verify target schema matches what we expect ----
	sr, err := pgEng.OpenSchemaReader(ctx, targetDSN)
	if err != nil {
		t.Fatalf("OpenSchemaReader: %v", err)
	}
	defer closeIf(sr)

	got, err := sr.ReadSchema(ctx)
	if err != nil {
		t.Fatalf("ReadSchema: %v", err)
	}
	if len(got.Tables) != 2 {
		t.Fatalf("target tables = %d; want 2 (have: %v)", len(got.Tables), targetTableNames(got))
	}

	users := findTable(got, "users")
	posts := findTable(got, "posts")
	if users == nil || posts == nil {
		t.Fatalf("missing target tables; have %v", targetTableNames(got))
	}

	// PK on id
	if users.PrimaryKey == nil || users.PrimaryKey.Columns[0].Column != "id" {
		t.Errorf("users PK = %#v; want PK on id", users.PrimaryKey)
	}

	// Unique on email
	hasEmailUnique := false
	for _, ix := range users.Indexes {
		if ix.Unique && len(ix.Columns) == 1 && ix.Columns[0].Column == "email" {
			hasEmailUnique = true
			break
		}
	}
	if !hasEmailUnique {
		t.Errorf("users indexes = %#v; want a unique index on email", users.Indexes)
	}

	// FK with CASCADE on delete
	if len(posts.ForeignKeys) != 1 {
		t.Fatalf("posts FKs = %d; want 1", len(posts.ForeignKeys))
	}
	fk := posts.ForeignKeys[0]
	if fk.ReferencedTable != "users" || fk.OnDelete != ir.FKActionCascade {
		t.Errorf("posts FK = %+v; want users on-delete cascade", fk)
	}

	// ---- Verify target data ----
	rr, err := pgEng.OpenRowReader(ctx, targetDSN)
	if err != nil {
		t.Fatalf("OpenRowReader: %v", err)
	}
	defer closeIf(rr)

	usersRows := readAll(t, ctx, rr, users)
	if len(usersRows) != 2 {
		t.Errorf("target users rows = %d; want 2", len(usersRows))
	}
	if email, ok := usersRows[0]["email"].(string); !ok || email != "alice@example.com" {
		t.Errorf("users[0].email = %#v; want 'alice@example.com'", usersRows[0]["email"])
	}
	if active, ok := usersRows[0]["active"].(bool); !ok || !active {
		t.Errorf("users[0].active = %#v; want true", usersRows[0]["active"])
	}

	postsRows := readAll(t, ctx, rr, posts)
	if len(postsRows) != 3 {
		t.Errorf("target posts rows = %d; want 3", len(postsRows))
	}
}
