//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// Value-level pin for the per-column COLLATE carry (restore-parity
// oracle TRIAGE finding #2): a PG → PG migrate of a `text COLLATE "C"`
// column must land the collation on the target CATALOG *and* preserve
// the collation's BEHAVIOUR — ORDER BY on the target returns the
// source's ordering for a seed set that sorts differently under "C"
// (byte order) than under an en_US-ish locale default. Pre-fix, the PG
// emitter dropped the clause and the target column silently reverted
// to the database default collation, changing sort/comparison order
// and any collation-dependent index/constraint semantics.

package pipeline

import (
	"context"
	"database/sql"
	"reflect"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/engines"
)

func TestMigrate_PGToPG_ColumnCollationCarry(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()

	// Seed values chosen so byte order ("C") and locale order diverge:
	// under "C" uppercase sorts wholesale before lowercase
	// (A < B < Zz < a < b < ~x), while glibc/ICU en_US-ish locales
	// interleave case (a before B) and weight punctuation differently.
	const seedDDL = `
		CREATE TABLE regions (
			id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			code TEXT COLLATE "C" NOT NULL
		);
		INSERT INTO regions (code) VALUES
			('a'), ('B'), ('b'), ('A'), ('Zz'), ('~x');
	`
	applyPGDDL(t, sourceDSN, seedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}
	mig := &Migrator{
		Source:    pgEng,
		Target:    pgEng,
		SourceDSN: sourceDSN,
		TargetDSN: targetDSN,
	}
	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		t.Fatalf("Migrator.Run: %v", err)
	}

	// Catalog pin: the target column's attcollation must name "C"
	// explicitly (not the database default).
	tgt, err := sql.Open("pgx", targetDSN)
	if err != nil {
		t.Fatalf("open target: %v", err)
	}
	defer func() { _ = tgt.Close() }()
	const collQ = `
		SELECT co.collname
		FROM   pg_attribute a
		JOIN   pg_class     cl ON cl.oid = a.attrelid
		JOIN   pg_namespace n  ON n.oid  = cl.relnamespace
		JOIN   pg_collation co ON co.oid = a.attcollation
		WHERE  n.nspname = 'public' AND cl.relname = 'regions' AND a.attname = 'code'`
	var collname string
	if err := tgt.QueryRowContext(ctx, collQ).Scan(&collname); err != nil {
		t.Fatalf("read target collation (no row means the COLLATE clause was dropped): %v", err)
	}
	if collname != "C" {
		t.Fatalf("target regions.code collation = %q; want %q", collname, "C")
	}

	// Behaviour pin: ORDER BY on the target matches the source, and
	// both match "C"'s byte order — ground truth, not just catalog
	// text. (If the target column had silently reverted to the
	// database default collation — en_US.utf8 on the stock postgres
	// image — 'a' would sort before 'B' and this would fail.)
	wantOrder := []string{"A", "B", "Zz", "a", "b", "~x"}
	orderOf := func(dsn, side string) []string {
		db, err := sql.Open("pgx", dsn)
		if err != nil {
			t.Fatalf("open %s: %v", side, err)
		}
		defer func() { _ = db.Close() }()
		rows, err := db.QueryContext(ctx, "SELECT code FROM regions ORDER BY code")
		if err != nil {
			t.Fatalf("%s ORDER BY: %v", side, err)
		}
		defer func() { _ = rows.Close() }()
		var out []string
		for rows.Next() {
			var s string
			if err := rows.Scan(&s); err != nil {
				t.Fatalf("%s scan: %v", side, err)
			}
			out = append(out, s)
		}
		if err := rows.Err(); err != nil {
			t.Fatalf("%s rows: %v", side, err)
		}
		return out
	}
	srcOrder := orderOf(sourceDSN, "source")
	tgtOrder := orderOf(targetDSN, "target")
	if !reflect.DeepEqual(srcOrder, wantOrder) {
		t.Fatalf("source ORDER BY under COLLATE \"C\" = %v; want byte order %v (seed/ground-truth broken)", srcOrder, wantOrder)
	}
	if !reflect.DeepEqual(tgtOrder, srcOrder) {
		t.Fatalf("target ORDER BY = %v; want source's \"C\" ordering %v — the collation did not carry behaviourally", tgtOrder, srcOrder)
	}
}
