//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// PG → PG pg_trgm passthrough integration tests (ADR-0032 Tier 2 lite).
// pg_trgm is "operator-class only" — no new column types, just
// `gin_trgm_ops` / `gist_trgm_ops` operator classes on existing
// `text` / `varchar` columns. The test boots a stock postgres:16
// container (pg_trgm ships in the standard contrib bundle), runs
// CREATE EXTENSION on both source and target, exercises the migrate
// path with a `CREATE INDEX ... USING GIN (col gin_trgm_ops)` index,
// and verifies the round-trip preserves the index's operator class
// on the target.

package pipeline

import (
	"context"
	"database/sql"
	"errors"
	"strings"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/engines"
	"sluicesync.dev/sluice/internal/ir"

	_ "sluicesync.dev/sluice/internal/engines/mysql"
	_ "sluicesync.dev/sluice/internal/engines/postgres"

	"github.com/testcontainers/testcontainers-go"
	pgtc "github.com/testcontainers/testcontainers-go/modules/postgres"
)

// startPostgresWithTrgm boots a stock postgres:16 container, creates
// the source and target databases, and runs CREATE EXTENSION pg_trgm
// on both. pg_trgm ships in the standard postgres contrib bundle so
// no special image is required — the postgres:16 image CI already
// pre-pulls works as-is.
//
// enableOnTarget mirrors the pgvector helper's flag: set true for
// the happy-path round-trip, false to exercise the
// target-missing-extension preflight refusal.
func startPostgresWithTrgm(t *testing.T, enableOnTarget bool) (sourceDSN, targetDSN string, cleanup func()) {
	t.Helper()
	testcontainers.SkipIfProviderIsNotHealthy(t)

	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Minute)
	defer cancel()

	container, err := pgtc.Run(
		ctx,
		// Task #68: pre-baked PG image. See
		// pg_prebaked_integration_test.go for the full rationale.
		pgPrebakedImage,
		pgtc.WithDatabase("source_db"),
		pgtc.WithUsername("test"),
		pgtc.WithPassword("test"),
		pgtc.BasicWaitStrategies(),
		pgPrebakedWaitStrategy(),
	)
	if err != nil {
		t.Fatalf("start container: %v", err)
	}

	terminate := func() {
		shutdown, c := context.WithTimeout(context.Background(), 30*time.Second)
		defer c()
		_ = container.Terminate(shutdown)
	}

	srcConn, err := container.ConnectionString(ctx, "sslmode=disable")
	if err != nil {
		terminate()
		t.Fatalf("connection string: %v", err)
	}

	db, err := sql.Open("pgx", srcConn)
	if err != nil {
		terminate()
		t.Fatalf("open: %v", err)
	}
	defer func() { _ = db.Close() }()

	if _, err := db.ExecContext(ctx, "CREATE DATABASE target_db"); err != nil {
		terminate()
		t.Fatalf("create target_db: %v", err)
	}

	tgtConn, err := buildPGDSN(srcConn, "target_db")
	if err != nil {
		terminate()
		t.Fatalf("build target DSN: %v", err)
	}

	if _, err := db.ExecContext(ctx, "CREATE EXTENSION IF NOT EXISTS pg_trgm"); err != nil {
		terminate()
		t.Fatalf("CREATE EXTENSION pg_trgm on source: %v", err)
	}

	if enableOnTarget {
		tgtDB, err := sql.Open("pgx", tgtConn)
		if err != nil {
			terminate()
			t.Fatalf("open target: %v", err)
		}
		defer func() { _ = tgtDB.Close() }()
		if _, err := tgtDB.ExecContext(ctx, "CREATE EXTENSION IF NOT EXISTS pg_trgm"); err != nil {
			terminate()
			t.Fatalf("CREATE EXTENSION pg_trgm on target: %v", err)
		}
	}

	return srcConn, tgtConn, terminate
}

// TestMigrate_PG_PgTrgm_GinIndexPassthrough exercises the load-bearing
// pg_trgm path: a `CREATE INDEX ... USING GIN (body gin_trgm_ops)`
// index round-trips through PG → PG migrate when the operator opts
// into --enable-pg-extension pg_trgm and both sides have the
// extension installed. The ground truth is a pg_index/pg_opclass
// query on the target verifying the index exists with the expected
// access method AND operator class — without the per-opclass
// passthrough this PR adds, the index would land on the target
// with the GIN AM but no opclass, and CREATE INDEX would fail at
// emit-time (gin has no default opclass for text).
func TestMigrate_PG_PgTrgm_GinIndexPassthrough(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresWithTrgm(t, true)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE documents (
			id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			body TEXT NOT NULL
		);

		INSERT INTO documents (body) VALUES
			('the quick brown fox'),
			('jumps over the lazy dog'),
			('pack my box with five dozen liquor jugs');

		CREATE INDEX documents_body_trgm
		    ON documents USING GIN (body gin_trgm_ops);
	`
	applyPGDDL(t, sourceDSN, seedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	mig := &Migrator{
		Source:              pgEng,
		Target:              pgEng,
		SourceDSN:           sourceDSN,
		TargetDSN:           targetDSN,
		EnabledPGExtensions: []string{"pg_trgm"},
	}

	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		t.Fatalf("Migrator.Run: %v", err)
	}

	tgtDB, err := sql.Open("pgx", targetDSN)
	if err != nil {
		t.Fatalf("open target: %v", err)
	}
	defer func() { _ = tgtDB.Close() }()

	// Ground truth — query pg_index + pg_opclass on the target. The
	// load-bearing assertion is `opcname = 'gin_trgm_ops'`: without
	// the per-opclass capture this PR adds, the index would either
	// fail to create (gin has no default opclass for text) or land
	// with the wrong opclass. Either way the SELECT below would
	// surface the regression cleanly.
	const idxQuery = `
		SELECT am.amname, opc.opcname
		FROM   pg_index ix
		JOIN   pg_class i  ON i.oid = ix.indexrelid
		JOIN   pg_class cl ON cl.oid = ix.indrelid
		JOIN   pg_am    am ON am.oid = i.relam
		JOIN   LATERAL unnest(ix.indclass) WITH ORDINALITY AS uc(opcoid, ord) ON TRUE
		JOIN   pg_opclass opc ON opc.oid = uc.opcoid
		WHERE  cl.relname = 'documents'
		  AND  i.relname  = 'documents_body_trgm'`
	var (
		amname  string
		opcname string
	)
	if err := tgtDB.QueryRowContext(ctx, idxQuery).Scan(&amname, &opcname); err != nil {
		t.Fatalf("index method/opclass query: %v", err)
	}
	if amname != "gin" {
		t.Errorf("target index method = %q; want gin", amname)
	}
	if opcname != "gin_trgm_ops" {
		t.Errorf("target index opclass = %q; want gin_trgm_ops", opcname)
	}

	// Row count check — bulk copy should have moved 3 rows.
	var n int
	if err := tgtDB.QueryRowContext(ctx, "SELECT COUNT(*) FROM documents").Scan(&n); err != nil {
		t.Fatalf("count: %v", err)
	}
	if n != 3 {
		t.Errorf("target documents rows = %d; want 3", n)
	}

	// Sanity check — the trigram operator should fire on the target.
	// `%` is the trigram-similarity operator; without the GIN +
	// gin_trgm_ops index it would still work as a sequential scan,
	// but the EXPLAIN below proves the index is being used.
	var planText string
	if err := tgtDB.QueryRowContext(ctx,
		"EXPLAIN (FORMAT TEXT) SELECT id FROM documents WHERE body % 'quick brown'").
		Scan(&planText); err != nil {
		// EXPLAIN may return multiple rows; falling back to a simpler
		// existence check rather than failing the test on plan-shape
		// quirks across PG versions.
		t.Logf("EXPLAIN failed (non-fatal): %v", err)
	} else {
		t.Logf("trigram-search plan: %s", planText)
	}

	// Round-trip the IR through the target reader to confirm the
	// IndexColumn.OperatorClass field surfaces from the rebuilt
	// schema. Mirrors the pgvector test's "read-back IR" assertion.
	pgRdr, err := pgEng.OpenSchemaReader(ctx, targetDSN)
	if err != nil {
		t.Fatalf("OpenSchemaReader on target: %v", err)
	}
	defer closeIf(pgRdr)
	if aware, ok := pgRdr.(ir.ExtensionAware); ok {
		if err := aware.EnableExtensions(ctx, []string{"pg_trgm"}); err != nil {
			t.Fatalf("EnableExtensions on target reader: %v", err)
		}
	}
	got, err := pgRdr.ReadSchema(ctx)
	if err != nil {
		t.Fatalf("ReadSchema on target: %v", err)
	}
	docs := findTable(got, "documents")
	if docs == nil {
		t.Fatal("target has no documents table")
	}
	var foundTrgm bool
	for _, idx := range docs.Indexes {
		for _, c := range idx.Columns {
			if c.OperatorClass == "gin_trgm_ops" {
				foundTrgm = true
				if c.Column != "body" {
					t.Errorf("trgm index column = %q; want body", c.Column)
				}
			}
		}
	}
	if !foundTrgm {
		t.Errorf("did not find gin_trgm_ops on documents indexes; got %+v", docs.Indexes)
	}
}

// TestMigrate_PG_PgTrgm_GistIndexPassthrough mirrors the GIN test for
// the GiST flavour. pg_trgm supports both AMs; the catalog declares
// both opclasses and the round-trip must preserve either.
func TestMigrate_PG_PgTrgm_GistIndexPassthrough(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresWithTrgm(t, true)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE documents (
			id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			body TEXT NOT NULL
		);

		INSERT INTO documents (body) VALUES
			('the quick brown fox'),
			('hello world');

		CREATE INDEX documents_body_trgm_gist
		    ON documents USING GIST (body gist_trgm_ops);
	`
	applyPGDDL(t, sourceDSN, seedDDL)

	pgEng, _ := engines.Get("postgres")
	mig := &Migrator{
		Source:              pgEng,
		Target:              pgEng,
		SourceDSN:           sourceDSN,
		TargetDSN:           targetDSN,
		EnabledPGExtensions: []string{"pg_trgm"},
	}

	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		t.Fatalf("Migrator.Run: %v", err)
	}

	tgtDB, err := sql.Open("pgx", targetDSN)
	if err != nil {
		t.Fatalf("open target: %v", err)
	}
	defer func() { _ = tgtDB.Close() }()

	const idxQuery = `
		SELECT am.amname, opc.opcname
		FROM   pg_index ix
		JOIN   pg_class i  ON i.oid = ix.indexrelid
		JOIN   pg_class cl ON cl.oid = ix.indrelid
		JOIN   pg_am    am ON am.oid = i.relam
		JOIN   LATERAL unnest(ix.indclass) WITH ORDINALITY AS uc(opcoid, ord) ON TRUE
		JOIN   pg_opclass opc ON opc.oid = uc.opcoid
		WHERE  cl.relname = 'documents'
		  AND  i.relname  = 'documents_body_trgm_gist'`
	var (
		amname  string
		opcname string
	)
	if err := tgtDB.QueryRowContext(ctx, idxQuery).Scan(&amname, &opcname); err != nil {
		t.Fatalf("index method/opclass query: %v", err)
	}
	if amname != "gist" {
		t.Errorf("target index method = %q; want gist", amname)
	}
	if opcname != "gist_trgm_ops" {
		t.Errorf("target index opclass = %q; want gist_trgm_ops", opcname)
	}
}

// TestMigrate_PG_PgTrgm_NotEnabled_DropsOpclass pins the loud-failure
// shape when --enable-pg-extension pg_trgm is NOT set. The schema
// reader's per-opclass gate (extensionOperatorClassEnabled) only
// fires when the operator opted into the extension; without that
// opt-in, the opclass is dropped from the IR and the writer emits
// the index without it. PG then rejects the CREATE INDEX with
// "operator class \"<x>\" does not exist for access method \"<y>\""
// — which on the index-creation phase surfaces as a Migrator.Run
// error, preserving the loud-failure tenet.
func TestMigrate_PG_PgTrgm_NotEnabled_DropsOpclass(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresWithTrgm(t, true)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE documents (
			id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			body TEXT NOT NULL
		);

		CREATE INDEX documents_body_trgm
		    ON documents USING GIN (body gin_trgm_ops);
	`
	applyPGDDL(t, sourceDSN, seedDDL)

	pgEng, _ := engines.Get("postgres")
	mig := &Migrator{
		Source:    pgEng,
		Target:    pgEng,
		SourceDSN: sourceDSN,
		TargetDSN: targetDSN,
		// Deliberately NO EnabledPGExtensions — the opt-in tenet
		// means a pg_trgm-using source without the flag must fail
		// loudly rather than silently dropping the opclass and
		// emitting a useless index.
	}

	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()
	err := mig.Run(ctx)
	if err == nil {
		t.Fatal("Migrator.Run = nil; want failure when opclass dropped from IR")
	}
	// PG's error: `data type text has no default operator class for
	// access method "gin"`. Be lenient on exact wording — assert on
	// the load-bearing fragments.
	msg := strings.ToLower(err.Error())
	if !strings.Contains(msg, "operator class") && !strings.Contains(msg, "default") {
		t.Errorf("err = %v; want mention of \"operator class\" / \"default\"", err)
	}
}

// TestMigrate_PG_PgTrgm_TargetMissing_RefusedAtPreflight pins the
// loud-failure default on a target that doesn't have pg_trgm
// installed. Mirrors the pgvector preflight refusal.
func TestMigrate_PG_PgTrgm_TargetMissing_RefusedAtPreflight(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresWithTrgm(t, false)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE documents (
			id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			body TEXT NOT NULL
		);
	`
	applyPGDDL(t, sourceDSN, seedDDL)

	pgEng, _ := engines.Get("postgres")
	mig := &Migrator{
		Source:              pgEng,
		Target:              pgEng,
		SourceDSN:           sourceDSN,
		TargetDSN:           targetDSN,
		EnabledPGExtensions: []string{"pg_trgm"},
	}

	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()
	err := mig.Run(ctx)
	if err == nil {
		t.Fatal("Migrator.Run = nil; want preflight refusal")
	}
	if !strings.Contains(err.Error(), "pg_trgm") {
		t.Errorf("err = %v; want mention of \"pg_trgm\"", err)
	}
	if !strings.Contains(err.Error(), "target") {
		t.Errorf("err = %v; want mention of \"target\"", err)
	}
}

// TestMigrate_PG_PgTrgm_CrossEngineToMySQL_RefusedAtPreflight pins
// the v0.30.1 wire-up: simple-mode migrate now runs
// checkCrossEngineSupportable before any data moves, so a PG source
// with a pg_trgm-indexed table targeting MySQL fails at preflight
// with an actionable refusal — NOT silently bulk-copies and then
// dies cryptically at MySQL Error 1170 during the indexes phase.
// Mirrors the existing chain_restore preflight; the gap was that
// migrate.go never called the helper.
func TestMigrate_PG_PgTrgm_CrossEngineToMySQL_RefusedAtPreflight(t *testing.T) {
	sourceDSN, _, pgCleanup := startPostgresWithTrgm(t, true)
	defer pgCleanup()

	_, mysqlTargetDSN, mysqlCleanup := startMySQL(t)
	defer mysqlCleanup()

	const seedDDL = `
		CREATE TABLE documents (
			id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			body TEXT NOT NULL
		);
		INSERT INTO documents (body) VALUES ('the quick brown fox');
		CREATE INDEX documents_body_trgm
		    ON documents USING GIN (body gin_trgm_ops);
	`
	applyPGDDL(t, sourceDSN, seedDDL)

	pgEng, _ := engines.Get("postgres")
	mysqlEng, _ := engines.Get("mysql")
	mig := &Migrator{
		Source:    pgEng,
		Target:    mysqlEng,
		SourceDSN: sourceDSN,
		TargetDSN: mysqlTargetDSN,
		// Deliberately NO EnabledPGExtensions — that flag pairing with
		// a non-PG target would short-circuit at the source-side
		// applyEnabledPGExtensions gate, which is a separate and
		// earlier refusal mechanism. The scenario this test exercises
		// is the operator running a vanilla cross-engine migrate on a
		// PG source that *happens* to have a pg_trgm-indexed table —
		// the v0.30.0 cycle showed that without the v0.30.1 migrate-
		// path preflight wire-up + the AM-based check in
		// unsupportablePGIndexToMySQL, the operator gets MySQL Error
		// 1170 after bulk-copy. Pinning that refusal here.
	}

	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()
	err := mig.Run(ctx)
	if err == nil {
		t.Fatal("Migrator.Run = nil; want cross-engine preflight refusal")
	}
	// Two distinct refusal mechanisms can fire here:
	//   1. applyEnabledPGExtensions refuses when --enable-pg-extension
	//      is paired with a non-PG target (source-side reader gate; the
	//      earliest gate in the migrate pipeline).
	//   2. The v0.30.1 migrate-path preflight via
	//      unsupportablePGIndexToMySQL refuses on the opclass-bearing
	//      IndexColumn (runs after ApplyMappings; only fires when (1)
	//      didn't already catch it).
	// Either is correct — both happen before any data moves. Assert on
	// the load-bearing operator-visible property: error message names
	// MySQL or cross-engine, and the target's documents table doesn't
	// exist.
	msg := err.Error()
	if !strings.Contains(msg, "mysql") && !strings.Contains(msg, "MySQL") &&
		!strings.Contains(msg, "cross-engine") {
		t.Errorf("err = %v; want mention of MySQL target or cross-engine refusal", err)
	}

	// Load-bearing: the refusal must fire BEFORE any rows reach MySQL.
	// Open the MySQL target and confirm the documents table doesn't
	// exist (preflight bailed before CreateTables).
	mysqlDB, openErr := sql.Open("mysql", mysqlTargetDSN)
	if openErr != nil {
		t.Fatalf("open mysql target: %v", openErr)
	}
	defer func() { _ = mysqlDB.Close() }()
	var name string
	err = mysqlDB.QueryRowContext(ctx,
		`SELECT table_name FROM information_schema.tables
		 WHERE  table_schema = DATABASE() AND table_name = 'documents'`).Scan(&name)
	if err == nil {
		t.Errorf("documents table exists on MySQL target after preflight refusal — wanted empty target")
	} else if !errors.Is(err, sql.ErrNoRows) {
		// driver couldn't run the query at all; that's also fine —
		// what matters is the table isn't there.
		t.Logf("table-existence query did not return ErrNoRows: %v (acceptable)", err)
	}
}

// TestMigrate_PG_Bug65_ExpressionIndexWithOpclass is the ADR-0045 §3
// (Bug 65, D3 full-carry) ground truth: the PG schema reader's
// populateIndexes used to NOT query pg_index.indexprs, so an
// expression-only index entry (indkey `0` sentinel, empty attname)
// hit `if colName == "" { continue }` and was SILENTLY DROPPED — the
// whole functional index vanished from the IR. ADR-0045 surfaces it
// via pg_get_indexdef into IndexColumn.Expression /
// ExpressionDialect="postgres", the PG-source analogue of the
// MySQL-source post-Bug-16 path.
//
// The index here is BOTH an expression index AND opclass-bearing
// (`USING GIN (lower(body) gin_trgm_ops)`), which is the Bug 47 /
// ADR-0032 interaction the ADR flags: surfacing the expression must
// not regress the independent opclass capture. Asserted on a PG→PG
// round-trip (the reader change is what's under test) plus an IR
// read-back proving Expression + OperatorClass both populate.
func TestMigrate_PG_Bug65_ExpressionIndexWithOpclass(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresWithTrgm(t, true)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE documents (
			id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			body TEXT NOT NULL
		);

		INSERT INTO documents (body) VALUES
			('The Quick Brown Fox'),
			('JUMPS over the Lazy Dog');

		-- Expression index, no opclass: pre-ADR-0045 this was dropped
		-- silently (Bug 65). lower(body) is a functional key.
		CREATE INDEX documents_lower_body ON documents (lower(body));

		-- Expression index WITH an extension opclass: Bug 65 must
		-- surface the expression AND not regress Bug 47 opclass capture.
		CREATE INDEX documents_lower_body_trgm
		    ON documents USING GIN (lower(body) gin_trgm_ops);
	`
	applyPGDDL(t, sourceDSN, seedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}
	mig := &Migrator{
		Source:              pgEng,
		Target:              pgEng,
		SourceDSN:           sourceDSN,
		TargetDSN:           targetDSN,
		EnabledPGExtensions: []string{"pg_trgm"},
	}
	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		t.Fatalf("Migrator.Run: %v", err)
	}

	tgtDB, err := sql.Open("pgx", targetDSN)
	if err != nil {
		t.Fatalf("open target: %v", err)
	}
	defer func() { _ = tgtDB.Close() }()

	// Both expression indexes must exist on the target — pre-ADR-0045
	// they'd be absent (silently dropped at read).
	for _, idxName := range []string{"documents_lower_body", "documents_lower_body_trgm"} {
		var n int
		if err := tgtDB.QueryRowContext(ctx, `
			SELECT COUNT(*)
			FROM   pg_index ix
			JOIN   pg_class i  ON i.oid = ix.indexrelid
			JOIN   pg_class cl ON cl.oid = ix.indrelid
			WHERE  cl.relname = 'documents' AND i.relname = $1`, idxName).Scan(&n); err != nil {
			t.Fatalf("index existence query (%s): %v", idxName, err)
		}
		if n == 0 {
			t.Errorf("expression index %q missing on target — Bug 65 regression (silent drop)", idxName)
		}
	}

	// The opclass on the expression index must be preserved (Bug 47
	// non-regression on an expression-bearing index).
	var amname, opcname string
	if err := tgtDB.QueryRowContext(ctx, `
		SELECT am.amname, opc.opcname
		FROM   pg_index ix
		JOIN   pg_class i  ON i.oid = ix.indexrelid
		JOIN   pg_class cl ON cl.oid = ix.indrelid
		JOIN   pg_am    am ON am.oid = i.relam
		JOIN   LATERAL unnest(ix.indclass) WITH ORDINALITY AS uc(opcoid, ord) ON TRUE
		JOIN   pg_opclass opc ON opc.oid = uc.opcoid
		WHERE  cl.relname = 'documents' AND i.relname = 'documents_lower_body_trgm'`).
		Scan(&amname, &opcname); err != nil {
		t.Fatalf("opclass query: %v", err)
	}
	if amname != "gin" {
		t.Errorf("expression index AM = %q; want gin", amname)
	}
	if opcname != "gin_trgm_ops" {
		t.Errorf("expression index opclass = %q; want gin_trgm_ops (Bug 47 regressed by Bug 65 fix)", opcname)
	}

	// IR read-back: the rebuilt schema must carry Expression +
	// ExpressionDialect on the expression index entries, and the
	// opclass on the trgm one — proving the reader populates the IR
	// (not just that PG happened to recreate it).
	pgRdr, err := pgEng.OpenSchemaReader(ctx, targetDSN)
	if err != nil {
		t.Fatalf("OpenSchemaReader on target: %v", err)
	}
	defer closeIf(pgRdr)
	if aware, ok := pgRdr.(ir.ExtensionAware); ok {
		if err := aware.EnableExtensions(ctx, []string{"pg_trgm"}); err != nil {
			t.Fatalf("EnableExtensions on target reader: %v", err)
		}
	}
	got, err := pgRdr.ReadSchema(ctx)
	if err != nil {
		t.Fatalf("ReadSchema on target: %v", err)
	}
	docs := findTable(got, "documents")
	if docs == nil {
		t.Fatal("target has no documents table")
	}
	var sawPlainExpr, sawTrgmExpr bool
	for _, idx := range docs.Indexes {
		for _, c := range idx.Columns {
			if c.Expression == "" {
				continue
			}
			if c.ExpressionDialect != "postgres" {
				t.Errorf("index %q expr dialect = %q; want postgres", idx.Name, c.ExpressionDialect)
			}
			switch idx.Name {
			case "documents_lower_body":
				sawPlainExpr = true
			case "documents_lower_body_trgm":
				sawTrgmExpr = true
				if c.OperatorClass != "gin_trgm_ops" {
					t.Errorf("trgm expression index opclass in IR = %q; want gin_trgm_ops",
						c.OperatorClass)
				}
			}
		}
	}
	if !sawPlainExpr {
		t.Errorf("plain expression index not surfaced into IR; indexes=%+v", docs.Indexes)
	}
	if !sawTrgmExpr {
		t.Errorf("opclass-bearing expression index not surfaced into IR; indexes=%+v", docs.Indexes)
	}
}
