//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// End-to-end CLI test for the `--format json` result envelope + JSON
// dry-run plan (docs/research/ai-friendly-sluice.md recommendation #2).
// Unlike the sibling tests in this file's package, the unit under test
// is the BUILT BINARY's stdout contract — one JSON object, nothing
// else — so the test compiles cmd/sluice and drives it as an agent
// would. Lives in internal/pipeline (TestMigrate_* name) so it lands
// in the pipeline-migrate CI shard.

package pipeline

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"testing"
	"time"
)

// buildSluiceBinary compiles cmd/sluice into t's temp dir and returns
// the binary path. ~seconds against a warm build cache.
func buildSluiceBinary(t *testing.T) string {
	t.Helper()
	bin := filepath.Join(t.TempDir(), "sluice")
	if runtime.GOOS == "windows" {
		bin += ".exe"
	}
	cmd := exec.Command("go", "build", "-o", bin, "sluicesync.dev/sluice/cmd/sluice")
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("go build cmd/sluice: %v\n%s", err, out)
	}
	return bin
}

// runSluice executes the binary and returns stdout, stderr, and the
// exit code (0 when the process succeeded).
func runSluice(t *testing.T, bin string, args ...string) (stdout, stderr string, exitCode int) {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()
	cmd := exec.CommandContext(ctx, bin, args...)
	cmd.Env = os.Environ()
	var outBuf, errBuf bytes.Buffer
	cmd.Stdout = &outBuf
	cmd.Stderr = &errBuf
	err := cmd.Run()
	code := 0
	if err != nil {
		var ee *exec.ExitError
		if !errors.As(err, &ee) {
			t.Fatalf("run %v: %v\nstderr: %s", args, err, errBuf.String())
		}
		code = ee.ExitCode()
	}
	return outBuf.String(), errBuf.String(), code
}

// decodeSingleJSONObject asserts stdout carries exactly one JSON
// object (the envelope contract) and decodes it.
func decodeSingleJSONObject(t *testing.T, stdout string) map[string]any {
	t.Helper()
	dec := json.NewDecoder(bytes.NewReader([]byte(stdout)))
	var doc map[string]any
	if err := dec.Decode(&doc); err != nil {
		t.Fatalf("stdout is not valid JSON: %v\nstdout: %s", err, stdout)
	}
	var extra any
	if err := dec.Decode(&extra); err == nil {
		t.Fatalf("stdout carries more than one JSON value: %s", stdout)
	}
	return doc
}

// envelopeTableNames pulls the name field from an envelope's tables /
// a plan's tables array.
func envelopeTableNames(t *testing.T, tables any) []string {
	t.Helper()
	list, ok := tables.([]any)
	if !ok {
		t.Fatalf("tables is not an array: %v", tables)
	}
	names := make([]string, 0, len(list))
	for _, entry := range list {
		names = append(names, entry.(map[string]any)["name"].(string))
	}
	return names
}

func containsName(names []string, want string) bool {
	for _, n := range names {
		if n == want {
			return true
		}
	}
	return false
}

// TestMigrate_JSONEnvelopeCLI drives the built binary end-to-end
// against a real Postgres pair and pins the four stdout contracts:
//
//  1. `--dry-run --format json` emits the plan object (with real row
//     counts — PG implements RowCounter) and nothing else on stdout.
//  2. `--dry-run` (text mode) leaves stdout EMPTY — the plan renders
//     on the stderr slog stream exactly as before the envelope layer.
//  3. A CLI-validation refusal under `--format json` still emits one
//     envelope (status "refused") and a non-zero exit code.
//  4. A real migrate under `--format json` emits one envelope with
//     status "completed" + the migrated table set.
func TestMigrate_JSONEnvelopeCLI(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()

	applyPGDDL(t, sourceDSN, `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL
		);
		INSERT INTO users (email) VALUES ('a@example.com'), ('b@example.com'), ('c@example.com');
	`)

	bin := buildSluiceBinary(t)
	baseArgs := []string{
		"migrate",
		"--source-driver", "postgres", "--source", sourceDSN,
		"--target-driver", "postgres", "--target", targetDSN,
	}

	t.Run("dry-run json plan", func(t *testing.T) {
		stdout, stderr, code := runSluice(t, bin, append(baseArgs, "--dry-run", "--format", "json")...)
		if code != 0 {
			t.Fatalf("exit %d\nstderr: %s", code, stderr)
		}
		doc := decodeSingleJSONObject(t, stdout)
		if doc["command"] != "migrate" || doc["dry_run"] != true {
			t.Fatalf("plan envelope header: %v", doc)
		}
		plan := doc["plan"].(map[string]any)
		if plan["source_engine"] != "postgres" || plan["target_engine"] != "postgres" {
			t.Fatalf("plan engines: %v", plan)
		}
		tables := plan["tables"].([]any)
		if len(tables) != 1 {
			t.Fatalf("plan tables: %v", tables)
		}
		users := tables[0].(map[string]any)
		if users["name"] != "users" || users["row_count"] != float64(3) {
			t.Fatalf("plan users entry: %v (want name=users row_count=3)", users)
		}
	})

	t.Run("dry-run text mode leaves stdout untouched", func(t *testing.T) {
		stdout, stderr, code := runSluice(t, bin, append(baseArgs, "--dry-run")...)
		if code != 0 {
			t.Fatalf("exit %d\nstderr: %s", code, stderr)
		}
		if stdout != "" {
			t.Fatalf("text-mode dry run wrote to stdout: %q", stdout)
		}
		if !bytes.Contains([]byte(stderr), []byte("dry run: migration plan")) {
			t.Fatalf("text-mode plan missing from stderr:\n%s", stderr)
		}
	})

	t.Run("refusal emits refused envelope", func(t *testing.T) {
		args := append(baseArgs, "--include-table", "users", "--exclude-table", "users", "--format", "json")
		stdout, stderr, code := runSluice(t, bin, args...)
		if code == 0 {
			t.Fatalf("mutually-exclusive filters must fail; stderr: %s", stderr)
		}
		doc := decodeSingleJSONObject(t, stdout)
		if doc["status"] != "refused" {
			t.Fatalf("status: %v (doc: %v)", doc["status"], doc)
		}
		msg := doc["error"].(map[string]any)["message"].(string)
		if !bytes.Contains([]byte(msg), []byte("mutually exclusive")) {
			t.Fatalf("error.message: %q", msg)
		}
	})

	t.Run("completed envelope with table stats", func(t *testing.T) {
		stdout, stderr, code := runSluice(t, bin, append(baseArgs, "--format", "json")...)
		if code != 0 {
			t.Fatalf("exit %d\nstderr: %s", code, stderr)
		}
		doc := decodeSingleJSONObject(t, stdout)
		if doc["command"] != "migrate" || doc["status"] != "completed" {
			t.Fatalf("envelope: %v", doc)
		}
		if doc["source_engine"] != "postgres" || doc["target_engine"] != "postgres" {
			t.Fatalf("engines: %v", doc)
		}
		names := envelopeTableNames(t, doc["tables"])
		if !containsName(names, "users") {
			t.Fatalf("tables missing users: %v", names)
		}
		resume := doc["resume"].(map[string]any)
		if resume["supported"] != true {
			t.Fatalf("resume: %v", resume)
		}
		steps := doc["next_steps"].([]any)
		if len(steps) == 0 {
			t.Fatalf("next_steps empty: %v", doc)
		}
		// The envelope must never carry either DSN (credentials ride in
		// them on real deployments).
		for _, dsn := range []string{sourceDSN, targetDSN} {
			if bytes.Contains([]byte(stdout), []byte(dsn)) {
				t.Fatalf("envelope leaked a DSN:\n%s", stdout)
			}
		}
	})
}
