//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// ADR-0053 — EXCLUDE constraint verbatim carry integration test.
//
// Pre-ADR sluice silently dropped every EXCLUDE constraint from the
// IR (the PG schema reader queried only contype='f' and 'c', never
// 'x'). PG → PG migrate of a schema with EXCLUDE constraints landed
// target tables MISSING the semantic invariant. This test pins the
// fix end-to-end: the schema reader populates ExcludeConstraints, the
// PG writer emits them inline in CREATE TABLE, and the target's
// pg_get_constraintdef matches the source's byte-exact for every
// observed shape from the GitLab corpus.
//
// Cross-engine PG → MySQL refusal is unit-tested in
// cross_engine_supportable_test.go; the integration test scope here
// is the same-engine happy path that closes the silent-loss class.

package pipeline

import (
	"context"
	"database/sql"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/engines"

	_ "sluicesync.dev/sluice/internal/engines/postgres"
)

// seedExcludeConstraintDDL exercises all four observed EXCLUDE
// shapes from the GitLab corpus:
//   - simple (column WITH op)
//   - predicated (WHERE predicate)
//   - multi-key (two pairs in the constraint body, including a
//     function-call expression as the second key)
//   - DEFERRABLE INITIALLY DEFERRED + predicated
//
// All four use the core GiST AM with default opclasses (no
// extension dependency); btree_gist would be needed for the
// equality operator on plain integer columns, so this fixture uses
// only operators GiST supports natively on tstzrange / daterange /
// int8range columns. The btree_gist case would broaden coverage but
// adds an extension-presence concern; defer to a follow-up if a
// real workload demands it.
const seedExcludeConstraintDDL = `
	CREATE TABLE shifts (
		id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		valid_during int8range NOT NULL,
		coverage     int8range NULL,
		shift_window tstzrange NULL,
		cadence_range daterange NULL,
		CONSTRAINT simple_overlap        EXCLUDE USING gist (valid_during WITH &&),
		CONSTRAINT predicated_overlap    EXCLUDE USING gist (coverage WITH &&) WHERE ((coverage IS NOT NULL)),
		CONSTRAINT multikey_overlap      EXCLUDE USING gist (valid_during WITH &&, shift_window WITH &&),
		CONSTRAINT deferrable_overlap    EXCLUDE USING gist (cadence_range WITH &&) WHERE ((cadence_range IS NOT NULL)) DEFERRABLE INITIALLY DEFERRED
	);
`

// TestMigrate_PG_ExcludeConstraint_VerbatimCarry is the ADR-0053
// happy path. No flag is required — EXCLUDE constraints are
// PG-only and carry verbatim on every same-engine PG → PG run.
func TestMigrate_PG_ExcludeConstraint_VerbatimCarry(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()
	applyPGDDL(t, sourceDSN, seedExcludeConstraintDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	mig := &Migrator{
		Source:    pgEng,
		Target:    pgEng,
		SourceDSN: sourceDSN,
		TargetDSN: targetDSN,
	}
	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		t.Fatalf("Migrator.Run: %v (ADR-0053: PG schema reader must populate "+
			"ExcludeConstraints AND PG writer must emit them inline)", err)
	}

	// Read both sides' pg_get_constraintdef and compare byte-exact for
	// every EXCLUDE constraint by name. PG canonicalises the output
	// server-side, so two structurally-identical constraints produce
	// byte-identical text — any divergence on the target is a real
	// verbatim-carry regression.
	srcDefs := readExcludeDefs(t, ctx, sourceDSN, "shifts")
	tgtDefs := readExcludeDefs(t, ctx, targetDSN, "shifts")

	if len(srcDefs) != 4 {
		t.Fatalf("source has %d EXCLUDE constraints; want 4 (the fixture "+
			"shape is the load-bearing characterisation)", len(srcDefs))
	}
	if len(tgtDefs) != len(srcDefs) {
		t.Fatalf("target has %d EXCLUDE constraints; want %d (verbatim "+
			"carry MUST preserve every constraint by count + by name)",
			len(tgtDefs), len(srcDefs))
	}
	for name, src := range srcDefs {
		tgt, ok := tgtDefs[name]
		if !ok {
			t.Errorf("target missing EXCLUDE constraint %q (silent-loss class "+
				"would have surfaced here pre-ADR-0053)", name)
			continue
		}
		if src != tgt {
			t.Errorf("EXCLUDE constraint %q definition diverged byte-exact\n"+
				"--- source ---\n%s\n--- target ---\n%s", name, src, tgt)
		}
	}
}

// readExcludeDefs returns a name → pg_get_constraintdef map for
// every contype='x' row on the named table.
func readExcludeDefs(t *testing.T, ctx context.Context, dsn, tableName string) map[string]string {
	t.Helper()
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		t.Fatalf("open %s: %v", dsn, err)
	}
	defer func() { _ = db.Close() }()

	const q = `
		SELECT con.conname,
		       pg_catalog.pg_get_constraintdef(con.oid, true)
		FROM   pg_constraint con
		JOIN   pg_class      cl ON cl.oid = con.conrelid
		WHERE  cl.relname    = $1
		  AND  con.contype   = 'x'
		ORDER  BY con.conname`

	rows, err := db.QueryContext(ctx, q, tableName)
	if err != nil {
		t.Fatalf("pg_constraint query on %s: %v", dsn, err)
	}
	defer func() { _ = rows.Close() }()

	out := map[string]string{}
	for rows.Next() {
		var name, def string
		if err := rows.Scan(&name, &def); err != nil {
			t.Fatalf("scan: %v", err)
		}
		out[name] = def
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows.Err: %v", err)
	}
	return out
}
