//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// ADR-0051 — core pg_catalog type verbatim carry integration test.
// Sibling to ADR-0047's migrate_verbatim_extension_integration_test
// (which covers uncatalogued USER-DEFINED types). This file covers
// the *core* types reported by information_schema with their literal
// name (range family, multirange family) — they never reach the
// USER-DEFINED branch, so the ADR-0047 mechanism does not engage.
//
// Same-engine PG → PG migrate of a table with range / multirange
// columns must:
//   - read schema without loud-refusal (the GitLab-corpus gap closed)
//   - emit DDL on the target with the exact source pg_catalog.format_type
//     spelling (verbatim re-emit)
//   - round-trip values via the type's text I/O
//   - round-trip a GiST index over a range column (core GiST AM, no
//     extension, no opclass passthrough complication)
//
// Cross-engine refusal is enforced by `cross_engine_supportable.go`'s
// existing `ir.VerbatimType` rejection — see ADR-0047's gate tests
// (verbatim_extension_gate_test.go); this ADR shares that gate.

package pipeline

import (
	"context"
	"database/sql"
	"strings"
	"testing"
	"time"

	"github.com/orware/sluice/internal/engines"

	_ "github.com/orware/sluice/internal/engines/postgres"
)

// seedCoreVerbatimDDL builds a table with one column from each Stage 1
// family (range / multirange) plus a tsvector to confirm the consolidated
// tsvector path still works through the same allowlist mechanism. The
// GiST index over int8range exercises the index-AM round-trip on a core
// GiST + the type's default opclass (range_ops, which PG's
// pg_get_indexdef omits because it's opcdefault=t — mirrors the ltree
// gist_ltree_ops shape in the ADR-0047 sibling test).
const seedCoreVerbatimDDL = `
	CREATE TABLE schedule_slots (
		id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		label         VARCHAR(64) NOT NULL,
		valid_during  int8range NOT NULL,
		on_dates      daterange NULL,
		window_at     tstzrange NULL,
		coverage_mr   int8multirange NULL,
		search_text   tsvector NULL
	);
	CREATE INDEX schedule_slots_valid_during_gist
		ON schedule_slots USING gist (valid_during);

	INSERT INTO schedule_slots (label, valid_during, on_dates, window_at, coverage_mr, search_text) VALUES
		('weekday-morning', '[1,100)', '[2026-01-01,2026-06-30)',
		 '[2026-05-21 08:00:00+00,2026-05-21 12:00:00+00)',
		 '{[1,10), [20,30)}',
		 to_tsvector('english', 'weekday morning coverage')),
		('weekend-evening', '[500,1000)', NULL,
		 '[2026-05-22 18:00:00+00,2026-05-22 23:00:00+00)',
		 '{[100,200)}',
		 to_tsvector('english', 'weekend evening shift')),
		('all-quarter',     '[1,1000)', '[2026-04-01,2026-07-01)',
		 NULL, NULL,
		 NULL);
`

// TestMigrate_PG_CoreVerbatim_RangesAndMultirange is ADR-0051's
// happy path. No flag is required — the verbatim tier is implicit from
// same-engine PG → PG identity (same shape as ADR-0047).
func TestMigrate_PG_CoreVerbatim_RangesAndMultirange(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()
	applyPGDDL(t, sourceDSN, seedCoreVerbatimDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	mig := &Migrator{
		Source:    pgEng,
		Target:    pgEng,
		SourceDSN: sourceDSN,
		TargetDSN: targetDSN,
		// Deliberately NO EnabledPGExtensions — ADR-0051 determination
		// is implicit for same-engine PG → PG. Mirrors ADR-0047 §3.
	}
	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		t.Fatalf("Migrator.Run: %v (this is the GitLab-corpus regression — "+
			"ADR-0051 closes it by allowlisting the core range / multirange "+
			"types in coreVerbatimEligibleTypes)", err)
	}

	tgtDB, err := sql.Open("pgx", targetDSN)
	if err != nil {
		t.Fatalf("open target: %v", err)
	}
	defer func() { _ = tgtDB.Close() }()

	// Column types re-emitted verbatim. pg_catalog.format_type equality
	// per column is the strongest assertion that the verbatim path
	// captured the exact source spelling and the writer re-emitted it
	// literally — not e.g. silently coerced to TEXT.
	wantFormatType := map[string]string{
		"valid_during": "int8range",
		"on_dates":     "daterange",
		"window_at":    "tstzrange",
		"coverage_mr":  "int8multirange",
		"search_text":  "tsvector",
	}
	for col, want := range wantFormatType {
		col, want := col, want
		t.Run("format_type/"+col, func(t *testing.T) {
			var got string
			if err := tgtDB.QueryRowContext(ctx, `
				SELECT pg_catalog.format_type(a.atttypid, a.atttypmod)
				FROM pg_attribute a
				JOIN pg_class c ON c.oid = a.attrelid
				WHERE c.relname = 'schedule_slots' AND a.attname = $1`, col).Scan(&got); err != nil {
				t.Fatalf("format_type(%s): %v", col, err)
			}
			if got != want {
				t.Errorf("target schedule_slots.%s = %q; want %q (verbatim spelling)",
					col, got, want)
			}
		})
	}

	// Row count round-trips.
	var n int
	if err := tgtDB.QueryRowContext(ctx, "SELECT COUNT(*) FROM schedule_slots").Scan(&n); err != nil {
		t.Fatalf("count: %v", err)
	}
	if n != 3 {
		t.Errorf("target rows = %d; want 3", n)
	}

	// Range value round-trips via text I/O. The canonical text form
	// (`[1,100)`) is what the verbatim text-IO path carries — assert
	// it directly.
	var validDuring string
	if err := tgtDB.QueryRowContext(ctx,
		"SELECT valid_during::text FROM schedule_slots WHERE label = 'weekday-morning'").Scan(&validDuring); err != nil {
		t.Fatalf("read valid_during: %v", err)
	}
	if validDuring != "[1,100)" {
		t.Errorf("valid_during = %q; want \"[1,100)\"", validDuring)
	}

	// Multirange value round-trips. Canonical form uses braces around
	// space-separated ranges; PG normalises whitespace on storage so
	// the readback may differ in inner spacing — assert via subset
	// rather than exact text equality.
	var coverageMR string
	if err := tgtDB.QueryRowContext(ctx,
		"SELECT coverage_mr::text FROM schedule_slots WHERE label = 'weekday-morning'").Scan(&coverageMR); err != nil {
		t.Fatalf("read coverage_mr: %v", err)
	}
	if !strings.Contains(coverageMR, "[1,10)") || !strings.Contains(coverageMR, "[20,30)") {
		t.Errorf("coverage_mr = %q; want it to contain \"[1,10)\" and \"[20,30)\"", coverageMR)
	}

	// GiST index over int8range round-tripped. range_ops is the default
	// opclass for range types (pg_opclass.opcdefault=t), so PG's
	// pg_get_indexdef omits the opclass spelling on BOTH source and
	// target — the round-trip is functionally exact even though the
	// opclass bareword isn't echoed in indexdef. We assert the index
	// exists, uses gist over valid_during, and is functionally usable
	// for an int8range overlap query.
	var idxDef string
	if err := tgtDB.QueryRowContext(ctx, `
		SELECT indexdef FROM pg_indexes
		WHERE tablename = 'schedule_slots' AND indexname = 'schedule_slots_valid_during_gist'`).Scan(&idxDef); err != nil {
		t.Fatalf("indexdef query: %v", err)
	}
	if !strings.Contains(idxDef, "USING gist") || !strings.Contains(idxDef, "valid_during") {
		t.Errorf("target index def = %q; want USING gist over (valid_during)", idxDef)
	}

	// Functional check: the GiST range index supports the && overlap
	// operator. '[50,200)' overlaps weekday-morning's [1,100) and
	// weekend-evening's [500,1000)? No — only the first.
	var overlapCount int
	if err := tgtDB.QueryRowContext(ctx,
		"SELECT COUNT(*) FROM schedule_slots WHERE valid_during && '[50,200)'::int8range").Scan(&overlapCount); err != nil {
		t.Fatalf("range overlap query: %v", err)
	}
	if overlapCount != 1 {
		t.Errorf("range && [50,200) matched %d rows; want 1 (weekday-morning)", overlapCount)
	}

	// NULL element preserved across the verbatim path.
	var onDates sql.NullString
	if err := tgtDB.QueryRowContext(ctx,
		"SELECT on_dates::text FROM schedule_slots WHERE label = 'weekend-evening'").Scan(&onDates); err != nil {
		t.Fatalf("read on_dates: %v", err)
	}
	if onDates.Valid {
		t.Errorf("on_dates for weekend-evening = %q; want NULL", onDates.String)
	}

	// tsvector still works via the consolidated allowlist (regression
	// guard for the catalog Bug 17 consolidation — the existing
	// tsvector path moved from a switch-case to the allowlist; this
	// confirms the existing FTS round-trip didn't break in the move).
	var searchText string
	if err := tgtDB.QueryRowContext(ctx,
		"SELECT search_text::text FROM schedule_slots WHERE label = 'weekday-morning'").Scan(&searchText); err != nil {
		t.Fatalf("read search_text: %v", err)
	}
	// to_tsvector('english', 'weekday morning coverage') produces
	// 'coverag':3 'morn':2 'weekday':1 (stems differ slightly per PG
	// version). Assert non-empty + contains at least one stem rather
	// than full text — the text-IO carry is what's load-bearing here,
	// not the FTS dictionary's exact output.
	if searchText == "" || !strings.Contains(searchText, "weekday") {
		t.Errorf("search_text = %q; want a non-empty tsvector containing 'weekday'", searchText)
	}
}
