//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// Task #42: cross-engine case-sensitivity test matrix — PG → PG path.
//
// What this pins (the "always quote, preserve verbatim" invariant):
//
//   - PG sources reading information_schema.tables.table_name into
//     ir.Table.Name without case-folding.
//   - PG writers (ddl_emit.go, row_writer.go, change_applier.go) wrapping
//     every identifier in double-quotes via quoteIdent(), preserving
//     whatever case the IR carries.
//   - PG cdc_reader.go extracting RelationName / per-column Name verbatim
//     from pgoutput.
//
// Regression shape this guards against: someone adds a strings.ToLower()
// in a schema reader, or "simplifies" the DDL emitter to drop quotes for
// "simple" identifiers, or the CDC path normalizes relation names. Any
// of those would make a case-preserved source table fail to round-trip
// — and the failure mode is silent on the bulk-copy path (rows copied
// into the wrong target table) and loud on the CDC path (PG raises
// "relation does not exist" when sluice tries to apply against a
// lower-cased name).
//
// Scope (Phase A discipline): only QUOTED source DDL. Unquoted DDL
// behaviour (PG folds to lowercase by SQL standard) is operator-intent
// territory and not what this matrix is pinning. We test with
// "MixedCase" etc. so the operator's intent is unambiguous.

package pipeline

import (
	"context"
	"database/sql"
	"fmt"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/engines"

	_ "sluicesync.dev/sluice/internal/engines/postgres"
)

// caseShape is one row in the test matrix: a table name + column name
// that together exercise a class of case patterns. The control
// (`lowercase_simple`) is the "should never regress" baseline; the
// other three are the load-bearing cases.
type caseShape struct {
	label  string // matrix label for t.Run subtest naming
	table  string // table identifier as the operator wrote it
	column string // identifier of the case-sensitive column under test
}

// caseShapes is the test matrix. Same matrix is shared across all four
// directions in the case-preservation test files — keeping it
// per-file (rather than one shared package-level var) keeps each file
// self-contained and easy to read.
var caseShapes = []caseShape{
	{label: "lowercase_simple", table: "widgets", column: "name"},
	{label: "UPPERCASE_ONLY", table: "WIDGETS", column: "USER_NAME"},
	{label: "MixedCase", table: "Widgets", column: "UserName"},
	{label: "Snake_With_Caps", table: "Widget_Inventory", column: "Last_Modified_At"},
}

// TestMigrate_CasePreservation_PostgresToPostgres pins same-engine PG
// case preservation on the bulk-copy (Migrator) path. For each shape,
// creates a source table with explicitly-quoted identifiers, seeds two
// rows, runs the simple-mode orchestrator, and asserts the target
// table name + column name match the source case-for-case AND the row
// data is intact.
//
// Each shape runs in its own subtest with its own container pair so
// one shape's failure doesn't pollute the others' assertions, and so
// the t.Run subtest name in CI logs pinpoints which shape regressed.
func TestMigrate_CasePreservation_PostgresToPostgres(t *testing.T) {
	for _, shape := range caseShapes {
		shape := shape
		t.Run(shape.label, func(t *testing.T) {
			sourceDSN, targetDSN, cleanup := startPostgres(t)
			defer cleanup()

			seedDDL := fmt.Sprintf(`
				CREATE TABLE %q (
					id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					%q      VARCHAR(255) NOT NULL
				);
				INSERT INTO %q (%q) VALUES ('alice'), ('bob');
			`, shape.table, shape.column, shape.table, shape.column)
			applyPGDDL(t, sourceDSN, seedDDL)

			pgEng, ok := engines.Get("postgres")
			if !ok {
				t.Fatal("postgres engine not registered")
			}

			mig := &Migrator{
				Source:    pgEng,
				Target:    pgEng,
				SourceDSN: sourceDSN,
				TargetDSN: targetDSN,
			}
			ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
			defer cancel()
			if err := mig.Run(ctx); err != nil {
				t.Fatalf("Migrator.Run: %v", err)
			}

			assertPGTableCasePreserved(t, ctx, targetDSN, shape)
			assertPGRowsPreserved(t, ctx, targetDSN, shape, 2)
		})
	}
}

// TestStreamer_CasePreservation_PostgresToPostgres pins same-engine PG
// case preservation on the CDC path. For each shape, cold-starts a
// Streamer (snapshot+CDC), waits for bulk-copy to land the seed rows,
// then INSERTs an additional row on the source and verifies it
// replicates to the target using the case-preserved table+column
// identifier. The CDC path is queried with quoted target names — if
// sluice's pgoutput parsing or change applier lower-cased an
// identifier somewhere, the apply would fail loudly with "relation
// does not exist" and the row never lands.
func TestStreamer_CasePreservation_PostgresToPostgres(t *testing.T) {
	for _, shape := range caseShapes {
		shape := shape
		t.Run(shape.label, func(t *testing.T) {
			sourceDSN, targetDSN, cleanup := startPostgresLogical(t)
			defer cleanup()

			// REPLICA IDENTITY FULL so UPDATEs/DELETEs are fully
			// represented over pgoutput; matters less here since we
			// only INSERT, but mirrors the streamer test conventions
			// in this package.
			seedDDL := fmt.Sprintf(`
				CREATE TABLE %q (
					id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					%q      VARCHAR(255) NOT NULL
				);
				ALTER TABLE %q REPLICA IDENTITY FULL;
				INSERT INTO %q (%q) VALUES ('alice'), ('bob');
			`, shape.table, shape.column, shape.table, shape.table, shape.column)
			applyPGDDL(t, sourceDSN, seedDDL)

			pgEng, ok := engines.Get("postgres")
			if !ok {
				t.Fatal("postgres engine not registered")
			}

			streamer := &Streamer{
				Source:    pgEng,
				Target:    pgEng,
				SourceDSN: sourceDSN,
				TargetDSN: targetDSN,
				StreamID:  "test-case-pres-pg-" + shape.label,
			}
			streamCtx, streamCancel := context.WithCancel(context.Background())
			defer streamCancel()
			runErr := make(chan error, 1)
			go func() { runErr <- streamer.Run(streamCtx) }()

			// Wait for bulk-copy to land the two seed rows on the target,
			// queried with the case-preserved identifier.
			if !waitForRowCountQuoted(t, targetDSN, shape.table, 2, 60*time.Second) {
				t.Fatalf("bulk copy never delivered seed rows to target table %q", shape.table)
			}

			// Schema-level case preservation check on the bulk-copy
			// side (the streamer's coldStart runs the same DDL emit
			// path as Migrator).
			assertPGTableCasePreserved(t, streamCtx, targetDSN, shape)

			// INSERT a third row via the source and verify it lands
			// through CDC.
			applyPGDDL(t, sourceDSN, fmt.Sprintf(
				`INSERT INTO %q (%q) VALUES ('carol');`,
				shape.table, shape.column,
			))
			if !waitForRowCountQuoted(t, targetDSN, shape.table, 3, 30*time.Second) {
				t.Fatalf("CDC never delivered post-snapshot INSERT to %q", shape.table)
			}

			// Verify the CDC-delivered row carries the carol value at
			// the case-preserved column name (not folded to lowercase
			// somewhere in the pgoutput → ir.Row → applier path).
			row := readOneRowByValueQuoted(t, streamCtx, targetDSN, shape.table, shape.column, "carol")
			if row == nil {
				t.Errorf("CDC row for 'carol' not found at %q.%q on target", shape.table, shape.column)
			}

			streamCancel()
			select {
			case <-runErr:
			case <-time.After(15 * time.Second):
				t.Fatal("Streamer.Run did not return after ctx cancel")
			}
		})
	}
}

// assertPGTableCasePreserved queries the PG target's information_schema
// for the given case-preserved table + column and fails the test if
// either is missing under that exact name. Uses `=` (case-sensitive),
// not ILIKE — that's the whole point.
func assertPGTableCasePreserved(t *testing.T, ctx context.Context, dsn string, shape caseShape) {
	t.Helper()
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		t.Fatalf("open target: %v", err)
	}
	defer func() { _ = db.Close() }()

	var got string
	err = db.QueryRowContext(ctx, `
		SELECT table_name
		FROM   information_schema.tables
		WHERE  table_schema = 'public' AND table_name = $1
	`, shape.table).Scan(&got)
	if err != nil {
		// List every table on the target to make the failure
		// actionable — if the table landed under a folded name, this
		// surfaces what sluice actually emitted.
		listed := listPGUserTables(t, ctx, db)
		t.Fatalf("table %q not found on PG target (case-folded?); target tables = %v", shape.table, listed)
	}
	if got != shape.table {
		t.Errorf("PG target table_name = %q; want %q (case-preserved)", got, shape.table)
	}

	var gotCol string
	err = db.QueryRowContext(ctx, `
		SELECT column_name
		FROM   information_schema.columns
		WHERE  table_schema = 'public'
		  AND  table_name   = $1
		  AND  column_name  = $2
	`, shape.table, shape.column).Scan(&gotCol)
	if err != nil {
		listed := listPGColumnsOf(t, ctx, db, shape.table)
		t.Fatalf("column %q on %q not found (case-folded?); columns = %v", shape.column, shape.table, listed)
	}
	if gotCol != shape.column {
		t.Errorf("PG target column_name = %q; want %q (case-preserved)", gotCol, shape.column)
	}
}

// assertPGRowsPreserved counts rows in the case-preserved target table
// and asserts the count matches `want`. Queries with the quoted
// identifier — if sluice routed bulk-copy data into a folded-name
// table, the count on the case-preserved name would be 0 or
// undefined-relation.
func assertPGRowsPreserved(t *testing.T, ctx context.Context, dsn string, shape caseShape, want int) {
	t.Helper()
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		t.Fatalf("open target: %v", err)
	}
	defer func() { _ = db.Close() }()

	var n int
	q := fmt.Sprintf(`SELECT count(*) FROM %q`, shape.table)
	if err := db.QueryRowContext(ctx, q).Scan(&n); err != nil {
		t.Fatalf("count rows on case-preserved %q: %v", shape.table, err)
	}
	if n != want {
		t.Errorf("target %q row count = %d; want %d", shape.table, n, want)
	}
}

// listPGUserTables lists every base table in the public schema on the
// target. Used for actionable failure messages — when a case-preserved
// table isn't found, the operator wants to see what sluice actually
// emitted.
func listPGUserTables(t *testing.T, ctx context.Context, db *sql.DB) []string {
	t.Helper()
	rows, err := db.QueryContext(ctx, `
		SELECT table_name FROM information_schema.tables
		WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
		ORDER BY table_name
	`)
	if err != nil {
		return []string{"<query failed: " + err.Error() + ">"}
	}
	defer func() { _ = rows.Close() }()
	var out []string
	for rows.Next() {
		var n string
		if err := rows.Scan(&n); err == nil {
			out = append(out, n)
		}
	}
	if err := rows.Err(); err != nil {
		out = append(out, "<rows.Err: "+err.Error()+">")
	}
	return out
}

// listPGColumnsOf lists every column on the named table (queried with
// the exact case the caller supplies — used when the table itself is
// case-preserved-found but a column lookup failed).
func listPGColumnsOf(t *testing.T, ctx context.Context, db *sql.DB, table string) []string {
	t.Helper()
	rows, err := db.QueryContext(ctx, `
		SELECT column_name FROM information_schema.columns
		WHERE table_schema = 'public' AND table_name = $1
		ORDER BY ordinal_position
	`, table)
	if err != nil {
		return []string{"<query failed: " + err.Error() + ">"}
	}
	defer func() { _ = rows.Close() }()
	var out []string
	for rows.Next() {
		var n string
		if err := rows.Scan(&n); err == nil {
			out = append(out, n)
		}
	}
	if err := rows.Err(); err != nil {
		out = append(out, "<rows.Err: "+err.Error()+">")
	}
	return out
}

// waitForRowCountQuoted is the case-preservation counterpart to
// waitForRowCount: queries the target with a double-quoted identifier
// (i.e. case-sensitive) so the matrix tests can poll for case-preserved
// tables.
func waitForRowCountQuoted(t *testing.T, dsn, table string, n int, timeout time.Duration) bool {
	t.Helper()
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		if pollRowCountPGQuoted(dsn, table) >= n {
			return true
		}
		time.Sleep(200 * time.Millisecond)
	}
	return false
}

// pollRowCountPGQuoted is the tolerant counterpart of countRows for
// case-preserved table names on a PG target: returns 0 on any error
// (table missing during the bulk-copy startup window, etc.) so the
// caller's poll doesn't spam fatals.
func pollRowCountPGQuoted(dsn, table string) int {
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		return 0
	}
	defer func() { _ = db.Close() }()
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	var n int
	q := fmt.Sprintf(`SELECT count(*) FROM %q`, table)
	if err := db.QueryRowContext(ctx, q).Scan(&n); err != nil {
		return 0
	}
	return n
}

// readOneRowByValueQuoted returns a non-nil map when a row with the
// given value at the given case-preserved column exists, and nil
// otherwise. Used to verify CDC-delivered rows landed at the
// case-preserved identifier, not some folded variant.
func readOneRowByValueQuoted(t *testing.T, ctx context.Context, dsn, table, column, want string) map[string]any {
	t.Helper()
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer func() { _ = db.Close() }()
	q := fmt.Sprintf(`SELECT count(*) FROM %q WHERE %q = $1`, table, column)
	var n int
	if err := db.QueryRowContext(ctx, q, want).Scan(&n); err != nil {
		t.Fatalf("read by case-preserved column %q.%q: %v", table, column, err)
	}
	if n == 0 {
		return nil
	}
	return map[string]any{column: want}
}
