//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// Integration test for Bug 14 (PG array → MySQL JSON override).
//
// Pre-fix shape: an operator using --type-override=col=jsonb to land
// a PG array column as MySQL JSON would see "Invalid JSON text:
// Missing a name for object member" — sluice's row writer bound the
// PG array literal `{a,b,c}` straight through, and MySQL's JSON
// parser rejected it.
//
// The fix: when the target is [ir.JSON] and the value is either a
// canonical IR `[]any` (the shape PG arrays decode to) or a PG
// array text literal `{...}`, convert to a JSON array string
// (`["a","b","c"]`) before binding. See [prepareValue] in
// internal/engines/mysql/row_writer.go for the conversion.

package pipeline

import (
	"context"
	"database/sql"
	"strings"
	"testing"
	"time"

	"github.com/orware/sluice/internal/config"
	"github.com/orware/sluice/internal/engines"

	_ "github.com/orware/sluice/internal/engines/mysql"
	_ "github.com/orware/sluice/internal/engines/postgres"
)

// TestMigrate_PostgresToMySQL_ArrayToJSONOverride exercises the
// canonical Bug 14 scenario: a PG `text[]` column on the source,
// `--type-override=tags.tags=jsonb` on the migrate command, target
// MySQL ends up with a `json` column carrying valid JSON arrays.
func TestMigrate_PostgresToMySQL_ArrayToJSONOverride(t *testing.T) {
	pgSource, _, pgCleanup := startPostgres(t)
	defer pgCleanup()

	_, mysqlTarget, mysqlCleanup := startMySQL(t)
	defer mysqlCleanup()

	const seedDDL = `
		CREATE TABLE tags (
			id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			tags TEXT[] NOT NULL
		);
		INSERT INTO tags (tags) VALUES
			(ARRAY['news', 'tech', 'sports']),
			(ARRAY['solo']),
			(ARRAY[]::TEXT[]);
	`
	applyPGDDL(t, pgSource, seedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}
	mysqlEng, ok := engines.Get("mysql")
	if !ok {
		t.Fatal("mysql engine not registered")
	}

	mig := &Migrator{
		Source:    pgEng,
		Target:    mysqlEng,
		SourceDSN: pgSource,
		TargetDSN: mysqlTarget,
		Mappings: []config.Mapping{
			{Table: "tags", Column: "tags", TargetType: "jsonb"},
		},
	}

	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		t.Fatalf("Migrator.Run: %v", err)
	}

	// The target column came out as MySQL `json` (the result of
	// the jsonb override on a MySQL target).
	gotType := readMySQLColumnType(t, ctx, mysqlTarget, "tags", "tags")
	if gotType != "json" {
		t.Errorf("target tags.tags column type = %q; want json", gotType)
	}

	// Each source row's array literal should have round-tripped as
	// a JSON array, NOT as the verbatim PG literal "{a,b,c}".
	rows := readMySQLAllJSON(t, ctx, mysqlTarget, "tags", "tags")
	want := []string{
		`["news", "tech", "sports"]`,
		`["solo"]`,
		`[]`,
	}
	if len(rows) != len(want) {
		t.Fatalf("got %d rows; want %d", len(rows), len(want))
	}
	for i, got := range rows {
		// MySQL's JSON_VALID round-trip preserves a stable
		// rendering of the document — array of strings — but the
		// exact whitespace MySQL emits varies between versions.
		// Normalise on whitespace before comparing.
		if normaliseJSON(got) != normaliseJSON(want[i]) {
			t.Errorf("row[%d]: got %q; want %q", i, got, want[i])
		}
	}
}

func readMySQLColumnType(t *testing.T, ctx context.Context, dsn, table, col string) string {
	t.Helper()
	db, err := sql.Open("mysql", dsn)
	if err != nil {
		t.Fatalf("open mysql: %v", err)
	}
	defer func() { _ = db.Close() }()
	const q = `
		SELECT data_type
		FROM   information_schema.columns
		WHERE  table_schema = DATABASE()
		  AND  table_name   = ?
		  AND  column_name  = ?`
	var dt string
	if err := db.QueryRowContext(ctx, q, table, col).Scan(&dt); err != nil {
		t.Fatalf("read column type: %v", err)
	}
	return dt
}

func readMySQLAllJSON(t *testing.T, ctx context.Context, dsn, table, col string) []string {
	t.Helper()
	db, err := sql.Open("mysql", dsn)
	if err != nil {
		t.Fatalf("open mysql: %v", err)
	}
	defer func() { _ = db.Close() }()
	rows, err := db.QueryContext(ctx, "SELECT "+col+" FROM "+table+" ORDER BY id")
	if err != nil {
		t.Fatalf("query: %v", err)
	}
	defer func() { _ = rows.Close() }()
	var out []string
	for rows.Next() {
		var v sql.NullString
		if err := rows.Scan(&v); err != nil {
			t.Fatalf("scan: %v", err)
		}
		if v.Valid {
			out = append(out, v.String)
		} else {
			out = append(out, "")
		}
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows.Err: %v", err)
	}
	return out
}

// normaliseJSON strips whitespace from a JSON string so two
// renderings of the same logical document compare equal. We don't
// pull in encoding/json's Decoder for this — the array shape is
// shallow and a strip-whitespace pass is enough to compare element
// order and content.
func normaliseJSON(s string) string {
	var b strings.Builder
	inString := false
	for i := 0; i < len(s); i++ {
		c := s[i]
		if c == '"' && (i == 0 || s[i-1] != '\\') {
			inString = !inString
		}
		if !inString && (c == ' ' || c == '\t' || c == '\n') {
			continue
		}
		b.WriteByte(c)
	}
	return b.String()
}
