//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// Standalone-sequence round-trip pins (item-51 TRIAGE finding #1).
//
// Value-level ground truth first: the silent-loss class was "the
// target's nextval() produces DIFFERENT numbers than the source
// would", so the load-bearing assertions here are actual INSERTs /
// nextval() calls on the migrated target — catalog-text equality is
// the dump-parity oracle's job (migrate_dump_parity_integration_test.go).
//
// The options matrix is the Bug-74 discipline applied to sequences:
// the reader/writer dispatch on the sequence's option/ownership
// SHAPE (ascending vs descending, type family, cycle/cache, owned vs
// unowned vs shared, serial-collapsible vs re-optioned), so each
// shape family gets its own pinned sequence rather than one
// representative.

package pipeline

import (
	"context"
	"database/sql"
	"errors"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/engines"
	"sluicesync.dev/sluice/internal/pipeline/migcore"
)

// TestMigrate_PGStandaloneSequence_ValueGroundTruth pins the fix's
// semantics at the value level:
//
//   - a FRESH standalone sequence (never nextval'd on the source)
//     produces its declared series on the target: 1000, 1005;
//   - a CONSUMED sequence (source already issued 1000, 1005 into
//     copied rows) CONTINUES on the target: the first post-migration
//     insert gets 1010, exactly what the source's next insert would
//     have produced — and never re-issues numbers the copied rows
//     already hold.
func TestMigrate_PGStandaloneSequence_ValueGroundTruth(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()

	const seedDDL = `
		CREATE SEQUENCE order_number_seq START WITH 1000 INCREMENT BY 5;
		CREATE SEQUENCE fresh_seq START WITH 1000 INCREMENT BY 5;
		CREATE TABLE orders (
			id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			order_number BIGINT NOT NULL DEFAULT nextval('order_number_seq')
		);
		INSERT INTO orders DEFAULT VALUES;
		INSERT INTO orders DEFAULT VALUES;
	`
	applyPGDDL(t, sourceDSN, seedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}
	mig := &Migrator{
		Source:    pgEng,
		Target:    pgEng,
		SourceDSN: sourceDSN,
		TargetDSN: targetDSN,
	}
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Minute)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		t.Fatalf("Migrator.Run: %v", err)
	}

	db, err := sql.Open("pgx", targetDSN)
	if err != nil {
		t.Fatalf("open target: %v", err)
	}
	defer func() { _ = db.Close() }()

	// Fresh sequence: declared series from the top.
	for _, want := range []int64{1000, 1005} {
		var got int64
		if err := db.QueryRowContext(ctx, "SELECT nextval('fresh_seq')").Scan(&got); err != nil {
			t.Fatalf("nextval(fresh_seq): %v", err)
		}
		if got != want {
			t.Errorf("fresh_seq nextval = %d; want %d (declared START 1000 INCREMENT 5)", got, want)
		}
	}

	// Consumed sequence: the first post-migration insert continues at
	// 1010 — the source consumed 1000 and 1005 into the copied rows.
	var orderNumber int64
	if err := db.QueryRowContext(ctx,
		"INSERT INTO orders DEFAULT VALUES RETURNING order_number").Scan(&orderNumber); err != nil {
		t.Fatalf("post-migration insert: %v", err)
	}
	if orderNumber != 1010 {
		t.Errorf("post-migration order_number = %d; want 1010 (source consumed 1000, 1005; pre-fix targets re-issued 1 — the identity collapse)", orderNumber)
	}
	// And the copied rows still hold the source-issued numbers.
	var n int
	if err := db.QueryRowContext(ctx,
		"SELECT count(*) FROM orders WHERE order_number IN (1000, 1005)").Scan(&n); err != nil {
		t.Fatalf("count copied rows: %v", err)
	}
	if n != 2 {
		t.Errorf("copied rows with source-issued numbers = %d; want 2", n)
	}
}

// sequenceCatalogRow is the option tuple compared source-vs-target in
// the options matrix — one row of pg_sequence plus the type spelling.
type sequenceCatalogRow struct {
	DataType  string
	Start     int64
	Increment int64
	MinValue  int64
	MaxValue  int64
	Cache     int64
	Cycle     bool
}

func readSequenceCatalogRow(ctx context.Context, t *testing.T, db *sql.DB, name string) (sequenceCatalogRow, bool) {
	t.Helper()
	const q = `
		SELECT pg_catalog.format_type(s.seqtypid, NULL),
		       s.seqstart, s.seqincrement, s.seqmin, s.seqmax, s.seqcache, s.seqcycle
		FROM   pg_class     c
		JOIN   pg_namespace n ON n.oid = c.relnamespace
		JOIN   pg_sequence  s ON s.seqrelid = c.oid
		WHERE  n.nspname = 'public' AND c.relname = $1 AND c.relkind = 'S'`
	var row sequenceCatalogRow
	err := db.QueryRowContext(ctx, q, name).Scan(
		&row.DataType, &row.Start, &row.Increment, &row.MinValue, &row.MaxValue, &row.Cache, &row.Cycle,
	)
	if errors.Is(err, sql.ErrNoRows) {
		return sequenceCatalogRow{}, false
	}
	if err != nil {
		t.Fatalf("read sequence catalog row %q: %v", name, err)
	}
	return row, true
}

// TestMigrate_PGStandaloneSequence_OptionsMatrix pins every sequence
// shape family src==dst on the real catalog:
//
//	ascending-custom / descending / cycle+cache (integer) / smallint /
//	shared-by-two-columns / re-optioned serial (owned, carried with
//	OWNED BY) — plus the serial-modernization control (a factory
//	serial column arrives as an IDENTITY column, not a sequence).
func TestMigrate_PGStandaloneSequence_OptionsMatrix(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()

	const seedDDL = `
		CREATE SEQUENCE seq_asc   START WITH 1000 INCREMENT BY 5;
		CREATE SEQUENCE seq_desc  INCREMENT BY -3 START WITH -10 MAXVALUE -1;
		CREATE SEQUENCE seq_cycle AS integer MINVALUE 1 MAXVALUE 50 CACHE 10 CYCLE;
		CREATE SEQUENCE seq_small AS smallint START WITH 5;
		CREATE SEQUENCE seq_shared START WITH 100 INCREMENT BY 10;

		CREATE TABLE tickets (
			id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			a_num  BIGINT NOT NULL DEFAULT nextval('seq_shared'),
			b_num  BIGINT NOT NULL DEFAULT nextval('seq_shared')
		);

		-- Re-optioned serial: OWNED BY survives, but the custom
		-- INCREMENT disqualifies the serial → identity modernization.
		CREATE TABLE legacy_reopt (id SERIAL PRIMARY KEY, note TEXT);
		ALTER SEQUENCE legacy_reopt_id_seq INCREMENT BY 7;

		-- Control: a factory serial stays on the modernization path.
		CREATE TABLE serial_ctl (id SERIAL PRIMARY KEY, note TEXT);

		INSERT INTO tickets DEFAULT VALUES;
		INSERT INTO legacy_reopt (note) VALUES ('x');
		INSERT INTO serial_ctl (note) VALUES ('y');

		-- Descending × consumed (delta-review extra pin): issue -10 on
		-- the source so the migrated target must CONTINUE at -13, not
		-- restart at -10.
		SELECT nextval('seq_desc');
	`
	applyPGDDL(t, sourceDSN, seedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}
	mig := &Migrator{
		Source:    pgEng,
		Target:    pgEng,
		SourceDSN: sourceDSN,
		TargetDSN: targetDSN,
	}
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Minute)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		t.Fatalf("Migrator.Run: %v", err)
	}

	srcDB, err := sql.Open("pgx", sourceDSN)
	if err != nil {
		t.Fatalf("open source: %v", err)
	}
	defer func() { _ = srcDB.Close() }()
	dstDB, err := sql.Open("pgx", targetDSN)
	if err != nil {
		t.Fatalf("open target: %v", err)
	}
	defer func() { _ = dstDB.Close() }()

	// Each carried family: the full option tuple must match the
	// source catalog exactly.
	for _, name := range []string{"seq_asc", "seq_desc", "seq_cycle", "seq_small", "seq_shared", "legacy_reopt_id_seq"} {
		src, srcOK := readSequenceCatalogRow(ctx, t, srcDB, name)
		if !srcOK {
			t.Fatalf("sequence %q missing on SOURCE — seed bug", name)
		}
		dst, dstOK := readSequenceCatalogRow(ctx, t, dstDB, name)
		if !dstOK {
			t.Errorf("sequence %q missing on target (silently collapsed?)", name)
			continue
		}
		if src != dst {
			t.Errorf("sequence %q options diverge:\n src %+v\n dst %+v", name, src, dst)
		}
	}

	// Descending × consumed: the source issued -10 pre-migrate, so the
	// target's next draw continues DOWNWARD at -13 — the position
	// carry must be direction-aware, never treating a descending
	// advance as a rewind.
	var descNext int64
	if err := dstDB.QueryRowContext(ctx, "SELECT nextval('seq_desc')").Scan(&descNext); err != nil {
		t.Fatalf("nextval(seq_desc): %v", err)
	}
	if descNext != -13 {
		t.Errorf("descending consumed nextval = %d; want -13 (source issued -10; INCREMENT -3 continues)", descNext)
	}

	// Shared topology: BOTH column defaults still reference
	// seq_shared, and one insert draws two consecutive values from
	// the SAME sequence (source consumed 100, 110 into the copied
	// row → target continues at 120, 130).
	var aNum, bNum int64
	if err := dstDB.QueryRowContext(ctx,
		"INSERT INTO tickets DEFAULT VALUES RETURNING a_num, b_num").Scan(&aNum, &bNum); err != nil {
		t.Fatalf("shared-sequence insert: %v", err)
	}
	if aNum != 120 || bNum != 130 {
		t.Errorf("shared-sequence insert = (%d, %d); want (120, 130) — both columns must draw from the ONE carried sequence", aNum, bNum)
	}

	// Re-optioned serial: ownership carried (pg_get_serial_sequence
	// resolves) and the custom increment holds at the value level.
	var owned sql.NullString
	if err := dstDB.QueryRowContext(ctx,
		"SELECT pg_get_serial_sequence('legacy_reopt', 'id')").Scan(&owned); err != nil {
		t.Fatalf("pg_get_serial_sequence: %v", err)
	}
	if !owned.Valid || owned.String != "public.legacy_reopt_id_seq" {
		t.Errorf("legacy_reopt.id owned sequence = %v; want public.legacy_reopt_id_seq (OWNED BY not carried)", owned)
	}
	var reoptID int64
	if err := dstDB.QueryRowContext(ctx,
		"INSERT INTO legacy_reopt (note) VALUES ('z') RETURNING id").Scan(&reoptID); err != nil {
		t.Fatalf("re-optioned serial insert: %v", err)
	}
	if reoptID != 8 {
		t.Errorf("re-optioned serial id = %d; want 8 (source issued 1, INCREMENT BY 7 continues)", reoptID)
	}

	// Serial-modernization control: factory serial arrives as an
	// IDENTITY column (attidentity 'd'), NOT a standalone sequence
	// with a nextval default — and the next insert continues past the
	// copied rows.
	var attidentity string
	if err := dstDB.QueryRowContext(ctx, `
		SELECT a.attidentity::text
		FROM   pg_attribute a
		WHERE  a.attrelid = 'public.serial_ctl'::regclass AND a.attname = 'id'`).Scan(&attidentity); err != nil {
		t.Fatalf("read serial_ctl.id attidentity: %v", err)
	}
	if attidentity != "d" {
		t.Errorf("serial_ctl.id attidentity = %q; want %q (serial → identity modernization, docs/type-mapping.md)", attidentity, "d")
	}
	var ctlID int64
	if err := dstDB.QueryRowContext(ctx,
		"INSERT INTO serial_ctl (note) VALUES ('w') RETURNING id").Scan(&ctlID); err != nil {
		t.Fatalf("serial control insert: %v", err)
	}
	if ctlID != 2 {
		t.Errorf("serial control id = %d; want 2 (SyncIdentitySequences past the copied row)", ctlID)
	}
}

// TestMigrate_PGIncludeTable_ExcludedSequenceOwner pins the audit N-4
// fix at the product level: `--include-table` selecting a subset that
// EXCLUDES the owner of a standalone owned sequence (any re-optioned
// serial outside the subset — a common source shape) must succeed.
// Pre-fix this failed DETERMINISTICALLY: the filter pruned only
// schema.Tables, the owned sequence passed through with OwnedByTable
// intact, and bindSequenceOwners emitted `ALTER SEQUENCE …
// OWNED BY <excluded_table>.<col>` → 42P01 after the kept tables were
// already created — blocking the shipped copy-table-subset guide's
// path. Post-fix: the owned sequence is dropped (with a WARN), the
// unowned standalone sequence still migrates, and the subset lands.
func TestMigrate_PGIncludeTable_ExcludedSequenceOwner(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()

	applyPGDDL(t, sourceDSN, `
		CREATE TABLE keep_me (
			id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			note TEXT
		);
		-- The excluded owner: a re-optioned serial, whose sequence is
		-- read as a standalone owned sequence (custom INCREMENT
		-- disqualifies the serial → identity modernization).
		CREATE TABLE excluded_owner (id SERIAL PRIMARY KEY, note TEXT);
		ALTER SEQUENCE excluded_owner_id_seq INCREMENT BY 7;
		-- Control: an unowned standalone sequence must still migrate.
		CREATE SEQUENCE unowned_seq START WITH 1000 INCREMENT BY 5;
		INSERT INTO keep_me (note) VALUES ('k');
		INSERT INTO excluded_owner (note) VALUES ('x');
	`)

	filter, err := migcore.NewTableFilter([]string{"keep_me"}, nil)
	if err != nil {
		t.Fatalf("NewTableFilter: %v", err)
	}
	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}
	mig := &Migrator{
		Source:    pgEng,
		Target:    pgEng,
		SourceDSN: sourceDSN,
		TargetDSN: targetDSN,
		Filter:    filter,
	}
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Minute)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		t.Fatalf("Migrator.Run with --include-table excluding a sequence owner: %v (pre-N-4-fix this was the 42P01 OWNED BY failure)", err)
	}

	db, err := sql.Open("pgx", targetDSN)
	if err != nil {
		t.Fatalf("open target: %v", err)
	}
	defer func() { _ = db.Close() }()

	// The subset landed with its row.
	var n int
	if err := db.QueryRowContext(ctx, "SELECT count(*) FROM keep_me").Scan(&n); err != nil {
		t.Fatalf("count keep_me: %v", err)
	}
	if n != 1 {
		t.Errorf("keep_me rows = %d; want 1", n)
	}

	// The excluded owner's table AND its owned sequence are absent.
	var exists bool
	if err := db.QueryRowContext(ctx,
		"SELECT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'excluded_owner' AND relkind = 'r')").Scan(&exists); err != nil {
		t.Fatalf("probe excluded_owner: %v", err)
	}
	if exists {
		t.Error("excluded_owner table present on target; the include filter should have dropped it")
	}
	if _, seqOK := readSequenceCatalogRow(ctx, t, db, "excluded_owner_id_seq"); seqOK {
		t.Error("excluded_owner_id_seq present on target; a sequence owned by a filtered-out table must be dropped with it")
	}

	// The unowned standalone sequence still migrated with its options.
	unowned, seqOK := readSequenceCatalogRow(ctx, t, db, "unowned_seq")
	if !seqOK {
		t.Fatal("unowned_seq missing on target; unowned standalone sequences must pass the filter")
	}
	if unowned.Start != 1000 || unowned.Increment != 5 {
		t.Errorf("unowned_seq options = %+v; want START 1000 INCREMENT 5", unowned)
	}
}

// TestMigrate_PGStandaloneSequence_PreCreatedTargetReprimes pins the
// delta-review finding-#1 resume shape: the target ALREADY has the
// standalone sequence, sitting at its unprimed start position — the
// crashed-between-create-and-prime window, and equally an operator
// pre-created sequence. The exists path must FORWARD-ONLY RE-PRIME
// (not silently skip): the first post-migration insert continues at
// 1010, never re-issuing the 1000/1005 the copied rows hold.
func TestMigrate_PGStandaloneSequence_PreCreatedTargetReprimes(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()

	applyPGDDL(t, sourceDSN, `
		CREATE SEQUENCE order_number_seq START WITH 1000 INCREMENT BY 5;
		CREATE TABLE orders (
			id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			order_number BIGINT NOT NULL DEFAULT nextval('order_number_seq')
		);
		INSERT INTO orders DEFAULT VALUES;
		INSERT INTO orders DEFAULT VALUES;
	`)
	// Target: the sequence exists but was never primed — exactly what
	// a crash between CREATE SEQUENCE and setval used to leave behind
	// (pre-fix those were two autocommit statements) and what an
	// operator pre-creating the sequence produces.
	applyPGDDL(t, targetDSN, `
		CREATE SEQUENCE order_number_seq START WITH 1000 INCREMENT BY 5;
	`)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}
	mig := &Migrator{
		Source:    pgEng,
		Target:    pgEng,
		SourceDSN: sourceDSN,
		TargetDSN: targetDSN,
	}
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Minute)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		t.Fatalf("Migrator.Run: %v", err)
	}

	db, err := sql.Open("pgx", targetDSN)
	if err != nil {
		t.Fatalf("open target: %v", err)
	}
	defer func() { _ = db.Close() }()

	var orderNumber int64
	if err := db.QueryRowContext(ctx,
		"INSERT INTO orders DEFAULT VALUES RETURNING order_number").Scan(&orderNumber); err != nil {
		t.Fatalf("post-migration insert: %v", err)
	}
	if orderNumber != 1010 {
		t.Errorf("post-migration order_number = %d; want 1010 — a pre-created unprimed target sequence must be re-primed forward, not silently skipped (silent duplicate class)", orderNumber)
	}
}
