//go:build integration

// Integration tests for the generated-column path: schema reader
// captures the GENERATED expression, the DDL writer recreates it on
// the target, and the row reader/writer drop the column from the
// bulk-copy column list so the target's GENERATED clause recomputes
// the value naturally.
//
// Translation policy is verbatim passthrough — the expression text
// is preserved as-is. These tests use a portable arithmetic
// expression (qty * price) that's valid in both MySQL and Postgres;
// non-portable expressions (e.g. CONCAT(a, b) vs a || b) would fail
// loudly on the target by design, not silently.

package pipeline

import (
	"context"
	"database/sql"
	"strconv"
	"testing"
	"time"

	"github.com/orware/sluice/internal/engines"

	_ "github.com/orware/sluice/internal/engines/mysql"
	_ "github.com/orware/sluice/internal/engines/postgres"
)

// TestMigrate_MySQLToMySQL_Generated verifies that a STORED generated
// column on the MySQL source is recreated on the MySQL target with the
// same expression, that bulk-copied rows recompute the generated
// value via the target's GENERATED clause (rather than being written
// directly), and that subsequent updates to dependent columns
// trigger correct recomputation.
func TestMigrate_MySQLToMySQL_Generated(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startMySQL(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE invoices (
			id    BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
			qty   INT             NOT NULL,
			price DECIMAL(10, 2)  NOT NULL,
			total DECIMAL(20, 2) GENERATED ALWAYS AS (qty * price) STORED,
			PRIMARY KEY (id)
		) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

		INSERT INTO invoices (qty, price) VALUES
			(2, 10.00),
			(3, 5.50);
	`
	applyMySQLDDL(t, sourceDSN, seedDDL)

	mysqlEng, ok := engines.Get("mysql")
	if !ok {
		t.Fatal("mysql engine not registered")
	}

	mig := &Migrator{
		Source:    mysqlEng,
		Target:    mysqlEng,
		SourceDSN: sourceDSN,
		TargetDSN: targetDSN,
	}

	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		t.Fatalf("Migrator.Run: %v", err)
	}

	// The target table must report `total` as a generated column;
	// pulling that information out of information_schema is the
	// authoritative way to confirm the GENERATED clause was emitted.
	tgt, err := sql.Open("mysql", targetDSN)
	if err != nil {
		t.Fatalf("open target: %v", err)
	}
	defer func() { _ = tgt.Close() }()

	var genExpr string
	const checkQ = `
		SELECT IFNULL(generation_expression, '')
		FROM   information_schema.columns
		WHERE  table_schema = DATABASE()
		  AND  table_name   = 'invoices'
		  AND  column_name  = 'total'`
	if err := tgt.QueryRowContext(ctx, checkQ).Scan(&genExpr); err != nil {
		t.Fatalf("query target generation_expression: %v", err)
	}
	if genExpr == "" {
		t.Fatalf("target invoices.total has no GENERATED expression; want non-empty")
	}

	// Bulk-copied rows: total should equal qty * price for each row.
	assertInvoiceTotals(t, ctx, tgt, []float64{20.00, 16.50})

	// Update a dependent column on the target; total must recompute.
	if _, err := tgt.ExecContext(ctx, "UPDATE invoices SET qty = 5 WHERE id = 1"); err != nil {
		t.Fatalf("update target: %v", err)
	}
	assertInvoiceTotals(t, ctx, tgt, []float64{50.00, 16.50})
}

// TestMigrate_PostgresToPostgres_Generated mirrors the MySQL same-
// engine test. Postgres only supports STORED generated columns, so
// the assertion shape is the same.
func TestMigrate_PostgresToPostgres_Generated(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgres(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE invoices (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			qty   INTEGER         NOT NULL,
			price NUMERIC(10, 2)  NOT NULL,
			total NUMERIC(20, 2)  GENERATED ALWAYS AS (qty * price) STORED
		);

		INSERT INTO invoices (qty, price) VALUES
			(2, 10.00),
			(3, 5.50);
	`
	applyPGDDL(t, sourceDSN, seedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	mig := &Migrator{
		Source:    pgEng,
		Target:    pgEng,
		SourceDSN: sourceDSN,
		TargetDSN: targetDSN,
	}

	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		t.Fatalf("Migrator.Run: %v", err)
	}

	tgt, err := sql.Open("pgx", targetDSN)
	if err != nil {
		t.Fatalf("open target: %v", err)
	}
	defer func() { _ = tgt.Close() }()

	// is_generated = 'ALWAYS' is the canonical PG marker for a
	// GENERATED column; the only storage class PG supports is STORED.
	var isGenerated, genExpr string
	const checkQ = `
		SELECT is_generated, COALESCE(generation_expression, '')
		FROM   information_schema.columns
		WHERE  table_schema = 'public'
		  AND  table_name   = 'invoices'
		  AND  column_name  = 'total'`
	if err := tgt.QueryRowContext(ctx, checkQ).Scan(&isGenerated, &genExpr); err != nil {
		t.Fatalf("query target is_generated: %v", err)
	}
	if isGenerated != "ALWAYS" || genExpr == "" {
		t.Fatalf("target invoices.total: is_generated=%q expr=%q; want ALWAYS + non-empty",
			isGenerated, genExpr)
	}

	assertInvoiceTotals(t, ctx, tgt, []float64{20.00, 16.50})

	if _, err := tgt.ExecContext(ctx, "UPDATE invoices SET qty = 5 WHERE id = 1"); err != nil {
		t.Fatalf("update target: %v", err)
	}
	assertInvoiceTotals(t, ctx, tgt, []float64{50.00, 16.50})
}

// TestMigrate_MySQLToPostgres_Generated exercises the cross-engine
// path. The expression `qty * price` is portable across both
// dialects, so the verbatim-passthrough policy lands a working
// GENERATED clause on the PG target without any translation.
//
// Non-portable expressions (function names that differ between
// dialects, operator-spelling differences) are out of scope: they
// fail loudly on the target by design, and operators recover by
// using the per-column mappings hook to drop the GENERATED clause
// or rewrite the source.
func TestMigrate_MySQLToPostgres_Generated(t *testing.T) {
	mysqlSource, _, mysqlCleanup := startMySQL(t)
	defer mysqlCleanup()

	_, pgTarget, pgCleanup := startPostgres(t)
	defer pgCleanup()

	const seedDDL = `
		CREATE TABLE invoices (
			id    BIGINT          NOT NULL AUTO_INCREMENT,
			qty   INT             NOT NULL,
			price DECIMAL(10, 2)  NOT NULL,
			total DECIMAL(20, 2)  GENERATED ALWAYS AS (qty * price) STORED,
			PRIMARY KEY (id)
		) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

		INSERT INTO invoices (qty, price) VALUES
			(2, 10.00),
			(3, 5.50);
	`
	applyMySQLDDL(t, mysqlSource, seedDDL)

	mysqlEng, ok := engines.Get("mysql")
	if !ok {
		t.Fatal("mysql engine not registered")
	}
	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	mig := &Migrator{
		Source:    mysqlEng,
		Target:    pgEng,
		SourceDSN: mysqlSource,
		TargetDSN: pgTarget,
	}

	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()
	if err := mig.Run(ctx); err != nil {
		t.Fatalf("Migrator.Run: %v", err)
	}

	tgt, err := sql.Open("pgx", pgTarget)
	if err != nil {
		t.Fatalf("open pg target: %v", err)
	}
	defer func() { _ = tgt.Close() }()

	var isGenerated, genExpr string
	const checkQ = `
		SELECT is_generated, COALESCE(generation_expression, '')
		FROM   information_schema.columns
		WHERE  table_schema = 'public'
		  AND  table_name   = 'invoices'
		  AND  column_name  = 'total'`
	if err := tgt.QueryRowContext(ctx, checkQ).Scan(&isGenerated, &genExpr); err != nil {
		t.Fatalf("query pg target is_generated: %v", err)
	}
	if isGenerated != "ALWAYS" || genExpr == "" {
		t.Fatalf("pg target invoices.total: is_generated=%q expr=%q; want ALWAYS + non-empty",
			isGenerated, genExpr)
	}

	assertInvoiceTotals(t, ctx, tgt, []float64{20.00, 16.50})

	if _, err := tgt.ExecContext(ctx, "UPDATE invoices SET qty = 5 WHERE id = 1"); err != nil {
		t.Fatalf("update pg target: %v", err)
	}
	assertInvoiceTotals(t, ctx, tgt, []float64{50.00, 16.50})
}

// assertInvoiceTotals reads the invoices table in PK order and
// asserts that each row's total column equals the supplied want
// value. Both MySQL and Postgres return DECIMAL/NUMERIC as a string
// via database/sql; we parse to float64 for the comparison.
func assertInvoiceTotals(t *testing.T, ctx context.Context, db *sql.DB, want []float64) {
	t.Helper()
	rows, err := db.QueryContext(ctx, "SELECT total FROM invoices ORDER BY id")
	if err != nil {
		t.Fatalf("select totals: %v", err)
	}
	defer func() { _ = rows.Close() }()

	var got []float64
	for rows.Next() {
		var totalStr string
		if err := rows.Scan(&totalStr); err != nil {
			t.Fatalf("scan total: %v", err)
		}
		got = append(got, parseDecimal(t, totalStr))
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows iteration: %v", err)
	}
	if len(got) != len(want) {
		t.Fatalf("got %d rows; want %d (got=%v)", len(got), len(want), got)
	}
	for i := range want {
		// DECIMAL comparison tolerates a tiny epsilon — the source and
		// target may differ in trailing-zero representation.
		const eps = 0.001
		if diff := got[i] - want[i]; diff < -eps || diff > eps {
			t.Errorf("row %d: total = %v; want %v", i, got[i], want[i])
		}
	}
}

// parseDecimal parses a DECIMAL/NUMERIC string into float64. Both
// drivers return DECIMAL/NUMERIC as a Go string; we only care about
// arithmetic equality for the assertions, not byte-perfect form.
func parseDecimal(t *testing.T, s string) float64 {
	t.Helper()
	v, err := strconv.ParseFloat(s, 64)
	if err != nil {
		t.Fatalf("parse decimal %q: %v", s, err)
	}
	return v
}
