//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// Selector-form × lane matrix for --redact (audit 2026-08-27 NEW-1).
//
// The defect: the redact preflight resolved a rule by (table, column)
// and ignored its schema, while every row-emitting lane hands
// [redact.Registry.Get] the table's stamped namespace — "" on a MySQL
// source in single-database mode. A schema-qualified rule
// (`source_db.users.email`) therefore passed preflight and then missed
// the registry key on every bulk-copy and backup row, while CDC rows
// (binlog rows carry the database name) hit it: the column shipped
// UNREDACTED at exit 0 on exactly the lanes that move the bulk of the
// data. The fix is upstream — the preflight resolves a qualified rule
// against a table in THAT namespace, refuses it on a flat-scope
// source, and now runs on the backup lane too — so the pin is per
// cell: the value is either redacted on the target, or the run
// refuses before any row moves. NEVER raw.
//
// Lanes: bulk copy on MySQL and on Postgres (Migrator), CDC on MySQL
// (Streamer cold start + a live insert), backup chunk write on MySQL
// and on Postgres (Backup, read back through Restore — a reader that
// is not the writer). Selector forms: bare `table.column`, qualified
// with the namespace the run reads, qualified with a foreign
// namespace. The expected verdict per cell is stated explicitly so a
// regression in EITHER direction (the flat-scope cell passing again,
// or the bare form being refused) is red.
//
// Mutation run 2026-09-02: restoring the schema-blind lookup in
// migcore.findSchemaTable turned the qualified-own × bulk-MySQL and
// × backup-MySQL cells red on THIS file's "row(s) landed with the
// PLAINTEXT value" assertion (plus every qualified-foreign cell on
// both engines); the bare cells stayed green, and they assert the
// pass direction explicitly, so a preflight that started refusing the
// bare form is red too.

package pipeline

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/engines"
	"sluicesync.dev/sluice/internal/ir"
	"sluicesync.dev/sluice/internal/pipeline/backup"
	"sluicesync.dev/sluice/internal/pipeline/blobcodec"
	"sluicesync.dev/sluice/internal/pipeline/lineage"
	"sluicesync.dev/sluice/internal/redact"

	_ "sluicesync.dev/sluice/internal/engines/mysql"
	_ "sluicesync.dev/sluice/internal/engines/postgres"
)

const (
	redactLanePlaintext = "alice@example.com"
	redactLaneRedacted  = "REDACTED"
)

const redactLaneSeedMySQL = `
	CREATE TABLE users (
		id    BIGINT       NOT NULL AUTO_INCREMENT,
		email VARCHAR(255) NOT NULL,
		PRIMARY KEY (id)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
	INSERT INTO users (email) VALUES ('` + redactLanePlaintext + `');
`

const redactLaneSeedPG = `
	CREATE TABLE users (
		id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		email VARCHAR(255) NOT NULL
	);
	INSERT INTO users (email) VALUES ('` + redactLanePlaintext + `');
`

// redactSelectorForm is one selector spelling of the same intent —
// "redact users.email" — and the verdict the preflight owes it on a
// source whose tables carry ownNamespace ("" = flat scope).
type redactSelectorForm struct {
	name       string
	schema     string
	wantRefuse bool
}

// redactSelectorForms enumerates the three CLI-producible spellings for
// a run that reads readNamespace (what the operator would write for
// "this database/schema") on a source whose tables are stamped with
// stampedNamespace ("" for single-database MySQL, "public" for PG).
func redactSelectorForms(readNamespace, stampedNamespace string) []redactSelectorForm {
	return []redactSelectorForm{
		{name: "bare", schema: ""},
		// The NEW-1 cell: on a flat-scope source the qualified form can
		// match no bulk row, so it MUST refuse; on a namespaced source
		// it resolves and must redact.
		{name: "qualified-own", schema: readNamespace, wantRefuse: stampedNamespace == ""},
		{name: "qualified-foreign", schema: "other_ns", wantRefuse: true},
	}
}

func (f redactSelectorForm) registry() *redact.Registry {
	r := redact.New()
	r.Set(f.schema, "users", "email", redact.Static{Value: redactLaneRedacted})
	return r
}

// assertRedactLaneVerdict is the per-cell oracle. counts returns
// (raw, redacted) row counts on the target; a missing target table
// counts as (0, 0).
func assertRedactLaneVerdict(t *testing.T, f redactSelectorForm, runErr error, counts func() (raw, redacted int)) {
	t.Helper()
	raw, redacted := counts()
	if raw != 0 {
		t.Errorf("%d row(s) landed with the PLAINTEXT value — the silent-loss shape this matrix exists to catch (run err: %v)", raw, runErr)
	}
	if f.wantRefuse {
		if runErr == nil {
			t.Fatalf("selector %q must be refused at preflight (it can match no row on this lane); run returned nil", f.schema+".users.email")
		}
		if !errors.Is(runErr, errRedactSelectorUnresolved) {
			t.Fatalf("want errRedactSelectorUnresolved; got: %v", runErr)
		}
		if redacted != 0 {
			t.Errorf("refused run must move no rows; found %d redacted row(s) on the target", redacted)
		}
		return
	}
	if runErr != nil {
		t.Fatalf("selector %q must pass preflight and redact; run refused: %v", f.schema+".users.email", runErr)
	}
	if redacted == 0 {
		t.Fatal("run passed but no redacted row reached the target (nothing was copied?)")
	}
}

func redactLaneCountsMySQL(dsn string) func() (raw, redacted int) {
	return func() (int, int) {
		db, err := sql.Open("mysql", dsn)
		if err != nil {
			return 0, 0
		}
		defer func() { _ = db.Close() }()
		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()
		var raw, red int
		if err := db.QueryRowContext(
			ctx,
			"SELECT SUM(email = ?), SUM(email = ?) FROM users", redactLanePlaintext, redactLaneRedacted,
		).Scan(&raw, &red); err != nil {
			return 0, 0 // table absent (refused run) or empty
		}
		return raw, red
	}
}

func redactLaneCountsPG(dsn string) func() (raw, redacted int) {
	return func() (int, int) {
		db, err := sql.Open("pgx", dsn)
		if err != nil {
			return 0, 0
		}
		defer func() { _ = db.Close() }()
		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()
		var raw, red int
		if err := db.QueryRowContext(
			ctx,
			"SELECT count(*) FILTER (WHERE email = $1), count(*) FILTER (WHERE email = $2) FROM users",
			redactLanePlaintext, redactLaneRedacted,
		).Scan(&raw, &red); err != nil {
			return 0, 0
		}
		return raw, red
	}
}

// freshMySQLTarget creates an empty database on the source's server and
// returns a DSN for it, so each cell starts from a clean target.
func freshMySQLTarget(t *testing.T, sourceDSN, name string) string {
	t.Helper()
	applyDDLMySQL(t, sourceDSN, "CREATE DATABASE "+name)
	dsn, err := buildMySQLDSN(sourceDSN, name)
	if err != nil {
		t.Fatalf("build target DSN: %v", err)
	}
	return dsn
}

// freshPGTarget (the Postgres twin) already exists in
// migrate_where_pg_integration_test.go with the same contract.

func engineOrFatal(t *testing.T, name string) ir.Engine {
	t.Helper()
	eng, ok := engines.Get(name)
	if !ok {
		t.Fatalf("%s engine not registered", name)
	}
	return eng
}

// TestRedactSelectorLaneMatrix_BulkMySQL — the lane NEW-1 leaked on:
// single-database MySQL stamps Table.Schema = "", so the bulk copy
// hands "" to the registry.
func TestRedactSelectorLaneMatrix_BulkMySQL(t *testing.T) {
	sourceDSN, _, cleanup := startMySQL(t)
	defer cleanup()
	applyDDLMySQL(t, sourceDSN, redactLaneSeedMySQL)
	eng := engineOrFatal(t, "mysql")

	for i, f := range redactSelectorForms("source_db", "") {
		t.Run(f.name, func(t *testing.T) {
			targetDSN := freshMySQLTarget(t, sourceDSN, fmt.Sprintf("tgt_bulk_%d", i))
			ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
			defer cancel()
			err := (&Migrator{
				Source: eng, Target: eng, SourceDSN: sourceDSN, TargetDSN: targetDSN,
				Redactor: f.registry(),
			}).Run(ctx)
			assertRedactLaneVerdict(t, f, err, redactLaneCountsMySQL(targetDSN))
		})
	}
}

// TestRedactSelectorLaneMatrix_BulkPG — the namespaced sibling: PG
// stamps Table.Schema = "public", so the qualified-own form resolves
// and must redact, and only the foreign namespace refuses.
func TestRedactSelectorLaneMatrix_BulkPG(t *testing.T) {
	sourceDSN, _, cleanup := startPostgres(t)
	defer cleanup()
	applyPGDDL(t, sourceDSN, redactLaneSeedPG)
	eng := engineOrFatal(t, "postgres")

	for i, f := range redactSelectorForms("public", "public") {
		t.Run(f.name, func(t *testing.T) {
			targetDSN := freshPGTarget(t, sourceDSN, fmt.Sprintf("tgt_bulk_%d", i))
			ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
			defer cancel()
			err := (&Migrator{
				Source: eng, Target: eng, SourceDSN: sourceDSN, TargetDSN: targetDSN,
				Redactor: f.registry(),
			}).Run(ctx)
			assertRedactLaneVerdict(t, f, err, redactLaneCountsPG(targetDSN))
		})
	}
}

// TestRedactSelectorLaneMatrix_CDCMySQL — sync cold start (bulk copy
// of the seed row) followed by a live INSERT that arrives through the
// binlog with Schema = "source_db". Pre-fix this is the lane that DID
// redact the qualified-own form while its own cold-start bulk copy did
// not; post-fix the form is refused before the cold start moves a row,
// and the bare form redacts on both halves.
func TestRedactSelectorLaneMatrix_CDCMySQL(t *testing.T) {
	sourceDSN, _, cleanup := startMySQLBinlog(t)
	defer cleanup()
	applyDDLMySQL(t, sourceDSN, redactLaneSeedMySQL)
	eng := engineOrFatal(t, "mysql")

	for i, f := range redactSelectorForms("source_db", "") {
		t.Run(f.name, func(t *testing.T) {
			targetDSN := freshMySQLTarget(t, sourceDSN, fmt.Sprintf("tgt_cdc_%d", i))
			ctx, cancel := context.WithCancel(context.Background())
			defer cancel()
			runErr := make(chan error, 1)
			go func() {
				runErr <- (&Streamer{
					Source: eng, Target: eng, SourceDSN: sourceDSN, TargetDSN: targetDSN,
					StreamID: fmt.Sprintf("redact-lane-%d", i),
					Redactor: f.registry(),
				}).Run(ctx)
			}()

			counts := redactLaneCountsMySQL(targetDSN)
			if f.wantRefuse {
				select {
				case err := <-runErr:
					assertRedactLaneVerdict(t, f, err, counts)
				case <-time.After(90 * time.Second):
					t.Fatal("streamer did not refuse within 90s (preflight let the rule through?)")
				}
				return
			}

			// Cold start lands the seed row through the bulk-copy half.
			if !waitForRowCountMySQL(t, targetDSN, "users", 1, 60*time.Second) {
				t.Fatalf("cold start never delivered the seed row; run err: %v", drainRunErr(runErr))
			}
			// The CDC half: a binlog row carrying Schema = "source_db".
			applyDDLMySQL(t, sourceDSN, "INSERT INTO users (email) VALUES ('"+redactLanePlaintext+"');")
			if !waitForRowCountMySQL(t, targetDSN, "users", 2, 60*time.Second) {
				t.Fatalf("CDC never delivered the live insert; run err: %v", drainRunErr(runErr))
			}
			cancel()
			select {
			case <-runErr:
			case <-time.After(30 * time.Second):
				t.Fatal("streamer did not return after cancel")
			}
			assertRedactLaneVerdict(t, f, nil, counts)
			if _, redacted := counts(); redacted != 2 {
				t.Errorf("want both the bulk-copied and the CDC row redacted; got %d", redacted)
			}
		})
	}
}

// drainRunErr returns a run error that has already arrived, or nil.
func drainRunErr(runErr <-chan error) error {
	select {
	case err := <-runErr:
		return err
	default:
		return nil
	}
}

// TestRedactSelectorLaneMatrix_BackupMySQL — the backup chunk writer
// redacts through the same RedactRow with the same "" namespace, and
// pre-fix ran NO redaction preflight at all. The archive is read back
// through Restore into a fresh database — a reader that is not the
// writer — and graded on the restored rows.
func TestRedactSelectorLaneMatrix_BackupMySQL(t *testing.T) {
	sourceDSN, _, cleanup := startMySQLBinlog(t)
	defer cleanup()
	applyDDLMySQL(t, sourceDSN, redactLaneSeedMySQL)
	eng := engineOrFatal(t, "mysql")

	for i, f := range redactSelectorForms("source_db", "") {
		t.Run(f.name, func(t *testing.T) {
			runBackupRestoreCell(t, f, eng, sourceDSN,
				freshMySQLTarget(t, sourceDSN, fmt.Sprintf("tgt_bk_%d", i)), redactLaneCountsMySQL)
		})
	}
}

// TestRedactSelectorLaneMatrix_BackupPG — the namespaced backup sibling.
func TestRedactSelectorLaneMatrix_BackupPG(t *testing.T) {
	sourceDSN, _, cleanup := startPostgresLogical(t)
	defer cleanup()
	applyPGDDL(t, sourceDSN, redactLaneSeedPG)
	eng := engineOrFatal(t, "postgres")

	for i, f := range redactSelectorForms("public", "public") {
		t.Run(f.name, func(t *testing.T) {
			runBackupRestoreCell(t, f, eng, sourceDSN,
				freshPGTarget(t, sourceDSN, fmt.Sprintf("tgt_bk_%d", i)), redactLaneCountsPG)
		})
	}
}

// runBackupRestoreCell takes a full backup with the form's registry
// into a fresh local store; a refused run must leave no manifest, a
// passing run is restored into targetDSN and graded there.
func runBackupRestoreCell(t *testing.T, f redactSelectorForm, eng ir.Engine, sourceDSN, targetDSN string, counts func(string) func() (int, int)) {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Minute)
	defer cancel()
	store, err := blobcodec.NewLocalStore(t.TempDir())
	if err != nil {
		t.Fatalf("NewLocalStore: %v", err)
	}
	backupErr := (&backup.Backup{Source: eng, SourceDSN: sourceDSN, Store: store, Redactor: f.registry()}).Run(ctx)
	if backupErr == nil {
		if err := (&backup.Restore{Target: eng, TargetDSN: targetDSN, Store: store}).Run(ctx); err != nil {
			t.Fatalf("Restore.Run: %v", err)
		}
	} else if m, err := lineage.ReadManifestIfPresent(ctx, store); err == nil && m != nil {
		t.Errorf("refused backup must not leave a manifest behind (it would carry the unredacted chunks); found %q", m.BackupID)
	}
	assertRedactLaneVerdict(t, f, backupErr, counts(targetDSN))
}
