//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// ADR-0054 Bug 84 end-to-end pin — PG → PG.
//
// Reproduces v0.73.1's PG-specific "unrecognized multi-shape combo
// delta" refusal on Shape A live coordination. The Bug 83 pin
// (shard_consolidation_bug83_pg_integration_test.go) uses a minimal
// schema (`id INT PRIMARY KEY, name TEXT NOT NULL`) whose type-struct
// projection happens to match between the cold-start SchemaReader and
// the CDC pgoutput RelationMessage path. Bug 84's schema uses
// `id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//  name VARCHAR(64) NOT NULL` — the IDENTITY column's
// `Integer.AutoIncrement` and the VARCHAR's `Charset`/`Collation`
// are populated by the SchemaReader but NOT by pgoutput's
// RelationMessage projection. The classifier's `reflect.DeepEqual` on
// the IR Type structs therefore reports `altered-col=true` on every
// existing column, combining with the legitimate `added=1` (the
// `price` column) into a multi-shape combo refusal.
//
// Post-fix the engine-level CDC-comparison normalizer strips those
// known-asymmetric fields from the cold-start seed before storing it
// in the intercept's cache, so the seed's projection matches what
// pgoutput later emits and only the real boundary (added=1) fires.
//
// "Validate end-to-end before building more" — this is the cross-
// engine pin Bug 83 v1 shipped without (the cost was Bug 84).

package pipeline

import (
	"context"
	"database/sql"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/engines"

	_ "sluicesync.dev/sluice/internal/engines/postgres"
)

// TestStreamer_Bug84_PG_LiveCoordination_AddColumn pins the canonical
// Bug 84 repro on PG: streamer runs cold-start → CDC with a schema
// that exercises IDENTITY + VARCHAR (the field-asymmetry case);
// source ALTER adds a column; subsequent INSERT on the source
// replicates without the classifier surfacing a multi-shape combo
// delta refusal, and the lease table's row reflects an applied
// boundary.
func TestStreamer_Bug84_PG_LiveCoordination_AddColumn(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresLogical(t)
	defer cleanup()

	// Bug 84's exact schema (from sluice-testing/BUG-CATALOG.md): a
	// BIGINT IDENTITY column and a VARCHAR — both surfaces where the
	// pgoutput RelationMessage projection is poorer than the
	// SchemaReader (no Integer.AutoIncrement bit, no Varchar.Collation).
	applyPGDDL(t, sourceDSN, `
		CREATE TABLE widgets (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name VARCHAR(64) NOT NULL
		);
		ALTER TABLE widgets REPLICA IDENTITY FULL;
		INSERT INTO widgets (name) VALUES ('alpha'), ('beta');
	`)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	const streamID = "test-bug84-pg"
	streamer := &Streamer{
		Source:    pgEng,
		Target:    pgEng,
		SourceDSN: sourceDSN,
		TargetDSN: targetDSN,
		StreamID:  streamID,
		InjectShardColumn: ShardColumnSpec{
			Name:  "source_shard_id",
			Value: "shard_a",
		},
		// Engage live coordination — this is what the CLI default
		// (--no-coordinate-live-ddl absent) produces.
		CoordinateLiveDDL: true,
		ShardCoordinationLease: LeaseConfig{
			LeaseDuration: 30 * time.Second,
			RenewDeadline: 20 * time.Second,
			RetryPeriod:   5 * time.Second,
		},
	}

	streamCtx, streamCancel := context.WithCancel(context.Background())
	defer streamCancel()

	runErr := make(chan error, 1)
	go func() { runErr <- streamer.Run(streamCtx) }()

	// Wait for bulk-copy to land the 2 seed rows on the target.
	if !waitForPGRowCount(t, targetDSN, "widgets", 2, 30*time.Second) {
		t.Fatalf("phase A: bulk-copy never landed seed rows (cold-start path stalled before CDC)")
	}

	// Apply source DDL + INSERT BEFORE any other CDC events flow. This
	// is the precise Bug 83/84 timing: source schema changes between
	// cold-start completion and the first row event the CDC reader
	// has to surface as a SchemaSnapshot. Bug 84 specifically: the
	// classifier's IR-Type DeepEqual surfaces a false positive
	// `altered-col=true` on the existing columns because the cold-
	// start seed carries SchemaReader-rich fields (AutoIncrement /
	// Collation) while the CDC projection does not.
	applyPGDDL(t, sourceDSN, `
		ALTER TABLE widgets ADD COLUMN price NUMERIC(10,2);
		INSERT INTO widgets (name, price) VALUES ('gamma', 3.75);
	`)

	// Wait for the post-DDL row to land. Pre-fix this never happens —
	// the classifier refuses the boundary with "unrecognized multi-
	// shape combo delta (added=1 dropped=0 created-idx=0 dropped-idx=0
	// altered-col=true)" and the streamer exits with the refusal.
	if !waitForPGRowCount(t, targetDSN, "widgets", 3, 60*time.Second) {
		t.Fatalf("phase B: post-DDL row never landed — Bug 84 regression " +
			"(classifier surfaced a false 'altered-col=true' on existing columns " +
			"because the cold-start seed's IR Type fields didn't match what pgoutput " +
			"projects from the wire — engine CDC-comparison normalizer missing)")
	}

	// Assert the target schema reflects the added column.
	tgtDB, err := sql.Open("pgx", targetDSN)
	if err != nil {
		t.Fatalf("open target: %v", err)
	}
	defer func() { _ = tgtDB.Close() }()

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	var hasPrice int
	if err := tgtDB.QueryRowContext(ctx, `
		SELECT COUNT(*) FROM information_schema.columns
		WHERE table_schema = 'public' AND table_name = 'widgets' AND column_name = 'price'
	`).Scan(&hasPrice); err != nil {
		t.Fatalf("check column: %v", err)
	}
	if hasPrice != 1 {
		t.Errorf("target widgets.price column missing — boundary apply didn't fire")
	}

	// Assert the lease row reflects the applied state. Bug 84's pre-
	// fix symptom is an EMPTY lease table (the classifier refused
	// before the lease-acquire path could record).
	const leaseQ = `SELECT applied_at IS NOT NULL, applied_schema_version
		FROM "public"."sluice_shard_consolidation_lease"
		WHERE target_table_full_name = $1`
	var (
		applied bool
		version int64
	)
	if err := tgtDB.QueryRowContext(ctx, leaseQ, "public.widgets").Scan(&applied, &version); err != nil {
		t.Fatalf("scan lease row: %v (a missing row is the load-bearing Bug 84 symptom — "+
			"the classifier surfaced the combo refusal before the lease-acquire path could fire)", err)
	}
	if !applied {
		t.Error("lease.applied_at should be set after the routed boundary")
	}
	if version < 1 {
		t.Errorf("lease.applied_schema_version = %d; want >= 1", version)
	}

	// Confirm the gamma row landed with the price.
	var (
		gotName  string
		gotPrice sql.NullString
	)
	if err := tgtDB.QueryRowContext(ctx,
		"SELECT name, price::text FROM widgets WHERE name = 'gamma'").Scan(&gotName, &gotPrice); err != nil {
		t.Fatalf("scan gamma: %v", err)
	}
	if gotName != "gamma" {
		t.Errorf("widgets.name = %q; want gamma", gotName)
	}
	if !gotPrice.Valid || gotPrice.String != "3.75" {
		t.Errorf("widgets.price = %v; want 3.75", gotPrice)
	}

	// Clean shutdown.
	streamCancel()
	select {
	case <-runErr:
	case <-time.After(15 * time.Second):
		t.Fatal("Streamer.Run did not return after ctx cancel")
	}
}
