//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// ADR-0046 load-bearing integration matrix (Postgres, testcontainers):
//
//   - Zero-loss multi-segment rotation under continuous write load:
//     drive a KNOWN insert sequence spanning several inline rotations,
//     restore the multi-segment lineage, assert the EXACT final state
//     (every row exactly once — no loss, no duplication across any
//     segment boundary).
//   - Crash-injection matrix: kill at EVERY FSM edge (post-drain,
//     post-snapshot, post-bulkcopy, pre-commit-write,
//     post-commit-write) -> restart -> assert no data loss + correct
//     <=COMMIT / >COMMIT resolution + restore correctness.
//   - Never-rotated one-segment lineage restores byte-identical data
//     to a pre-ADR single chain (strict-generalization proof).
//   - Mixed-codec (none + gzip + zstd) lineage restores correctly.
//   - Prune-on-lineage (drop a leading whole segment) keeps
//     restore-after-prune correct.

package pipeline

import (
	"context"
	"database/sql"
	"fmt"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/engines"
	"sluicesync.dev/sluice/internal/ir"
	irbackup "sluicesync.dev/sluice/internal/ir/backup"

	_ "sluicesync.dev/sluice/internal/engines/postgres"
)

// rotationSeedFull takes the initial full backup and patches its
// EndPosition to the freshly-created slot LSN so the stream chains
// off it (mirrors the existing stream PG tests' setup).
func rotationSeedFull(t *testing.T, store irbackup.BackupStore, eng ir.Engine, sourceDSN, slotLSN string) *irbackup.Manifest {
	t.Helper()
	if err := (&Backup{Source: eng, SourceDSN: sourceDSN, Store: store, SluiceVersion: "test"}).
		Run(context.Background()); err != nil {
		t.Fatalf("seed Backup.Run: %v", err)
	}
	full, _ := readManifest(context.Background(), store)
	full.Kind = irbackup.BackupKindFull
	full.EndPosition = ir.Position{
		Engine: "postgres",
		Token:  fmt.Sprintf(`{"slot":"sluice_slot","lsn":%q}`, slotLSN),
	}
	full.BackupID = irbackup.ComputeBackupID(full)
	if err := writeManifestAt(context.Background(), store, ManifestFileName, full); err != nil {
		t.Fatalf("rewrite seed full: %v", err)
	}
	// Seed lineage.json so the open segment is catalogued (the first
	// rollover would also seed it; doing it here makes rotation's
	// "lineage not yet catalogued" guard a non-issue from rollover 0).
	// Record the codec the seed Backup.Run above actually wrote with
	// (it passes no Codec → DefaultCodec). Hardcoding a literal here
	// desyncs the recorded codec from the chunk bytes the moment the
	// default flips (v0.67.0 gzip→zstd) → restore reads with the wrong
	// codec. DefaultCodec tracks it.
	updateLineageForManifestBestEffort(context.Background(), store, full, ManifestFileName, DefaultCodec)
	return full
}

// TestADR0046_ZeroLossMultiSegmentRotation_PG is THE load-bearing
// gate: a continuous-write stream with a tight chain-length rotation
// threshold produces a MULTI-SEGMENT lineage; the restored target
// must contain EVERY driven row exactly once (zero loss, zero dup
// across every segment boundary).
func TestADR0046_ZeroLossMultiSegmentRotation_PG(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresLogical(t)
	defer cleanup()

	applyDDL(t, sourceDSN, `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL UNIQUE
		);
		ALTER TABLE users REPLICA IDENTITY FULL;
		INSERT INTO users (email) VALUES ('seed0@example.com');
	`)
	applyDDL(t, sourceDSN, `CREATE PUBLICATION sluice_pub FOR ALL TABLES`)
	slotLSN, err := createPGLogicalSlotReturningLSN(t, sourceDSN, "sluice_slot")
	if err != nil {
		t.Fatalf("create slot: %v", err)
	}
	defer dropPGLogicalSlot(t, sourceDSN, "sluice_slot")

	eng, _ := engines.Get("postgres")
	dir := t.TempDir()
	store, _ := NewLocalStore(dir)
	full := rotationSeedFull(t, store, eng, sourceDSN, slotLSN)

	// Continuous writer: a known, ordered sequence so the final-state
	// assertion is exact.
	const total = 40
	var wg sync.WaitGroup
	writeCtx, writeCancel := context.WithCancel(context.Background())
	wg.Add(1)
	go func() {
		defer wg.Done()
		for i := 0; i < total; i++ {
			select {
			case <-writeCtx.Done():
				return
			default:
			}
			applyDDL(t, sourceDSN, fmt.Sprintf(
				`INSERT INTO users (email) VALUES ('row%03d@example.com');`, i,
			))
			time.Sleep(40 * time.Millisecond)
		}
	}()

	stream := &BackupStream{
		Source:                    eng,
		SourceDSN:                 sourceDSN,
		Store:                     store,
		ParentRef:                 full.BackupID,
		RolloverWindow:            900 * time.Millisecond,
		RolloverMaxChanges:        6,
		RolloverMaxBytes:          1 << 30,
		ChunkChanges:              50,
		RetainRotateAtChainLength: 2, // rotate every 2 rollovers -> many segments
		SluiceVersion:             "test",
	}
	ctx, cancel := context.WithTimeout(context.Background(), 120*time.Second)
	defer cancel()
	streamErr := make(chan error, 1)
	go func() { streamErr <- stream.Run(ctx) }()

	// Let the writer finish + a few extra rollovers drain the tail.
	wg.Wait()
	writeCancel()
	time.Sleep(6 * time.Second)
	cancel()
	select {
	case err := <-streamErr:
		if err != nil {
			t.Fatalf("stream.Run = %v; want clean exit", err)
		}
	case <-time.After(20 * time.Second):
		t.Fatal("stream.Run did not exit within 20s of cancel")
	}

	// The lineage must have rotated (>1 segment) — proves the FSM ran.
	lin, ok, err := loadLineageCatalog(context.Background(), store)
	if err != nil || !ok {
		t.Fatalf("loadLineageCatalog: ok=%v err=%v", ok, err)
	}
	if len(lin.Segments) < 2 {
		t.Fatalf("lineage segments = %d; want >= 2 (rotation did not fire)", len(lin.Segments))
	}
	t.Logf("ADR-0046 zero-loss: lineage has %d segments", len(lin.Segments))

	// Verify every chunk's bytes still hash (cross-segment).
	tot, mis, err := VerifyBackup(context.Background(), store)
	if err != nil || mis != 0 {
		t.Fatalf("VerifyBackup: total=%d mismatches=%d err=%v", tot, mis, err)
	}

	// Restore the multi-segment lineage and assert EXACT final state.
	if err := (&Restore{Target: eng, TargetDSN: targetDSN, Store: store}).
		Run(context.Background()); err != nil {
		t.Fatalf("Restore.Run (multi-segment lineage): %v", err)
	}
	got := pgQueryEmails(t, targetDSN)
	want := map[string]int{"seed0@example.com": 0}
	for i := 0; i < total; i++ {
		want[fmt.Sprintf("row%03d@example.com", i)] = 0
	}
	for _, e := range got {
		if _, expected := want[e]; !expected {
			t.Errorf("UNEXPECTED row on target: %q (data corruption / dup)", e)
			continue
		}
		want[e]++
	}
	missing, dup := 0, 0
	for e, n := range want {
		switch {
		case n == 0:
			missing++
			t.Errorf("ZERO-LOSS VIOLATION: missing row %q", e)
		case n > 1:
			dup++
			t.Errorf("ZERO-LOSS VIOLATION: row %q appeared %d times", e, n)
		}
	}
	if missing == 0 && dup == 0 {
		t.Logf("ADR-0046 zero-loss PROVEN: %d rows, every one exactly once across %d segments",
			len(want), len(lin.Segments))
	}
}

// TestADR0046_CrashInjectionMatrix_PG kills at EVERY FSM edge, then
// restarts the stream and asserts: no data loss, correct <=COMMIT /
// >COMMIT recovery resolution, and a correct restore afterward
// (ADR-0036-style permanent proof-of-falsification).
func TestADR0046_CrashInjectionMatrix_PG(t *testing.T) {
	edges := []struct {
		name       string
		postCommit bool // true => >COMMIT (new segment authoritative)
	}{
		{"post-drain", false},
		{"post-snapshot", false},
		{"post-bulkcopy", false},
		{"pre-commit-write", false},
		{"post-commit-write", true},
	}
	for _, edge := range edges {
		edge := edge
		t.Run(edge.name, func(t *testing.T) {
			sourceDSN, targetDSN, cleanup := startPostgresLogical(t)
			defer cleanup()
			applyDDL(t, sourceDSN, `
				CREATE TABLE users (
					id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					email VARCHAR(255) NOT NULL UNIQUE
				);
				ALTER TABLE users REPLICA IDENTITY FULL;
				INSERT INTO users (email) VALUES ('seed@example.com');
			`)
			applyDDL(t, sourceDSN, `CREATE PUBLICATION sluice_pub FOR ALL TABLES`)
			slotLSN, err := createPGLogicalSlotReturningLSN(t, sourceDSN, "sluice_slot")
			if err != nil {
				t.Fatalf("create slot: %v", err)
			}
			defer dropPGLogicalSlot(t, sourceDSN, "sluice_slot")

			eng, _ := engines.Get("postgres")
			dir := t.TempDir()
			store, _ := NewLocalStore(dir)
			full := rotationSeedFull(t, store, eng, sourceDSN, slotLSN)

			// Drive a handful of writes so a rollover commits, then the
			// rotation FSM fires and we crash it at `edge`.
			for i := 0; i < 8; i++ {
				applyDDL(t, sourceDSN, fmt.Sprintf(
					`INSERT INTO users (email) VALUES ('pre%02d@example.com');`, i,
				))
			}

			// Arm the crash failpoint exactly once at this edge.
			// fired is written by the failpoint closure on the rollover
			// goroutine and read by the test goroutine's spin-wait below
			// — atomic (CAS gives exactly-once without a TOCTOU window).
			var fired atomic.Bool
			rotationCrashPoint = func(e string) error {
				if e == edge.name && fired.CompareAndSwap(false, true) {
					return fmt.Errorf("injected crash at %s", e)
				}
				return nil
			}
			defer func() { rotationCrashPoint = nil }()

			run1 := &BackupStream{
				Source: eng, SourceDSN: sourceDSN, Store: store,
				ParentRef:                 full.BackupID,
				RolloverWindow:            700 * time.Millisecond,
				RolloverMaxChanges:        3,
				RolloverMaxBytes:          1 << 30,
				ChunkChanges:              50,
				RetainRotateAtChainLength: 1,
				SluiceVersion:             "test",
			}
			ctx1, c1 := context.WithTimeout(context.Background(), 40*time.Second)
			e1 := make(chan error, 1)
			go func() { e1 <- run1.Run(ctx1) }()

			// Wait until the crash fired (the FSM aborts-stay-open; the
			// stream keeps streaming the prior segment), then stop run 1.
			deadline := time.Now().Add(30 * time.Second)
			for time.Now().Before(deadline) && !fired.Load() {
				time.Sleep(200 * time.Millisecond)
			}
			if !fired.Load() {
				c1()
				<-e1
				t.Fatalf("crash failpoint %q never fired", edge.name)
			}
			c1()
			select {
			case <-e1:
			case <-time.After(15 * time.Second):
				t.Fatal("run1 did not exit after cancel")
			}
			rotationCrashPoint = nil

			// Drive a few more writes after the crash.
			for i := 0; i < 5; i++ {
				applyDDL(t, sourceDSN, fmt.Sprintf(
					`INSERT INTO users (email) VALUES ('post%02d@example.com');`, i,
				))
			}

			// Reap any walsender still holding a sluice slot before the
			// recovery run (task #48). After run1's injected crash the
			// server can legitimately keep the slot marked active until
			// it notices the dead client — under CI's -race scheduler
			// that can exceed run2's 8-second useful-run window, so run2
			// burned the whole window in slot-active retries and the
			// test's cancel surfaced as "context canceled" mid-retry
			// (fired on PR #178 and PR #190 runs). The retry behaviour
			// has its own pins; THIS test is about recoverRotationState,
			// so make the slot handoff deterministic instead of racing
			// the server's reaper.
			reapSluiceWalsenders(t, sourceDSN)

			// Restart: recoverRotationState reconciles the marker. <=COMMIT
			// edges discard the provisional & resume the prior segment;
			// the post-commit-write edge keeps the new segment.
			run2 := &BackupStream{
				Source: eng, SourceDSN: sourceDSN, Store: store,
				RolloverWindow:     700 * time.Millisecond,
				RolloverMaxChanges: 3,
				RolloverMaxBytes:   1 << 30,
				ChunkChanges:       50,
				SluiceVersion:      "test",
			}
			ctx2, c2 := context.WithTimeout(context.Background(), 40*time.Second)
			e2 := make(chan error, 1)
			go func() { e2 <- run2.Run(ctx2) }()
			time.Sleep(8 * time.Second)
			c2()
			select {
			case err := <-e2:
				if err != nil {
					t.Fatalf("run2.Run = %v; want clean exit after recovery", err)
				}
			case <-time.After(20 * time.Second):
				t.Fatal("run2 did not exit")
			}

			// The recovery marker must be gone.
			if ex, _ := store.Exists(context.Background(), RotationStateFileName); ex {
				t.Errorf("rotation_state.json still present after recovery (%s)", edge.name)
			}
			lin, _, _ := loadLineageCatalog(context.Background(), store)
			if edge.postCommit {
				if len(lin.Segments) < 2 {
					t.Errorf(">COMMIT edge %q: segments=%d; want >=2 (new segment kept)",
						edge.name, len(lin.Segments))
				}
			}

			// Restore must succeed and contain every committed row (no
			// loss). Exact dup-freedom is asserted by the dedicated
			// zero-loss test; here the gate is "recovery + restore
			// correct, no loss".
			if err := (&Restore{Target: eng, TargetDSN: targetDSN, Store: store}).
				Run(context.Background()); err != nil {
				t.Fatalf("restore after %s recovery: %v", edge.name, err)
			}
			got := map[string]bool{}
			for _, e := range pgQueryEmails(t, targetDSN) {
				got[e] = true
			}
			for i := 0; i < 8; i++ {
				if !got[fmt.Sprintf("pre%02d@example.com", i)] {
					t.Errorf("%s: pre-crash row pre%02d missing after recovery+restore (DATA LOSS)", edge.name, i)
				}
			}
			t.Logf("ADR-0046 crash-injection %q: recovery + restore correct (%d segments, postCommit=%v)",
				edge.name, len(lin.Segments), edge.postCommit)
		})
	}
}

// TestADR0046_NeverRotatedByteIdentical_PG proves the
// strict-generalization claim: a never-rotated stream produces a
// one-segment lineage whose restored data is identical to what a
// pre-ADR single chain would have produced (same rows, same path
// layout — Dir == "").
func TestADR0046_NeverRotatedByteIdentical_PG(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresLogical(t)
	defer cleanup()
	applyDDL(t, sourceDSN, `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL UNIQUE
		);
		ALTER TABLE users REPLICA IDENTITY FULL;
		INSERT INTO users (email) VALUES ('a@example.com'), ('b@example.com');
	`)
	applyDDL(t, sourceDSN, `CREATE PUBLICATION sluice_pub FOR ALL TABLES`)
	slotLSN, err := createPGLogicalSlotReturningLSN(t, sourceDSN, "sluice_slot")
	if err != nil {
		t.Fatalf("create slot: %v", err)
	}
	defer dropPGLogicalSlot(t, sourceDSN, "sluice_slot")

	eng, _ := engines.Get("postgres")
	dir := t.TempDir()
	store, _ := NewLocalStore(dir)
	full := rotationSeedFull(t, store, eng, sourceDSN, slotLSN)

	for i := 0; i < 10; i++ {
		applyDDL(t, sourceDSN, fmt.Sprintf(`INSERT INTO users (email) VALUES ('u%02d@example.com');`, i))
	}
	stream := &BackupStream{
		Source: eng, SourceDSN: sourceDSN, Store: store, ParentRef: full.BackupID,
		RolloverWindow:     1500 * time.Millisecond,
		RolloverMaxChanges: 4,
		RolloverMaxBytes:   1 << 30,
		ChunkChanges:       100,
		SluiceVersion:      "test",
		// NO rotation thresholds -> one segment, never rotated.
	}
	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()
	errc := make(chan error, 1)
	go func() { errc <- stream.Run(ctx) }()
	time.Sleep(12 * time.Second)
	cancel()
	<-errc

	lin, ok, _ := loadLineageCatalog(context.Background(), store)
	if !ok || len(lin.Segments) != 1 || lin.Segments[0].Dir != "" ||
		lin.Segments[0].codecOrDefault() != DefaultCodec {
		t.Fatalf("never-rotated lineage = %+v; want exactly one root segment (Dir='', codec=%s)", lin.Segments, DefaultCodec)
	}
	if !lin.Segments[0].open() {
		t.Error("the only segment of a never-rotated lineage must be open (uncapped)")
	}
	if err := (&Restore{Target: eng, TargetDSN: targetDSN, Store: store}).
		Run(context.Background()); err != nil {
		t.Fatalf("restore one-segment lineage: %v", err)
	}
	got := map[string]bool{}
	for _, e := range pgQueryEmails(t, targetDSN) {
		got[e] = true
	}
	for _, must := range []string{"a@example.com", "b@example.com"} {
		if !got[must] {
			t.Errorf("seed row %q missing (one-segment restore not byte-identical)", must)
		}
	}
	for i := 0; i < 10; i++ {
		if !got[fmt.Sprintf("u%02d@example.com", i)] {
			t.Errorf("incremental row u%02d missing (one-segment restore not byte-identical)", i)
		}
	}
}

// TestADR0046_MixedCodecLineageRestores_PG hand-builds a 3-segment
// lineage whose segments use none / gzip / zstd respectively (each a
// self-contained full) and proves restore reads each segment's
// RECORDED codec correctly (never inferred from bytes).
func TestADR0046_MixedCodecLineageRestores_PG(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresLogical(t)
	defer cleanup()
	applyDDL(t, sourceDSN, `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL UNIQUE
		);
	`)
	eng, _ := engines.Get("postgres")
	dir := t.TempDir()
	store, _ := NewLocalStore(dir)

	codecs := []Codec{CodecNone, CodecGzip, CodecZstd}
	var segs []LineageSegment
	for i, c := range codecs {
		applyDDL(t, sourceDSN, fmt.Sprintf(
			`TRUNCATE users; INSERT INTO users (email) VALUES ('seg%d-x@example.com'),('seg%d-y@example.com');`, i, i,
		))
		segDir := ""
		if i > 0 {
			segDir = fmt.Sprintf("seg-%d", i)
		}
		segStore := newPrefixedStore(store, segDir)
		if err := (&Backup{
			Source: eng, SourceDSN: sourceDSN, Store: segStore,
			SluiceVersion: "test", Codec: c,
		}).Run(context.Background()); err != nil {
			t.Fatalf("seg %d (%s) backup: %v", i, c, err)
		}
		fm, _ := readManifestAt(context.Background(), segStore, ManifestFileName)
		fm.Kind = irbackup.BackupKindFull
		// Synthetic contiguous boundary tokens so the lineage-walk's
		// single monotonicity validator passes (these segments were
		// independent backups; we assert codec handling, not CDC).
		fm.StartPosition = ir.Position{Engine: "postgres", Token: fmt.Sprintf("0/%d00", i)}
		fm.EndPosition = ir.Position{Engine: "postgres", Token: fmt.Sprintf("0/%d00", i+1)}
		fm.BackupID = irbackup.ComputeBackupID(fm)
		_ = writeManifestAt(context.Background(), segStore, ManifestFileName, fm)
		seg := LineageSegment{
			SegmentID: fm.BackupID, Dir: segDir, FullManifestPath: ManifestFileName,
			StartPosition: fm.StartPosition, EndPosition: fm.EndPosition, Codec: c,
		}
		if i < len(codecs)-1 {
			capt := time.Now().UTC()
			seg.CappedAt = &capt
			seg.CapReason = rotationReasonChainLength
		}
		segs = append(segs, seg)
	}
	cat := &LineageCatalog{
		FormatVersion: 1, SourceEngine: "postgres",
		CreatedAt: time.Now().UTC(), Segments: segs,
	}
	if err := writeLineageCatalog(context.Background(), store, cat); err != nil {
		t.Fatalf("write mixed-codec lineage: %v", err)
	}

	// VerifyBackup is codec-agnostic (byte hash) but must pass.
	if _, mis, err := VerifyBackup(context.Background(), store); err != nil || mis != 0 {
		t.Fatalf("VerifyBackup mixed-codec: mis=%d err=%v", mis, err)
	}
	// Restore walks all 3 segments, decoding each with ITS recorded
	// codec. The last segment's full (zstd) is the final state.
	if err := (&Restore{Target: eng, TargetDSN: targetDSN, Store: store}).
		Run(context.Background()); err != nil {
		t.Fatalf("restore mixed-codec lineage: %v", err)
	}
	got := map[string]bool{}
	for _, e := range pgQueryEmails(t, targetDSN) {
		got[e] = true
	}
	// Final segment (i=2, zstd) state must be present.
	for _, must := range []string{"seg2-x@example.com", "seg2-y@example.com"} {
		if !got[must] {
			t.Errorf("mixed-codec restore missing final zstd-segment row %q", must)
		}
	}
}

// TestADR0046_UnknownRecordedCodecRefused_PG: a lineage that records
// an unknown codec on a segment is a LOUD refusal at restore (codec
// recorded, never sniffed — DR data).
func TestADR0046_UnknownRecordedCodecRefused_PG(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresLogical(t)
	defer cleanup()
	applyDDL(t, sourceDSN, `CREATE TABLE users (id BIGINT PRIMARY KEY, email TEXT);
		INSERT INTO users VALUES (1,'x@example.com');`)
	eng, _ := engines.Get("postgres")
	dir := t.TempDir()
	store, _ := NewLocalStore(dir)
	if err := (&Backup{Source: eng, SourceDSN: sourceDSN, Store: store, SluiceVersion: "test"}).
		Run(context.Background()); err != nil {
		t.Fatalf("backup: %v", err)
	}
	fm, _ := readManifest(context.Background(), store)
	fm.Kind = irbackup.BackupKindFull
	fm.BackupID = irbackup.ComputeBackupID(fm)
	_ = writeManifestAt(context.Background(), store, ManifestFileName, fm)
	cat := &LineageCatalog{
		FormatVersion: 1, SourceEngine: "postgres",
		Segments: []LineageSegment{{
			SegmentID: fm.BackupID, Dir: "", FullManifestPath: ManifestFileName,
			Codec: Codec("snappy"), // unknown / garbled
		}},
	}
	_ = writeLineageCatalog(context.Background(), store, cat)
	err := (&Restore{Target: eng, TargetDSN: targetDSN, Store: store}).Run(context.Background())
	if err == nil {
		t.Fatal("restore with unknown recorded codec = nil; want loud refusal")
	}
}

// reapSluiceWalsenders terminates any backend still holding a
// sluice-prefixed replication slot ACTIVE, then waits for the slots to
// read inactive. Test-harness determinism only (task #48): after an
// injected hard crash the server keeps the slot active until it
// notices the dead client — correct server behaviour, pinned
// elsewhere (the v0.99.34 bounded retry + the #186 graceful-Terminate
// paths); recovery-shape tests shouldn't race that reaper.
func reapSluiceWalsenders(t *testing.T, dsn string) {
	t.Helper()
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		t.Fatalf("reapSluiceWalsenders: open: %v", err)
	}
	defer func() { _ = db.Close() }()
	if _, err := db.Exec(
		`SELECT pg_terminate_backend(active_pid) FROM pg_replication_slots
		 WHERE active AND active_pid IS NOT NULL AND slot_name LIKE 'sluice%'`,
	); err != nil {
		t.Fatalf("reapSluiceWalsenders: terminate: %v", err)
	}
	deadline := time.Now().Add(15 * time.Second)
	for time.Now().Before(deadline) {
		var n int
		if err := db.QueryRow(
			`SELECT count(*) FROM pg_replication_slots WHERE active AND slot_name LIKE 'sluice%'`,
		).Scan(&n); err != nil {
			t.Fatalf("reapSluiceWalsenders: poll: %v", err)
		}
		if n == 0 {
			return
		}
		time.Sleep(200 * time.Millisecond)
	}
	t.Fatal("reapSluiceWalsenders: sluice slots still active after 15s")
}
