//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// Roadmap item 98, against a real Postgres source: the real-wire half of
// the pin in stream_rollover_bound_replay_test.go.
//
// The unit pins SCRIPT the replay; this one PROVOKES it. It chains three
// stream runs so each resumes at a position PostgreSQL itself produced (a
// commit LSN), which is the only way to exercise the actual walsender
// behaviour behind the bug: logical decoding restarts at
// max(requested_lsn, confirmed_flush_lsn) and skips only transactions
// committing STRICTLY BEFORE that point, so the transaction the previous
// run ended on is re-delivered in full. Nothing in sluice can be mocked
// into that; it has to come off the wire.
//
// Each run is stopped after exactly ONE committed rollover — via the
// ADR-0156 readout hook, which the rollover loop calls at the top of every
// iteration, before its stop-request check. That is what makes this a DATA
// pin rather than a position pin: a stream left running would pick the
// missed delta up on its next rollover, so the cost of the defect only
// becomes visible in the chain when the stream stops on the replay-only
// rollover — which is exactly what a short-lived or promptly-stopped
// `backup stream` does.

package pipeline

import (
	"context"
	"fmt"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/engines"
	"sluicesync.dev/sluice/internal/ir"
	irbackup "sluicesync.dev/sluice/internal/ir/backup"
	"sluicesync.dev/sluice/internal/pipeline/backup"
	"sluicesync.dev/sluice/internal/pipeline/blobcodec"
	"sluicesync.dev/sluice/internal/pipeline/lineage"
	"sluicesync.dev/sluice/internal/progress"

	_ "sluicesync.dev/sluice/internal/engines/postgres"
)

// TestBackupStream_PostgresRolloverCapsOutrunTheReplay is the item-98
// gate. A tightly-capped rollover on a RESUMED stream must not close on
// the boundary transaction its own resume replays: its EndPosition has to
// move past its StartPosition, and a chain restore has to carry every row
// committed after the parent. Both caps are exercised — they count what
// the replay carries and share the window-closing decision, so a green
// pin on one is not evidence for the other.
func TestBackupStream_PostgresRolloverCapsOutrunTheReplay(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresLogical(t)
	defer cleanup()

	applyDDL(t, sourceDSN, `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL
		);
		ALTER TABLE users REPLICA IDENTITY FULL;
		INSERT INTO users (email) VALUES ('alice@example.com');
	`)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}
	store, err := blobcodec.NewLocalStore(t.TempDir())
	if err != nil {
		t.Fatalf("NewLocalStore: %v", err)
	}

	applyDDL(t, sourceDSN, `CREATE PUBLICATION sluice_pub FOR ALL TABLES`)
	slotLSN, err := createPGLogicalSlotReturningLSN(t, sourceDSN, "sluice_slot")
	if err != nil {
		t.Fatalf("create slot: %v", err)
	}
	defer dropPGLogicalSlot(t, sourceDSN, "sluice_slot")

	ctx := context.Background()
	if err := (&backup.Backup{
		Source: pgEng, SourceDSN: sourceDSN, Store: store, SluiceVersion: "test",
	}).Run(ctx); err != nil {
		t.Fatalf("Backup.Run: %v", err)
	}
	full, err := lineage.ReadManifest(ctx, store)
	if err != nil {
		t.Fatalf("ReadManifest: %v", err)
	}
	full.Kind = irbackup.BackupKindFull
	full.EndPosition = ir.Position{
		Engine: "postgres",
		Token:  fmt.Sprintf(`{"slot":"sluice_slot","lsn":%q}`, slotLSN),
	}
	full.BackupID = irbackup.ComputeBackupID(full)
	if err := lineage.WriteManifestAt(ctx, store, lineage.ManifestFileName, full); err != nil {
		t.Fatalf("rewrite full manifest: %v", err)
	}

	// Link 1: a TIME-bounded run over one committed transaction. Its
	// EndPosition is bob's commit LSN — the position link 2 resumes at,
	// and therefore the transaction PostgreSQL will replay to it.
	applyDDL(t, sourceDSN, `INSERT INTO users (email) VALUES ('bob@example.com');`)
	link1 := runItem98StreamLink(t, pgEng, sourceDSN, store, full.BackupID, &BackupStream{
		RolloverWindow:     3 * time.Second,
		RolloverMaxChanges: 1_000_000,
		RolloverMaxBytes:   1 << 30,
		ChunkChanges:       100,
	})
	if len(link1.ChangeChunks) == 0 {
		t.Fatalf("link 1 captured no changes; the fixture cannot provoke a replay (end=%s)", link1.EndPosition.Token)
	}

	// Link 2 resumes at bob's commit LSN with a change cap (2) the
	// replayed bob transaction satisfies all by itself.
	applyDDL(t, sourceDSN, `INSERT INTO users (email) VALUES ('carol@example.com');`)
	link2 := runItem98StreamLink(t, pgEng, sourceDSN, store, link1.BackupID, &BackupStream{
		RolloverWindow:     30 * time.Second,
		RolloverMaxChanges: 2,
		RolloverMaxBytes:   1 << 30,
		ChunkChanges:       100,
	})
	assertItem98LinkAdvanced(t, pgEng, "link 2 (--rollover-max-changes)", link1, link2)

	// Link 3 does the same for the BYTE cap: a 1-byte ceiling that the
	// replayed carol transaction's own flushed chunk satisfies. The small
	// ChunkChanges is load-bearing — the ceiling is only re-evaluated
	// when a chunk flushes (the codec buffers until close).
	applyDDL(t, sourceDSN, `INSERT INTO users (email) VALUES ('dave@example.com');`)
	link3 := runItem98StreamLink(t, pgEng, sourceDSN, store, link2.BackupID, &BackupStream{
		RolloverWindow:     30 * time.Second,
		RolloverMaxChanges: 1_000_000,
		RolloverMaxBytes:   1,
		ChunkChanges:       2,
	})
	assertItem98LinkAdvanced(t, pgEng, "link 3 (--rollover-max-bytes)", link2, link3)

	// The load-bearing assertion: restore the chain and count the rows.
	// Pre-fix, a link that closed on its own replay carries none of the
	// delta committed after its parent, and the chain stops there.
	if err := (&backup.Restore{Target: pgEng, TargetDSN: targetDSN, Store: store}).Run(ctx); err != nil {
		t.Fatalf("Restore.Run: %v", err)
	}
	got := map[string]bool{}
	for _, e := range pgQueryEmails(t, targetDSN) {
		got[e] = true
	}
	for _, want := range []string{"alice@example.com", "bob@example.com", "carol@example.com", "dave@example.com"} {
		if !got[want] {
			t.Errorf("restored target is missing %q (has: %v) — a rollover closed on the transaction its resume replayed, so its segment carries nothing new (roadmap item 98)", want, got)
		}
	}
}

// assertItem98LinkAdvanced checks one resumed link: it must start exactly
// where its parent ended (so the replay is genuinely provoked) and must
// end strictly after that, in PostgreSQL's own LSN order.
func assertItem98LinkAdvanced(t *testing.T, eng ir.Engine, label string, parent, link *irbackup.Manifest) {
	t.Helper()
	if link.StartPosition != parent.EndPosition {
		t.Fatalf("%s StartPosition = %s; want the parent's EndPosition %s",
			label, link.StartPosition.Token, parent.EndPosition.Token)
	}
	if link.EndPosition == link.StartPosition {
		t.Errorf("%s EndPosition == StartPosition (%s) — the cap closed the rollover on the replayed boundary transaction, so the segment carries none of the delta (roadmap item 98)",
			label, link.EndPosition.Token)
	}
	after, err := eng.(ir.PositionMonotonicChecker).PrecedesOrEqual(link.StartPosition, link.EndPosition)
	if err != nil {
		t.Fatalf("%s PrecedesOrEqual: %v", label, err)
	}
	if !after {
		t.Errorf("%s EndPosition %s is not at-or-after its StartPosition %s",
			label, link.EndPosition.Token, link.StartPosition.Token)
	}
}

// runItem98StreamLink runs one `backup stream` against the live source,
// stops it after exactly ONE committed rollover, and returns that
// rollover's manifest. tmpl carries only the bound knobs under test.
//
// The stop rides the ADR-0156 readout hook: Run calls it at the top of
// every loop iteration with the lifetime rollover count, BEFORE the
// iteration's stop-request check, so requesting the stop from the hook the
// first time that count is non-zero ends the run before a second rollover
// can open. Same goroutine as the loop, so there is no race to lose.
func runItem98StreamLink(t *testing.T, eng ir.Engine, sourceDSN string, store irbackup.Store, parentID string, tmpl *BackupStream) *irbackup.Manifest {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 180*time.Second)
	defer cancel()

	before, err := lineage.ListAllManifestsViaWalk(ctx, store)
	if err != nil {
		t.Fatalf("list manifests (before): %v", err)
	}
	seen := map[string]bool{}
	for _, r := range before {
		seen[r.Path] = true
	}

	stream := *tmpl
	stream.Source = eng
	stream.SourceDSN = sourceDSN
	stream.Store = store
	stream.ParentRef = parentID
	stream.SluiceVersion = "test"
	stream.Readout = func(fields []progress.Field) {
		for _, f := range fields {
			if f.Label != "incrementals" || f.Value == "0" {
				continue
			}
			if _, sErr := RequestStreamStop(ctx, store, time.Now()); sErr != nil {
				t.Errorf("RequestStreamStop: %v", sErr)
			}
		}
	}
	if err := stream.Run(ctx); err != nil {
		t.Fatalf("BackupStream.Run: %v", err)
	}

	after, err := lineage.ListAllManifestsViaWalk(ctx, store)
	if err != nil {
		t.Fatalf("list manifests (after): %v", err)
	}
	var got *irbackup.Manifest
	for _, r := range after {
		if seen[r.Path] || r.Manifest.Kind != irbackup.BackupKindIncremental {
			continue
		}
		if got != nil {
			t.Fatalf("the run committed more than one rollover (%s and %s); the readout stop did not hold, so this is no longer a data pin",
				got.BackupID, r.Manifest.BackupID)
		}
		got = r.Manifest
	}
	if got == nil {
		t.Fatal("no new incremental manifest after the stream run")
	}
	return got
}
