//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// Integration tests for Phase 4 — long-running backup stream — against
// a real Postgres testcontainer. Mirrors the shape of the Phase 3.1
// incremental tests in incremental_pg_integration_test.go.
//
// Acceptance criteria covered (per design/logical-backups-phase-4.md):
//
//   1. PG long-running stream produces rolling incrementals.
//   3. Time-bound rollover triggers (quiet source + small window).
//   4. Size-bound rollover triggers (drive N inserts → expected count).
//   5. Restore from stream-written chain works (chain-walker
//      transparently handles stream-written chains).
//   6. SIGTERM clean exit (modeled via ctx.Cancel mid-stream).
//   7. backup stream stop cross-machine (write stop_requested_at from
//      a separate goroutine; stream observes and exits).
//   8. Concurrent-writer protection refuses second stream.

package pipeline

import (
	"context"
	"fmt"
	"strings"
	"sync"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/engines"
	"sluicesync.dev/sluice/internal/ir"
	irbackup "sluicesync.dev/sluice/internal/ir/backup"
	"sluicesync.dev/sluice/internal/pipeline/backup"
	"sluicesync.dev/sluice/internal/pipeline/blobcodec"
	"sluicesync.dev/sluice/internal/pipeline/lineage"

	_ "sluicesync.dev/sluice/internal/engines/postgres"
)

// TestBackupStream_Postgres_RolloverByMaxChanges is the load-bearing
// happy-path test: drive ~25 inserts under a stream with
// --rollover-max-changes=10, observe 3 rollovers, restore the chain
// into a fresh target, verify every row arrives.
//
// Acceptance criteria 1, 4, 5.
func TestBackupStream_Postgres_RolloverByMaxChanges(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresLogical(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL
		);
		ALTER TABLE users REPLICA IDENTITY FULL;
		INSERT INTO users (email) VALUES ('alice@example.com'), ('bob@example.com');
	`
	applyDDL(t, sourceDSN, seedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	dir := t.TempDir()
	store, err := blobcodec.NewLocalStore(dir)
	if err != nil {
		t.Fatalf("NewLocalStore: %v", err)
	}

	applyDDL(t, sourceDSN, `CREATE PUBLICATION sluice_pub FOR ALL TABLES`)
	slotLSN, err := createPGLogicalSlotReturningLSN(t, sourceDSN, "sluice_slot")
	if err != nil {
		t.Fatalf("create slot: %v", err)
	}
	defer dropPGLogicalSlot(t, sourceDSN, "sluice_slot")

	// Full backup (parent for the stream chain).
	if err := (&backup.Backup{
		Source: pgEng, SourceDSN: sourceDSN, Store: store, SluiceVersion: "test",
	}).Run(context.Background()); err != nil {
		t.Fatalf("Backup.Run: %v", err)
	}
	full, _ := lineage.ReadManifest(context.Background(), store)
	full.Kind = irbackup.BackupKindFull
	full.EndPosition = ir.Position{
		Engine: "postgres",
		Token:  fmt.Sprintf(`{"slot":"sluice_slot","lsn":%q}`, slotLSN),
	}
	full.BackupID = irbackup.ComputeBackupID(full)
	if err := lineage.WriteManifestAt(context.Background(), store, lineage.ManifestFileName, full); err != nil {
		t.Fatalf("rewrite full: %v", err)
	}

	// Drive 25 inserts on the source AFTER the slot is created, so
	// they're retained in WAL and visible to the stream.
	for i := 0; i < 25; i++ {
		applyDDL(t, sourceDSN, fmt.Sprintf(
			`INSERT INTO users (email) VALUES ('user%d@example.com');`, i,
		))
	}

	// Run the stream with small bounds so it commits multiple
	// rollovers quickly. The CDC pump's channel will close once we
	// cancel ctx after observing enough rollovers.
	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()

	stream := &BackupStream{
		Source:             pgEng,
		SourceDSN:          sourceDSN,
		Store:              store,
		ParentRef:          full.BackupID,
		RolloverWindow:     2 * time.Second,
		RolloverMaxChanges: 10,
		RolloverMaxBytes:   1 << 30,
		ChunkChanges:       100,
		SluiceVersion:      "test",
	}

	streamErr := make(chan error, 1)
	go func() { streamErr <- stream.Run(ctx) }()

	// Watch for rollovers; cancel once we have at least 2 AND the
	// rollover throughput has settled (no new manifest in ~3s, which
	// is > rollover-window so an idle final rollover would have
	// committed or timed out empty before we cancel). Polling on
	// count alone (the pre-v0.20.1 shape) cancels too eagerly when
	// each rollover takes ~30-250ms (Bug 38 fix's per-rollover schema
	// refresh) — by the time 2 incrementals appear on disk, the
	// cancel races with the in-flight rollover that contains the
	// trailing inserts.
	deadline := time.Now().Add(45 * time.Second)
	var lastCount, stableTicks int
	for time.Now().Before(deadline) {
		records, _ := lineage.ListAllManifestsViaWalk(context.Background(), store)
		var incrCount int
		for _, r := range records {
			if r.Manifest.Kind == irbackup.BackupKindIncremental {
				incrCount++
			}
		}
		if incrCount == lastCount {
			stableTicks++
		} else {
			stableTicks = 0
			lastCount = incrCount
		}
		if incrCount >= 2 && stableTicks >= 6 {
			break
		}
		time.Sleep(500 * time.Millisecond)
	}
	cancel()

	select {
	case err := <-streamErr:
		if err != nil {
			t.Errorf("stream.Run after cancel = %v; want nil (clean exit)", err)
		}
	case <-time.After(10 * time.Second):
		t.Fatal("stream.Run did not exit within 10s of ctx.Cancel")
	}

	// Inspect manifests; expect at least 2 incrementals.
	records, _ := lineage.ListAllManifestsViaWalk(context.Background(), store)
	var incrementals []*irbackup.Manifest
	for _, r := range records {
		if r.Manifest.Kind == irbackup.BackupKindIncremental {
			incrementals = append(incrementals, r.Manifest)
		}
	}
	if len(incrementals) < 2 {
		t.Fatalf("incremental rollovers = %d; want >= 2", len(incrementals))
	}

	// Verify chain (every chunk's hash matches what's on disk).
	total, mismatches, err := backup.VerifyBackup(context.Background(), store)
	if err != nil {
		t.Fatalf("VerifyBackup: %v", err)
	}
	if mismatches != 0 {
		t.Errorf("VerifyBackup: %d of %d chunks failed", mismatches, total)
	}

	// Chain restore into the fresh target.
	if err := (&backup.Restore{
		Target: pgEng, TargetDSN: targetDSN, Store: store,
	}).Run(context.Background()); err != nil {
		t.Fatalf("Restore.Run: %v", err)
	}

	// Verify every email is on the target.
	got := pgQueryEmails(t, targetDSN)
	want := map[string]bool{
		"alice@example.com": true,
		"bob@example.com":   true,
	}
	for i := 0; i < 25; i++ {
		want[fmt.Sprintf("user%d@example.com", i)] = true
	}
	gotMap := map[string]bool{}
	for _, e := range got {
		gotMap[e] = true
	}
	for w := range want {
		if !gotMap[w] {
			t.Errorf("target missing email %q (got count: %d)", w, len(got))
		}
	}
}

// TestBackupStream_Postgres_StopCommandRequestsExit drives the
// cross-machine stop path: start a stream, write stop_requested_at
// from a separate goroutine, verify the stream exits cleanly within
// the rollover-window envelope.
//
// Acceptance criterion 7.
//
// Bug 37 (v0.19.1) closed: in-process stop channel + heartbeat
// merge-helper makes this test pass reliably on CI under -race; the
// v0.19.0 skip-on-CI guard is gone. Local: ~6s; CI: comparable.
func TestBackupStream_Postgres_StopCommandRequestsExit(t *testing.T) {
	sourceDSN, _, cleanup := startPostgresLogical(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL
		);
		ALTER TABLE users REPLICA IDENTITY FULL;
		INSERT INTO users (email) VALUES ('alice@example.com');
	`
	applyDDL(t, sourceDSN, seedDDL)

	pgEng, _ := engines.Get("postgres")
	dir := t.TempDir()
	store, _ := blobcodec.NewLocalStore(dir)

	applyDDL(t, sourceDSN, `CREATE PUBLICATION sluice_pub FOR ALL TABLES`)
	slotLSN, err := createPGLogicalSlotReturningLSN(t, sourceDSN, "sluice_slot")
	if err != nil {
		t.Fatalf("create slot: %v", err)
	}
	defer dropPGLogicalSlot(t, sourceDSN, "sluice_slot")

	if err := (&backup.Backup{
		Source: pgEng, SourceDSN: sourceDSN, Store: store, SluiceVersion: "test",
	}).Run(context.Background()); err != nil {
		t.Fatalf("Backup.Run: %v", err)
	}
	full, _ := lineage.ReadManifest(context.Background(), store)
	full.Kind = irbackup.BackupKindFull
	full.EndPosition = ir.Position{
		Engine: "postgres",
		Token:  fmt.Sprintf(`{"slot":"sluice_slot","lsn":%q}`, slotLSN),
	}
	full.BackupID = irbackup.ComputeBackupID(full)
	_ = lineage.WriteManifestAt(context.Background(), store, lineage.ManifestFileName, full)

	stream := &BackupStream{
		Source:                pgEng,
		SourceDSN:             sourceDSN,
		Store:                 store,
		ParentRef:             full.BackupID,
		RolloverWindow:        2 * time.Second,
		RolloverMaxChanges:    1_000_000,
		RolloverMaxBytes:      1 << 30,
		IncludeEmptyRollovers: true, // commit heartbeats so stop_requested_at is observed quickly
		SluiceVersion:         "test",
	}

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	streamErr := make(chan error, 1)
	go func() { streamErr <- stream.Run(ctx) }()

	// Wait for the first rollover so stream_state.json exists, then
	// write stop_requested_at from a separate goroutine.
	time.Sleep(4 * time.Second)
	if _, err := RequestStreamStop(context.Background(), store, time.Now()); err != nil {
		t.Fatalf("RequestStreamStop: %v", err)
	}

	select {
	case err := <-streamErr:
		if err != nil {
			t.Errorf("stream.Run after stop = %v; want nil (clean exit)", err)
		}
	case <-time.After(60 * time.Second):
		t.Fatal("stream.Run did not exit within 60s of stop request")
	}
}

// TestBackupStream_Postgres_ConcurrentWriterRefused exercises the
// concurrent-writer protection: start one stream, attempt a second
// without --force, verify the second refuses.
//
// Acceptance criterion 8.
func TestBackupStream_Postgres_ConcurrentWriterRefused(t *testing.T) {
	sourceDSN, _, cleanup := startPostgresLogical(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL
		);
		ALTER TABLE users REPLICA IDENTITY FULL;
		INSERT INTO users (email) VALUES ('alice@example.com');
	`
	applyDDL(t, sourceDSN, seedDDL)

	pgEng, _ := engines.Get("postgres")
	dir := t.TempDir()
	store, _ := blobcodec.NewLocalStore(dir)

	applyDDL(t, sourceDSN, `CREATE PUBLICATION sluice_pub FOR ALL TABLES`)
	slotLSN, err := createPGLogicalSlotReturningLSN(t, sourceDSN, "sluice_slot")
	if err != nil {
		t.Fatalf("create slot: %v", err)
	}
	defer dropPGLogicalSlot(t, sourceDSN, "sluice_slot")

	if err := (&backup.Backup{
		Source: pgEng, SourceDSN: sourceDSN, Store: store, SluiceVersion: "test",
	}).Run(context.Background()); err != nil {
		t.Fatalf("Backup.Run: %v", err)
	}
	full, _ := lineage.ReadManifest(context.Background(), store)
	full.Kind = irbackup.BackupKindFull
	full.EndPosition = ir.Position{
		Engine: "postgres",
		Token:  fmt.Sprintf(`{"slot":"sluice_slot","lsn":%q}`, slotLSN),
	}
	full.BackupID = irbackup.ComputeBackupID(full)
	_ = lineage.WriteManifestAt(context.Background(), store, lineage.ManifestFileName, full)

	// Pre-seed a fresh stream_state.json mimicking another running
	// stream on a different host. This is what a real second-process
	// would race against.
	now := time.Now().UTC()
	preexisting := &streamState{
		PID: 99999, Host: "other.example.com",
		StartedAt:      now.Add(-10 * time.Second),
		LastRolloverAt: now.Add(-1 * time.Second), // very fresh
	}
	if err := writeStreamState(context.Background(), store, DefaultStreamStateFilename, preexisting); err != nil {
		t.Fatalf("seed stream_state: %v", err)
	}

	stream := &BackupStream{
		Source:             pgEng,
		SourceDSN:          sourceDSN,
		Store:              store,
		ParentRef:          full.BackupID,
		RolloverWindow:     time.Minute, // recent threshold = 2 min
		RolloverMaxChanges: 100,
		SluiceVersion:      "test",
	}

	err = stream.Run(context.Background())
	if err == nil {
		t.Fatal("err = nil; want concurrent-writer refusal")
	}
	if !strings.Contains(err.Error(), "stream is already running") {
		t.Errorf("err = %v; want concurrent-writer guidance", err)
	}

	// With --force, the second stream should accept the takeover.
	stream.Force = true
	ctx, cancel := context.WithCancel(context.Background())
	streamErr := make(chan error, 1)
	go func() { streamErr <- stream.Run(ctx) }()

	// Let it tick at least once.
	time.Sleep(3 * time.Second)
	cancel()

	select {
	case err := <-streamErr:
		if err != nil {
			t.Errorf("stream.Run with --force after cancel = %v; want nil", err)
		}
	case <-time.After(10 * time.Second):
		t.Fatal("stream.Run did not exit within 10s")
	}

	// Verify the state file now reflects our pid (not the pre-seeded
	// 99999), which proves we took over.
	got, err := readStreamState(context.Background(), store, DefaultStreamStateFilename)
	if err != nil {
		t.Fatalf("readStreamState: %v", err)
	}
	if got.PID == 99999 {
		t.Errorf("state file pid = 99999; expected our process's pid (takeover did not write fresh state)")
	}
}

// TestBackupStream_Postgres_QuietSourceTimeBoundRollover verifies the
// time-bound rollover path on a quiet source: with no INSERTs, the
// stream produces empty rollovers (heartbeats) at the configured
// cadence.
//
// Acceptance criterion 3.
func TestBackupStream_Postgres_QuietSourceTimeBoundRollover(t *testing.T) {
	sourceDSN, _, cleanup := startPostgresLogical(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL
		);
		ALTER TABLE users REPLICA IDENTITY FULL;
		INSERT INTO users (email) VALUES ('alice@example.com');
	`
	applyDDL(t, sourceDSN, seedDDL)

	pgEng, _ := engines.Get("postgres")
	dir := t.TempDir()
	store, _ := blobcodec.NewLocalStore(dir)

	applyDDL(t, sourceDSN, `CREATE PUBLICATION sluice_pub FOR ALL TABLES`)
	slotLSN, err := createPGLogicalSlotReturningLSN(t, sourceDSN, "sluice_slot")
	if err != nil {
		t.Fatalf("create slot: %v", err)
	}
	defer dropPGLogicalSlot(t, sourceDSN, "sluice_slot")

	if err := (&backup.Backup{
		Source: pgEng, SourceDSN: sourceDSN, Store: store, SluiceVersion: "test",
	}).Run(context.Background()); err != nil {
		t.Fatalf("Backup.Run: %v", err)
	}
	full, _ := lineage.ReadManifest(context.Background(), store)
	full.Kind = irbackup.BackupKindFull
	full.EndPosition = ir.Position{
		Engine: "postgres",
		Token:  fmt.Sprintf(`{"slot":"sluice_slot","lsn":%q}`, slotLSN),
	}
	full.BackupID = irbackup.ComputeBackupID(full)
	_ = lineage.WriteManifestAt(context.Background(), store, lineage.ManifestFileName, full)

	stream := &BackupStream{
		Source:                pgEng,
		SourceDSN:             sourceDSN,
		Store:                 store,
		ParentRef:             full.BackupID,
		RolloverWindow:        2 * time.Second,
		RolloverMaxChanges:    1_000_000,
		RolloverMaxBytes:      1 << 30,
		IncludeEmptyRollovers: true, // commit empty heartbeat manifests
		SluiceVersion:         "test",
	}

	ctx, cancel := context.WithTimeout(context.Background(), 12*time.Second)
	defer cancel()

	streamErr := make(chan error, 1)
	go func() { streamErr <- stream.Run(ctx) }()

	// Wait ~7 s; expect at least 2 empty heartbeat rollovers.
	time.Sleep(7 * time.Second)
	cancel()

	select {
	case <-streamErr:
	case <-time.After(10 * time.Second):
		t.Fatal("stream.Run did not exit within 10s of ctx.Cancel")
	}

	records, _ := lineage.ListAllManifestsViaWalk(context.Background(), store)
	var emptyRollovers int
	for _, r := range records {
		if r.Manifest.Kind == irbackup.BackupKindIncremental && len(r.Manifest.ChangeChunks) == 0 {
			emptyRollovers++
		}
	}
	if emptyRollovers < 2 {
		t.Errorf("empty heartbeat rollovers = %d; want >= 2 (window=2s, ran ~7s)", emptyRollovers)
	}
}

// TestBackupStream_Postgres_SignalDrainExitsClean drives the SIGTERM-
// shape path: cancel ctx in the middle of an active stream, verify
// Run returns nil within stopDrainTimeout (clean drain).
//
// Acceptance criterion 6.
func TestBackupStream_Postgres_SignalDrainExitsClean(t *testing.T) {
	sourceDSN, _, cleanup := startPostgresLogical(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL
		);
		ALTER TABLE users REPLICA IDENTITY FULL;
		INSERT INTO users (email) VALUES ('alice@example.com');
	`
	applyDDL(t, sourceDSN, seedDDL)

	pgEng, _ := engines.Get("postgres")
	dir := t.TempDir()
	store, _ := blobcodec.NewLocalStore(dir)

	applyDDL(t, sourceDSN, `CREATE PUBLICATION sluice_pub FOR ALL TABLES`)
	slotLSN, err := createPGLogicalSlotReturningLSN(t, sourceDSN, "sluice_slot")
	if err != nil {
		t.Fatalf("create slot: %v", err)
	}
	defer dropPGLogicalSlot(t, sourceDSN, "sluice_slot")

	if err := (&backup.Backup{
		Source: pgEng, SourceDSN: sourceDSN, Store: store, SluiceVersion: "test",
	}).Run(context.Background()); err != nil {
		t.Fatalf("Backup.Run: %v", err)
	}
	full, _ := lineage.ReadManifest(context.Background(), store)
	full.Kind = irbackup.BackupKindFull
	full.EndPosition = ir.Position{
		Engine: "postgres",
		Token:  fmt.Sprintf(`{"slot":"sluice_slot","lsn":%q}`, slotLSN),
	}
	full.BackupID = irbackup.ComputeBackupID(full)
	_ = lineage.WriteManifestAt(context.Background(), store, lineage.ManifestFileName, full)

	// Drive concurrent inserts so the stream is mid-rollover when ctx
	// fires.
	var wg sync.WaitGroup
	insertCtx, insertCancel := context.WithCancel(context.Background())
	defer insertCancel()
	wg.Add(1)
	go func() {
		defer wg.Done()
		i := 0
		for {
			select {
			case <-insertCtx.Done():
				return
			default:
			}
			applyDDL(t, sourceDSN, fmt.Sprintf(
				`INSERT INTO users (email) VALUES ('streaming%d@example.com');`, i,
			))
			i++
			time.Sleep(50 * time.Millisecond)
		}
	}()

	stream := &BackupStream{
		Source:             pgEng,
		SourceDSN:          sourceDSN,
		Store:              store,
		ParentRef:          full.BackupID,
		RolloverWindow:     5 * time.Second,
		RolloverMaxChanges: 1_000_000,
		RolloverMaxBytes:   1 << 30,
		SluiceVersion:      "test",
	}

	ctx, cancel := context.WithCancel(context.Background())
	streamErr := make(chan error, 1)
	go func() { streamErr <- stream.Run(ctx) }()

	// Let the stream observe some inserts, then cancel.
	time.Sleep(2 * time.Second)
	cancel()

	insertCancel()
	wg.Wait()

	select {
	case err := <-streamErr:
		if err != nil {
			t.Errorf("stream.Run after ctx.Cancel = %v; want nil (clean exit)", err)
		}
	case <-time.After(15 * time.Second):
		t.Fatal("stream.Run did not exit within 15s of ctx.Cancel")
	}
}
