//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// Integration test for Bug 13 (publication-scope-by-table, ADR-0021).
//
// The pre-fix shape: sluice's CDC reader created `sluice_pub` with
// FOR ALL TABLES. Any new table on the source mid-stream became
// part of the WAL stream automatically; the applier saw events
// for an unknown-on-target table and crashed with "table public.X
// has no columns (does it exist?)".
//
// The fix: scope the publication to the table list the streamer
// reads from the source schema (CREATE PUBLICATION sluice_pub
// FOR TABLE …). New tables on the source stay out of the stream.
// As defence in depth, the applier skips events targeting a
// missing table with a WARN line rather than aborting the stream.
//
// This test runs the canonical scenario: cold-start with N
// tables, mid-stream CREATE TABLE on the source, sustained writes
// to the new table — the original tables continue to sync, the
// new table's events are not delivered to the applier, and the
// stream stays alive.

package pipeline

import (
	"context"
	"database/sql"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/engines"

	_ "sluicesync.dev/sluice/internal/engines/postgres"
)

// TestStreamer_PostgresToPostgres_NewTableOnSourceIgnored is the
// regression for Bug 13. Cold-start with 2 tables; mid-stream
// CREATE TABLE on the source plus rows; assert the streamer
// survives and the original tables continue to apply.
func TestStreamer_PostgresToPostgres_NewTableOnSourceIgnored(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresLogical(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE customers (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL
		);
		ALTER TABLE customers REPLICA IDENTITY FULL;

		CREATE TABLE products (
			id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name VARCHAR(64) NOT NULL
		);
		ALTER TABLE products REPLICA IDENTITY FULL;

		INSERT INTO customers (email) VALUES ('alice@example.com');
		INSERT INTO products (name) VALUES ('widget');
	`
	applyDDL(t, sourceDSN, seedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	const streamID = "bug13-new-table-ignored"
	streamer := &Streamer{
		Source:    pgEng,
		Target:    pgEng,
		SourceDSN: sourceDSN,
		TargetDSN: targetDSN,
		StreamID:  streamID,
	}

	streamCtx, streamCancel := context.WithCancel(context.Background())
	defer streamCancel()
	runErr := make(chan error, 1)
	go func() { runErr <- streamer.Run(streamCtx) }()

	// Bulk-copy delivers seed rows (1 in each table).
	if !waitForRowCount(t, targetDSN, "customers", 1, 30*time.Second) {
		t.Fatalf("bulk copy did not deliver customers seed row")
	}
	if !waitForRowCount(t, targetDSN, "products", 1, 30*time.Second) {
		t.Fatalf("bulk copy did not deliver products seed row")
	}

	// Verify CDC works on the original tables.
	applyDDL(t, sourceDSN, "INSERT INTO customers (email) VALUES ('bob@example.com');")
	if !waitForRowCount(t, targetDSN, "customers", 2, 30*time.Second) {
		t.Fatalf("CDC did not deliver post-snapshot insert on customers")
	}

	// ---- Now create a new table on the source mid-stream and
	// insert into it. Pre-fix, the applier crashed within seconds.
	// Post-fix (publication scoped to {customers, products}), the
	// new table's events never reach the WAL stream — and even if
	// they did (e.g. a manually-altered publication), the
	// applier's defence-in-depth path skips events for unknown
	// tables with a WARN.
	const newTableDDL = `
		CREATE TABLE ignored_table (
			id   BIGINT PRIMARY KEY,
			val  TEXT
		);
		INSERT INTO ignored_table VALUES (1, 'hi'), (2, 'there');
	`
	applyDDL(t, sourceDSN, newTableDDL)

	// Drive another change on customers AFTER the new table's
	// events. If the applier crashed on the new-table events, this
	// won't land; if it skipped them, this will arrive normally.
	applyDDL(t, sourceDSN, "INSERT INTO customers (email) VALUES ('carol@example.com');")
	if !waitForRowCount(t, targetDSN, "customers", 3, 30*time.Second) {
		t.Fatalf("CDC stream wedged after CREATE TABLE on source — Bug 13 regression")
	}

	// Sanity: the new table must NOT exist on the target. Sluice
	// is not auto-translating + creating; the publication scope
	// keeps it out, and the test asserts the negative.
	if tableExistsOnTarget(t, targetDSN, "ignored_table") {
		t.Errorf("ignored_table unexpectedly exists on target — sluice should not auto-create new source tables")
	}

	streamCancel()
	select {
	case err := <-runErr:
		if err != nil {
			t.Errorf("Streamer.Run returned err: %v", err)
		}
	case <-time.After(15 * time.Second):
		t.Fatal("Streamer.Run did not return after ctx cancel")
	}
}

// tableExistsOnTarget returns true when the named table is present
// in the target's public schema.
func tableExistsOnTarget(t *testing.T, dsn, name string) bool {
	t.Helper()
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer func() { _ = db.Close() }()
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	var exists bool
	const q = `
		SELECT EXISTS (
			SELECT 1 FROM information_schema.tables
			WHERE table_schema='public' AND table_name=$1
		)`
	if err := db.QueryRowContext(ctx, q, name).Scan(&exists); err != nil {
		t.Fatalf("table-exists probe: %v", err)
	}
	return exists
}
