//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// Integration pin for unchanged-TOAST column preservation through CDC
// apply. Adoption from the broader-mining report (gap #2 —
// docs/dev/notes/test-gap-mining-broader.md):
//
//	sluice's decoder correctly omits unchanged-TOAST (the 'u' byte at
//	cdc_reader.go:1454) and the applier's "absent key = preserve"
//	semantics in buildUpdateSQL are right in theory. But the existing
//	pin is unit-level (cdc_reader_test.go:384) and never exercises a
//	REAL multi-KB TOAST column with a sibling-column UPDATE. A
//	regression in buildUpdateSQL that interpolated an empty string for
//	the absent key would silently wipe the TOAST column — exactly the
//	silent-loss class the loud-failure tenet refuses.
//
// This file fills the gap. Setup: a PG table with a TEXT column sized
// >TOAST threshold (~2KB; we use 8KB to be safe), REPLICA IDENTITY
// DEFAULT (so the OldTuple of an UPDATE carries only the PK and the
// 'u' byte applies to the absent TOAST column on the NewTuple). Run
// a streamer, wait for the bulk-copy seed to land, then UPDATE a
// SIBLING column on the source (counter) — NOT the TOAST column. PG
// emits an UPDATE message whose NewTuple omits big_text via the 'u'
// byte; sluice's applier must preserve the target's big_text.
//
// A regression here is the worst class of bug per the tenet — the
// target row's TOAST column would silently flip from the 8KB
// payload to "" (empty string) and the operator would have no signal
// short of byte-comparing the source and target. The integration
// pin closes that observability gap loudly.

package pipeline

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/engines"

	_ "sluicesync.dev/sluice/internal/engines/postgres"
)

// TestStreamer_PostgresToPostgres_TOASTedColumnPreservedOnSiblingUpdate
// is the regression pin for gap #2. The 8KB TOAST value must survive
// a sibling-column UPDATE byte-exact on the target.
func TestStreamer_PostgresToPostgres_TOASTedColumnPreservedOnSiblingUpdate(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresLogical(t)
	defer cleanup()

	// Schema: a TOAST-prone TEXT column + a sibling INTEGER. REPLICA
	// IDENTITY DEFAULT (the sluice-default, not FULL) is what makes
	// the 'u' byte fire — under FULL the OldTuple would carry the
	// big_text value and the apply WHERE would include it (which is a
	// different code path, exercised by Bug 92 in the existing matrix).
	const seedDDL = `
		CREATE TABLE blob_holder (
			id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			label    VARCHAR(64) NOT NULL,
			big_text TEXT        NOT NULL,
			counter  INTEGER     NOT NULL DEFAULT 0
		);
		-- DEFAULT is the implicit replica identity; spelt out for clarity.
		ALTER TABLE blob_holder REPLICA IDENTITY DEFAULT;
	`
	applyDDL(t, sourceDSN, seedDDL)

	// Build a deterministic >8KB payload so PG's TOAST threshold
	// (~2KB, depends on TOAST_TUPLE_TARGET) is unambiguously exceeded.
	// Pattern is non-compressible enough to land in the TOAST table
	// (LZ4/PGLZ won't shrink random-ish content to inline). We use a
	// fixed pseudo-random alphabet so the test is byte-deterministic.
	const toastSize = 8192
	toastValue := makePseudoRandomString(toastSize)
	if len(toastValue) != toastSize {
		t.Fatalf("makePseudoRandomString: len=%d want %d", len(toastValue), toastSize)
	}

	// Seed the row BEFORE starting the streamer so the value flows
	// via bulk-copy, not via the change-stream. This isolates the
	// CDC-apply path being tested (only the sibling UPDATE is a
	// streamed event).
	insertSQL := fmt.Sprintf(
		"INSERT INTO blob_holder (label, big_text) VALUES ('initial', '%s');",
		strings.ReplaceAll(toastValue, "'", "''"),
	)
	applyDDL(t, sourceDSN, insertSQL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	const streamID = "gap2-toast-unchanged"
	streamer := &Streamer{
		Source:    pgEng,
		Target:    pgEng,
		SourceDSN: sourceDSN,
		TargetDSN: targetDSN,
		StreamID:  streamID,
	}

	streamCtx, streamCancel := context.WithCancel(context.Background())
	defer streamCancel()
	runErr := make(chan error, 1)
	go func() { runErr <- streamer.Run(streamCtx) }()
	t.Cleanup(func() {
		streamCancel()
		// Drain the streamer; a non-nil non-cancel error here is
		// surfaced as a test-level issue rather than ignored.
		select {
		case err := <-runErr:
			if err != nil && err != context.Canceled {
				t.Logf("streamer exit err: %v", err)
			}
		case <-time.After(15 * time.Second):
			t.Log("streamer did not exit within 15s after cancel")
		}
	})

	// Wait for bulk-copy to deliver the seed row + its full TOAST value.
	if !waitForRowCount(t, targetDSN, "blob_holder", 1, 60*time.Second) {
		t.Fatalf("bulk copy did not deliver the seed row within 60s")
	}

	// Verify the target has the FULL TOAST value before we touch
	// anything via CDC. If this assertion fails, the bulk-copy COPY
	// path lost the TOAST value — a separate, equally-serious bug.
	target, err := sql.Open("pgx", targetDSN)
	if err != nil {
		t.Fatalf("sql.Open target: %v", err)
	}
	defer func() { _ = target.Close() }()

	verifyTOAST := func(stage, wantText string, wantCounter int) {
		t.Helper()
		var gotText string
		var gotCounter int
		const q = "SELECT big_text, counter FROM blob_holder WHERE label = 'initial'"
		if err := target.QueryRowContext(streamCtx, q).Scan(&gotText, &gotCounter); err != nil {
			t.Fatalf("%s: scan target row: %v", stage, err)
		}
		if gotCounter != wantCounter {
			t.Errorf("%s: counter = %d; want %d", stage, gotCounter, wantCounter)
		}
		if gotText != wantText {
			// Don't dump 8KB to the log — name the size + the first
			// and last 32 bytes so a wipe (gotText="") or a truncation
			// (gotText prefix matches but length differs) are
			// distinguishable.
			head := head32(gotText)
			tail := tail32(gotText)
			t.Errorf("%s: big_text length=%d want=%d; head=%q tail=%q "+
				"(silent-loss class: this is the gap #2 the loud-failure tenet refuses)",
				stage, len(gotText), len(wantText), head, tail)
		}
	}

	verifyTOAST("after bulk-copy", toastValue, 0)

	// THE LOAD-BEARING STEP: UPDATE the sibling column ONLY. Under
	// REPLICA IDENTITY DEFAULT this emits an UPDATE message whose
	// NewTuple includes counter + the 'u' byte for big_text. The
	// applier must produce `UPDATE … SET counter=$1 WHERE id=$2`
	// (NOT include big_text in the SET). If buildUpdateSQL regressed
	// to interpolating "" for absent keys, big_text would land as ""
	// on the target.
	applyDDL(t, sourceDSN, "UPDATE blob_holder SET counter = 42 WHERE label = 'initial';")

	// Poll for the apply to land. The CDC stream is async; counter
	// flipping from 0 → 42 is the "apply has run" signal. Once it
	// flips, big_text MUST still be the 8KB original.
	if !waitForCounterValue(t, target, streamCtx, 42, 30*time.Second) {
		t.Fatalf("CDC sibling-UPDATE did not land within 30s (counter never became 42)")
	}
	verifyTOAST("after sibling UPDATE (the gap #2 load-bearing assertion)", toastValue, 42)
}

// makePseudoRandomString returns a deterministic n-byte ASCII string
// that compresses poorly (so PG TOASTs it inline rather than inline-
// compressing it under PGLZ). Uses a simple xorshift over a printable
// alphabet for determinism + byte-stability across test runs.
func makePseudoRandomString(n int) string {
	const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_."
	state := uint32(0xC001D00D)
	out := make([]byte, n)
	for i := 0; i < n; i++ {
		state ^= state << 13
		state ^= state >> 17
		state ^= state << 5
		out[i] = alphabet[int(state)%len(alphabet)]
	}
	return string(out)
}

func head32(s string) string {
	if len(s) <= 32 {
		return s
	}
	return s[:32] + "…"
}

func tail32(s string) string {
	if len(s) <= 32 {
		return s
	}
	return "…" + s[len(s)-32:]
}

// waitForCounterValue polls until blob_holder.counter for label='initial'
// reaches wantCounter or the timeout expires. Returns true on success.
func waitForCounterValue(t *testing.T, db *sql.DB, ctx context.Context, wantCounter int, timeout time.Duration) bool {
	t.Helper()
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		var got int
		const q = "SELECT counter FROM blob_holder WHERE label = 'initial'"
		if err := db.QueryRowContext(ctx, q).Scan(&got); err == nil && got == wantCounter {
			return true
		}
		time.Sleep(100 * time.Millisecond)
	}
	return false
}
