//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

package pipeline

import (
	"context"
	"database/sql"
	"encoding/json"
	"strings"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/engines"
)

// TestStreamer_PG_ForeignLineageRefusedOnWarmResume_EmptyTarget is the
// end-to-end pin for audit 2026-09-15 A0915-ARCH-MEDIUM-1, on the arm the
// audit found open.
//
// A Postgres source whose (systemid, timeline) no longer matches the
// persisted position's pin — a PITR'd or promoted instance, or a DSN
// re-pointed at a different one — used to surface through
// ir.ErrPositionInvalid, the sentinel that routes the ADR-0022 automatic
// re-copy. A POPULATED target was saved by the populated-target gate; an
// EMPTY one (a freshly prepared target the operator pointed a resuming
// sync at) cold-started from the diverged instance at exit 0 and then
// streamed the wrong lineage, with every change on the abandoned timeline
// absent forever. The engine now carries ir.ErrPositionForeignLineage
// and the pipeline REFUSES (FOREIGN-LINEAGE-REFUSED).
//
// The divergence is a tampered systemid in the persisted position (the
// same substitution the engine's own pin uses: checkSourceIdentity
// compares the pin to IDENTIFY_SYSTEM and cannot tell a doctored token
// from a real PITR). The slot is dropped and the target emptied so the
// pre-fix path has nothing to refuse on — before this change the run
// entered CDC and never returned; with it, the refusal names the marker
// and the target stays empty.
func TestStreamer_PG_ForeignLineageRefusedOnWarmResume_EmptyTarget(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresLogical(t)
	defer cleanup()

	applyDDL(t, sourceDSN, `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL
		);
		ALTER TABLE users REPLICA IDENTITY FULL;
		INSERT INTO users (email) VALUES ('alice@example.com'), ('bob@example.com');
	`)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}
	const streamID = "pg-foreign-lineage"
	newStreamer := func() *Streamer {
		return &Streamer{
			Source: pgEng, Target: pgEng,
			SourceDSN: sourceDSN, TargetDSN: targetDSN,
			StreamID: streamID,
		}
	}

	// Run 1: a real cold start, so the target holds a persisted position
	// carrying the source's (systemid, timeline) pin.
	streamCtx, streamCancel := context.WithCancel(context.Background())
	runErr := make(chan error, 1)
	go func() { runErr <- newStreamer().Run(streamCtx) }()
	waitForSourceSlot(t, sourceDSN, 60*time.Second)
	if !waitForRowCount(t, targetDSN, "users", 2, 60*time.Second) {
		streamCancel()
		<-runErr
		t.Fatalf("target users rows = %d after bulk copy; want 2", pollRowCount(targetDSN, "users"))
	}
	// The CDC anchor is written at the very END of the cold start, after
	// the copy the row count above proves; wait for it, or there is no
	// persisted position to tamper with.
	tgt, err := sql.Open("pgx", targetDSN)
	if err != nil {
		t.Fatalf("open target: %v", err)
	}
	defer func() { _ = tgt.Close() }()
	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()
	var token string
	for deadline := time.Now().Add(60 * time.Second); ; {
		err := tgt.QueryRowContext(ctx, `SELECT source_position FROM sluice_cdc_state WHERE stream_id = $1`, streamID).Scan(&token)
		if err == nil && token != "" {
			break
		}
		if time.Now().After(deadline) {
			streamCancel()
			<-runErr
			t.Fatalf("no persisted position for %q after the cold start: %v", streamID, err)
		}
		time.Sleep(200 * time.Millisecond)
	}
	streamCancel()
	select {
	case <-runErr:
	case <-time.After(20 * time.Second):
		t.Fatal("first stream did not return after ctx cancel")
	}

	// Tamper the persisted position's systemid on the target — the pin
	// the engine compares against IDENTIFY_SYSTEM.
	var pos map[string]any
	if err := json.Unmarshal([]byte(token), &pos); err != nil {
		t.Fatalf("decode persisted position %q: %v", token, err)
	}
	sysid, _ := pos["systemid"].(string)
	if sysid == "" {
		t.Fatalf("persisted position carries no systemid pin; nothing to diverge: %s", token)
	}
	pos["systemid"] = sysid + "0"
	tampered, err := json.Marshal(pos)
	if err != nil {
		t.Fatalf("encode tampered position: %v", err)
	}
	if _, err := tgt.ExecContext(ctx, `UPDATE sluice_cdc_state SET source_position = $1 WHERE stream_id = $2`, string(tampered), streamID); err != nil {
		t.Fatalf("write tampered position: %v", err)
	}

	// The harm arm: no slot to refuse on, and an EMPTY target so the
	// populated-target gate — the unrelated guard that saved the other
	// arm — has nothing to say.
	if dropSluiceSlots(t, sourceDSN) == 0 {
		t.Fatal("no sluice replication slot to drop; the pre-fix fall-through path cannot be modelled")
	}
	if _, err := tgt.ExecContext(ctx, `TRUNCATE users`); err != nil {
		t.Fatalf("empty the target: %v", err)
	}

	// Run 2: the warm resume must REFUSE with the foreign-lineage marker,
	// promptly, having copied nothing.
	resumeCtx, resumeCancel := context.WithCancel(context.Background())
	defer resumeCancel()
	resumeErr := make(chan error, 1)
	go func() { resumeErr <- newStreamer().Run(resumeCtx) }()
	select {
	case err := <-resumeErr:
		if err == nil {
			t.Fatal("warm resume against a diverged source returned nil")
		}
		if !strings.Contains(err.Error(), foreignLineageMarker) {
			t.Fatalf("warm resume against a diverged source did not refuse with %s:\n%v", foreignLineageMarker, err)
		}
		if !strings.Contains(err.Error(), "source identity has changed") {
			t.Errorf("the refusal does not carry the engine's own diagnosis naming both pins:\n%v", err)
		}
	case <-time.After(90 * time.Second):
		resumeCancel()
		t.Fatal("warm resume against a diverged source neither refused nor returned within 90s — the " +
			"pre-fix fall-through cold-started from the diverged instance and entered CDC")
	}
	if n := countRows(t, targetDSN, "users"); n != 0 {
		t.Errorf("target users rows = %d after the refusal; want 0 — the refusal must copy nothing", n)
	}
}
