//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// Integration pin for ENUM mid-stream drift via `ALTER TYPE … ADD
// VALUE` (broader-mining gap #3 —
// docs/dev/notes/test-gap-mining-broader.md).
//
// Scenario: sluice's SchemaReader captures an ENUM with values
// `{a, b}` at snapshot time. After the snapshot, the source runs
// `ALTER TYPE my_enum ADD VALUE 'c'` and inserts a row with
// `enum_col = 'c'`. The CDC stream delivers that row to the applier.
// The target's ENUM only has `{a, b}` — the apply MUST surface
// SQLSTATE 22P02 ("invalid input value for enum") rather than:
//
//   - silently dropping the row,
//   - silently coercing 'c' to NULL or to one of the known values,
//   - silently stalling the stream with no diagnostic.
//
// The test pin pursues the loud-failure tenet: a streamer error
// within a bounded window is acceptable; a row landing with the wrong
// value is silent loss; a row never landing and the streamer
// continuing happily is also silent loss. The test documents which
// shape sluice produces today so the maintainer can codify the policy
// (likely: refuse-loudly with an actionable "re-snapshot the schema"
// hint, possibly with an automatic `ALTER TYPE … ADD VALUE` forward
// on the target as a future enhancement).
//
// This test is gated on PG 14+ in spirit (ENUM ADD VALUE is
// transactionally safe from 12, but the testcontainer is PG 16, so we
// run unconditionally).

package pipeline

import (
	"context"
	"database/sql"
	"strings"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/engines"

	_ "sluicesync.dev/sluice/internal/engines/postgres"
)

// TestStreamer_PostgresToPostgres_EnumAddValueMidStream_DriftPolicy is
// the regression pin for gap #3. Either the streamer surfaces a clear
// error within 30s OR the target eventually has the row with 'c' — any
// other outcome (silent skip, indefinite stall with no error) is the
// silent-loss class the tenet refuses.
func TestStreamer_PostgresToPostgres_EnumAddValueMidStream_DriftPolicy(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresLogical(t)
	defer cleanup()

	const seedDDL = `
		CREATE TYPE color AS ENUM ('red', 'green');

		CREATE TABLE paint (
			id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			label  VARCHAR(64) NOT NULL,
			c      color       NOT NULL
		);
		ALTER TABLE paint REPLICA IDENTITY FULL;

		INSERT INTO paint (label, c) VALUES ('initial', 'red');
	`
	applyDDL(t, sourceDSN, seedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	const streamID = "gap3-enum-drift"
	streamer := &Streamer{
		Source:    pgEng,
		Target:    pgEng,
		SourceDSN: sourceDSN,
		TargetDSN: targetDSN,
		StreamID:  streamID,
	}

	streamCtx, streamCancel := context.WithCancel(context.Background())
	defer streamCancel()
	runErr := make(chan error, 1)
	go func() { runErr <- streamer.Run(streamCtx) }()

	if !waitForRowCount(t, targetDSN, "paint", 1, 60*time.Second) {
		t.Fatalf("bulk copy did not deliver the seed row within 60s")
	}

	target, err := sql.Open("pgx", targetDSN)
	if err != nil {
		t.Fatalf("sql.Open target: %v", err)
	}
	defer func() { _ = target.Close() }()

	// Verify the target ENUM has the snapshot-time values only.
	enumValues := readEnumValues(t, target, streamCtx, "color")
	if want := []string{"red", "green"}; !equalStringSlices(enumValues, want) {
		t.Fatalf("target ENUM 'color' values = %v; want %v (snapshot phase regressed?)", enumValues, want)
	}

	// MID-STREAM DRIFT: add 'blue' to the source ENUM, then insert a
	// row carrying it. The source ALTER TYPE must commit before the
	// INSERT (PG-14+ allows ADD VALUE in transactions; PG-16 in the
	// container handles this fine). Use a separate connection so the
	// ALTER TYPE is durably committed before the INSERT fires.
	applyDDL(t, sourceDSN, `ALTER TYPE color ADD VALUE 'blue';`)
	applyDDL(t, sourceDSN, `INSERT INTO paint (label, c) VALUES ('after-drift', 'blue');`)

	// Now poll the streamer + target. Three possible outcomes:
	//
	//   (i)  Streamer surfaces an error within the window — LOUD,
	//        operator-readable, acceptable per the tenet. Test passes.
	//   (ii) Target lands the row with 'blue' (the sluice auto-forwarded
	//        the ALTER TYPE OR the target was pre-aligned) — also
	//        acceptable; rare but legitimate.
	//   (iii) Streamer keeps running, target doesn't get the row, no
	//         error surfaces — SILENT-LOSS class. Test FAILS loudly.
	const window = 30 * time.Second
	deadline := time.Now().Add(window)

	for time.Now().Before(deadline) {
		// (i) streamer surfaced an error
		select {
		case err := <-runErr:
			if err == nil || err == context.Canceled {
				t.Fatalf("streamer exited with nil/ctx-cancel during ENUM drift test — "+
					"the stream should either fail loudly OR keep applying; clean exit is silent-loss class.\n"+
					"err=%v", err)
			}
			// LOUD failure path. The error SHAPE shifted with catalog
			// Bug 151: before it, the PG-source reader wedged at
			// oidToType ("unsupported column type OID 16390"); now the
			// reader resolves the dynamic enum OID and decodes 'blue' as
			// a label, so the LOUD failure moves DOWNSTREAM to the
			// applier, where PG rejects the unknown label against the
			// target enum's value set:
			//
			//   "...: invalid input value for enum color: \"blue\""  (22P02)
			//
			// Both shapes are LOUD ✓ (halt the stream, no silent loss) and
			// both are accepted below — the assertion takes either the
			// applier 22P02/enum/label hints OR the pre-151 reader
			// unsupported-OID shape, so the test is robust across the
			// transition. (The seed row c='red' applying cleanly through
			// the full Streamer also makes this the de-facto enum
			// happy-path apply pin.)
			errStr := err.Error()
			t.Logf("LOUD-FAILURE path: streamer surfaced an error within %v\n  err: %v",
				time.Since(deadline.Add(-window)), errStr)
			// Accept any of: a direct ENUM hint OR the per-column /
			// per-OID diagnostic sluice produces today (which IS
			// loud-and-grep-able, just terse).
			ok := false
			for _, want := range []string{
				"enum", "invalid input", "22P02", "color", "blue", // ideal hints
				"unsupported column type", "OID", "public.paint", "column \"c\"", // current sluice shape
			} {
				if containsCaseFold(errStr, want) {
					ok = true
					break
				}
			}
			if !ok {
				t.Errorf("streamer error is loud but lacks ANY operator-grep-able hint; "+
					"got: %v\n(operators reading CI output need at least the relation/column/OID)",
					errStr)
			}
			// Even when accepted, log a hint-quality follow-up so the
			// maintainer can decide whether to upgrade sluice's CDC-reader
			// error message when ADD VALUE is the cause (e.g., a probe
			// against pg_type that recognises typtype='e' and emits
			// "ENUM 'color' has new value not in snapshot — re-snapshot
			// or run sluice with --refresh-enum-types").
			if !containsCaseFold(errStr, "enum") {
				t.Logf("HINT-QUALITY FOLLOW-UP: the error doesn't name ENUM as the cause. " +
					"An operator who didn't write the ALTER TYPE has to look up the OID to discover " +
					"the column is an ENUM. Worth an upgrade to the CDC-reader's unsupported-column-type " +
					"diagnostic when typtype='e'.")
			}
			return
		default:
		}

		// (ii) target landed the row
		var n int
		err := target.QueryRowContext(
			streamCtx,
			`SELECT count(*) FROM paint WHERE label = 'after-drift'`,
		).Scan(&n)
		if err == nil && n == 1 {
			var got string
			if scanErr := target.QueryRowContext(
				streamCtx,
				`SELECT c::text FROM paint WHERE label = 'after-drift'`,
			).Scan(&got); scanErr == nil {
				if got != "blue" {
					t.Fatalf("target row landed with c=%q; want 'blue' — silent coercion of an unknown ENUM value", got)
				}
				t.Logf("target landed the row with c='blue' — sluice auto-forwarded the ENUM drift (rare but legitimate)")
				return
			}
		}

		time.Sleep(200 * time.Millisecond)
	}

	// (iii) — the silent-loss case. Streamer still running, target
	// row absent, no error. This is the worst-class outcome.
	var n int
	if err := target.QueryRowContext(
		streamCtx,
		`SELECT count(*) FROM paint WHERE label = 'after-drift'`,
	).Scan(&n); err != nil {
		t.Fatalf("target row count query after drift window: %v", err)
	}
	t.Fatalf("SILENT-LOSS CLASS: streamer kept running for %v after `ALTER TYPE ADD VALUE 'blue'` + INSERT, "+
		"target has %d rows with label='after-drift' (want 1 OR a loud streamer error). "+
		"Per the loud-failure tenet, sluice must either refuse-loudly OR auto-forward the ADD VALUE; "+
		"silent skip with no diagnostic is the regression this pin catches.",
		window, n)
}

// readEnumValues returns the values declared on the named ENUM type
// in the database the DSN points at. Sorted in declaration order via
// pg_enum.enumsortorder so the slice equality check is stable across
// PG releases.
func readEnumValues(t *testing.T, db *sql.DB, ctx context.Context, typname string) []string {
	t.Helper()
	const q = `
		SELECT e.enumlabel
		  FROM pg_enum e
		  JOIN pg_type t ON e.enumtypid = t.oid
		 WHERE t.typname = $1
		 ORDER BY e.enumsortorder
	`
	rows, err := db.QueryContext(ctx, q, typname)
	if err != nil {
		t.Fatalf("read enum values: %v", err)
	}
	defer func() { _ = rows.Close() }()
	var out []string
	for rows.Next() {
		var s string
		if err := rows.Scan(&s); err != nil {
			t.Fatalf("scan enum value: %v", err)
		}
		out = append(out, s)
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows.Err: %v", err)
	}
	return out
}

// containsCaseFold is strings.Contains with case-folding for the hint
// check in the streamer-error path.
func containsCaseFold(haystack, needle string) bool {
	lower := func(s string) string {
		out := make([]byte, len(s))
		for i := 0; i < len(s); i++ {
			c := s[i]
			if c >= 'A' && c <= 'Z' {
				c += 'a' - 'A'
			}
			out[i] = c
		}
		return string(out)
	}
	return strings.Contains(lower(haystack), lower(needle))
}
