//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// Integration pin for TRUNCATE event handling through CDC apply
// (broader-mining gap #7 — docs/dev/notes/test-gap-mining-broader.md).
//
// sluice's CDC reader emits [ir.Truncate] for pgoutput TRUNCATE
// messages (postgres/cdc_reader.go:1159), and the applier translates
// to `TRUNCATE schema.table` on the target with a skip-with-warning
// fallback if the target table is missing (postgres/change_applier.go
// :1126). This pin asserts that contract holds end-to-end:
//
//   1. Source has N rows; bulk-copy delivers them to the target.
//   2. Source runs `TRUNCATE table` mid-stream.
//   3. Target's row count drops to 0 within a bounded window.
//   4. Post-TRUNCATE INSERTs on source are then applied normally.
//
// The silent-loss class this pin catches is the opposite of the usual
// shape: if the applier silently SKIPPED the TRUNCATE event, the
// target would retain stale rows that no longer exist on the source
// — a divergence the operator wouldn't notice until a future query
// returned different results from the source and target.

package pipeline

import (
	"context"
	"database/sql"
	"testing"
	"time"

	"github.com/orware/sluice/internal/engines"

	_ "github.com/orware/sluice/internal/engines/postgres"
)

// TestStreamer_PostgresToPostgres_TruncateEventAppliedToTarget pins
// the gap #7 contract: pgoutput TRUNCATE → applier TRUNCATE on
// target → row count drops, and a subsequent INSERT also lands.
func TestStreamer_PostgresToPostgres_TruncateEventAppliedToTarget(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresLogical(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE events (
			id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			label  VARCHAR(64) NOT NULL
		);
		ALTER TABLE events REPLICA IDENTITY FULL;

		INSERT INTO events (label) VALUES
			('seed-1'), ('seed-2'), ('seed-3'), ('seed-4'), ('seed-5');
	`
	applyDDL(t, sourceDSN, seedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	streamer := &Streamer{
		Source:    pgEng,
		Target:    pgEng,
		SourceDSN: sourceDSN,
		TargetDSN: targetDSN,
		StreamID:  "gap7-truncate-event",
	}

	streamCtx, streamCancel := context.WithCancel(context.Background())
	defer streamCancel()
	runErr := make(chan error, 1)
	go func() { runErr <- streamer.Run(streamCtx) }()
	t.Cleanup(func() {
		streamCancel()
		select {
		case err := <-runErr:
			if err != nil && err != context.Canceled {
				t.Logf("streamer exit err: %v", err)
			}
		case <-time.After(15 * time.Second):
			t.Log("streamer did not exit within 15s after cancel")
		}
	})

	// Bulk-copy delivers the 5 seed rows.
	if !waitForRowCount(t, targetDSN, "events", 5, 60*time.Second) {
		t.Fatalf("bulk copy did not deliver the 5 seed rows within 60s")
	}

	// TRUNCATE on the source. pgoutput emits a TRUNCATE message; the
	// applier should issue `TRUNCATE schema.events` on the target.
	applyDDL(t, sourceDSN, `TRUNCATE TABLE events;`)

	// Poll until the target row count drops to 0. The silent-loss
	// shape this catches: applier silently skips the TRUNCATE → the 5
	// rows stay on the target while the source has 0, a divergence
	// the operator wouldn't see without comparing both sides.
	deadline := time.Now().Add(30 * time.Second)
	target, err := sql.Open("pgx", targetDSN)
	if err != nil {
		t.Fatalf("sql.Open target: %v", err)
	}
	defer func() { _ = target.Close() }()

	for time.Now().Before(deadline) {
		var n int
		if err := target.QueryRowContext(streamCtx,
			`SELECT count(*) FROM events`).Scan(&n); err != nil {
			t.Fatalf("count target rows: %v", err)
		}
		if n == 0 {
			break
		}
		time.Sleep(200 * time.Millisecond)
	}

	var finalCount int
	if err := target.QueryRowContext(streamCtx,
		`SELECT count(*) FROM events`).Scan(&finalCount); err != nil {
		t.Fatalf("final count target rows: %v", err)
	}
	if finalCount != 0 {
		// Surface streamer state to distinguish silent-skip from a
		// halt or stall.
		select {
		case err := <-runErr:
			t.Fatalf("target row count = %d after TRUNCATE within 30s; streamer exited err=%v", finalCount, err)
		default:
		}
		t.Fatalf("SILENT-SKIP CLASS: target row count = %d 30s after source TRUNCATE; "+
			"streamer still running but TRUNCATE event was not applied. "+
			"Per the loud-failure tenet, sluice must either apply the TRUNCATE or surface an error; "+
			"silently leaving the target with stale rows is a source/target divergence the operator "+
			"would not notice.", finalCount)
	}

	// Post-TRUNCATE INSERT must land. This catches a streamer that
	// halted on the TRUNCATE — the row count would stay at 0 but
	// subsequent inserts wouldn't reach the target either.
	applyDDL(t, sourceDSN, `INSERT INTO events (label) VALUES ('post-truncate-1'), ('post-truncate-2');`)
	if !waitForRowCount(t, targetDSN, "events", 2, 30*time.Second) {
		t.Fatalf("post-TRUNCATE INSERT (2 rows) did not land within 30s — possible streamer halt after TRUNCATE apply")
	}

	// Final sanity: the rows are the correct ones (the post-TRUNCATE
	// ones, not zombie pre-TRUNCATE rows).
	var labels [2]string
	rows, err := target.QueryContext(streamCtx,
		`SELECT label FROM events ORDER BY id`)
	if err != nil {
		t.Fatalf("query labels: %v", err)
	}
	defer func() { _ = rows.Close() }()
	i := 0
	for rows.Next() {
		if i >= len(labels) {
			t.Fatal("more rows than expected")
		}
		if err := rows.Scan(&labels[i]); err != nil {
			t.Fatalf("scan label: %v", err)
		}
		i++
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows.Err: %v", err)
	}
	if labels[0] != "post-truncate-1" || labels[1] != "post-truncate-2" {
		t.Errorf("target labels = %v; want [post-truncate-1, post-truncate-2] "+
			"(if the labels look like 'seed-*' the TRUNCATE didn't really land and the post-INSERT rows mixed in)",
			labels)
	}
}
