//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// Continuous-sync (snapshot + CDC) integration tests for the
// generated-column path. Same-engine MySQL→MySQL and Postgres→Postgres
// only — cross-engine CDC over generated columns is covered by the
// (non-CDC) cross-engine migrate test in
// migrate_generated_integration_test.go; the CDC path through the
// snapshot orchestrator is the same shape on both sides, so a
// cross-engine streamer test would not exercise anything new.
//
// Translation policy reminder: the source's GENERATED expression is
// passed through verbatim; non-portable expressions fail loudly on
// the target, not silently.

package pipeline

import (
	"context"
	"database/sql"
	"strconv"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/engines"

	_ "sluicesync.dev/sluice/internal/engines/mysql"
	_ "sluicesync.dev/sluice/internal/engines/postgres"
)

// TestStreamer_MySQLToMySQL_Generated drives the snapshot+CDC path
// across a schema with a STORED generated column. The post-snapshot
// CDC stream emits binlog row events that include the generated
// column's value; the reader filters it out so the applier's INSERT
// doesn't try to write into the GENERATED column. The target's own
// GENERATED clause then recomputes the value.
func TestStreamer_MySQLToMySQL_Generated(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startMySQLBinlog(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE invoices (
			id    BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
			qty   INT             NOT NULL,
			price DECIMAL(10, 2)  NOT NULL,
			total DECIMAL(20, 2) GENERATED ALWAYS AS (qty * price) STORED,
			PRIMARY KEY (id)
		) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
		INSERT INTO invoices (qty, price) VALUES (2, 10.00);
	`
	applyDDLMySQL(t, sourceDSN, seedDDL)

	mysqlEng, ok := engines.Get("mysql")
	if !ok {
		t.Fatal("mysql engine not registered")
	}

	streamer := &Streamer{
		Source:    mysqlEng,
		Target:    mysqlEng,
		SourceDSN: sourceDSN,
		TargetDSN: targetDSN,
		StreamID:  "test-generated-mysql",
	}

	streamCtx, streamCancel := context.WithCancel(context.Background())
	defer streamCancel()

	runErr := make(chan error, 1)
	go func() { runErr <- streamer.Run(streamCtx) }()

	// Phase 1: snapshot delivers the seed row.
	if !waitForRowCountMySQL(t, targetDSN, "invoices", 1, 60*time.Second) {
		t.Fatalf("phase 1: bulk copy never delivered seed row to target")
	}
	assertMySQLInvoiceTotals(t, targetDSN, []float64{20.00})

	// Phase 2: CDC INSERT — applier must not try to write `total`.
	applyDDLMySQL(t, sourceDSN, "INSERT INTO invoices (qty, price) VALUES (3, 5.50);")
	if !waitForRowCountMySQL(t, targetDSN, "invoices", 2, 30*time.Second) {
		t.Fatalf("phase 2: CDC INSERT never delivered row 2 to target")
	}
	assertMySQLInvoiceTotals(t, targetDSN, []float64{20.00, 16.50})

	// Phase 3: CDC UPDATE on a dependent column — total must
	// recompute on the target via its own GENERATED clause.
	applyDDLMySQL(t, sourceDSN, "UPDATE invoices SET qty = 5 WHERE id = 1;")
	if !waitForMySQLInvoiceTotal(t, targetDSN, 1, 50.00, 30*time.Second) {
		t.Fatalf("phase 3: CDC UPDATE never propagated; row 1 total never reached 50.00")
	}
	assertMySQLInvoiceTotals(t, targetDSN, []float64{50.00, 16.50})
}

// TestStreamer_PostgresToPostgres_Generated mirrors the MySQL test
// above on Postgres. PG's logical replication doesn't replicate
// generated columns at all (the publisher elides them from
// RelationMessage and TupleData), so the filter on the IR side is
// defence-in-depth here — the test still verifies the end-to-end
// invariant that the target's GENERATED clause does the recomputation.
func TestStreamer_PostgresToPostgres_Generated(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresLogical(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE invoices (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			qty   INTEGER        NOT NULL,
			price NUMERIC(10, 2) NOT NULL,
			total NUMERIC(20, 2) GENERATED ALWAYS AS (qty * price) STORED
		);
		ALTER TABLE invoices REPLICA IDENTITY FULL;
		INSERT INTO invoices (qty, price) VALUES (2, 10.00);
	`
	applyDDL(t, sourceDSN, seedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	streamer := &Streamer{
		Source:    pgEng,
		Target:    pgEng,
		SourceDSN: sourceDSN,
		TargetDSN: targetDSN,
		StreamID:  "test-generated-pg",
	}

	streamCtx, streamCancel := context.WithCancel(context.Background())
	defer streamCancel()

	runErr := make(chan error, 1)
	go func() { runErr <- streamer.Run(streamCtx) }()

	if !waitForRowCount(t, targetDSN, "invoices", 1, 60*time.Second) {
		t.Fatalf("phase 1: bulk copy never delivered seed row to target")
	}
	assertPGInvoiceTotals(t, targetDSN, []float64{20.00})

	applyDDL(t, sourceDSN, "INSERT INTO invoices (qty, price) VALUES (3, 5.50);")
	if !waitForRowCount(t, targetDSN, "invoices", 2, 30*time.Second) {
		t.Fatalf("phase 2: CDC INSERT never delivered row 2 to target")
	}
	assertPGInvoiceTotals(t, targetDSN, []float64{20.00, 16.50})

	applyDDL(t, sourceDSN, "UPDATE invoices SET qty = 5 WHERE id = 1;")
	if !waitForPGInvoiceTotal(t, targetDSN, 1, 50.00, 30*time.Second) {
		t.Fatalf("phase 3: CDC UPDATE never propagated; row 1 total never reached 50.00")
	}
	assertPGInvoiceTotals(t, targetDSN, []float64{50.00, 16.50})
}

// assertMySQLInvoiceTotals reads invoices.total in PK order on the
// MySQL target and asserts the values match want. Tolerates an
// epsilon for DECIMAL string-form differences.
func assertMySQLInvoiceTotals(t *testing.T, dsn string, want []float64) {
	t.Helper()
	db, err := sql.Open("mysql", dsn)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer func() { _ = db.Close() }()
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	assertInvoiceTotalsFromDB(t, ctx, db, want)
}

func assertPGInvoiceTotals(t *testing.T, dsn string, want []float64) {
	t.Helper()
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer func() { _ = db.Close() }()
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	assertInvoiceTotalsFromDB(t, ctx, db, want)
}

func assertInvoiceTotalsFromDB(t *testing.T, ctx context.Context, db *sql.DB, want []float64) {
	t.Helper()
	rows, err := db.QueryContext(ctx, "SELECT total FROM invoices ORDER BY id")
	if err != nil {
		t.Fatalf("select totals: %v", err)
	}
	defer func() { _ = rows.Close() }()

	var got []float64
	for rows.Next() {
		var s string
		if err := rows.Scan(&s); err != nil {
			t.Fatalf("scan: %v", err)
		}
		v, err := strconv.ParseFloat(s, 64)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		got = append(got, v)
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows iter: %v", err)
	}
	if len(got) != len(want) {
		t.Fatalf("got %d rows; want %d (got=%v)", len(got), len(want), got)
	}
	for i := range want {
		const eps = 0.001
		if diff := got[i] - want[i]; diff < -eps || diff > eps {
			t.Errorf("row %d: total = %v; want %v", i, got[i], want[i])
		}
	}
}

// waitForMySQLInvoiceTotal polls invoices.total for a specific id
// until it reaches the target value or the timeout expires. Used to
// assert async CDC propagation without flaky time.Sleep.
func waitForMySQLInvoiceTotal(t *testing.T, dsn string, id int, want float64, timeout time.Duration) bool {
	t.Helper()
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		if pollMySQLInvoiceTotal(dsn, id) == want {
			return true
		}
		time.Sleep(200 * time.Millisecond)
	}
	return false
}

func pollMySQLInvoiceTotal(dsn string, id int) float64 {
	db, err := sql.Open("mysql", dsn)
	if err != nil {
		return 0
	}
	defer func() { _ = db.Close() }()
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	var s string
	if err := db.QueryRowContext(ctx, "SELECT total FROM invoices WHERE id = ?", id).Scan(&s); err != nil {
		return 0
	}
	v, err := strconv.ParseFloat(s, 64)
	if err != nil {
		return 0
	}
	return v
}

func waitForPGInvoiceTotal(t *testing.T, dsn string, id int, want float64, timeout time.Duration) bool {
	t.Helper()
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		if pollPGInvoiceTotal(dsn, id) == want {
			return true
		}
		time.Sleep(200 * time.Millisecond)
	}
	return false
}

func pollPGInvoiceTotal(dsn string, id int) float64 {
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		return 0
	}
	defer func() { _ = db.Close() }()
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	var s string
	if err := db.QueryRowContext(ctx, "SELECT total FROM invoices WHERE id = $1", id).Scan(&s); err != nil {
		return 0
	}
	v, err := strconv.ParseFloat(s, 64)
	if err != nil {
		return 0
	}
	return v
}
