//go:build integration

// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// Phase 3.3 integration tests for `sluice sync start
// --position-from-manifest` on PG sources. Covers the design doc's
// Acceptance Criteria 6, 7, 8 plus the EndPosition-recording
// criterion 1:
//
//   - Criterion 1: a v0.17.2 full backup records EndPosition; the
//     "parent has no EndPosition" warning no longer fires.
//   - Criterion 6: chain handoff with the slot still in place — the
//     CDC reader resumes via slot reuse.
//   - Criterion 7: chain handoff with the slot dropped but
//     wal_keep_size sufficient — soft warnings emitted; no refusal.
//   - Criterion 8: chain handoff with the slot dropped AND
//     wal_keep_size insufficient — refusal naming the gap.
//   - Criterion 10 (mocked-equivalent): Patroni-detection signals on
//     a real PG cluster aren't testable without a Patroni front-end,
//     so we cover the detection logic with the role-name signal.

package pipeline

import (
	"context"
	"database/sql"
	"strings"
	"testing"
	"time"

	"sluicesync.dev/sluice/internal/engines"
	"sluicesync.dev/sluice/internal/ir"
	irbackup "sluicesync.dev/sluice/internal/ir/backup"
	"sluicesync.dev/sluice/internal/pipeline/blobcodec"

	_ "sluicesync.dev/sluice/internal/engines/postgres"

	"github.com/testcontainers/testcontainers-go"
	pgtc "github.com/testcontainers/testcontainers-go/modules/postgres"
)

// TestBackup_RecordsEndPosition_PostgresIntegration pins acceptance
// criterion 1: a v0.17.2 PG full backup records a non-empty
// EndPosition, with the slot/lsn shape the chain incremental can
// resume from.
func TestBackup_RecordsEndPosition_PostgresIntegration(t *testing.T) {
	sourceDSN, _, cleanup := startPostgresLogical(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL
		);
		ALTER TABLE users REPLICA IDENTITY FULL;
		INSERT INTO users (email) VALUES ('alice@example.com');
	`
	applyDDL(t, sourceDSN, seedDDL)

	pgEng, ok := engines.Get("postgres")
	if !ok {
		t.Fatal("postgres engine not registered")
	}

	dir := t.TempDir()
	store, err := blobcodec.NewLocalStore(dir)
	if err != nil {
		t.Fatalf("NewLocalStore: %v", err)
	}
	if err := (&Backup{
		Source: pgEng, SourceDSN: sourceDSN, Store: store,
		SluiceVersion: "v0.17.2-test",
		SlotName:      "sluice_slot",
	}).Run(context.Background()); err != nil {
		t.Fatalf("Backup.Run: %v", err)
	}
	full, err := readManifest(context.Background(), store)
	if err != nil {
		t.Fatalf("readManifest: %v", err)
	}
	if full.EndPosition.Engine != "postgres" {
		t.Errorf("EndPosition.Engine = %q; want postgres", full.EndPosition.Engine)
	}
	if !strings.Contains(full.EndPosition.Token, `"slot":"sluice_slot"`) {
		t.Errorf("EndPosition.Token = %q; want containing slot=sluice_slot", full.EndPosition.Token)
	}
	if !strings.Contains(full.EndPosition.Token, `"lsn":`) {
		t.Errorf("EndPosition.Token = %q; want containing lsn=", full.EndPosition.Token)
	}
	if full.BackupID == "" {
		t.Error("BackupID empty after EndPosition recording")
	}
	if full.Kind != irbackup.BackupKindFull {
		t.Errorf("Kind = %q; want %q", full.Kind, irbackup.BackupKindFull)
	}
}

// TestStreamer_SyncStart_PositionFromManifest_PG_SlotExists pins acceptance
// criterion 6: a chain restored into a target plus
// `sync start --position-from-manifest` reuses the existing slot to
// resume CDC. The full's recorded EndPosition becomes the resume
// position; the slot is created fresh before CDC starts so its
// restart_lsn covers the chain terminal.
func TestStreamer_SyncStart_PositionFromManifest_PG_SlotExists(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresLogical(t)
	defer cleanup()

	const seedDDL = `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL
		);
		ALTER TABLE users REPLICA IDENTITY FULL;
		INSERT INTO users (email) VALUES ('alice@example.com');
	`
	applyDDL(t, sourceDSN, seedDDL)

	pgEng, _ := engines.Get("postgres")
	dir := t.TempDir()
	store, _ := blobcodec.NewLocalStore(dir)

	// Create publication + slot BEFORE the backup so the slot's
	// restart_lsn covers the EndPosition recorded by the full.
	applyDDL(t, sourceDSN, `CREATE PUBLICATION sluice_pub FOR ALL TABLES`)
	if _, err := createPGLogicalSlotReturningLSN(t, sourceDSN, "sluice_slot"); err != nil {
		t.Fatalf("create slot: %v", err)
	}
	defer dropPGLogicalSlot(t, sourceDSN, "sluice_slot")

	// Take the full — Phase 3.3.A records EndPosition automatically.
	if err := (&Backup{
		Source: pgEng, SourceDSN: sourceDSN, Store: store,
		SluiceVersion: "v0.17.2-test",
		SlotName:      "sluice_slot",
	}).Run(context.Background()); err != nil {
		t.Fatalf("Backup.Run: %v", err)
	}

	// Restore into target (the chain has no incrementals; restore is
	// just the full). After restore, target has alice but the
	// sluice_cdc_state row is absent — that's the surface
	// --position-from-manifest is designed for.
	if err := (&Restore{
		Target: pgEng, TargetDSN: targetDSN, Store: store,
	}).Run(context.Background()); err != nil {
		t.Fatalf("Restore.Run: %v", err)
	}

	// Insert ON SOURCE between backup and sync — these changes must
	// be picked up by the chain handoff, NOT lost.
	applyDDL(t, sourceDSN, `INSERT INTO users (email) VALUES ('bob@example.com'), ('carol@example.com')`)

	// Now run a brief sync with --position-from-manifest.
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	streamer := &Streamer{
		Source:                    pgEng,
		Target:                    pgEng,
		SourceDSN:                 sourceDSN,
		TargetDSN:                 targetDSN,
		StreamID:                  "test-position-from-manifest-pg",
		PositionFromManifestStore: store,
	}
	runErr := make(chan error, 1)
	go func() { runErr <- streamer.Run(ctx) }()
	if !waitForRowCount(t, targetDSN, "users", 3, 20*time.Second) {
		cancel()
		<-runErr
		t.Fatal("target did not reach 3 rows; CDC handoff didn't catch up")
	}
	cancel()
	if err := <-runErr; err != nil && !isContextCanceled(err) {
		t.Fatalf("streamer.Run: %v", err)
	}

	emails := pgQueryEmails(t, targetDSN)
	want := map[string]bool{"alice@example.com": true, "bob@example.com": true, "carol@example.com": true}
	got := map[string]bool{}
	for _, e := range emails {
		got[e] = true
	}
	for w := range want {
		if !got[w] {
			t.Errorf("missing email %q on target; got %v", w, emails)
		}
	}
}

// TestStreamer_SyncStart_PositionFromManifest_PG_SlotMissing_Refuses pins
// acceptance criterion 6's failure mode and 8's headline: when the
// slot named in the chain's terminal position doesn't exist on the
// source, Phase 3.3.C's preflight refuses with a clear error rather
// than silently proceeding to a slot-creation that would advance
// past the chain's terminal LSN and miss data.
func TestStreamer_SyncStart_PositionFromManifest_PG_SlotMissing_Refuses(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresLogical(t)
	defer cleanup()

	applyDDL(t, sourceDSN, `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL
		);
		ALTER TABLE users REPLICA IDENTITY FULL;
		INSERT INTO users (email) VALUES ('alice@example.com');
	`)
	pgEng, _ := engines.Get("postgres")
	dir := t.TempDir()
	store, _ := blobcodec.NewLocalStore(dir)

	// Create slot, take backup, then DROP slot before sync — simulates
	// the "the slot was abandoned long enough that something cleaned
	// it up" case the design doc covers.
	applyDDL(t, sourceDSN, `CREATE PUBLICATION sluice_pub FOR ALL TABLES`)
	if _, err := createPGLogicalSlotReturningLSN(t, sourceDSN, "sluice_slot"); err != nil {
		t.Fatalf("create slot: %v", err)
	}

	if err := (&Backup{
		Source: pgEng, SourceDSN: sourceDSN, Store: store,
		SluiceVersion: "v0.17.2-test", SlotName: "sluice_slot",
	}).Run(context.Background()); err != nil {
		t.Fatalf("Backup.Run: %v", err)
	}
	if err := (&Restore{Target: pgEng, TargetDSN: targetDSN, Store: store}).Run(context.Background()); err != nil {
		t.Fatalf("Restore.Run: %v", err)
	}

	// Drop the slot so the preflight's check 3 trips.
	dropPGLogicalSlot(t, sourceDSN, "sluice_slot")

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	streamer := &Streamer{
		Source:                    pgEng,
		Target:                    pgEng,
		SourceDSN:                 sourceDSN,
		TargetDSN:                 targetDSN,
		StreamID:                  "test-slot-missing",
		PositionFromManifestStore: store,
		SlotName:                  "sluice_slot",
	}
	err := streamer.Run(ctx)
	if err == nil {
		t.Fatal("Streamer.Run: nil; want preflight refusal on missing slot")
	}
	if !strings.Contains(err.Error(), "slot") || !strings.Contains(err.Error(), "does not exist") {
		t.Errorf("err = %v; want refusal naming the missing slot", err)
	}
}

// TestStreamer_SyncStart_PositionFromManifest_PG_StrictPreflight_LowWalKeep
// pins acceptance criterion 9's strict path: a small wal_keep_size on
// a chatty source surfaces as a soft warning under default settings;
// --strict-preflight escalates to a refusal.
//
// The PG containers in startPostgresLogical have wal_keep_size at
// PG's default (which is 0 on PG 13+, then changed to use
// max_slot_wal_keep_size). Setting it explicitly to a small value
// triggers the v0.17.2 threshold.
func TestStreamer_SyncStart_PositionFromManifest_PG_StrictPreflight_LowWalKeep(t *testing.T) {
	sourceDSN, targetDSN, cleanup := startPostgresLogical(t)
	defer cleanup()

	applyDDL(t, sourceDSN, `
		CREATE TABLE users (
			id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email VARCHAR(255) NOT NULL
		);
		ALTER TABLE users REPLICA IDENTITY FULL;
		INSERT INTO users (email) VALUES ('alice@example.com');
	`)
	pgEng, _ := engines.Get("postgres")
	dir := t.TempDir()
	store, _ := blobcodec.NewLocalStore(dir)

	applyDDL(t, sourceDSN, `CREATE PUBLICATION sluice_pub FOR ALL TABLES`)
	if _, err := createPGLogicalSlotReturningLSN(t, sourceDSN, "sluice_slot"); err != nil {
		t.Fatalf("create slot: %v", err)
	}
	defer dropPGLogicalSlot(t, sourceDSN, "sluice_slot")

	if err := (&Backup{
		Source: pgEng, SourceDSN: sourceDSN, Store: store,
		SluiceVersion: "v0.17.2-test", SlotName: "sluice_slot",
	}).Run(context.Background()); err != nil {
		t.Fatalf("Backup.Run: %v", err)
	}
	if err := (&Restore{Target: pgEng, TargetDSN: targetDSN, Store: store}).Run(context.Background()); err != nil {
		t.Fatalf("Restore.Run: %v", err)
	}

	// Force wal_keep_size below the v0.17.2 warn threshold (64 MB).
	// Requires SUPERUSER which the test container's role has.
	applyDDL(t, sourceDSN, `ALTER SYSTEM SET wal_keep_size = '16MB'`)
	applyDDL(t, sourceDSN, `SELECT pg_reload_conf()`)

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	streamer := &Streamer{
		Source:                    pgEng,
		Target:                    pgEng,
		SourceDSN:                 sourceDSN,
		TargetDSN:                 targetDSN,
		StreamID:                  "test-strict-preflight",
		PositionFromManifestStore: store,
		SlotName:                  "sluice_slot",
		StrictPreflight:           true,
	}
	err := streamer.Run(ctx)
	if err == nil {
		t.Fatal("Streamer.Run: nil; want refusal under --strict-preflight + low wal_keep_size")
	}
	if !strings.Contains(err.Error(), "strict-preflight") {
		t.Errorf("err = %v; want refusal under --strict-preflight surface", err)
	}
}

// TestStreamer_Preflight_PG_DetectsLowWalKeepSize confirms the preflight
// query side: a low wal_keep_size on the source produces a warning
// (without StrictPreflight, the warning logs but the run proceeds).
// We exercise the preflight directly via the SchemaReader surface so
// the test doesn't have to wait for a CDC stream.
func TestStreamer_Preflight_PG_DetectsLowWalKeepSize(t *testing.T) {
	sourceDSN, _, cleanup := startPostgresLogical(t)
	defer cleanup()

	// Set wal_keep_size below the v0.17.2 warn threshold.
	db, err := sql.Open("pgx", sourceDSN)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer func() { _ = db.Close() }()
	if _, err := db.ExecContext(context.Background(), `ALTER SYSTEM SET wal_keep_size = '16MB'`); err != nil {
		t.Fatalf("set wal_keep_size: %v", err)
	}
	if _, err := db.ExecContext(context.Background(), `SELECT pg_reload_conf()`); err != nil {
		t.Fatalf("reload: %v", err)
	}

	pgEng, _ := engines.Get("postgres")
	sr, err := pgEng.OpenSchemaReader(context.Background(), sourceDSN)
	if err != nil {
		t.Fatalf("OpenSchemaReader: %v", err)
	}
	defer closeIf(sr)

	preflighter, ok := sr.(PositionFromManifestPreflight)
	if !ok {
		t.Fatal("PG SchemaReader does not implement PositionFromManifestPreflight")
	}
	chainPos := ir.Position{Engine: "postgres", Token: `{"slot":"sluice_slot","lsn":"0/100"}`}
	report, err := preflighter.PreflightPositionFromManifest(context.Background(), chainPos, "sluice_slot")
	if err != nil {
		t.Fatalf("PreflightPositionFromManifest: %v", err)
	}
	// Slot doesn't exist on a fresh PG; expect a refusal naming the
	// missing slot, plus a wal_keep warning.
	if report.Refusal == "" {
		t.Errorf("expected refusal for missing slot; got empty Refusal, warnings=%v", report.Warnings)
	}
	if !strings.Contains(report.Refusal, "does not exist") {
		t.Errorf("refusal = %q; want 'does not exist'", report.Refusal)
	}
	var sawWalKeep bool
	for _, w := range report.Warnings {
		if strings.Contains(w, "wal_keep_size") {
			sawWalKeep = true
		}
	}
	if !sawWalKeep {
		t.Errorf("expected wal_keep_size warning; got %v", report.Warnings)
	}
}

// TestStreamer_Preflight_PG_DetectsPhysicalSlot confirms Bug 36 (v0.17.3)
// Signal 4: a non-temporary physical replication slot on the source
// is detected as an HA-cluster signal. Most non-HA PG deployments
// don't carry standby physical slots, so the presence of one is a
// strong heuristic — and it covers managed-PG services where the
// v0.17.2 SQL signals (Patroni-prefixed GUCs / pg_stat_replication /
// patroni-named roles) all systematically miss.
func TestStreamer_Preflight_PG_DetectsPhysicalSlot(t *testing.T) {
	sourceDSN, _, cleanup := startPostgresLogical(t)
	defer cleanup()

	db, err := sql.Open("pgx", sourceDSN)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer func() { _ = db.Close() }()

	// Create a non-temporary physical replication slot to simulate
	// the HA-cluster shape.
	if _, err := db.ExecContext(
		context.Background(),
		`SELECT pg_create_physical_replication_slot('sluice_test_phys_slot', false, false)`,
	); err != nil {
		t.Fatalf("create physical slot: %v", err)
	}
	defer func() {
		_, _ = db.ExecContext(context.Background(),
			`SELECT pg_drop_replication_slot('sluice_test_phys_slot')`)
	}()

	pgEng, _ := engines.Get("postgres")
	sr, err := pgEng.OpenSchemaReader(context.Background(), sourceDSN)
	if err != nil {
		t.Fatalf("OpenSchemaReader: %v", err)
	}
	defer closeIf(sr)

	preflighter, ok := sr.(PositionFromManifestPreflight)
	if !ok {
		t.Fatal("PG SchemaReader does not implement PositionFromManifestPreflight")
	}
	chainPos := ir.Position{Engine: "postgres", Token: `{"slot":"sluice_slot","lsn":"0/100"}`}
	report, err := preflighter.PreflightPositionFromManifest(context.Background(), chainPos, "sluice_slot")
	if err != nil {
		t.Fatalf("PreflightPositionFromManifest: %v", err)
	}
	var sawPatroni bool
	for _, w := range report.Warnings {
		if strings.HasPrefix(w, "this PG cluster is HA-managed") {
			sawPatroni = true
			if !strings.Contains(w, "physical replication slots") {
				t.Errorf("Patroni warning = %q; want 'physical replication slots' substring", w)
			}
		}
	}
	if !sawPatroni {
		t.Errorf("expected Patroni warning citing physical slot; got %v", report.Warnings)
	}
}

// TestStreamer_Preflight_PG_DetectsClusterNameGUC confirms Bug 36 (v0.17.3)
// Signal 5: a populated cluster_name GUC on the source is detected as
// an HA-managed-convention signal. Patroni sets this; many managed
// services do too. This signal catches managed-PG services where
// pg_replication_slots is restricted (so Signal 4 misses) but
// cluster_name is exposed via pg_settings.
//
// cluster_name is a postmaster-context GUC: it can only be set at
// server startup, not via ALTER SYSTEM + reload. The test boots a
// dedicated container with cluster_name passed as a server arg.
func TestStreamer_Preflight_PG_DetectsClusterNameGUC(t *testing.T) {
	sourceDSN, cleanup := startPostgresLogicalWithClusterName(t, "sluice-test-cluster")
	defer cleanup()

	pgEng, _ := engines.Get("postgres")
	sr, err := pgEng.OpenSchemaReader(context.Background(), sourceDSN)
	if err != nil {
		t.Fatalf("OpenSchemaReader: %v", err)
	}
	defer closeIf(sr)

	preflighter, ok := sr.(PositionFromManifestPreflight)
	if !ok {
		t.Fatal("PG SchemaReader does not implement PositionFromManifestPreflight")
	}
	chainPos := ir.Position{Engine: "postgres", Token: `{"slot":"sluice_slot","lsn":"0/100"}`}
	report, err := preflighter.PreflightPositionFromManifest(context.Background(), chainPos, "sluice_slot")
	if err != nil {
		t.Fatalf("PreflightPositionFromManifest: %v", err)
	}
	var sawPatroni bool
	for _, w := range report.Warnings {
		if strings.HasPrefix(w, "this PG cluster is HA-managed") {
			sawPatroni = true
			if !strings.Contains(w, "cluster_name") {
				t.Errorf("Patroni warning = %q; want 'cluster_name' substring", w)
			}
			if !strings.Contains(w, "sluice-test-cluster") {
				t.Errorf("Patroni warning = %q; want cluster_name value substring", w)
			}
		}
	}
	if !sawPatroni {
		t.Errorf("expected Patroni warning citing cluster_name; got %v", report.Warnings)
	}
}

// startPostgresLogicalWithClusterName boots a single PG container
// (no separate target) with cluster_name set at startup via a -c
// flag, returning the source DSN and a cleanup. Mirror of
// startPostgresLogical but specialised for the postmaster-context
// GUC test (cluster_name can only be set at server start).
func startPostgresLogicalWithClusterName(t *testing.T, clusterName string) (sourceDSN string, cleanup func()) {
	t.Helper()
	testcontainers.SkipIfProviderIsNotHealthy(t)

	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()

	container, err := pgtc.Run(
		ctx,
		// Task #68: pre-baked PG image. See
		// pg_prebaked_integration_test.go for the full rationale.
		pgPrebakedImage,
		pgtc.WithDatabase("source_db"),
		pgtc.WithUsername("test"),
		pgtc.WithPassword("test"),
		pgtc.BasicWaitStrategies(),
		pgPrebakedWaitStrategy(),
		testcontainers.CustomizeRequest(testcontainers.GenericContainerRequest{
			ContainerRequest: testcontainers.ContainerRequest{
				Cmd: []string{
					"-c", "wal_level=logical",
					"-c", "max_wal_senders=8",
					"-c", "max_replication_slots=8",
					"-c", "cluster_name=" + clusterName,
				},
			},
		}),
	)
	if err != nil {
		t.Fatalf("start container: %v", err)
	}
	terminate := func() {
		shutdown, c := context.WithTimeout(context.Background(), 30*time.Second)
		defer c()
		_ = container.Terminate(shutdown)
	}
	srcConn, err := container.ConnectionString(ctx, "sslmode=disable")
	if err != nil {
		terminate()
		t.Fatalf("connection string: %v", err)
	}
	return srcConn, terminate
}

// TestStreamer_SyncStart_PatroniMode_Off_SuppressesWarning confirms Bug 36
// (v0.17.3) override: --patroni-mode=off skips the Patroni-detection
// signals entirely and suppresses the warning, even when a heuristic
// would fire. Other warnings (wal_keep_size) are unaffected.
func TestStreamer_SyncStart_PatroniMode_Off_SuppressesWarning(t *testing.T) {
	sourceDSN, _, cleanup := startPostgresLogical(t)
	defer cleanup()

	db, err := sql.Open("pgx", sourceDSN)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer func() { _ = db.Close() }()

	// Trip Signal 4: create a non-temporary physical replication slot.
	if _, err := db.ExecContext(
		context.Background(),
		`SELECT pg_create_physical_replication_slot('sluice_test_phys_off', false, false)`,
	); err != nil {
		t.Fatalf("create physical slot: %v", err)
	}
	defer func() {
		_, _ = db.ExecContext(context.Background(),
			`SELECT pg_drop_replication_slot('sluice_test_phys_off')`)
	}()

	pgEng, _ := engines.Get("postgres")
	sr, err := pgEng.OpenSchemaReader(context.Background(), sourceDSN)
	if err != nil {
		t.Fatalf("OpenSchemaReader: %v", err)
	}
	defer closeIf(sr)
	preflighter := sr.(PositionFromManifestPreflight)
	chainPos := ir.Position{Engine: "postgres", Token: `{"slot":"sluice_slot","lsn":"0/100"}`}
	engineReport, err := preflighter.PreflightPositionFromManifest(context.Background(), chainPos, "sluice_slot")
	if err != nil {
		t.Fatalf("PreflightPositionFromManifest: %v", err)
	}

	// Streamer-level: applyPatroniMode under "off" should strip every
	// Patroni warning the engine emitted.
	s := &Streamer{SourceDSN: sourceDSN, PatroniMode: PatroniModeOff}
	final := s.applyPatroniMode(engineReport, PatroniModeOff)
	for _, w := range final.Warnings {
		if strings.HasPrefix(w, "this PG cluster is HA-managed") {
			t.Errorf("--patroni-mode=off did not suppress warning: %q", w)
		}
	}
}

// TestStreamer_SyncStart_PatroniMode_On_FiresOnVanilla confirms Bug 36
// (v0.17.3) override: --patroni-mode=on emits the Patroni warning
// even on a vanilla PG container with no Patroni signals (no GUCs,
// no pg_stat_replication entries, no patroni-named roles, no
// physical slots, no cluster_name set).
func TestStreamer_SyncStart_PatroniMode_On_FiresOnVanilla(t *testing.T) {
	sourceDSN, _, cleanup := startPostgresLogical(t)
	defer cleanup()

	pgEng, _ := engines.Get("postgres")
	sr, err := pgEng.OpenSchemaReader(context.Background(), sourceDSN)
	if err != nil {
		t.Fatalf("OpenSchemaReader: %v", err)
	}
	defer closeIf(sr)
	preflighter := sr.(PositionFromManifestPreflight)
	chainPos := ir.Position{Engine: "postgres", Token: `{"slot":"sluice_slot","lsn":"0/100"}`}
	engineReport, err := preflighter.PreflightPositionFromManifest(context.Background(), chainPos, "sluice_slot")
	if err != nil {
		t.Fatalf("PreflightPositionFromManifest: %v", err)
	}
	// Confirm vanilla PG didn't trip any engine-side Patroni signals
	// — the test's surface depends on it.
	for _, w := range engineReport.Warnings {
		if strings.HasPrefix(w, "this PG cluster is HA-managed") {
			t.Fatalf("vanilla PG unexpectedly tripped a Patroni signal: %q", w)
		}
	}

	s := &Streamer{SourceDSN: sourceDSN, PatroniMode: PatroniModeOn}
	final := s.applyPatroniMode(engineReport, PatroniModeOn)
	var sawForced bool
	for _, w := range final.Warnings {
		if strings.HasPrefix(w, "this PG cluster is HA-managed") {
			sawForced = true
			if !strings.Contains(w, "operator forced") {
				t.Errorf("warning = %q; want 'operator forced' substring", w)
			}
		}
	}
	if !sawForced {
		t.Errorf("--patroni-mode=on did not emit forced warning; got %v", final.Warnings)
	}
}

// isContextCanceled reports whether err is a context-cancellation
// error. The streamer's Run path returns nil on clean ctx cancel
// in most cases; on the inner channel races, it can surface a
// wrapped context.Canceled.
func isContextCanceled(err error) bool {
	if err == nil {
		return false
	}
	return strings.Contains(err.Error(), "context canceled") ||
		strings.Contains(err.Error(), "context deadline exceeded")
}
