// Copyright 2026 Omar Ramos
// SPDX-License-Identifier: Apache-2.0

// The [Column.Identity] wire contract (gap census 2026-09-22 S4/S5). A
// backup manifest is a codec: every value the field can carry must
// round-trip exact, and a manifest written BEFORE the field existed must
// decode to the value the writing binary implied — nil, which the
// Postgres writer renders as the bare `GENERATED BY DEFAULT AS IDENTITY`
// that binary emitted.

package ir

import (
	"encoding/json"
	"testing"
)

// TestColumnJSON_IdentityRoundTrip pins the field-present direction over
// every shape the reader can produce: ALWAYS with every option
// non-default (a descending, cycling, cached sharded identity), BY
// DEFAULT with factory defaults, and an option legitimately at ZERO
// (START WITH 0 under MINVALUE 0), which `omitempty` drops on the wire
// and which must still decode as 0 — the case a "non-zero only" pin
// would never see.
func TestColumnJSON_IdentityRoundTrip(t *testing.T) {
	cases := []struct {
		name string
		id   *IdentityOptions
	}{
		{"ALWAYS, every option non-default", &IdentityOptions{Always: true, Start: 3, Increment: 10, MinValue: -5, MaxValue: 1000, Cache: 50, Cycle: true}},
		{"BY DEFAULT, factory defaults", &IdentityOptions{Start: 1, Increment: 1, MinValue: 1, MaxValue: 9223372036854775807, Cache: 1}},
		{"START WITH 0 under MINVALUE 0", &IdentityOptions{Always: true, Start: 0, Increment: 1, MinValue: 0, MaxValue: 2147483647, Cache: 1}},
		{"descending", &IdentityOptions{Start: -1, Increment: -1, MinValue: -9223372036854775808, MaxValue: -1, Cache: 1}},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			original := &Column{Name: "id", Type: Integer{Width: 64, AutoIncrement: true}, Identity: tc.id}
			b, err := json.Marshal(original)
			if err != nil {
				t.Fatalf("Marshal: %v", err)
			}
			var got Column
			if err := json.Unmarshal(b, &got); err != nil {
				t.Fatalf("Unmarshal: %v", err)
			}
			if got.Identity == nil {
				t.Fatalf("Identity decoded nil from %s", b)
			}
			if *got.Identity != *tc.id {
				t.Errorf("Identity round-trip = %+v; want %+v (wire: %s)", *got.Identity, *tc.id, b)
			}
		})
	}
}

// TestUnmarshalColumn_OldWireLeavesIdentityNil is the pre-field manifest
// direction: a column written by a binary that predates Identity carries
// no "identity" key and must decode nil — never a zero-valued struct,
// which the emitter would render as `START WITH 0 INCREMENT BY 0 …`.
func TestUnmarshalColumn_OldWireLeavesIdentityNil(t *testing.T) {
	const oldWire = `{"name":"id","type":{"kind":"Integer","width":64,"auto_increment":true},"nullable":false}`
	var got Column
	if err := json.Unmarshal([]byte(oldWire), &got); err != nil {
		t.Fatalf("Unmarshal: %v", err)
	}
	if got.Identity != nil {
		t.Errorf("an older manifest decoded Identity = %+v; want nil — a restore would render options the writing binary never carried", *got.Identity)
	}
	intT, ok := got.Type.(Integer)
	if !ok || !intT.AutoIncrement {
		t.Errorf("Type = %#v; want an AutoIncrement Integer (the pre-field carry must be untouched)", got.Type)
	}
	// A nil Identity must also stay OFF the wire, so a re-marshalled old
	// manifest gains no key on this field.
	b, err := json.Marshal(&got)
	if err != nil {
		t.Fatalf("Marshal: %v", err)
	}
	var keys map[string]json.RawMessage
	if err := json.Unmarshal(b, &keys); err != nil {
		t.Fatalf("re-decode: %v", err)
	}
	if _, present := keys["identity"]; present {
		t.Errorf("re-marshalled old wire grew an identity key: %s", b)
	}
}
