-- Kitchen-sink seed v1 for the restore-parity oracle (roadmap item 51).
--
-- Feature checklist (one line per class, keep in sync with the
-- expected-object-count consts in migrate_dump_parity_integration_test.go):
--   * enum type + column with enum default        (order_status)
--   * domain + column                             (email_address)
--   * STORED generated column                     (orders.total_cents)
--   * identity columns                            (every table's id)
--   * explicit standalone sequence + nextval def  (order_number_seq)
--   * UNIQUE constraint                           (customers_email_unique)
--   * named CHECK constraint                      (orders_subtotal_positive)
--   * FK ON DELETE CASCADE                        (orders_customer_fk)
--   * FK ON DELETE SET NULL                       (shipments_order_fk)
--   * EXCLUDE constraint (core gist, no ext)      (bookings_no_overlap)
--   * partial index                               (orders_active_idx)
--   * expression index                            (customers_email_lower_idx)
--   * table + column COMMENTs                     (customers)
--   * non-default libc collation                  (customers.region_code, "C")
--   * partitioned table, range, 2 partitions      (events) — EXCLUDED from
--     the sluice leg via TableFilter: Bug 100 refuses partitioned parents
--     loudly, so the family shows up oracle-side only (allowlisted).
--
-- Deliberately absent in v1 (documented limitations, not oversights):
-- functions / procedures / triggers (dollar-quoted bodies; user
-- triggers are roadmap item 50) and extension types (the optional
-- extension legs are a follow-up per the roadmap entry).

CREATE TYPE order_status AS ENUM ('pending', 'paid', 'shipped', 'cancelled');

CREATE DOMAIN email_address AS TEXT
    CHECK (VALUE ~ '^[^@]+@[^@]+$');

CREATE SEQUENCE order_number_seq START WITH 1000 INCREMENT BY 5;

CREATE TABLE customers (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       email_address NOT NULL,
    full_name   TEXT NOT NULL,
    region_code TEXT COLLATE "C" NOT NULL DEFAULT 'zz',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT customers_email_unique UNIQUE (email)
);
COMMENT ON TABLE customers IS 'Registered customers';
COMMENT ON COLUMN customers.region_code IS 'ISO region code, byte-order collation';

CREATE INDEX customers_email_lower_idx ON customers (lower((email)::text));

CREATE TABLE orders (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number   BIGINT NOT NULL DEFAULT nextval('order_number_seq'),
    customer_id    BIGINT NOT NULL,
    status         order_status NOT NULL DEFAULT 'pending',
    subtotal_cents BIGINT NOT NULL,
    tax_cents      BIGINT NOT NULL DEFAULT 0,
    total_cents    BIGINT GENERATED ALWAYS AS (subtotal_cents + tax_cents) STORED,
    placed_on      DATE NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT orders_customer_fk FOREIGN KEY (customer_id)
        REFERENCES customers (id) ON DELETE CASCADE,
    CONSTRAINT orders_subtotal_positive CHECK (subtotal_cents >= 0)
);

CREATE INDEX orders_active_idx ON orders (customer_id) WHERE status <> 'cancelled';

CREATE TABLE shipments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT,
    carrier    VARCHAR(64) NOT NULL,
    shipped_at TIMESTAMPTZ,
    CONSTRAINT shipments_order_fk FOREIGN KEY (order_id)
        REFERENCES orders (id) ON DELETE SET NULL
);

CREATE INDEX shipments_order_id_idx ON shipments (order_id);

CREATE TABLE bookings (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL,
    during  int8range NOT NULL,
    CONSTRAINT bookings_no_overlap EXCLUDE USING gist (during WITH &&)
);

CREATE TABLE events (
    id          BIGINT NOT NULL,
    happened_at TIMESTAMPTZ NOT NULL,
    payload     TEXT,
    PRIMARY KEY (id, happened_at)
) PARTITION BY RANGE (happened_at);

CREATE TABLE events_2026h1 PARTITION OF events
    FOR VALUES FROM ('2026-01-01') TO ('2026-07-01');
CREATE TABLE events_2026h2 PARTITION OF events
    FOR VALUES FROM ('2026-07-01') TO ('2027-01-01');

-- A few rows so the sluice leg exercises the realistic migrate path
-- (schema + bulk copy); the parity comparison itself is schema-only.
INSERT INTO customers (email, full_name, region_code) VALUES
    ('alice@example.com', 'Alice Example', 'us'),
    ('bob@example.com',   'Bob Example',   'mx');

INSERT INTO orders (customer_id, status, subtotal_cents, tax_cents) VALUES
    (1, 'paid',    12500, 1000),
    (2, 'pending',  9900,    0);

INSERT INTO shipments (order_id, carrier, shipped_at) VALUES
    (1, 'DHL', now());

INSERT INTO bookings (room_id, during) VALUES
    (7, int8range(100, 200));

INSERT INTO events (id, happened_at, payload) VALUES
    (1, '2026-02-01T00:00:00Z', 'h1'),
    (2, '2026-08-01T00:00:00Z', 'h2');
