-- Kitchen-sink seed v1 for the restore-parity oracle (roadmap item 51).
--
-- Feature checklist (one line per class, keep in sync with the
-- expected-object-count consts in migrate_dump_parity_integration_test.go):
--   * enum type + column with enum default        (order_status)
--   * domain + column                             (email_address)
--   * STORED generated column                     (orders.total_cents)
--   * identity columns                            (every table's id)
--   * explicit standalone sequence + nextval def  (order_number_seq —
--     carried at FULL parity since the item-51 finding-#1 fix)
--   * classic serial column                       (legacy_counters.id —
--     deliberately modernized to identity; allowlisted, cited to
--     docs/type-mapping.md "Sequences and serial columns")
--   * UNIQUE constraints (TRIAGE #4 closed)       (customers_email_unique,
--     orders_order_number_unique) — carried as ADD CONSTRAINT, not
--     demoted to unique indexes
--   * UNIQUE NULLS NOT DISTINCT (PG 15+)          (customers_extref_nnd) —
--     lands plain UNIQUE (the C3 read-time WARN names the weakening);
--     the mismatch is a cited allowlist entry until the faithful-carry
--     follow-up ships (roadmap "UNIQUE-constraint attribute fidelity")
--   * plain UNIQUE INDEX (stays an index)         (shipments_order_carrier_uidx)
--   * temporal precision shapes (TRIAGE #3)       (shipments: bare timestamptz,
--     timestamptz(0), timestamptz(6), timestamp(3), time(4), timetz(2))
--   * named CHECK constraint                      (orders_subtotal_positive)
--   * FK ON DELETE CASCADE                        (orders_customer_fk)
--   * FK ON DELETE SET NULL                       (shipments_order_fk)
--   * EXCLUDE constraint (core gist, no ext)      (bookings_no_overlap)
--   * partial index                               (orders_active_idx)
--   * expression index                            (customers_email_lower_idx)
--   * table + column COMMENTs                     (customers)
--   * non-default libc collation                  (customers.region_code, "C")
--   * partitioned table, range, 2 partitions      (events) — EXCLUDED from
--     the sluice leg via TableFilter: Bug 100 refuses partitioned parents
--     loudly, so the family shows up oracle-side only (allowlisted).
--
-- Deliberately absent in v1 (documented limitations, not oversights):
-- functions / procedures / triggers (dollar-quoted bodies; user
-- triggers are roadmap item 50) and extension types (the optional
-- extension legs are a follow-up per the roadmap entry).

CREATE TYPE order_status AS ENUM ('pending', 'paid', 'shipped', 'cancelled');

CREATE DOMAIN email_address AS TEXT
    CHECK (VALUE ~ '^[^@]+@[^@]+$');

CREATE SEQUENCE order_number_seq START WITH 1000 INCREMENT BY 5;

CREATE TABLE customers (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email        email_address NOT NULL,
    full_name    TEXT NOT NULL,
    region_code  TEXT COLLATE "C" NOT NULL DEFAULT 'zz',
    external_ref TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT customers_email_unique UNIQUE (email),
    CONSTRAINT customers_extref_nnd UNIQUE NULLS NOT DISTINCT (external_ref)
);
COMMENT ON TABLE customers IS 'Registered customers';
COMMENT ON COLUMN customers.region_code IS 'ISO region code, byte-order collation';

CREATE INDEX customers_email_lower_idx ON customers (lower((email)::text));

CREATE TABLE orders (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number   BIGINT NOT NULL DEFAULT nextval('order_number_seq')
        CONSTRAINT orders_order_number_unique UNIQUE,
    customer_id    BIGINT NOT NULL,
    status         order_status NOT NULL DEFAULT 'pending',
    subtotal_cents BIGINT NOT NULL,
    tax_cents      BIGINT NOT NULL DEFAULT 0,
    total_cents    BIGINT GENERATED ALWAYS AS (subtotal_cents + tax_cents) STORED,
    placed_on      DATE NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT orders_customer_fk FOREIGN KEY (customer_id)
        REFERENCES customers (id) ON DELETE CASCADE,
    CONSTRAINT orders_subtotal_positive CHECK (subtotal_cents >= 0)
);

CREATE INDEX orders_active_idx ON orders (customer_id) WHERE status <> 'cancelled';

-- shipments doubles as the temporal-precision matrix (TRIAGE #3):
-- bare timestamptz (typmod -1, the engine-default 6-behaving form)
-- must round-trip BARE — not materialize as (6) — while every
-- explicitly declared precision (including 0) must round-trip
-- explicit, across the tz / non-tz / time-of-day family members.
CREATE TABLE shipments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT,
    carrier      VARCHAR(64) NOT NULL,
    shipped_at   TIMESTAMPTZ,
    delivered_at TIMESTAMPTZ(0),
    audited_at   TIMESTAMPTZ(6),
    eta          TIMESTAMP(3),
    pickup_after TIME(4),
    pickup_tz    TIME(2) WITH TIME ZONE,
    CONSTRAINT shipments_order_fk FOREIGN KEY (order_id)
        REFERENCES orders (id) ON DELETE SET NULL
);

CREATE INDEX shipments_order_id_idx ON shipments (order_id);

-- A PLAIN unique index (no owning constraint): must round-trip as
-- CREATE UNIQUE INDEX, NOT get promoted to a table constraint — the
-- symmetric half of the TRIAGE #4 constraint-vs-index distinction.
CREATE UNIQUE INDEX shipments_order_carrier_uidx ON shipments (order_id, carrier);

CREATE TABLE bookings (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL,
    during  int8range NOT NULL,
    CONSTRAINT bookings_no_overlap EXCLUDE USING gist (during WITH &&)
);

-- Classic serial column: the ONE shape sluice deliberately rewrites
-- (serial → identity modernization; docs/type-mapping.md "Sequences
-- and serial columns"). No column defaults besides the serial so the
-- only oracle deltas for this table are the documented serial trio.
CREATE TABLE legacy_counters (
    id   SERIAL PRIMARY KEY,
    hits BIGINT NOT NULL
);

CREATE TABLE events (
    id          BIGINT NOT NULL,
    happened_at TIMESTAMPTZ NOT NULL,
    payload     TEXT,
    PRIMARY KEY (id, happened_at)
) PARTITION BY RANGE (happened_at);

CREATE TABLE events_2026h1 PARTITION OF events
    FOR VALUES FROM ('2026-01-01') TO ('2026-07-01');
CREATE TABLE events_2026h2 PARTITION OF events
    FOR VALUES FROM ('2026-07-01') TO ('2027-01-01');

-- A few rows so the sluice leg exercises the realistic migrate path
-- (schema + bulk copy); the parity comparison itself is schema-only.
-- Exactly ONE NULL external_ref: customers_extref_nnd is NULLS NOT
-- DISTINCT, so a second NULL row would (correctly) violate it.
INSERT INTO customers (email, full_name, region_code, external_ref) VALUES
    ('alice@example.com', 'Alice Example', 'us', 'ext-1001'),
    ('bob@example.com',   'Bob Example',   'mx', NULL);

INSERT INTO orders (customer_id, status, subtotal_cents, tax_cents) VALUES
    (1, 'paid',    12500, 1000),
    (2, 'pending',  9900,    0);

INSERT INTO shipments (order_id, carrier, shipped_at, delivered_at, audited_at, eta, pickup_after, pickup_tz) VALUES
    (1, 'DHL', now(), now(), now(), now(), '10:11:12.12345', '10:11:12.12+02');

INSERT INTO bookings (room_id, during) VALUES
    (7, int8range(100, 200));

INSERT INTO legacy_counters (hits) VALUES (41), (42);

INSERT INTO events (id, happened_at, payload) VALUES
    (1, '2026-02-01T00:00:00Z', 'h1'),
    (2, '2026-08-01T00:00:00Z', 'h2');
